force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l&apos;oggetto Vendita</description>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di Fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_OrderItemTst.cls
/**
* @author Lucas da Silva Fernandes (lucas.dasilva@engdb.com.br)
* @date 04/08/2021
* @description HDT_QR_OrderItem Test Class
* @history Lucas da Silva Fernandes – 04/08/2021 – Created Class
*/

@isTest
public with sharing class HDT_QR_OrderItemTst {
    
    @TestSetup
    static void setup(){
        
        HDT_UTL_DataFactoryTst.pClickInstance();
        
        HDT_UTL_DataFactoryTst.pClickOrderPhase();
        
        List<Account> acc = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<Opportunity> opp = HDT_UTL_DataFactoryTst.createOpportunity(1, true);
        List<Sale__c> sales = HDT_UTL_DataFactoryTst.createSale(1, true, acc[0].Id, 'Bozza');
        List<Order> orders = HDT_UTL_DataFactoryTst.createOrder(1, false, acc[0].Id, sales[0].Id);
        orders[0].Phase__c = 'Bozza';
        
        insert orders;
        
        List<SBQQ__Quote__c> quotes = HDT_UTL_DataFactoryTst.createQuote(1, true, orders[0].Id, opp[0].Id, sales[0].Id, 'Amendment');
        
        orders[0].SBQQ__Quote__c = quotes[0].Id;
        update orders;
        
        List<Product2> prod = HDT_UTL_DataFactoryTst.createProduct2(1, false);
        prod[0].Name = 'PDR';
        prod[0].Family = 'VAS Opzione prodotto';
        
        insert prod;
        
        Id pricebookId=Test.getStandardPricebookId();
        
        List<PricebookEntry> pbEntry = HDT_UTL_DataFactoryTst.createPricebookEntry(prod, true, pricebookId);
        
        orders[0].Pricebook2Id = pricebookId;
        update orders;
        
        List<ServicePoint__c> spList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        
        List<BillingProfile__c> bp =  HDT_UTL_DataFactoryTst.createBillingProfile(1, true, acc[0].Id);
        
        List<OrderItem> oiList = HDT_UTL_DataFactoryTst.createOrderItem(1, false, orders[0].Id, spList[0].Id, prod[0].Id, pbEntry[0].Id);
        oiList[0].BillingProfile__c = bp[0].Id;
        insert oiList;
        
    }
    
    @isTest
    public static void testGetRecordsByOrderIdListFilteredPdrPod() {
        
        Test.startTest();
        
        Id orderId = [SELECT Id FROM Order WHERE Order.Phase__c = 'Bozza'].Id;
        
        List<Id> orderIds = new List<Id>();
        orderIds.add(orderId);
        
        List<OrderItem> oiList = new List<OrderItem>();
        
        HDT_QR_OrderItem qrOi = new HDT_QR_OrderItem();
        
        oiList = qrOi.getRecordsByOrderIdListFilteredPdrPod(orderIds);
        
        System.assertEquals(orderId, oiList[0].OrderId, 'Order IDs match.');
        System.assertNotEquals(orderId, null, 'Order IDs mismatch.');
        
        Test.stopTest();
    }
    
    @isTest
    public static void testGetRecordsByOrderIdFilteredPdrPod() {
        
        Test.startTest();
        
        String orderId = String.valueOf([SELECT Id FROM Order WHERE Order.Phase__c = 'Bozza'].Id);
        
        List<OrderItem> oiList = new List<OrderItem>();
        
        System.debug('Order IDs: '+ orderId);
        
        HDT_QR_OrderItem qrOi = new HDT_QR_OrderItem();
        
        oiList = qrOi.getRecordsByOrderIdFilteredPdrPod(orderId);
        
        System.debug('oiList: '+ oiList);
        
        System.assertEquals(orderId, String.valueOf(oiList[0].OrderId), 'Order IDs match.');
        System.assertNotEquals(orderId, null, 'Order IDs mismatch.');
        
        Test.stopTest();
    }
    
    @isTest
    public static void testGetRecordsWithBillingProfile() {
        
        Test.startTest();
        
        Id orderId = [SELECT Id FROM Order].Id;
        
        List<Id> orderIds = new List<Id>();
        orderIds.add(orderId);
        
        List<OrderItem> oiList = new List<OrderItem>();
        
        HDT_QR_OrderItem qrOi = new HDT_QR_OrderItem();
        
        oiList = qrOi.getRecordsWithBillingProfile(orderIds);
        
        System.assertEquals(orderId, oiList[0].OrderId, 'Order IDs match.');
        System.assertNotEquals(orderId, null, 'Order IDs mismatch.');
        
        Test.stopTest();
    }
    
    @isTest
    public static void testGetRecordsWithAmend() {
        
        Test.startTest();
        
        Id orderId = [SELECT Id FROM Order].Id;
        
        System.debug('orderId: '+orderId);
        
        List<Id> orderIds = new List<Id>();
        orderIds.add(orderId);
        
        List<OrderItem> oiList = new List<OrderItem>();
        
        HDT_QR_OrderItem qrOi = new HDT_QR_OrderItem();
        
        oiList = qrOi.getRecordsWithAmend(orderIds);
        
        System.debug('oiList: '+oiList);
        
        System.assertEquals(orderId, oiList[0].OrderId, 'Order IDs match.');
        System.assertNotEquals(orderId, null, 'Order IDs mismatch.');
        
        Test.stopTest();
    }
    
    // @isTest
    // public static void testGetMainItem() {
        
    //     Test.startTest();
        
    //     String orderId = String.valueOf([SELECT Id FROM Order].Id);
        
    //     List<OrderItem> oiList = new List<OrderItem>();
        
    //     System.debug('Order IDs: '+ orderId);
        
    //     HDT_QR_OrderItem qrOi = new HDT_QR_OrderItem();
        
    //     oiList = qrOi.getMainItem(orderId);
        
    //     System.debug('oiList: '+ oiList);
        
    //     System.assertEquals(orderId, String.valueOf(oiList[0].OrderId), 'Order IDs match.');
    //     System.assertNotEquals(orderId, null, 'Order IDs mismatch.');
        
    //     Test.stopTest();
    // }
    
    @isTest
    public static void testGetAnalisiConsumi() {
        
        Test.startTest();
        
        Product2 prod = [SELECT Id, Name, Family FROM Product2];
        prod.Family = 'VAS Fatturabili';
        update prod;
        
        List<Order> orderList = [SELECT Id FROM Order LIMIT 1];
        HDT_QR_OrderItem qrOi = new HDT_QR_OrderItem();
        List<OrderItem> oiList = qrOi.getAnalisiConsumi(orderList[0].Id);
        
        System.assertEquals(orderList[0].Id, String.valueOf(oiList[0].OrderId), 'Order IDs match.');
        System.assertNotEquals(orderList[0].Id, null, 'Order IDs mismatch.');
        
        Test.stopTest();
    }
    @isTest
    public static void testGetRecordsByOrderIdFilteredFamilyBonus() {
        
        
        
        Test.startTest();
        
        Id orderId = [SELECT Id FROM Order LIMIT 1].Id;
        
        List<Id> orderIds = new List<Id>();
        orderIds.add(orderId);
        
        List<OrderItem> oiList = new List<OrderItem>();
        
        HDT_QR_OrderItem qrOi = new HDT_QR_OrderItem();
        
        oiList = qrOi.getRecordsByOrderIdFilteredFamilyBonus(orderIds);
        
        
        System.assertNotEquals(orderId, null, 'Order IDs mismatch.');
        
        Test.stopTest();
    }
    
    
    
    
    @isTest
    public static void testGetItemFromOrderIdList() {
        
        
        
        Test.startTest();
        
        Id orderId = [SELECT Id FROM Order LIMIT 1].Id;
        
        List<Id> orderIds = new List<Id>();
        orderIds.add(orderId);
        
        List<OrderItem> oiList = new List<OrderItem>();
        
        oiList = HDT_QR_OrderItem.getItemFromOrderIdList(orderIds);
        
        
        System.assertNotEquals(oiList[0].OrderId, null, 'Order IDs mismatch.');
        
        Test.stopTest();
    }
    
    
    @isTest
    public static void testGetPodOrderFromQuote() {
        
        
        Test.startTest();
        List<OrderItem> qrOi = new List<OrderItem>();
        qrOi = [
            SELECT
            OrderId,
            Order.SBQQ__Quote__c,
            Order.ServicePoint__r.ServicePointCode__c,
            Order.ServicePoint__c
            FROM
            OrderItem LIMIT 1];
        
        
        List<OrderItem> oiList = new List<OrderItem>();
        HDT_QR_OrderItem qrOi1 = new HDT_QR_OrderItem();
        oiList = qrOi1.getPodOrderFromQuote(qrOi[0].Order.SBQQ__Quote__c,qrOi[0].Order.ServicePoint__c);
        System.debug('@@@'+qrOi[0].Order.ServicePoint__c);
        

        
        Test.stopTest();
    }
}