force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/BillSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>BillSendingMethod__c</fullName>
    <label>Modalità invio bolletta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillSendingMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/ElectronicInvoiceCertifiedEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>ElectronicInvoiceCertifiedEmailAddress__c</fullName>
    <description>Dati per fatturazione elettronica</description>
    <label>PEC Fatturazione Elettronica</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/ElectronicInvoicingMethod__c.field-meta.xml
<CustomField>
    <fullName>ElectronicInvoicingMethod__c</fullName>
    <label>Modalità invio fatturazione Elettronica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Estero</fullName>
            </value>
            <value>
                <fullName>XML</fullName>
            </value>
            <value>
                <fullName>XML + carta/email</fullName>
            </value>
            <value>
                <fullName>XML PA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoiceCertifiedEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCertifiedEmailAddress__c</fullName>
    <label>Email PEC Invio Bolletta</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingAddressFormula__c.field-meta.xml
<CustomField>
    <fullName>InvoicingAddressFormula__c</fullName>
    <formula>InvoicingStreetName__c &amp;&apos;, &apos;&amp; InvoicingStreetNumber__c &amp;&apos;/&apos;&amp; InvoicingStreetNumberExtension__c &amp;&apos;, &apos;&amp; InvoicingPlace__c &amp;&apos;, &apos;&amp; InvoicingCity__c &amp;&apos;, &apos;&amp; InvoicingProvince__c &amp;&apos;, &apos;&amp; InvoicingPostalCode__c &amp;&apos;, &apos;&amp; InvoicingCountry__c</formula>
    <label>Indirizzo Spedizione/Fatturazione</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingCity__c.field-meta.xml
<CustomField>
    <fullName>InvoicingCity__c</fullName>
    <label>Comune [Spedizione/Fatturazione]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingCountry__c.field-meta.xml
<CustomField>
    <fullName>InvoicingCountry__c</fullName>
    <label>Stato [Spedizione/Fatturazione]</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>InvoicingPostalCode__c</fullName>
    <label>CAP [Spedizione/Fatturazione]</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingProvince__c.field-meta.xml
<CustomField>
    <fullName>InvoicingProvince__c</fullName>
    <description>Provincia codificata in due caratteri</description>
    <label>Provincia [Spedizione/Fatturazione]</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingStreetName__c.field-meta.xml
<CustomField>
    <fullName>InvoicingStreetName__c</fullName>
    <label>Nome Via [Spedizione/Fatturazione]</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingStreetNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoicingStreetNumber__c</fullName>
    <label>Civico [Spedizione/Fatturazione]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoicingStreetNumberExtension__c.field-meta.xml
<CustomField>
    <fullName>InvoicingStreetNumberExtension__c</fullName>
    <label>Estens.Civico [Spedizione/Fatturazione]</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/SendCertifiedEmailConsentDate__c.field-meta.xml
<CustomField>
    <fullName>SendCertifiedEmailConsentDate__c</fullName>
    <label>Data consenso E-mail PEC Invio Bolletta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/SubjectCode__c.field-meta.xml
<CustomField>
    <fullName>SubjectCode__c</fullName>
    <description>in questo campo deve essere riportato il codice ufficio, deve essere implementato se modalità invio fatturazione XML se invece Modalità invio Fatturazione XML+carta non deve essere implemetato</description>
    <label>Codice Destinatario</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/XMLType__c.field-meta.xml
<CustomField>
    <fullName>XMLType__c</fullName>
    <label>Tipo XML</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_XmlType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Profile</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Casi</relationshipLabel>
    <relationshipName>Casi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/BillSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>BillSendingMethod__c</fullName>
    <description>Nuova modalità invio bolletta per sotto-processo Modifica Dati di Recapito</description>
    <label>Modalità invio bolletta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillSendingMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CommodityFormula__c.field-meta.xml
<CustomField>
    <fullName>CommodityFormula__c</fullName>
    <description>Settore merceologico preso in Lookup dal Service Point</description>
    <formula>IF(TEXT(ServicePoint__r.CommoditySector__c) != &apos;&apos;,TEXT(ServicePoint__r.CommoditySector__c), TEXT(Commodity__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DataUltimoAllineamentoGAA__c.field-meta.xml
<CustomField>
    <fullName>DataUltimoAllineamentoGAA__c</fullName>
    <label>Data Ultimo Allineamento GAA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ElectronicInvoiceCertifiedEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>ElectronicInvoiceCertifiedEmailAddress__c</fullName>
    <description>Per modifica Dati fatturazione elettronica</description>
    <label>PEC Fatturazione Elettronica</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ElectronicInvoicingMethod__c.field-meta.xml
<CustomField>
    <fullName>ElectronicInvoicingMethod__c</fullName>
    <description>Per modifica Dati fatturazione elettronica</description>
    <label>Modalità invio fatturazione Elettronica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillingMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceCertifiedEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCertifiedEmailAddress__c</fullName>
    <description>Nuova email invio bolletta PEC per sotto-processo Modifica Dati di Recapito</description>
    <label>Email PEC Invio Bolletta</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoicingCity__c.field-meta.xml
<CustomField>
    <fullName>InvoicingCity__c</fullName>
    <description>Componente Indirizzo di fatturazione</description>
    <label>Comune [Spedizione/Fatturazione]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoicingCountry__c.field-meta.xml
<CustomField>
    <fullName>InvoicingCountry__c</fullName>
    <description>Componente Indirizzo di fatturazione</description>
    <label>Stato [Spedizione/Fatturazione]</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoicingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>InvoicingPostalCode__c</fullName>
    <description>Componente Indirizzo di fatturazione</description>
    <label>CAP [Spedizione/Fatturazione]</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoicingProvince__c.field-meta.xml
<CustomField>
    <fullName>InvoicingProvince__c</fullName>
    <description>Componente Indirizzo di fatturazione</description>
    <label>Provincia [Spedizione/Fatturazione]</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoicingStreetName__c.field-meta.xml
<CustomField>
    <fullName>InvoicingStreetName__c</fullName>
    <description>Componente Indirizzo di fatturazione</description>
    <label>Nome Via [Spedizione/Fatturazione]</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoicingStreetNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoicingStreetNumber__c</fullName>
    <description>Componente Indirizzo di fatturazione</description>
    <label>Civico [Spedizione/Fatturazione]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoicingStreetNumberExtension__c.field-meta.xml
<CustomField>
    <fullName>InvoicingStreetNumberExtension__c</fullName>
    <description>Componente Indirizzo di fatturazione</description>
    <label>Estens.Civico [Spedizione/Fatturazione]</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Mercato</description>
    <label>Mercato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SendCertifiedEmailConsentDate__c.field-meta.xml
<CustomField>
    <fullName>SendCertifiedEmailConsentDate__c</fullName>
    <description>Nuova data consenso email invio bolletta PEC per sotto-processo Modifica Dati di Recapito</description>
    <label>Data consenso E-mail PEC Invio Bolletta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/XMLType__c.field-meta.xml
<CustomField>
    <fullName>XMLType__c</fullName>
    <description>Per modifica Dati fatturazione elettronica</description>
    <label>Tipo XML</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_XmlType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(SBQQ__Order__r.Market__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercato</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_DataEnrichmentTransocode__mdt/HDT_DataEnrichmentTransocode__mdt.object-meta.xml
<CustomObject>
    <label>Transcodifica Arricchimento Dati</label>
    <pluralLabel>Transcodifiche Arricchimento Dati</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_DataEnrichmentTransocode__mdt/fields/IsTranscode__c.field-meta.xml
<CustomField>
    <fullName>IsTranscode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transcodifica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HDT_DataEnrichmentTransocode__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Metodo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_DataEnrichmentTransocode__mdt/fields/SapField__c.field-meta.xml
<CustomField>
    <fullName>SapField__c</fullName>
    <label>Campo Sap</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateCategory__c/RateCategory__c.object-meta.xml
<CustomObject>
    <description>Oggetto utilizzato per calcolare la Rate category dell&apos;order</description>
    <label>RateCategory</label>
    <nameField>
        <label>RateCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RateCategory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCategory__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Mercato di Riferimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_BillingMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Estero</fullName>
    </customValue>
    <customValue>
        <fullName>XML</fullName>
    </customValue>
    <customValue>
        <fullName>XML + carta/email</fullName>
    </customValue>
    <customValue>
        <fullName>XML PA</fullName>
    </customValue>
    <description>Estero
XML
XML + carta/email
XML PA</description>
    <masterLabel>Modalità Invio Fatturazione</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_BillSendingMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bolletta per e-mail</fullName>
    </customValue>
    <customValue>
        <fullName>Cartaceo</fullName>
    </customValue>
    <customValue>
        <fullName>Fatturazione PA</fullName>
    </customValue>
    <customValue>
        <fullName>Invio tramite PEC</fullName>
    </customValue>
    <customValue>
        <fullName>Bolletta per e-mail + Carta</fullName>
        <isActive>false</isActive>
        <label>Bolletta per e-mail + Carta</label>
    </customValue>
    <masterLabel>Modalità Invio Bolletta</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Libero</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>FUI</fullName>
    </customValue>
    <customValue>
        <fullName>Regolamentato</fullName>
    </customValue>
    <customValue>
        <fullName>Salvaguardia</fullName>
    </customValue>
    <customValue>
        <fullName>STGM</fullName>
    </customValue>
    <masterLabel>Mercato</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_XmlType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dettaglio</fullName>
    </customValue>
    <customValue>
        <fullName>Sintetico</fullName>
    </customValue>
    <masterLabel>Tipo XML</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_DataEnrichmentPostSales.cls
public with sharing class HDT_UTL_DataEnrichmentPostSales {

    /**
     * Gestisce la response dell'arricchimento dati scrivendo i valori su currentCase.
     */
    public static Case handleResponse(String serializedResponse, Case currentCase){
        Set<String> dataEnrichmentFields = new Set<String>();
        return handleResponse(serializedResponse, currentCase, dataEnrichmentFields);
    }

    /**
     * Gestisce la response dell'arricchimento dati scrivendo i valori su currentCase e restituendo la lista dei campi valorizzati in dataEnrichmentFields.
     */

     /*
    * @Author: Salvatore A. Sarà 19/10/2021
    * Risoluzione "Debug Should Use Logging Level"
    * Risoluzione "Avoid debug statements since they impact on performance"
    * Risoluzione "Local variable is declared and-or assigned but not used"
    */
    @SuppressWarnings('PMD.AvoidDebugStatements')
    public static Case handleResponse(String serializedResponse, Case currentCase, Set<String> dataEnrichmentFields){
        HDT_QR_DataEnrichmentPostSales depsQr = new HDT_QR_DataEnrichmentPostSales();
        HDT_SRV_DataEnrichmentPostSales depsSrv = new HDT_SRV_DataEnrichmentPostSales();
        HDT_QR_AnagAlignment anagAlignQr = new HDT_QR_AnagAlignment();
        List<HDT_WS_ArrichmentDataEntityResponse.HDT_WRP_PosizioniResponseObject> positions = new List<HDT_WS_ArrichmentDataEntityResponse.HDT_WRP_PosizioniResponseObject>();
        List<HDT_DataEnrichmentTransocode__mdt> transcodeConfigList = new List<HDT_DataEnrichmentTransocode__mdt>();
        Map<String, Object> transcodeMap = new Map<String, Object>();
        String billingProfileCode;
        String billingProfilesfdcField;
        String billingProfileId;
        String contractSapCode;
        String contractSfdcField;
        String contractId;
        String modInvioBolletta;
        String pecBolletta;
        String emailBolletta;
        String deliveryAddress;
        String salesCompanyCode;
        String salesCompany;
        String method;
        String sottoTipologiaDuso;
        /*
			@Author: Davide Viola - 20/10/2021
			Description: PMD -> Commentata variabile non utilizzata.
		*/
        Decimal decValue;
        HDT_WS_ArrichmentDataEntityResponse resp= (HDT_WS_ArrichmentDataEntityResponse) JSON.deserialize(serializedResponse, HDT_WS_ArrichmentDataEntityResponse.class);
        positions = resp.data.posizioni;
        transcodeConfigList = depsQr.getTranscodeConfig();
        for(HDT_WS_ArrichmentDataEntityResponse.HDT_WRP_PosizioniResponseObject position : positions){
            for(HDT_DataEnrichmentTransocode__mdt transcodeConfig : transcodeConfigList){
               if(position.campo == transcodeConfig.SapField__c){
                    if(transcodeConfig.IsNumber__c){
                        if(transcodeConfig.Precision__c == 0){
                            try{
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                Integer.valueOf(Decimal.valueOf(position.valore)));
                            }catch(Exception e){
                                System.debug(LoggingLevel.DEBUG, e.getMessage());
                            }
                        }else if(transcodeConfig.Precision__c > 0){
                            try{
                                decValue = Decimal.valueOf(position.valore);
                                transcodeMap.put(transcodeConfig.SfdcField__c, 
                                decValue.setScale(Integer.valueOf(transcodeConfig.Precision__c)));
                            }catch(Exception e){
                                System.debug(LoggingLevel.DEBUG, e.getMessage());
                            }
                        }
                    } else if(transcodeConfig.IsTranscode__c){
                        method = transcodeConfig.Method__c;                        
                        switch on method{
                            when 'getPicklistValue'{
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.getPicklistValue('Case', transcodeConfig.SfdcField__c, position.valore));
                            }
                            when 'getBoolFromString'{
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.getBoolFromString(position.valore));
                            }
                            when 'getDateByYear'{
                                transcodeMap.put(transcodeConfig.SfdcField__c, 
                                depsSrv.getDateByYear(position.valore));
                            }
                            when 'getBillingProfileIdBySapCode'{
                                billingProfilesfdcField = transcodeConfig.SfdcField__c;
                                billingProfileCode = position.valore;
                            }
                            when 'getContractIdBySapCode'{
                                contractSfdcField = transcodeConfig.SfdcField__c;
                                String caseContractLookup = (String) currentCase.get(contractSfdcField);
                                // Transcodifichiamo solo se il Case non ha già un contratto, altrimenti facciamo una query inutile sul Contract.
                                if (String.isBlank(caseContractLookup)){
                                    contractSapCode = position.valore;
                                }
                            }
                            when 'getCaliber'{
                                transcodeMap.put(transcodeConfig.SfdcField__c, 
                                depsSrv.getCaliber(position.valore));
                            }
                            when 'writeCollectiveBillType' {
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.writeCollectiveBillType(position.valore, currentCase));
                            }
                            when 'getOpzione'{
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.getOpzione(position.valore));
                            }
                            when 'getDateFromString'{
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.getDateFromString(position.valore));
                            }
                            when 'variationsBlock'{
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.variationsBlock(position.valore));
                            }
                            when 'writeBlockCode' {
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.writeBlockCode(position.valore, currentCase));
                            }
                            /*when 'transCodeDoubleOppositeToDecimal' {
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.transCodeDoubleOppositeToDecimal(position.valore));
                            }*/
                            when 'transCodeSiNo' {
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.transCodeSiNo(position.valore));
                            }
                            when 'transCodeDoubleToString' {
                                transcodeMap.put(transcodeConfig.SfdcField__c,
                                depsSrv.transCodeDoubleToString(position.valore));
                            }
                            when 'alignGaaDate' {
                                Date dataGaa = depsSrv.alignGaaDate(String.valueOf(transcodeMap.get('DataUltimoAllineamentoGAA__c')), position.valore);
                                transcodeMap.put(transcodeConfig.SfdcField__c, dataGaa);
                            }
                            when 'transCodeSiNoConDescr' {
                                transcodeMap.put(transcodeConfig.SfdcField__c, depsSrv.transCodeSiNoConDescr(position.valore));
                            }
                            when 'transcodificaInfoDepurazione' {
                                transcodeMap.put(transcodeConfig.SfdcField__c, depsSrv.transcodificaInfoDepurazione(position.valore));
                            }
                            
                        }
                    } else {
                        transcodeMap.put(transcodeConfig.SfdcField__c, position.valore);
                    }
                }
            }
        }

        if(String.isBlank(String.valueOf(transcodeMap.get('Market__c'))) && ('Acqua'.equalsIgnoreCase(currentCase.CommodityFormula__c) || 'Acqua'.equalsIgnoreCase(currentCase.Commodity__c))){
            transcodeMap.put('Market__c', 'Regolamentato');
        }

        //BILLING PROFILE 
        try{
            BillingProfile__c billingRecord = depsQr.getBillingProfileIdBySapCode(billingProfileCode);
            billingProfileId = billingRecord.Id;
            //deliveryAddress = depsSrv.getDeliveryAddress(billingProfileId);
            deliveryAddress = billingRecord.InvoicingAddressFormula__c;
            String viaRecapito = billingRecord.InvoicingStreetName__c != null? billingRecord.InvoicingStreetName__c :'';
            String civicoRecapito = billingRecord.InvoicingStreetNumber__c != null? billingRecord.InvoicingStreetNumber__c :'';
            String comuneRecapito = billingRecord.InvoicingCity__c != null? billingRecord.InvoicingCity__c :'';
            String capRecapito = billingRecord.InvoicingPostalCode__c != null? billingRecord.InvoicingPostalCode__c :'';
            String suffissoRecapito = billingRecord.InvoicingStreetNumberExtension__c != null? billingRecord.InvoicingStreetNumberExtension__c :'';
            String provinciaRecapito = billingRecord.InvoicingProvince__c != null? billingRecord.InvoicingProvince__c :'';
            String nazioneRecapito = billingRecord.InvoicingCountry__c != null? billingRecord.InvoicingCountry__c :'';
            nazioneRecapito = nazioneRecapito.length()>0?nazioneRecapito.substring(0,2):nazioneRecapito;
            String codiceUfficio = billingRecord.SubjectCode__c != null?billingRecord.SubjectCode__c:'';
            String tipoXml = billingRecord.XMLType__c != null?billingRecord.XMLType__c:'';
            String pecElettronica = billingRecord.ElectronicInvoiceCertifiedEmailAddress__c != null?billingRecord.ElectronicInvoiceCertifiedEmailAddress__c:'';
            String modInvioFatt = billingRecord.ElectronicInvoicingMethod__c != null?billingRecord.ElectronicInvoicingMethod__c:'';
            Date dataConsensoPEc = billingRecord.SendCertifiedEmailConsentDate__c;
            modInvioBolletta = billingRecord.BillSendingMethod__c;
            pecBolletta = billingRecord.InvoiceCertifiedEmailAddress__c;
            emailBolletta = billingRecord.InvoiceEmailAddress__c;
            
            transcodeMap.put('BillSendingMethod__c', modInvioBolletta);
            transcodeMap.put('InvoiceEmail__c', emailBolletta);
            transcodeMap.put('InvoiceCertifiedEmailAddress__c', pecBolletta);
            transcodeMap.put(billingProfilesfdcField, billingProfileId);
            transcodeMap.put('InvoicingPostalCode__c', capRecapito);
            transcodeMap.put('InvoicingProvince__c', provinciaRecapito);
            transcodeMap.put('DeliveryAddress__c', deliveryAddress);
            transcodeMap.put('InvoicingStreetNumber__c', civicoRecapito);
            transcodeMap.put('InvoicingCity__c', comuneRecapito);
            transcodeMap.put('InvoicingStreetNumberExtension__c', suffissoRecapito);
            transcodeMap.put('InvoicingStreetName__c', viaRecapito);
            transcodeMap.put('OfficeSubjectCode__c', codiceUfficio);
            transcodeMap.put('XMLType__c', tipoXml);
            transcodeMap.put('ElectronicInvoiceCertifiedEmailAddress__c', pecElettronica);
            transcodeMap.put('ElectronicInvoicingMethod__c', modInvioFatt);
            transcodeMap.put('SendCertifiedEmailConsentDate__c', dataConsensoPEc);
            transcodeMap.put('InvoicingCountry__c', nazioneRecapito);

        } catch(Exception e) {
            System.debug(LoggingLevel.DEBUG, 'Billing Profile non presente a sistema');
        }

        //ServicePoint
        try{
            ServicePoint__c servicePoint = depsQr.getServicePointData(currentCase.ServicePoint__c);
            transcodeMap.put('SupplyType__c',ServicePoint.SupplyType__c);
            transcodeMap.put('Disconnectable__c',ServicePoint.Disconnectable__c);
            transcodeMap.put('DisconnectibilityType__c',ServicePoint.DisconnectibilityType__c);
        } catch(Exception e){
            System.debug(LoggingLevel.DEBUG, 'Errore Ereditare campi SP -> ' + e.getMessage());
        }

        // Contract
        try{
            if (String.isNotBlank(contractSapCode)){
                Contract c = depsQr.getContractData(contractSapCode);
                contractId = c.Id;
                transcodeMap.put(contractSfdcField, contractId);
            }
        } catch(Exception e){
            System.debug(LoggingLevel.DEBUG, 'Errore Set Lookup Contract -> ' + e.getMessage());
        }
        //Accise & Addizionale Regionale
        String taxes = (String)transcodeMap.get('Taxes__c') != null ? (String)transcodeMap.get('Taxes__c') : '';
        if(String.isBlank(String.valueOf(transcodeMap.get('Excises__c'))) && String.isNotBlank(taxes))
        {
            List<HDT_ExciseTranscode__mdt> exciseTranscode = [SELECT Id, Excise__c FROM HDT_ExciseTranscode__mdt WHERE ExciseString__c = :taxes WITH SECURITY_ENFORCED];
            Double excises = !exciseTranscode.isEmpty() ? exciseTranscode[0].Excise__c : 0.0;
            transcodeMap.put('Excises__c', excises);
        }
        if(String.isBlank(String.valueOf(transcodeMap.get('RegionalAdditional__c'))) && String.isNotBlank(taxes))
        {
            Double regionalAdditional = anagAlignQr.findRegionalAdditional(taxes, (String)transcodeMap.get('SupplyCity__c'), '');
            transcodeMap.put('RegionalAdditional__c', regionalAdditional);
        }

        //SALESCOMPANY && SALESCOMPANYCODE
        salesCompanyCode = (String) transcodeMap.get('SalesCompanyCode__c');
        salesCompanyCode = String.isBlank(salesCompanyCode) && 'Acqua'.equalsIgnoreCase(currentCase.CommodityFormula__c) ? '11-HERASPA' : salesCompanyCode;
        salesCompanyCode = String.isBlank(salesCompanyCode) && 'Acqua'.equalsIgnoreCase(currentCase.Commodity__c) ? '11-HERASPA' : salesCompanyCode;
        salesCompanyCode = String.isBlank(salesCompanyCode) && 'Ambiente'.equalsIgnoreCase(currentCase.CommodityFormula__c) ? '1200000000' : salesCompanyCode;
        salesCompanyCode = String.isBlank(salesCompanyCode) && 'Ambiente'.equalsIgnoreCase(currentCase.Commodity__c) ? '1200000000' : salesCompanyCode;
        salesCompany = depsSrv.calculateSalesCompany(salesCompanyCode);
        
        transcodeMap.put('SalesCompany__c', salesCompany);
        transcodeMap.put('SalesCompanyCode__c', salesCompanyCode);

        //SOTTOTIPOLOGIA D'USO
        sottoTipologiaDuso = HDT_SRV_DataEnrichmentPostSales.handleSubType(salesCompany, (String) transcodeMap.get('RateCategory__c'));
        transcodeMap.put('UseSubCategory__c',sottoTipologiaDuso);
       
        dataEnrichmentFields.addAll(transcodeMap.keySet());
        return depsSrv.populateCase(transcodeMap, currentCase);
    }

    // Wrapper per i flow
    @InvocableMethod(label='Handle Response Data Enrichment')
    public static List<Case> handleResponseFlow(List<HDT_UTL_FlowInput> inputs){
        String serializedResponse = inputs[0].serializedResponse;
        Case currentCase = inputs[0].currentCase;
        
        List<Case> caseList = new List<Case>();
        caseList.add(handleResponse(serializedResponse, currentCase));
        return caseList;
    }

    public class HDT_UTL_FlowInput{

        @InvocableVariable
        public String serializedResponse;
        @InvocableVariable
        public Case currentCase;

    }


}