force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/BankAccountSignatoryFirstName__c.field-meta.xml
<CustomField>
    <fullName>BankAccountSignatoryFirstName__c</fullName>
    <description>Nome Sottoscrittore CC</description>
    <label>Nome sottoscrittore CC</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/BankAccountSignatoryFiscalCode__c.field-meta.xml
<CustomField>
    <fullName>BankAccountSignatoryFiscalCode__c</fullName>
    <description>Codice Fiscale Sottoscrittore CC</description>
    <label>Codice Fiscale Sottoscrittore CC</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/BankAccountSignatoryLastName__c.field-meta.xml
<CustomField>
    <fullName>BankAccountSignatoryLastName__c</fullName>
    <description>Valorizzato con i dati di chi paga(intestatario/sottoscrittore): Se c&apos;è un pagatore alternativo questi dati saranno valorizzati con quelli di quest&apos;ultimo</description>
    <label>Cognome sottoscrittore CC</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/BillSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>BillSendingMethod__c</fullName>
    <label>Modalità invio bolletta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillSendingMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/IbanABI__c.field-meta.xml
<CustomField>
    <fullName>IbanABI__c</fullName>
    <description>Indica dal 6° al 10° carattere dell&apos;Iban</description>
    <label>ABI</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/IbanCAB__c.field-meta.xml
<CustomField>
    <fullName>IbanCAB__c</fullName>
    <description>Indica dal 11° al 15° carattere dell&apos;Iban</description>
    <label>CAB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/IbanCIN__c.field-meta.xml
<CustomField>
    <fullName>IbanCIN__c</fullName>
    <description>Indica il 5° carattere dell&apos;Iban</description>
    <label>CIN</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/IbanCodeNumber__c.field-meta.xml
<CustomField>
    <fullName>IbanCodeNumber__c</fullName>
    <description>Indica dal 16° al 27° carattere dell&apos;Iban</description>
    <label>Numero Conto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/IbanIsForeign__c.field-meta.xml
<CustomField>
    <fullName>IbanIsForeign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>è un campo di tipo flag se a Yes vierrà inserito l&apos;IBAN Estero e devono essere effettuati i controlli su IBAN estero</description>
    <label>IBAN Estero</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoiceCertifiedEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCertifiedEmailAddress__c</fullName>
    <label>Email PEC Invio Bolletta</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/InvoiceEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>InvoiceEmailAddress__c</fullName>
    <label>Email Invio Bolletta</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/OtherPayer_c__c.field-meta.xml
<CustomField>
    <fullName>OtherPayer_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account pagatore delle bollette (diverso dal titolare della fornitura)</description>
    <label>Pagatore Alternativo</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Billing Profiles</relationshipLabel>
    <relationshipName>Billing_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/SignatoryType__c.field-meta.xml
<CustomField>
    <fullName>SignatoryType__c</fullName>
    <label>Tipo Sottoscrittore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legale Rappresentante</fullName>
            </value>
            <value>
                <fullName>Pagatore Alternativo</fullName>
            </value>
            <value>
                <fullName>Stesso Sottoscrittore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/SubjectCode__c.field-meta.xml
<CustomField>
    <fullName>SubjectCode__c</fullName>
    <description>in questo campo deve essere riportato il codice ufficio, deve essere implementato se modalità invio fatturazione XML se invece Modalità invio Fatturazione XML+carta non deve essere implemetato</description>
    <label>Codice Destinatario</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/SubjectCodeEndDate__c.field-meta.xml
<CustomField>
    <fullName>SubjectCodeEndDate__c</fullName>
    <label>Data fine validità codice destinatario</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/SubjectCodeStartDate__c.field-meta.xml
<CustomField>
    <fullName>SubjectCodeStartDate__c</fullName>
    <label>Data inizio validità codice destinatario</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_BillSendingMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bolletta per e-mail</fullName>
    </customValue>
    <customValue>
        <fullName>Cartaceo</fullName>
    </customValue>
    <customValue>
        <fullName>Fatturazione PA</fullName>
    </customValue>
    <customValue>
        <fullName>Invio tramite PEC</fullName>
    </customValue>
    <customValue>
        <fullName>Bolletta per e-mail + Carta</fullName>
        <isActive>false</isActive>
        <label>Bolletta per e-mail + Carta</label>
    </customValue>
    <masterLabel>Modalità Invio Bolletta</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_BillingProfileForm.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 27/11/2020
* @description Apex controller for hdtBillingProfileForm.js component
* @history Keltin Mesonjesi – 27/11/2020 – Created class
*/

public inherited sharing class HDT_LC_BillingProfileForm {

    private static HDT_SRV_BillingProfile billingProfileSRV = new HDT_SRV_BillingProfile();
    private static HDT_SRV_Account accountSRV = new HDT_SRV_Account();
    private static HDT_QR_Account accountQR = new HDT_QR_Account();

    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @date 27/11/2020
     * @description Get form fields based on selected payment method
     * @param String paymentMethod
     * @return List<String>
     */
    @AuraEnabled
    public static List<String> getFormFields(String paymentMethod, String accountId){
        
        Set<String> resultSet = new Set<String>();
        List<String> resultList = new List<String>();

        Set<String> bollettionoPostale = new Set<String>{
            'InvoiceEmailAddress__c',
            'InvoiceCertifiedEmailAddress__c',
            'BillSendingMethod__c'
        };

        Set<String> rid = new Set<String>{
            'InvoiceEmailAddress__c',
            'InvoiceCertifiedEmailAddress__c',
            'IbanIsForeign__c',
            'IbanCIN__c',
            'IbanABI__c',
            'IbanCAB__c',
            'IbanCodeNumber__c',
            'SignatoryType__c',
            'OtherPayer_c__c',
            'BankAccountSignatoryFiscalCode__c',
            'BankAccountSignatoryFirstName__c',
            'BankAccountSignatoryLastName__c'
        };

        Set<String> fatturazioneElettronica = new Set<String>{
            'BillSendingMethod__c',
            'SubjectCode__c',
            'InvoiceCertifiedEmailAddress__c',
            'SubjectCodeStartDate__c',
            'SubjectCodeEndDate__c'
        };

        List<String> fieldsToCheck = new List<String>();
        fieldsToCheck.addAll(bollettionoPostale);
        fieldsToCheck.addAll(rid);
        fieldsToCheck.addAll(fatturazioneElettronica);
        billingProfileSRV.checkReadAccess(String.join(fieldsToCheck,','));

        switch on paymentMethod {
            when  'Bollettino postale'{
                resultSet = bollettionoPostale;
            }
            when 'RID' {
                resultSet = rid;
            }
        }

        accountSRV.checkReadAccess('RecordType.Name');
        Account currentAccount = accountQR.getRecordById(accountId, 'RecordType.Name');
        if (currentAccount.RecordType.Name == 'Business') {
            resultSet.addAll(fatturazioneElettronica);
        }

        resultList.addAll(resultSet);

        return resultList;

    }

    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Create BillingProfile__C record
     * @param BillingProfile__c
     * @return BillingProfile__c
     */
    @AuraEnabled
    public static BillingProfile__c createBillingProfile(BillingProfile__c billingProfile){
        return billingProfileSRV.createRecord(billingProfile);
    }

}