force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VASBillingMode__c.field-meta.xml
<CustomField>
    <fullName>VASBillingMode__c</fullName>
    <label>Modalità di Fatturazione VAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillingModeVAS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di Fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>Versione del Product associato.</description>
    <label>Versione Prodotto</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DescriptionSAP__c.field-meta.xml
<CustomField>
    <fullName>DescriptionSAP__c</fullName>
    <description>Descrizione del prodotto come su DB SAP</description>
    <label>Descrizione SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/VASBillingMode__c.field-meta.xml
<CustomField>
    <fullName>VASBillingMode__c</fullName>
    <description>Possibili modalità di Faturazione VAS per il dato record di prodotto.</description>
    <label>Modalità di Fatturazione VAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillingModeVAS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>la versione del dato record di Prodotto nella funzionalità di Configurazione Offerta Tecnica</description>
    <label>Versione</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SaleServiceItem__c/SaleServiceItem__c.object-meta.xml
<CustomObject>
    <description>Oggetto giunzione tra opportunity/quote e Service point</description>
    <label>Sale Service Item</label>
    <nameField>
        <label>SaleServiceItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Service Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SaleServiceItem__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Sale Service Items</relationshipLabel>
    <relationshipName>SaleServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di Fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>QuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di Fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ServicePointLinkItem__c.field-meta.xml
<CustomField>
    <fullName>ServicePointLinkItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto Fornitura</label>
    <referenceTo>SaleServiceItem__c</referenceTo>
    <relationshipLabel>Quote Lines (Punto Fornitura)</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/VASBillingMode__c.field-meta.xml
<CustomField>
    <fullName>VASBillingMode__c</fullName>
    <label>Modalità di fatturazione VAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillingModeVAS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Versione</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_BillingModeVAS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A-Rate fisse</fullName>
    </customValue>
    <customValue>
        <fullName>C-Fattura SD</fullName>
    </customValue>
    <customValue>
        <fullName>D-Fattura SD</fullName>
    </customValue>
    <customValue>
        <fullName>E-Canone fisso</fullName>
    </customValue>
    <customValue>
        <fullName>F-Standalone</fullName>
    </customValue>
    <description>A-Rate fisse
C-Fattura SD 
D-Fattura SD 
E-Canone fisso
F-Standalone
    </description>
    <masterLabel>Modalita Fatturazione VAS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_QR_OrderItem.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 07/01/2020
* @description HDT_QR_OrderItem – Contains queries for OrderItem
* @history Keltin Mesonjesi – 07/01/2020 – Created class
*/
public inherited sharing class HDT_QR_OrderItem {
    
    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 07/01/2020
    * @description Get list of records by listOrderId and filtered by Product2 IN ('PDR','POD')
    * @param listOrderId
    * @return List<OrderItem>
    */
    public List<OrderItem> getRecordsByOrderIdListFilteredPdrPod(List<Id> listOrderId){
        return [
            SELECT
            ServicePoint__c,
            ServicePoint__r.Name,
            ServicePoint__r.ServicePointCode__c,
            OrderId,
            Product2.Name
            FROM 
            OrderItem 
            WHERE
            OrderId IN :listOrderId 
            AND (Product2.Name IN ('PDR','POD') OR (Product2.Family IN  ('VAS Opzione prodotto', 'VAS Fatturabili', 'VAS Prodotto', 'VAS Servizio') AND (NOT Product2.Description LIKE '%Sconto%')))
            WITH SECURITY_ENFORCED
        ];
    }

    public List<OrderItem> getRecordsByOrderIdFilteredFamilyBonus(List<Id> listOrderId){
        Set<String> famils = HDT_UTL_OrderProcessAssignment.getFamilySconto();
        return [
            SELECT
            ServicePoint__c,
            ServicePoint__r.Name,
            ServicePoint__r.ServicePointCode__c,
            OrderId,
            Order.OrderNumber,
            SBQQ__QuoteLine__r.SBQQ__RequiredBy__c,
            SBQQ__RequiredBy__c,
            Product2.Name
            FROM 
            OrderItem 
            WHERE
            OrderId IN :listOrderId 
            AND Order.SBQQ__Quote__r.SBQQ__Type__c != 'Amendment'
            AND Product2.Family IN :famils
            WITH SECURITY_ENFORCED
            Order by BillingProfile__c NULLS LAST
        ];
    }



    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 08/01/2020
    * @description Get record by orderId and filtered by Product2 IN ('PDR','POD')
    * @param orderId
    * @return List<OrderItem>
    */
    public List<OrderItem> getRecordsByOrderIdFilteredPdrPod(String orderId){
        return [
            SELECT 
            ServicePoint__r.Name,
            ServicePoint__r.ServicePointCode__c,
            OrderId,
            Product2.Name
            FROM 
            OrderItem 
            WHERE
            OrderId = :orderId 
            AND Product2.Name IN ('PDR','POD')
            WITH SECURITY_ENFORCED
        ];
    }

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 10/02/2021
    * @description Get record that have BillingProfile__c value set
    * @param listOrderId
    * @return List<OrderItem>
    */
    public List<OrderItem> getRecordsWithBillingProfile(List<Id> listOrderId){
        return [
            SELECT 
            OrderId,
            BillingProfile__c
            FROM 
            OrderItem 
            WHERE
            OrderId IN :listOrderId  
            AND BillingProfile__c != null
            WITH SECURITY_ENFORCED
        ];
    }

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @description getRecordsWithAmend
    * @param listOrderId
    * @return List<OrderItem>
    */
    public List<OrderItem> getRecordsWithAmend(List<Id> listOrderId){
        Set<String> famils = HDT_UTL_OrderProcessAssignment.getFamilySconto();
        famils.add('VAS Prodotto');
        famils.add('VAS Servizio');
        return [
            SELECT 
            OrderId,
            BillingProfile__c,
            ServicePoint__c
            FROM 
            OrderItem 
            WHERE
            OrderId IN :listOrderId  
            AND Order.SBQQ__Quote__r.SBQQ__Type__c = 'Amendment'
            AND (Product2.Name IN ('PDR','POD') OR Product2.Family IN :famils)
            WITH SECURITY_ENFORCED
        ];
    }

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @description getMainItem
    * @param orderId
    * @return List<OrderItem>
    */
    public List<OrderItem> getMainItem(String orderId){
        return [
            SELECT 
            OrderId,
            BillingProfile__c,
            Product2Id,
            Product2.Family,
            Product2.Version__c,
            Product2.ProductCode,
            Product2.Name,
            Product2.DescriptionSAP__c,
            VASBillingMode__c,
            SBQQ__QuoteLine__r.SBQQ__RequiredBy__c,
            SBQQ__QuoteLine__r.ServicePointLinkItem__r.ServicePoint__c
            FROM 
            OrderItem 
            WHERE OrderId = :orderId
            AND SBQQ__RequiredBy__c = null
            WITH SECURITY_ENFORCED
        ];
    }



    /**
    * @description 
    * @author federico.defelice@webresults.it | 11-10-2021 
    * @param quoteId 
    * @param quoteLineId 
    * @return List<Order> 
    **/
    public List<OrderItem> getPodOrderFromQuote(Id quoteId, Id qlOrServPointId){
        return [
            SELECT
            OrderId,
            Order.ServicePoint__r.ServicePointCode__c
            FROM
            OrderItem
            WHERE
            Order.SBQQ__Quote__c =:quoteId
            AND (SBQQ__QuoteLine__c =:qlOrServPointId OR Order.ServicePoint__c=:qlOrServPointId)
            AND Order.ServicePoint__c!=null
            WITH SECURITY_ENFORCED
        ];
    }

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @description getAnalisiConsumi
    * @param orderId
    * @return List<OrderItem>
    */
    public List<OrderItem> getAnalisiConsumi(String orderId){
        return [
            SELECT 
            OrderId,
            BillingProfile__c,
            Product2Id,
            Product2.Family,
            Product2.Name
            FROM 
            OrderItem 
            WHERE OrderId = :orderId
            AND Product2.Family = 'VAS Fatturabili'
            WITH SECURITY_ENFORCED
        ];
    }

}