force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Riferimento all&apos;Account</description>
    <label>Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Profiles</relationshipLabel>
    <relationshipName>BillingProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status; Ereditato da SAP</description>
    <label>Status del Profilo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Numero Documento</description>
    <label>Numero Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>Descrizione funzionale dell&apos;oggetto</description>
    <label>Interazione</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Interazione Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo di ricerca per l’Account da collegare all’interazione o creazione nuovo Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interazioni</relationshipLabel>
    <relationshipName>Interazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/LoginGroup__c.field-meta.xml
<CustomField>
    <fullName>LoginGroup__c</fullName>
    <label>Gruppo Login</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/LoginWorkstation__c.field-meta.xml
<CustomField>
    <fullName>LoginWorkstation__c</fullName>
    <label>Postazione di Login</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aperta</fullName>
                <default>true</default>
                <label>Aperta</label>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
            <value>
                <fullName>Scartata</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
                <isActive>false</isActive>
                <label>Bozza</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>Codice Agenzia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/AreaManager__c.field-meta.xml
<CustomField>
    <fullName>AreaManager__c</fullName>
    <label>Area Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale di Vendita</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CommercialId__c.field-meta.xml
<CustomField>
    <fullName>CommercialId__c</fullName>
    <description>Id Commerciale</description>
    <label>Venduto Da</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentDate__c.field-meta.xml
<CustomField>
    <fullName>DocumentDate__c</fullName>
    <label>Data Documento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Numero Documento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipologia Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARTA DI IDENTITÀ</fullName>
            </value>
            <value>
                <fullName>PATENTE</fullName>
            </value>
            <value>
                <fullName>PASSAPORTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/LoginGroup__c.field-meta.xml
<CustomField>
    <fullName>LoginGroup__c</fullName>
    <label>Gruppo Login</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/LoginWorkstation__c.field-meta.xml
<CustomField>
    <fullName>LoginWorkstation__c</fullName>
    <label>Postazione di Login</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/VendorFirstName__c.field-meta.xml
<CustomField>
    <fullName>VendorFirstName__c</fullName>
    <label>Nome Venditore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VendorLastName__c.field-meta.xml
<CustomField>
    <fullName>VendorLastName__c</fullName>
    <label>Cognome Venditore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agenzia</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products (Agenzia)</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>La tipologia di canale associato al order product</description>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_ProductOptionChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LoginGroup__c.field-meta.xml
<CustomField>
    <fullName>LoginGroup__c</fullName>
    <description>il gruppo di user associato al dato record di product option.</description>
    <label>Raggruppamento Login</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Stato</description>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullata</fullName>
            </value>
            <value>
                <fullName>Confermata</fullName>
            </value>
            <value>
                <fullName>In Sviluppo</fullName>
            </value>
            <value>
                <fullName>Vendibile</fullName>
            </value>
            <value>
                <fullName>Scaduta</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Details con l&apos;oggetto account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendite</relationshipLabel>
    <relationshipName>Vendite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>Codice Agenzia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/fields/CommercialId__c.field-meta.xml
<CustomField>
    <fullName>CommercialId__c</fullName>
    <label>Venduto Da</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/DocumentDate__c.field-meta.xml
<CustomField>
    <fullName>DocumentDate__c</fullName>
    <label>Data Emissione Documento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Numero Documento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipologia Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARTA DI IDENTITÀ</fullName>
            </value>
            <value>
                <fullName>PATENTE</fullName>
            </value>
            <value>
                <fullName>PASSAPORTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/fields/LoginGroup__c.field-meta.xml
<CustomField>
    <fullName>LoginGroup__c</fullName>
    <label>Gruppo Login</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Attiva</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/fields/VendorFirstName__c.field-meta.xml
<CustomField>
    <fullName>VendorFirstName__c</fullName>
    <label>Nome Venditore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/VendorLastName__c.field-meta.xml
<CustomField>
    <fullName>VendorLastName__c</fullName>
    <label>Cognome Venditore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account del titolare del punto di fornitura</description>
    <label>Account Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points (Account)</relationshipLabel>
    <relationshipName>Service_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Impianto compl. in funzione</fullName>
            </value>
            <value>
                <fullName>Interruzione avviata</fullName>
            </value>
            <value>
                <fullName>Impianto parzialmente chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto compl. chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto in attivazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_ProductOptionChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agente</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia</fullName>
    </customValue>
    <customValue>
        <fullName>App</fullName>
    </customValue>
    <customValue>
        <fullName>Assistente Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Camper</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>CONSIP</fullName>
    </customValue>
    <customValue>
        <fullName>Da PGM</fullName>
    </customValue>
    <customValue>
        <fullName>e-mail</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM POINT</fullName>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>ON-LINE</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <customValue>
        <fullName>PARTNER</fullName>
    </customValue>
    <customValue>
        <fullName>Postel</fullName>
    </customValue>
    <customValue>
        <fullName>Protocollo</fullName>
    </customValue>
    <customValue>
        <fullName>Punto Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>ServiziSociali</fullName>
    </customValue>
    <customValue>
        <fullName>SFA</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello amministratori</fullName>
    </customValue>
    <customValue>
        <fullName>SUPPORTO AGENZIE</fullName>
    </customValue>
    <customValue>
        <fullName>SUPPORTO GDA</fullName>
    </customValue>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Telefono Outbound</fullName>
    </customValue>
    <masterLabel>Canale Product Option</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SalesChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>HC Point</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie SME</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Punti Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
        <isActive>false</isActive>
        <label>Consip</label>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <isActive>false</isActive>
        <label>Reseller</label>
    </customValue>
    <description>Canale vendita associato all&apos;utente</description>
    <masterLabel>Canale Vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_OrderDossierWizard.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 06/01/2021
* @description Apex controller for HDT_LCP_OrderDossierWizard component
* @history Keltin Mesonjesi – 06/01/2021 – Created class
*/
public inherited sharing class HDT_LC_OrderDossierWizard {
    
    private static HDT_QR_Sale saleQr = new HDT_QR_Sale();
    private static HDT_SRV_Sale saleSrv = new HDT_SRV_Sale();
    private static HDT_QR_Order orderQr = new HDT_QR_Order();
    private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();
    private static HDT_QR_OrderItem orderItemQr = new HDT_QR_OrderItem();
    private static HDT_SRV_OrderItem orderItemSrv = new HDT_SRV_OrderItem();
    // EVERIS_NTTDATA START
    private static HDT_QR_AccountContactRelation acrQr = new HDT_QR_AccountContactRelation();
    // EVERIS_NTTDATA END

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 06/01/2021
    * @description Initialize controller
    * @param String saleId
    * @return Map<String, Object>
    */
    @AuraEnabled
    public static Map<String, Object> controllerInit(String saleId) {
        
        Map<String,Object> mapResponse = new Map<String,Object>();
        
        Boolean check = false;

        //Get Sale
        saleSrv.checkReadAccess('Status__c,Account__c,Name,Channel__c,VendorLastName__c,VendorFirstName__c,CommercialId__c,AgencyCode__c,Agency__c,AreaManager__c,DocumentNumber__c,DocumentDate__c,DocumentType__c');
        Sale__c sale = saleQr.getRecordById(saleId, 'LoginWorkstation__c, LoginGroup__c, CreatorGroup__c,Interaction__c,UpperChannelAgency__c,LowerChannelAgency__c,SalesContact__c,CreatedBy.LoginChannel__c,Status__c,Account__c,Name,Channel__c,VendorLastName__c,VendorFirstName__c,CommercialId__c,AgencyCode__c,Agency__c,AreaManager__c,DocumentNumber__c,DocumentDate__c,DocumentType__c');
        check = sale.Status__c == 'Attiva' ? true : false;
        
        //Get Orders
        List<Order> listOrder = orderQr.getRecordBySale(saleId);

        System.debug('Lista Ordini da Legare ' +listOrder);

        //Store orders Id
        List<Id> listOrdersId = new List<Id>();
        
        //Get OrderDossier record type
        String recordTypeIdOrderDossier = orderSrv.getRecordTypeIdOrderDossier();

        //Get Default record type
        String recordTypeIdDefault = orderSrv.getRecordTypeIdDefault();

        //Check for parent orders
        List<Order> listOrderParent = orderQr.getRecordBySaleFilterRecordTypeId(saleId, recordTypeIdOrderDossier);

        // EVERIS_NTTDATA START
        AccountContactRelation acr = acrQr.getPrimaryContactRelationBusiness(sale.Account__c);
        Id contactId = acr != null ? acr.ContactId : null;
        // EVERIS_NTTDATA END

        //Init parent order
        Order parentOrder = new Order();

        //Case Order is 'Attiva'
        if(check){
            //When there is no parent order
            if(listOrderParent.isEmpty()){

                Order parentOrderNew = new Order(
                    Name = sale.Name.length() < 80-7 ? 'Ordine '+sale.Name : 'Ordine '+sale.Name.substring(0, 80-7), //max length - size('Ordine ')
                    AccountId = sale.Account__c,
                    // EVERIS_NTTDATA START
                    Contact__c = contactId,
                    // EVERIS_NTTDATA END
                    Sale__c = sale.Id,
                    Status = 'Draft',
                    RecordTypeId = recordTypeIdOrderDossier,
                    EffectiveDate = Date.today(),
                    Step__c = 1,
                    Channel__c = sale.Channel__c,
                    LoginChannel__c = sale.CreatedBy.LoginChannel__c,
                    VendorLastName__c = sale.VendorLastName__c,
                    VendorFirstName__c = sale.VendorFirstName__C,
                    DocumentDate__c = sale.DocumentDate__c,
                    DocumentNumber__c = sale.DocumentNumber__c,
                    DocumentType__c = sale.DocumentType__c,
                    CommercialId__c = sale.CommercialId__c,
                    AgencyCode__c = sale.AgencyCode__c,
                    Agency__c = sale.Agency__c,
                    AreaManager__c = sale.AreaManager__c,
                    SalesContact__c = sale.SalesContact__c,
                    Interaction__c = sale.Interaction__c,
                    LowerChannelAgency__c = sale.LowerChannelAgency__c,
                    UpperChannelAgency__c = sale.UpperChannelAgency__c,
                    LoginWorkstation__c = sale.LoginWorkstation__c, 
                    LoginGroup__c = sale.LoginGroup__c, 
                    CreatorGroup__c = sale.CreatorGroup__c 
                );

                orderSrv.createRecord(parentOrderNew);
                
                for(Order o : listOrder){
                    listOrdersId.add(o.Id);
                }

                System.debug(listOrder != null && !listOrder.isEmpty());

                if(listOrder != null && !listOrder.isEmpty()){

                    System.debug('Entrato nel Loop');
                    system.debug(listOrdersId);

                    Map<String, Order> ordersToUpdateMap = new Map<String, Order>();
                    List<Order> ordersToUpdate = new List<Order>();
                    orderItemSrv.checkReadAccess('ServicePoint__c,ServicePoint__r.Name,ServicePoint__r.ServicePointCode__c,OrderId,Product2.Name');
                    List<OrderItem> orderItemsList = orderItemQr.getRecordsByOrderIdListFilteredPdrPod(listOrdersId);
                    orderItemsList.addAll(handleNotAmendBonus(listOrdersId));


                    System.debug('Lista Ordini '+orderItemsList);

                    for (OrderItem orderItem : orderItemsList) {
                        ordersToUpdateMap.put(orderItem.OrderId, new Order(
                            Id = orderItem.OrderId,
                            ServicePoint__c = orderItem.ServicePoint__c != null ? orderItem.ServicePoint__c : null,
                            ParentOrder__c = parentOrderNew.Id,
                            RecordTypeId = recordTypeIdDefault
                        ));
                    }
                    orderItemSrv.checkReadAccess('OrderId,BillingProfile__c');
                    List<OrderItem> orderItemsListWithBillingProfile = orderItemQr.getRecordsWithBillingProfile(listOrdersId);
                    Boolean isDuplicated = false;
                    for (OrderItem orderItem : orderItemsListWithBillingProfile) {
                        if (ordersToUpdateMap.get(orderItem.OrderId) != null) {
                            Order orderToUpdate = ordersToUpdateMap.get(orderItem.OrderId);
                            orderToUpdate.BillingProfile__c = orderItem.BillingProfile__c != null ? orderItem.BillingProfile__c : null;
                            
                            for (Order ord : ordersToUpdate) {
                                if (ord.Id == orderToUpdate.Id) {
                                    isDuplicated = true;
                                    break;
                                }
                            }
    
                            if (!isDuplicated) {
                                ordersToUpdate.add(orderToUpdate);
                            }
    
                            isDuplicated = false;
                        }
                    }

                    List<OrderItem> orderItemsAmend = orderItemQr.getRecordsWithAmend(listOrdersId);
                    system.debug('ordersToUpdate before: ' + ordersToUpdate);
                    system.debug('orderItemsAmend: ' + orderItemsAmend);
                    
                    for (OrderItem orderItem : orderItemsAmend) {
                        Order orderToUpdate = ordersToUpdateMap.get(orderItem.OrderId);
                        system.debug('orderToUpdate: ' + orderToUpdate);
                        //system.debug('ordersToUpdate after: ' + ordersToUpdate);
                        if(orderToUpdate!=null){
                            for (Order ord : ordersToUpdate) {
                                if (ord?.Id == orderToUpdate?.Id) {
                                    isDuplicated = true;
                                    break;
                                }
                            }
    
                            if (!isDuplicated) {
                                ordersToUpdate.add(orderToUpdate);
                            }
    
                            isDuplicated = false;
                        }
                    }

                    if(!ordersToUpdate.isEmpty()){
                        system.debug(ordersToUpdate);
                        orderSrv.updateRecords(ordersToUpdate);
                    }
                }

                parentOrder = orderQr.getRecordById(parentOrderNew.Id);

            } else { //when there is a parent order
                parentOrder = listOrderParent[0];
            }
        }

        mapResponse.put('check',check);
        mapResponse.put('checkExist',!listOrderParent.isEmpty());
        mapResponse.put('orderParent',parentOrder.Id);
        mapResponse.put('orderParentRecord',parentOrder);
        mapResponse.put('orderParentName',parentOrder.Name);
        mapResponse.put('accountId',parentOrder.AccountId);

        System.debug(mapResponse);

        return mapResponse;
    }

    private static List<OrderItem> handleNotAmendBonus(List<Id> listOrdersId){
        List<OrderItem> bonusToUpdate = new List<OrderItem>();
        List<OrderItem> allBonuses = orderItemQr.getRecordsByOrderIdFilteredFamilyBonus(listOrdersId);
        for(OrderItem itm : allBonuses){
            if(itm.SBQQ__RequiredBy__c==null){
                bonusToUpdate.add(itm);
            }
        }
        system.debug(bonusToUpdate);
        return bonusToUpdate;
    }

    // @AuraEnabled
    // public static String ordineVenditaCancel(String id){
    //     Ordine_di_Vendita__c ordVen = [Select id,account__c,account__r.name,Stato__c from Ordine_di_vendita__c where id=:id];
    //     ordVen.Stato__c = 'Disattivo';
    //     update ordVen;
    //     return ordVen.account__c;
    // }
    
    @AuraEnabled
    public static Order getOrderParent(String orderParentId){
        orderSrv.checkReadAccess('AccountId,Account.Name,Account.VATNumber__c,Account.FiscalCode__c,Account.BillingAddress,Account.ShippingAddress,Name,RecordType.DeveloperName,SystemModstamp,Status,ContractSigned__c,SignedDate__c,SignatureMethod__c,DocSendingMethod__c,Sale__c,CreatedDate,Step__c');
        return orderQr.getRecordById(orderParentId);
    }

    @AuraEnabled
    public static boolean checkCommunityLogin(){
        boolean check=False;
        string us= userinfo.getUserType();
        system.debug(us);
        if (!'Standard'.Equals(us)){
            check=True;
           
        }
        return check;
    }
    @AuraEnabled
    public static boolean checkDatiDiscordanti(String orderid){

        boolean res = HDT_UTL_Order.checkToDiscordanti(orderid);


        return res;
    }


    @AuraEnabled
    public static boolean saveProsegui(String orderParentId){
        Boolean check = true;

        orderSrv.checkReadAccess('AccountId,Account.Name,Name,Status,OrderNumber');
        List<Order>ordList = orderQr.getChildOrdersByParentId(orderParentId);

        for(Order ord : ordList){
            if(ord.Status != 'Activated'){
            	check = false;
            }
        }
        
        if(check){
            orderSrv.checkReadAccess('SystemModstamp,Status');
            Order orderParent = orderQr.getRecordById(orderParentId);

            orderParent.Status = 'Activated';
            orderSrv.updateRecord(orderParent);
        }

        return check;
    }

    /**
    * @author Andrei Necsulescu (andrei.necsulescu@webresults.it)
    * @date 03/09/2021
    * @description New community check logic using Site Class
    * @return Map<String, Object> Containing indication if it's community context or not + any errors
    */
    @AuraEnabled
    public static Map<String, Object> isCommunity(){

        Map<String, Object> result = new Map<String, Object>();

        try {

            Id siteId = Site.getSiteId(); 
            
            if (siteId != null) {
                result.put('isCommunity', true);
            } else {
                result.put('isCommunity', false);
            }

            result.put('error', false);
            
            
        } catch (Exception e) {
            
            result.put('error', true);
            result.put('errorMessage', e.getMessage());
            result.put('errorStackTrace', e.getStackTraceString());
            
        }

        return result;
    }

}