force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/ContractAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ContractAccountCode__c</fullName>
    <description>Codice Contract Account Sap</description>
    <externalId>true</externalId>
    <label>Conto Contrattuale</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <formula>Account.CustomerCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Codice Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Importo</description>
    <label>Importo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Profile</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Casi</relationshipLabel>
    <relationshipName>Casi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ContractAccountCode__c</fullName>
    <description>Conto Contrattuale</description>
    <label>Conto Contrattuale</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Numero Documento</description>
    <label>Numero Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <description>Data Scadenza</description>
    <label>Data Scadenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/DocumentSelected__c.object-meta.xml
<CustomObject>
    <label>Documento selezionato</label>
    <nameField>
        <label>Nome Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documenti selezionati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentSelected__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Importo</description>
    <label>Importo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Numero Documento</description>
    <label>Numero Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <description>Data Scadenza</description>
    <label>Data Scadenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/Position1__c.field-meta.xml
<CustomField>
    <fullName>Position1__c</fullName>
    <description>Campo utilizzato nel processo Paperless</description>
    <label>Posizione 1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/Position2__c.field-meta.xml
<CustomField>
    <fullName>Position2__c</fullName>
    <description>Campo utilizzato nel processo Paperless</description>
    <label>Posizione 2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/Position3__c.field-meta.xml
<CustomField>
    <fullName>Position3__c</fullName>
    <description>Campo utilizzato nel processo Paperless</description>
    <label>Posizione 3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_SRV_Paperless.cls
public with sharing class HDT_SRV_Paperless {

    HDT_QR_Paperless paperlessQr = new HDT_QR_Paperless();
    HDT_UTL_CreatePaymentsRequestBody paymentsUtl = new HDT_UTL_CreatePaymentsRequestBody();

    public String createRequestBody(String recordId){

        List<HDT_UTL_CreatePaymentsRequestBody.HDT_UTL_WrapperInput> inputList = new List<HDT_UTL_CreatePaymentsRequestBody.HDT_UTL_WrapperInput>();
        HDT_UTL_CreatePaymentsRequestBody.HDT_UTL_WrapperInput caseInput = new HDT_UTL_CreatePaymentsRequestBody.HDT_UTL_WrapperInput();
        HDT_UTL_CreatePaymentsRequestBody.HDT_UTL_WrapperInput documentInput = new HDT_UTL_CreatePaymentsRequestBody.HDT_UTL_WrapperInput();
        List<Map<String, Object>> documentsListMap = new List<Map<String, Object>>();
        List<Map<String, Object>> caseListMap = new List<Map<String, Object>>();
        List<DocumentSelected__c> documents = new List<DocumentSelected__c>();
        Case currentCase = new Case();
        String pretty;

        currentCase = paperlessQr.getCaseById(recordId);
        documents = paperlessQr.getDocumentSelectedByCase(recordId);

        System.debug('SRV_Paperless Case--> '+currentCase);
        System.debug('SRV_Paperless Documetns--> '+documents);

        Map<String, Object> caseMap = new Map<String, Object>{
            'codicecliente' => currentCase.AccountCode__c,
            'contocontrattuale' => currentCase.BillingProfile__r.ContractAccountCode__c,
            'rds' => currentCase.CaseNumber
        };

        caseListMap.add(caseMap);

        caseInput.isParent = true;
        caseInput.isChild = false;
        caseInput.configMapList = caseListMap;

        inputList.add(caseInput);

        for(DocumentSelected__c document : documents){
            documentsListMap.add(
                new Map<String, Object>{
                    'documento' => document.DocumentNumber__c,
                    'posizione1' => document.Position1__c,
                    'posizione2' => document.Position2__c,
                    'posizione3' => document.Position3__c,
                    'importo' => document.Amount__c,
                    'scadenza' => document.ExpirationDate__c
                }
            );
        }

        documentInput.isParent = false;
        documentInput.isChild = true;
        documentInput.childObjName = 'bollettini';
        documentInput.configMapList = documentsListMap;

        inputList.add(documentInput);
    

        pretty = paymentsUtl.createBodyRequest(inputList);

        System.debug('SRV_Paperless -->' +pretty);

        return pretty;
    
    }
}