force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l&apos;oggetto Vendita</description>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Cost__c/SBQQ__Cost__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__CostHelp</customHelpPage>
    <description>Unit cost for a product in one currency.</description>
    <label>Cost</label>
    <nameField>
        <displayFormat>COST-{000000}</displayFormat>
        <label>Cost #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__DiscountSchedule__c/SBQQ__DiscountSchedule__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__DiscountScheduleHelp</customHelpPage>
    <description>Volume discount schedule that applies automatic discounts based on quantity.</description>
    <label>Discount Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune Fornitura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>la tipologia di canale associato al dato record di product option</description>
    <label>Agenzia</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di Fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>QuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/OwnerAC__c.field-meta.xml
<CustomField>
    <fullName>OwnerAC__c</fullName>
    <label>Proprietario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di Fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <description>Campo di configurazione usato per indicare i comuni per il record di criterio nella funzionalità di Configurazione Offerta Tecnica</description>
    <label>Comune Fornitura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_SRV_QuoteLineTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 30/07/2021
 * @description Test Class for HDT_SRV_QuoteLine.cls
 * @history Fabricio Petkevicius Nunes – 30/07/2021 – Created class
 */
@isTest
public class HDT_SRV_QuoteLineTst{
	@TestSetup
	static void setup(){

		HDT_UTL_DataFactoryTst.pClickInstance();
        HDT_UTL_DataFactoryTst.pClickOrderPhase();

        List<Account> accounts = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');

        List<Opportunity> opportunities = HDT_UTL_DataFactoryTst.createOpportunity(1, true);

        List<Sale__c> sales = HDT_UTL_DataFactoryTst.createSale(1, true, accounts[0].Id, 'Bozza');

        List<ServicePoint__c> servicePoints = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        
        List<Product2> products = HDT_UTL_DataFactoryTst.createProduct2(1, false);
        products[0].Family = 'VAS Opzione prodotto';
        products[0].Name = 'POD';
        insert products;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> pricebookEntry = HDT_UTL_DataFactoryTst.createPricebookEntry(products, true, pricebookId);

        List<BillingProfile__c> billingProfiles = HDT_UTL_DataFactoryTst.createBillingProfile(1, true, accounts[0].Id);

        List<Order> orders = HDT_UTL_DataFactoryTst.createOrderWithPricebook(1,false, accounts[0].Id, sales, pricebookId);
        orders[0].BillingProfile__c = billingProfiles[0].Id;

        insert orders;

        List<SBQQ__Quote__c> quotes = HDT_UTL_DataFactoryTst.createQuote(1, false, orders[0].Id, opportunities[0].Id, sales[0].Id, 'Amendment');


        quotes[0].SBQQ__Account__c = accounts[0].Id;
        quotes[0].SBQQ__PricebookId__c =  pricebookId;

        insert quotes;


        opportunities[0].SBQQ__PrimaryQuote__c = quotes[0].Id;
        opportunities[0].Account = accounts[0];

        update opportunities;


        orders[0].SBQQ__Quote__c = quotes[0].Id;

        update orders;

        List<SBQQ__DiscountSchedule__c> discScheds = new List<SBQQ__DiscountSchedule__c>();
        SBQQ__DiscountSchedule__c discSchedule = new SBQQ__DiscountSchedule__c();

        insert discSchedule;

        Quote tQuote = new Quote();
        tQuote.Name = 'test';
        tQuote.OpportunityId = opportunities[0].Id;
        tquote.Pricebook2Id = pricebookId;

        insert tQuote;  

        List<QuoteLineItem> quoteLineItems = new List<QuoteLineItem>();
        QuoteLineItem quoteLineItem = new QuoteLineItem();
        quoteLineItem.Description = 'test';
        quoteLineItem.QuoteId = tQuote.Id;
        quoteLineItem.PricebookEntryId = pricebookEntry[0].Id;
        quoteLineItem.Quantity = 1;
        quoteLineItem.UnitPrice = 10;
        quoteLineItem.Product2 =products[0];

        insert quoteLineItem;

        List<SBQQ__Cost__c> costs = new List<SBQQ__Cost__c>();
        SBQQ__Cost__c  tCost = new SBQQ__Cost__c();
        tCost.SBQQ__Product__c = products[0].Id;
        tCost.SBQQ__UnitCost__c = 10;

        insert tCost;

        

        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
        quoteLine.SBQQ__Quote__c = quotes[0].Id;
        quoteLine.SBQQ__DiscountSchedule__c = discSchedule.Id;
        quoteLine.SBQQ__Cost__c = tCost.Id;
        quoteLine.ServicePoint__c = servicePoints[0].Id;
        quoteLine.SupplyCity__c = 'test city';
        quoteLine.BillingProfile__c = billingProfiles[0].Id;
        quoteLine.Agency__c = accounts[0].Id;
        quoteLine.OwnerAC__c = 'Si';

        insert quoteLine;

        
	}

	@isTest
	static void testcheckAccessInit(){

		Test.startTest();

		HDT_SRV_QuoteLine tstQuoteLineSrv=new HDT_SRV_QuoteLine();

		tstQuoteLineSrv.checkAccessInit('SupplyCity__c, SBQQ__Quote__c', 'create');


		// System.assertEquals('', '', '');

		// System.assertNotEquals('', '');

		Test.stopTest();
	}


    @isTest
	static void testcheckReadAccess(){

		Test.startTest();

		HDT_SRV_QuoteLine tstQuoteLineSrv=new HDT_SRV_QuoteLine();

		tstQuoteLineSrv.checkReadAccess('SupplyCity__c, SBQQ__Quote__c');


		// System.assertEquals('', '', '');

		// System.assertNotEquals('', '');

		Test.stopTest();
	}

    @isTest
	static void testcheckCreateAccess(){

		Test.startTest();

		HDT_SRV_QuoteLine tstQuoteLineSrv=new HDT_SRV_QuoteLine();

		tstQuoteLineSrv.checkCreateAccess('SupplyCity__c, SBQQ__Quote__c');


		// System.assertEquals('', '', '');

		// System.assertNotEquals('', '');

		Test.stopTest();
	}


    @isTest
	static void testcheckUpdateAccess(){

		Test.startTest();

		HDT_SRV_QuoteLine tstQuoteLineSrv=new HDT_SRV_QuoteLine();

		tstQuoteLineSrv.checkUpdateAccess('SupplyCity__c, SBQQ__Quote__c');


		// System.assertEquals('', '', '');

		// System.assertNotEquals('', '');

		Test.stopTest();
	}
}