force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/BankAccountSignatoryFiscalCode__c.field-meta.xml
<CustomField>
    <fullName>BankAccountSignatoryFiscalCode__c</fullName>
    <description>Codice Fiscale Sottoscrittore CC</description>
    <label>Codice Fiscale Sottoscrittore CC</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/ContractAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ContractAccountCode__c</fullName>
    <description>Codice Contract Account Sap</description>
    <externalId>true</externalId>
    <label>Conto Contrattuale</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HDT_TRH_BillingProfileTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 06/08/2021
 * @description HDT_TRH_BillingProfile for Test Classes
 * @history Fabricio Petkevicius Nunes – 06/08/2021 – Created class
 */
@isTest
public with sharing class HDT_TRH_BillingProfileTst{

	@isTest
	public static void testTriggerBillingProfileBeforeInsert(){

        Test.startTest();
		
			List<Account> accounts=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
			List<BillingProfile__c> billingProfiles = HDT_UTL_DataFactoryTst.createBillingProfile(1, false, accounts[0].Id);
			billingProfiles[0].BankAccountSignatoryFiscalCode__c = 'CSRMNL70A01F205L';
			HDT_UTL_DatabaseService.insertSObject(billingProfiles);

            BillingProfile__c testBillProf = [SELECT Id,ContractAccountCode__c FROM BillingProfile__c WHERE ContractAccountCode__c='200008867681' LIMIT 1];

		
			
            System.assertEquals('200008867681', testBillProf.ContractAccountCode__c, 'BillingProfile ContractAccountCode__c field is not Inserted(BillingProfile Trigger)');
            System.assertNotEquals(null, testBillProf.Id,'BillingProfile id is empty (BillingProfile Trigger)');
			Test.stopTest();
		}
	

	@isTest
	public static void testTriggerBillingProfileBeforeUpdate(){

        Test.startTest();
		
			List<Account> accounts=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
			HDT_UTL_DataFactoryTst.createBillingProfile(1, true, accounts[0].Id);
		
            BillingProfile__c testBillProf = [SELECT Id,ContractAccountCode__c FROM BillingProfile__c WHERE ContractAccountCode__c='200008867681' LIMIT 1];
			testBillProf.BankAccountSignatoryFiscalCode__c = 'CSRMNL70A01F205L';
			HDT_UTL_DatabaseService.updateSObject(testBillProf);
		
			
            System.assertEquals('200008867681', testBillProf.ContractAccountCode__c, 'BillingProfile ContractAccountCode__c field is not Inserted(BillingProfile Trigger)');
            System.assertNotEquals(null, testBillProf.Id,'BillingProfile id is empty (BillingProfile Trigger)');
			Test.stopTest();
		}
}

	