force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Riferimento all&apos;Account</description>
    <label>Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Profiles</relationshipLabel>
    <relationshipName>BillingProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status; Ereditato da SAP</description>
    <label>Status del Profilo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ExciseEle__c.field-meta.xml
<CustomField>
    <fullName>ExciseEle__c</fullName>
    <formula>TEXT(SBQQ__Order__r.ExciseEle__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accise Ele</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SAPContractCode__c.field-meta.xml
<CustomField>
    <fullName>SAPContractCode__c</fullName>
    <description>Numero Contratto Sap</description>
    <externalId>true</externalId>
    <label>Codice Contratto SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CommodityFormula__c.field-meta.xml
<CustomField>
    <fullName>CommodityFormula__c</fullName>
    <formula>TEXT(ServicePoint__r.CommoditySector__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare un contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Data decorrenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/PreviousCustomer__c.field-meta.xml
<CustomField>
    <fullName>PreviousCustomer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo che traccia il cliente precedente</description>
    <label>Cliente uscente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders (Cliente uscente)</relationshipLabel>
    <relationshipName>Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SapContractCode__c.field-meta.xml
<CustomField>
    <fullName>SapContractCode__c</fullName>
    <label>Codice Contratto SAP</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SAPImplantCode__c.field-meta.xml
<CustomField>
    <fullName>SAPImplantCode__c</fullName>
    <label>Impianto SAP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Subprocess__c.field-meta.xml
<CustomField>
    <fullName>Subprocess__c</fullName>
    <label>Sottoprocesso Voltura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderSubprocess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/VoltureType__c.field-meta.xml
<CustomField>
    <fullName>VoltureType__c</fullName>
    <label>Tipo Voltura</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ordinaria</fullName>
            </value>
            <value>
                <fullName>Mortis Causa</fullName>
            </value>
            <value>
                <fullName>Incorporazione societaria</fullName>
            </value>
            <value>
                <fullName>Oridnaria</fullName>
                <isActive>false</isActive>
                <label>Oridnaria</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_AttivazioneConModifica.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_AttivazioneConModifica</fullName>
    <active>true</active>
    <description>Record type per gli ordini di Prima attivazione con modifica</description>
    <label>Attivazione con Modifica</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_TemporaneaNuovaAtt.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_TemporaneaNuovaAtt</fullName>
    <active>true</active>
    <description>Record type per gli ordini di Temporanea Nuova Attivazione</description>
    <label>Temporanea Nuova Attivazione</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VAS.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VAS</fullName>
    <active>true</active>
    <label>VAS</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_Voltura.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Voltura</fullName>
    <active>true</active>
    <description>Record Type per processo di Voltura</description>
    <label>Voltura</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VolturaConSwitch.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VolturaConSwitch</fullName>
    <active>true</active>
    <label>Voltura Con Switch</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account del titolare del punto di fornitura</description>
    <label>Account Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points (Account)</relationshipLabel>
    <relationshipName>Service_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SAPContractCode__c.field-meta.xml
<CustomField>
    <fullName>SAPContractCode__c</fullName>
    <label>Codice Contratto SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SAPImplantCode__c.field-meta.xml
<CustomField>
    <fullName>SAPImplantCode__c</fullName>
    <description>SAPImplantCode__c</description>
    <externalId>true</externalId>
    <label>Impianto SAP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Impianto compl. in funzione</fullName>
            </value>
            <value>
                <fullName>Interruzione avviata</fullName>
            </value>
            <value>
                <fullName>Impianto parzialmente chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto compl. chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto in attivazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/recordTypes/HDT_RT_Ele.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Ele</fullName>
    <active>true</active>
    <description>Punto di fornitura Energia Elettrica</description>
    <label>Punto Elettrico</label>
</RecordType>

force-app/main/default/objects/ServicePoint__c/recordTypes/HDT_RT_Gas.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Gas</fullName>
    <active>true</active>
    <description>Punto di fornitura Gas</description>
    <label>Punto Gas</label>
</RecordType>

force-app/main/default/objects/ServiceRequest__c/ServiceRequest__c.object-meta.xml
<CustomObject>
    <description>oggetto per configurare la capability &quot;Matrice Compatibilità e Sequenzializzatore&quot;.  Ogni record rappresenta un processo (sales o post sales) i quali verranno utilizzati dal tool &quot;Compatibility&quot; di Pclick per valutare l&apos;eventuale inammissibilità del processo.</description>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifica l&apos;Account associato al processo.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>ServiceRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifica il BillingProfile associato al processo.</description>
    <label>Billing Profile</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>ServiceRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Identifica il settore merceologico del ServicePoint associato al Processo.</description>
    <label>Settore Merceologico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Energia Elettrica</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Multi</fullName>
            </value>
            <value>
                <fullName>Teleriscaldamento</fullName>
            </value>
            <value>
                <fullName>Acqua</fullName>
            </value>
            <value>
                <fullName>Ambiente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifica l&apos;Order (nei processi Sales) associato al processo.</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>ServiceRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Tipologia Processo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_ProcessType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifica il ServicePoint associato al processo</description>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>ServiceRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <description>Identifica l&apos;ID del ServicePoint associato al processo.</description>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Definisce lo stato del processo, se in lavorazione oppure chiuso/annullato.</description>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Completato</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Sequenzializzato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indica il tipo di oggetto che sarà associato alla Service Request (Order/Case).</description>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OrderSubprocess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Con Autolettura</fullName>
    </customValue>
    <customValue>
        <fullName>Retroattiva</fullName>
    </customValue>
    <description>Lista Sottoprocessi.</description>
    <masterLabel>Sottoprocesso Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_ProcessType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alert</fullName>
    </customValue>
    <customValue>
        <fullName>Allineamento Anagrafica</fullName>
    </customValue>
    <customValue>
        <fullName>Allineamento Canone RAI - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Annullamento contratti</fullName>
    </customValue>
    <customValue>
        <fullName>Annullamento passivo dal SII</fullName>
    </customValue>
    <customValue>
        <fullName>Annullamento Prestazione</fullName>
    </customValue>
    <customValue>
        <fullName>Attivazione ClickPay</fullName>
    </customValue>
    <customValue>
        <fullName>Attivazione VAS (billabile)</fullName>
    </customValue>
    <customValue>
        <fullName>Attivazione VAS (non billabile)</fullName>
    </customValue>
    <customValue>
        <fullName>Autoelettrica/modalità attivazione contratto</fullName>
    </customValue>
    <customValue>
        <fullName>Autolettura da cliente/da processo - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Autolettura da cliente/da processo - GAS</fullName>
    </customValue>
    <customValue>
        <fullName>Blocco al sollecito ed interessi</fullName>
    </customValue>
    <customValue>
        <fullName>BP/CA - errata categoria</fullName>
    </customValue>
    <customValue>
        <fullName>Caduta Linea/Chiamata Muta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio contatore non registrato - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio contatore non registrato - GAS</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio offerta - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio offerta - GAS</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio uso - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio uso fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Chiusura contatore - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Chiusura contatore - GAS</fullName>
    </customValue>
    <customValue>
        <fullName>Comportamento altri venditori - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Comportamento altri venditori - GAS</fullName>
    </customValue>
    <customValue>
        <fullName>Comportamento venditori HC - EE</fullName>
    </customValue>
    <customValue>
        <fullName>Comportamento venditori HC - GAS</fullName>
    </customValue>
    <customValue>
        <fullName>Comunicazione di Fallimento</fullName>
    </customValue>
    <customValue>
        <fullName>Comunicazione Pagamento</fullName>
    </customValue>
    <customValue>
        <fullName>Condizioni contrattuali errate - EE</fullName>
    </customValue>
    <description>Tipologia del processo della Service Request.</description>
    <masterLabel>Tipologia Processo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_ChildOrderProcessPrecheck.cls
/**
 * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
 * @date 06/02/2021
 * @description HDT_LC_ChildOrderProcessPrecheck.cls - Class that holds methods that are called from hdtChildOrderProcessPrecheck.js
 * @history Inserire Nome Cognome – Data Modifica – Descrizione della modifica
 */
public inherited sharing class HDT_LC_ChildOrderProcessPrecheck {

    private static HDT_QR_Order orderQr = new HDT_QR_Order();
    private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();
    private static HDT_UTL_Order orderUtl = new HDT_UTL_Order();
    private static HDT_QR_ServicePoint servicePointQr = new HDT_QR_ServicePoint();
    private static HDT_SRV_ServicePoint servicePointSrv = new HDT_SRV_ServicePoint();
    private static HDT_QR_Contract contractQr = new HDT_QR_Contract();
    private static HDT_QR_VoltureChangeManager  voltureChangeQr = new HDT_QR_VoltureChangeManager();
    private static HDT_QR_AnagAlignment regionalAdditionalQr = new HDT_QR_AnagAlignment();

    @AuraEnabled
    public static List<HDT_UTL_OrderProcessAssignment.HDT_WRP_Process> init(Order order){
        List<HDT_UTL_OrderProcessAssignment.HDT_WRP_Process> processesList = new List<HDT_UTL_OrderProcessAssignment.HDT_WRP_Process>();

        if (order.ServicePoint__c != null) {//returns processes that are different from VAS
            processesList = HDT_UTL_OrderProcessAssignment.getAvailableProcesses(order);
        }

        return processesList;
    }

    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @date 06/02/2021
     * @description Handle actions on "Avanti" click
     * @param orderId
     * @param String selectedProcess - selected process for child order
     * @param String deliberate
     */
    @AuraEnabled
    public static String next(Order order,String orderId, Map<String,String> selectedProcessObject, String deliberate, Map<String,String> extraParams, ServiceRequest__c srRequest){

        String compatibility='';
        ServiceRequest__c srvReq = new ServiceRequest__c();
        srvReq.ServicePointCode__c= srRequest.ServicePointCode__c;
        srvReq.Status__c= srRequest.Status__c;
        srvReq.Order__c= srRequest.Order__c;
        srvReq.CommoditySector__c= srRequest.CommoditySector__c;
        srvReq.Type__c= srRequest.Type__c;
        if(srRequest.ServicePoint__c != null){
            srvReq.ServicePoint__c= srRequest.ServicePoint__c;
        }else{
            srvReq.Account__c= srRequest.Account__c;
            srvReq.BillingProfile__c= srRequest.BillingProfile__c;
        }
        srvReq.ProcessType__c= srRequest.ProcessType__c;
        HDT_SRV_ServiceRequest.createRecord(srvReq);
        wrts_prcgvr.ObjectCompatibility_1_0.CheckResult result = HDT_UTL_MatrixCompatibility.checkCompatibility(srvReq);
        
        if(!result.incompatibilities.isEmpty()){
            compatibility = HDT_UTL_MatrixCompatibility.getIncompatibilityMessage((ServiceRequest__c[])result.incompatibilities);
            HDT_SRV_ServiceRequest.deleteRecord(srvReq);
        }
        if(compatibility == '' || compatibility == order.OrderNumber){
            system.debug('extraParams: ' + extraParams);

            String recordTypeId = orderSrv.getRecordTypeIdByDeveloperName(selectedProcessObject.get('recordType'));

            //INIZIO SVILUPPI EVERIS
            Order newOrder = new Order();    
            //FINE SVILUPPI EVERIS

            String processType = selectedProcessObject.get('processType');
            String processCode = selectedProcessObject.get('processCode');

            switch on selectedProcessObject.get('recordType') {
                //INIZIO SVILUPPI EVERIS
                when 'HDT_RT_Voltura', 'HDT_RT_VolturaConSwitch'
                {
                    String sapCode = '';
                    //@frpanico predefault "Processo", "Sottoprocesso", "Tipo Voltura", "Codice Causale", "Data Decorrenza", "Contratto", "Codice Contratto"
                    List<Contract> contracts = contractQr.getContractFromServicePoint(order.ServicePoint__c);
                    System.debug('Condition ' + !contracts.isEmpty());
                    if(!contracts.isEmpty())
                    {
                        List<AccountContactRelation> exitingContacts = voltureChangeQr.getContactInfosByAccountId(contracts[0].AccountId);
                        newOrder.PreviousCustomer__c = exitingContacts[0]?.ContactId;
                        newOrder.ContractReference__c = contracts[0]?.Id;
						sapCode = contracts[0].SAPContractCode__c;
                    }
                    processType = selectedProcessObject.get('recordType').equalsIgnoreCase('HDT_RT_Voltura') ? 'Voltura' : 'Voltura con Switch';
                    newOrder.Subprocess__c = 'Standard';
                    newOrder.VoltureType__c = 'Ordinaria';
                    processCode = extraParams.get('servicePointType') == 'HDT_RT_Ele'? 'VT1' : 'VTG';
                    newOrder.EffectiveDate__c = orderSrv.addBusinessDay(System.today(), 3);
                    newOrder.SapContractCode__c = sapCode;
                    newOrder.Id = orderId;
                    //@frpanico "Chiamata Arricchimento Dati" per ulteriori predefault
                    callDataEnrichment(order.SAPImplantCode__c,sapCode,JSON.serialize(newOrder));
                    //newOrder = orderUtl.enrichOrder(newOrder);
                    //orderSrv.updateRecord(newOrder);
                    String tax = order.CommodityFormula__c == 'Energia Elettrica' ? newOrder.ExciseEle__c : newOrder.ExciseGAS__c;
                    String city = order.SupplyCity__c;
                    String region = '';
                    newOrder.RegionalAdditional__c = regionalAdditionalQr.findRegionalAdditional(tax, city, region);
                    newOrder.ExciseRate__c = order.CommodityFormula__c == 'Energia Elettrica' ? voltureChangeQr.getExciseTranscode(tax)[0].Excise__c : null;
                }
                when 'HDT_RT_AttivazioneConModifica' {
                    newOrder.RequestOption__c = HDT_UTL_OrderFieldsAlignment.calculateRequestedOption(order.ImplantType__c, order.PowerRequested__c);
                }
                when 'HDT_RT_TemporaneaNuovaAtt' {
                    newOrder.ConnectionType__c = null;
                }
            }

            switch on processType {
                when 'Switch in Ripristinatorio'{
                    HDT_UTL_OrderProcessAssignment.switchInRipristinatorioAction(order);
                    newOrder.SignedDate__c = Date.today();
                    newOrder.WaiverRightAfterthought__c = 'Si';
                }
                when 'Prima Attivazione'{
                    processType = 'Prima Attivazione ' + ('In Delibera'.equalsIgnoreCase(deliberate) ? 'In delibera' : 'Fuori delibera');
                    processCode = 'In Delibera'.equalsIgnoreCase(deliberate) ? 'A40' : 'A01';
                }
            }

            //EVERIS: MODIFICATA LOGICA DI UPDATE PER GESTIRE I PREDEFAULT
            newOrder.Id = orderId;
            newOrder.RecordTypeId = recordTypeId;
            newOrder.Step__c = 2;
            newOrder.Deliberation__c = deliberate;
            newOrder.ProcessType__c = processType;
            newOrder.ProcessCode__c = processCode;
            newOrder.Phase__c = 'Bozza';

            //Logica Superficie Servita Start
            newOrder.SurfaceServed__c = (extraParams.get('servicePointType') == 'HDT_RT_Gas' && selectedProcessObject.get('recordType') != 'HDT_RT_Voltura') ? 75 : null;
            //Logica Superficie Servita End
            orderSrv.updateRecord(newOrder);
            //EVERIS 
        }
        return compatibility;

    }
    
    @TestVisible
    private static String getServicePointTypeFromOrder(String orderId) {
        orderSrv.checkReadAccess('ContractReference__r.ServicePoint__c');
        Order order = orderQr.getRecordById(orderId);

        servicePointSrv.checkReadAccess('RecordType.DeveloperName');
        List<ServicePoint__c> servicePointList = servicePointQr.getRecordById(order.ContractReference__r.ServicePoint__c, 'RecordType.DeveloperName');

        return servicePointList[0].RecordType.DeveloperName;
    }
	/**@frpanico 26/10/2021
     * Modified method
     * Instead of hardcoding and handling each single field of the response  
     * An handler method is called
     */
    @TestVisible
    @Future(Callout = true)
    private static void callDataEnrichment(String servicePointCode, String contractCode, String newOrderSerialized)
    {
        Order newOrder = (Order)JSON.deserialize(newOrderSerialized, Order.class);
        Order orderToUpdate = new Order();
        orderToUpdate.Id = newOrder.Id;
        HDT_SRV_VoltureChangeManager voltureChangeSrv = new HDT_SRV_VoltureChangeManager();
        List<Order> orderList = new List<Order>();
        try
        {
            String serializedResponse = HDT_WS_ArricchimentoDatiTemp.submitRequest(servicePointCode, contractCode);
            List<HDT_WS_ArricchimentoDatiTemp.HDT_WRP_ArricchimentoPosizioni> positions = new List<HDT_WS_ArricchimentoDatiTemp.HDT_WRP_ArricchimentoPosizioni>();
            positions = (List<HDT_WS_ArricchimentoDatiTemp.HDT_WRP_ArricchimentoPosizioni>)
                    JSON.deserialize(serializedResponse, List<HDT_WS_ArricchimentoDatiTemp.HDT_WRP_ArricchimentoPosizioni>.class);
            
            Map<String,List<Object>> inputMap = new Map<String, List<Object>>
            {
                'posizioni' => positions,
                'sobjList' => new List<Order>{orderToUpdate}
            };

             orderList = voltureChangeSrv.handleResponseDataEnrichment(inputMap);

        } catch(Exception e){
            System.debug(LoggingLevel.DEBUG, 'Error');
        } 

        HDT_UTL_DatabaseService.updateSObject(orderList);
    }

    @AuraEnabled
    public static Boolean checkVasAndCommodity(String parentOrdId){
        try {
            List<Order> childOrders = orderQr.getChildOrdersByParentId(parentOrdId);

            Order ordCommodity = new Order();
            Order vasOrd = new Order();

            if (childOrders.size() > 1) {
                for (Order ord : childOrders) {
                    if (ord.RecordType.DeveloperName != 'HDT_RT_VAS') {
                        ordCommodity = ord;
                    } else {
                        vasOrd.Id = ord.Id;
                    }
                }

                if (vasord.Id != null) {
                    vasOrd.IncomingCreditCheckResult__c = ordCommodity.IncomingCreditCheckResult__c;
                    vasOrd.OutgoingCreditCheckResult__c = ordCommodity.OutgoingCreditCheckResult__c;
                    vasOrd.CreditCheckDescription__c = ordCommodity.CreditCheckDescription__c;
                    orderSrv.updateRecord(vasOrd);
                }
            }

            return childOrders.size() > 1 ? true : false;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Map<String, Object> checkContendibilita(Order order){

        try {
            return HDT_SRV_QservHandler.handler(order);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}