force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SAPContractCode__c.field-meta.xml
<CustomField>
    <fullName>SAPContractCode__c</fullName>
    <description>Numero Contratto Sap</description>
    <externalId>true</externalId>
    <label>Codice Contratto SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare un contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SapContractCode__c.field-meta.xml
<CustomField>
    <fullName>SapContractCode__c</fullName>
    <label>Codice Contratto SAP</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/SAPContractCode__c.field-meta.xml
<CustomField>
    <fullName>SAPContractCode__c</fullName>
    <label>Codice Contratto SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_UTL_ContractProcessTst.cls
/**
* @author 'Keltin Mesonjesi' (keltin.mesonjesi@protonmail.ch);
* @date 19/04/2020
* @description Class HDT_UTL_ContractProcess.cls
* @history Lucas da Silva Fernandes – 19/04/2020 – Updated Header
*/

@isTest
public with sharing class HDT_UTL_ContractProcessTst {

    @TestSetup
    static void setup(){

        HDT_UTL_DataFactoryTst.pClickInstance();
        HDT_UTL_DataFactoryTst.pClickOrderPhase();
        
        List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<BillingProfile__c> bpList = HDT_UTL_DataFactoryTst.createBillingProfile(1, true, accList[0].Id);
        List<ServicePoint__c> spList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);

        List<Order> orderList = HDT_UTL_DataFactoryTst.createOrder(1, false, accList[0].Id, 'Bozza');
        orderList[0].BillingProfile__c = bpList[0].Id;
        orderList[0].ServicePoint__c = spList[0].Id;
        insert orderList;

        List<Contract> cttList = HDT_UTL_DataFactoryTst.createContract(1, false, accList[0].Id);
        cttList[0].SBQQ__Order__c = orderList[0].Id;
        insert cttList;
    }

    @isTest
    public static void testOrderCompletataPhaseManagement() {

        Test.startTest();

        List<Contract> cttList = [SELECT Id, SBQQ__Order__c, BillingProfile__c FROM Contract WHERE SAPContractCode__c='3011913470' LIMIT 1];
        System.debug('cttList: '+cttList);
        List<Order> orderList = [SELECT Id, BillingProfile__c FROM Order WHERE Name = 'testOrderName0' LIMIT 1];
        System.debug('orderList: '+orderList);
        HDT_UTL_ContractProcess.orderCompletataPhaseManagement(cttList);

        System.assertEquals(orderList[0].Id, cttList[0].SBQQ__Order__c, 'Order Id Match');
        System.assertNotEquals(null, cttList[0].SBQQ__Order__c, 'Order Id mismatch');

        Test.stopTest();
    }

    @isTest
    public static void testmoveOut() {

        Test.startTest();

        List<Contract> cttList = [SELECT Id,Status,EndDate FROM Contract LIMIT 1];
        List<Order> orderList = [SELECT Id FROM Order LIMIT 1];
        
        orderList[0].ContractReference__c = cttList[0].Id;

        update orderList;

        HDT_UTL_ContractProcess.moveOut( orderList[0].Id, 'ContractReference__c' );

        cttList = [SELECT Id,Status,EndDate FROM Contract LIMIT 1];

        System.assertEquals(cttList[0].Status, 'Cessato','Status non in Cessato');
        System.assertEquals(cttList[0].EndDate, date.Today(), 'Data non aggiornata ad Oggi correttamente');

        Test.stopTest();
    }

}