force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status; Ereditato da SAP</description>
    <label>Status del Profilo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l&apos;oggetto Vendita</description>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare un contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsVAS__c.field-meta.xml
<CustomField>
    <fullName>IsVAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Ordine di riferimento)</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Stato</description>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullata</fullName>
            </value>
            <value>
                <fullName>Confermata</fullName>
            </value>
            <value>
                <fullName>In Sviluppo</fullName>
            </value>
            <value>
                <fullName>Vendibile</fullName>
            </value>
            <value>
                <fullName>Scaduta</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Attiva</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SaleServiceItem__c/SaleServiceItem__c.object-meta.xml
<CustomObject>
    <description>Oggetto giunzione tra opportunity/quote e Service point</description>
    <label>Sale Service Item</label>
    <nameField>
        <label>SaleServiceItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Service Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SaleServiceItem__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Sale Service Items</relationshipLabel>
    <relationshipName>SaleServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziareun contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (CPQ) (Contratto di riferimento)</relationshipLabel>
    <relationshipName>QuotesCPQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/IsVAS__c.field-meta.xml
<CustomField>
    <fullName>IsVAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Quotes (CPQ)</relationshipLabel>
    <relationshipName>QuotesCPQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune Fornitura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Impianto compl. in funzione</fullName>
            </value>
            <value>
                <fullName>Interruzione avviata</fullName>
            </value>
            <value>
                <fullName>Impianto parzialmente chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto compl. chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto in attivazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_LC_SaleServiceItemsTilesTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 04/08/2021
 * @description Test Class for HDT_LC_SaleServiceItemsTiles.cls
 * @history Fabricio Petkevicius Nunes – 04/08/2021 – Created class
 */
@isTest
public class HDT_LC_SaleServiceItemsTilesTst{
	private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
	@TestSetup
	static void setup(){

		Id standardUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.HERA_STANDARD_USER_NAME);
		Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.HERA_STANDARD_USER_NAME);

		User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);

		internalUser.UserPermissionsMarketingUser=true;

		insert internalUser;

		List<PermissionSetAssignment> permissionSetAssignments=new List<PermissionSetAssignment>{HDT_UTL_DataFactoryTst.assignPermissionSet(internalUser, constants.PERMISSIONSET_HDT_SALESFORCE_CPQ_ADMIN_NAME, false), HDT_UTL_DataFactoryTst.assignPermissionSet(internalUser, constants.PERMISSIONSET_HDT_SALESFORCE_CPQ_LICENSE_NAME, false)};

		insert permissionSetAssignments;

		System.runAs(internalUser){

			HDT_UTL_DataFactoryTst.pClickInstance();
			HDT_UTL_DataFactoryTst.pClickOrderPhase();

			List<Account> accounts=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');

			List<Opportunity> opportunities=HDT_UTL_DataFactoryTst.createOpportunity(1, true);

			List<Contract> contracts=HDT_UTL_DataFactoryTst.createContract(1, true, accounts[0].Id);

			List<Sale__c> sales=HDT_UTL_DataFactoryTst.createSale(1, true, accounts[0].Id, 'Bozza');

			List<ServicePoint__c> servicePoints=HDT_UTL_DataFactoryTst.createServicePoint(1, true);

			List<Product2> products=HDT_UTL_DataFactoryTst.createProduct2(1, false);
			products[0].Family='VAS Opzione prodotto';
			products[0].Name='POD';
			insert products;

			Id pricebookId=Test.getStandardPricebookId();

			List<PricebookEntry> pricebookEntry=HDT_UTL_DataFactoryTst.createPricebookEntry(products, true, pricebookId);

			List<BillingProfile__c> billingProfiles=HDT_UTL_DataFactoryTst.createBillingProfile(1, true, accounts[0].Id);

			List<Order> orders=HDT_UTL_DataFactoryTst.createOrderWithPricebook(1, false, accounts[0].Id, sales, pricebookId);
			orders[0].BillingProfile__c=billingProfiles[0].Id;

			insert orders;

			List<SBQQ__Quote__c> quotes=HDT_UTL_DataFactoryTst.createQuote(1, false, orders[0].Id, opportunities[0].Id, sales[0].Id, 'Amendment');

			quotes[0].SBQQ__Account__c=accounts[0].Id;
			quotes[0].SBQQ__PricebookId__c=pricebookId;
			quotes[0].OrderReference__c=orders[0].Id;
			quotes[0].ContractReference__c=contracts[0].Id;
			quotes[0].SupplyCity__c='Roma';
			//quotes[0].IsVAS__c=true;

			insert quotes;

			opportunities[0].SBQQ__PrimaryQuote__c=quotes[0].Id;
			opportunities[0].Account=accounts[0];
			opportunities[0].Sale__c=sales[0].Id;

			update opportunities;

			orders[0].SBQQ__Quote__c=quotes[0].Id;

			update orders;

            List<SaleServiceItem__c> saleServiceItens = HDT_UTL_DataFactoryTst.createSaleServiceItem(1, true, opportunities[0].Id, quotes[0].Id, servicePoints[0].Id);
		}
	}

	@isTest
	static void testgetTiles(){

		User u=[SELECT Id
		        FROM User
		        WHERE Alias='crmuser'
		        LIMIT 1];


		System.runAs(u){
			Test.startTest();

			Sale__c tSale=[SELECT Id, Status__c
			               FROM Sale__c
			               WHERE Status__c='Bozza'
			               LIMIT 1];

			Map<String, List<List<SObject>>> tgetTiles=HDT_LC_SaleServiceItemsTiles.getTiles(tsale.Id);

			System.debug('tgetTiles = '+tgetTiles);

			System.assertEquals(2, tgetTiles.size(), 'Return is wrong');

			System.assertNotEquals(1, tgetTiles.size(), 'getTiles did not work correctly');

			Test.stopTest();

		}
	}

	@isTest
	static void testdeleteTile(){

		User u=[SELECT Id
		        FROM User
		        WHERE Alias='crmuser'
		        LIMIT 1];

		System.runAs(u){
			Test.startTest();

			Opportunity tOpp=[SELECT Id, StageName
			                  FROM Opportunity
			                  WHERE StageName='Negotiation'
			                  LIMIT 1];

			HDT_LC_SaleServiceItemsTiles.deleteTile(tOpp.Id, 'Errata operativita');

			HDT_LC_SaleServiceItemsTiles.deleteTile(tOpp.Id, 'Volonta cliente');

			Opportunity tOppUpdt=[SELECT Id, StageName
			                      FROM Opportunity
			                      WHERE StageName='Closed Lost'
			                      LIMIT 1];


			System.debug('tOppUpdt = '+tOppUpdt);

			System.assertEquals('Closed Lost', tOppUpdt.StageName, 'Opportunity not updated');

			System.assertNotEquals('Negotiation', tOppUpdt.StageName, 'deleteTile did not work correctly');

			Test.stopTest();

		}
	}
}