force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Profile</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Casi</relationshipLabel>
    <relationshipName>Casi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Nome del Cluster a cui appartiene un processo.</description>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CompetentOffice__c.field-meta.xml
<CustomField>
    <fullName>CompetentOffice__c</fullName>
    <description>L&apos;ufficio competente inerente il case in oggetto</description>
    <label>Ufficio competente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCM</fullName>
            </value>
            <value>
                <fullName>Marche Multiservizi Spa</fullName>
            </value>
            <value>
                <fullName>Mercato Aziende</fullName>
            </value>
            <value>
                <fullName>Mercato Aziende In</fullName>
            </value>
            <value>
                <fullName>Mercato Aziende Out</fullName>
            </value>
            <value>
                <fullName>Mercato Famiglie</fullName>
            </value>
            <value>
                <fullName>Procedure Concorsuali</fullName>
            </value>
            <value>
                <fullName>Marche Multiservizi SpaMercato</fullName>
            </value>
            <value>
                <fullName>AziendeMercato aziende InMercato</fullName>
            </value>
            <value>
                <fullName>Aziende outMercato</fullName>
            </value>
            <value>
                <fullName>FamiglieProcedure Concorsuali</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup all&apos;object Contract</description>
    <label>Contratto</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsContainer__c.field-meta.xml
<CustomField>
    <fullName>IsContainer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contenitore?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Recapito Telefonico</description>
    <label>PhoneNumber</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_Morosita.cls
public inherited sharing class HDT_UTL_Morosita {

    public String transcodeProcess(String process){
        string result;

        switch on process{
            when 'Sospensione Fornitura'{
                result = 'Sospensione Fornitura';
            }
            when 'Riattivazione Fornitura'{
                result = 'Riattivazione Fornitura';
            }
            when 'Risoluzione no sospensione'{
                result = 'Risoluzione No Sospensione';
            }
            when 'Risoluzione no disalimentabile'{
                result = 'Risoluzione No Disalimentabile';
            }
            when else{
                result = process;
            }
            
        }

        return result;
    }

    public String handleContainer(Case currentCase){
        String containerId = '';

        Case containerCase = new case();
        containerCase.Cluster__c = currentCase.Cluster__c;
        containerCase.Type = 'Contenitore Morosità';
        containerCase.AccountId = currentCase.AccountId;
        containerCase.ContactId = currentCase.ContactId;
        containerCase.PhoneNumber__c = currentCase.PhoneNumber__c;
        containerCase.Email__c = currentCase.Email__c;
        containerCase.Contract__c = currentCase.Contract__c;
        containerCase.BillingProfile__c = currentCase.BillingProfile__c;
        containerCase.IsContainer__c = true;
        containerCase.RecordTypeId = currentCase.RecordTypeId;
        containerCase.ServicePoint__c = currentCase.ServicePoint__c;
        containerCase.CompanyOwner__c = currentCase.CompanyOwner__c;
        containerCase.CompetentOffice__c = currentCase.CompetentOffice__c;
        containerCase.Phase__c = 'Bozza';
        containerCase.Status = 'New';
        containerCase.Priority = currentCase.Priority != null && currentCase.Priority != '' ? currentCase.Priority : '3';
        containerCase.Origin = currenCase.Origin;
        containerId = JSON.serialize(containerCase);
        
        return containerId;
    }
}