force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Canale verso il quale verrà erogata la campagna</description>
    <label>Canale</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefonico Inbound</fullName>
            </value>
            <value>
                <fullName>Sportello</fullName>
            </value>
            <value>
                <fullName>SOL</fullName>
            </value>
            <value>
                <fullName>Telefonico Outbound</fullName>
            </value>
            <value>
                <fullName>Door to Door</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Push</fullName>
            </value>
            <value>
                <fullName>Cartaceo</fullName>
            </value>
            <value>
                <fullName>Bolletta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/StaticTextMessageBill__c.field-meta.xml
<CustomField>
    <fullName>StaticTextMessageBill__c</fullName>
    <description>Testo Libero, obbligatorio se “Tipo messaggio in Bolletta” = ‘Testo statico e codice’</description>
    <label>Testo statico messaggio Bolletta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <description>Valorizzabile dall’utente Marketing Cloud con tutti gli identificativi dei Contratti dello stesso Contatto che si vogliono inserire nel Target. Se il campo è vuoto il CRM interpreta come Target tutti i contratti legati al Contatto.</description>
    <label>Riferimento Contratti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/isWsBollettaInvoked__c.field-meta.xml
<CustomField>
    <fullName>isWsBollettaInvoked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WS Bolletta Invoked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/PromoCommercialCode__c.field-meta.xml
<CustomField>
    <fullName>PromoCommercialCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l’oggetto che definisce i codici commerciali. Il campo è gestito in automatico dal sistema e non è editabile dall’utente</description>
    <label>Codice Commerciale</label>
    <referenceTo>CommercialCode__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commercial_Code_Batch_Context__c/Commercial_Code_Batch_Context__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Commercial Code Batch Context</label>
</CustomObject>

force-app/main/default/objects/Commercial_Code_Batch_Context__c/fields/BollettaDone__c.field-meta.xml
<CustomField>
    <fullName>BollettaDone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BollettaDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Commercial_Code_Batch_Context__c/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <label>CampaignId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commercial_Code_Batch_Context__c/fields/CampaignMemberId__c.field-meta.xml
<CustomField>
    <fullName>CampaignMemberId__c</fullName>
    <label>CampaignMemberId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commercial_Code_Batch_Context__c/fields/CommercialCodeDone__c.field-meta.xml
<CustomField>
    <fullName>CommercialCodeDone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CommercialCodeDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/CommercialCode__c.object-meta.xml
<CustomObject>
    <label>Codice Commerciale</label>
    <nameField>
        <label>Codice Commerciale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codici Commerciali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommercialCode__c/fields/FullCode__c.field-meta.xml
<CustomField>
    <fullName>FullCode__c</fullName>
    <label>Codice</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_BA_CampaignBolletta.cls
public with sharing class HDT_BA_CampaignBolletta implements Database.Batchable<Commercial_Code_Batch_Context__c>, Database.AllowsCallouts {

    public Iterable<Commercial_Code_Batch_Context__c> start(Database.BatchableContext bc) {
        List<Commercial_Code_Batch_Context__c> context = [SELECT Id, CampaignId__c, CampaignMemberId__c
                                                    		FROM Commercial_Code_Batch_Context__c 
                                                    		WHERE CommercialCodeDone__c = TRUE AND BollettaDone__c = FALSE];
        return context;
    }

    public void execute(Database.BatchableContext BC, List<Commercial_Code_Batch_Context__c> context) {
        Set<String> campaignIds = new Set<String>();
        Set<String> campaignMemberIds = new Set<String>();
        for(Commercial_Code_Batch_Context__c curObj : context){
            campaignIds.add(curObj.CampaignId__c);
            campaignMemberIds.add(curObj.CampaignMemberId__c);
        }
        List<CampaignMember> scope = [SELECT ContractReference__c, PromoCommercialCode__r.fullcode__c, Campaign.Name, Campaign.Description, Campaign.StaticTextMessageBill__c, Campaign.Channel__c 
                                        FROM CampaignMember 
                                        WHERE Id IN :campaignMemberIds AND CampaignId IN :campaignIds AND ContractReference__c != null AND isWsBollettaInvoked__c = false AND Campaign.Channel__c INCLUDES ('Bolletta') WITH SECURITY_ENFORCED];
        List<CampaignMember> membersToUpdate = new List<CampaignMember>();
        List<HDT_WS_CampaignBolletta.HDT_WS_CampaignBollettaRequest> wsReqList = new List<HDT_WS_CampaignBolletta.HDT_WS_CampaignBollettaRequest>();

        for (CampaignMember cm : scope) {
                HDT_WS_CampaignBolletta.HDT_WS_CampaignBollettaRequest wsReq = new HDT_WS_CampaignBolletta.HDT_WS_CampaignBollettaRequest();
                wsReq.campaignId = cm.CampaignId;
                wsReq.campaignName = cm.Campaign.Name;
                wsReq.campaignDescription = cm.Campaign.Description;
                wsReq.comunicationText = cm.Campaign.StaticTextMessageBill__c == null ? cm.PromoCommercialCode__r.fullcode__c : cm.Campaign.StaticTextMessageBill__c + ' ' + cm.PromoCommercialCode__r.fullcode__c;
                wsReq.contractCode = cm.ContractReference__c != null ? cm.ContractReference__c : '';
                
                System.debug(wsReq);
                wsReqList.add(wsReq);
        }
        
        //WS call
        if (wsReqList.size() > 0) {
            System.debug(wsReqList);
            HDT_WS_Response res = HDT_WS_CampaignBolletta.channelBolletta(wsReqList);
            System.debug(res);
            if (res.status != 'failed') {
                for (CampaignMember cm : scope) {
                    CampaignMember newCm = new CampaignMember();
                    newCm.Id = cm.Id;
                    newCm.isWsBollettaInvoked__c = true;
                    membersToUpdate.add(newCm);
                }
                if (membersToUpdate.size() > 0) {
                    update membersToUpdate;
                }
            }
        }
        
        System.debug('@@@ deleting worked context');
        delete context;
    }

    public void finish(Database.BatchableContext bc){
        System.debug('-------- finish batch');
        List<Commercial_Code_Batch_Context__c> remainingContext = [SELECT Id, CampaignId__c, CampaignMemberId__c
                                                    		        FROM Commercial_Code_Batch_Context__c 
                                                    		        WHERE CommercialCodeDone__c = TRUE AND BollettaDone__c = FALSE];
        if(remainingContext.size()>0) System.scheduleBatch(new HDT_BA_CampaignBolletta(), 'HDT_BA_CampaignBolletta', 1, 100);
    }
}