force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Canale verso il quale verrà erogata la campagna</description>
    <label>Canale</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefonico Inbound</fullName>
            </value>
            <value>
                <fullName>Sportello</fullName>
            </value>
            <value>
                <fullName>SOL</fullName>
            </value>
            <value>
                <fullName>Telefonico Outbound</fullName>
            </value>
            <value>
                <fullName>Door to Door</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Push</fullName>
            </value>
            <value>
                <fullName>Cartaceo</fullName>
            </value>
            <value>
                <fullName>Bolletta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agenzia Teleseller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/GenericField1__c.field-meta.xml
<CustomField>
    <fullName>GenericField1__c</fullName>
    <description>Campo testo libero valorizzato dall&apos;utente durante il targeting. Utilizzato per comunicare info puntuali all’Operatore o per indirizzare il comportamento degli Script in funzione del valore dei campi.</description>
    <label>Campo 01</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/SurveyResponse__c.field-meta.xml
<CustomField>
    <fullName>SurveyResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Response</label>
    <referenceTo>SurveyResponse__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup per ricercare una campagna esistente e associarla al Case</description>
    <label>Campagna</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Nome del Cluster a cui appartiene un processo.</description>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommercialCode__c/CommercialCode__c.object-meta.xml
<CustomObject>
    <label>Codice Commerciale</label>
    <nameField>
        <label>Codice Commerciale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codici Commerciali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommercialCode__c/fields/ActualUsesEE__c.field-meta.xml
<CustomField>
    <fullName>ActualUsesEE__c</fullName>
    <label>Utilizzi Effettivi EE</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/ActualUsesGAS__c.field-meta.xml
<CustomField>
    <fullName>ActualUsesGAS__c</fullName>
    <label>Utilizzi Effettivi GAS</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/ActualUsesVAS__c.field-meta.xml
<CustomField>
    <fullName>ActualUsesVAS__c</fullName>
    <label>Utilizzi Effettivi VAS</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campagna</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Codici Commerciali</relationshipLabel>
    <relationshipName>Codici_Commerciali</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/FullCode__c.field-meta.xml
<CustomField>
    <fullName>FullCode__c</fullName>
    <label>Codice</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/MaximalUsesEE__c.field-meta.xml
<CustomField>
    <fullName>MaximalUsesEE__c</fullName>
    <description>Numerico, gestito dal CRM alla generazione del codice</description>
    <label>Massimale Utilizzi EE</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/MaximalUsesGAS__c.field-meta.xml
<CustomField>
    <fullName>MaximalUsesGAS__c</fullName>
    <description>Numerico, gestito dal CRM alla generazione del codice</description>
    <label>Massimale Utilizzi GAS</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/MaximalUsesVAS__c.field-meta.xml
<CustomField>
    <fullName>MaximalUsesVAS__c</fullName>
    <description>Numerico, gestito dal CRM alla generazione del codice</description>
    <label>Massimale Utilizzi VAS</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/RecoveryUsesEE__c.field-meta.xml
<CustomField>
    <fullName>RecoveryUsesEE__c</fullName>
    <label>Recuperi Utilizzi EE</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/RecoveryUsesGAS__c.field-meta.xml
<CustomField>
    <fullName>RecoveryUsesGAS__c</fullName>
    <label>Recuperi Utilizzi GAS</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/fields/RecoveryUsesVAS__c.field-meta.xml
<CustomField>
    <fullName>RecoveryUsesVAS__c</fullName>
    <label>Recuperi Utilizzi VAS</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyResponse__c/SurveyResponse__c.object-meta.xml
<CustomObject>
    <description>Survey Response</description>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyResponse__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campagna</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>SurveyResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_SalesChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>HC Point</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie SME</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Punti Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
        <isActive>false</isActive>
        <label>Consip</label>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <isActive>false</isActive>
        <label>Reseller</label>
    </customValue>
    <description>Canale vendita associato all&apos;utente</description>
    <masterLabel>Canale Vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_CampaignsController.cls
public inherited sharing class HDT_LC_CampaignsController {

    private static HDT_QR_CampaignMember campaignMemberQr = new HDT_QR_CampaignMember();
    private static HDT_SRV_CampaignMember campaignMemberSrv = new HDT_SRV_CampaignMember();
    private static HDT_QR_Contact contactQr = new HDT_QR_Contact();
    private static HDT_QR_Case caseQr = new HDT_QR_Case();
    private static HDT_SRV_Case caseSrv = new HDT_SRV_Case();
    private static HDT_SRV_CommercialCode commercialCodeSrv = new HDT_SRV_CommercialCode();
    private static HDT_QR_Campaign campaignQr = new HDT_QR_Campaign();

    @AuraEnabled(cacheable=true)
    public static List <CampaignMember> getCampaigns(String id, String objectName, String category, String channel) {
        campaignMemberSrv.checkReadAccess('Campaign.Name,Campaign.Status,Campaign.Channel__c,Campaign.EndDate');

        if (objectName == 'Contact') {
            //return all active campaigns related to this Contact
            return  campaignMemberQr.getActiveCampaignsByContact(id);
        } else if(objectName == 'Lead') {
            //return all active campaigns related to this Lead
            return campaignMemberQr.getActiveCampaignsByLead(id);
        } else if(objectName == 'Account') {
            //return all active campaigns related to all contacts related to this Account
            List<String> contacts = contactQr.getContactsIdByAccountId(id);
            if (category != '') {
                if (channel != '') {
                    return campaignMemberQr.filterCampaignsByCategoryAndChannel(contacts, category, channel);
                }
                return campaignMemberQr.filterCampaignsByCategory(contacts, category);
            }
            return campaignMemberQr.getCampaignsFilteredByContacts(contacts);
        } else {
            return null;
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Campaign> getOutboundCampaigns() {
        return  campaignQr.getOutboundCampaigns();
    }
    @AuraEnabled
    public static CampaignMember updateCampaignMemberStatus(String campaignMemberId, String statusValue){
        try {
            CampaignMember cm = new CampaignMember(
                Id = campaignMemberId,
                Status = statusValue
            );
            campaignMemberSrv.updateRecord(cm);
            return cm;
        } catch (Exception e) {
            System.debug(e.getMessage());
            return null;
        }
    }

    @AuraEnabled
    public static List<CampaignMember> updateCampaignMembersStatus(List<String> campaignMemberIds, String statusValue){
        List<CampaignMember> membersToUpdate = new List<CampaignMember> ();
        for (String id : campaignMemberIds) {
            CampaignMember cm = new CampaignMember(
                Id = id,
                Status = statusValue
            );
            membersToUpdate.add(cm);
        }
        try {
            campaignMemberSrv.updateRecords(membersToUpdate);
            return membersToUpdate;
        } catch (Exception e) {
            System.debug(e.getMessage());
            return null;
        }

    }

    @AuraEnabled
    public static Case createNewCase(Case c){
        Case newCase = caseSrv.createRecord(c);
        system.debug(newCase);
        return newCase;
    }
    @AuraEnabled
    public static String getServiceCatalogUrlByCaseType(Case c){
        //Case newCase = caseSrv.createRecord(c);
        String s = HDT_QR_ServiceCatalog.getServiceLinkItemAccountRedirectUrlByCategory(c.cluster__c, c.type);
        String res = '';
        if(s != null){
            res = s.replace('{!Id}',c.AccountId);
            res = res + '&c__campaignId=' + c.Campaign__c;
            //s = s.replace('', arg1)
        }
        else{
            res = null;
        }

        return res;
    }


    @AuraEnabled
    public static List<CampaignMember> getUnassignedCampaignMembers(String campaignId) {
        return  campaignMemberQr.getUnassignedCampaignMembers(campaignId);
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getAccountsforCampaignMembers() {
        return  campaignMemberQr.getAccountsforCampaignMembers();
    }

    @AuraEnabled
    public static CampaignMember getAccountAndCampaign(String campaignMemberId) {
        campaignMemberSrv.checkReadAccess('ContactId,LeadId,CampaignId,GenericField1__c');
        return  campaignMemberQr.getAccountAndCampaign(campaignMemberId);
    }

    @AuraEnabled
    public static List<CampaignMember> assignCampaignMemberAgency(String campaignId, List<Id> toAssignObj){
        List<CampaignMember> allUnassignedMembers = campaignMemberQr.getUnassignedCampaignMembers(campaignId);
        List<CampaignMember> assignedMembers = new List<CampaignMember>();
        for (Id agencyId : toAssignObj) {
            CampaignMember cm = allUnassignedMembers[0];
            cm.Agency__c = agencyId;
            assignedMembers.add(cm);
            allUnassignedMembers.remove(0);            
        }

        campaignMemberSrv.updateRecords(assignedMembers);
        return assignedMembers;
    }

    @AuraEnabled
    public static CampaignMember updateCampaignMemberSurveyResponse(String campaignMemberId, String surveyResponseId){
        try {
            CampaignMember cm = new CampaignMember(
                Id = campaignMemberId,
                SurveyResponse__c = surveyResponseId
            );
            campaignMemberSrv.updateRecord(cm);
            return cm;
        } catch (Exception e) {
            System.debug(e.getMessage());
            return null;
        }
    }

    @AuraEnabled
    public static CommercialCode__c createCommercialCode(String campaignId, String fullCode, Integer maxUsesEE, Integer maxUsesGAS, Integer maxUsesVAS){
        try {
            CommercialCode__c cc = new CommercialCode__c (
                Campaign__c = campaignId,
                FullCode__c = fullCode,
                Name = fullCode,
                MaximalUsesEE__c = maxUsesEE,
                MaximalUsesGAS__c = maxUsesGAS,
                MaximalUsesVAS__c = maxUsesVAS,
                ActualUsesEE__c = 0,
                ActualUsesGAS__c = 0,
                ActualUsesVAS__c = 0,
                RecoveryUsesEE__c = 0,
                RecoveryUsesGAS__c = 0,
                RecoveryUsesVAS__c = 0
            );
            CommercialCode__c res = commercialCodeSrv.createRecord(cc);
            return res;
        } catch (Exception e) {
            System.debug(e.getMessage());
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static Boolean checkCommercialCodeUniqueness(String commercialCode, String campaignId) {
        List<Campaign> campaignsList = campaignQr.getCommercialCode(commercialCode, campaignId);
        if (campaignsList.size() > 0) {
            return false;
        }
        return true;
    }
}