force-app/main/default/objects/Campaign/fields/CodeConventionQuantity__c.field-meta.xml
<CustomField>
    <fullName>CodeConventionQuantity__c</fullName>
    <label>Quantità Codici convenzione</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/CodeGenerationRule__c.field-meta.xml
<CustomField>
    <fullName>CodeGenerationRule__c</fullName>
    <label>Regola generazione codice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CodeManagementModel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manuale</fullName>
            </value>
            <value>
                <fullName>PrefissoProgressivo</fullName>
                <label>Prefisso + Progressivo</label>
            </value>
            <value>
                <fullName>Prefisso + Nome + Cognome + Progressivo</fullName>
            </value>
            <value>
                <fullName>CognomeProgressivo</fullName>
                <isActive>false</isActive>
                <label>Cognome + Progressivo</label>
            </value>
            <value>
                <fullName>PrefissoNome</fullName>
                <isActive>false</isActive>
                <label>Prefisso + Nome</label>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/CodeManagementModel__c.field-meta.xml
<CustomField>
    <fullName>CodeManagementModel__c</fullName>
    <description>Generico, Per singolo Campaign Member, Porta un amico: selezionabile solo con Campagne MC e Campagne Outbound con canale Bolletta. Pubblico e Convenzione sono compatibili solo con Campagne CRM</description>
    <label>Modello Gestione Codici</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nessuno</fullName>
            </value>
            <value>
                <fullName>Generico</fullName>
            </value>
            <value>
                <fullName>Per singolo Campaign Member</fullName>
            </value>
            <value>
                <fullName>Porta un amico</fullName>
            </value>
            <value>
                <fullName>Pubblico</fullName>
            </value>
            <value>
                <fullName>Convenzione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_TRH_CampaignTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 09/08/2021
 * @description HDT_TRH_Campaign for Test Classes
 * @history Fabricio Petkevicius Nunes – 9/08/2021 – Created class
 */
@isTest
public with sharing class HDT_TRH_CampaignTst{
	private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
	@isTest
	public static void testBeforeInsertBeforeUpdate(){

		Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME);
		User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);
		insert internalUser;

		List<PermissionSetAssignment> permissionSetAssignments=new List<PermissionSetAssignment>{HDT_UTL_DataFactoryTst.assignPermissionSet(internalUser, constants.PERMISSIONSET_HDT_APEXCLASSES, false)};

		insert permissionSetAssignments;

		System.runAs(internalUser){

			Test.startTest();

			List<Campaign> campaigns=HDT_UTL_DataFactoryTst.createCampaign(1, false);
			campaigns[0].Status='Pianificata';

			insert campaigns;

			campaigns[0].IsActive=true;
			campaigns[0].CodeConventionQuantity__c=1;
			campaigns[0].CodeManagementModel__c='Convenzione';
			campaigns[0].CodeGenerationRule__c='PrefissoProgressivo';
			campaigns[0].Status='In Corso';

			update campaigns;

			List<Campaign> updatedCampaign = [SELECT Id, Status FROM Campaign WHERE Status = 'In Corso' LIMIT 1];

			System.assertEquals('In Corso', updatedCampaign[0].Status, 'Campaign Not Updated');
			System.assertNotEquals('Pianificata', updatedCampaign[0].Status, 'Campaign Not Updated');

			Test.stopTest();
		}
	}
}