force-app/main/default/objects/Campaign/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Tipo Processo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuova Vendita</fullName>
            </value>
            <value>
                <fullName>Nuovo Caso</fullName>
            </value>
            <value>
                <fullName>Entrambi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Società Silos</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>Codice Agenzia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Società Silos</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>LeadsSOL</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/MassiveLoaderRequest__c.object-meta.xml
<CustomObject>
    <label>Esito Caricamento</label>
    <nameField>
        <displayFormat>MLR-{00000000}</displayFormat>
        <label>Id Pratica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Esito Caricamenti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>File non processato</fullName>
            </value>
            <value>
                <fullName>File in elaborazione</fullName>
            </value>
            <value>
                <fullName>File processato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>Codice Agenzia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ComfortCallDaysDue__c.field-meta.xml
<CustomField>
    <fullName>ComfortCallDaysDue__c</fullName>
    <description>Campo di tracciamento per identificare la data quando l’order e stato segnato per la comfort call</description>
    <label>Giorni a scadere comfort call</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contatto Primario</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders (Contatto Primario)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CreditCheckDescription__c.field-meta.xml
<CustomField>
    <fullName>CreditCheckDescription__c</fullName>
    <label>Descrizione Esito Credit Check</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Data decorrenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ImplantType__c.field-meta.xml
<CustomField>
    <fullName>ImplantType__c</fullName>
    <label>Tipo impianto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_ImplantType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/NotRegisteredMeterCase__c.field-meta.xml
<CustomField>
    <fullName>NotRegisteredMeterCase__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag che permette di segnalare che bisogna innescare il Case di Cambio Contatore non registrato</description>
    <label>Cambio Contatore Non Registrato</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentOrder__c.field-meta.xml
<CustomField>
    <fullName>ParentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione verso l&apos;order dossier</description>
    <label>Order Padre</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku</fullName>
            </value>
            <value>
                <fullName>Da Inviare</fullName>
            </value>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PowerCommitted__c.field-meta.xml
<CustomField>
    <fullName>PowerCommitted__c</fullName>
    <description>Indica la potenza impegnata dell&apos;impianto</description>
    <label>Potenza Impegnata</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/QualityCall__c.field-meta.xml
<CustomField>
    <fullName>QualityCall__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quality call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/QualityCallUnique__c.field-meta.xml
<CustomField>
    <fullName>QualityCallUnique__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Unica quality call per tutti gli ordini legati al dossier</description>
    <label>Quality Call Unica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/RequestOption__c.field-meta.xml
<CustomField>
    <fullName>RequestOption__c</fullName>
    <description>UNB_OPZIONE(Lov Siebel che verra ceensita su CMD e poi riportata la scelta sul campo)</description>
    <label>Opzione Richiesta</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SignatureMethod__c.field-meta.xml
<CustomField>
    <fullName>SignatureMethod__c</fullName>
    <label>Metodo Firma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vocal Order</fullName>
            </value>
            <value>
                <fullName>OTP Remoto</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
            </value>
            <value>
                <fullName>OTP Coopresenza</fullName>
            </value>
            <value>
                <fullName>Contratto già firmato</fullName>
            </value>
            <value>
                <fullName>Accettato Digitalmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/WizardCompletedDate__c.field-meta.xml
<CustomField>
    <fullName>WizardCompletedDate__c</fullName>
    <label>Data completamento wizard</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_OrderDossier.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_OrderDossier</fullName>
    <active>true</active>
    <description>Record Type Ordine Padre</description>
    <label>Order Dossier</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_SwitchIn.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_SwitchIn</fullName>
    <active>true</active>
    <description>Record type per gli ordini di SwitchIn</description>
    <label>SwitchIn</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VAS.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VAS</fullName>
    <active>true</active>
    <label>VAS</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ImplantType__c.field-meta.xml
<CustomField>
    <fullName>ImplantType__c</fullName>
    <label>Tipologia Impianto</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CommoditySector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_ImplantType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HC</fullName>
    </customValue>
    <customValue>
        <fullName>HCM</fullName>
    </customValue>
    <customValue>
        <fullName>EENE</fullName>
        <label>NEWCO</label>
    </customValue>
    <customValue>
        <fullName>HSPA</fullName>
    </customValue>
    <customValue>
        <fullName>EB</fullName>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HC+HCM+EENE</fullName>
    </customValue>
    <description>Identifica la società di appartenenza</description>
    <masterLabel>Company</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_ImplantType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1001-Cottura cibi</fullName>
    </customValue>
    <customValue>
        <fullName>1002-Cottura/Produz acq calda</fullName>
    </customValue>
    <customValue>
        <fullName>1003-Riscaldamento esclusivo</fullName>
    </customValue>
    <customValue>
        <fullName>1004-Riscaldamento promiscuo</fullName>
    </customValue>
    <customValue>
        <fullName>1005-Risc. centraliz esclusivo</fullName>
    </customValue>
    <customValue>
        <fullName>1006-Risc. centraliz promiscuo</fullName>
    </customValue>
    <customValue>
        <fullName>1007-Attivita produttive</fullName>
    </customValue>
    <customValue>
        <fullName>1008-Promiscuo (prod+ risc)</fullName>
    </customValue>
    <customValue>
        <fullName>1009-Reti (cabine primo salto)</fullName>
    </customValue>
    <customValue>
        <fullName>1010-Usi interni</fullName>
    </customValue>
    <customValue>
        <fullName>13A0-Usi di Abitazione BT</fullName>
    </customValue>
    <customValue>
        <fullName>13BB-Illuminazione pubblica BT</fullName>
    </customValue>
    <customValue>
        <fullName>13CB-Non domestici in BT</fullName>
    </customValue>
    <customValue>
        <fullName>13CT-Forn temporanee &lt; 21 gg</fullName>
    </customValue>
    <customValue>
        <fullName>13DM-Illuminazione pubblica MT</fullName>
    </customValue>
    <customValue>
        <fullName>13EM-Non domestici MT</fullName>
    </customValue>
    <customValue>
        <fullName>13FM-Non domestici AT</fullName>
    </customValue>
    <customValue>
        <fullName>13X0-Usi interni BT</fullName>
    </customValue>
    <customValue>
        <fullName>13Y0-Usi interni MT</fullName>
    </customValue>
    <customValue>
        <fullName>13Z0-Grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>1101-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>1102-Non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>1103-Attivita</fullName>
    </customValue>
    <customValue>
        <fullName>1104-Scar. poz priv. civ. cont</fullName>
    </customValue>
    <customValue>
        <fullName>1105-Antincendio</fullName>
    </customValue>
    <customValue>
        <fullName>1106-Cantiere</fullName>
    </customValue>
    <customValue>
        <fullName>1107-Colonnetta</fullName>
    </customValue>
    <customValue>
        <fullName>1108-Irriguo</fullName>
    </customValue>
    <customValue>
        <fullName>1109-Comunale</fullName>
    </customValue>
    <customValue>
        <fullName>1110-Ente pubblico</fullName>
    </customValue>
    <description>1001-Cottura cibi
1002-Cottura/Produz acq calda
1003-Riscaldamento esclusivo
1100-ACQUA --- Non definito --- 
1119-Scar. ind.le  cont. Div</description>
    <masterLabel>Tipologia Impianto</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_CheckCompatibilitySalesTst.cls
@isTest
public with sharing class HDT_UTL_CheckCompatibilitySalesTst {
    private static HDT_UTL_Constants utlconstants = new HDT_UTL_Constants();
    
    @TestSetup
    static void setup(){
            HDT_UTL_DataFactoryTst.pClickInstance();
            HDT_UTL_DataFactoryTst.pClickOrderPhase();
            HDT_UTL_DataFactoryTst.newPhaseTransition('Comunicazione verso Heroku','Bozza',Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_OrderDossier').getRecordTypeId(),'HDT_RT_OrderDossier');
            HDT_UTL_DataFactoryTst.newPhaseTransition('Comunicazione verso Heroku','Bozza',Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_SwitchIn').getRecordTypeId(),'HDT_RT_SwitchIn');
            HDT_UTL_DataFactoryTst.newPhaseTransition('Da Inviare','Bozza',Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_VAS').getRecordTypeId(),'HDT_RT_VAS');

            List<Account> accs = HDT_UTL_DataFactoryTst.createAccountBusiness(1,true,'MMS','G3 - MMS Azienda','Aziende SME');
            Id accId = accs[0].id;
            
            List<Contact> contacts = HDT_UTL_DataFactoryTst.createContact(2,false,accId);
            for(Contact c : contacts) {
                c.Company__c='MMS';
            }
            insert contacts;
            Id contactId = contacts[0].id;
            Id anotherContactId = contacts[1].id;
            List<Order> parentOrders = HDT_UTL_DataFactoryTst.createOrder(1,false,accId,'Bozza');
            Id parentOrderId = parentOrders[0].id;
            parentOrders[0].Contact__c = contactId;
            parentOrders[0].Phase__c='In Lavorazione';
            parentOrders[0].recordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_OrderDossier').getRecordTypeId();
            insert parentOrders;
            List<ServicePoint__c> vasPoints=HDT_UTL_DataFactoryTst.createServicePoint(1, false);
            vasPoints[0].ServicePointCode__c='00720503018142';
            vasPoints[0].CommoditySector__c='Gas';
            insert vasPoints;
            List<Order> orderss = HDT_UTL_DataFactoryTst.createOrder(1,false,accId,'Bozza');
            orderss[0].Username__c='test';
            orderss[0].Password__c='test1';
            orderss[0].NotRegisteredMeterCase__c=true;
            orderss[0].EffectiveDate__c=date.today();
            orderss[0].PowerCommitted__c=2;
            orderss[0].ImplantType__c='13A0-Usi di Abitazione BT';
            orderss[0].RequestOption__c='Domestici-TD';
            orderss[0].CreditCheckDescription__c='test1';
            orderss[0].QualityCall__c=true;  
            orderss[0].ComfortCallDaysDue__c=null;
            orderss[0].WizardCompletedDate__c=date.today()-60;
            orderss[0].ParentOrder__c = parentOrderId;
            orderss[0].Contact__c = contactId;
            orderss[0].QualityCallUnique__c=false;
            orderss[0].AgencyCode__c='001';
            orderss[0].recordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_SwitchIn').getRecordTypeId();
            orderss[0].Phase__c = 'Bozza';
            orderss[0].SignatureMethod__c='Contratto già firmato';
            orderss[0].ProcessType__c='Switch in Gas';
            orderss[0].VasSubtype__c='';
            orderss[0].ParentOrder__c=parentOrders[0].Id;
            orderss[0].ServicePoint__c=vasPoints[0].Id;
            insert orderss;
            List<Campaign> campaigns = HDT_UTL_DataFactoryTst.createCampaign(1,false);
            campaigns[0].Name = 'Comfort Campaign';
            insert campaigns;
            String processName='Lead';
            MassiveLoaderRequest__c mlrSwitch=HDT_UTL_DataFactoryTst.createMassiveLoaderRequest(processName,new List<String>{'HERA COMM,HCM,null,347852147,null,,Mario,Rossi,Laurea,Studente,Benedetto Brin,1,80100,80100,Napoli,NA,null,,null,,25,null,Maschio,null,SI,1,2020-10-1,Webform callback,AAA,sito standard,NO,1,2020-10-1,Webform callback,HCM,sito standard,null,,null,,2020-10-1,null,,null,,null,,null,,null,test'});
            List<MassiveLoaderRequestItem__c> itemList=new List<MassiveLoaderRequestItem__c>();
            for(MassiveLoaderRequestItem__c item:[SELECT Id FROM MassiveLoaderRequestItem__c WHERE MassiveLoaderRequest__r.ProcessType__c='Lead']){
                HDT_UTL_ProcessSales.HDT_WRP_NextDataObj nextObj=new HDT_UTL_ProcessSales.HDT_WRP_NextDataObj();
                nextObj.parentOrderId=parentOrders[0].Id;
                nextObj.accountId=accId;
                nextObj.billProfId='';
                nextObj.contactId=contacts[0].Id;
                nextObj.servPointId=vasPoints[0].Id;
                item.NextStepData__c=JSON.serialize(nextObj);
                item.MassiveLoaderRequest__c=mlrSwitch.Id;
                itemList.add(item);
            }
            update itemList;
        List<Order> analisiConsumi = HDT_UTL_DataFactoryTst.createOrder(1,false,accId,'Bozza');
        analisiConsumi[0].Username__c='testAn';
        analisiConsumi[0].Password__c='test1An';
        analisiConsumi[0].NotRegisteredMeterCase__c=true;
        analisiConsumi[0].EffectiveDate__c=date.today();
        analisiConsumi[0].PowerCommitted__c=2;
        analisiConsumi[0].ImplantType__c='13A0-Usi di Abitazione BT';
        analisiConsumi[0].RequestOption__c='Domestici-TD';
        analisiConsumi[0].CreditCheckDescription__c='test1';
        analisiConsumi[0].QualityCall__c=true;
        analisiConsumi[0].ComfortCallDaysDue__c=null;
        analisiConsumi[0].WizardCompletedDate__c=date.today()-60;
        analisiConsumi[0].ParentOrder__c = parentOrders[0].Id;
        analisiConsumi[0].Contact__c = contactId;
        analisiConsumi[0].QualityCallUnique__c=false;
        analisiConsumi[0].AgencyCode__c='001';
        analisiConsumi[0].RecordTypeId=Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_VAS').getRecordTypeId();
        analisiConsumi[0].Phase__c = 'Bozza';
        analisiConsumi[0].SignatureMethod__c='Contratto già firmato';
        analisiConsumi[0].ProcessType__c='VAS';
        analisiConsumi[0].VasSubtype__c='Analisi Consumi';
        analisiConsumi[0].ServicePoint__c=vasPoints[0].Id;
        insert analisiConsumi;
    }
    @isTest
    public static void Execute(){
        Order otherOrder=[SELECT Id,Contact__c,AccountId,ParentOrder__c,ServicePoint__c FROM ORder WHERE RecordType.DeveloperName='HDT_RT_SwitchIn'];
        //
        //
        List<MassiveLoaderRequestItem__c> listReqItem = [SELECT id ,Status__c,NextStepData__c,MassiveLoaderRequest__r.ProcessType__c FROM MassiveLoaderRequestItem__c];
        System.debug('size is: '+listReqItem.size());
        HDT_UTL_CheckCompatibilitySales testClass =  new HDT_UTL_CheckCompatibilitySales();
        Test.startTest();
        testClass.setRequestItemList(listReqItem);
        testClass.generateWrapperMap();
        testClass.getRecords();
        testClass.runCheckCompatibilitySales();
        Test.stopTest();
    }
}