force-app/main/default/objects/Case/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Profile</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Casi</relationshipLabel>
    <relationshipName>Casi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Nome del Cluster a cui appartiene un processo.</description>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CommodityFormula__c.field-meta.xml
<CustomField>
    <fullName>CommodityFormula__c</fullName>
    <description>Settore merceologico preso in Lookup dal Service Point</description>
    <formula>IF(TEXT(ServicePoint__r.CommoditySector__c) != &apos;&apos;,TEXT(ServicePoint__r.CommoditySector__c), TEXT(Commodity__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InformationDetail__c.field-meta.xml
<CustomField>
    <fullName>InformationDetail__c</fullName>
    <description>Informazioni di dettalio inerenti l&apos;informativa</description>
    <label>Dettaglio Informazioni</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_InformationDetail</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/InformativeCluster__c.field-meta.xml
<CustomField>
    <fullName>InformativeCluster__c</fullName>
    <description>Cluster selezionato all&apos;interno del processo di Informative</description>
    <label>Informative - Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambiente</fullName>
            </value>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Attivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>HERA</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>PostSales VAS</fullName>
            </value>
			<value>
                <fullName>Generiche Attivazioni</fullName>
            </value>
			<value>
                <fullName>Generiche VAS</fullName>
            </value>
            <value>
                <fullName>VAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/InformativeType__c.field-meta.xml
<CustomField>
    <fullName>InformativeType__c</fullName>
    <description>Processo selezionato all&apos;interno del processo di Informative</description>
    <label>Informative - Processo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allineamento Anagrafica</fullName>
            </value>
            <value>
                <fullName>Allineamento Canone Rai</fullName>
            </value>
            <value>
                <fullName>Altre Verifiche</fullName>
            </value>
            <value>
                <fullName>Annullamento Contratti</fullName>
            </value>
            <value>
                <fullName>Attivazione Click&amp;Pay</fullName>
            </value>
            <value>
                <fullName>Autolettura da cliente</fullName>
            </value>
            <value>
                <fullName>Autolettura da processo</fullName>
            </value>
            <value>
                <fullName>Blocco Sollecito/Interessi</fullName>
            </value>
            <value>
                <fullName>BP/CA - errata categoria</fullName>
            </value>
            <value>
                <fullName>Caduta Linea/Chiamata Muta</fullName>
            </value>
            <value>
                <fullName>Cambio contatore non registrato</fullName>
            </value>
            <value>
                <fullName>Chiusura Contatore</fullName>
            </value>
            <value>
                <fullName>Comportamento Altri Venditori</fullName>
            </value>
            <value>
                <fullName>Comportamento Venditori HC</fullName>
            </value>
            <value>
                <fullName>Comunicazione di Fallimento</fullName>
            </value>
            <value>
                <fullName>Comunicazione Pagamento</fullName>
            </value>
            <value>
                <fullName>Condizioni Contrattuali Errate</fullName>
            </value>
            <value>
                <fullName>Consegna copia chiave GdM</fullName>
            </value>
            <value>
                <fullName>Contenzioso In Corso</fullName>
            </value>
            <value>
                <fullName>Contratto Non Richiesto</fullName>
            </value>
            <value>
                <fullName>Copia Bolletta/Bollettino</fullName>
            </value>
            <value>
                <fullName>Dettaglio Bolletta</fullName>
            </value>
            <value>
                <fullName>Disassociazione Utente Web</fullName>
            </value>
            <value>
                <fullName>Doppi Pagamenti/Incassi</fullName>
            </value>
            <value>
                <fullName>Errore Chiamata</fullName>
            </value>
            <value>
                <fullName>Errore di Fatturazione</fullName>
            </value>
            <value>
                <fullName>Esercizio Diritti Privacy</fullName>
            </value>
            <value>
                <fullName>Fiscale</fullName>
            </value>
            <value>
                <fullName>Fiscale  - IVA Esenzione/Revoca</fullName>
            </value>
            <value>
                <fullName>Gestione Bonus Sociale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/MacroTopic__c.field-meta.xml
<CustomField>
    <fullName>MacroTopic__c</fullName>
    <description>Il Macro argomento inerente l&apos;informativa</description>
    <label>Macro Argomento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_MacroTopic</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HDT_ClusterProcess__mdt/HDT_ClusterProcess__mdt.object-meta.xml
<CustomObject>
    <label>HDT_ClusterProcess</label>
    <pluralLabel>HDT_ClusterProcess</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_ClusterProcess__mdt/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_ClusterProcess__mdt/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>ProcessType</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HDT_Informative_Configuration__mdt/HDT_Informative_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>HDT_Informative_Configuration</label>
    <pluralLabel>HDT_Informative_Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_Informative_Configuration__mdt/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BillingProfile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HDT_Informative_Configuration__mdt/fields/InformationDetail__c.field-meta.xml
<CustomField>
    <fullName>InformationDetail__c</fullName>
    <label>InformationDetail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_Informative_Configuration__mdt/fields/MacroTopic__c.field-meta.xml
<CustomField>
    <fullName>MacroTopic__c</fullName>
    <label>MacroTopic</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_Informative_Configuration__mdt/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ServicePoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attivazioni</fullName>
                <default>true</default>
                <label>Attivazioni</label>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CommodityFormula__c.field-meta.xml
<CustomField>
    <fullName>CommodityFormula__c</fullName>
    <formula>TEXT(ServicePoint__r.CommoditySector__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_MacroTopic.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Appuntamento agente</fullName>
    </customValue>
    <customValue>
        <fullName>Consenso ricontatto</fullName>
    </customValue>
    <customValue>
        <fullName>Info modulistica</fullName>
    </customValue>
    <customValue>
        <fullName>genHERAZIONI</fullName>
    </customValue>
    <customValue>
        <fullName>Info su stato pratica</fullName>
    </customValue>
    <customValue>
        <fullName>Info contratto</fullName>
    </customValue>
    <customValue>
        <fullName>Consulenza offerte</fullName>
    </customValue>
    <customValue>
        <fullName>Info contatto</fullName>
    </customValue>
    <customValue>
        <fullName>Info Consegna e prodotti</fullName>
    </customValue>
    <customValue>
        <fullName>Info Fatturazione</fullName>
    </customValue>
    <customValue>
        <fullName>Info stato pratica</fullName>
    </customValue>
    <customValue>
        <fullName>Info modalità</fullName>
    </customValue>
    <customValue>
        <fullName>Richiesta di approfondimenti</fullName>
    </customValue>
    <customValue>
        <fullName>Info estratto conto</fullName>
    </customValue>
    <customValue>
        <fullName>Info pagamenti</fullName>
    </customValue>
    <customValue>
        <fullName>Info dati</fullName>
    </customValue>
    <customValue>
        <fullName>Info fattura</fullName>
    </customValue>
    <customValue>
        <fullName>Modalità comunicazione</fullName>
    </customValue>
    <customValue>
        <fullName>Informazione stato pratica</fullName>
    </customValue>
    <customValue>
        <fullName>Info servizi</fullName>
    </customValue>
    <masterLabel>Macro Argomento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_QR_InformativeManager.cls
public with sharing class HDT_QR_InformativeManager {

    //modificare prendendo i cluster dall'oggetto HDT_Informative_Configuration__mdt in base al punto d'innesco.
    public static List<HDT_ClusterProcess__mdt> getClusterProcess(String context)
    {

        context = context == 'ServicePoint__c' || context == 'BillingProfile__c' ? context : context + '__c';

        String query = 'SELECT Id, Cluster__c FROM HDT_Informative_Configuration__mdt WHERE ' +context+ '=true WITH SECURITY_ENFORCED';

        return Database.query(query);

    }
    public static String getProcessByCluster(String cluster){
        return [SELECT Id, Cluster__c,ProcessType__c FROM HDT_ClusterProcess__mdt WHERE Cluster__c =:cluster WITH SECURITY_ENFORCED].ProcessType__c;
    }

    public static List<HDT_Informative_Configuration__mdt> getTopicByCluster(String cluster, String context){

        context = context == 'ServicePoint__c' || context == 'BillingProfile__c' ? context : context + '__c';

        String query = 'SELECT Id, Cluster__c, MacroTopic__c FROM HDT_Informative_Configuration__mdt '+
        'WHERE Cluster__c =:cluster AND ' +context+ '=true WITH SECURITY_ENFORCED';

        return Database.query(query);

    }
    public static List<HDT_Informative_Configuration__mdt> getInfoByTopicCluster(String topic, String cluster, String context){

        context = context == 'ServicePoint__c' || context == 'BillingProfile__c' ? context : context + '__c';

        String query = 'SELECT Id, Cluster__c, MacroTopic__c, InformationDetail__c FROM HDT_Informative_Configuration__mdt '+
        'WHERE Cluster__c =:cluster AND MacroTopic__c =:topic AND ' +context+ '=true WITH SECURITY_ENFORCED';

        return Database.query(query);
    }

    public static Case getFieldToPrePopulate(String recordId){

        return [SELECT InformativeCluster__c, 
        InformativeType__c,
        CommodityFormula__c
        FROM Case
        WHERE Id = :recordId
        WITH SECURITY_ENFORCED
        LIMIT 1];


    }

    public static SObject getPrePopulationInfo(String recordId,String sObjName){

        SObject contextSobj;

        switch on sObjName{

                when 'Case'{

                    contextSobj = [SELECT AccountId, 
                    ServicePoint__c, 
                    Market__c, 
                    BillingProfile__c, 
                    Cluster__c, 
                    Type,
                    SalesCompany__c,
                    Contract__c
                    FROM Case
                    WHERE Id = :recordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1];

                }
                when 'Order'{

                    contextSobj = [SELECT Id,AccountId,
                    ServicePoint__c,
                    Market__c,
                    BillingProfile__c,
                    SalesCompany__c,
                    ContractId,
                    Subprocess__c,
                    Cluster__c
                    FROM Order
                    WHERE Id = :recordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
                    ];

                }
                when 'Opportunity'{

                    //Sono previsti questi campi sull' opportunity?

                    contextSobj = [SELECT AccountId,
                    //ServicePoint__c,
                    //Market__c,
                    //BillingProfile__c,
                    //SalesCompany__c,
                    ContractId
                    FROM Order
                    WHERE Id =: recordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1]; 


                }
                when 'ServicePoint__c'{

                    contextSobj = [SELECT Account__c,
                    MarketOrigin__c/*,
                    //BillingProfile__c,
                    //Company__c, Non convinto che sia questo il campo corretto
                    Contract__c*/
                    FROM ServicePoint__c
                    WHERE Id =: recordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1];
                

                }
                when 'Contract'{

                    contextSobj = [SELECT Id,
                    BillingProfile__c/*,
                    //BillingProfile__c,
                    //Company__c, Non convinto che sia questo il campo corretto
                    Contract__c*/
                    FROM Contract
                    WHERE ServicePoint__c =: recordId
                    AND Status = 'Active'
                    WITH SECURITY_ENFORCED
                    LIMIT 1];
                }
                when 'BillingProfile__c'{
                    contextSobj = [SELECT Id,
                    Account__c
                    FROM BillingProfile__c
                    WHERE Id =: recordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1]; 
                }
                when 'Lead'{

                    //No query needed

                }
                when 'Contact'{

                    //no query needed

                }
                when 'Account'{

                    //No query needed

                }
        }
       
        return contextSobj;

    }
    
}