force-app/main/default/objects/Case/fields/BillingCategory__c.field-meta.xml
<CustomField>
    <fullName>BillingCategory__c</fullName>
    <label>Categoria Billing</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SuspensionEndDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionEndDate__c</fullName>
    <formula>SuspensionDate__c + SuspensionDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data Fine Sospensione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/ExpRavv__c.object-meta.xml
<CustomObject>
    <label>Export Ravvedimento</label>
    <nameField>
        <displayFormat>ER - {000000}</displayFormat>
        <label>Nome Export Ravvedimento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Export Ravvedimenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpRavv__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Export Ravvedimenti</relationshipLabel>
    <relationshipName>Export_Ravvedimenti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/CityCode__c.field-meta.xml
<CustomField>
    <fullName>CityCode__c</fullName>
    <label>Codice comune catastale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/OperandName__c.field-meta.xml
<CustomField>
    <fullName>OperandName__c</fullName>
    <label>Operando</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/OperandValue__c.field-meta.xml
<CustomField>
    <fullName>OperandValue__c</fullName>
    <label>Valore operando</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Export Ravvedimenti</relationshipLabel>
    <relationshipName>Export_Ravvedimenti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <formula>IF(Order__r.ProcessCode__c=&quot;A01&quot;, &quot;Ambiente&quot;, 
IF(Order__r.ProcessCode__c=&quot;VT1&quot;, &quot;Subentro&quot;,
&quot;Variazione&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sottotipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/SuspensionEndDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionEndDate__c</fullName>
    <label>Fine periodo sospensione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/SuspensionStartDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionStartDate__c</fullName>
    <label>Inizio periodo sospensione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpRavv__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>&quot;Contratti&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingCategory__c.field-meta.xml
<CustomField>
    <fullName>BillingCategory__c</fullName>
    <label>Categoria Billing</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_UTL_ExpSieRavv.cls
public with sharing class HDT_UTL_ExpSieRavv {

    @AuraEnabled(cacheable=false)
    public static void createExportSobjects(HDT_WRP_SieExport wrapper){
        //cancellare gli esistenti record di ravvedimento operoso
        HDT_UTL_DatabaseService.deleteSObject([Select id From ExpRavv__c Where Case__c =:wrapper.record.Id OR Order__c =:wrapper.record.Id]);
        //creare e inserire i nuovi
        List<ExpRavv__c> exportObjectsToInsert = getExportRavv(wrapper);
        HDT_UTL_DatabaseService.insertSObject(exportObjectsToInsert);
        return;
    }


    private static List<ExpRavv__c>  getExportRavv(HDT_WRP_SieExport wrapper, Case caseRavv){
        HDT_UTL_SieSobjectCreation createSobjUtl = new HDT_UTL_SieSobjectCreation(wrapper);
        List<ExpRavv__c> listToInsert = new List<ExpRavv__c>();
        if('x'.equalsIgnoreCase(wrapper.period)){//SE Periodo != "X"
            if('order'.equalsIgnoreCase(createSobjUtl.getSobjectType())){//SE  SOTTOTIPO è  'Nuovo contratto' ,'Subentro' ,'Subentro Cambio Cat.Tariffa' ,'Cambio Cat.Tariffa Stesso Cli.'
                Order ord = (Order) wrapper.record;
                if( !'A'.equalsIgnoreCase(ord.BillingCategory__c)){
                    // listToInsert.add(createSobjUtl.createExpRavv());
                }
            
            }else if('case'.equalsIgnoreCase(createSobjUtl.getSobjectType())){//SE  SOTTOTIPO è  'Modifica dati contr.stesso Cli'
                Case caso = (Case) wrapper.record;
            }
        }
    }

    public with sharing class HDT_WRP_SieExport{
        @AuraEnabled public String period {get;set;}
        @AuraEnabled public String subtype {get;set;}
        @AuraEnabled public String cityCode {get;set;}
        @AuraEnabled public Date declarationDate {get;set;}
        @AuraEnabled public Date effectiveDate {get;set;}
        @AuraEnabled public Date limitDateX {get;set;}
        @AuraEnabled public Sobject record {get;set;}
    }

    private with sharing class HDT_UTL_SieSobjectCreation{
        HDT_WRP_SieExport wrapper {get;set;}
        String sobjectTypeName {get;set;}
        HDT_UTL_SieSobjectCreation(HDT_WRP_SieExport wrapper){
            this.wrapper=wrapper;
            this.sobjectTypeName = wrapper.record.Id.getSobjectType().getDescribe().getName().toLowerCase();
        }

        getSobjectType(){
            return this.sobjectTypeName;
        }

        @SuppressWarnings('PMD.ExcessiveParameterList')
        ExpRavv__c createExpRavv(String operandName, String operandValue){
            ExpRavv__c exportRecord = new ExpRavv__c();
            exportRecord.OperandName__c = operandName;
            exportRecord.OperandValue__c = operandValue;

            String billingCategory = (String) this.wrapper.record.get('BillingCategory__c');
            exportRecord.SuspensionEndDate__c = this.wrapper.declarationDate.addDays(-1);
            if(!'y'.equalsIgnoreCase(wrapper.period) || 'C'.equalsIgnoreCase(billingCategory) ){    
                exportRecord.SuspensionStartDate__c = this.wrapper.effectiveDate;  
            }else if('B'.equalsIgnoreCase(billingCategory)){
                exportRecord.SuspensionStartDate__c = this.wrapper.limitDateX;
            }

            exportRecord.CityCode__c = this.wrapper.cityCode;
            exportRecord.Type__c='Contratti';
            if('Subentro'.equalsIgnoreCase(this.wrapper.subtype)){   exportRecord.Subtype__c = 'Subentro';}
            else if(this.wrapper.subtype?.containsIgnoreCase('Attivazione')==true){ exportRecord.Subtype__c = 'Attivazione';}
            else { exportRecord.Subtype__c = 'Variazione';}
            switch on this.sobjectTypeName {
                when 'case' {
                    exportRecord.Case__c=this.wrapper.record.Id;
                }
                when 'order' {
                    exportRecord.Order__c=this.wrapper.record.Id;
                }
            }
            return exportRecord;
        }
    }
}