force-app/main/default/objects/Case/fields/BillSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>BillSendingMethod__c</fullName>
    <description>Nuova modalità invio bolletta per sotto-processo Modifica Dati di Recapito</description>
    <label>Modalità invio bolletta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillSendingMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup all&apos;object Contract</description>
    <label>Contratto</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PowerRequested__c.field-meta.xml
<CustomField>
    <fullName>PowerRequested__c</fullName>
    <description>Indica la potenza richiesta dal cliente</description>
    <label>Potenza Richiesta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Residente</description>
    <label>Residente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/UseCategory__c.field-meta.xml
<CustomField>
    <fullName>UseCategory__c</fullName>
    <label>Tipologia uso PdR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_UseCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EligibilityCriteria__c/EligibilityCriteria__c.object-meta.xml
<CustomObject>
    <description>Ogggetto  custom per la gestione dei criteri di eleggibilità legati ai prodotti</description>
    <label>Criterio di Eleggibilita</label>
    <nameField>
        <displayFormat>COE-{00000000}</displayFormat>
        <label>Criterio di Eleggibilita Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criteri di Eleggibilita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EligibilityCriteria__c/fields/BillSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>BillSendingMethod__c</fullName>
    <description>Modalità di invio della bottetta</description>
    <label>Modalità Invio Bolletta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_BillSendingMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EligibilityCriteria__c/fields/PaymentMode__c.field-meta.xml
<CustomField>
    <fullName>PaymentMode__c</fullName>
    <description>Modalità di pagamento associata al criterio di eleggibilità</description>
    <label>Modalità di pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_PaymentMode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EligibilityCriteria__c/fields/PowerRangeMax__c.field-meta.xml
<CustomField>
    <fullName>PowerRangeMax__c</fullName>
    <description>Campo di configurazione usato per indicare il valore massimo della potenza.</description>
    <label>Potenza/Portata max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EligibilityCriteria__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo di configurazione usato per indicare il prodotto legato al criterio, usato nella funzionalità dei Criteri di Eleggiblità</description>
    <label>Prodotto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Criteri di Eleggibilita</relationshipLabel>
    <relationshipName>EligibilitiesCriteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EligibilityCriteria__c/fields/ResidentDeliveryAddress__c.field-meta.xml
<CustomField>
    <fullName>ResidentDeliveryAddress__c</fullName>
    <label>Residente all&apos;indirizzo di fornitura</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EligibilityCriteria__c/fields/UseCategory__c.field-meta.xml
<CustomField>
    <fullName>UseCategory__c</fullName>
    <description>Campo di configurazione usato per indicare la categoria d&apos;uso per il record di criterio nella funzionalità di Configurazione Offerta Tecnica</description>
    <label>Categoria Uso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_UseCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PaymentMode__c.field-meta.xml
<CustomField>
    <fullName>PaymentMode__c</fullName>
    <description>la modalità di pagamento associata al dato record di prodotto opzione</description>
    <label>Modalita di Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To define</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/ResidentDeliveryAddress__c.field-meta.xml
<CustomField>
    <fullName>ResidentDeliveryAddress__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag che indica se il dato record di Product deve essere legato all&apos;indirizzo di residenza della fornitura</description>
    <label>Residente Indirizzo di Fornitura</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/UseCategory__c.field-meta.xml
<CustomField>
    <fullName>UseCategory__c</fullName>
    <label>Categoria Uso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To define</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_BillSendingMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bolletta per e-mail</fullName>
    </customValue>
    <customValue>
        <fullName>Cartaceo</fullName>
    </customValue>
    <customValue>
        <fullName>Fatturazione PA</fullName>
    </customValue>
    <customValue>
        <fullName>Invio tramite PEC</fullName>
    </customValue>
    <customValue>
        <fullName>Bolletta per e-mail + Carta</fullName>
        <isActive>false</isActive>
        <label>Bolletta per e-mail + Carta</label>
    </customValue>
    <masterLabel>Modalità Invio Bolletta</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_PaymentMode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bollettino</fullName>
    </customValue>
    <customValue>
        <fullName>Rate</fullName>
    </customValue>
    <customValue>
        <fullName>RID</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Bonifico</fullName>
    </customValue>
    <masterLabel>Modalità di Pagamento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_UseCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001-Uso cottura cibi</fullName>
    </customValue>
    <customValue>
        <fullName>002-Prod.acqua calda sanitaria</fullName>
    </customValue>
    <customValue>
        <fullName>003-CotturaCibi+AcquaCalda</fullName>
    </customValue>
    <customValue>
        <fullName>004-Uso tecnologico</fullName>
    </customValue>
    <customValue>
        <fullName>005-Uso condizionamento</fullName>
    </customValue>
    <customValue>
        <fullName>006-Riscald. individ./central.</fullName>
    </customValue>
    <customValue>
        <fullName>007-Ris.Ind+Cottura+AcquaCalda</fullName>
    </customValue>
    <customValue>
        <fullName>008-Ris.Ind.+Cottura Cibi</fullName>
    </customValue>
    <customValue>
        <fullName>009-Ris.Ind.+AcquaCalda</fullName>
    </customValue>
    <customValue>
        <fullName>010-Ris.Cen.+Cott.+AcquaCalda</fullName>
    </customValue>
    <customValue>
        <fullName>011-Ris.Cen.+AcquaCalda</fullName>
    </customValue>
    <customValue>
        <fullName>012-Uso Tecnologico + Riscald.</fullName>
    </customValue>
    <customValue>
        <fullName>013-Uso Condizionam.+Riscald.</fullName>
    </customValue>
    <masterLabel>Categoria duso</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_ElegibilityCriteriaCheck.cls
public with sharing class HDT_UTL_ElegibilityCriteriaCheck {
    
    @InvocableMethod(label='Check Criterio Elegibilità')
    public static List<HDT_WRP_ElegibilityCriteriaCheckOutput> execute(List<HDT_WRP_ElegibilityCriteriaCheckInput> inputs){
        if(inputs==null || inputs.size()<=0) return null;
      
        HDT_WRP_ElegibilityCriteriaCheckInput input = inputs[0];
        HDT_WRP_ElegibilityCriteriaCheckOutput output = new HDT_WRP_ElegibilityCriteriaCheckOutput();
        List<HDT_WRP_ElegibilityCriteriaCheckOutput> outputList = new List<HDT_WRP_ElegibilityCriteriaCheckOutput>();

        // Query su Case
        HDT_QR_Case caseQuery = new HDT_QR_Case();
        String caseQueryFields = 'Id,Contract__c,Type,BillSendingMethod__c,Resident__c,UseCategory__c,PowerRequested__c';
        List<String> caseIds = new List<String>();
        caseIds.add(input.caseId);
        List<Case> cases = caseQuery.getRecordsById(caseIds, caseQueryFields);
        if (cases.isEmpty()){
            outputList.add(output);
            return outputList;
        }

        Case caseRecord = cases[0];
        Id contractId = caseRecord.Contract__c;

        if (contractId == null) {
            // TODO: se non ho un contratto sul case (es. sulle Domiciliazioni o sulle Mod. Anagrafiche) bisogna scorrersi tutti i contratti del cliente...
            outputList.add(output);
            return outputList;
        }

        // Query su Contract
        String objectName = 'Contract';
        String queryFields = 'Id,ContractNumber,Status';
        String queryString = 'SELECT ' + queryFields;
        String fromString = ' FROM '+ objectName;
        String controllingField = 'Id';
        String whereString = ' WHERE ' + controllingField + ' =\''+ contractId + '\'';
        //String relatedQueryString = ',(SELECT Id,SBQQ__ProductName__c FROM SBQQ__Subscriptions__r WHERE SBQQ__Product__r.Family = \'Offerta commerciale\')';//montors fix --
        String relatedQueryString = ',(SELECT SBQQ__Product__c FROM SBQQ__Subscriptions__r WHERE SBQQ__Product__r.Family = \'Offerta commerciale\')';//montors fix ++
        queryString = queryString + relatedQueryString + fromString + whereString; 
        System.debug('contract query: ' + queryString);

        List<sObject> contracts = HDT_QR_GenericQuery.getGenericRecords(queryString, objectName);
        if (contracts.isEmpty()){
            outputList.add(output);
            return outputList;
        }

        Contract c = (Contract) contracts[0];
        List<SBQQ__Subscription__c> subscriptions = (List<SBQQ__Subscription__c>) c.SBQQ__Subscriptions__r;
        //String productName = subscriptions[0].SBQQ__ProductName__c;//montors fix --
        String productId = subscriptions[0].SBQQ__Product__c;//montors fix ++

        // Query oggetto criteri eleggibilità
        objectName = 'EligibilityCriteria__c';
        queryFields = 'Id,BillSendingMethod__c,UseCategory__c,ResidentDeliveryAddress__c,PowerRangeMax__c';
        queryString = 'SELECT ' + queryFields;
        fromString = ' FROM '+ objectName;
        whereString = ' WHERE Product__c =\''+ productId + '\'';//montors fix ++
        queryString = queryString + fromString + whereString; 
        System.debug('criteria query: ' + queryString);

        List<sObject> criterias = HDT_QR_GenericQuery.getGenericRecords(queryString, objectName);
        if (criterias.isEmpty()){
            outputList.add(output);
            return outputList;
        }

        for (Integer i = 0; i < criterias.size(); i++) {
            EligibilityCriteria__c criteria = (EligibilityCriteria__c) criterias[i];

            switch on caseRecord.Type {
                when 'Modifica Tariffa Residente/Non Residente' {
                    String caseValue = caseRecord.Resident__c ? 'Si' : 'No';
                    if (caseValue != criteria.ResidentDeliveryAddress__c) {
                        output.abortProcess = true;
                        output.abortProcessWarning = 'L\'offerta attiva sul contratto selezionato è incompatibile con la variazione del campo Residente. Per poter procedere è necessario eseguire un cambio offerta.';
                        outputList.add(output);
                        return outputList;
                    }
                }
                when 'Marcatura/Uso PdR' {
                    if (criteria.UseCategory__c != null && !criteria.UseCategory__c.contains(caseRecord.UseCategory__c)) {
                        output.abortProcess = true;
                        output.abortProcessWarning = 'L\'offerta attiva sul contratto selezionato è incompatibile con la variazione del campo Tipologia Uso. Per poter procedere è necessario eseguire un cambio offerta.';
                        outputList.add(output);
                        return outputList;
                    }
                }
                when 'Variazione Anagrafica Cliente' {
                    if (caseRecord.BillSendingMethod__c != criteria.BillSendingMethod__c) {
                        output.abortProcess = true;
                        output.abortProcessWarning = 'L\'offerta attiva sul contratto selezionato è incompatibile con la variazione del campo Modalità Invio Bolletta. Per poter procedere è necessario eseguire un cambio offerta.';
                        outputList.add(output);
                        return outputList;
                    }
                }
                when 'Variazione Potenza' {
                    if (criteria.PowerRangeMax__c > 0 && caseRecord.PowerRequested__c > criteria.PowerRangeMax__c) {
                        output.abortProcess = true;
                        output.abortProcessWarning = 'L\'offerta attiva sul contratto selezionato è incompatibile con l\'aumento di potenza richiesto. Per poter procedere è necessario eseguire un cambio offerta.';
                        outputList.add(output);
                        return outputList;
                    }
                }
                when 'Richiesta Domiciliazione' {
                    if (criteria.PaymentMode__c != 'RID') {
                        output.abortProcess = true;
                        output.abortProcessWarning = 'L\'offerta attiva sul contratto selezionato è incompatibile con l\'attivazione della Domiciliazione. Per poter procedere è necessario eseguire un cambio offerta.';
                        outputList.add(output);
                        return outputList;
                    }
                }
                when 'Revoca Domiciliazione' {
                    if (criteria.PaymentMode__c == 'RID') {
                        output.abortProcess = true;
                        output.abortProcessWarning = 'L\'offerta attiva sul contratto selezionato è incompatibile con la revoca della Domiciliazione. Per poter procedere è necessario eseguire un cambio offerta.';
                        outputList.add(output);
                        return outputList;
                    }
                }
            }
        }

        outputList.add(output);
        return outputList;
    }

    public class HDT_WRP_ElegibilityCriteriaCheckInput {
        @InvocableVariable
        public String caseId;
    }

    public class HDT_WRP_ElegibilityCriteriaCheckOutput {
        @InvocableVariable
        public Boolean abortProcess;    // Indica se il processo deve essere interrotto poichè sta modificando un criterio di elegibilità.

        @InvocableVariable
        public String abortProcessWarning; // Indica il motivo per cui il processo deve essere interrotto.
    }
}