force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup all&apos;object Contract</description>
    <label>Contratto</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CopyType__c.field-meta.xml
<CustomField>
    <fullName>CopyType__c</fullName>
    <label>Tipo Copia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Copia contratto firmato</fullName>
            </value>
            <value>
                <fullName>Copia contratto non firmato</fullName>
            </value>
            <value>
                <fullName>Copia della registrazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <description>Note</description>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/OperationSubType__c.field-meta.xml
<CustomField>
    <fullName>OperationSubType__c</fullName>
    <label>Sottotipo Operazione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Risarcimenti danni</fullName>
            </value>
            <value>
                <fullName>Prezzo energia negoziato</fullName>
            </value>
            <value>
                <fullName>Rimborso totale bollette</fullName>
            </value>
            <value>
                <fullName>Rimborso parziale bollette</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OperationType__c.field-meta.xml
<CustomField>
    <fullName>OperationType__c</fullName>
    <description>Picklist specifica per il processo &quot;Unificazione/Separazione CA-Bolletta&quot;.</description>
    <label>Tipo operatività</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unificazione CA</fullName>
            </value>
            <value>
                <fullName>Separazione CA</fullName>
            </value>
            <value>
                <fullName>Unificazione bolletta</fullName>
            </value>
            <value>
                <fullName>Separazione bolletta</fullName>
            </value>
            <value>
                <fullName>Unificazione BP</fullName>
            </value>
            <value>
                <fullName>Accollo parziale</fullName>
            </value>
            <value>
                <fullName>Bonus commerciale</fullName>
            </value>
            <value>
                <fullName>Accollo totale</fullName>
            </value>
            <value>
                <fullName>Riattivazione non morose</fullName>
            </value>
            <value>
                <fullName>Modifica dati contr. stesso Cli</fullName>
                <isActive>false</isActive>
                <label>Modifica dati contr. stesso Cli</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReassignmentReason__c.field-meta.xml
<CustomField>
    <fullName>ReassignmentReason__c</fullName>
    <label>Causale Riassegnazione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standby per attesa cessazione contratto</fullName>
            </value>
            <value>
                <fullName>Attesa approvazione</fullName>
            </value>
            <value>
                <fullName>Sospensione per lavorazione in corso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SendMode__c.field-meta.xml
<CustomField>
    <fullName>SendMode__c</fullName>
    <description>Modalità invio</description>
    <label>Modalità invio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SendMode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <description>Approved</description>
    <label>Approvazione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Viene restituito il canale di vendita dell&apos;ordine padre correlato, oppure dell&apos;ordine padre dell&apos;ordine correlato all&apos;attività</description>
    <formula>IF(Order__r.ParentOrder__c = null, Order__r.Channel__c , Order__r.ParentOrder__r.Channel__c)</formula>
    <label>Canale di vendita</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <description>Campo Note compilabile dall&apos;operatore</description>
    <label>Note</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OrderID</description>
    <label>Order Correlato</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <formula>IF(NOT(ISNULL(Case__c)), TEXT(Case__r.Phase__c), IF(NOT(ISNULL(Order__c)), TEXT(Order__r.Phase__c), &quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo attività</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Anticipo Appuntamento</fullName>
            </value>
            <value>
                <fullName>Approvazione Bonus Commerciale</fullName>
            </value>
            <value>
                <fullName>Approvazione Offerte</fullName>
            </value>
            <value>
                <fullName>Assistenza Contact Center</fullName>
            </value>
            <value>
                <fullName>Attesa Preventivo DL</fullName>
            </value>
            <value>
                <fullName>Attivazioni</fullName>
            </value>
            <value>
                <fullName>Back Office - Catalogo Prodotti</fullName>
            </value>
            <value>
                <fullName>Back Office - Contratti</fullName>
            </value>
            <value>
                <fullName>Back Office - Fatturazione</fullName>
            </value>
            <value>
                <fullName>Back Office - Morosità</fullName>
            </value>
            <value>
                <fullName>Back Office - Pagamenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Preventivi</fullName>
            </value>
            <value>
                <fullName>Back Office - Supporto/Comunicazioni Urgenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Tari/TCP</fullName>
            </value>
            <value>
                <fullName>Back Office - Vas e HVAC</fullName>
            </value>
            <value>
                <fullName>Busta Docusign non consegnata</fullName>
            </value>
            <value>
                <fullName>Caricamenti contratti</fullName>
            </value>
            <value>
                <fullName>Caricamento Manuale Siebel</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Chiamata Callback</fullName>
            </value>
            <value>
                <fullName>Chiamata inbound</fullName>
            </value>
            <value>
                <fullName>Chiamata outbound</fullName>
            </value>
            <value>
                <fullName>Comfort Call</fullName>
            </value>
            <value>
                <fullName>Comunicazione da DL</fullName>
            </value>
            <value>
                <fullName>Comunicazioni con DL</fullName>
            </value>
            <value>
                <fullName>Conferma Preventivo</fullName>
            </value>
            <value>
                <fullName>Contratti/Bonus Commerciale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/recordTypes/HDT_RT_AttivitaGestionali.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_AttivitaGestionali</fullName>
    <active>true</active>
    <description>Record type per gli le activiti Gestionali</description>
    <label>AttivitàGestionali</label>
</RecordType>

force-app/main/default/globalValueSets/HDT_SendMode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>E-Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Posta Cartacea</fullName>
    </customValue>
    <customValue>
        <fullName>Stampa Cartacea</fullName>
    </customValue>
    <masterLabel>Send Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_RecordEditFormSales.cls
/**
* @author Sabina Levonja (sabina.levonja@dunegroup.it)
* @date 16/06/21
* @description HDT_LC_RecordEditFormSales
* @history Sabina Levonja – 16/06/21 – created class
*/
public with sharing class HDT_LC_RecordEditFormSales {

    public static HDT_SRV_Case caseSRV= new HDT_SRV_Case();
    public static HDT_SRV_ActivityCustom activitySrv= new HDT_SRV_ActivityCustom();
    public static HDT_QR_RecordType rctype= new HDT_QR_RecordType();
    public static HDT_QR_Case caseQr = new HDT_QR_Case();
  //  public static HDT_QR_Recordtype rctype = new HDT_QR_Recordtype();
    @AuraEnabled
    public static void cancelCase(String caseId){
        try {
            Case cs= new Case(Id= caseId, Phase__c='Annullato', Status='Closed');
            caseSRV.updateRecord(cs);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static wrapReturn getActivity(String caseId){
        List<Case> caseList = caseQr.getRecordsById(new List<String>{caseId},'id,AccountId,Channel__c,CopyType__c,sendmode__c,order__c,OperationSubType__c,OperationType__c,Contract__c');
        List<wrts_prcgvr__Activity__c> listActiv = HDT_QR_ActivityCustom.getRecordByCaseId(caseId);
        Case res = new Case();
        wrapReturn wrp = new wrapReturn();
        wrp.c = res;

        //List<wrts_prcgvr__Activity__c> obbList = HDT_QR_ActivityCustom.getRecordByCaseId(caseid);
      //  wrts_prcgvr__Activity__c res;
        if(caseList != null && !caseList.isEmpty()){
            res = caseList[0];
        } 
        if(listActiv != null && !listActiv.isEmpty() && listActiv[0].approved__c != null){
            wrp.disabled = true;
        }
        wrp.c = res;
        return wrp;
    }

    
    @AuraEnabled
    public static Boolean confirmForApproval(String caseId, String accountId){
        try {
           // Case cs= new Case(Id=caseId);
           // caseSRV.updateRecord(cs); 
            List<wrts_prcgvr__Activity__c> activities= HDT_QR_ActivityCustom.getRecordByCaseId(caseId);
            if(activities != null && activities.isEmpty()){
                Id recTypeId= null;
                RecordType rc= rctype.getRecordType('HDT_RT_AttivitaGestionali', 'wrts_prcgvr__Activity__c');
                if(rc !=null){
                    recTypeId= rc.Id;
                }
                wrts_prcgvr__Activity__c activity= new wrts_prcgvr__Activity__c(Case__c= caseId, Account__c= accountId, RecordTypeId= recTypeId, Type__c= 'Contratti/Bonus Commerciale');
                System.debug('LOG_ACTIVITY_MISSING2:');
                System.debug(activity);
                //activitySrv.createRecord(activity);
                System.debug('LOG_ACTIVITY_MISSING2:');
                return false;
            }else{
                return true;
            }
        } catch (Exception e) {
            System.debug('LOG_ACTIVITY_MISSING:' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String savePractice(String caseId, String accountId, Map<String,Object> caseob){
        try {
            Case cs= new Case(Id=caseId,status='Closed', Phase__c='Completata');
            String note = '';
            if(caseob.containsKey('OperationSubType__c')){
                cs.put('OperationSubType__c',String.valueOf(caseob.get('OperationSubType__c')));
            }
            if(caseob.containsKey('Contract__c')){
                cs.put('Contract__c',String.valueOf(caseob.get('Contract__c')));
            }
           /* if(caseob.containsKey('ReassignmentReason__c')){
                cs.put('ReassignmentReason__c',String.valueOf(caseob.get('ReassignmentReason__c')));
            }*/
            if(caseob.containsKey('OperationType__c')){
                cs.put('OperationType__c',String.valueOf(caseob.get('OperationType__c')));
            }
            if(caseob.containsKey('Note__c')){
                cs.put('Note__c',String.valueOf(caseob.get('Note__c')));
                note = String.valueOf(caseob.get('Note__c'));
            }
           // caseSRV.updateRecord(cs); 
            List<wrts_prcgvr__Activity__c> activities= HDT_QR_ActivityCustom.getRecordByCaseId(caseId);
            if(activities != null && !activities.isEmpty() && activities[0].wrts_prcgvr__status__c == 'Chiusa' && activities[0].approved__c == 'Si'){
                caseSRV.updateRecord(cs); 
                Id recTypeId= null;
                RecordType rc= rctype.getRecordType('HDT_RT_AttivitaGestionali', 'wrts_prcgvr__Activity__c');
                if(rc !=null){
                    recTypeId= rc.Id;
                }
                wrts_prcgvr__Activity__c activity= new wrts_prcgvr__Activity__c(Case__c= caseId, Account__c= accountId, RecordTypeId= recTypeId, Type__c= 'Contratti/Bonus Commerciale');
                System.debug(activity);
                activitySrv.createRecord(activity);
                return 'success';
            }
            else if(activities != null && !activities.isEmpty() && activities[0].wrts_prcgvr__status__c == 'Chiusa' && activities[0].approved__c == 'No'){
                return 'annulla';
            }
            else if(activities != null && !activities.isEmpty() && activities[0].wrts_prcgvr__status__c != 'Chiusa'){
                return 'aperta';
            }
            else if(activities != null && activities.isEmpty()){
                cs.status = 'In Lavorazione';
                cs.Phase__c = 'In Lavorazione';
                caseSRV.updateRecord(cs);
                Id recTypeId= null;
                RecordType rc= rctype.getRecordType('HDT_RT_AttivitaGestionali', 'wrts_prcgvr__Activity__c');
                if(rc !=null){
                    recTypeId= rc.Id;
                }
                wrts_prcgvr__Activity__c activity= new wrts_prcgvr__Activity__c(Case__c= caseId, Account__c= accountId, RecordTypeId= recTypeId, Type__c= 'Approvazione Bonus Commerciale');
                activity.OpeningNote__c = note;
                activitySrv.createRecord(activity);
                return 'success2';
            }
            else{
                return 'errore';
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
           // return 'errore';
        }
    }
    @AuraEnabled
    public static void saveDraft(String caseId, String accountId, Map<String,Object> caseob){
        try {
            Case cs= new Case(Id=caseId);

            if(caseob.containsKey('OperationSubType__c')){
                cs.put('OperationSubType__c',String.valueOf(caseob.get('OperationSubType__c')));
            }
            if(caseob.containsKey('Contract__c')){
                cs.put('Contract__c',String.valueOf(caseob.get('Contract__c')));
            }
            if(caseob.containsKey('ReassignmentReason__c')){
                cs.put('ReassignmentReason__c',String.valueOf(caseob.get('ReassignmentReason__c')));
            }
            if(caseob.containsKey('OperationType__c')){
                cs.put('OperationType__c',String.valueOf(caseob.get('OperationType__c')));
            }
            if(caseob.containsKey('Note__c')){
                cs.put('Note__c',String.valueOf(caseob.get('Note__c')));
            }
            caseSRV.updateRecord(cs); 
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   
    public class wrapReturn{
        @AuraEnabled public Case c {get;set;}
        @AuraEnabled public boolean disabled = false;
    }
}