force-app/main/default/objects/Case/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Nome del Cluster a cui appartiene un processo.</description>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_EmailComunicazioneGestore__mdt/HDT_EmailComunicazioneGestore__mdt.object-meta.xml
<CustomObject>
    <label>HDT_EmailComunicazioneGestore</label>
    <pluralLabel>HDT_EmailComunicazioneGestore</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_EmailComunicazioneGestore__mdt/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_EmailComunicazioneGestore__mdt/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <label>Email Template Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_MailSender.cls
public inherited sharing class HDT_QR_MailSender {

    public static List<Folder> getFolderList(String folderName){
        return [
            SELECT Id
            FROM Folder
            WHERE Name = :folderName
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<EmailTemplate> getEmailTemplateList(Id folderId){
        return [
            SELECT Id, Body, DeveloperName, FolderId, FolderName, IsActive, Name
            FROM EmailTemplate
            WHERE IsActive = true
            AND FolderId = :folderId
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<EmailTemplate> getEmailTemplateByNameList(String templateName){
        return [
            SELECT Id, Body, DeveloperName, FolderId, FolderName, IsActive, Name, HtmlValue
            FROM EmailTemplate
            WHERE IsActive = true
            AND Name = :templateName
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<OrgWideEmailAddress> getOrgWideEmailAddressList(String displayName){
        return [
            SELECT Id, Address, DisplayName
            FROM OrgWideEmailAddress
            WHERE DisplayName = :displayName
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }

    public static List<EmailTemplate> getEmailTemplateById(Id templateId){
        return [
            SELECT Id, Body, DeveloperName, FolderId, FolderName, IsActive, Name
            FROM EmailTemplate
            WHERE IsActive = true
            AND Id = :templateId
            WITH SECURITY_ENFORCED
        ];
    }

    public static Integer getChildCase(Id parentId){
        return [
            SELECT count()
            FROM Case
            WHERE ParentId = :parentId
            AND Type = 'Comunicazione con il Gestore'
            AND Cluster__c = 'Informative'
        ];
    }

    public static String getEmail(String emailTemplateName){
        //return [
        //    SELECT Email_Template_Name__c, Email__c, DeveloperName, MasterLabel
        //    FROM HDT_EmailComunicazioneGestore__mdt
        //    WHERE Email_Template_Name__c = :emailTemplateName
        //    WITH SECURITY_ENFORCED
        //    LIMIT 1
        //].Email__c;
        return null;
    }

    public static List<EmailMessage> getEmailMessage(Id caseId, String Subject){
        return [
            SELECT EmailTemplateId, ParentId, RelatedToId, Status, Subject, ToAddress
            FROM EmailMessage
            WHERE RelatedToId = :caseId
            AND Subject = :Subject
            WITH SECURITY_ENFORCED
        ];
    }

}