force-app/main/default/objects/Case/fields/CommodityFormula__c.field-meta.xml
<CustomField>
    <fullName>CommodityFormula__c</fullName>
    <description>Settore merceologico preso in Lookup dal Service Point</description>
    <formula>IF(TEXT(ServicePoint__r.CommoditySector__c) != &apos;&apos;,TEXT(ServicePoint__r.CommoditySector__c), TEXT(Commodity__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_UTL_Variations.cls
public inherited sharing class HDT_UTL_Variations {


    public static Boolean consistencyCheck(String recordId, String useCategory, String supplyType, String servicePointType){

        return HDT_QR_Variations.queryConsistencyTable(recordId, useCategory, supplyType, servicePointType);

    }

    public static Boolean modifyRate(String caseId){

        List<Case> otherCases = new List<Case>();

        Boolean check;

        Integer flag = 0;
        Integer count = 0;

        Case currentCase =  HDT_QR_Variations.getCaseInfo(caseId);


        List<ServicePoint__c> servicePoints = HDT_QR_Variations.queryServicePoint(currentCase.AccountId,
            currentCase.CommodityFormula__c, currentCase.ServicePoint__c);

        List<Id> spIds= new List<Id>();

        if(servicePoints.size() > 0){        
            
            for(ServicePoint__c sp : servicePoints){

                spIds.add(sp.Id);

          }

            otherCases = HDT_QR_Variations.queryOtherCases(spIds, caseId);

            if(otherCases.size() == 0){

                check = false;

            } else {

                for(Id spId : spIds){

                    flag = 0;

                    for(Case c : otherCases){

                        if(c.ServicePoint__c == spId){

                            ++flag;

                        }

                    }

                    if(flag > 0){

                        ++count;

                    }

                }

                if(count == spIds.size()){

                    check = true;

                } else {

                    check = false;

                }

            }
        
        }else{

            check = true;

        }

        return check;


    }

}