force-app/main/default/objects/Case/fields/ComplaintType__c.field-meta.xml
<CustomField>
    <fullName>ComplaintType__c</fullName>
    <label>Tipologia Reclamo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reclamo Scritto</fullName>
            </value>
            <value>
                <fullName>Richiesta Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FirstLevelComplaintClassification__c.field-meta.xml
<CustomField>
    <fullName>FirstLevelComplaintClassification__c</fullName>
    <label>1° Livello</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ComplaintType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Reclamo Scritto</fullName>
            </value>
            <value>
                <fullName>Rettifica Doppia Fatturazione</fullName>
            </value>
            <value>
                <fullName>Richiesta di informazioni</fullName>
            </value>
            <value>
                <fullName>Richiesta di Rettifica di fatturazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IndemnityConfirmed__c.field-meta.xml
<CustomField>
    <fullName>IndemnityConfirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generazione possibile indennizzo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SecondLevelComplaintClassification__c.field-meta.xml
<CustomField>
    <fullName>SecondLevelComplaintClassification__c</fullName>
    <label>2° Livello</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FirstLevelComplaintClassification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Altro</fullName>
            </value>
            <value>
                <fullName>Bonus sociale</fullName>
            </value>
            <value>
                <fullName>Connessioni, lavori e qualità tecnica</fullName>
            </value>
            <value>
                <fullName>Contratti</fullName>
            </value>
            <value>
                <fullName>Doppia Fatturazione</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Impatti Ambientali</fullName>
            </value>
            <value>
                <fullName>Mercato</fullName>
            </value>
            <value>
                <fullName>Misura</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Morosità e sospensione</fullName>
            </value>
            <value>
                <fullName>Qualità Commerciale</fullName>
            </value>
            <value>
                <fullName>Qualità del Servizio</fullName>
            </value>
            <value>
                <fullName>Servizio Clienti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_SRV_IndemnityConfirmationTst.cls
@isTest
public with sharing class HDT_SRV_IndemnityConfirmationTst {
    
    //DEBUG
    public static final String TEST_NAME = 'HDT_SRV_IndemnityConfirmationTst';
    
    //DATA
    private static HDT_UTL_Constants utlConstants = new HDT_UTL_Constants();
    
    
    //TEST SETUP
    private static void mySetup(){
        List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<Order> ordList = HDT_UTL_DataFactoryTst.createOrder(1, true, accList[0].id, 'Bozza');
        List<ServicePoint__c> servPointList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        List<Contact> contactList = HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].Id);
        List<Contract> contractList = HDT_UTL_DataFactoryTst.createContract(1, true, accList[0].id);
    }
    
    
    //TESTS
    @isTest
    private static void checkIndemnityConfirmationTest() {
        
        //DEBUG
        String debugString = TEST_NAME + ' - ' + 'checkIndemnityConfirmationTest';
        System.debug(debugString);
        
        //SETUP
        mySetup();
        
        Account acc = [SELECT Id FROM Account];
        Contact con = [SELECT Id FROM Contact];
        ServicePoint__c srv = [SELECT Id FROM ServicePoint__c];
        Contract contract = [SELECT Id FROM Contract];
        Order ord = [SELECT Id FROM Order];
        
        //MY CASE 1
        Case myCase_1 = HDT_UTL_DataFactoryTst.createCaseDocumentale(1, false, acc.id, con.Id, srv.id, contract.id, ord.id)[0];
        myCase_1.ComplaintType__c = 'Reclamo Scritto';
        myCase_1.FirstLevelComplaintClassification__c = 'Reclamo Scritto';
        myCase_1.SecondLevelComplaintClassification__c = 'Misura';
        myCase_1.IndemnityConfirmed__c = true;
        insert myCase_1;
        
        //MY CASE 2
        Case myCase_2 = HDT_UTL_DataFactoryTst.createCaseDocumentale(1, false, acc.id, con.Id, srv.id, contract.id, ord.id)[0];
        insert myCase_2;
        
        //HDT_UTL_FlowInputs
        HDT_SRV_IndemnityConfirmation.HDT_UTL_FlowInputs input = new HDT_SRV_IndemnityConfirmation.HDT_UTL_FlowInputs();
        input.recordId = myCase_2.Id;
        input.accountId = acc.Id;
        input.servicePointId = srv.Id;
        input.firstLevel = myCase_1.FirstLevelComplaintClassification__c;
        input.secondLevel = myCase_1.SecondLevelComplaintClassification__c;
        
        List<HDT_SRV_IndemnityConfirmation.HDT_UTL_FlowInputs> inputs;
        inputs = new List<HDT_SRV_IndemnityConfirmation.HDT_UTL_FlowInputs>{input};
        
        
        //TESTING
        List<HDT_SRV_IndemnityConfirmation.HDT_UTL_FlowOutputs> outputs;
        outputs = HDT_SRV_IndemnityConfirmation.checkIndemnityConfirmation(inputs);
        
        //ASSERTS
        HDT_SRV_IndemnityConfirmation.HDT_UTL_FlowOutputs output = outputs[0];
        System.assert(output.indemnityNotConfirmed);
        
    }
    
}