force-app/main/default/objects/Case/fields/ContractCode__c.field-meta.xml
<CustomField>
    <fullName>ContractCode__c</fullName>
    <description>Codice contratto preso in lookup dal Contract</description>
    <formula>Contract__r.SAPContractCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Codice contratto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ElementDetail__c.field-meta.xml
<CustomField>
    <fullName>ElementDetail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Elementi di Dettaglio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Esito OK da SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/TecnicalPhase__c.field-meta.xml
<CustomField>
    <fullName>TecnicalPhase__c</fullName>
    <description>Campo Tecnico di appoggio per la gestione del doppio cambio di fase.</description>
    <label>Fase Tecnica</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TecnicalPhase__c.field-meta.xml
<CustomField>
    <fullName>TecnicalPhase__c</fullName>
    <description>Campo Tecnico di appoggio per la gestione del doppio cambio di fase.</description>
    <label>Fase Tecnica</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_SRV_ModificaLayoutFatturaTst.cls
@SuppressWarnings('PMD.AvoidDebugStatements, PMD.DebugsShouldUseLoggingLevel')
@isTest
public with sharing class HDT_SRV_ModificaLayoutFatturaTst {
    
    //DEBUG
    public static final String TEST_NAME = 'HDT_SRV_ModificaLayoutFatturaTst';
    
    //DATA
    private static HDT_UTL_Constants constants = new HDT_UTL_Constants();
    
    
    //TEST SETUP
    @SuppressWarnings('PMD.UnusedLocalVariable')
    private static void mySetup(){
        
        List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<Order> ordList = HDT_UTL_DataFactoryTst.createOrder(1, true, accList[0].id, 'Bozza');
        List<ServicePoint__c> servPointList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        List<Contact> contactList = HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].Id);
        List<Contract> contractList = HDT_UTL_DataFactoryTst.createContract(1, true, accList[0].id);
        List<Case> caseList = HDT_UTL_DataFactoryTst.createCase(1, true, accList[0].id, contactList[0].Id, servPointList[0].id, contractList[0].id, ordList[0].id);
        
    }

    /**@frpanico 19/10/2021
     * Added TestSetup
     */
    @TestSetup
    static void setup()
    {
        HDT_UTL_DataFactoryTst.pClickInstance();
        HDT_UTL_DataFactoryTst.pClickCasePhase();
    }
    
    //TESTS
    
    //executeTest
    @isTest
    private static void executeTestOk() {
        
        //DEBUG
        String debugString = 'HDT_SRV_ModificaLayoutFatturaTst - executeTest_ok';
        
        //SETUP
        mySetup();
        
        
        String methodOk = 'ModificaLayoutFattura';//NOTA: in verità è endpoint.
        
        Case obj = [SELECT Id, CaseNumber, ContractCode__c, ElementDetail__c FROM Case];
        System.debug(debugString + ' - case obj: ' + obj);
        
        Map<String, Object> argsMap = new Map<String,Object>();
        argsMap.put('method', methodOk);
        argsMap.put('sender', obj);
        
        //WEBSERVICE MOCK
        Test.setMock(HttpCalloutMock.class, new MyMockForTest());
        
        //TESTING
        Test.startTest();
        HDT_SRV_ModificaLayoutFattura myObjectToTest = new HDT_SRV_ModificaLayoutFattura();
        wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse result = (wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse) myObjectToTest.execute(argsMap);
        Test.stopTest();
        
        //RETRIEVING DATA
        Case myCase = [SELECT Id, Phase__c,TecnicalPhase__c FROM Case];
        
        //ASSERTS
        System.assert(result.success, 'Result non true.');
        System.assertEquals('OK', result.message, 'Message non OK');
        //@frpanico 20/09/2021 a seguito di modifica classe adeguata anche classe di test
        //TODO: 'Errore Lavorazione SAP'
        //System.assertEquals('Completata', myCase.TecnicalPhase__c, 'Tecnical Phase errata.');
        
    }
    
    @isTest
    private static void executeTestNull() {
        
        //DEBUG
        String debugString = 'HDT_SRV_ModificaLayoutFatturaTst - executeTest_null';
        
        //SETUP
        mySetup();
        
        
        //TESTING
        String methodDataNull = 'ModificaLayoutFattura_null';//NOTA: in verità è endpoint.
        
        Case obj = [SELECT Id, CaseNumber, ContractCode__c, ElementDetail__c FROM Case];
        System.debug(debugString + ' - case obj: ' + obj);
        
        Map<String, Object> argsMap = new Map<String,Object>();
        argsMap.put('method', methodDataNull);
        argsMap.put('sender', obj);
        
        //WEBSERVICE MOCK
        Test.setMock(HttpCalloutMock.class, new MyMockForTest());
        
        //TESTING
        Test.startTest();
        HDT_SRV_ModificaLayoutFattura myObjectToTest = new HDT_SRV_ModificaLayoutFattura();
        wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse result = (wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse) myObjectToTest.execute(argsMap);
        Test.stopTest();
        
        //RETRIEVING DATA
        Case myCase = [SELECT Id, Phase__c,TecnicalPhase__c FROM Case];
        
        //ASSERTS
        System.assert(result.success, 'Result non true.');
        System.assertEquals('OK', result.message, 'Message non OK');
        //@frpanico 20/09/2021 a seguito di modifica classe adeguata anche classe di test
        System.assertEquals('Errore Lavorazione SAP', myCase.TecnicalPhase__c, 'Tecnical Phase errata');//TODO: 'Errore Lavorazione SAP'
        
    }
    
    @isTest
    private static void executeTestNotOk() {
        
        //DEBUG
        String debugString = 'HDT_SRV_ModificaLayoutFatturaTst - executeTest_NotOk';
        
        //SETUP
        mySetup();
        
        
        //TESTING
        String methodNotOk = 'ModificaLayoutFattura_notOK';//NOTA: in verità è endpoint.
        
        Case obj = [SELECT Id, CaseNumber, ContractCode__c, ElementDetail__c FROM Case];
        System.debug(debugString + ' - case obj: ' + obj);
        
        Map<String, Object> argsMap = new Map<String,Object>();
        argsMap.put('method', methodNotOk);
        argsMap.put('sender', obj);
        
        //WEBSERVICE MOCK
        Test.setMock(HttpCalloutMock.class, new MyMockForTest());
        
        //TESTING
        Test.startTest();
        HDT_SRV_ModificaLayoutFattura myObjectToTest = new HDT_SRV_ModificaLayoutFattura();
        wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse result = (wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse) myObjectToTest.execute(argsMap);
        Test.stopTest();
        
        //RETRIEVING DATA
        Case myCase = [SELECT Id, Phase__c,TecnicalPhase__c FROM Case];
        
        //ASSERTS
        System.assert(result.success, 'Result non true.');
        System.assertEquals('OK', result.message, 'Message non OK');
        //@frpanico 20/09/2021 a seguito di modifica classe adeguata anche classe di test
        System.assertEquals('Errore Lavorazione SAP', myCase.TecnicalPhase__c, 'Tecnical Phase errata');//TODO: 'Errore Lavorazione SAP'
        
    }
    
    
    
    
    //WEBSERVICE MOCK
    @SuppressWarnings('PMD.ClassNamingConventions')
    public class MyMockForTest implements HTTPCalloutMock{
        
        public HTTPResponse respond(HTTPRequest request){
            
            HttpResponse response = new HttpResponse();
            System.debug(LoggingLevel.DEBUG, 'request.getEndpoint: ' + request.getEndpoint());
            
            if('Callout:ModificaLayoutFattura'.equals(request.getEndpoint())){
                
                HDT_SRV_ModificaLayoutFattura.HDT_WRP_Data wrpData = new HDT_SRV_ModificaLayoutFattura.HDT_WRP_Data();
                wrpData.rds = 'rds';
                wrpData.attivita = 'Esito OK da SAP';
                
                HDT_SRV_ModificaLayoutFattura.HDT_WRP_SuccessResponse bodyResp = new HDT_SRV_ModificaLayoutFattura.HDT_WRP_SuccessResponse();
                bodyResp.status = 'TST_Status';
                bodyResp.correlationId = 'TST_CorrelId';
                bodyResp.timestamp = 'TST_TimeStamp';
                bodyResp.data = wrpData;
                
                
                String bodyResponse = JSON.serialize(bodyResp);
                
                response.setHeader('Content-Type', 'application/json');
                response.setBody(bodyResponse);
                response.setStatusCode(200);
                response.setStatus('OK');
                
            } else if('Callout:ModificaLayoutFattura_null'.equals(request.getEndpoint())){
                
                HDT_SRV_ModificaLayoutFattura.HDT_WRP_SuccessResponse bodyResp = new HDT_SRV_ModificaLayoutFattura.HDT_WRP_SuccessResponse();
                
                bodyResp.status = 'TST_Status';
                bodyResp.correlationId = 'TST_CorrelId';
                bodyResp.timestamp = 'TST_TimeStamp';
                bodyResp.data = null;//TARGET
                
                
                String bodyResponse = JSON.serialize(bodyResp);
                
                response.setHeader('Content-Type', 'application/json');
                response.setBody(bodyResponse);
                response.setStatusCode(200);
                response.setStatus('OK');
                
            } else if('Callout:ModificaLayoutFattura_notOK'.equals(request.getEndpoint())){
                
                HDT_SRV_ModificaLayoutFattura.HDT_WRP_Data wrpData = new HDT_SRV_ModificaLayoutFattura.HDT_WRP_Data();
                wrpData.rds = 'rds';
                wrpData.attivita = 'Test';//TARGET
                
                HDT_SRV_ModificaLayoutFattura.HDT_WRP_SuccessResponse bodyResp = new HDT_SRV_ModificaLayoutFattura.HDT_WRP_SuccessResponse();
                bodyResp.status = 'TST_Status';
                bodyResp.correlationId = 'TST_CorrelId';
                bodyResp.timestamp = 'TST_TimeStamp';
                bodyResp.data = wrpData;
                
                String bodyResponse = JSON.serialize(bodyResp);
                
                response.setHeader('Content-Type', 'application/json');
                response.setBody(bodyResponse);
                response.setStatusCode(200);
                response.setStatus('OK');
                
                return response;
                
            } else {
                System.debug(LoggingLevel.DEBUG, 'Invalid Callout Endpoint - Empty HTTP Response.');
                
            }
            
            return response;
        }
        
    }
    
    
}