force-app/main/default/objects/Case/fields/CreatorGroup__c.field-meta.xml
<CustomField>
    <fullName>CreatorGroup__c</fullName>
    <label>Gruppo Creatore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CreatorGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In attesa di lavorazione</fullName>
                <default>true</default>
                <label>In attesa di lavorazione</label>
            </value>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Errore</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
                <isActive>false</isActive>
                <label>Done</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Ready To Run</fullName>
                <isActive>false</isActive>
                <label>Ready To Run</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CreatorGroup__c.field-meta.xml
<CustomField>
    <fullName>CreatorGroup__c</fullName>
    <label>Gruppo Creatore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/LoginChannel__c.field-meta.xml
<CustomField>
    <fullName>LoginChannel__c</fullName>
    <label>Canale di Login</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CreatorGroup__c.field-meta.xml
<CustomField>
    <fullName>CreatorGroup__c</fullName>
    <label>Gruppo Creatore</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LoginChannel__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CreatorGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/LoginADN__c.field-meta.xml
<CustomField>
    <fullName>LoginADN__c</fullName>
    <description>Campo chiesto da Everis per l&apos;integrazione con SIGMA, corrisponde alla concatenazione del FirstName e del LastName separati da un punto.</description>
    <formula>LOWER(FirstName+&apos;.&apos;+LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Login ADN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/LoginChannel__c.field-meta.xml
<CustomField>
    <fullName>LoginChannel__c</fullName>
    <description>Indica il canale di riferimento dell&apos;utente</description>
    <label>Canale Login</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetName>HDT_LoginChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ActivityOutcome__c.field-meta.xml
<CustomField>
    <fullName>ActivityOutcome__c</fullName>
    <description>Per salvare l&apos;esito di una generica lavorazione</description>
    <label>Esito attività</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positivo</fullName>
            </value>
            <value>
                <fullName>Negativo</fullName>
            </value>
            <value>
                <fullName>Dati corretti forniti da cliente e cambio uso inserito</fullName>
            </value>
            <value>
                <fullName>Dati corretti forniti da cliente e cambio uso - non necessario</fullName>
            </value>
            <value>
                <fullName>Dati corretti forniti dal DL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ClosedByUsername__c.field-meta.xml
<CustomField>
    <fullName>ClosedByUsername__c</fullName>
    <label>Utente chiusura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ClosingCreatorGroup__c.field-meta.xml
<CustomField>
    <fullName>ClosingCreatorGroup__c</fullName>
    <label>Gruppo Creatore di Chiusura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CreatorGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ClosingUserChannel__c.field-meta.xml
<CustomField>
    <fullName>ClosingUserChannel__c</fullName>
    <label>Canale Utente di Chiusura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/CreatorGroup__c.field-meta.xml
<CustomField>
    <fullName>CreatorGroup__c</fullName>
    <label>Gruppo Creatore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CreatorGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/LoginChannel__c.field-meta.xml
<CustomField>
    <fullName>LoginChannel__c</fullName>
    <label>Canale di Vendita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OrderID</description>
    <label>Order Correlato</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Stato dell&apos;attività</description>
    <label>Stato Lavorazione Attività</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Null</fullName>
            </value>
            <value>
                <fullName>Creata</fullName>
                <default>true</default>
                <label>Creata</label>
            </value>
            <value>
                <fullName>Invio app.to SELF cliente</fullName>
            </value>
            <value>
                <fullName>Presa appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Appuntamento di competenza Distributore</fullName>
            </value>
            <value>
                <fullName>Appuntamento confermato</fullName>
            </value>
            <value>
                <fullName>Modifica appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Modifica confermata</fullName>
            </value>
            <value>
                <fullName>Appuntamento non eseguito</fullName>
            </value>
            <value>
                <fullName>Appuntamento eseguito</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
            <value>
                <fullName>Comunicazione Inviata</fullName>
            </value>
            <value>
                <fullName>KO Risolto</fullName>
            </value>
            <value>
                <fullName>KO Definitivo</fullName>
            </value>
            <value>
                <fullName>KO Forzato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/wrts_prcgvr__Status__c.field-meta.xml
<CustomField>
    <fullName>wrts_prcgvr__Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aperta</fullName>
                <default>true</default>
                <label>Aperta</label>
            </value>
            <value>
                <fullName>Sospesa</fullName>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
            <value>
                <fullName>Creata</fullName>
            </value>
            <value>
                <fullName>Presa appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Appuntamento confermato</fullName>
            </value>
            <value>
                <fullName>Appuntamento non eseguito</fullName>
            </value>
            <value>
                <fullName>Appuntamento eseguito</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
            <value>
                <fullName>Invio app.to SELF cliente</fullName>
            </value>
            <value>
                <fullName>Appuntamento di competenza Distributore</fullName>
            </value>
            <value>
                <fullName>Scartata</fullName>
            </value>
            <value>
                <fullName>Modifica confermata</fullName>
            </value>
            <value>
                <fullName>Modifica appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Esitata</fullName>
            </value>
            <value>
                <fullName>Non Esitata</fullName>
            </value>
            <value>
                <fullName>Comunicazione inviata</fullName>
            </value>
            <value>
                <fullName>Comunicazione inviata</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>KO Forzato</fullName>
            </value>
            <value>
                <fullName>KO Risolto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CreatorGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AA CALL TS OUT</fullName>
    </customValue>
    <customValue>
        <fullName>AA SPORT TS OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_Back Office Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CDO_OM</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CDO_OM_OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CDO_PPT_DISCO</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CDO_PPT_DISCO_OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CDO_PPT_QMMUI</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CDO_PPT_QMMUI_OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CDO_S&amp;MS</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CORPMUI_CORP</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CORPMUI_CORP_CC_OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CORPMUI_CORP_OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CORPMUI_MUI</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CORPMUI_MUI_CC_OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CORPMUI_MUI_OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CREDITO</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CREDITO OUT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_AGGOP_STAFF</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_CC_OUT_CMDGRP</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_CC_OUT_KN</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_CC_OUT_LT</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_CC_OUT_VK</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_CC_STAFF</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_CH_OUT_CD</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_HD_LTCH</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_SDEST_CE</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_SDEST_FO</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_SDEST_RA</fullName>
    </customValue>
    <customValue>
        <fullName>HC_CRM_SDEST_RN</fullName>
    </customValue>
    <description>Gruppo creatore dell&apos; utente</description>
    <masterLabel>Gruppo Creatore</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_LoginChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Assistente web</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Callback</fullName>
    </customValue>
    <customValue>
        <fullName>Camper</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
    </customValue>
    <customValue>
        <fullName>Da PGM</fullName>
    </customValue>
    <customValue>
        <fullName>HC_WEB</fullName>
    </customValue>
    <customValue>
        <fullName>Helpdesk</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <customValue>
        <fullName>Protocollo</fullName>
    </customValue>
    <customValue>
        <fullName>ServiziSociali</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SOL</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Supporto agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Supporto GDA</fullName>
    </customValue>
    <customValue>
        <fullName>Telefono Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Telefono Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Business</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita MM</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <description>Canale login dell&apos;utente</description>
    <masterLabel>Canale Login</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_ProcessChiusuraMassivaActivity.cls
/**
 * @author Marco Ficorella NTTDATA
 * Classe utility per la gestione della chiusura massiva delle attività (custom) e aggiornamento della fase entità correlate (case o order)
 **/
@SuppressWarnings('PMD.AvoidDebugStatements')
public inherited sharing class HDT_UTL_ProcessChiusuraMassivaActivity extends HDT_UTL_ProcessExecution {
    List<MassiveLoaderRequestItem__c> itemsToSave;
    Map<String, String> mapActivityFields;
    Map<String, String> mapWrapperActivityFields;
    Map<String,wrts_prcgvr__Activity__c> mapActivityId;
    Map<Id,Id> mapActivityOrderId;
    Map<Id,Id> mapActivityCaseId;
    Map<String,User> mapUserAdn;
    Map<String,String> mapUserActId;

    Integer activityIndex;
    Integer faseIndex;
    Integer utenteIndex;
    Set<String> userNameSet;
    List<HDT_WRP_ProcessObjects> processObjList;
    HDT_WRP_ProcessObjects processObj;
    Set<String> activityIdSet;
    List<Order> orderToSave;
    List<Case> caseToSave;
    List<wrts_prcgvr__Activity__c> actToSave;

    public override void checks(){
        System.debug(LoggingLevel.DEBUG, 'checks');

        //System.debug(LoggingLevel.DEBUG, '>>> this.processName: ' + this.processName);
        itemsToSave = new List<MassiveLoaderRequestItem__c>();

        mapFieldsObject();
        // UTENTE_CHIUSURA  recuperare user da loginADN
        // CANALE_UTENTE_CHIUSURA LoginChannel__c user
        // GRUPPO_CREATORE_CHIUSURA CreatorGroup__c dello user che va verificato se corrisponde con l'utente chiusura e il canale


        
        activityIndex = mapHeaderForWrapper.get(mapWrapperActivityFields.get('ID_ATTIVITA'));
        faseIndex = mapHeaderForWrapper.get(mapWrapperActivityFields.get('FASE_PROCESSO'));
        utenteIndex = mapHeaderForWrapper.get(mapWrapperActivityFields.get('UTENTE_CHIUSURA'));


        System.debug(LoggingLevel.DEBUG, '>>> Index: activityIndex [' + activityIndex + '];  faseIndex [' + faseIndex + ']; userIndex [' + utenteIndex + '];  ');

        HDT_WRP_ProcessObjects processObj;
        processObjList = new List<HDT_WRP_ProcessObjects>();
        List<String> tempSplitedFields;
        userNameSet=new Set<String>();
        mapUserActId=new Map<String,String>();
        mapActivityId = new Map<String,wrts_prcgvr__Activity__c>();
        for(MassiveLoaderRequestItem__c item : requestItemList){

            tempSplitedFields = new List<String>();
            tempSplitedFields = item.Data__c.split(splitCharacter, -1);
            //verifica campi obbligatori
            checkRequiredFields(item, tempSplitedFields);
            System.debug(LoggingLevel.DEBUG, '>>> itemStatus' + item.Status__c);

            if(item.Status__c.equalsIgnoreCase('Errore')){
                itemsToSave.add(item);
                continue;
            }

            //inizializzazione processobj
            String activityId = tempSplitedFields[activityIndex];
            String utente = tempSplitedFields[utenteIndex];
            String fase = tempSplitedFields[faseIndex];

            userNameSet.add(utente);

            processObj = new HDT_WRP_ProcessObjects();
            processObj.requestItem = item;
            processObj.csvSplitted = tempSplitedFields;
            processObj.activity = new wrts_prcgvr__Activity__c();
            mapUserActId.put(activityId,utente);
            
            Integer count = 0;
            String convertionError;
            //popolamento automatico dei campi dell'activity e verifica dei valori picklist
            for (String tempField : processObj.csvSplitted) {

                if ('null'.equalsIgnoreCase(tempField)) {
                   tempField = '';
                }

                if(!String.isEmpty(convertionError)){
                    // error happened -> exit
                    break;
                }

                if(String.isNotBlank(mapActivityFields.get(mapHeaderByPosition.get(count))) && String.isNotBlank(tempField)){
                    System.debug(LoggingLevel.DEBUG, '>>> tempField: ' + tempField + ' # Header: ' + mapHeaderByPosition.get(count) + ' # ActivityFields: ' + mapActivityFields.get(mapHeaderByPosition.get(count)));
                    convertionError = mapTypeField(processObj.activity, mapActivityFields, count, tempField);

                    if(!String.isEmpty(convertionError)){
                        // error happened -> exit
                        break;
                    }
                }
                count++;
            }

            if(!String.isEmpty(convertionError)){
                itemsToSave.add(setErrorItem(processObj.requestItem, convertionError));
                continue;
            }

            if(errorForPicklistValue('wrts_prcgvr__Activity__c', 'ActivityOutcome__c', processObj.activity.ActivityOutcome__c)){
                itemsToSave.add(setErrorItem(processObj.requestItem, 'Valore Esito attività non corretto: ' + processObj.activity.ActivityOutcome__c));
                continue;
            }


            processObj.activity.Id = activityId;
            processObj.activity.wrts_prcgvr__Status__c = 'Chiusa';

            mapActivityId.put(activityId,processObj.activity);
            processObj.fase=fase;
            processObjList.add(processObj);

        }

    }


    public override void getRecords(){
        activityIdSet=mapActivityId.keySet();
        mapActivityOrderId=new Map<Id,Id>();
        mapActivityCaseId=new Map<Id,Id>();
        mapUserAdn=new Map<String,User>();
        //recupero delle attività
        List<wrts_prcgvr__Activity__c> activityList=HDT_QR_ProcessPostSales.getActivityById(activityIdSet);
        //eseguo mapping degli order e case correlati
        for(wrts_prcgvr__Activity__c activity:activityList){
            if(activity.Order__c!=null){
                mapActivityOrderId.put(activity.Id,activity.Order__c);
            }
            if(activity.Case__c!=null){
                mapActivityCaseId.put(activity.Id,activity.Case__c);
            }
        }
        //recupero gli user e li mappo
        List<User> userList=HDT_QR_ProcessPostSales.getUserByLoginAdn(userNameSet);
        for(User usr:userList){
            mapUserAdn.put(usr.LoginADN__c,usr);
        }


    }

    public override void registryCreation(){
        List<MassiveLoaderRequestItem__c> requestItemForUpsertAct = new List<MassiveLoaderRequestItem__c>();
        Map<Id,MassiveLoaderRequestItem__c> mapRequestItemForUpsertNext = new Map<Id,MassiveLoaderRequestItem__c>();
        List<MassiveLoaderRequestItem__c> requestItemForUpsertOrd = new List<MassiveLoaderRequestItem__c>();
        List<MassiveLoaderRequestItem__c> requestItemForUpsertCase = new List<MassiveLoaderRequestItem__c>();
        getLimitDetails('START registryCreation');
        actToSave = new List<wrts_prcgvr__Activity__c>();
        orderToSave = new List<Order>();
        caseToSave = new List<Case>();
        //preparazione aggiornamento entità
        //mappo prima gli user nell'activity
        for(HDT_WRP_ProcessObjects procObj:processObjList){
            wrts_prcgvr__Activity__c act=procObj.activity;
            String usrAdn=mapUserActId.get(act.Id);

            if(!mapUserAdn.containsKey(usrAdn)){
                itemsToSave.add(setErrorItem(procObj.requestItem, 'Utente non trovato con LoginADN: ' + usrAdn));
                continue;
            }

            User usr=mapUserAdn.get(usrAdn);
            

            act.ClosingUserChannel__c = usr.LoginChannel__c;
            act.ClosingCreatorGroup__c = usr.CreatorGroup__c;
            act.ClosedByUsername__c = usr.Username;

            actToSave.add(act);           
            
            requestItemForUpsertAct.add(procObj.requestItem);
        }

        if(!actToSave.isEmpty()){
            //salvo le activity
            HDT_WRP_SaveResponse saveResponse;
            saveResponse = databaseUpsert(actToSave, requestItemForUpsertAct, 'wrts_prcgvr__Activity__c');
            actToSave.clear();
            getLimitDetails('AFTER ACT CLOSE');
            
            Map<Id, String> errorItemMap=saveResponse.errorItemMap;
            for( MassiveLoaderRequestItem__c requestItem:saveResponse.reponseItemList){
                //verifico quali activity sono andate ok e le mappo per la successiva elaborazione. Quelle in errore non verranno rielaborate
                if(errorItemMap.containsKey(requestItem.Id)){
                    itemsToSave.add(setErrorItem(requestItem, errorItemMap.get(requestItem.Id)));
                } else {
                    mapRequestItemForUpsertNext.put(requestItem.Id,requestItem);
                }
            }

            for(HDT_WRP_ProcessObjects procObj:processObjList){
                //skip delle richieste andate in errore in precedenza
                if(!mapRequestItemForUpsertNext.containsKey(procObj.requestItem.Id)){
                    continue;
                }

                wrts_prcgvr__Activity__c act=procObj.activity;
                //recupero l'order se associatio e lo mappo
                Id relOrdId;
                if(mapActivityOrderId.containsKey(act.Id)){
                    relOrdid=mapActivityOrderId.get(act.Id);
                    if(errorForPicklistValue('Order', 'Phase__c', procObj.fase)){
                        itemsToSave.add(setErrorItem(procObj.requestItem, 'Valore fase Order non corretto: ' + procObj.fase));
                        continue;
                    }
                    Order refOrder=new Order(Id=relOrdid,Phase__c=procObj.fase);
                    orderToSave.add(refOrder);
                    requestItemForUpsertOrd.add(procObj.requestItem);
                    System.debug(LoggingLevel.DEBUG, '>>> requestItemForUpsertOrd' + requestItemForUpsertOrd);
                }
                
                //recupero il case se associato e lo mappo
                Id relCaseId;
                if(mapActivityCaseId.containsKey(act.Id)){
                    relCaseId=mapActivityCaseId.get(act.Id);
                    if(errorForPicklistValue('Case', 'Phase__c', procObj.fase)){
                        itemsToSave.add(setErrorItem(procObj.requestItem, 'Valore fase Case non corretto: ' + procObj.fase));
                        continue;
                    }
                    Case refCase=new Case(Id=relCaseId  ,Phase__c=procObj.fase);
                    caseToSave.add(refCase);
                    requestItemForUpsertCase.add(procObj.requestItem);
                    System.debug(LoggingLevel.DEBUG, '>>> requestItemForUpsertCase' + requestItemForUpsertCase);
                }
                
            }
            System.debug(LoggingLevel.DEBUG, '>>> itemsToSave' + itemsToSave);
            //aggiorno gli order
            if(!orderToSave.isEmpty()){
                HDT_WRP_SaveResponse saveResponseOrd;
                saveResponseOrd = databaseUpsert(orderToSave, requestItemForUpsertOrd, 'Order');
                orderToSave.clear();
                getLimitDetails('AFTER Order UPDATE');
                System.debug(LoggingLevel.DEBUG, '>>> saveResponseOrd.reponseItemList' + saveResponseOrd.reponseItemList);
                if(saveResponseOrd.reponseItemList.size() > 0){
                    itemsToSave.addAll(saveResponseOrd.reponseItemList);
                }
                System.debug(LoggingLevel.DEBUG, '>>> itemsToSave - Ord' + itemsToSave);

            }
            //aggiorno i case
            if(!caseToSave.isEmpty()){
                HDT_WRP_SaveResponse saveResponseCase;
                saveResponseCase = databaseUpsert(caseToSave, requestItemForUpsertCase, 'Case');
                caseToSave.clear();
                getLimitDetails('AFTER Case UPDATE');
                System.debug(LoggingLevel.DEBUG, '>>> saveResponseCase.reponseItemList' + saveResponseCase.reponseItemList);
                if(saveResponseCase.reponseItemList.size() > 0){
                    itemsToSave.addAll(saveResponseCase.reponseItemList);
                }
                System.debug(LoggingLevel.DEBUG, '>>> itemsToSave - Case' + itemsToSave);

            }
            System.debug(LoggingLevel.DEBUG, '>>> itemsToSave - Final' + itemsToSave);

        }


    }

    public override void finalUpdate(){
        System.debug(LoggingLevel.DEBUG, 'finalUpdate');

        if(itemsToSave.size() > 0){
            update itemsToSave;
        }

    }

    private void mapFieldsObject(){
        //esegue il caricamento dei valori in mappa
        List<HDT_MassiveFieldsObjectMap__mdt> listActivityFields;
        List<HDT_MassiveFieldsObjectMap__mdt> listWrapperActivityFields;

        mapActivityFields = new Map<String, String>();
        mapWrapperActivityFields = new Map<String, String>();

        listActivityFields = getMapFieldsObject('wrts_prcgvr__Activity__c', this.processName);
        listWrapperActivityFields = getMapFieldsObject('WrapperActivity', this.processName);
        System.debug(LoggingLevel.DEBUG, '>>> listActivityFields' + listActivityFields);
        System.debug(LoggingLevel.DEBUG, '>>> mapWrapperActivityFields' + listWrapperActivityFields);

        for(HDT_MassiveFieldsObjectMap__mdt temp : listActivityFields){
            mapActivityFields.put(temp.labelField__c, temp.nameField__c);
        }

        for(HDT_MassiveFieldsObjectMap__mdt temp : listWrapperActivityFields){
            mapWrapperActivityFields.put(temp.labelField__c, temp.nameField__c);
        }

    }


    private class HDT_WRP_ProcessObjects {
        private Case refCase;
        private Order refOrder;
        private String fase;
        private wrts_prcgvr__Activity__c activity;
        private MassiveLoaderRequestItem__c requestItem;
        private List<String> csvSplitted;
    }
}