force-app/main/default/objects/Case/fields/DeclarationDate__c.field-meta.xml
<CustomField>
    <fullName>DeclarationDate__c</fullName>
    <label>Data Dichiarazione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <description>Data Decorrenza</description>
    <label>Data Decorrenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CityTechnicalData__c/CityTechnicalData__c.object-meta.xml
<CustomObject>
    <label>Dato Tecnico Comunale</label>
    <nameField>
        <displayFormat>DTC - {000000}</displayFormat>
        <label>Numero Dato Tecnico Comunale</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dati Tecnici Comunali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CityTechnicalData__c/fields/CityNotManagedAlert__c.field-meta.xml
<CustomField>
    <fullName>CityNotManagedAlert__c</fullName>
    <label>Alert comune non gestito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CityTechnicalData__c/fields/CutOverEndDate__c.field-meta.xml
<CustomField>
    <fullName>CutOverEndDate__c</fullName>
    <label>Data fine cut-over</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CityTechnicalData__c/fields/TARIManagingEndDate__c.field-meta.xml
<CustomField>
    <fullName>TARIManagingEndDate__c</fullName>
    <label>Data fine gestione TARI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CityTechnicalData__c/fields/TARIManagingStartDate__c.field-meta.xml
<CustomField>
    <fullName>TARIManagingStartDate__c</fullName>
    <label>Data inizio gestione TARI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/HDT_UTL_CityDataTariValidation.cls
public inherited sharing class HDT_UTL_CityDataTariValidation implements HDT_UTL_CaseValidationInterface{

    HDT_QR_CaseValidations caseValidationQr = new HDT_QR_CaseValidations();
    Map<String, Object> fieldsMap=null;

    public String validate(String fields, String recordId){
        Case currentCase = caseValidationQr.getCaseById(recordId);
        System.debug(LoggingLevel.DEBUG,'HDT_UTL_CaseValidations: validating Case ' + currentCase);        
        List<CityTechnicalData__c> cityData = HDT_LC_ActiveRepentant.getCityTecData(currentCase.SupplyCity__c);

        this.fieldsMap = (Map<String, Object>) JSON.deserializeUntyped(fields);
        String result;

        if(!cityData.isEmpty()){
            result=checkDates(cityData[0]);
        }


        if(STRING.isBlank(result))  {result = JSON.serialize(new HDT_UTL_CaseValidationWrapper('OK', 'Success'));}
        return result;
    }

    private String checkDates(CityTechnicalData__c cityData){
        if(cityData.CutOverEndDate__c != null && cityData.CutOverEndDate__c > (Date) this.fieldsMap.get('DeclarationDate__c') ){
            return JSON.serialize(new HDT_UTL_CaseValidationWrapper('Error', 'La data di contatto è successiva a quella di fine cut-over!'));
        }
        if(cityData.TARIManagingStartDate__c != null && cityData.TARIManagingEndDate__c!=null){
            Boolean condition = cityData.TARIManagingStartDate__c > (Date) this.fieldsMap.get('EffectiveDate__c');
            condition|=cityData.TARIManagingEndDate__c < (Date) this.fieldsMap.get('EffectiveDate__c');
            if(condition){
                return JSON.serialize(new HDT_UTL_CaseValidationWrapper('Error', cityData.CityNotManagedAlert__c));
            }
        }
        return null;
    }
}