force-app/main/default/objects/Case/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Acconto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Numero Documento</description>
    <label>Numero Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <description>Data Scadenza</description>
    <label>Data Scadenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/TotalPaidCustomer__c.field-meta.xml
<CustomField>
    <fullName>TotalPaidCustomer__c</fullName>
    <label>Totale Residuo Canone Rai</label>
    <summarizedField>DocumentSelected__c.TvFeeResidual__c</summarizedField>
    <summaryForeignKey>DocumentSelected__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/TotalResidue__c.field-meta.xml
<CustomField>
    <fullName>TotalResidue__c</fullName>
    <label>Totale Residuo</label>
    <summarizedField>DocumentSelected__c.DocumentResidue__c</summarizedField>
    <summaryForeignKey>DocumentSelected__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/TotalToPay__c.field-meta.xml
<CustomField>
    <fullName>TotalToPay__c</fullName>
    <label>Totale da Pagare</label>
    <summarizedField>DocumentSelected__c.Amount__c</summarizedField>
    <summaryForeignKey>DocumentSelected__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/DocumentSelected__c.object-meta.xml
<CustomObject>
    <label>Documento selezionato</label>
    <nameField>
        <label>Nome Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documenti selezionati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentSelected__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Numero Documento</description>
    <label>Numero Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <description>Data Scadenza</description>
    <label>Data Scadenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/Extension__c.field-meta.xml
<CustomField>
    <fullName>Extension__c</fullName>
    <description>Dilazione</description>
    <label>Dilazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <description>Data Emissione</description>
    <label>Data Emissione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/PaidCustomer__c.field-meta.xml
<CustomField>
    <fullName>PaidCustomer__c</fullName>
    <description>Campo che corrisponde all&apos;importo pagato dal cliente</description>
    <label>Pagato Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/fields/TotalCommunicationPayment__c.field-meta.xml
<CustomField>
    <fullName>TotalCommunicationPayment__c</fullName>
    <description>Totale Comunicazione Pagamento</description>
    <label>Totale Comunicazione Pagamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HDT_SRV_PaymentCommunication.cls
public inherited sharing class HDT_SRV_PaymentCommunication {

    HDT_QR_PaymentCommunication paymentQr = new HDT_QR_PaymentCommunication();

    public String createRequestBody(String recordId){

        List<DocumentSelected__c> documents = new List<DocumentSelected__c>();
        Case currentCase = new Case();
        String pretty;

        currentCase = paymentQr.getCaseById(recordId);
        documents = paymentQr.getDocumentSelectedByCase(recordId);

        System.debug('SRV_PaymenCommunication Case--> '+currentCase);
        System.debug('SRV_PaymentCommunication Documetns--> '+documents);

        Map<String, Object> caseMap = new Map<String, Object>{
            'rds' => currentCase.CaseNumber,
            'totale' => currentCase.TotalPaidCustomer__c,
            'residuo' => currentCase.TotalResidue__c,
            'importo' => currentCase.TotalToPay__c,
            'acconto' => currentCase.Deposit__c
        };

        JSONGenerator gen = JSON.createGenerator(true);

        gen.writeStartObject();
        for(String mapKey : caseMap.keySet()){

            if(caseMap.get(mapKey) != null){

                if(caseMap.get(mapKey) instanceof String){

                    gen.writeStringField(mapKey, (String) caseMap.get(mapKey));

                } else if(caseMap.get(mapKey) instanceof Integer){

                    gen.writeNumberField(mapKey, (Integer) caseMap.get(mapKey));

                }else if(caseMap.get(mapKey) instanceof Decimal){

                    gen.writeNumberField(mapKey, (Decimal) caseMap.get(mapKey));

                } else if(caseMap.get(mapKey) instanceof Date){

                    gen.writeDateField(mapKey, (Date) caseMap.get(mapKey));

                } else if(caseMap.get(mapKey) instanceof Boolean){

                    gen.writeBooleanField(mapKey, (Boolean) caseMap.get(mapKey));

                }

            }else{

                gen.writeNullField(mapKey);

            }

        }
        gen.writeFieldName('pagamenti');
        gen.writeStartArray();
        for(DocumentSelected__c document : documents){

            gen.writeStartObject();
            gen.writeStringField('numeroBollettino','');
            gen.writeStringField('numeroFattura',document.DocumentNumber__c.startsWith('0') ? document.DocumentNumber__c : '');
            gen.writeStringField('numeroFattura1','');
            gen.writeStringField('rataFattura','');
            gen.writeDateField('scadenza',document.ExpirationDate__c);
            //gen.writeNumberField('pagato',document.PaidCustomer__c);
            gen.writeStringField('infoBlocco','');
            gen.writeStringField('idProcesso','');
            gen.writeStringField('numeroDocumento',document.DocumentNumber__c.startsWith('0') ? '' : document.DocumentNumber__c);
            //gen.writeStringField('rateizzazione',document.Extension__c);
            gen.writeDateField('dataFattura',document.IssueDate__c);
            gen.writeNumberField('totaleParziale',document.TotalCommunicationPayment__c);
            gen.writeEndObject();
        }
        gen.writeEndArray();
        gen.writeEndObject();
    
        pretty = gen.getAsString();

        System.debug('SRV_PaymentCommunication -->' +pretty);

        return pretty;
    }



}