force-app/main/default/objects/Case/fields/DocusignExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>DocusignExpirationDate__c</fullName>
    <description>Data Scadenza Documento</description>
    <label>Data Scadenza Documento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Modulo Firmato</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>In attesa risposta Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocusignExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>DocusignExpirationDate__c</fullName>
    <description>Data Scadenza Busta Docusign</description>
    <label>Data Scadenza Busta Docusign</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_LC_MailSenderTst.cls
/**
* @author Elvin Iluca
* @date 19/10/2022
* @description Test Class for HDT_LC_MailSender.cls
* @history Elvin Iluca – 19/10/2022 – Created class
*/


@isTest
public with sharing class HDT_LC_MailSenderTst {

    //DATA
	private static HDT_UTL_Constants utlConstants = new HDT_UTL_Constants();

    /**​
    * @author Elvin Iluca
    * @date 19/10/2022
    * @description HDT_LC_MailSenderTst – Test Class for HDT_LC_MailSender.cls
    */
    @TestSetup
	static void setup(){

        HDT_UTL_DataFactoryTst.createEmailMessage(1, true);
        HDT_UTL_DataFactoryTst.createEmailTemplate(1, true);
        HDT_UTL_DataFactoryTst.pClickInstance();
        HDT_UTL_DataFactoryTst.pClickCasePhase();
        
        Id recTypeId = utlConstants.CASE_RECORDTYPEID_MOROSITA;
        String recTypeName = utlConstants.CASE_RECORDTYPE_DEVELOPERNAME_MOROSITA;
        string recTypeInformativeDevName=utlConstants.CASE_RECORDTYPE_DEVELOPERNAME_INFORMATIVE;
        Id informativeRtypeId=utlConstants.CASE_RECORDTYPEID_INFORMATIVE;
        HDT_UTL_DataFactoryTst.newPhaseTransition('Annullato','Bozza', recTypeId, recTypeName);
        HDT_UTL_DataFactoryTst.newPhaseTransition('In attesa risposta Mail','Bozza', recTypeId, recTypeName);
        HDT_UTL_DataFactoryTst.newPhaseTransition('In attesa risposta Mail','Bozza', informativeRtypeId, recTypeInformativeDevName);
        List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<Order> ordList = HDT_UTL_DataFactoryTst.createOrder(1, true, accList[0].id, 'Bozza');
        List<ServicePoint__c> servPointList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        List<Contact> contactList = HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].id);
        List<Contract> contractList = HDT_UTL_DataFactoryTst.createContract(1, true, accList[0].id);
        List<Case> caseList = HDT_UTL_DataFactoryTst.createCase(2, false, accList[0].id, contactList[0].Id, servPointList[0].id, contractList[0].id, ordList[0].id);
        for(Case c : caseList){
            c.DocusignExpirationDate__c = Date.today().addDays(5);
            c.RecordTypeId = recTypeId;
            c.Phase__c = 'Attesa Modulo Firmato';
        }
        
        Case mySingleCase = HDT_UTL_DataFactoryTst.createCase(1, false, accList[0].id, contactList[0].Id, servPointList[0].id, contractList[0].id, ordList[0].id)[0];
        mySingleCase.RecordTypeId = recTypeId;
        mySingleCase.Phase__c = 'Attesa Modulo Firmato';
        caseList.add(mySingleCase);

        HDT_QR_RecordType qrRecordType = new HDT_QR_RecordType();
        Case caseGestore = HDT_UTL_DataFactoryTst.createCase(1, false, accList[0].id, contactList[0].Id, servPointList[0].id, contractList[0].id, ordList[0].id)[0];
        caseGestore.RecordTypeId = qrRecordType.getRecordTypeIdByName('HDT_RT_Informative');
        caseGestore.Type = 'Comunicazione con il Gestore';
        caseGestore.Phase__c = 'In attesa risposta Mail';
        caseList.add(caseGestore);
        
        insert caseList;

        List<ContentVersion> contentVersion = HDT_UTL_DataFactoryTst.createContentVers(1, false);
        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument WHERE LatestPublishedVersionId = :contentVersion[0].Id];

        list<ContentDocumentLink> listDocumentLink = HDT_UTL_DataFactoryTst.createContentDocumentLink(1, false, caseList[0].Id, documents[0].Id);
        insert listDocumentLink;

        List<EmailMessage> listEmailMessage = new List<EmailMessage>();
        Case csGestore = [SELECT Id FROM Case WHERE Type = 'Comunicazione con il Gestore' LIMIT 1];
        List<EmailMessage> msgList = HDT_UTL_DataFactoryTst.createEmailMessage(1, false);
        msgList[0].Subject = 'Comunicazione dal gestore';
        msgList[0].RelatedToId = csGestore.Id;
        listEmailMessage.add(msgList[0]);
        insert listEmailMessage;

    }

    /**​
    * @author Elvin Iluca
    * @date 19/10/2022
    * @description HDT_LC_MailSenderTst – Test Class for HDT_LC_MailSender.cls
    */
    @isTest
    static void getMetadataTst () {
        HDT_WRP_MailSender.HDT_WRP_Result ret ;
        EmailMessage emailMessage =  [SELECT Id FROM EmailMessage LIMIT 1];

        Test.startTest();
        ret = HDT_LC_MailSender.getMetadata(emailMessage.Id);
        Test.stopTest();
        System.assertEquals(true, ret.success, 'can\'t find the EmailTemplate in the folder');
        
    }

    /**​
    * @author Elvin Iluca
    * @date 19/10/2022
    * @description HDT_LC_MailSenderTst – Test Class for HDT_LC_MailSender.cls
    */
    @isTest
    static void getBodyMailMergedTst(){
        HDT_WRP_MailSender.HDT_WRP_BodyMail ret;
        EmailMessage emailMessage =  [SELECT Id FROM EmailMessage LIMIT 1];
        EmailTemplate emailTemplate =  [SELECT Id, Name FROM EmailTemplate LIMIT 1];

        Test.startTest();
        ret = HDT_LC_MailSender.getBodyMailMerged(emailTemplate.Name, emailTemplate.Id, emailMessage.Id);
        Test.stopTest();
        System.assertEquals(true, ret.success, 'body mail was succsesfully merged');
    }

    /**​
    * @author Elvin Iluca
    * @date 19/10/2022
    * @description HDT_LC_MailSenderTst – Test Class for HDT_LC_MailSender.cls
    */
    @isTest
    static void sendMailTst(){
        HDT_WRP_MailSender.HDT_WRP_SendMailResult ret;
        //In the org there must be at least one record of OrgWideEmailAddress
        List<OrgWideEmailAddress> orgWideEmailAdress = [SELECT Id, Address FROM OrgWideEmailAddress];
        List<Case> cases =  [SELECT Id FROM Case LIMIT 1];
        String orgWideAddId = orgWideEmailAdress[0].Id;
        String toAddress = orgWideEmailAdress[0].Address;
        String caseId= cases[0].Id;
        String emailMessageJson = '{"recordId": "'+ caseId +'", "isReminder": false,"orgWideAddId": "'+ orgWideAddId +'", "bodyMail": "Note 2", "toAddress": "'+ toAddress +'"}';

        Test.startTest();
        ret = HDT_LC_MailSender.sendMail(emailMessageJson);
        Test.stopTest();
        System.assertEquals(true, ret.success, ret.message);
    }

    @IsTest
    static void getContentDocsTst(){

        List<Case> cases =  [SELECT Id FROM Case LIMIT 1];
        Test.startTest();
        List<ContentDocument> cdList = HDT_LC_MailSender.getContentDocs(cases[0].Id);
        Test.stopTest();
        System.assert(cdList.size() > 0, 'Errore in fase di retrieve dei documenti caricati.');
        
    }

    @IsTest
    static void deletePendingFilesTst(){
        List<Case> cases =  [SELECT Id FROM Case LIMIT 1];
        List<Id> cdIdList = new List<Id>();
        Test.startTest();
            List<ContentDocument> cdList = HDT_LC_MailSender.getContentDocs(cases[0].Id);
            cdIdList.add(cdList[0].Id); 
            HDT_UTL_MailSenderHelper.deletePendingFiles(cdIdList);
        Test.stopTest();
        
        List<ContentDocument> cdListAfter = [SELECT Id FROM ContentDocument LIMIT 1];
        System.assert(cdListAfter.size() == 0, 'Errore in fase di eliminazione dei documenti.');
    }

    @IsTest
    static void getContentSizeAttachmentsTst(){
        List<Case> cases =  [SELECT Id FROM Case LIMIT 1];
        Test.startTest();
            List<ContentDocument> cdList = HDT_LC_MailSender.getContentDocs(cases[0].Id);
            List<Id> cdIdList = new List<Id>();
            cdIdList.add(cdList[0].Id);
            Decimal attachmentsSize = HDT_UTL_MailSenderHelper.getContentSizeAttachments(cdIdList);
        Test.stopTest();
        
        System.assert(attachmentsSize != null, 'Errore in fase di retrieve della dimensione dei documenti.');
    }

    @IsTest
    static void getMetadataForReminderTst(){
        HDT_WRP_MailSender.HDT_WRP_Result ret ;
        List<Case> cases =  [SELECT Id FROM Case WHERE Type = 'Comunicazione con il Gestore' LIMIT 1];
        Test.startTest();
            ret = HDT_LC_MailSender.getMetadata(cases[0].Id);
        Test.stopTest();
        
        System.assert(ret != null, 'Errore in fase di retrieve della dimensione dei documenti.');
    }
}