force-app/main/default/objects/Case/fields/HerokuPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>HerokuPracticeCode__c</fullName>
    <description>Codice pratica restituito da Heroku al CRM.</description>
    <label>Codice Pratica Heroku</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DiscardReason__c.field-meta.xml
<CustomField>
    <fullName>DiscardReason__c</fullName>
    <label>Causale Ultimo Scarto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/HerokuPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>HerokuPracticeCode__c</fullName>
    <label>Codice Pratica Heroku</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Ordine di riferimento)</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__CalloutTemplate__c/wrts_prcgvr__CalloutTemplate__c.object-meta.xml
<CustomObject>
    <description>Available selective callout templates</description>
    <label>Callout Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callout Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Log__c/wrts_prcgvr__Log__c.object-meta.xml
<CustomObject>
    <description>Enables ProcessClick internal logging system</description>
    <label>Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_SRV_BillableVasDeactivation.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global inherited sharing class HDT_SRV_BillableVasDeactivation implements wrts_prcgvr.Interfaces_1_0.IApexCalloutAction {

    
    private static HDT_QR_HerokuPostSalesManager hpsmQr = new HDT_QR_HerokuPostSalesManager();
    private static HDT_UTL_HerokuPostSalesManager hpsmUtl = new HDT_UTL_HerokuPostSalesManager();

    private final static String PHASE_OK = 'Comunicazione verso Heroku OK';
    private final static String PHASE_KO = 'Comunicazione verso Heroku KO';

    private Map<String,String> mapRequestFields = new Map<String,String>();
    
    global HDT_SRV_BillableVasDeactivation(){
        return;
    }

    /*public HDT_SRV_BillableVasDeactivation(HDT_WRP_MrrRequest.HDT_WRP_Request request){
        if (request?.objects?.size()> 0 && request?.objects?.get(0)?.fields?.size() > 0) {
            for(HDT_WRP_MrrRequest.HDT_WRP_Field field : request.objects.get(0).fields){
                if(this.mapRequestFields.get(field.name) == null){
                    this.mapRequestFields.put(field.name,field.value);
                }
            }
        }
    }*/

    public static void handlerAsyncronousNotify(HDT_WRP_MrrRequest.HDT_WRP_Request request){
        HDT_WRP_MrrRequest.HDT_WRP_Field fieldId;
        if (request?.objects?.size()> 0 && request?.objects?.get(0)?.fields?.size() > 0) {
            for(HDT_WRP_MrrRequest.HDT_WRP_Field field : request.objects.get(0).fields){
                if(field.name == 'RECORD_ID'){
                    fieldId=field;
                }
            }
        }
        List<Case> cases;
        if(STRING.isNotBlank(fieldId?.value) && fieldId.value.startsWithIgnoreCase('O-')){
            cases = [SELECT Id FROM Case
                        WHERE RecordType.DeveloperName='HDT_RT_PostSalesVAS' AND Type='Disattivazione VAS'
                        AND (Asset.SBQQ__OrderProduct__r.Order.OrderNumber=:fieldId.value OR Subscription__r.SBQQ__Contract__r.SBQQ__Order__r.OrderNumber=:fieldId.value) AND Status NOT IN ('Closed', 'Bozza')
                        WITH SECURITY_ENFORCED LIMIT 1];
        }
        if(cases?.size()>0){
            fieldId.value=cases[0].Id;
        }
    }
    

    
    public static wrts_prcgvr__Log__c createLogObj(wrts_prcgvr.MRR_1_0.MultiRequest multirequestObj, wrts_prcgvr.MRR_1_0.MultiResponse responseService, Map<String, Object> argsMap) {
        String method = (String) argsMap.get('method');
        wrts_prcgvr__Log__c calloutLog = new wrts_prcgvr__Log__c();
        calloutLog.wrts_prcgvr__Code__c = String.valueof(
            system.now().format('yyyyMMddHHmmssSSS')
        );
        calloutLog.wrts_prcgvr__Message__c = 'PClick CALLOUT-' + method;
        calloutLog.wrts_prcgvr__Description__c =
            'request: \n' +
            wrts_prcgvr.MRR_1_0.serializeMultiRequest(
                new Map<String, Object>{
                    'object' => multirequestObj,
                    'format' => 'JSON'
                }
            ) +
            '\n\n\n\nresponse:\n' +
            wrts_prcgvr.MRR_1_0.serializeMultiResponse(
                new Map<String, Object>{
                    'object' => responseService,
                    'format' => 'JSON'
                }
            );
        return calloutLog; //those debug logs must violate crud permission, those are registered for admins only
    }

    global Object execute(Object args) {
        wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse response = new wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse();
        wrts_prcgvr.MRR_1_0.MultiResponse responseMrr = new wrts_prcgvr.MRR_1_0.MultiResponse();
        wrts_prcgvr__CalloutTemplate__c record = new wrts_prcgvr__CalloutTemplate__c();
        Map<String, Object> arg = new Map<String, Object>();
        //List<Case> caseToUpdate = new List<Case>();
        Case currentCase = new Case();
        String ticket;
        String code;
        Case caseToUpdate;

        //fake code

        //Deprecato
        // HDT_WRP_HerokuPostSalesProva.HDT_WRP_MultiResponse mrrResponse = new HDT_WRP_HerokuPostSalesProva.HDT_WRP_MultiResponse();

        //fake code

        List<HDT_WRP_HerokuPostSalesManager> wrpResponses = new List<HDT_WRP_HerokuPostSalesManager>();
        //String outputResult;

        Map<String, Object> argsMap = (Map<String, Object>) args;
        //SObject transition = (SObject) argsMap.get('transition'); //phase transition
        //SObject action = (SObject) argsMap.get('action'); //phase transition detail
        //String method = (String) argsMap.get('method');
        SObject obj = (SObject) argsMap.get('sender');
        //Object templateMap = argsMap.get('templateMap');
        Map<String, String> parameters = (Map<String, String>) argsMap.get(
            'parameters'
        );

        try {
            ticket = (String) obj.get('Id');
            currentCase = (Case) obj;
            caseToUpdate = new Case(Id=currentCase.Id);
            code = hpsmUtl.getCodeFromPhaseTransition(currentCase);
            record = hpsmQr.getCalloutTemplateByCode(code);

            wrts_prcgvr.Interfaces_1_0.IEndpointRulesIntegration endpointUtils = (wrts_prcgvr.Interfaces_1_0.IEndpointRulesIntegration) wrts_prcgvr.VersionManager.newClassInstance(
                'EndpointRulesIntegration'
            );

            String endpoint = endpointUtils.getEndpoint(
                new Map<String, Object>{ 'Case' => currentCase }
            );
            System.debug(
                'endpoint ' +
                endpointUtils.getEndpoint(
                    new Map<String, Object>{ 'Case' => currentCase }
                )
            );

            argsMap.put('template', record);
            wrts_prcgvr.Interfaces_1_0.ICalloutTemplateMng templateEngine = (wrts_prcgvr.Interfaces_1_0.ICalloutTemplateMng) wrts_prcgvr.VersionManager.newClassInstance(
                'CalloutTemplateMng'
            );

            argsMap = (Map<String, Object>) templateEngine.getTemplate(argsMap);
            argsMap = (Map<String, Object>) templateEngine.applyTemplate(
                argsMap
            );
            System.debug('parameters ' + parameters);
            System.debug('argsMap ' + argsMap);

            wrts_prcgvr.MRR_1_0.MultiRequest mrrList = (wrts_prcgvr.MRR_1_0.MultiRequest) argsMap.get(
                'multirequest'
            );

            arg.put('endpoint', endpoint);
            arg.put('timeout', 12000);
            arg.put('payload', mrrList);
            arg.put('clientType', 'REST');
            arg.put('contentType', 'application/json');

            System.debug('mrrList--> ' + mrrList);

            wrts_prcgvr.Interfaces_1_0.ICalloutClient client = (wrts_prcgvr.Interfaces_1_0.ICalloutClient) wrts_prcgvr.VersionManager.newClassInstance(
                'CalloutClient'
            );
            responseMrr = (wrts_prcgvr.MRR_1_0.MultiResponse) client.send(arg);
            /*HttpRequest req = new HttpRequest();
         req.setEndpoint(endpoint);
         req.setMethod('POST');
         req.setBody(wrts_prcgvr.MRR_1_0.serializeMultiRequest(mrrList));
         Http http = new Http();
         HTTPResponse res = http.send(req);
 
         System.debug('Body --> '+res.getBody());
         System.debug(res.getStatusCode());
         System.debug(res.getStatus());*/

            insert createLogObj(mrrList, responseMrr, argsMap);
        } catch (Exception ex) {
            //Error Handling
            System.debug(ex.getMessage());
        }

        System.debug('ResponseMrr --> ' + responseMrr);

        //wrpResponses = hpsmUtl.manipulateResponse(responseMrr);

        System.debug('WRPResponse --> ' + wrpResponses);
        //caseToUpdate = hpsmUtl.handleResponse(wrpResponses, currentCase);

        if (responseMrr.responses[0].objects == null) {
            // ord.DiscardReason__c = responseService.responses[0].description;
            //ord.Phase__c = 'Comunicazione verso Heroku KO';
            caseToUpdate.Phase__c=PHASE_KO;
        }else{
            map<String,String> fieldValueResponse = new map<String,String>();
            wrts_prcgvr.MRR_1_0.WObject objResponse = responseMrr.responses[0].objects[0];
            for(wrts_prcgvr.MRR_1_0.field field : objResponse.fields){
                fieldValueResponse.put(field.name,field.value);
            }
            if(String.isNotBlank(fieldValueResponse.get('COD_PRAT_UTENTE'))){
                caseToUpdate.HerokuPracticeCode__c = fieldValueResponse.get('COD_PRAT_UTENTE');
            }else if(String.isNotBlank(responseMrr.responses[0].header.requestId)){
                caseToUpdate.HerokuPracticeCode__c = responseMrr.responses[0].header.requestId;
            }
            caseToUpdate.Phase__c = 'OK'.equalsIgnoreCase(fieldValueResponse.get('result'))? PHASE_OK : PHASE_KO;
        }

        system.debug(caseToUpdate);
        if(!Test.isRunningTest()){
            system.enqueueJob(new HDT_QBL_UpdateQueueable(caseToUpdate));
        }

        response.success = true;
        response.message = 'OK';
        return response;
    }

    public class HDT_QBL_UpdateQueueable implements Queueable {
        private Case caseToUpdate;
        public HDT_QBL_UpdateQueueable(){
            return;
        }
        public HDT_QBL_UpdateQueueable(Case c){
            this.caseToUpdate = c;
        }
        public void execute(QueueableContext context){
            HDT_UTL_DatabaseService.updateSObject(caseToUpdate);
        }
    }

    /*@Future
    private static void updateFuture(String inputString){
        system.debug('ivaste updatefuture');
        Case c = (Case) JSON.deserialize(inputString, Case.class);
        HDT_UTL_DatabaseService.updateSObject(c);
    }

    public Boolean isPostSalesOrder(){
        return this.mapRequestFields.get('RECORD_ID').startsWithIgnoreCase('O-');
    }*/
    
}