force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/TotalResidue__c.field-meta.xml
<CustomField>
    <fullName>TotalResidue__c</fullName>
    <label>Totale Residuo</label>
    <summarizedField>DocumentSelected__c.DocumentResidue__c</summarizedField>
    <summaryForeignKey>DocumentSelected__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OrderID</description>
    <label>Order Correlato</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>POD/PDR</description>
    <label>POD/PDR</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo attività</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Anticipo Appuntamento</fullName>
            </value>
            <value>
                <fullName>Approvazione Bonus Commerciale</fullName>
            </value>
            <value>
                <fullName>Approvazione Offerte</fullName>
            </value>
            <value>
                <fullName>Assistenza Contact Center</fullName>
            </value>
            <value>
                <fullName>Attesa Preventivo DL</fullName>
            </value>
            <value>
                <fullName>Attivazioni</fullName>
            </value>
            <value>
                <fullName>Back Office - Catalogo Prodotti</fullName>
            </value>
            <value>
                <fullName>Back Office - Contratti</fullName>
            </value>
            <value>
                <fullName>Back Office - Fatturazione</fullName>
            </value>
            <value>
                <fullName>Back Office - Morosità</fullName>
            </value>
            <value>
                <fullName>Back Office - Pagamenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Preventivi</fullName>
            </value>
            <value>
                <fullName>Back Office - Supporto/Comunicazioni Urgenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Tari/TCP</fullName>
            </value>
            <value>
                <fullName>Back Office - Vas e HVAC</fullName>
            </value>
            <value>
                <fullName>Busta Docusign non consegnata</fullName>
            </value>
            <value>
                <fullName>Caricamenti contratti</fullName>
            </value>
            <value>
                <fullName>Caricamento Manuale Siebel</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Chiamata Callback</fullName>
            </value>
            <value>
                <fullName>Chiamata inbound</fullName>
            </value>
            <value>
                <fullName>Chiamata outbound</fullName>
            </value>
            <value>
                <fullName>Comfort Call</fullName>
            </value>
            <value>
                <fullName>Comunicazione da DL</fullName>
            </value>
            <value>
                <fullName>Comunicazioni con DL</fullName>
            </value>
            <value>
                <fullName>Conferma Preventivo</fullName>
            </value>
            <value>
                <fullName>Pratica non gestita per il DL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/wrts_prcgvr__IsClosed__c.field-meta.xml
<CustomField>
    <fullName>wrts_prcgvr__IsClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HDT_UTL_PostSalesCriteriaManagerTst.cls
/*
    @Author:        Francesco Vitiello
    CreatedDate:    29/09/2021
*/

@isTest
public with sharing class HDT_UTL_PostSalesCriteriaManagerTst {

    
    //DEBUG
    public static final String TEST_NAME = 'HDT_UTL_PostSalesCriteriaManagerTst';
    
    
    //TEST SETUP
    
    @TestSetup
    static void makeData(){
        HDT_UTL_DataFactoryTst.pClickCasePhase();
        HDT_UTL_DataFactoryTst.pClickOrderPhase();
        List<Account> residentialAccounts=HDT_UTL_DataFactoryTst.createAccountResidenziale(1, true, 'HERA COMM', 'D1 - Persona fisica', 'Enti');
        List<Contact> residentialContacts=HDT_UTL_DataFactoryTst.createContact(1, true, residentialAccounts[0].Id);
        List<ServicePoint__c> servicePoits=HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        List<Contract> contracts=HDT_UTL_DataFactoryTst.createContract(1, true, residentialAccounts[0].Id);
        List<Order> orders=HDT_UTL_DataFactoryTst.createOrder(1, true, residentialAccounts[0].Id, 'Bozza');
        List<Case> cases=HDT_UTL_DataFactoryTst.createCaseDocumentale(2, true, residentialAccounts[0].Id, residentialContacts[0].Id, servicePoits[0].Id, contracts[0].Id, orders[0].Id);
        HDT_UTL_DataFactoryTst.createDocumentSelected(1,true, false, cases[0].Id, 'TEST001HDT');
        HDT_UTL_DataFactoryTst.createActivityWithParams(1, true, residentialAccounts[0].Id,new Map<String,Object>{
            'Order__c'=>orders[0].Id,'Type__c'=>'Valori non corrispondenti','wrts_prcgvr__IsClosed__c'=>false
        });
        HDT_UTL_DataFactoryTst.createActivityWithParams(1, true, residentialAccounts[0].Id,new Map<String,Object>{
            'Order__c'=>orders[0].Id,'Type__c'=>'Dati tecnici ricevuti_ Extra-sistema','wrts_prcgvr__IsClosed__c'=>false
        });
        HDT_UTL_DataFactoryTst.createActivityWithParams(1, true, residentialAccounts[0].Id,new Map<String,Object>{
            'Case__c'=>cases[0].Id,'Type__c'=>'Gestione Back Office','wrts_prcgvr__IsClosed__c'=>true
        });
        
        
    }
    
    //TESTS

    @isTest
    private static void distributorManagementTest(){
        
        //DEBUG
        String debugString = TEST_NAME + ' - ' + 'distributorManagementTest';
        System.debug(debugString);
        
        //SETUP
        
        String phaseStory = 'Pratica non gestita per il DL';

        //TESTING
        Test.startTest();
        Try{
            HDT_UTL_PostSalesCriteriaManager myClass = new HDT_UTL_PostSalesCriteriaManager();            
            myClass.distributorManagement(phaseStory);
            
        }catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }        
        Test.stopTest();
        
        //ASSERTS
        System.assert(phaseStory != null, 'Attenzione, phaseStory non può essere null!');
        
    }

    @isTest
    private static void secondAdmissibilityTest(){
        
        //DEBUG
        String debugString = TEST_NAME + ' - ' + 'secondAdmissibilityTest';
        System.debug(debugString);
        
        //SETUP
        
        String phaseStory = 'Preventivo Accettato';

        //TESTING
        Test.startTest();
        Try{
            
            HDT_UTL_PostSalesCriteriaManager myClass = new HDT_UTL_PostSalesCriteriaManager();            
            myClass.secondAdmissibility(phaseStory);
            
        }catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }        
        Test.stopTest();
        
        //ASSERTS
        System.assert(phaseStory != null, 'Attenzione, phaseStory non può essere null!');
        
    }

    @isTest
    private static void notExecWorksTest(){
        
        //DEBUG
        String debugString = TEST_NAME + ' - ' + 'notExecWorksTest';
        System.debug(debugString);
        
        //SETUP
        
        String phaseStory = 'Dati Tecnici Ricevuti';

        //TESTING
        Test.startTest();
        Try{
            
            HDT_UTL_PostSalesCriteriaManager myClass = new HDT_UTL_PostSalesCriteriaManager();            
            myClass.notExecWorks(phaseStory);
            
        }catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }        
        Test.stopTest();
        
        //ASSERTS
        System.assert(phaseStory != null, 'Attenzione, phaseStory non può essere null!');
        
    }

    /**
    * @author Cristiano Salvati (c.salvaty@key2.it)
    * @date 25/10/2022
    * @description HDT_UTL_PostSalesCriteriaManagerTst – totalResidueNotNull test method
    */

    @isTest
    static void totalResidueNotNullTst(){
        Boolean result=false;
        List<SObject> senders=[SELECT Id,TotalResidue__c FROM Case WHERE TotalResidue__c >0.00 WITH SECURITY_ENFORCED LIMIT 1];
        Test.startTest();
        result=new HDT_UTL_PostSalesCriteriaManager().totalResidueNotNull(senders[0]);
        Test.stopTest();
        System.assertEquals(true, result, 'total residue is not null');
    }

    /**
    * @author Cristiano Salvati (c.salvaty@key2.it)
    * @date 25/10/2022
    * @description HDT_UTL_PostSalesCriteriaManagerTst – totalResidueNull test method
    */

    @isTest
    static void totalResidueNullTst(){
        Boolean result=false;
        List<SObject> senders=[SELECT Id,TotalResidue__c FROM Case WHERE TotalResidue__c=0.00 WITH SECURITY_ENFORCED LIMIT 1];
        Test.startTest();
        result=new HDT_UTL_PostSalesCriteriaManager().totalResidueNull(senders[0]);
        Test.stopTest();
        System.assertEquals(true, result, 'total residue is null');
    }

    /**
    * @author Cristiano Salvati (c.salvaty@key2.it)
    * @date 25/10/2022
    * @description HDT_UTL_PostSalesCriteriaManagerTst – areActivityOpen test method
    */

    @isTest
    static void areActivityOpenTst(){
        List<Order> orders=[SELECT Id FROM Order WITH SECURITY_ENFORCED LIMIT 1];
        Boolean result=true;
        Test.startTest();
        result=new HDT_UTL_PostSalesCriteriaManager().areActivityOpen(orders[0].Id);
        Test.stopTest();
        System.assertEquals(false, result,'Activity list is not empty');
    }

    @isTest
    static void activityLetturaNonInseritaInSapPresenteTst(){
        List<Case> cases=[SELECT Id,TotalResidue__c FROM Case WHERE TotalResidue__c >0.00 WITH SECURITY_ENFORCED LIMIT 1];
        Boolean result=true;
        Test.startTest();
        result=new HDT_UTL_PostSalesCriteriaManager().activityLetturaNonInseritaInSapPresente(cases[0].Id);
        Test.stopTest();
        System.assertEquals(true, result,'Activity list is not empty');
    }

    @isTest
    static void activityLetturaNonInseritaInSapAssentiTst(){
        List<Case> cases=[SELECT Id,TotalResidue__c FROM Case WHERE TotalResidue__c >0.00 WITH SECURITY_ENFORCED LIMIT 1];
        Boolean result=false;
        Test.startTest();
        result=new HDT_UTL_PostSalesCriteriaManager().activityLetturaNonInseritaInSapAssenti(cases[0].Id);
        Test.stopTest();
        System.assertEquals(false, result,'Activity list is not empty');
    }

    @isTest
    static void isRapidoToAnaliticoTst(){
        List<wrts_prcgvr__Activity__c> activities=[SELECT Id,Order__c FROM wrts_prcgvr__Activity__c WHERE Type__c='Dati tecnici ricevuti_ Extra-sistema' WITH SECURITY_ENFORCED LIMIT 1];
        Boolean result=false;
        Test.startTest();
        result=new HDT_UTL_PostSalesCriteriaManager().isRapidoToAnalitico(activities[0].Order__c);
        Test.stopTest();
        System.assertEquals(true, result, 'Activity list not empty');

    }

    


}