force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HDT_LocalDispatcherInrete__mdt/HDT_LocalDispatcherInrete__mdt.object-meta.xml
<CustomObject>
    <label>Local Dispatcher InRete</label>
    <pluralLabel>Local Dispatcher InRete</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_LocalDispatcherInrete__mdt/fields/DispatcherDesc__c.field-meta.xml
<CustomField>
    <fullName>DispatcherDesc__c</fullName>
    <label>DispatcherDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__ActivityTemplate__c/wrts_prcgvr__ActivityTemplate__c.object-meta.xml
<CustomObject>
    <description>Defines instantiated Activity behaviors, initial data and appereance</description>
    <label>Activity Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_QR_PostSalesManager.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public inherited sharing class HDT_QR_PostSalesManager {

    public Integer checkLocalDispatcher(String dispatcherName){

        return [SELECT COUNT() 
        FROM HDT_LocalDispatcherInrete__mdt 
        WHERE DispatcherDesc__c = :dispatcherName
        WITH SECURITY_ENFORCED]; 

    }


    public wrts_prcgvr__ActivityTemplate__c getActivityTemplate(String template){

        return [SELECT Id,
        wrts_prcgvr__Assignees__c,
        wrts_prcgvr__Subject__c,
        wrts_prcgvr__DueDateField__c
        FROM wrts_prcgvr__ActivityTemplate__c
        WHERE Name = :template
        WITH SECURITY_ENFORCED
        LIMIT 1];

    }

    public Case getCaseByServicePoint(String type, String servicePoint){
        Case c = new Case();
        try{
           c = [SELECT Id,
            Phase__c
            FROM Case
            WHERE ServicePoint__c = :servicePoint
            AND Type = :type
            AND Status != 'Closed'
            WITH SECURITY_ENFORCED
            LIMIT 1];
        } catch(Exception e){
            System.debug(LoggingLevel.DEBUG, 'HDT_QR_PostSalesManage Exception -> ' + e.getMessage());
        }
        return c;
    }

}