force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Esito OK da SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_PEV_SelfReading__e/HDT_PEV_SelfReading__e.object-meta.xml
<CustomObject>
    <label>Autolettura</label>
    <pluralLabel>Autoletture</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_PEV_SelfReading__e/fields/SerializedCases__c.field-meta.xml
<CustomField>
    <fullName>SerializedCases__c</fullName>
    <label>Serialized Cases</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <formula>IF(NOT(ISNULL(Case__c)), TEXT(Case__r.Phase__c), IF(NOT(ISNULL(Order__c)), TEXT(Order__r.Phase__c), &quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QBL_SelfReadingsOutcome.cls
public inherited sharing class HDT_QBL_SelfReadingsOutcome implements Queueable, Database.AllowsCallouts {
    
    private List<Case> casesToUpdate;
    private List<wrts_prcgvr__Activity__c> activitiesToCreate;
    private Map<Id,Boolean> isAutomaticDiscardMap;

    private static Integer maxCases = 500;
    private static Integer maxActivities = 500;
    private static Integer maxQueueableJobs = 50; // equivalente a Limits.getLimitQueueableJobs() da contesto sync. 


    public HDT_QBL_SelfReadingsOutcome(List<Case> casesToUpdate, List<wrts_prcgvr__Activity__c> activitiesToCreate, Map<Id,Boolean> isAutomaticDiscardMap) {
        this.casesToUpdate = casesToUpdate != null ? casesToUpdate : new List<Case>();
        this.activitiesToCreate = activitiesToCreate != null ? activitiesToCreate : new List<wrts_prcgvr__Activity__c>();
        this.isAutomaticDiscardMap = isAutomaticDiscardMap;
    }

    /*
    * @Author: Salvatore A. Sarà 20/10/2021
    * Risoluzione "Avoid debug statements since they impact on performance"
    */
    @SuppressWarnings('PMD.AvoidDebugStatements')
    public void execute(QueueableContext context) {
        System.debug(LoggingLevel.DEBUG, '# cases in input: ' + this.casesToUpdate.size());
        System.debug(LoggingLevel.DEBUG,'# activities in input: ' + this.activitiesToCreate.size());

        if (this.casesToUpdate.isEmpty() && this.activitiesToCreate.isEmpty()) {
            System.debug(LoggingLevel.DEBUG, 'Nothing to do.');
            return;
        }

        List<Case> casesToProcess = new List<Case>();
        List<Case> casesForHeroku = new List<Case>();
        List<Case> casesToDelegate = new List<Case>();
        List<wrts_prcgvr__Activity__c> activitiesToProcess = new List<wrts_prcgvr__Activity__c>();
        List<wrts_prcgvr__Activity__c> activitiesToDelegate = new List<wrts_prcgvr__Activity__c>();

        for (Integer i = 0; i < this.casesToUpdate.size(); i++) {
            Case c = this.casesToUpdate[i];
            if (i < maxCases) {
                if (c.Phase__c == 'Esito OK da SAP') {
                    if (casesForHeroku.size() < maxQueueableJobs - 1) {
                        casesForHeroku.add(c);
                    } else {
                        casesToDelegate.add(c);
                    }
                } else {
                    casesToProcess.add(c);
                }
            } else {
                casesToDelegate.add(c);
            }
        }

        for (Integer i = 0; i < this.activitiesToCreate.size(); i++) {
            wrts_prcgvr__Activity__c act = this.activitiesToCreate[i];
            if (i < maxActivities) {
                activitiesToProcess.add(act);
            } else {
                activitiesToDelegate.add(act);
            }
        }

        if (!casesToProcess.isEmpty()) {
            System.debug(LoggingLevel.DEBUG, '# cases to update: ' + casesToProcess.size());
            HDT_UTL_DatabaseService.updateSObject(casesToProcess);
            // secondo update di fase per i Case che devono essere annullato a causa di scarto non lavorabile.
            List<Case> casesToDiscard = new List<Case>();
            for (Case c : casesToProcess) {
                if (this.isAutomaticDiscardMap.get(c.Id)) {
                    c.Phase__c = 'Annullato';
                    casesToDiscard.add(c);
                }
            }

            if (!casesToDiscard.isEmpty()) {
                HDT_UTL_DatabaseService.updateSObject(casesToDiscard);
            }
        }

        if (!activitiesToProcess.isEmpty()) {
            System.debug(LoggingLevel.DEBUG, '# activities to create: ' + activitiesToProcess.size());
            HDT_UTL_DatabaseService.insertSObject(activitiesToProcess);
        }

        // ProcessClick non fa partire i job per le callout da contesto queueable,
        // quindi demandiamo la DML che triggera la callout heroku ad un platform event.
        if (!casesForHeroku.isEmpty()) {
            System.debug(LoggingLevel.DEBUG, 'HDT_QBL_SelfReadingsOutcome: setting up platform event, # cases for heroku: ' + casesForHeroku.size());
            HDT_PEV_SelfReading__e event = new HDT_PEV_SelfReading__e();
            event.SerializedCases__c = JSON.serialize(casesForHeroku);

            Database.SaveResult sr = EventBus.publish(event);
            if (sr.isSuccess()) {
                System.debug(LoggingLevel.DEBUG, 'Successfully published event.');
            } else {
                for (Database.Error err : sr.getErrors()) {
                    System.debug(LoggingLevel.ERROR, 'Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
                }
            }
        }

        if (!casesToDelegate.isEmpty() || !activitiesToDelegate.isEmpty()) {
            System.debug(LoggingLevel.DEBUG, 'HDT_QBL_SelfReadingsOutcome: chaining next job...');
            System.enqueueJob(new HDT_QBL_SelfReadingsOutcome(casesToDelegate, activitiesToDelegate, this.isAutomaticDiscardMap));
        }
    }
}