force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_MassiveFieldsObjectMap__mdt/HDT_MassiveFieldsObjectMap__mdt.object-meta.xml
<CustomObject>
    <label>Massive Fields Object Map</label>
    <pluralLabel>Massive Fields Object Map</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_MassiveFieldsObjectMap__mdt/fields/labelField__c.field-meta.xml
<CustomField>
    <fullName>labelField__c</fullName>
    <label>labelField</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_MassiveFieldsObjectMap__mdt/fields/nameField__c.field-meta.xml
<CustomField>
    <fullName>nameField__c</fullName>
    <label>nameField</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In attesa di lavorazione</fullName>
                <default>true</default>
                <label>In attesa di lavorazione</label>
            </value>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Errore</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
                <isActive>false</isActive>
                <label>Done</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Ready To Run</fullName>
                <isActive>false</isActive>
                <label>Ready To Run</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_UTL_ProcessChiusuraOrderCase.cls
/**
 * @author Elvin Iluca NTTDATA
 * Classe utility per la gestione della chiusura massiva Order e Case
 **/

@SuppressWarnings('PMD.AvoidDebugStatements')
public inherited sharing class HDT_UTL_ProcessChiusuraOrderCase extends HDT_UTL_ProcessExecution {
    private List<MassiveLoaderRequestItem__c> itemsToSave;
    private Map<String, String> mapCaseFields;
    private Map<String, String> mapWrapperCaseFields;
    private Map<String, String> mapWrapperOrderFields;
    private List<HDT_WRP_ProcessObjects> processObjList;
    private Map<String, SObject> objMap;


 //map<Id,processObject>    
    public override void checks(){
        System.debug(LoggingLevel.DEBUG, 'checks');

        //Controlli SE CASE != NULL ORDER != NULL SOLO CASE è popolato o solo ORDER è popolato
        
        mapFieldsObject();
        //map.put(caseid||orderId,processObject)
        // System.debug('DEB1: ' + mapCaseFields);
        // System.debug('DEB2: ' + mapWrapperCaseFields);
        // System.debug('DEB3: ' + mapWrapperOrderFields);

        itemsToSave = new List<MassiveLoaderRequestItem__c>();
        HDT_WRP_ProcessObjects processObj;
        processObjList = new List<HDT_WRP_ProcessObjects>();
        List<String> tempSplitedFields;
        // System.debug('DEB3.5: ' + requestItemList);
        for(MassiveLoaderRequestItem__c item : requestItemList){
            tempSplitedFields = new List<String>();
            tempSplitedFields = item.Data__c.split(splitCharacter, -1);//valore dei campi
           // System.debug(tempSplitedFields);
            checkRequiredFields(item, tempSplitedFields);
            checkConsistentItem(item);
            //System.debug(item);
            if(String.isNotBlank(item.Status__c) && item.Status__c.equalsIgnoreCase('Errore')){
                itemsToSave.add(item);
                continue;
            }
            processObj = new HDT_WRP_ProcessObjects();
            processObj.requestItem = item;
            processObj.csvSplitted = tempSplitedFields;
            processObjList.add(processObj);
        }
        //System.debug('DEB4: ' + itemsToSave);
        // System.debug('DEB5: ' + processObjList);
    }
 
    public override void getRecords(){
        System.debug(LoggingLevel.DEBUG, 'getRecords');
        objMap = new Map<String, SObject>();
        List<Case> caseList = HDT_QR_ProcessPostSales.getAllCaseId();
        List<Order> orderList = HDT_QR_ProcessPostSales.getAllOrderId();
        for(Case c : caseList){
            objMap.put(c.Id, c);
        }
        for(Order o : orderList){
            objMap.put(o.Id, o);
        }
    }

    public override void registryCreation(){
        System.debug(LoggingLevel.DEBUG, 'registryCreation');
        List<Sobject> recordsToUpdate=new List<Sobject>();
        //check integrita' sul db degli id in input
        for(HDT_WRP_ProcessObjects currentObj : processObjList){
            //Se l'id dell SObject in question non e' presente ne in caseList ne in orderList -> Errore
            String caseId = currentObj.csvSplitted[0];
            String orderId = currentObj.csvSplitted[1];
            if(!String.isBlank(caseId) && objMap.get(caseId)!=null){
                System.debug('Il case e\' presente nel db ' + currentObj);
                Case tempCase = (Case) objMap.get(caseId);
                tempCase.Phase__c = 'Annullato per decorrenza dei termini';
                tempCase.Status = 'Chiuso';
                //Cambio fase e status al case
                recordsToUpdate.add(tempCase);
                currentObj.requestItem.Status__c = 'Chiuso';
                itemsToSave.add(currentObj.requestItem);
                continue;
            }
            if(!String.isBlank(orderId) && objMap.get(orderId)!=null){
                System.debug('I\'order e\' presente nel db ' + currentObj);
                Order tempOrder = (Order) objMap.get(orderId);
                tempOrder.Phase__c = 'Annullato per decorrenza dei termini';
                tempOrder.Status = 'Completed';
                recordsToUpdate.add(tempOrder);

                currentObj.requestItem.Status__c = 'Chiuso';
                itemsToSave.add(currentObj.requestItem);
               
                continue;
            }
            System.debug('Errore object: ' + currentObj);
            setErrorItem(currentObj.requestItem, 'Errore, Id non presente nel DB');
        }
        if(recordsToUpdate.size()>0){ //Order e phase
            update recordsToUpdate;
        }
        System.debug(recordsToUpdate);

    }

    public override void finalUpdate(){
        System.debug(LoggingLevel.DEBUG, 'finalUpdate');

        if(itemsToSave.size() > 0){
            update itemsToSave;
        }

    }

    /*
    public virtual void registryCreation(){
    List<Sobject> recordsToUpdate=new List<Sobject>();
        System.debug(LoggingLevel.DEBUG, 'registryCreation');
        //aggiorni le fasi e stato
        for(HDT_WRP_ProcessObjects wrp: map.values){
            if(wrp.recordToProcess.getSobjectTYpe=='Case){
            }else{
            }
            recordsToupdate.add(recordToProcess)
        }
        if(recordsToUpdate.size>0){ //Order e phase
            update;
        }
    }
    public virtual void finalUpdate(){
        System.debug(LoggingLevel.DEBUG, 'finalUpdate');
        if(item to save .size>0){
            update item save //MassiveLoaderRequestItem
        }
    } */


    private void checkConsistentItem(MassiveLoaderRequestItem__c item){
        List<String> row = item.Data__c.split(splitCharacter, -1);
        if((String.isBlank(row[0]) && String.isBlank(row[1])) || (!String.isBlank(row[0]) && !String.isBlank(row[1]))){
            setErrorItem(item, 'Error Data__c format');
        }
    }

    private void mapFieldsObject(){
        List<HDT_MassiveFieldsObjectMap__mdt> listCaseFields;
        List<HDT_MassiveFieldsObjectMap__mdt> listWrapperCaseFields;
        List<HDT_MassiveFieldsObjectMap__mdt> listWrapperOrderFields;
        mapCaseFields = new Map<String, String>();
        mapWrapperCaseFields = new Map<String, String>();
        mapWrapperOrderFields = new Map<String, String>();

        listCaseFields = getMapFieldsObject('Case', this.processName);
        listWrapperCaseFields = getMapFieldsObject('WrapperCase', this.processName);
        listWrapperOrderFields = getMapFieldsObject('WrapperOrder', this.processName);

        for(HDT_MassiveFieldsObjectMap__mdt temp : listCaseFields){
            mapCaseFields.put(temp.labelField__c, temp.nameField__c); //mappa header -> api
        }

        for(HDT_MassiveFieldsObjectMap__mdt temp : listWrapperCaseFields){
            mapWrapperCaseFields.put(temp.labelField__c, temp.nameField__c);
        }
        for(HDT_MassiveFieldsObjectMap__mdt temp : listWrapperOrderFields){
            mapWrapperOrderFields.put(temp.labelField__c, temp.nameField__c);
        }

    }

    private class HDT_WRP_ProcessObjects {
        //private Case refCase;
        //private Order refOrder;
        private Sobject recordToProcess;
        private MassiveLoaderRequestItem__c requestItem; //<---- in caso di assenza del case/order
        private List<String> csvSplitted; //<--- 
    }
}