force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentalActivity__c/DocumentalActivity__c.object-meta.xml
<CustomObject>
    <label>Attività Documentale</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Numero Attività</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attività Documentali</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentalActivity__c/fields/ParentProcessId__c.field-meta.xml
<CustomField>
    <fullName>ParentProcessId__c</fullName>
    <description>Campo tecnico inviato dal moga</description>
    <label>Id Processo Padre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalActivity__c/fields/ProcessId__c.field-meta.xml
<CustomField>
    <fullName>ProcessId__c</fullName>
    <description>Campo tecnico inviato dal moga</description>
    <label>Id Processo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentOrder__c.field-meta.xml
<CustomField>
    <fullName>ParentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione verso l&apos;order dossier</description>
    <label>Order Padre</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_TRH_DocumentalActivityTst.cls
@isTest
public with sharing class HDT_TRH_DocumentalActivityTst{

	//DEBUG

	public static final String TEST_NAME = 'HDT_TRH_DocumentalActivityTst';


	//SETUP

	
	//TESTING

	@isTest
	public static void beforeInsertTest(){
		
		
		
		//DEBUG

		String debugString = TEST_NAME + ' - ' + 'beforeInsertTest';
		System.debug(debugString);
		

		//SETUP

		HDT_UTL_DataFactoryTst.pClickCasePhase();
		
		HDT_UTL_DataFactoryTst.pClickOrderPhase();

		List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<Order> ordList = HDT_UTL_DataFactoryTst.createOrder(2, true, accList[0].id, 'Bozza');
		ordList[0].ParentOrder__c = ordList[1].Id;
		update ordList;
        List<ServicePoint__c> servPointList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        List<Contact> contactList = HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].Id);
        List<Contract> contractList = HDT_UTL_DataFactoryTst.createContract(1, true, accList[0].id);
        List<Case> caseList = HDT_UTL_DataFactoryTst.createCase(2, true, accList[0].id, contactList[0].Id, servPointList[0].id, contractList[0].id, ordList[0].id);
		caseList[0].ParentId = caseList[1].Id;
		update CaseList;
		List<DocumentalActivity__c> docActList = new List<DocumentalActivity__c>();
		DocumentalActivity__c dA1 = new DocumentalActivity__c();
		DocumentalActivity__c dA2 = new DocumentalActivity__c();

		// Necessario querare gli oggetti al fine di valorizzare i campi CaseNumber/OrderNumber
		Case caseOne = [SELECT Id, CaseNumber from Case WHERE Id = :caseList[0].Id LIMIT 1];
		Case caseTwo = [SELECT Id, CaseNumber from Case WHERE Id = :caseList[1].Id LIMIT 1];
		Order orderOne = [SELECT Id, OrderNumber from Order WHERE Id = :ordList[0].Id LIMIT 1];
		Order orderTwo = [SELECT Id, OrderNumber from Order WHERE Id = :ordList[1].Id LIMIT 1];

		dA1.ProcessId__c = caseOne.CaseNumber;
		dA2.ProcessId__c = orderOne.OrderNumber;
		
		dA1.ParentProcessId__c = caseTwo.CaseNumber;
		dA2.ParentProcessId__c = orderTwo.OrderNumber;

		docActList.add(dA1);
		docActList.add(dA2);		

		//TESTING

		Test.startTest();

        Try{

			insert docActList;
			
		}catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }        
        Test.stopTest();

		//ASSERTS
        System.assert(docActList != null, 'Attenzione, docActList non può essere null!');
	}

}