force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseVolumetricaJunction__c/CaseVolumetricaJunction__c.object-meta.xml
<CustomObject>
    <label>CaseVolumetricaJunction</label>
    <nameField>
        <label>Nome CaseVolumetricaJunction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseVolumetricaJunction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseVolumetricaJunction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CaseVolumetricaJunction</relationshipLabel>
    <relationshipName>CaseVolumetricaJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseVolumetricaJunction__c/fields/VolumetricEstimate__c.field-meta.xml
<CustomField>
    <fullName>VolumetricEstimate__c</fullName>
    <label>Stima Volumetrica</label>
    <referenceTo>VolumetricEstimate__c</referenceTo>
    <relationshipLabel>CaseVolumetricaJunction</relationshipLabel>
    <relationshipName>CaseVolumetricaJunction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VolumetricEstimate__c/VolumetricEstimate__c.object-meta.xml
<CustomObject>
    <label>Stima Volumetrica</label>
    <nameField>
        <label>Nome Stima Volumetrica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stime Volumetriche</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VolumetricEstimate__c/fields/CubicMeters__c.field-meta.xml
<CustomField>
    <fullName>CubicMeters__c</fullName>
    <label>Metri Cubi</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HDT_LC_MaterialSelectionTest.cls
@isTest
public with sharing class HDT_LC_MaterialSelectionTest {

    @TestSetup
    static void setup(){

        HDT_UTL_DataFactoryTst.pClickCasePhase();
        
        List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<ServicePoint__c> servPointList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        List<Contact> contactList = HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].Id);
        List<Case> caseList = HDT_UTL_DataFactoryTst.createCase(1, true, accList[0].id, contactList[0].Id, servPointList[0].id, null, null);
        List<VolumetricEstimate__c> volums = new List<VolumetricEstimate__c>{
            new VolumetricEstimate__c(Name='Materiale1', CubicMeters__c=1), 
            new VolumetricEstimate__c(Name='Materiale2', CubicMeters__c=2), 
            new VolumetricEstimate__c(Name='Materiale3', CubicMeters__c=3)
        };
        insert volums;
        insert new CaseVolumetricaJunction__c(Case__c=caseList[0].Id, VolumetricEstimate__c=volums[0].Id);
    }
    
    @isTest
    public static void volumetricaQueries(){
        String caseId = [Select id from Case Limit 1].Id;
        HDT_LC_MaterialSelection.HDT_WRP_Data data = new HDT_LC_MaterialSelection.HDT_WRP_Data();
        data = HDT_LC_MaterialSelection.getTables(caseId);
        system.assertEquals(3, data.volumetricEstimate.size(), 'Size tabella volumetriche errato');
        system.assertEquals(1, data.preselectedValues.size(), 'Numero valori junction errati');
    }

    @isTest
    public static void volumetricaModify(){
        String caseId = [Select id from Case Limit 1].Id;
        List<String> volumetricIds = new List<String>();
        for(VolumetricEstimate__c vol :[select id from VolumetricEstimate__c where id NOT IN (Select VolumetricEstimate__c From CaseVolumetricaJunction__c)]){
            volumetricIds.add(vol.Id);
        }
        HDT_LC_MaterialSelection.createJunctionObj(caseId, volumetricIds);
        system.assertEquals(2, HDT_LC_MaterialSelection.getTables(caseId).preselectedValues.size(), 'Numero valori junction errati (non è aumentato)');
    }
}