force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_UTL_PrClickEndSubscriptionBulk.cls
/**
 * @description       : 
 * @author            : federico.defelice@webresults.it
 * @group             : WR
 * @last modified on  : 03-11-2021
 * @last modified by  : federico.defelice@webresults.it
**/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global inherited sharing class HDT_UTL_PrClickEndSubscriptionBulk implements wrts_prcgvr.Interfaces_1_2.IApexActionBulk {


    private static List<SBQQ__Subscription__c> subsToBeTerminated = new List<SBQQ__Subscription__c>();


    /**
    * @description 
    * @author federico.defelice@webresults.it | 03-11-2021 
    * @param args 
    * @return Object 
    **/
    global Object execute(Object args){
        Map<String, Object> argsMap = (Map<String, Object>) args;
        //system.debug(json.serialize(args));

        //String method = (String) argsMap.get('method');

        List<Case> senders = (List<Case>) ((Map<String,Object>)argsMap.get('parameter')).get('records');
        //Map<Id, Id> orderToContract = new Map<Id, Id>();
        Date terminationDay = Date.today();
        for(Case c : senders){
            if(c.Subscription__c!=null){
                subsToBeTerminated.add(new SBQQ__Subscription__c(Id=c.Subscription__c, SBQQ__SubscriptionEndDate__c=terminationDay, SBQQ__TerminatedDate__c=terminationDay));
            }
        }
        return null;
    }


    /**
    * @description 
    * @author federico.defelice@webresults.it | 03-11-2021 
    * @param newOrders 
    **/
    public static void updateCorrelatedObjects(){
        if(subsToBeTerminated.isEmpty()){
            return;
        }
        HDT_UTL_DatabaseService.updateSObject(subsToBeTerminated);
    }
}