force-app/main/default/objects/CS_DaysToExpiration__c/CS_DaysToExpiration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Days to Expiration</label>
</CustomObject>

force-app/main/default/objects/CS_DaysToExpiration__c/fields/NumberOfDays__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDays__c</fullName>
    <label>Numero giorni</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_DaysToExpiration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipologia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attività</label>
    <referenceTo>wrts_prcgvr__Activity__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>CancellationReason__c</fullName>
    <label>Causale Annullamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CancellationReason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ParentOrder__c.field-meta.xml
<CustomField>
    <fullName>ParentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione verso l&apos;order dossier</description>
    <label>Order Padre</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_ScontiBonus.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_ScontiBonus</fullName>
    <active>true</active>
    <label>Aggiunta Sconti o Bonus VAS</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VAS.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VAS</fullName>
    <active>true</active>
    <label>VAS</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OrderID</description>
    <label>Order Correlato</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <formula>IF(NOT(ISNULL(Case__c)), TEXT(Case__r.Phase__c), IF(NOT(ISNULL(Order__c)), TEXT(Order__r.Phase__c), &quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/RequestedCancellationDate__c.field-meta.xml
<CustomField>
    <fullName>RequestedCancellationDate__c</fullName>
    <label>Data annullamento richiesta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo attività</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Anticipo Appuntamento</fullName>
            </value>
            <value>
                <fullName>Approvazione Bonus Commerciale</fullName>
            </value>
            <value>
                <fullName>Approvazione Offerte</fullName>
            </value>
            <value>
                <fullName>Assistenza Contact Center</fullName>
            </value>
            <value>
                <fullName>Attesa Preventivo DL</fullName>
            </value>
            <value>
                <fullName>Attivazioni</fullName>
            </value>
            <value>
                <fullName>Back Office - Catalogo Prodotti</fullName>
            </value>
            <value>
                <fullName>Back Office - Contratti</fullName>
            </value>
            <value>
                <fullName>Back Office - Fatturazione</fullName>
            </value>
            <value>
                <fullName>Back Office - Morosità</fullName>
            </value>
            <value>
                <fullName>Back Office - Pagamenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Preventivi</fullName>
            </value>
            <value>
                <fullName>Back Office - Supporto/Comunicazioni Urgenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Tari/TCP</fullName>
            </value>
            <value>
                <fullName>Back Office - Vas e HVAC</fullName>
            </value>
            <value>
                <fullName>Busta Docusign non consegnata</fullName>
            </value>
            <value>
                <fullName>Caricamenti contratti</fullName>
            </value>
            <value>
                <fullName>Caricamento Manuale Siebel</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Chiamata Callback</fullName>
            </value>
            <value>
                <fullName>Chiamata inbound</fullName>
            </value>
            <value>
                <fullName>Chiamata outbound</fullName>
            </value>
            <value>
                <fullName>Comfort Call</fullName>
            </value>
            <value>
                <fullName>Comunicazione da DL</fullName>
            </value>
            <value>
                <fullName>Comunicazioni con DL</fullName>
            </value>
            <value>
                <fullName>Conferma Preventivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Validation__c.field-meta.xml
<CustomField>
    <fullName>Validation__c</fullName>
    <label>Validata</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/wrts_prcgvr__Status__c.field-meta.xml
<CustomField>
    <fullName>wrts_prcgvr__Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aperta</fullName>
                <default>true</default>
                <label>Aperta</label>
            </value>
            <value>
                <fullName>Sospesa</fullName>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
            <value>
                <fullName>Creata</fullName>
            </value>
            <value>
                <fullName>Presa appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Appuntamento confermato</fullName>
            </value>
            <value>
                <fullName>Appuntamento non eseguito</fullName>
            </value>
            <value>
                <fullName>Appuntamento eseguito</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
            <value>
                <fullName>Invio app.to SELF cliente</fullName>
            </value>
            <value>
                <fullName>Appuntamento di competenza Distributore</fullName>
            </value>
            <value>
                <fullName>Scartata</fullName>
            </value>
            <value>
                <fullName>Modifica confermata</fullName>
            </value>
            <value>
                <fullName>Modifica appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Esitata</fullName>
            </value>
            <value>
                <fullName>Non Esitata</fullName>
            </value>
            <value>
                <fullName>Comunicazione inviata</fullName>
            </value>
            <value>
                <fullName>Comunicazione inviata</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>KO Forzato</fullName>
            </value>
            <value>
                <fullName>KO Risolto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CancellationReason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Classificazione errata</fullName>
    </customValue>
    <customValue>
        <fullName>Codice ABI obsoleto</fullName>
    </customValue>
    <customValue>
        <fullName>Contattare banca</fullName>
    </customValue>
    <customValue>
        <fullName>Contatto Quality Fallito</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazione in corso</fullName>
    </customValue>
    <customValue>
        <fullName>Domiciliazione già presente</fullName>
    </customValue>
    <customValue>
        <fullName>Firma falsa</fullName>
    </customValue>
    <customValue>
        <fullName>Mancanza titolarità</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-ricezione</fullName>
    </customValue>
    <customValue>
        <fullName>No conferma Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>PDR/POD errato</fullName>
    </customValue>
    <customValue>
        <fullName>Pratica errata</fullName>
    </customValue>
    <customValue>
        <fullName>Processo incompatibile</fullName>
    </customValue>
    <customValue>
        <fullName>Quality - Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 14.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 6.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 8.2 del TIMG</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente oltre i termini</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento tramite quality call</fullName>
    </customValue>
    <customValue>
        <fullName>Sollecito</fullName>
    </customValue>
    <customValue>
        <fullName>Volontà estorta</fullName>
    </customValue>
    <customValue>
        <fullName>Gestione Scarto</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per no conferma cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per possibile frode</fullName>
    </customValue>
    <customValue>
        <fullName>Il cliente rinuncia</fullName>
    </customValue>
    <customValue>
        <fullName>Rifiutato Preventivamente</fullName>
    </customValue>
    <customValue>
        <fullName>Registrazione non conforme</fullName>
    </customValue>
    <masterLabel>Motivazione Annullamento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_BA_ActivityVoRefuse.cls
public with sharing class HDT_BA_ActivityVoRefuse implements Database.Batchable<sObject> {

    private static HDT_SRV_ActivityCustom activitySrv = new HDT_SRV_ActivityCustom();
    private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String numberOfDays = setNumberOfDays();
        Date d = date.today();
        Date endDate;
        endDate = d.addDays(-Integer.valueOf(numberOfDays));
        String query = 'SELECT Id, RequestedCancellationDate__c, CreatedDate, Order__c from wrts_prcgvr__Activity__c where validation__c = null AND Type__c = \'Validazione Vocal Order\' and CreatedDate <= :endDate';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<wrts_prcgvr__Activity__c> scope) {
        List<SObject> sobjToUpdate = new List<SObject>();
        Set<String> recordTypeSet = new Set<String>{'HDT_RT_VAS','HDT_RT_ScontiBonus'};
        Set<Id> parentOrders = new Set<Id>();
        for(wrts_prcgvr__Activity__c act : scope)
        {   
            if(act.Order__c != null)
            {
                parentOrders.add(act.Order__c);
                act.wrts_prcgvr__Status__c = 'Chiusa';
                act.validation__c = 'No';
                sobjToUpdate.add(act);

            }
        }
        List<Order> childOrderToUpdate = [SELECT Id, 
            CancellationReason__c, 
            Phase__c,
            Status,
            ParentOrder__c 
            FROM Order
            WHERE ParentOrder__c 
            IN :parentOrders 
            AND RecordType.DeveloperName NOT IN :recordTypeSet 
            WITH SECURITY_ENFORCED];
        
        for(Order child : childOrderToUpdate)
        {
            child.Phase__c = 'Annullato';
            child.Status = 'Annullato';
            child.CancellationReason__c = 'Registrazione non conforme';

            sobjToUpdate.add(child);
        }
        /*List<wrts_prcgvr__Activity__c> actToUpdate = new List<wrts_prcgvr__Activity__c>();
        List<Order> orderList = new List<Order>();
        for (wrts_prcgvr__Activity__c act : scope) {
            //cancel vendita
            act.Validation__c = 'No';
            actToUpdate.add(act); 
            // cancel quote
            for(Order ord : act.Orders__r) {
                if (act.RequestedCancellationDate__c > date.today() && act.wrts_prcgvr__Status__c != 'Closed') {
                    ord.Phase__c = 'Annullato';
                }
                ord.CancellationReason__c = 'Registrazione non conforme';
                orderList.add(ord);
            }
        }*/
        HDT_UTL_DatabaseService.updateSObject(sobjToUpdate);
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('FinishRequiredForBatch');
    }

    public String setNumberOfDays() {
        List<CS_DaysToExpiration__c> numberOfDays = [SELECT NumberOfDays__c FROM CS_DaysToExpiration__c WHERE Type__c='ValidazioneVO'];
        
        return numberOfDays[0].NumberOfDays__c;
    }
}