force-app/main/default/objects/CS_DaysToExpiration__c/CS_DaysToExpiration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Days to Expiration</label>
</CustomObject>

force-app/main/default/objects/CS_DaysToExpiration__c/fields/NumberOfDays__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDays__c</fullName>
    <label>Numero giorni</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_DaysToExpiration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipologia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l&apos;oggetto Vendita</description>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Details con l&apos;oggetto account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendite</relationshipLabel>
    <relationshipName>Vendite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Attiva</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <label>In Lavorazione</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rifiutata</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Annullata</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <label>Accettata</label>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_BA_OldDraftSalesTest.cls
@isTest
public with sharing class HDT_BA_OldDraftSalesTest {

    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
   
    @testSetup

    static void setup(){

        DateTime thirtyDays = System.now().addDays(-30);

        CS_DaysToExpiration__c testCS = new CS_DaysToExpiration__c(Name='Vendita',Type__c='Vendita', NumberOfDays__c='60');
        insert testCS;
        
        Account acc = new Account(name='testAccount');
        insert acc;

        List<Sale__c> sales = new List<Sale__c>();
        List<Id> saleIds = new List<Id>();
        List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
        List<Opportunity> opps = new List<Opportunity>();

        for (Integer i=0; i<10; i++) {
            sales.add(new Sale__c(name='TestVendita' + i, Status__c='Bozza', Account__c=acc.Id));
        }

        insert sales;

        for (Sale__c s : sales) {
            saleIds.add(s.Id);
            Test.setCreatedDate(s.Id, thirtyDays);
        }

        for(Sale__c sale : [SELECT Id from Sale__c WHERE Id IN :saleIds]) {
            quotes.add(new SBQQ__Quote__c(SBQQ__Status__c='Test', Sale__c=sale.Id));
            opps.add(new Opportunity(name='TestOpp', StageName='Proposal', Sale__c=sale.Id, CloseDate=Date.today()));
        }
        insert quotes;
        insert opps;

        system.debug(sales);
        system.debug(saleIds);

        system.debug(quotes);
        system.debug(opps);

        /* List<Sale__c> myList = [SELECT Id, Status__c, CreatedDate, (SELECT Id, SBQQ__Status__c from Quotes__r), (SELECT Id, StageName from Opportunities__r) from Sale__c where Status__c='Bozza'];
        system.debug(myList); */
    }

    @isTest
    public static void testOldDratfSales() {
        
        Test.startTest();
        HDT_BA_OldDraftSales ods = new HDT_BA_OldDraftSales();
        Id batchId = Database.executeBatch(ods);
        Test.stopTest();

       List<Sale__c> mySales = [SELECT Id, Status__c, CreatedDate, (SELECT Id, SBQQ__Status__c from Quotes__r), (SELECT Id, StageName from Opportunities__r) from Sale__c];

       for (Sale__c s : mySales) {
           system.debug(s);
           system.assertEquals('Annullata', s.Status__c, 'value of parameter is matching');

           for(SBQQ__Quote__c quote : s.Quotes__r) {
               system.debug(quote);
               system.assertEquals('Annullata', quote.SBQQ__Status__c, 'value of parameter is matching');
           }
           for(Opportunity opp : s.Opportunities__r) {
               system.debug(opp);
               system.assertEquals('Chiusa/Annullata', opp.StageName, 'value of parameter is matching');
           }
       }
    }

    @isTest 
    public static void testBatchSchedule() {

        Test.startTest();
        String jobId = System.schedule('ScheduleOldDraftSalesTest', CRON_EXP, new HDT_SCH_OldDraftSalesSchedule());

        // checkinhg that batch hasn't been run yet
        List<Sale__c> mySales = [SELECT Id, Status__c FROM Sale__c WHERE Status__c='Annullata'];
        System.assertEquals(0, mySales.size(), 'Sales exist before baatch execution');
        Test.stopTest();
        
        // check schedulable is in job list
        List<AsyncApexJob> jobsScheduled = [select Id, ApexClassID, ApexClass.Name, Status, JobType from AsyncApexJob where JobType = 'ScheduledApex'];
        System.assertEquals(1, jobsScheduled.size(), 'expecting one scheduled job');
        System.assertEquals('HDT_SCH_OldDraftSalesSchedule', jobsScheduled[0].ApexClass.Name, 'expecting specific scheduled job');

        // check apex batch is in job list
        List<AsyncApexJob> jobsApexBatch = [select Id, ApexClassID, ApexClass.Name, Status, JobType from AsyncApexJob where JobType = 'BatchApex'];
        System.assertEquals(1, jobsApexBatch.size(), 'expecting one apex batch job');
        System.assertEquals('HDT_BA_OldDraftSales', jobsApexBatch[0].ApexClass.Name, 'expecting specific batch job');

    }
}