force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account del titolare del punto di fornitura</description>
    <label>Account Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points (Account)</relationshipLabel>
    <relationshipName>Service_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/AnnualConsumption__c.field-meta.xml
<CustomField>
    <fullName>AnnualConsumption__c</fullName>
    <description>Consumo Annuo</description>
    <label>Consumo Annuo</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/BrandLogo__c.field-meta.xml
<CustomField>
    <fullName>BrandLogo__c</fullName>
    <description>AS-Is viene valorizzato da SAP ed è comunque richiesto nelle comunicazioni con SAP</description>
    <label>Brand Logo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Disconnectable__c.field-meta.xml
<CustomField>
    <fullName>Disconnectable__c</fullName>
    <label>Disalimentabile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributore</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Necessario inserire un Account Distributore</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HDT_RT_Distributore</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points</relationshipLabel>
    <relationshipName>ServicePoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ImplantType__c.field-meta.xml
<CustomField>
    <fullName>ImplantType__c</fullName>
    <label>Tipologia Impianto</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CommoditySector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_ImplantType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/IsRemoteManaged__c.field-meta.xml
<CustomField>
    <fullName>IsRemoteManaged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Impianto Telegestito</description>
    <label>Impianto Telegestito</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MarketOrigin__c.field-meta.xml
<CustomField>
    <fullName>MarketOrigin__c</fullName>
    <label>Mercato di provenienza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterClass__c.field-meta.xml
<CustomField>
    <fullName>MeterClass__c</fullName>
    <description>Classe o Calibro Contatore</description>
    <label>Classe Contatore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G100 Turbina</fullName>
            </value>
            <value>
                <fullName>G160 Turbina</fullName>
            </value>
            <value>
                <fullName>G250 Turbina</fullName>
            </value>
            <value>
                <fullName>G400 Turbina</fullName>
            </value>
            <value>
                <fullName>G40 Turbina</fullName>
            </value>
            <value>
                <fullName>G65 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G160 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G250 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G250G Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G650 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G1000 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G400 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G1600 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G4000 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>DIR Monorario</fullName>
            </value>
            <value>
                <fullName>DIR Orario</fullName>
            </value>
            <value>
                <fullName>DIR Biorario</fullName>
            </value>
            <value>
                <fullName>100 Volt</fullName>
            </value>
            <value>
                <fullName>400 Volt</fullName>
            </value>
            <value>
                <fullName>230 Volt</fullName>
            </value>
            <value>
                <fullName>Elettronico</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>G1,6</fullName>
            </value>
            <value>
                <fullName>G10</fullName>
            </value>
            <value>
                <fullName>G100</fullName>
            </value>
            <value>
                <fullName>G1000</fullName>
            </value>
            <value>
                <fullName>G16</fullName>
            </value>
            <value>
                <fullName>G160</fullName>
            </value>
            <value>
                <fullName>G1600</fullName>
            </value>
            <value>
                <fullName>G2,5</fullName>
            </value>
            <value>
                <fullName>G25</fullName>
            </value>
            <value>
                <fullName>G250</fullName>
            </value>
            <value>
                <fullName>G4</fullName>
            </value>
            <value>
                <fullName>G40</fullName>
            </value>
            <value>
                <fullName>G400</fullName>
            </value>
            <value>
                <fullName>G4000</fullName>
            </value>
            <value>
                <fullName>G6</fullName>
            </value>
            <value>
                <fullName>G65</fullName>
            </value>
            <value>
                <fullName>G650</fullName>
            </value>
            <value>
                <fullName>G6500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterSN__c.field-meta.xml
<CustomField>
    <fullName>MeterSN__c</fullName>
    <description>Matricola del contatore attuale</description>
    <label>Matricola Contatore</label>
    <!--Modificata lunghezza campo da 255 a 18 in quanto Siebel, SAP non accettano matricole superiori ai 18
    Essendo un campo compilabile dall'operatore, al fine di preservare la coerenza dei dati tra i sistemi
    e' stata applicata la modifica della lunghezza.
    -->
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/PowerAvailable__c.field-meta.xml
<CustomField>
    <fullName>PowerAvailable__c</fullName>
    <description>Potenza disponibile dal Contatore</description>
    <label>Potenza Disponibile</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/PowerContractual__c.field-meta.xml
<CustomField>
    <fullName>PowerContractual__c</fullName>
    <description>Potenza Richiesta dal cliente (Richiesta / Impegnata)</description>
    <label>Potenza Contrattuale</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressione Fornitura</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/RemiCode__c.field-meta.xml
<CustomField>
    <fullName>RemiCode__c</fullName>
    <description>Cabina di REgolazione e MIsura (REMI) è il punto fisico di congiunzione tra le reti.</description>
    <label>Codice REMI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/RequestPhase__c.field-meta.xml
<CustomField>
    <fullName>RequestPhase__c</fullName>
    <label>Fase Richiesta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_PhaseType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Residente</description>
    <label>Residente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SAPImplantCode__c.field-meta.xml
<CustomField>
    <fullName>SAPImplantCode__c</fullName>
    <description>SAPImplantCode__c</description>
    <externalId>true</externalId>
    <label>Impianto SAP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyCountry__c.field-meta.xml
<CustomField>
    <fullName>SupplyCountry__c</fullName>
    <label>Stato [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyIsAddressVerified__c.field-meta.xml
<CustomField>
    <fullName>SupplyIsAddressVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indirizzo verificato  [Fornitura]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyPlace__c.field-meta.xml
<CustomField>
    <fullName>SupplyPlace__c</fullName>
    <label>Place [Supply]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyPlaceCode__c.field-meta.xml
<CustomField>
    <fullName>SupplyPlaceCode__c</fullName>
    <label>Codice Località [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyPostalCode__c.field-meta.xml
<CustomField>
    <fullName>SupplyPostalCode__c</fullName>
    <label>CAP [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyProvince__c.field-meta.xml
<CustomField>
    <fullName>SupplyProvince__c</fullName>
    <label>Provincia [Fornitura]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplySAPCityCode__c.field-meta.xml
<CustomField>
    <fullName>SupplySAPCityCode__c</fullName>
    <label>SAP City Code [Supply]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplySAPStreetCode__c.field-meta.xml
<CustomField>
    <fullName>SupplySAPStreetCode__c</fullName>
    <label>Codice Via Stradario SAP [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyStreet__c.field-meta.xml
<CustomField>
    <fullName>SupplyStreet__c</fullName>
    <label>Street [Supply]</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyStreetNumber__c.field-meta.xml
<CustomField>
    <fullName>SupplyStreetNumber__c</fullName>
    <label>Civico [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyStreetNumberExtension__c.field-meta.xml
<CustomField>
    <fullName>SupplyStreetNumberExtension__c</fullName>
    <label>Street Number Extension [Supply]</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyStreetToponym__c.field-meta.xml
<CustomField>
    <fullName>SupplyStreetToponym__c</fullName>
    <description>Contiene il Toponimo dell&apos;indirizzo</description>
    <label>Toponimo [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/TemporaryContractCode__c.field-meta.xml
<CustomField>
    <fullName>TemporaryContractCode__c</fullName>
    <description>Codice contratto SAP utilizzato durante il transitorio</description>
    <label>Codice Contratto Transitorio</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <description>Livello di tensione</description>
    <label>Tensione di Consegna</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VoltageLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_ImplantType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1001-Cottura cibi</fullName>
    </customValue>
    <customValue>
        <fullName>1002-Cottura/Produz acq calda</fullName>
    </customValue>
    <customValue>
        <fullName>1003-Riscaldamento esclusivo</fullName>
    </customValue>
    <customValue>
        <fullName>1004-Riscaldamento promiscuo</fullName>
    </customValue>
    <customValue>
        <fullName>1005-Risc. centraliz esclusivo</fullName>
    </customValue>
    <customValue>
        <fullName>1006-Risc. centraliz promiscuo</fullName>
    </customValue>
    <customValue>
        <fullName>1007-Attivita produttive</fullName>
    </customValue>
    <customValue>
        <fullName>1008-Promiscuo (prod+ risc)</fullName>
    </customValue>
    <customValue>
        <fullName>1009-Reti (cabine primo salto)</fullName>
    </customValue>
    <customValue>
        <fullName>1010-Usi interni</fullName>
    </customValue>
    <customValue>
        <fullName>13A0-Usi di Abitazione BT</fullName>
    </customValue>
    <customValue>
        <fullName>13BB-Illuminazione pubblica BT</fullName>
    </customValue>
    <customValue>
        <fullName>13CB-Non domestici in BT</fullName>
    </customValue>
    <customValue>
        <fullName>13CT-Forn temporanee &lt; 21 gg</fullName>
    </customValue>
    <customValue>
        <fullName>13DM-Illuminazione pubblica MT</fullName>
    </customValue>
    <customValue>
        <fullName>13EM-Non domestici MT</fullName>
    </customValue>
    <customValue>
        <fullName>13FM-Non domestici AT</fullName>
    </customValue>
    <customValue>
        <fullName>13X0-Usi interni BT</fullName>
    </customValue>
    <customValue>
        <fullName>13Y0-Usi interni MT</fullName>
    </customValue>
    <customValue>
        <fullName>13Z0-Grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>1101-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>1102-Non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>1103-Attivita</fullName>
    </customValue>
    <customValue>
        <fullName>1104-Scar. poz priv. civ. cont</fullName>
    </customValue>
    <customValue>
        <fullName>1105-Antincendio</fullName>
    </customValue>
    <customValue>
        <fullName>1106-Cantiere</fullName>
    </customValue>
    <customValue>
        <fullName>1107-Colonnetta</fullName>
    </customValue>
    <customValue>
        <fullName>1108-Irriguo</fullName>
    </customValue>
    <customValue>
        <fullName>1109-Comunale</fullName>
    </customValue>
    <customValue>
        <fullName>1110-Ente pubblico</fullName>
    </customValue>
    <description>1001-Cottura cibi
1002-Cottura/Produz acq calda
1003-Riscaldamento esclusivo
1100-ACQUA --- Non definito --- 
1119-Scar. ind.le  cont. Div</description>
    <masterLabel>Tipologia Impianto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Libero</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>FUI</fullName>
    </customValue>
    <customValue>
        <fullName>Regolamentato</fullName>
    </customValue>
    <customValue>
        <fullName>Salvaguardia</fullName>
    </customValue>
    <customValue>
        <fullName>STGM</fullName>
    </customValue>
    <masterLabel>Mercato</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_PhaseType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monofase</fullName>
    </customValue>
    <customValue>
        <fullName>Trifase</fullName>
    </customValue>
    <description>Monofase
Trifase</description>
    <masterLabel>Tipologia Fase</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_VoltageLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AAT</fullName>
    </customValue>
    <description>Livello Tensione</description>
    <masterLabel>Livello Tensione</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_ServicePoint.cls
public with sharing class HDT_UTL_ServicePoint {
    private static HDT_QR_Account accountQr = new HDT_QR_Account();
    public HDT_UTL_ServicePoint() {

    }


    @AuraEnabled
	public static List<ServicePoint__c> extractDataFromArriccDataServiceWithExistingSp(ServicePoint__c sp, HDT_WS_ArrichmentDataEntityResponse response ){
		
			servicePoint__c spNew = new servicePoint__c();
			if(sp!= null){
				system.debug('entra in sp diverso da null' + sp);
				spNew = sp;
			}
		Map<string,string> mapRes = new Map<string,string>();
		system.debug('posizioni ***************************'+response.data.posizioni[0]);
	
			for(HDT_WS_ArrichmentDataEntityResponse.HDT_WRP_posizioniResponseObject r : response.data.posizioni){
				if(!String.isBlank(r.campo) && mapRes.get(r.campo.toUpperCase()) == null){
					system.debug('campo ****' + r.campo);
					system.debug('valore ****' + r.valore);
					mapRes.put(r.campo.toUpperCase(),r.valore);
				}
	
			}

		
					
	/*	if(mapRes.get('CALIBRO1')!=null && !String.isBlank(mapRes.get('CALIBRO1'))){
			spNew.MeterClass__c = mapRes.get('CALIBRO1');
		}
		if(mapRes.get('CODICEREMI')!=null && !String.isBlank(mapRes.get('CODICEREMI'))){
			spNew.RemiCode__c = mapRes.get('CODICEREMI');
		}

		if(mapRes.get('CONTRATTO')!=null && !String.isBlank(mapRes.get('CONTRATTO'))){
			spNew.TemporaryContractCode__c = mapRes.get('CONTRATTO');
		}

	/*	if(mapRes.get('CONTRATTO')!=null && !String.isBlank(mapRes.get('CONTRATTO'))){
			spNew.Disconnectable__c = mapRes.get('CONTRATTO');
		}*/

		/*if(mapRes.get('FASE')!=null && !String.isBlank(mapRes.get('FASE'))){
			spNew.RequestPhase__c  = mapRes.get('FASE');
		}
*/
		if(mapRes.get('PRESSIONE')!=null && !String.isBlank(mapRes.get('PRESSIONE'))){
			spNew.Pressure__c  = integer.valueOf(mapRes.get('PRESSIONE'));
		}

		if(mapRes.get('CODICEREMI')!=null && !String.isBlank(mapRes.get('CODICEREMI'))){
			spNew.RemiCode__c = mapRes.get('CODICEREMI');
		}
        if(mapRes.get('CALIBRO1')!=null && !String.isBlank(mapRes.get('CALIBRO1'))){
			//spNew.MeterClass__c = mapRes.get('CALIBRO1') == 'GRT003' ? 'G4' : 'G6' ;
           if(mapRes.get('CALIBRO1')=='GRT005'){
            spNew.MeterClass__c = 'G10';

           }
           if(mapRes.get('CALIBRO1')=='GRT010'){
            spNew.MeterClass__c = 'G100';
            
           }
           if(mapRes.get('CALIBRO1')=='GRT015'){
            spNew.MeterClass__c = 'G100';
            
           }
           if(mapRes.get('CALIBRO1')=='GRT006'){
            spNew.MeterClass__c = 'G16';
            
           }
           if(mapRes.get('CALIBRO1')=='GRT011'){
            spNew.MeterClass__c = 'G160';
            
           }
           if(mapRes.get('CALIBRO1')=='GRT016'){
            spNew.MeterClass__c = 'G1600';
            
           }
           if(mapRes.get('CALIBRO1')=='GRT002'){
            spNew.MeterClass__c = 'G2,5';
            
           }
           if(mapRes.get('CALIBRO1')=='GRT007'){
            spNew.MeterClass__c = 'G25';
            
           }
           if(mapRes.get('CALIBRO1')=='GRT012'){
            spNew.MeterClass__c = 'G250';
           }
           if(mapRes.get('CALIBRO1')=='GRT003'){
            spNew.MeterClass__c = 'G4';
           }
           if(mapRes.get('CALIBRO1')=='GRT008'){
            spNew.MeterClass__c = 'G40';
           }
           if(mapRes.get('CALIBRO1')=='GRT013'){
            spNew.MeterClass__c = 'G400';
           }
           if(mapRes.get('CALIBRO1')=='GRT017'){
            spNew.MeterClass__c = 'G4000';
           }
           if(mapRes.get('CALIBRO1')=='GRT004'){
            spNew.MeterClass__c = 'G6';
           }
           if(mapRes.get('CALIBRO1')=='GRT009'){
            spNew.MeterClass__c = 'G65';
           }
           if(mapRes.get('CALIBRO1')=='GRT014'){
            spNew.MeterClass__c = 'G650';
           }
           if(mapRes.get('CALIBRO1')=='GRT018'){
            spNew.MeterClass__c = 'G6500';
           }

		}
        if(mapRes.get('MATRICOLA1')!=null && !String.isBlank(mapRes.get('MATRICOLA1'))){
			spNew.MeterSN__c = mapRes.get('MATRICOLA1');
		}
        if(mapRes.get('BRANDSOCIETARIO')!=null && !String.isBlank(mapRes.get('BRANDSOCIETARIO'))){
			spNew.BrandLogo__c   = mapRes.get('BRANDSOCIETARIO');
		}


				//campi fornitura
				if(mapRes.get('DISTRIBUTORE')!=null && !String.isBlank(mapRes.get('DISTRIBUTORE'))){
					//spNew.Account__r.id =mapRes.get('DISTRIBUTORE') ;
                    Account a = accountQr.getAccountByDistributorKey(mapRes.get('DISTRIBUTORE'));
                    spNew.Distributor__c = a.id;
                    System.debug('SOLILLO');
				}
				if(mapRes.get('POD')!=null && !String.isBlank(mapRes.get('POD'))){
					spNew.ServicePointCode__c   = mapRes.get('POD');
                    spNew.Name   = mapRes.get('POD');


				}
				if(mapRes.get('DESCRCOMM')!=null && !String.isBlank(mapRes.get('DESCRCOMM'))){
				
                    if(mapRes.get('DESCRCOMM')== 'Energia elettrica'){
                        spNew.CommoditySector__c = 'Energia Elettrica';

                    }else
                    {
					    spNew.CommoditySector__c = 'Gas';
                    }
		
				}
                if(mapRes.get('MOTGARANZIAFORN')==null){
				
                    spNew.Disconnectable__c = 'Si';
				}
                else if (mapRes.get('MOTGARANZIAFORN') == ''){
				
                    spNew.Disconnectable__c = 'No';
				}

				if(mapRes.get('IMPIANTO')!=null && !String.isBlank(mapRes.get('IMPIANTO'))){
		
					spNew.SAPImplantCode__c = mapRes.get('IMPIANTO');
				}
				if(mapRes.get('TIPOIMPIANTO')!=null && !String.isBlank(mapRes.get('TIPOIMPIANTO'))){
		
					spNew.ImplantType__c  = mapRes.get('TIPOIMPIANTO')+'-'+mapRes.get('DESCRTIPOIMP');		
				}
				if(mapRes.get('CONSUMOCAPDR')!=null && !String.isBlank(mapRes.get('CONSUMOCAPDR'))){
		
					spNew.AnnualConsumption__c = integer.valueOf(mapRes.get('CONSUMOCAPDR'));
				}
                if(mapRes.get('CONSUMOANNUOEE')!=null && !String.isBlank(mapRes.get('CONSUMOANNUOEE'))){
		
					spNew.AnnualConsumption__c = integer.valueOf(mapRes.get('CONSUMOANNUOEE'));
				}
				if(mapRes.get('MERCATO')!=null && !String.isBlank(mapRes.get('MERCATO'))){
                    String mercato = mapRes.get('MERCATO').substring(0,1) + mapRes.get('MERCATO').substring(1,mapRes.get('MERCATO').length()).toLowerCase();
					spNew.MarketOrigin__c = mercato;
				}
				if(mapRes.get('FLAGTELEGESTIBILE')!=null && !String.isBlank(mapRes.get('FLAGTELEGESTIBILE'))){
		
					spNew.IsRemoteManaged__c = 'X'.equalsIgnoreCase(mapRes.get('FLAGTELEGESTIBILE'));
				}
				if(mapRes.get('POTENZACONTRATTUALE')!=null && !String.isBlank(mapRes.get('POTENZACONTRATTUALE'))){
					//spNew.PowerContractual__c = integer.valueOf(mapRes.get('POTENZACONTRATTUALE').subString(0,mapRes.get('POTENZACONTRATTUALE').indexOf('.')+1));
                    Decimal d = integer.valueOf(mapRes.get('POTENZATECNICA'));
                    System.debug('POTENZACONTRATTUALE****************' + mapRes.get('POTENZACONTRATTUALE'));
                    spNew.PowerContractual__c = d.setScale(0);
                    System.debug('POTENZACONTRATTUALE2****************' + spNew.PowerContractual__c );
				}
				if(mapRes.get('POTENZATECNICA')!=null && !String.isBlank(mapRes.get('POTENZATECNICA'))){

                    System.debug('POTENZATECNICA1****************' + mapRes.get('POTENZATECNICA'));
                    
                    Decimal d = integer.valueOf(mapRes.get('POTENZATECNICA'));
                    //spNew.PowerAvailable__c  =integer.valueOf(mapRes.get('POTENZATECNICA').subString(0,mapRes.get('POTENZATECNICA').indexOf('.'))) ;
                    spNew.PowerAvailable__c  =d.setScale(1);

                    System.debug('POTENZATECNICA****************' + d.setScale(1));

				}
				if(mapRes.get('TENSIONE')!=null && !String.isBlank(mapRes.get('TENSIONE'))){
		
					spNew.VoltageLevel__c = mapRes.get('TENSIONE');
				}
				if(mapRes.get('RESIDENTEINDFORN')!=null && !String.isBlank(mapRes.get('RESIDENTEINDFORN'))){
		
					spNew.Resident__c = mapRes.get('RESIDENTEINDFORN') == 'SI' ? true : false;
				}

				//campi indirizzo
				if(mapRes.get('CAP')!=null && !String.isBlank(mapRes.get('CAP'))){

					spNew.SupplyPostalCode__c = mapRes.get('CAP');
				}
				if(mapRes.get('VIA')!=null && !String.isBlank(mapRes.get('VIA'))){
					spNew.SupplyStreet__c  = mapRes.get('VIA');
				}
				if(mapRes.get('TIPOVIA')!=null && !String.isBlank(mapRes.get('TIPOVIA'))){
					spNew.SupplyStreetToponym__c  = mapRes.get('TIPOVIA');
				}
				if(mapRes.get('CIVICO')!=null && !String.isBlank(mapRes.get('CIVICO'))){
					spNew.SupplyStreetNumber__c  = mapRes.get('CIVICO');
				}
				if(mapRes.get('LOCALITA')!=null && !String.isBlank(mapRes.get('LOCALITA'))){
					spNew.SupplyCity__c  = mapRes.get('LOCALITA');
				}
				if(mapRes.get('CODICEVIA')!=null && !String.isBlank(mapRes.get('CODICEVIA'))){
					spNew.SupplySAPStreetCode__c = mapRes.get('CODICEVIA');
				}
                if(mapRes.get('REGIONE')!=null && !String.isBlank(mapRes.get('REGIONE'))){
					spNew.SupplyProvince__c = mapRes.get('REGIONE');
				}
				if(mapRes.get('CODIFICALOCALITA')!=null && !String.isBlank(mapRes.get('CODIFICALOCALITA'))){
					spNew.SupplySAPCityCode__c = mapRes.get('CODIFICALOCALITA');
				}
                if(mapRes.get('CODICEPAESE')!=null && !String.isBlank(mapRes.get('CODICEPAESE'))){
					spNew.SupplyCountry__c = mapRes.get('CODICEPAESE') == 'IT' ? 'Italia' : 'Estero';
				}


		system.debug('spNew*****************' + spNew);
		List<ServicePoint__c> servicePoints = new List<ServicePoint__c>();
		servicePoints.add(spNew);
		return servicePoints;
	}

    @AuraEnabled
    public static List<String> objectToList(HDT_WRP_AddressObject Wrap){
        System.debug('HDT_UTL_ServicePoint objectToList START');

        List<String> listFields = new List<String>();
        String stringWrap = JSON.serialize(Wrap);
        listFields = (List<String>)JSON.deserializeUntyped(stringWrap);

        System.debug('HDT_UTL_ServicePoint objectToList END');
        return listFields;

    }
 

    @AuraEnabled(cacheable=true)
    public static  HDT_WRP_AddressObject getInstanceWrapAddressObject(sObject s){
    System.debug('HDT_UTL_ServicePoint - getInstanceWrapAddressObject START');

    Map<String,String> mapApiName = new map<String,String>{	
        'SupplyPostalCode__c' => 'CAP',
        'SupplyStreetNumber__c' => 'Civico',
        'SupplyCountry__c' => 'Stato',
        'SupplySAPCityCode__c' => 'CodiceComuneSAP',
        'SupplyCity__c' => 'Comune',
        'SupplyStreet__c' => 'Via',
        'SupplyStreetNumberExtension__c' => 'EstensCivico',
        'SupplySAPStreetCode__c' => 'CodiceViaStradarioSAP',
        'SupplyIsAddressVerified__c' => 'IndirizzoVerificato',
        'SupplyProvince__c' => 'Provincia',
        'SupplyIsAddressVerified__c' => 'FlagVerificato',
        'SupplyPlace__c' => 'Localita',
        'SupplyPlaceCode__c' => 'CodiceLocalita'
        };

   
    HDT_WRP_AddressObject result = new HDT_WRP_AddressObject();

    if(s!= null){
        System.debug('HDT_UTL_ServicePoint - getInstanceWrapAddressObject END');
        List<sObject> listObject = new  List<sObject>();
        listObject.add((sObject)s);
        String type = listObject.get(0).getSObjectType().getDescribe().getName();
        Map<String,Boolean> mapBooleanObject = new Map<String,Boolean>();
        Map<String,String> mapObject = new Map<String,String>();
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType objectSchema = schemaMap.get(type);
        Map<String, Schema.SObjectField> fieldMap = objectSchema.getDescribe().fields.getMap();
    
        for (String fieldName: fieldMap.keySet()) 
        {
            //System.debug('Field API Name='+fieldName+'label :'+fieldMap.get(fieldName).getDescribe().getLabel());
            Schema.DisplayType fielddataType = fieldMap.get(fieldName).getDescribe().getType();
            if(fielddataType.name().toUpperCase() == 'STRING' || fielddataType.name().toUpperCase() == 'TEXTAREA'|| fielddataType.name().toUpperCase() == 'TEXT')
            {
                mapObject.put(fieldMap.get(fieldName).getDescribe().getName(),(String)(s.get(fieldName)));
            }
            if(fielddataType.name().toUpperCase() == 'BOOLEAN'||fielddataType.name().toUpperCase() == 'CHECKBOX' ){
                mapBooleanObject.put(fieldMap.get(fieldName).getDescribe().getName(),(Boolean)(s.get(fieldName)));
            }                
        }
        system.debug('mapObject*************'+mapObject);
        system.debug('mapBooleanObject*************'+mapBooleanObject);
        return  result =   mapFieldsAddressWithWrapObject(mapObject,mapBooleanObject,mapApiName);

    }else{     
    
        result = new HDT_WRP_AddressObject('','','','','','','','','',false,false,'','');
        System.debug('result:' +  result);
    }

	
    System.debug('HDT_UTL_ServicePoint - getInstanceWrapAddressObject END');
    return result;
    }
	
	
	
	@AuraEnabled(cacheable=true)
    public static HDT_WRP_AddressObject mapFieldsAddressWithWrapObject(Map<String,String> mapObject,Map<String,Boolean> mapBooleanObject,Map<String,String> mapApiName){
        System.debug('HDT_UTL_ServicePoint - mapFieldsAddressWithWrapObject START');
        HDT_WRP_AddressObject h = new HDT_WRP_AddressObject();
		
		if(!mapObject.isEmpty()){
            for(String s :mapObject.keySet()){
                system.debug('stringa *****************' + s);
                
                if(mapApiName.containsKey(s) && s == 'SupplyPostalCode__c'){
                    System.debug('CAP :' + mapObject.get(s));
                    h.CAP = mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyCity__c'){
                    System.debug('Comune :' + mapObject.get(s));
                    h.Comune= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyStreet__c'){
                    System.debug('Via :' + mapObject.get(s));
                    h.Via= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyStreetNumber__c'){
                    System.debug('Civico :' + mapObject.get(s));
                    h.Civico= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyStreetNumberExtension__c'){
                    System.debug('EstensCivico :' + mapObject.get(s));
                    h.EstensCivico= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyProvince__c'){
                    System.debug('Provincia :' + mapObject.get(s));
                    h.Provincia= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyCountry__c'){
                    System.debug('Stato :' + mapObject.get(s));
                    h.Stato= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplySAPCityCode__c'){
                    System.debug('CodiceComuneSAP :' + mapObject.get(s));
                    h.CodiceComuneSAP= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplySAPStreetCode__c'){
                    System.debug('CodiceViaStradarioSAP :' + mapObject.get(s));
                    h.CodiceViaStradarioSAP= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplySAPStreetCode__c'){
                    System.debug('CodiceViaStradarioSAP :' + mapObject.get(s));
                    h.CodiceViaStradarioSAP= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyPlace__c'){
                    System.debug('Localita :' + mapObject.get(s));
                    h.Localita= mapObject.get(s);
                }
                if(mapApiName.containsKey(s) && s == 'SupplyPlaceCode__c'){
                    System.debug('Codice Localita :' + mapObject.get(s));
                    h.CodiceLocalita= mapObject.get(s);
                }
            }
        }
    

        if(!mapBooleanObject.isEmpty())
        {
            for(String b :mapBooleanObject.keySet())
            {
                if(mapApiName.containsKey(b)&& b == 'SupplyIsAddressVerified__c')
                {
                    System.debug('flagVerificato :' + mapBooleanObject.get(b));
                    h.flagVerificato= mapBooleanObject.get(b);
                }
            }
        }
        system.debug('wrapObject: ***************' + h);

          
        System.debug('HDT_UTL_ServicePoint - mapFieldsAddressWithWrapObject END');
        return h;
        
    }
}