force-app/main/default/objects/HDT_MetersListColumnTable__mdt/HDT_MetersListColumnTable__mdt.object-meta.xml
<CustomObject>
    <label>Tabella Elenco Misuratori</label>
    <pluralLabel>Tabella Elenco Misuratori</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_MetersListColumnTable__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HDT_ServicePointMetersList__mdt/HDT_ServicePointMetersList__mdt.object-meta.xml
<CustomObject>
    <label>Elenco Misuratori</label>
    <pluralLabel>Elenco Misuratori</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_ServicePointMetersList__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End point</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_MetersList.cls
public inherited sharing class HDT_QR_MetersList {

    public static List<HDT_MetersListColumnTable__mdt> getMetersListColumnTable(List<HDT_MetersListColumnTable__mdt> metersListColumnTable){
        metersListColumnTable = new List<HDT_MetersListColumnTable__mdt>();
        
        SObjectType objtype = Schema.getGlobalDescribe().get('HDT_MetersListColumnTable__mdt');
        Schema.DescribeSObjectResult objRes = objtype.getDescribe();

        if(objRes.isAccessible()){
            metersListColumnTable = [
                SELECT DeveloperName, MasterLabel
                FROM HDT_MetersListColumnTable__mdt
                ORDER BY Order__c
            ];
        }

        return metersListColumnTable;
    }

    /*public static List<HDT_ServicePointMetersList__mdt> getNamedCredential(List<HDT_ServicePointMetersList__mdt> metadataList, String code){
        metadataList = new List<HDT_ServicePointMetersList__mdt>();

        SObjectType objtype = Schema.getGlobalDescribe().get('HDT_ServicePointMetersList__mdt');
        Schema.DescribeSObjectResult objRes = objtype.getDescribe();

        if(objRes.isAccessible()){
            metadataList = [
                SELECT Endpoint__c
                FROM HDT_ServicePointMetersList__mdt
                WHERE DeveloperName = :code
                WITH SECURITY_ENFORCED
            ];
        }

        return metadataList;

    }*/

    public static List<ServicePoint__c> getServicePoint(List<ServicePoint__c> servicePointList, String recordId){
        servicePointList = new List<ServicePoint__c>();
        
        SObjectType objtype = Schema.getGlobalDescribe().get('ServicePoint__c');
        Schema.DescribeSObjectResult objRes = objtype.getDescribe();

        if(objRes.isAccessible()){
            servicePointList = [
                SELECT Id, Name, ServicePointCode__c
                FROM ServicePoint__c
                WHERE Id = :recordId
            ];
        }

        return servicePointList;
    }

}