force-app/main/default/objects/AtecoMatrix__c/AtecoMatrix__c.object-meta.xml
<CustomObject>
    <description>Oggetto tecnico (matrice) per la gestione dei codici Ateco e relative tipizazioni</description>
    <label>Matrice Ateco</label>
    <nameField>
        <label>Matrice Ateco Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice Ateco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AtecoMatrix__c/fields/AtecoCode__c.field-meta.xml
<CustomField>
    <fullName>AtecoCode__c</fullName>
    <label>Codice Ateco</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Comune</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/IstatCode__c.field-meta.xml
<CustomField>
    <fullName>IstatCode__c</fullName>
    <label>Codice Istat</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/RonchiCode__c.field-meta.xml
<CustomField>
    <fullName>RonchiCode__c</fullName>
    <label>Codice Ronchi</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>Lista di citta con corrispettivo codice belfiore per il calcolo del codice fiscale</description>
    <label>Città</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Città</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_QR_AtecoMatrixTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 23/08/2021
 * @description Test Class for HDT_QR_AtecoMatrix.cls
 * @history Fabricio Petkevicius Nunes – 23/08/2021 – Created class
 */
@isTest
public class HDT_QR_AtecoMatrixTst{
	@TestSetup
	static void setup(){

		List<AtecoMatrix__c> atecoMats=HDT_UTL_DataFactoryTst.createAtecoMatrix(1, false, 'testAtecoM');
		atecoMats[0].AtecoCode__c='test0';
		atecoMats[0].City__c='RO';
		atecoMats[0].IstatCode__c='test1';
		atecoMats[0].Category__c='test3';
		atecoMats[0].RonchiCode__c='test4';
		atecoMats[0].AtecoCode__c='test5';

		insert atecoMats;
	}

	@isTest
	static void testgetAtecoMatrixByComune(){

		Test.startTest();

		List<AtecoMatrix__c> testGetByComune=HDT_QR_AtecoMatrix.getAtecoMatrixByComune('RO');

		System.assertEquals('RO', testGetByComune[0].City__c, 'Ateco Matrix returned is wrong');
		System.assertNotEquals('', testGetByComune[0].City__c, 'getAtecoMatrixByComune did not work correctly');

		Test.stopTest();
	}

	@isTest
	static void testgetAtecoMatrixByCodiceIstat(){

		Test.startTest();

		List<AtecoMatrix__c> testGetByIstatCode=HDT_QR_AtecoMatrix.getAtecoMatrixByCodiceIstat('test1');

		System.assertEquals('test1', testGetByIstatCode[0].IstatCode__c, 'Ateco Matrix returned is wrong');
		System.assertNotEquals('', testGetByIstatCode[0].IstatCode__c, 'getAtecoMatrixByCodiceIstat did not work correctly');

		Test.stopTest();
	}

	@IsTest
	static void testGetAtecoMatrixByCodiceIstatWhich(){
		
		Test.startTest();

		List<AtecoMatrix__c> testGetByIstatCode = HDT_QR_AtecoMatrix.getAtecoMatrixByCodiceIstat('test1', 'Istat');
		HDT_QR_AtecoMatrix.getAtecoMatrixByCodiceIstat('test1', 'Ronchi');
		
		System.assertEquals('test1', testGetByIstatCode[0].IstatCode__c, 'Ateco Matrix returned is wrong');
		System.assertNotEquals('', testGetByIstatCode[0].IstatCode__c, 'getAtecoMatrixByCodiceIstat did not work correctly');
		
		Test.stopTest();
		
	}

	@IsTest
	static void testGetAtecoMatrixByComuneWhich(){
		
		Test.startTest();

		List<AtecoMatrix__c> testGetByComune=HDT_QR_AtecoMatrix.getAtecoMatrixByComune('RO', 'Istat');
		HDT_QR_AtecoMatrix.getAtecoMatrixByComune('RO', 'Ronchi');

		System.assertEquals('RO', testGetByComune[0].City__c, 'Ateco Matrix returned is wrong');
		System.assertNotEquals('', testGetByComune[0].City__c, 'getAtecoMatrixByComune did not work correctly');

		Test.stopTest();
		
	}
}