force-app/main/default/objects/AtecoMatrix__c/AtecoMatrix__c.object-meta.xml
<CustomObject>
    <description>Oggetto tecnico (matrice) per la gestione dei codici Ateco e relative tipizazioni</description>
    <label>Matrice Ateco</label>
    <nameField>
        <label>Matrice Ateco Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice Ateco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AtecoMatrix__c/fields/AtecoCode__c.field-meta.xml
<CustomField>
    <fullName>AtecoCode__c</fullName>
    <label>Codice Ateco</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Comune</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/IstatCode__c.field-meta.xml
<CustomField>
    <fullName>IstatCode__c</fullName>
    <label>Codice Istat</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>Lista di citta con corrispettivo codice belfiore per il calcolo del codice fiscale</description>
    <label>Città</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Città</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_QR_AtecoMatrix.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 30/06/2021
* @description Class HDT_QR_AtecoMatrix
* @history Keltin Mesonjesi – 30/06/2021 – Created class
*/
public inherited sharing class HDT_QR_AtecoMatrix {

    public static List<AtecoMatrix__c> getAtecoMatrixByComune(String comune){
        return [
            SELECT
            Id,
            Name,
            AtecoCode__c,
            City__c,
            IstatCode__c,
            Category__c
            FROM AtecoMatrix__c
            WHERE
            City__c = :comune
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<AtecoMatrix__c> getAtecoMatrixByCodiceIstat(String codiceIstat){
        return [
            SELECT
            Id,
            Name,
            AtecoCode__c,
            City__c,
            IstatCode__c,
            Category__c
            FROM AtecoMatrix__c
            WHERE
            IstatCode__c = :codiceIstat
            WITH SECURITY_ENFORCED
        ];
    }
}