force-app/main/default/objects/AtecoMatrix__c/AtecoMatrix__c.object-meta.xml
<CustomObject>
    <description>Oggetto tecnico (matrice) per la gestione dei codici Ateco e relative tipizazioni</description>
    <label>Matrice Ateco</label>
    <nameField>
        <label>Matrice Ateco Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice Ateco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AtecoMatrix__c/fields/AtecoCode__c.field-meta.xml
<CustomField>
    <fullName>AtecoCode__c</fullName>
    <label>Codice Ateco</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Comune</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/IstatCode__c.field-meta.xml
<CustomField>
    <fullName>IstatCode__c</fullName>
    <label>Codice Istat</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/RonchiCode__c.field-meta.xml
<CustomField>
    <fullName>RonchiCode__c</fullName>
    <label>Codice Ronchi</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/RonchiDescription__c.field-meta.xml
<CustomField>
    <fullName>RonchiDescription__c</fullName>
    <label>Descrizione Ronchi</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AtecoMatrix__c/fields/RonchiSubcategory__c.field-meta.xml
<CustomField>
    <fullName>RonchiSubcategory__c</fullName>
    <label>Sottocategoria Ronchi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/AtecoCode__c.field-meta.xml
<CustomField>
    <fullName>AtecoCode__c</fullName>
    <description>Combinazione alfanumerica che identifica una ATtività ECOnomica</description>
    <label>Codice Ateco</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RonchiCode__c.field-meta.xml
<CustomField>
    <fullName>RonchiCode__c</fullName>
    <label>Codice Ronchi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RonchiSubcategory__c.field-meta.xml
<CustomField>
    <fullName>RonchiSubcategory__c</fullName>
    <label>Sottocategoria Ronchi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SupplyCityCode__c.field-meta.xml
<CustomField>
    <fullName>SupplyCityCode__c</fullName>
    <label>Codice ISTAT [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>Lista di citta con corrispettivo codice belfiore per il calcolo del codice fiscale</description>
    <label>Città</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Città</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/AtecoCode__c.field-meta.xml
<CustomField>
    <fullName>AtecoCode__c</fullName>
    <description>combinazione alfanumerica che identifica una ATtività ECOnomica</description>
    <label>Codice Comune</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/HerAteco__c.field-meta.xml
<CustomField>
    <fullName>HerAteco__c</fullName>
    <label>Codice Istat/Ateco</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/RonchiCode__c.field-meta.xml
<CustomField>
    <fullName>RonchiCode__c</fullName>
    <label>Codice Ronchi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/RonchiDescription__c.field-meta.xml
<CustomField>
    <fullName>RonchiDescription__c</fullName>
    <label>Descrizione Ronchi</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/RonchiSubcat__c.field-meta.xml
<CustomField>
    <fullName>RonchiSubcat__c</fullName>
    <label>Sottocategoria Ronchi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyCityCode__c.field-meta.xml
<CustomField>
    <fullName>SupplyCityCode__c</fullName>
    <label>Codice ISTAT  [Fornitura]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_LC_CodiceAteco.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 30/06/2021
* @description Class HDT_LC_CodiceAteco
* @history Keltin Mesonjesi – 30/06/2021 – Created class
*/
public inherited sharing class HDT_LC_CodiceAteco {

    private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();
    private static HDT_SRV_Case caseSrv = new HDT_SRV_Case();
    
    @AuraEnabled
    public static List<AtecoMatrix__c> getAtecoMatrixList(String filterType, String filterValue){
        
        List<AtecoMatrix__c> atecoMatrixList = new List<AtecoMatrix__c>();

        switch on filterType {
            when 'City__c' {
                atecoMatrixList = HDT_QR_AtecoMatrix.getAtecoMatrixByComune(filterValue);
            }
            when 'IstatCode__c' {
                atecoMatrixList = HDT_QR_AtecoMatrix.getAtecoMatrixByCodiceIstat(filterValue);
            }
        }

        return atecoMatrixList;

    }

    @AuraEnabled
    public static void saveAtecoCode(Order order, Map<String,String> params){
        orderSrv.updateRecord(new Order(
            Id = order.Id,
            AtecoCode__c = params.get('atecoCode'),
            HerAteco__c = params.get('istatCode')
        ));
    }

    @AuraEnabled
    public static void saveAtecoRonchiCode(Order order, Map<String,String> params){
        orderSrv.updateRecord(new Order(
            Id = order.Id,
            AtecoCode__c = params.get('atecoCode'),
            HerAteco__c = params.get('istatCode'),
            RonchiCode__c = params.get('ronchiCode'),
            RonchiSubcat__c = params.get('ronchiSubcategory'),
            RonchiDescription__c = params.get('ronchiDescription')
        ));
    }

    @AuraEnabled
    public static void saveAtecoRonchiCodeCase(Case caseRecord, Map<String,String> params){
        caseSrv.updateRecord(new Case(
            Id = caseRecord.Id,
            AtecoCode__c = params.get('atecoCode'),
            SupplyCityCode__c = params.get('istatCode'),
            RonchiCode__c = params.get('ronchiCode'),
            RonchiSubcategory__c = params.get('ronchiSubcategory'),
            RonchiDescription__c = params.get('ronchiDescription')
        ));
    }

}