force-app/main/default/objects/SlaAdministration__c/SlaAdministration__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione, dove sono definiti gli SLA ed il relativo contesto di applicazione</description>
    <label>Amministrazione SLA</label>
    <nameField>
        <label>Nome SLA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amministrazione SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SlaAdministration__c/fields/CaseField__c.field-meta.xml
<CustomField>
    <fullName>CaseField__c</fullName>
    <label>Campo case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Inserimento Richiesta</fullName>
            </value>
            <value>
                <fullName>Data Ricezione Richiesta</fullName>
            </value>
            <value>
                <fullName>Data Pagamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Cluster</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Tipo cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Cittadino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrizione SLA</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/EndCasePhase__c.field-meta.xml
<CustomField>
    <fullName>EndCasePhase__c</fullName>
    <label>Fase Case fine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Info da Banca</fullName>
            </value>
            <value>
                <fullName>Avvenuta Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Check preliminari OK</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Da Inviare</fullName>
            </value>
            <value>
                <fullName>Da inviare a SAP</fullName>
            </value>
            <value>
                <fullName>Data Esecuzione Prevista</fullName>
            </value>
            <value>
                <fullName>Elaborazione Manuale</fullName>
            </value>
            <value>
                <fullName>E-Mail Inviata</fullName>
            </value>
            <value>
                <fullName>E-Mail Non Inviata</fullName>
            </value>
            <value>
                <fullName>Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Esito KO Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>Esito OK Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>Esito KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data fine validità</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/OrderField__c.field-meta.xml
<CustomField>
    <fullName>OrderField__c</fullName>
    <label>Campo Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data consenso E-mail PEC Invio Bolletta</fullName>
            </value>
            <value>
                <fullName>Data inizio Validità Codice Destinatario</fullName>
            </value>
            <value>
                <fullName>Data invio richiesta</fullName>
            </value>
            <value>
                <fullName>Data decorrenza</fullName>
            </value>
            <value>
                <fullName>Data differita</fullName>
            </value>
            <value>
                <fullName>Data lettura Attuale</fullName>
            </value>
            <value>
                <fullName>Data lettura retroattiva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Processo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tutti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <label>Intervallo SLA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/SalesCompany__c.field-meta.xml
<CustomField>
    <fullName>SalesCompany__c</fullName>
    <label>Societa di vendita</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/StartCasePhase__c.field-meta.xml
<CustomField>
    <fullName>StartCasePhase__c</fullName>
    <label>Fase Case inizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Info da Banca</fullName>
            </value>
            <value>
                <fullName>Avvenuta Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Check preliminari OK</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Da Inviare</fullName>
            </value>
            <value>
                <fullName>Da inviare a SAP</fullName>
            </value>
            <value>
                <fullName>Data Esecuzione Prevista</fullName>
            </value>
            <value>
                <fullName>Elaborazione Manuale</fullName>
            </value>
            <value>
                <fullName>E-Mail Inviata</fullName>
            </value>
            <value>
                <fullName>E-Mail Non Inviata</fullName>
            </value>
            <value>
                <fullName>Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Esito KO Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>Esito OK Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>Esito KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data inizio validità</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/SlaTracking__c.object-meta.xml
<CustomObject>
    <label>Tracciamento SLA</label>
    <nameField>
        <displayFormat>SLA-{0000}</displayFormat>
        <label>Tracciamento SLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracciamento SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SlaTracking__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>SlaAdministration__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descrizione</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <inlineHelpText>Data effettiva di fine lavorazione</inlineHelpText>
    <label>Data fine intervallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <formula>SlaAdministration__r.Range__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Intervallo SLA indicato nella regola</inlineHelpText>
    <label>Intervallo SLA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/SlaAdministration__c.field-meta.xml
<CustomField>
    <fullName>SlaAdministration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Amministrazione SLA</label>
    <referenceTo>SlaAdministration__c</referenceTo>
    <relationshipLabel>Tracciamento SLA</relationshipLabel>
    <relationshipName>SlaTrackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Data inizio intervallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_Cluster.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento</fullName>
    </customValue>
    <customValue>
        <fullName>Attivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Autolettura</fullName>
    </customValue>
    <customValue>
        <fullName>Canone Rai</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Fatturazione</fullName>
    </customValue>
    <customValue>
        <fullName>Indennizzi</fullName>
    </customValue>
    <customValue>
        <fullName>Informative</fullName>
    </customValue>
    <customValue>
        <fullName>Modifiche Anagrafiche</fullName>
    </customValue>
    <customValue>
        <fullName>Morosità</fullName>
    </customValue>
    <customValue>
        <fullName>Notifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Pagamenti</fullName>
    </customValue>
    <customValue>
        <fullName>PostSales VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Preventivi</fullName>
    </customValue>
    <customValue>
        <fullName>Reclami</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>Variazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Verifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
        <isActive>false</isActive>
        <label>Ambiente</label>
    </customValue>
    <customValue>
        <fullName>Generiche Attivazioni</fullName>
        <isActive>false</isActive>
        <label>Generiche Attivazioni</label>
    </customValue>
    <customValue>
        <fullName>Generiche VAS</fullName>
        <isActive>false</isActive>
        <label>Generiche VAS</label>
    </customValue>
    <customValue>
        <fullName>HERA</fullName>
        <isActive>false</isActive>
        <label>HERA</label>
    </customValue>
    <masterLabel>Cluster</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SalesCompany.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hera Comm Marche</fullName>
    </customValue>
    <customValue>
        <fullName>Acegas Aps Service</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Comm NordEst</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Comm S.p.A.</fullName>
    </customValue>
    <customValue>
        <fullName>EstEnergy S.p.A.</fullName>
    </customValue>
    <customValue>
        <fullName>Marche Multiservizi S.p.A.</fullName>
    </customValue>
    <masterLabel>Societa di vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_TRH_SlaTracking.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public inherited sharing  class HDT_TRH_SlaTracking extends HDT_TRH_TriggerHandler {

    public override void beforeUpdate(){

        List<Id> adminRuleIds = new List<Id>();
        Map<Id, SlaAdministration__c> adminRuleMap;

        for(SlaTracking__c track : (SlaTracking__c[])Trigger.New){
            if(track.StartDateTime__c != null && track.EndDateTime__c != null){
                adminRuleIds.add(track.SlaAdministration__c);
            }
        }

        List<SlaAdministration__c> slaAdminList = [ 
            SELECT Id, CaseField__c, OrderField__c, Cluster__c, CompanyOwner__c, EndDate__c, StartDate__c,
                   Description__c, EndCasePhase__c, StartCasePhase__c, Range__c, Name, Process__c,
                   RecordType.DeveloperName, Commodity__c, SalesCompany__c, CustomerType__c, RangeType__c, Type__c, ActivityType__c,
                   StartOrderPhase__c, EndOrderPhase__c
            FROM SlaAdministration__c
            WHERE Id IN :adminRuleIds
            WITH SECURITY_ENFORCED
        ];

        List<Holiday> holidayList = [
            SELECT Name, ActivityDate
                   //,EndTimeInMinutes, IsAllDay, IsRecurrence, RecurrenceDayOfMonth,
                   //RecurrenceDayOfWeekMask, RecurrenceEndDateOnly, RecurrenceInstance, RecurrenceInterval,
                   //RecurrenceMonthOfYear, RecurrenceStartDate, RecurrenceType, StartTimeInMinutes
            FROM Holiday
            WITH SECURITY_ENFORCED
        ];

        if(slaAdminList.size() > 0){
            adminRuleMap = new Map<Id, SlaAdministration__c>(slaAdminList);
        }

        String rangeType;
        Date startDate;
        Date endDate;
        for(SlaTracking__c track : (SlaTracking__c[])Trigger.New){

            if(track.StartDateTime__c == null || track.EndDateTime__c == null){
                continue;
            }

            startDate = convertDateTime(track.StartDateTime__c);
            endDate = convertDateTime(track.EndDateTime__c);
            track.SlaValue__c = startDate.daysBetween(endDate)+1;

            if(adminRuleMap.containsKey(track.SlaAdministration__c)){
                rangeType = adminRuleMap.get(track.SlaAdministration__c).RangeType__c;
                if(String.isNotEmpty(rangeType) && rangeType.equalsIgnoreCase('Giorni Lavorativi')){
                    track.SlaValue__c = calculateWorkingDays(track.StartDateTime__c, Integer.valueOf(track.SlaValue__c), holidayList);
                }
            }

        }

    }

    public static Integer calculateWorkingDays(DateTime startDateTime, Integer diff, List<Holiday> holidayList){

        Set<String> dayToAvoid = new Set<String>{'Saturday', 'Sunday', 'Sabato', 'Domenica'};
        Set<String> holidays = new Set<String>();

        for(Holiday hDay : holidayList){
            holidays.add(String.valueOf(hDay.ActivityDate.day()) + '-' + String.valueOf(hDay.ActivityDate.month()));//01-01
        }

        String dayOfWeek;
        Integer slaValue = 0;
        DateTime dt;
        Boolean isWeekEnd;
        Boolean isHoliday;
        for(Integer day=0; day<diff; day++){
            dt = startDateTime.addDays(day);
            dayOfWeek = dt.format('EEEE');

            isWeekEnd = dayToAvoid.contains(dayOfWeek);
            isHoliday = holidays.contains(String.valueOf(dt.day()) + '-' + String.valueOf(dt.month()));
            

            if(!isWeekEnd && !isHoliday){
                System.debug('>>> count');
                slaValue++;
            }
            System.debug('>>> date ' + Date.valueOf(dt) + ' - ' + dayOfWeek + ' - slaValue ' + slaValue);
        }
        return slaValue;
    }

    public static Date convertDateTime(DateTime dt){
        //return Date.valueOf(dt);
        return Date.newinstance(dt.year(), dt.month(), dt.day());
    }

}