force-app/main/default/objects/CS_SelezioneFornitura__c/CS_SelezioneFornitura__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CS che contiene le varie parametrizzazioni della capabilities Selezione Fornitura</description>
    <label>SelezioneFornitura</label>
</CustomObject>

force-app/main/default/objects/CS_SelezioneFornitura__c/fields/Max_Record__c.field-meta.xml
<CustomField>
    <fullName>Max_Record__c</fullName>
    <description>Numero massimo di record estraibili dalla ricerca</description>
    <label>Max Record</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CS_SelezioneFornitura__c/fields/OutputServicePoint__c.field-meta.xml
<CustomField>
    <fullName>OutputServicePoint__c</fullName>
    <description>elenco di campi da mostrare a valle della ricerca in caso ti targetObject fornitura</description>
    <label>Output Fornitura</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_LC_AdvancedSearch.cls
public with sharing class HDT_LC_AdvancedSearch {

    private static List<ServicePoint__c> servicePoints;

    /*
	 * Retrieve data from ServicePoint Object By ServiceCode
	 */
    @AuraEnabled(cacheable = true)
    public static List<ServicePoint__c> getServicePointsByName(String code) {
        CS_SelezioneFornitura__c customSetting = getCustomSetting();
        String stringCode = '%' + code.trim() + '%';
        String query = 'SELECT '+ customSetting.OutputServicePoint__c + ' FROM ServicePoint__c WHERE ServicePointCode__c LIKE :stringCode ';
        List<ServicePoint__c> serivePoints =  Database.query(query);
        if(serivePoints.size() > (customSetting.Max_Record__c).intValue()){
            throw new AuraHandledException('Number of record reached Maximum exceeded');
        }
        return serivePoints;
    }

    /*
	 * Getting Custom Settimg  'CS_SelezioneFornitura'
	 */
    static CS_SelezioneFornitura__c getCustomSetting() {
        return [SELECT Max_Record__c,OutputServicePoint__c FROM CS_SelezioneFornitura__c][0];
    }
}