force-app/main/default/objects/AgentMatrix__c/AgentMatrix__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione per recuperare le associazione degli agenti, agenzie e codici associati.</description>
    <label>Matrice Agenti</label>
    <nameField>
        <displayFormat>AM-{00000000}</displayFormat>
        <label>Campo &quot;Name&quot;</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrici Agenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgentMatrix__c/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>Codice Agenzia</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/AgencyName__c.field-meta.xml
<CustomField>
    <fullName>AgencyName__c</fullName>
    <label>Nome Agenzia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/AgentCode__c.field-meta.xml
<CustomField>
    <fullName>AgentCode__c</fullName>
    <label>Codice Agente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/AgentFirstName__c.field-meta.xml
<CustomField>
    <fullName>AgentFirstName__c</fullName>
    <label>Nome Agente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/AgentLastName__c.field-meta.xml
<CustomField>
    <fullName>AgentLastName__c</fullName>
    <label>Cognome Agente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/AreaManager__c.field-meta.xml
<CustomField>
    <fullName>AreaManager__c</fullName>
    <label>Area Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/IsMonitoring__c.field-meta.xml
<CustomField>
    <fullName>IsMonitoring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monitoraggio attivo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/LowerChannelAgency__c.field-meta.xml
<CustomField>
    <fullName>LowerChannelAgency__c</fullName>
    <label>Canale Inferiore Agenzia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGENZIE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BACK OFFICE</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>GDA_ASS</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>id di sistema</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>PA&amp;CO</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>SPORTELLI</fullName>
            </value>
            <value>
                <fullName>SPORTELLI_HCM</fullName>
            </value>
            <value>
                <fullName>SPORTELLI_OUT</fullName>
            </value>
            <value>
                <fullName>SPORTELLI_PH</fullName>
            </value>
            <value>
                <fullName>SPORTELLI_TOP</fullName>
            </value>
            <value>
                <fullName>TLS</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>WEB_SELF</fullName>
            </value>
            <value>
                <fullName>AGENZIE BUSINESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/UpperChannelAgency__c.field-meta.xml
<CustomField>
    <fullName>UpperChannelAgency__c</fullName>
    <label>Canale Superiore Agenzia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>id di sistema</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>PA&amp;CO</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agenzia Teleseller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Ecid__c.field-meta.xml
<CustomField>
    <fullName>ECID__c</fullName>
    <label>ECID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>Codice Agenzia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/CommercialId__c.field-meta.xml
<CustomField>
    <fullName>CommercialId__c</fullName>
    <label>Venduto Da</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/CommissioningCampaign__c.field-meta.xml
<CustomField>
    <fullName>CommissioningCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campagna Commissioning</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Vendite (Campagna Commissioning)</relationshipLabel>
    <relationshipName>ComissioningSales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/Ecid__c.field-meta.xml
<CustomField>
    <fullName>Ecid__c</fullName>
    <label>Ecid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/IsMonitoring__c.field-meta.xml
<CustomField>
    <fullName>IsMonitoring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monitoraggio Attivo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/LowerChannelAgency__c.field-meta.xml
<CustomField>
    <fullName>LowerChannelAgency__c</fullName>
    <label>Canale Inferiore Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/SalesContact__c.field-meta.xml
<CustomField>
    <fullName>SalesContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contatto Vendita</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vendite</relationshipLabel>
    <relationshipName>Vendite</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/UpperChannelAgency__c.field-meta.xml
<CustomField>
    <fullName>UpperChannelAgency__c</fullName>
    <label>Canale Superiore Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/VendorFirstName__c.field-meta.xml
<CustomField>
    <fullName>VendorFirstName__c</fullName>
    <label>Nome Venditore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/VendorLastName__c.field-meta.xml
<CustomField>
    <fullName>VendorLastName__c</fullName>
    <label>Cognome Venditore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/LoginChannel__c.field-meta.xml
<CustomField>
    <fullName>LoginChannel__c</fullName>
    <description>Indica il canale di riferimento dell&apos;utente</description>
    <label>Canale Login</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetName>HDT_LoginChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Ecid__c.field-meta.xml
<CustomField>
    <fullName>Ecid__c</fullName>
    <externalId>true</externalId>
    <label>Ecid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/LoginChannel__c.field-meta.xml
<CustomField>
    <fullName>LoginChannel__c</fullName>
    <label>Canale di Vendita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_LoginChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Assistente web</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Callback</fullName>
    </customValue>
    <customValue>
        <fullName>Camper</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
    </customValue>
    <customValue>
        <fullName>Da PGM</fullName>
    </customValue>
    <customValue>
        <fullName>HC_WEB</fullName>
    </customValue>
    <customValue>
        <fullName>Helpdesk</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <customValue>
        <fullName>Protocollo</fullName>
    </customValue>
    <customValue>
        <fullName>ServiziSociali</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SOL</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Supporto agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Supporto GDA</fullName>
    </customValue>
    <customValue>
        <fullName>Telefono Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Telefono Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Business</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita MM</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <description>Canale login dell&apos;utente</description>
    <masterLabel>Canale Login</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_GeneralInfo.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 11/11/2020
* @description Apex controller for hdtGeneralInfo.js component
* @history Keltin Mesonjesi – 11/11/2020 – Created class
*/

public inherited sharing class HDT_LC_GeneralInfo {

    private static HDT_SRV_Sale saleSrv = new HDT_SRV_Sale();
    private static HDT_QR_AccountContactRelation accoContRelQr = new HDT_QR_AccountContactRelation();
    private static HDT_SRV_AccountContactRelation accoContRelSrv = new HDT_SRV_AccountContactRelation();
    private static HDT_QR_CampaignMember campMembQr = new HDT_QR_CampaignMember();

    
    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Update Sale
     * @param Sale__c sale
     */
    @AuraEnabled
    public static void updateSale(Sale__c sale){
        try{

            List<wrts_prcgvr__Activity__c> listActi = HDT_QR_ActivityCustom.getActivityTelesellingOutboundByUser();
            if (listActi != null && !listActi.isEmpty()) {
                sale.Ecid__c = listActi[0].Ecid__c;
            }
            
        }catch(exception e){
            system.debug('***********' + e);
        }

        if(sale.SalesContact__c != null)
        {
            List<Contact> salesCon = [SELECT Phone, MobilePhone, Email FROM Contact WHERE Id = :sale.SalesContact__c WITH SECURITY_ENFORCED];
            if(!salesCon.isEmpty() && salesCon[0].Phone == null && salesCon[0].MobilePhone == null && salesCon[0].Email == null)
            {
                throw new AuraHandledException('Il contatto selezionato non dispone di alcun tipo di recapito. Aggiornare il contatto o selezionarne uno differente');
            }
        }

        saleSrv.updateRecord(sale);
        
        //if(sale.CommissioningCampaign__c != null){
          //  List<CampaignMember> campMembList = campMembQr.getCampaignMemberByCampaingAndContact(sale.CommissioningCampaign__c, sale.SalesContact__c);
            
           // if (!campMembList.isEmpty()) {
           //     sale.Ecid__c = campMembList[0].Ecid__c;
          //  }
        //}
    }
    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Get current username
     * @return String username
     */
    @AuraEnabled
    public static String getCurrentUserName(){
        String userName = UserInfo.getName();
        return userName;
    }

    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Get "Ruolo Contrattuale"
     * @param String accountId
     * @param String contactId
     * @return List<AccountContactRelation>
     */
    @AuraEnabled
    public static List<AccountContactRelation> getSaleContactRole(String accountId, String contactId){

        accoContRelSrv.checkReadAccess('Roles');
        return accoContRelQr.getRecordsFilteredByAccountAndContact(accountId, contactId);
    }

    @AuraEnabled
    public static List<AgentMatrix__c> getChannelAgency(String Channel){
        System.debug('test');
        Map<String,AgentMatrix__c> distinctAgency= new Map <String,AgentMatrix__c>();
        List<AgentMatrix__c> agentList = new List<AgentMatrix__c>();
        if('Back office'.equalsIgnoreCase(Channel)){
            agentList=HDT_QR_AgentMatrix.getAllRecords();
        }else{
            agentList=HDT_QR_AgentMatrix.getRecordsByChannel(Channel);
        }

        for (AgentMatrix__c agent : agentList) {
            distinctAgency.put((String)agent.AgencyName__c,agent);
        }
        agentList = distinctAgency.values();

        return agentList;
    }

    @AuraEnabled
    public static List<AgentMatrix__c> getAgents(String AgencyName, String Channel){
        System.debug('test');
        // Id userId=UserInfo.getUserId();

        List<AgentMatrix__c> agentList = new List<AgentMatrix__c>();

        if(Channel == 'Back office') {
            agentList = HDT_QR_AgentMatrix.getRecordByAgencyName(AgencyName);
        } else {
            agentList = HDT_QR_AgentMatrix.getRecordByAgencyNameAndChannel(AgencyName, Channel);
        }

        System.debug(agentList);
          return agentList;

          
    }
    @AuraEnabled
    public static List<AgentMatrix__c> handleAutomaticAgentAssign(String Channel,String saleId){
    List<AgentMatrix__c> agentList = HDT_QR_AgentMatrix.getAgentByUserNameAndChannel(UserInfo.getUserName(),Channel);
    System.debug('username '+UserInfo.getUserName());
    System.debug('Channel '+Channel);
    System.debug('agentList '+agentList);
    if(agentList.size()==0){
        throw new AuraHandledException('Per la tua utenza e per il canale selezionato non è censito un Id Commerciale. Selezionane uno tramite il tasto Seleziona Agenzia');
    }




    AgentMatrix__c agent = agentList[0];
    saleSrv.updateRecord(new Sale__c(
        Id = saleId,
        Agency__c = agent.AgencyName__c,
        AgencyCode__c = agent.AgencyCode__c,
        VendorLastName__c = agent.AgentLastName__c,
        VendorFirstName__c = agent.AgentFirstName__c,
        CommercialId__c = agent.AgentCode__c,
        UpperChannelAgency__c = agent.UpperChannelAgency__c,
        LowerChannelAgency__c = agent.LowerChannelAgency__c,
        IsMonitoring__c = agent.IsMonitoring__c,
        AreaManager__c = agent.AreaManager__c
    ));

    return agentList;

    }

    @AuraEnabled
    public static Map<String,String> initComp(){

        Map<String,String> result = new Map<String,String>();

        List<User> user = HDT_QR_UserQueries.getRoleAndProfile(UserInfo.getUserId());
        if(!user.isEmpty() && String.isNotBlank(user[0].LoginChannel__c))
        {
            result.put('loginchannel',user[0].LoginChannel__c);
        }
        if (user[0].UserRole != null) {
            result.put('userRole', user[0].UserRole.DeveloperName);
            result.put('userProfile', user[0].Profile.Name);
        }

        return result;
    }

}