force-app/main/default/objects/AgentMatrix__c/AgentMatrix__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione per recuperare le associazione degli agenti, agenzie e codici associati.</description>
    <label>Matrice Agenti</label>
    <nameField>
        <displayFormat>AM-{00000000}</displayFormat>
        <label>Campo &quot;Name&quot;</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrici Agenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgentMatrix__c/fields/AgencyName__c.field-meta.xml
<CustomField>
    <fullName>AgencyName__c</fullName>
    <label>Nome Agenzia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefono</fullName>
            </value>
            <value>
                <fullName>Back office</fullName>
            </value>
            <value>
                <fullName>Sportello</fullName>
            </value>
            <value>
                <fullName>HC Point</fullName>
            </value>
            <value>
                <fullName>Vendita Condomini</fullName>
            </value>
            <value>
                <fullName>Vendita TopBusiness</fullName>
            </value>
            <value>
                <fullName>Business Agent</fullName>
            </value>
            <value>
                <fullName>Agenzie SME</fullName>
            </value>
            <value>
                <fullName>Agenzie</fullName>
            </value>
            <value>
                <fullName>Punti Hera</fullName>
            </value>
            <value>
                <fullName>Teleselling Inbound</fullName>
            </value>
            <value>
                <fullName>Teleselling Outbound</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Consip</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Associazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgentMatrix__c/fields/UserIdentification__c.field-meta.xml
<CustomField>
    <fullName>UserIdentification__c</fullName>
    <label>Identificativo Utente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Silos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SalesChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>HC Point</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie SME</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Punti Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
        <isActive>false</isActive>
        <label>Consip</label>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <isActive>false</isActive>
        <label>Reseller</label>
    </customValue>
    <description>Canale vendita associato all&apos;utente</description>
    <masterLabel>Canale Vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_SoldByTst.cls
/**
 * @author Sabina Levonja (sabina.levonja@dunegroup.it)
 * @date 13/10/2021
 * @description HDT_LC_SoldBy Test Class
 * @history Sabina Levonja – 13/10/2021 – Created Class
 */
@isTest
public with sharing class HDT_LC_SoldByTst {
    @TestSetup
    static void setup(){
        
    	List<AgentMatrix__c> agentList= HDT_UTL_DataFactoryTst.createAgentMatrix(1,false,'Telefono');
        agentList[0].UserIdentification__c= UserInfo.getUserName();
        agentList[0].AgencyName__c='Test';
        insert agentList;
        HDT_UTL_DataFactoryTst.createLead(1,true);

	}
    @isTest
    public static void testGetLeadInfo() {

        Test.startTest();
			Lead l=[Select Id from Lead limit 1];
        	Lead res= HDT_LC_SoldBy.getLeadInfo(l.Id);
        Test.stopTest();

        System.assertNotEquals(null, res,'The lead has not been found');
    }
    
    @isTest
    public static void testHandleAutomaticAgentAssign() {

        Test.startTest();
        	AgentMatrix__c ag= [Select Id,Channel__c From AgentMatrix__c limit 1];
			Lead l=[Select Id from Lead limit 1];
        	HDT_LC_SoldBy.handleAutomaticAgentAssign(ag.Channel__c,l.Id);
        Test.stopTest();

		Lead lead= [Select Id, Channel__c from Lead limit 1];
        System.assertEquals(ag.Channel__c, lead.Channel__c,'The Channel__c field has not been updated');
        System.assertNotEquals(null, lead.Channel__c,'The lead has not been updated');
    }
    @isTest
    public static void testUpdateLead() {

        Test.startTest();
			Lead l=[Select Id,LastName,CompanyOwner__c from Lead limit 1];
        	l.Lastname='Test';
        	l.CompanyOwner__c='Reseller';
        	HDT_LC_SoldBy.updateLead(l);
        Test.stopTest();
        
		Lead lead = [Select Id,LastName,CompanyOwner__c from Lead limit 1];
        System.assertEquals(l.Lastname, lead.LastName,'The Lastname field has not been updated');
        System.assertNotEquals(false, lead.CompanyOwner__c == l.CompanyOwner__c,'The CompanyOwner__c field has not been updated');
    }
    @isTest
    public static void testGetChannelAgency() {

        Test.startTest();
        	AgentMatrix__c ag= [Select Id,Channel__c,AgencyName__c From AgentMatrix__c limit 1];
        	List<AgentMatrix__c> resp= HDT_LC_SoldBy.getChannelAgency(ag.Channel__c);
        Test.stopTest();

        System.assertEquals(ag.AgencyName__c, resp[0].AgencyName__c,'The agent has not been found');
        System.assertNotEquals(true, resp.isEmpty(),'The AgentMatrix__c list is empty');
    }
    
    @isTest
    public static void testGetAgents() {

        Test.startTest();
        	AgentMatrix__c ag= [Select Id,Channel__c,AgencyName__c From AgentMatrix__c limit 1];
        	List<AgentMatrix__c> resp= HDT_LC_SoldBy.getAgents(ag.AgencyName__c,ag.Channel__c);
        Test.stopTest();

        System.assertEquals(ag.AgencyName__c, resp[0].AgencyName__c,'The agent has not been found');
        System.assertNotEquals(true, resp.isEmpty(),'The AgentMatrix__c list is empty');
    }
}