force-app/main/default/objects/Order/fields/AdministrativeBurden__c.field-meta.xml
<CustomField>
    <fullName>AdministrativeBurden__c</fullName>
    <label>Onere Amministrativo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/AutorizationVolturaThirdTrader__c.field-meta.xml
<CustomField>
    <fullName>AutorizationVolturaThirdTrader__c</fullName>
    <label>Modulo Autorizzazione Voltura c/o VT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>CancellationReason__c</fullName>
    <label>Causale Annullamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CancellationReason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ChamberCommerceRegistration__c.field-meta.xml
<CustomField>
    <fullName>ChamberCommerceRegistration__c</fullName>
    <label>Visura camerale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CIAccoutn__c.field-meta.xml
<CustomField>
    <fullName>CIAccoutn__c</fullName>
    <label>Carta d&apos;identità Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ContractSigned__c.field-meta.xml
<CustomField>
    <fullName>ContractSigned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag che indica se esiste gia il contratto firmato</description>
    <label>Contratto Firmato</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>DocSendingMethod__c</fullName>
    <label>Modalita Invio Doc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Posta</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Stampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentLow80__c.field-meta.xml
<CustomField>
    <fullName>DocumentLow80__c</fullName>
    <label>Documento Legge 80</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/EstimateAmount__c.field-meta.xml
<CustomField>
    <fullName>EstimateAmount__c</fullName>
    <label>Importo Preventivo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/EstimatedVAT__c.field-meta.xml
<CustomField>
    <fullName>EstimatedVAT__c</fullName>
    <label>Iva Preventivo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Instance326__c.field-meta.xml
<CustomField>
    <fullName>Instance326__c</fullName>
    <label>Istanza 326</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Comunicazione Motore VAS</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku</fullName>
            </value>
            <value>
                <fullName>Quality Call OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PowerQuote__c.field-meta.xml
<CustomField>
    <fullName>PowerQuote__c</fullName>
    <label>Quote Potenza</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/QuickQuote__c.field-meta.xml
<CustomField>
    <fullName>QuickQuote__c</fullName>
    <label>Preventivo Rapido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SignatureMethod__c.field-meta.xml
<CustomField>
    <fullName>SignatureMethod__c</fullName>
    <label>Metodo Firma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vocal Order</fullName>
            </value>
            <value>
                <fullName>OTP Remoto</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
            </value>
            <value>
                <fullName>OTP Coopresenza</fullName>
            </value>
            <value>
                <fullName>Contratto già firmato</fullName>
            </value>
            <value>
                <fullName>Accettato Digitalmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SignedDate__c.field-meta.xml
<CustomField>
    <fullName>SignedDate__c</fullName>
    <description>In caso di contratto esiste, la data in cui è stato firmato</description>
    <label>Data Firma</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ValidityDateEstimate__c.field-meta.xml
<CustomField>
    <fullName>ValidityDateEstimate__c</fullName>
    <label>Data Validita Preventivo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_CambioOfferta.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_CambioOfferta</fullName>
    <active>true</active>
    <label>Cambio Offerta</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_OrderDossier.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_OrderDossier</fullName>
    <active>true</active>
    <description>Record Type Ordine Padre</description>
    <label>Order Dossier</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_SwitchIn.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_SwitchIn</fullName>
    <active>true</active>
    <description>Record type per gli ordini di SwitchIn</description>
    <label>SwitchIn</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VAS.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VAS</fullName>
    <active>true</active>
    <label>VAS</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/OrderItem/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Details con l&apos;oggetto account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendite</relationshipLabel>
    <relationshipName>Vendite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>CancellationReason__c</fullName>
    <label>Causale Annullamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CancellationReason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account del titolare del punto di fornitura</description>
    <label>Account Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points (Account)</relationshipLabel>
    <relationshipName>Service_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OrderID</description>
    <label>Order Correlato</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <formula>IF(NOT(ISNULL(Case__c)), TEXT(Case__r.Phase__c), IF(NOT(ISNULL(Order__c)), TEXT(Order__r.Phase__c), &quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>POD/PDR</description>
    <label>POD/PDR</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CancellationReason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Classificazione errata</fullName>
    </customValue>
    <customValue>
        <fullName>Codice ABI obsoleto</fullName>
    </customValue>
    <customValue>
        <fullName>Contattare banca</fullName>
    </customValue>
    <customValue>
        <fullName>Contatto Quality Fallito</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazione in corso</fullName>
    </customValue>
    <customValue>
        <fullName>Domiciliazione già presente</fullName>
    </customValue>
    <customValue>
        <fullName>Firma falsa</fullName>
    </customValue>
    <customValue>
        <fullName>Mancanza titolarità</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-ricezione</fullName>
    </customValue>
    <customValue>
        <fullName>No conferma Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>PDR/POD errato</fullName>
    </customValue>
    <customValue>
        <fullName>Pratica errata</fullName>
    </customValue>
    <customValue>
        <fullName>Processo incompatibile</fullName>
    </customValue>
    <customValue>
        <fullName>Quality - Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 14.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 6.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 8.2 del TIMG</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente oltre i termini</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento tramite quality call</fullName>
    </customValue>
    <customValue>
        <fullName>Sollecito</fullName>
    </customValue>
    <customValue>
        <fullName>Volontà estorta</fullName>
    </customValue>
    <customValue>
        <fullName>Gestione Scarto</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per no conferma cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per possibile frode</fullName>
    </customValue>
    <customValue>
        <fullName>Il cliente rinuncia</fullName>
    </customValue>
    <customValue>
        <fullName>Rifiutato Preventivamente</fullName>
    </customValue>
    <masterLabel>Motivazione Annullamento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_DocuementValidation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Richiesto</fullName>
    </customValue>
    <customValue>
        <fullName>Validato</fullName>
    </customValue>
    <customValue>
        <fullName>Non Validato</fullName>
    </customValue>
    <customValue>
        <fullName>Sollecitato</fullName>
    </customValue>
    <masterLabel>Document Validation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_OrdersForComfortQualityListTst.cls
/**
 * @author Valere (valere@noeli-it.net)
 * @date 20/09/2021
 * @description HDT_UTL_OrderProcessAssignment Test Classes
 * @history valere - 20/09/2021– Created Class
 */


 
@isTest
private class HDT_LC_OrdersForComfortQualityListTst {

  public static List<Order> createOrderWithPricebookWithPhase(Integer amount, Boolean doInsert, List<Sale__c> sales, Map<String,Object> params){

		List<Order> orderList=new List<Order>();

		for (Integer i=0; i<amount; i++){

			Order ord=new Order();

			ord.Name='testOrderName'+i;
			ord.Status='Draft';
			ord.EffectiveDate=Date.today();
			ord.AccountId=(String)params.get('AccountId');
			ord.EstimateAmount__c=1000;
			ord.PowerQuote__c=1000;
			ord.AdministrativeBurden__c=1;
			ord.EstimatedVAT__c=1;
			ord.ValidityDateEstimate__c=Date.today().addDays(30);
			ord.Phase__c='Bozza';
			ord.CIAccoutn__c='Richiesto';
			ord.QuickQuote__c='Richiesto';
			ord.ChamberCommerceRegistration__c='Richiesto';
			ord.Instance326__c='Richiesto';
			ord.DocumentLow80__c='Richiesto';
			ord.AutorizationVolturaThirdTrader__c='Richiesto';
			ord.ContractSigned__c=true;
			ord.SignedDate__c=Date.today();
			ord.SignatureMethod__c='Vocal Order';
			ord.DocSendingMethod__c='E-mail';
			ord.Sale__c=sales[i].Id;
			ord.Pricebook2Id=(String)params.get('Pricebook2Id');
			ord.Phase__c=(String)params.get('Phase__c');
			ord.RecordTypeId=(String)params.get('RecordTypeId');

			orderList.add(ord);
		}

		if (doInsert){

			insert orderList;
		}

		return orderList;
	}

  
    public static List<wrts_prcgvr__Activity__c> createActivityCustom(Integer amount, Boolean doInsert, Id accId,Map<String,Object> params){

		List<wrts_prcgvr__Activity__c> activityCustomList=new List<wrts_prcgvr__Activity__c>();
    
		for (Integer i=0; i<amount; i++){

			wrts_prcgvr__Activity__c actCustom=new wrts_prcgvr__Activity__c();

			actCustom.Account__c=accId;
      actCustom.Order__c=(String)params.get('orderId');


			activityCustomList.add(actCustom);
		}

		if (doInsert){

			insert activityCustomList;
		}

		return activityCustomList;
	}


    @testSetup 
  static void setup() {
    //Id hDT_RT_OrderDossier_RecordTypeId= [select Id, DeveloperName from RecordType Where DeveloperName='HDT_RT_OrderDossier' LIMIT 1].Id;
    Id hDT_RT_VAS_RecordTypeId= [select Id, DeveloperName from RecordType Where DeveloperName='HDT_RT_VAS' LIMIT 1].Id;
    Id hDT_RT_CambioOfferta_RecordTypeId= [select Id, DeveloperName from RecordType Where DeveloperName='HDT_RT_CambioOfferta' LIMIT 1].Id;
    Id hDT_RT_SwitchIn_RecordTypeId= [select Id, DeveloperName from RecordType Where DeveloperName='HDT_RT_SwitchIn' LIMIT 1].Id;
    HDT_UTL_DataFactoryTst.pClickInstance();
    HDT_UTL_DataFactoryTst.pClickOrderPhase();    
    List<Account> accountList= HDT_UTL_DataFactoryTst.createAccountResidenziale(1,true,'HERA COMM','Persona fisica','Famiglie');

    //Instantiate the Pricebook2 record with StandardPricebookId
    Pricebook2 standardPricebook = new Pricebook2(
              Id = Test.getStandardPricebookId(),
              IsActive = true
    );
    Update standardPricebook;

    List<Sale__c> salesList= HDT_UTL_DataFactoryTst.createSale(4, true, accountList[0].id, 'Bozza');

    List<Order> orderList0= createOrderWithPricebookWithPhase(1, true, salesList,new Map<String,Object>{
      'AccountId'=>accountList[0].id,
      'Pricebook2Id'=>standardPricebook.id,
      'Phase__c'=>'Annullato',
      'RecordTypeId'=>null
  } ); 
  List<Order> orderList1= createOrderWithPricebookWithPhase(1, true, salesList,new Map<String,Object>{
    'AccountId'=>accountList[0].id,
    'Pricebook2Id'=>standardPricebook.id,
    'Phase__c'=>'Comunicazione Motore VAS',
    'RecordTypeId'=>hDT_RT_VAS_RecordTypeId
} ); 
List<Order> orderList2= createOrderWithPricebookWithPhase(1, true, salesList,new Map<String,Object>{
  'AccountId'=>accountList[0].id,
  'Pricebook2Id'=>standardPricebook.id,
  'Phase__c'=>'Comunicazione verso Heroku',
  'RecordTypeId'=>hDT_RT_CambioOfferta_RecordTypeId
} );
List<Order> orderList3= createOrderWithPricebookWithPhase(1, true, salesList,new Map<String,Object>{
  'AccountId'=>accountList[0].id,
  'Pricebook2Id'=>standardPricebook.id,
  'Phase__c'=>'Comunicazione verso Heroku',
  'RecordTypeId'=>hDT_RT_SwitchIn_RecordTypeId
} );    
    //orderList[0].RecordTypeId=hDT_RT_OrderDossier_RecordTypeId;
    // orderList[0].Phase__c='Annullato';
    // orderList[1].RecordTypeId=hDT_RT_VAS_RecordTypeId;
    // orderList[1].Phase__c='Comunicazione Motore VAS';
    // orderList[2].RecordTypeId=hDT_RT_CambioOfferta_RecordTypeId;
    // orderList[2].Phase__c='Comunicazione verso Heroku';
    // orderList[3].RecordTypeId=hDT_RT_SwitchIn_RecordTypeId;
    // orderList[3].Phase__c='Comunicazione verso Heroku';
    // insert orderList;
    //List<Order> orderList= HDT_UTL_DataFactoryTst.createOrder(1, true, accountList[0].id,'Bozza');
    List<wrts_prcgvr__Activity__c> activity0=createActivityCustom(1, true,accountList[0].id,new Map<String,Object>{
        'orderId'=> orderList0[0].id
    });
    List<wrts_prcgvr__Activity__c> activity1=createActivityCustom(1, true,accountList[0].id,new Map<String,Object>{
      'orderId'=> orderList1[0].id
    });
    List<wrts_prcgvr__Activity__c> activity2=createActivityCustom(1, true,accountList[0].id,new Map<String,Object>{
      'orderId'=> orderList2[0].id
    });
    List<wrts_prcgvr__Activity__c> activity3=createActivityCustom(1, true,accountList[0].id,new Map<String,Object>{
      'orderId'=> orderList3[0].id
    });
    List<ServicePoint__c>  servicePoint=  HDT_UTL_DataFactoryTst.createServicePoint(1, true);
    List<Product2> Product2List = HDT_UTL_DataFactoryTst.createProduct2(1, true);
    List<PricebookEntry> pricebookentryList= HDT_UTL_DataFactoryTst.createPricebookEntry(Product2List, true, standardPricebook.Id);
    List<OrderItem> orderItem= HDT_UTL_DataFactoryTst.createOrderItem(1, true, orderList0[0].id, servicePoint[0].id, Product2List[0].Id, pricebookentryList[0].id);

    
       
   
}
    
  @isTest
  static void testGetTableData() {

    Order order=[SELECT id,CancellationReason__c,Status,Phase__c FROM Order WHERE Phase__c='Annullato' LIMIT 1];

    List<wrts_prcgvr__Activity__c> activity= [SELECT id,Order__r.RecordType.DeveloperName 
                                              FROM wrts_prcgvr__Activity__c
                                              WHERE Order__c=:order.id];
    
    List<wrts_prcgvr__Activity__c> acts = HDT_LC_OrdersForComfortQualityList.getTableData(activity[0].id);
    //System.assertEquals(1, acts.size());
    System.assertEquals(acts[0].id, activity[0].id,'The value is the same by entering in the else');
    System.assertNotEquals('HDT_RT_OrderDossier', acts[0].Order__r.RecordType.DeveloperName,'The value is the same by entering in the else');

  }


  @isTest
  static void testConfirmContract() {

    Order order=[SELECT id,ConfirmCustomerContract__c,Phase__c FROM Order WHERE Phase__c='Annullato' LIMIT 1];

    List<wrts_prcgvr__Activity__c> activity= [SELECT id,Order__r.RecordType.DeveloperName,Status__c 
                                              FROM wrts_prcgvr__Activity__c
                                              WHERE Order__c=:order.id];


    
                                          
    HDT_LC_OrdersForComfortQualityList.confirmContract( order.id, activity[0].id , 'ComfortNo');

    //System.assertEquals(1, acts.size());
    System.assertEquals(true, [SELECT Id, Status__c, ContactResult__c FROM wrts_prcgvr__Activity__c WHERE ContactResult__c = 'Quality Call OK'].size()>0,'An wrts_prcgvr__Activity__c is created');
    System.assertNotEquals(false, [SELECT Id, Phase__c FROM Order WHERE Phase__c = 'Annullato'].size()>0,'An Order is created');

  }


  @isTest
  static void testConfirmContractWithHDT_RT_VAS() {

    Order order=[SELECT id,ConfirmCustomerContract__c,Phase__c FROM Order WHERE RecordType.DeveloperName='HDT_RT_VAS' LIMIT 1];

    List<wrts_prcgvr__Activity__c> activity= [SELECT id,Order__r.RecordType.DeveloperName,Status__c 
                                              FROM wrts_prcgvr__Activity__c
                                              WHERE Order__c=:order.id];


    
                                          
    HDT_LC_OrdersForComfortQualityList.confirmContract( order.id, activity[0].id , 'Comfort');

    //System.assertEquals(1, acts.size());
    System.assertEquals(true, [SELECT Id, Status__c, ContactResult__c FROM wrts_prcgvr__Activity__c WHERE ContactResult__c = ''].size()>0,'An wrts_prcgvr__Activity__c is created');
    System.assertNotEquals(false, [SELECT Id, Phase__c FROM Order WHERE Phase__c = 'Comunicazione Motore VAS'].size()>0,'An Order is created');

  }

  @isTest
  static void testConfirmContractWithHDT_RT_CambioOfferta() {

    Order order=[SELECT id,ConfirmCustomerContract__c,Phase__c FROM Order WHERE RecordType.DeveloperName='HDT_RT_CambioOfferta' LIMIT 1];

    List<wrts_prcgvr__Activity__c> activity= [SELECT id,Order__r.RecordType.DeveloperName,Status__c 
                                              FROM wrts_prcgvr__Activity__c
                                              WHERE Order__c=:order.id];


    
                                          
    HDT_LC_OrdersForComfortQualityList.confirmContract( order.id, activity[0].id , 'Comfort');

    //System.assertEquals(1, acts.size());
    System.assertEquals(true, [SELECT Id, Status__c, ContactResult__c FROM wrts_prcgvr__Activity__c WHERE ContactResult__c = ''].size()>0,'An wrts_prcgvr__Activity__c is created');
    System.assertNotEquals(false, [SELECT Id, Phase__c FROM Order WHERE Phase__c = 'Comunicazione verso Heroku'].size()>0,'An Order is created');

  }

  @isTest
  static void testConfirmContractWithHDT_RT_SwitchIn() {

    Order order=[SELECT id,ConfirmCustomerContract__c,Phase__c FROM Order WHERE RecordType.DeveloperName='HDT_RT_SwitchIn' LIMIT 1];

    List<wrts_prcgvr__Activity__c> activity= [SELECT id,Order__r.RecordType.DeveloperName,Status__c 
                                              FROM wrts_prcgvr__Activity__c
                                              WHERE Order__c=:order.id];


    
                                          
    HDT_LC_OrdersForComfortQualityList.confirmContract( order.id, activity[0].id , 'Comfort');

    //System.assertEquals(1, acts.size());
    System.assertEquals(true, [SELECT Id, Status__c, ContactResult__c FROM wrts_prcgvr__Activity__c WHERE ContactResult__c = ''].size()>0,'An wrts_prcgvr__Activity__c is created');
    System.assertNotEquals(false, [SELECT Id, Phase__c FROM Order WHERE Phase__c = 'Comunicazione verso Heroku'].size()>0,'An Order is created');

  }

  @isTest
  static void testCancelContract() {

    Order order=[SELECT id FROM Order WHERE Phase__c='Annullato' LIMIT 1];

    List<wrts_prcgvr__Activity__c> activity= [SELECT id,Order__r.RecordType.DeveloperName 
                                              FROM wrts_prcgvr__Activity__c
                                              WHERE Order__c=:order.id];
    
    HDT_LC_OrdersForComfortQualityList.cancelContract( order.id, activity[0].id , 'Annullo voltura');
    
    //System.assertEquals(1, acts.size());
    System.assertEquals(true, [SELECT Id, Status__c, ContactResult__c FROM wrts_prcgvr__Activity__c WHERE ContactResult__c = 'Annullato'].size()>0,'An wrts_prcgvr__Activity__c is created');
    System.assertNotEquals(false, [SELECT Id, Phase__c,Status FROM Order WHERE Status = 'Activated'].size()>0,'An Order is created');

  }
 
 

  


}