force-app/main/default/objects/Order/fields/AutorizationVolturaThirdTrader__c.field-meta.xml
<CustomField>
    <fullName>AutorizationVolturaThirdTrader__c</fullName>
    <label>Modulo Autorizzazione Voltura c/o VT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>CancellationReason__c</fullName>
    <label>Causale Annullamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CancellationReason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ChamberCommerceRegistration__c.field-meta.xml
<CustomField>
    <fullName>ChamberCommerceRegistration__c</fullName>
    <label>Visura camerale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CIAccoutn__c.field-meta.xml
<CustomField>
    <fullName>CIAccoutn__c</fullName>
    <label>Carta d&apos;identità Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CILegalRepresentative__c.field-meta.xml
<CustomField>
    <fullName>CILegalRepresentative__c</fullName>
    <label>Carta d&apos;identità Rap. Legale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ContractSigned__c.field-meta.xml
<CustomField>
    <fullName>ContractSigned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag che indica se esiste gia il contratto firmato</description>
    <label>Contratto Firmato</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentLow80__c.field-meta.xml
<CustomField>
    <fullName>DocumentLow80__c</fullName>
    <label>Documento Legge 80</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Instance326__c.field-meta.xml
<CustomField>
    <fullName>Instance326__c</fullName>
    <label>Istanza 326</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Documentazione Validata</fullName>
            </value>
            <value>
                <fullName>In attesa validazione</fullName>
            </value>
            <value>
                <fullName>Plico da inviare</fullName>
            </value>
            <value>
                <fullName>Plico Firmato da validare</fullName>
            </value>
            <value>
                <fullName>Plico inviato da validare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/QuickQuote__c.field-meta.xml
<CustomField>
    <fullName>QuickQuote__c</fullName>
    <label>Preventivo Rapido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <description>Campo per gestire gli step nel wizard</description>
    <label>Step</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_Voltura.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Voltura</fullName>
    <active>true</active>
    <description>Record Type per processo di Voltura</description>
    <label>Voltura</label>
    </picklistValues>
</RecordType>

force-app/main/default/globalValueSets/HDT_CancellationReason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Classificazione errata</fullName>
    </customValue>
    <customValue>
        <fullName>Codice ABI obsoleto</fullName>
    </customValue>
    <customValue>
        <fullName>Contattare banca</fullName>
    </customValue>
    <customValue>
        <fullName>Contatto Quality Fallito</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazione in corso</fullName>
    </customValue>
    <customValue>
        <fullName>Domiciliazione già presente</fullName>
    </customValue>
    <customValue>
        <fullName>Firma falsa</fullName>
    </customValue>
    <customValue>
        <fullName>Mancanza titolarità</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-ricezione</fullName>
    </customValue>
    <customValue>
        <fullName>No conferma Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>PDR/POD errato</fullName>
    </customValue>
    <customValue>
        <fullName>Pratica errata</fullName>
    </customValue>
    <customValue>
        <fullName>Processo incompatibile</fullName>
    </customValue>
    <customValue>
        <fullName>Quality - Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 14.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 6.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 8.2 del TIMG</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente oltre i termini</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento tramite quality call</fullName>
    </customValue>
    <customValue>
        <fullName>Sollecito</fullName>
    </customValue>
    <customValue>
        <fullName>Volontà estorta</fullName>
    </customValue>
    <customValue>
        <fullName>Gestione Scarto</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per no conferma cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per possibile frode</fullName>
    </customValue>
    <customValue>
        <fullName>Il cliente rinuncia</fullName>
    </customValue>
    <customValue>
        <fullName>Rifiutato Preventivamente</fullName>
    </customValue>
    <masterLabel>Motivazione Annullamento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_DocuementValidation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Richiesto</fullName>
    </customValue>
    <customValue>
        <fullName>Validato</fullName>
    </customValue>
    <customValue>
        <fullName>Non Validato</fullName>
    </customValue>
    <customValue>
        <fullName>Sollecitato</fullName>
    </customValue>
    <masterLabel>Document Validation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_OrderDossierWizardActions.cls
/**
 * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
 * @date 16/02/2021
 * @description HDT_LC_OrderDossierWizardActions.cls - Class that holds methods that are called from hdtOrderDossierWizardActions.js
 * @history Inserire Nome Cognome – Data Modifica – Descrizione della modifica
 */
public inherited sharing class HDT_LC_OrderDossierWizardActions {
    
    private static HDT_QR_Order orderQr = new HDT_QR_Order();
    private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 16/02/2021
    * @description Handle "stampa" action
    * @param Order orderParent
    */
    @AuraEnabled
    public static void save(Order orderParent){

        List<Order> childOrders = orderQr.getChildOrdersByParentId(orderParent.Id);
        List<Order> ordersToUpdate = new List<Order>();
        
        if (orderParent.ContractSigned__c == false) {

            //update child orders
            for (Order childOrder : childOrders) {
                ordersToUpdate.add(new Order(
                    Id = childOrder.Id,
                    //EVERIS: Aggiunto caso per Voltura 
                    Phase__c = childOrder.RecordType.DeveloperName == 'HDT_RT_Voltura' ? childOrder.Phase__c 
                    : checkRequiredDocs(childOrder) ? 'Documentazione Validata': 'In attesa validazione'
                ));
            }

            //update parent order
            ordersToUpdate.add(new Order(
                Id = orderParent.Id,
                Phase__c = 'Plico da inviare' //Everis: modificato in 'Plico da inviare poiche la fase 'Plico inviato da validare' non presente a DM'
            ));

        } else {

            //update child orders
            for (Order childOrder : childOrders) {
                ordersToUpdate.add(new Order(
                    Id = childOrder.Id,
                    Phase__c = checkRequiredDocs(childOrder) ? 'Documentazione Validata': 'In attesa validazione'
                ));
            }

            //update parent order
            ordersToUpdate.add(new Order(
                Id = orderParent.Id,
                Phase__c = 'Plico Firmato da validare'
            ));

        }

        orderSrv.updateRecords(ordersToUpdate);

    }

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 17/02/2021
    * @description Handle "Annulla" action
    * @param Order orderParent
    * @param String cancellationReason
    */
    @AuraEnabled
    public static void cancel(Order orderParent, String cancellationReason){
        
        List<Order> childOrders = orderQr.getChildOrdersByParentId(orderParent.Id);
        List<Order> ordersToUpdate = new List<Order>();

        //update child orders
        for (Order childOrder : childOrders) {
            ordersToUpdate.add(new Order(
                Id = childOrder.Id,
                Status = 'Annullato',
                Phase__c = 'Annullato',
                CancellationReason__c = cancellationReason
            ));
        }

        //update parent order
        ordersToUpdate.add(new Order(
            Id = orderParent.Id,
            Status = 'Annullato',
            Phase__c = 'Annullato',
            CancellationReason__c = cancellationReason
        ));

        orderSrv.updateRecords(ordersToUpdate);
    }

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 16/02/2021
    * @description Check order required documents
    * @param Order ord
    * @return Boolean
    */
    public static Boolean checkRequiredDocs(Order ord){

        Boolean check = true;

        if(ord.AutorizationVolturaThirdTrader__c != null || ord.CILegalRepresentative__c != null ||  ord.CIAccoutn__c != null || ord.QuickQuote__c != null || ord.ChamberCommerceRegistration__c != null || ord.Instance326__c != null || ord.DocumentLow80__c != null)
        {
           	check = true;
            if(ord.CILegalRepresentative__c != null && !'Validato'.EqualsIgnoreCase(ord.CILegalRepresentative__c)){
                check = false;
            }
            if(ord.CIAccoutn__c != null && !'Validato'.EqualsIgnoreCase(ord.CIAccoutn__c)){
                check = false;
            }
            if(ord.QuickQuote__c != null && !'Validato'.EqualsIgnoreCase(ord.QuickQuote__c)){
                check = false;
            }
            if(ord.ChamberCommerceRegistration__c != null && !'Validato'.EqualsIgnoreCase(ord.ChamberCommerceRegistration__c)){
                check = false;
            }
            if(ord.Instance326__c != null && !'Validato'.EqualsIgnoreCase(ord.Instance326__c)){
                check = false;
            }
            if(ord.DocumentLow80__c != null && !'Validato'.EqualsIgnoreCase(ord.DocumentLow80__c)){
                check = false;
            }
            if(ord.AutorizationVolturaThirdTrader__c != null && !'Validato'.EqualsIgnoreCase(ord.AutorizationVolturaThirdTrader__c)){
                check = false;
            }
        } else if(ord.AutorizationVolturaThirdTrader__c == null && ord.CILegalRepresentative__c == null &&  ord.CIAccoutn__c == null && ord.QuickQuote__c == null && ord.ChamberCommerceRegistration__c == null && ord.Instance326__c == null && ord.DocumentLow80__c == null) {
            check = true;
        }

        return check;
    }

    /**
    * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
    * @date 16/02/2021
    * @description Check if save button should be disabled or not
    * @param String orderParentId
    * @return Boolean
    */
    @AuraEnabled
    public static Boolean isSaveDisabled(String orderParentId){
        Boolean result = false;
        
        List<Order> childOrders = orderQr.getChildOrdersByParentId(orderParentId);
        
        for (Order childOrder : childOrders) {
            if (childOrder.Step__c != 20) {
                result = true;
                break;
            }
        }

        return result;
    }

}