force-app/main/default/objects/Order/fields/AutorizationVolturaThirdTrader__c.field-meta.xml
<CustomField>
    <fullName>AutorizationVolturaThirdTrader__c</fullName>
    <label>Modulo Autorizzazione Voltura c/o VT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ChamberCommerceRegistration__c.field-meta.xml
<CustomField>
    <fullName>ChamberCommerceRegistration__c</fullName>
    <label>Visura camerale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CIAccoutn__c.field-meta.xml
<CustomField>
    <fullName>CIAccoutn__c</fullName>
    <label>Carta d&apos;identità Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentLow80__c.field-meta.xml
<CustomField>
    <fullName>DocumentLow80__c</fullName>
    <label>Documento Legge 80</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentPackage__c.field-meta.xml
<CustomField>
    <fullName>DocumentPackage__c</fullName>
    <label>Plico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Instance326__c.field-meta.xml
<CustomField>
    <fullName>Instance326__c</fullName>
    <label>Istanza 326</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ParentOrder__c.field-meta.xml
<CustomField>
    <fullName>ParentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione verso l&apos;order dossier</description>
    <label>Order Padre</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku</fullName>
            </value>
            <value>
                <fullName>Da Inviare</fullName>
            </value>
            <value>
                <fullName>Documentazione da validare</fullName>
            </value>
            <value>
                <fullName>Documentazione Gestita</fullName>
            </value>
            <value>
                <fullName>Documentazione Validata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/QuickQuote__c.field-meta.xml
<CustomField>
    <fullName>QuickQuote__c</fullName>
    <label>Preventivo Rapido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_DocuementValidation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_Voltura.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Voltura</fullName>
    <active>true</active>
    <description>Record Type per processo di Voltura</description>
    <label>Voltura</label>
    </picklistValues>
</RecordType>

force-app/main/default/globalValueSets/HDT_DocuementValidation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Richiesto</fullName>
    </customValue>
    <customValue>
        <fullName>Validato</fullName>
    </customValue>
    <customValue>
        <fullName>Non Validato</fullName>
    </customValue>
    <customValue>
        <fullName>Sollecitato</fullName>
    </customValue>
    <masterLabel>Document Validation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_DocumentValidation.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 27/02/2021
* @description HDT_LC_DocumentValidation
* @history Keltin Mesonjesi – 27/02/2021 – Created class
*/

public inherited sharing class HDT_LC_DocumentValidation {
    private static HDT_QR_Order orderQr = new HDT_QR_Order();
	private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();

    /**
    * @description isValidPhase
    * @param recordId
    * @return Boolean
    */
    @AuraEnabled
    public static Boolean isValidPhase(String recordId){
        Order ord = orderQr.getRecordById(recordId);
        return ('Da Inviare'.equalsIgnoreCase(ord.phase__c) || 'In Attesa Validazione'.equalsIgnoreCase(ord.phase__c) || 'Documentazione da validare'.equalsIgnoreCase(ord.Phase__c));
    }
    
    /**
    * @description saveValidation
    * @param ord
    */
    @AuraEnabled
    public static void saveValidation(Order ord){
        System.debug('**************:'+ord);
        // quelli mostrati ( non null) tutti validati -----> phase --->  Documentazione Validata
   		Boolean check = false;
        if( /*Aggiunta carta identita*/ord.CIAccoutn__c != null || ord.QuickQuote__c != null || ord.ChamberCommerceRegistration__c != null || ord.Instance326__c != null || ord.DocumentLow80__c != null || ord.AutorizationVolturaThirdTrader__c != null)
        {
           	check = true;
            //Per voltura
            if(ord.CIAccoutn__c != null && !'Validato'.EqualsIgnoreCase(ord.CIAccoutn__c)){
                check = false;
            }
            //Per voltura
            if(ord.QuickQuote__c != null && !'Validato'.EqualsIgnoreCase(ord.QuickQuote__c)){
                check = false;
            }
            if(ord.ChamberCommerceRegistration__c != null && !'Validato'.EqualsIgnoreCase(ord.ChamberCommerceRegistration__c)){
                check = false;
            }
            if(ord.Instance326__c != null && !'Validato'.EqualsIgnoreCase(ord.Instance326__c)){
                check = false;
            }
            if(ord.DocumentLow80__c != null && !'Validato'.EqualsIgnoreCase(ord.DocumentLow80__c)){
                check = false;
            }
            if(ord.AutorizationVolturaThirdTrader__c != null && !'Validato'.EqualsIgnoreCase(ord.AutorizationVolturaThirdTrader__c)){
                check = false;
            }
            if(ord.DocumentPackage__c != null && !'Validato'.EqualsIgnoreCase(ord.DocumentPackage__c)){
                check = false;
            }
            
        }
        if(check){

            Order orderRetrive = orderQr.getRecordById(ord.Id);
            if('Documentazione Gestita'.EqualsIgnoreCase(orderRetrive.ParentOrder__r.Phase__c)){
                if(orderRetrive.RecordType.DeveloperName == 'HDT_RT_Voltura'){
                    ord.Phase__c = 'Documentazione Validata';
                } else {
                //    if(){
                 //       ord.Phase__c = 'Comunicazione verso Heroku';
                 //   }else{
                        ord.Phase__c = 'Documentazione Validata';
                 //   }
                }
            } else {
                ord.Phase__c = 'Documentazione Validata';
            }

            if(orderRetrive.ParentOrder__c == null){
                ord.Phase__c = 'Documentazione Gestita';
            }

        }
        System.debug('************:'+ord);
        orderSrv.updateRecord(ord);
        //update ord;
        //return true;
        //Order ord = orderQr.getRecordById(recordId);
        //return ('Da Inviare'.equalsIgnoreCase(ord.phase__c) || 'In Attesa Validazione'.equalsIgnoreCase(ord.phase__c));
    }

    /**
    * @description cancelOrder
    * @param recordId
    */
    @AuraEnabled
    public static void cancelOrder(String recordId){
        orderSrv.updateRecord(new Order(
            Id = recordId,
            Status = 'Annullato', //Chiuso
            Phase__c = 'Annullato'
        ));
    }
}