force-app/main/default/objects/Order/fields/BonusData__c.field-meta.xml
<CustomField>
    <fullName>BonusData__c</fullName>
    <label>Info Bonus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/EstimateAmount__c.field-meta.xml
<CustomField>
    <fullName>EstimateAmount__c</fullName>
    <label>Importo Preventivo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/FareCode__c.field-meta.xml
<CustomField>
    <fullName>FareCode__c</fullName>
    <label>Codice Tariffa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/MeterClass__c.field-meta.xml
<CustomField>
    <fullName>MeterClass__c</fullName>
    <description>Classe o Calibro Contatore</description>
    <label>Classe Contatore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Cluster</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MeterSN__c.field-meta.xml
<CustomField>
    <fullName>MeterSN__c</fullName>
    <label>Matricola Contatore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressione Fornitura</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/QuotationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuotationNumber__c</fullName>
    <label>Numero Preventivo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/QuotationType__c.field-meta.xml
<CustomField>
    <fullName>QuotationType__c</fullName>
    <label>Tipo Preventivo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <label>Tipo Fornitura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ValidityDateEstimate__c.field-meta.xml
<CustomField>
    <fullName>ValidityDateEstimate__c</fullName>
    <label>Data Validita Preventivo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/WorkExecutionTime__c.field-meta.xml
<CustomField>
    <fullName>WorkExecutionTime__c</fullName>
    <label>Tempo Esecuzione Lavori</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Collection__c.field-meta.xml
<CustomField>
    <fullName>Collection__c</fullName>
    <label>Raccolta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CorrectiveCoefficient__c.field-meta.xml
<CustomField>
    <fullName>CorrectiveCoefficient__c</fullName>
    <label>Coefficiente Correttivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CorrectorDigitNumber__c.field-meta.xml
<CustomField>
    <fullName>CorrectorDigitNumber__c</fullName>
    <label>Numero Cifre Convertitore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CorrectorSignal__c.field-meta.xml
<CustomField>
    <fullName>CorrectorSignal__c</fullName>
    <label>Segnale Convertitore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CorrectorSN__c.field-meta.xml
<CustomField>
    <fullName>CorrectorSN__c</fullName>
    <label>Matricola Convertitore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CorrectorType__c.field-meta.xml
<CustomField>
    <fullName>CorrectorType__c</fullName>
    <label>Tipo Misuratore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CorrectorWithdrawal__c.field-meta.xml
<CustomField>
    <fullName>CorrectorWithdrawal__c</fullName>
    <label>Prelievo Convertitore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/DigitNumberActive__c.field-meta.xml
<CustomField>
    <fullName>DigitNumberActive__c</fullName>
    <label>Cifre Attiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/DigitNumberReactive__c.field-meta.xml
<CustomField>
    <fullName>DigitNumberReactive__c</fullName>
    <label>Cifre Reattiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/DispatchingPoint__c.field-meta.xml
<CustomField>
    <fullName>DispatchingPoint__c</fullName>
    <label>Punto di Dispacciamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/DistributorTreatment__c.field-meta.xml
<CustomField>
    <fullName>DistributorTreatment__c</fullName>
    <label>Trattamento Distributore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Forfait__c.field-meta.xml
<CustomField>
    <fullName>Forfait__c</fullName>
    <label>Forfait</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/InstallationDateActive__c.field-meta.xml
<CustomField>
    <fullName>InstallationDateActive__c</fullName>
    <label>Data Installazione Attiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/InstallationDatePower__c.field-meta.xml
<CustomField>
    <fullName>InstallationDatePower__c</fullName>
    <label>Data Installazione Potenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/InstallationDateReactive__c.field-meta.xml
<CustomField>
    <fullName>InstallationDateReactive__c</fullName>
    <label>Data Installazione Reattiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/kActive__c.field-meta.xml
<CustomField>
    <fullName>kActive__c</fullName>
    <label>K Attiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/kPower__c.field-meta.xml
<CustomField>
    <fullName>kPower__c</fullName>
    <label>K Potenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/kReactive__c.field-meta.xml
<CustomField>
    <fullName>kReactive__c</fullName>
    <label>K Reattiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MarketTypeCode__c.field-meta.xml
<CustomField>
    <fullName>MarketTypeCode__c</fullName>
    <label>Servizio Tutela</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MaxHourWithdrawal__c.field-meta.xml
<CustomField>
    <fullName>MaxHourWithdrawal__c</fullName>
    <label>Max Prelievo Ora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterAccessible__c.field-meta.xml
<CustomField>
    <fullName>MeterAccessible__c</fullName>
    <label>Accessibilità Misuratore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterActiveSN__c.field-meta.xml
<CustomField>
    <fullName>MeterActiveSN__c</fullName>
    <label>Matricola Misuratore Attiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterClass__c.field-meta.xml
<CustomField>
    <fullName>MeterClass__c</fullName>
    <description>Classe o Calibro Contatore</description>
    <label>Classe Contatore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G100 Turbina</fullName>
            </value>
            <value>
                <fullName>G160 Turbina</fullName>
            </value>
            <value>
                <fullName>G250 Turbina</fullName>
            </value>
            <value>
                <fullName>G400 Turbina</fullName>
            </value>
            <value>
                <fullName>G40 Turbina</fullName>
            </value>
            <value>
                <fullName>G65 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G160 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G250 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G250G Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G650 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G1000 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G400 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G1600 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>G4000 Pistoni rot.</fullName>
            </value>
            <value>
                <fullName>DIR Monorario</fullName>
            </value>
            <value>
                <fullName>DIR Orario</fullName>
            </value>
            <value>
                <fullName>DIR Biorario</fullName>
            </value>
            <value>
                <fullName>100 Volt</fullName>
            </value>
            <value>
                <fullName>400 Volt</fullName>
            </value>
            <value>
                <fullName>230 Volt</fullName>
            </value>
            <value>
                <fullName>Elettronico</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>G1,6</fullName>
            </value>
            <value>
                <fullName>G10</fullName>
            </value>
            <value>
                <fullName>G100</fullName>
            </value>
            <value>
                <fullName>G1000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterDigitNumber__c.field-meta.xml
<CustomField>
    <fullName>MeterDigitNumber__c</fullName>
    <label>Numero Cifre Misuratore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterGroup__c.field-meta.xml
<CustomField>
    <fullName>MeterGroup__c</fullName>
    <label>Gruppo Misuratore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterPowerSN__c.field-meta.xml
<CustomField>
    <fullName>MeterPowerSN__c</fullName>
    <label>Matricola Misuratore Potenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterReactiveSN__c.field-meta.xml
<CustomField>
    <fullName>MeterReactiveSN__c</fullName>
    <label>Matricola Misuratore Reattiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterSignal__c.field-meta.xml
<CustomField>
    <fullName>MeterSignal__c</fullName>
    <label>Segnale Misuratore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterSN__c.field-meta.xml
<CustomField>
    <fullName>MeterSN__c</fullName>
    <description>Matricola del contatore attuale</description>
    <label>Matricola Contatore</label>
    <!--Modificata lunghezza campo da 255 a 18 in quanto Siebel, SAP non accettano matricole superiori ai 18
    Essendo un campo compilabile dall'operatore, al fine di preservare la coerenza dei dati tra i sistemi
    e' stata applicata la modifica della lunghezza.
    -->
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterYear__c.field-meta.xml
<CustomField>
    <fullName>MeterYear__c</fullName>
    <label>Anno fabbricazione misuratore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressione Fornitura</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/RegimeDate2G__c.field-meta.xml
<CustomField>
    <fullName>RegimeDate2G__c</fullName>
    <label>Data Regime 2G</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <label>Tipo Fornitura</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CommoditySector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/recordTypes/HDT_RT_Gas.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Gas</fullName>
    <active>true</active>
    <description>Punto di fornitura Gas</description>
    <label>Punto Gas</label>
</RecordType>

force-app/main/default/globalValueSets/HDT_Cluster.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento</fullName>
    </customValue>
    <customValue>
        <fullName>Attivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Autolettura</fullName>
    </customValue>
    <customValue>
        <fullName>Canone Rai</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Fatturazione</fullName>
    </customValue>
    <customValue>
        <fullName>Indennizzi</fullName>
    </customValue>
    <customValue>
        <fullName>Informative</fullName>
    </customValue>
    <customValue>
        <fullName>Modifiche Anagrafiche</fullName>
    </customValue>
    <customValue>
        <fullName>Morosità</fullName>
    </customValue>
    <customValue>
        <fullName>Notifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Pagamenti</fullName>
    </customValue>
    <customValue>
        <fullName>PostSales VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Preventivi</fullName>
    </customValue>
    <customValue>
        <fullName>Reclami</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>Variazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Verifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
        <isActive>false</isActive>
        <label>Ambiente</label>
    </customValue>
    <customValue>
        <fullName>Generiche Attivazioni</fullName>
        <isActive>false</isActive>
        <label>Generiche Attivazioni</label>
    </customValue>
    <customValue>
        <fullName>Generiche VAS</fullName>
        <isActive>false</isActive>
        <label>Generiche VAS</label>
    </customValue>
    <customValue>
        <fullName>HERA</fullName>
        <isActive>false</isActive>
        <label>HERA</label>
    </customValue>
    <masterLabel>Cluster</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SupplyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Non Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>A-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>B-Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>C-Aziende di pubblica utilita</fullName>
    </customValue>
    <customValue>
        <fullName>D-Altri usi</fullName>
    </customValue>
    <customValue>
        <fullName>Uso domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso diverso da domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Usi industriali che scaricano in pubblica fognatura</fullName>
    </customValue>
    <customValue>
        <fullName>Altri usi</fullName>
    </customValue>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <masterLabel>Tipo Fornitura</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_HandleTechnicalDataTst.cls
/**
 * @author Valere (valere@noeli-it.net)
 * @date 6/10/2021
 * @description HDT_UTL_VasManagementTst Test Class
 * @history valere - 6/10/2021– Created Class
 */
@isTest
private class HDT_UTL_HandleTechnicalDataTst {

@testSetup 
  static void setup() {

    List<Account> accountList= HDT_UTL_DataFactoryTst.createAccountResidenziale(1,true,'HERA COMM','Persona fisica','Famiglie');

    //List<Order> order = 
    HDT_UTL_DataFactoryTst.createOrder(1,true, accountList[0].id,'Bozza');


    //List<ServicePoint__c> servicePoint = 
    HDT_UTL_DataFactoryTst.createServicePoint(1,true);


  }
    
  @isTest
  static void testhandleE154Flow() {

    Order order=[SELECT id,EstimateAmount__c,QuotationType__c, SupplyType__c, ValidityDateEstimate__c,QuotationNumber__c,WorkExecutionTime__c FROM Order];  

    HDT_UTL_HandleTechnicalData handleTechnicalData = new HDT_UTL_HandleTechnicalData();
    handleTechnicalData.handleE154Flow(new Map<String,String>{
        'IMP_PREV_DIST'=>'10',
        'DT_MAX_PREV'=>'20220502',
        'NUMPREV'=>'10',
        'TEMP_ES_PREV'=>'10'
    },order);
    

    System.assertEquals('Analitico',order.QuotationType__c, 'value of parameters is matching');
    System.assertNotEquals('code',order.QuotationType__c, 'value of parameters is  not  matching');

  }



  @isTest
  static void testhandleE150Flow() {

    Order order=[SELECT id,FareCode__c,WorkExecutionTime__c FROM Order];  

    ServicePoint__c service=[SELECT
                              DispatchingPoint__c,
                              CorrectorType__c,
                              RegimeDate2G__c,
                              DistributorTreatment__c,
                              kActive__c,
                              kReactive__c,
                              kPower__c,
                              MeterActiveSN__c,
                              MeterReactiveSN__c,
                              MeterPowerSN__c,
                              InstallationDateActive__c,
                              InstallationDateReactive__c,
                              InstallationDatePower__c,
                              DigitNumberActive__c,
                              DigitNumberReactive__c,
                              MeterGroup__c,
                              Forfait__c,
                              MarketTypeCode__c,
                              ServicePointCode__c
                              FROM ServicePoint__c LIMIT 1];

    HDT_UTL_HandleTechnicalData handleTechnicalData = new HDT_UTL_HandleTechnicalData();
    handleTechnicalData.sp= service;
    handleTechnicalData.handleE150Flow(new Map<String,String>{
        'PUNTODISPACCIAMENTO'=>'DispatchingPoint',
        'TIPO_MISURATORE'=>'CorrectorType',
        'DATA_REGIME_2G'=>'10',
        'TRATTAMENTO_DT'=>'10',


        'K_ATT'=>'10',
        'K_REATT'=>'20220502',
        'K_POT'=>'10',
        'MATR_MIS_ATTIVA_NEW'=>'10',


        'MATR_MIS_REATTIVA_NEW'=>'10',
        'MATR_MIS_POTENZA_NEW'=>'20220502',
        'DATA_INST_ATT'=>'10',
        'DATA_INST_REA'=>'10',


        'DATA_INST_POT'=>'10',
        'CIFRE_ATTIVA'=>'20220502',
        'CIFRE_REATTIVA'=>'10',
        'CIFRE_POT'=>'10',


        'GRUPPO_MIS'=>'10',
        'FORFAIT'=>'20220502',
        'CODICE_TARIFFA'=>'10',
        'SERV_TUTELA'=>'10',
        'GRUPPO_MIS_DT'=>'10',
        'TEMP_ES_PREV'=>'10'

    },order);
    

    System.assertEquals('10',order.FareCode__c, 'value of parameters is matching');
    System.assertNotEquals('code',order.FareCode__c, 'value of parameters is  not  matching');

  }


  @isTest
  static void testhandlE351Flow() {

    Order order=[SELECT id,MeterSN__c,WorkExecutionTime__c FROM Order];  


    ServicePoint__c service=[SELECT
                              DistributorTreatment__c,
                              MeterDigitNumber__c,
                              CorrectorSN__c,
                              CorrectorDigitNumber__c,
                              CorrectiveCoefficient__c,
                              Collection__c,
                              MeterClass__c,
                              CorrectorWithdrawal__c,
                              MeterGroup__c,
                              ServicePointCode__c

                             FROM ServicePoint__c LIMIT 1];

    HDT_UTL_HandleTechnicalData handleTechnicalData = new HDT_UTL_HandleTechnicalData();
    handleTechnicalData.sp= service;
    handleTechnicalData.handlE351Flow(new Map<String,String>{
        'TRATTAMENTO_DT'=>'TRATTAMENTO_DT',
        'MATR_MIS'=>'MATR_MIS',
        'N_CIFRE_MIS'=>'N_CIFRE_MIS',
        'MATR_CONV'=>'MATR_CONV',


        'N_CIFRE_CONV'=>'N_CIFRE_CONV',
        'COEFF_CORRETTIVO'=>'COEFF_CORRETTIVO',
        'RACCOLTA'=>'RACCOLTA',
        'VOL_ANNUO_SOST'=>'VOL_ANNUO_SOST',


        
        'PRE_CONV'=>'PRE_CONV',
        'GRUPPO_MIS_INT'=>'GRUPPO_MIS_INT',
        'TEMP_ES_PREV'=>'10'

    },order);
    

    System.assertEquals('MATR_MIS',order.MeterSN__c, 'value of parameters is matching');
    System.assertNotEquals('code',order.MeterSN__c, 'value of parameters is  not  matching');

  }



  @isTest
  static void testhandlE300Flow() {

    Order order=[SELECT id,MeterSN__c,BonusData__c,WorkExecutionTime__c FROM Order];  

    ServicePoint__c service=[SELECT
                              MeterDigitNumber__c,
                              MeterClass__c,
                              MeterYear__c,
                              MeterSignal__c,
                              CorrectorSN__c,
                              CorrectorDigitNumber__c,
                              CorrectorSignal__c,
                              CorrectiveCoefficient__c,
                              MeterAccessible__c,
                              Pressure__c,
                              MaxHourWithdrawal__c,
                              AnnualConsumption__c,
                              OrderDueDate__c,
                              RenewalMonth__c,
                              ServicePointCode__c
   
                             FROM ServicePoint__c LIMIT 1];

    HDT_UTL_HandleTechnicalData handleTechnicalData = new HDT_UTL_HandleTechnicalData();
    handleTechnicalData.sp= service;
    handleTechnicalData.handlE300Flow(new Map<String,String>{
        'MATR_MIS'=>'MATR_MIS',
        'TIPO_PDR'=>'TIPO_PDR',
        'DATA_REGIME_2G'=>'DATA_REGIME_2G',
        

        'ANNO_FABB_MIS'=>'ANNO_FABB_MIS',
        'SEGN_MIS_AVVIO'=>'SEGN_MIS_AVVIO',
        'MATR_CONV'=>'MATR_CONV',
        'N_CIFRE_CONV'=>'N_CIFRE_CONV',


        'SEGN_CONV'=>'SEGN_CONV',
        'COEFF_CORRETTIVO'=>'COEFF_CORRETTIVO',
        'ACC_MIS'=>'ACC_MIS',
        'COD_PROF_PREL'=>'COD_PROF_PREL',


        'COD_REMI'=>'COD_REMI',
        'PRESS_MIS'=>'10',
        'MAX_PRELIEVO_ORA'=>'MAX_PRELIEVO_ORA',
        'CONS_ANNUO'=>'10',


        'DATA_SCAD_DS'=>'DATA_SCAD_DS',
        'BONUSGAS'=>'BONUSGAS',
        'BONUS_INIZ'=>'BONUS_INIZ',
        'BONUS_FINE'=>'BONUS_FINE',
        'MESE_RIN'=>'MESE_RIN',
        'TIPO_BONUS'=>'TIPO_BONUS',
        'TEMP_ES_PREV'=>'10'

    },order);
    

    System.assertEquals('MATR_MIS',order.MeterSN__c, 'value of parameters is matching');
    System.assertNotEquals('code',order.MeterSN__c, 'value of parameters is  not  matching');

  }


  @isTest
  static void testhandleCompletataActivo() {

    ServicePoint__c service=[SELECT
                              SAPImplantCode__c,
                              SAPContractCode__c,
                              MeterStatus__c,
                              Status__c,
                              RecordTypeId,
                              ServicePointCode__c
                             FROM ServicePoint__c LIMIT 1];
    Account acc = [SELECT Id FROM Account LIMIT 1];
    String recordTypeId = Schema.SObjectType.ServicePoint__c.getRecordTypeInfosByDeveloperName().get('HDT_RT_Gas').getRecordTypeId();
    service.RecordTypeId = recordTypeId;
    service.CommoditySector__c = 'Gas';
    update service;
    HDT_UTL_HandleTechnicalData handleTechnicalData = new HDT_UTL_HandleTechnicalData();
    handleTechnicalData.sp= service;
    handleTechnicalData.handleCompletata(new Map<String,String>{
        'ANLAGE'=>'10',
        'VERTRAG'=>'20',
        'ANLAGE_ST'=>'Open',
        'supplyType' => 'A-Domestico',
        'implantType' => '1004-Riscaldamento promiscuo',
        'NuovoAccount' => acc.Id
   
    });
    
    System.assertEquals('Attivo',  handleTechnicalData.sp.MeterStatus__c, 'value of parameters is matching');
    System.assertNotEquals('code',  handleTechnicalData.sp.MeterStatus__c, 'value of parameters is  not  matching');

  }

  @isTest
  static void testhandleCompletataInattivo() {

   ServicePoint__c service=[SELECT
                              SAPImplantCode__c,
                              SAPContractCode__c,
                              MeterStatus__c,
                              Status__c,
                              ServicePointCode__c
                                

                             FROM ServicePoint__c LIMIT 1];

    HDT_UTL_HandleTechnicalData handleTechnicalData = new HDT_UTL_HandleTechnicalData();
    handleTechnicalData.sp= service;
    handleTechnicalData.handleCompletata(new Map<String,String>{
        'ANLAGE'=>'10',
        'VERTRAG'=>'20',
        'ANLAGE_ST'=>'Impianto chiuso per morosita'
   
    });
    
    System.assertEquals('Inattivo',  handleTechnicalData.sp.MeterStatus__c, 'value of parameters is matching');
    System.assertNotEquals('code',  handleTechnicalData.sp.MeterStatus__c, 'value of parameters is  not  matching');

  }


  @isTest
  static void testhandleCompletataSospeso() {

      ServicePoint__c service=[SELECT
                                SAPImplantCode__c,
                                SAPContractCode__c,
                                MeterStatus__c,
                                Status__c,
                                ServicePointCode__c
                              

                            FROM ServicePoint__c LIMIT 1];
    HDT_UTL_HandleTechnicalData handleTechnicalData = new HDT_UTL_HandleTechnicalData();
    handleTechnicalData.sp= service;
    handleTechnicalData.handleCompletata(new Map<String,String>{
        'ANLAGE'=>'10',
        'VERTRAG'=>'20',
        'ANLAGE_ST'=>'Interr. avviata per morosita'
   
    });
    
    System.assertEquals('Sospeso',  handleTechnicalData.sp.MeterStatus__c, 'value of parameters is matching');
    System.assertNotEquals('code',  handleTechnicalData.sp.MeterStatus__c, 'value of parameters is  not  matching');

  }



}