force-app/main/default/objects/Order/fields/CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>CancellationReason__c</fullName>
    <label>Causale Annullamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CancellationReason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DocusignExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>DocusignExpirationDate__c</fullName>
    <description>Data Scadenza Busta Docusign</description>
    <label>Data Scadenza Busta Docusign</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentOrder__c.field-meta.xml
<CustomField>
    <fullName>ParentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione verso l&apos;order dossier</description>
    <label>Order Padre</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_ScontiBonus.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_ScontiBonus</fullName>
    <active>true</active>
    <label>Aggiunta Sconti o Bonus VAS</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VAS.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VAS</fullName>
    <active>true</active>
    <label>VAS</label>
    </picklistValues>
</RecordType>

force-app/main/default/globalValueSets/HDT_CancellationReason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Annullo voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Classificazione errata</fullName>
    </customValue>
    <customValue>
        <fullName>Codice ABI obsoleto</fullName>
    </customValue>
    <customValue>
        <fullName>Contattare banca</fullName>
    </customValue>
    <customValue>
        <fullName>Contatto Quality Fallito</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazione in corso</fullName>
    </customValue>
    <customValue>
        <fullName>Domiciliazione già presente</fullName>
    </customValue>
    <customValue>
        <fullName>Firma falsa</fullName>
    </customValue>
    <customValue>
        <fullName>Mancanza titolarità</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-ricezione</fullName>
    </customValue>
    <customValue>
        <fullName>No conferma Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>PDR/POD errato</fullName>
    </customValue>
    <customValue>
        <fullName>Pratica errata</fullName>
    </customValue>
    <customValue>
        <fullName>Processo incompatibile</fullName>
    </customValue>
    <customValue>
        <fullName>Quality - Annullo cambio offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 14.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 6.3 del TIMOE</fullName>
    </customValue>
    <customValue>
        <fullName>Revoca ai sensi del comma 8.2 del TIMG</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento da cliente oltre i termini</fullName>
    </customValue>
    <customValue>
        <fullName>Ripensamento tramite quality call</fullName>
    </customValue>
    <customValue>
        <fullName>Sollecito</fullName>
    </customValue>
    <customValue>
        <fullName>Volontà estorta</fullName>
    </customValue>
    <customValue>
        <fullName>Gestione Scarto</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per no conferma cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Annullato per possibile frode</fullName>
    </customValue>
    <customValue>
        <fullName>Il cliente rinuncia</fullName>
    </customValue>
    <customValue>
        <fullName>Rifiutato Preventivamente</fullName>
    </customValue>
    <masterLabel>Motivazione Annullamento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_BA_ExpiredOrders.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public with sharing class HDT_BA_ExpiredOrders implements Database.Batchable<sObject> , Schedulable {

    public void execute(SchedulableContext ctx){
        Database.executebatch(this,100);
    }

    //BATCH START
    
    //TODO: SOSTITUIRE SEND DATE CON DocusignExpirationDate__c --> Fatto
    public Database.QueryLocator start(Database.BatchableContext bc){
        Date todayDate = Date.today();
        Set<String> recordTypeSet = new Set<String>{'HDT_RT_VAS','HDT_RT_ScontiBonus'};
        return Database.getQueryLocator('SELECT Id, Status, ParentOrder__c, ParentOrder__r.DocusignExpirationDate__c, Phase__c, CancellationReason__c FROM Order WHERE  (ParentOrder__r.DocusignExpirationDate__c != null AND ParentOrder__r.DocusignExpirationDate__c < :todayDate) AND ParentOrder__r.Phase__c NOT IN (\'Documentazione Gestita\') AND Phase__c NOT IN (\'Completata\', \'Annullato\') AND RecordType.DeveloperName NOT IN :recordTypeSet');
    }
    
    //BATCH EXECUTE
    public void execute(Database.BatchableContext bc, List<Order> ordersToNullify){
        
        for(Order myOrder : ordersToNullify){
            myOrder.Phase__c = 'Annullato';
            myOrder.Status = 'Annullato';
            myOrder.CancellationReason__c = 'Annullato per no conferma cliente';
        }
        System.debug(LoggingLevel.DEBUG, 'HDT_BA_ExpiredOrders - Aggiorno Order Record: ' + ordersToNullify.size());
        
        HDT_UTL_DatabaseService.updateSObject(ordersToNullify);
    }
    
    //BATCH FINISH
    public void finish(Database.BatchableContext bc) {
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :bc.getJobId()];
        System.debug(LoggingLevel.DEBUG, 'HDT_BA_ExpiredOrders - finished job: ' + a);
    }
    
}