force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contatto Primario</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders (Contatto Primario)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ActivityDuration__c.field-meta.xml
<CustomField>
    <fullName>ActivityDuration__c</fullName>
    <description>Durata attivita</description>
    <label>Durata Attività</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ActivityEndTime__c.field-meta.xml
<CustomField>
    <fullName>ActivityEndTime__c</fullName>
    <description>Data e ora fine attività</description>
    <label>Fine Attività</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ActivityStartTime__c.field-meta.xml
<CustomField>
    <fullName>ActivityStartTime__c</fullName>
    <description>Data e ora inizio attività</description>
    <label>Inizio Attività</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/BPCode__c.field-meta.xml
<CustomField>
    <fullName>BPCode__c</fullName>
    <description>Codice identificativo del cliente digitato in IVR</description>
    <label>Codice BP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/CallCenterNumber__c.field-meta.xml
<CustomField>
    <fullName>CallCenterNumber__c</fullName>
    <description>Numero centralino coinvolto nell&apos;interazione</description>
    <label>Numero Verde</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/CallDuration__c.field-meta.xml
<CustomField>
    <fullName>CallDuration__c</fullName>
    <description>Durata chiamata</description>
    <label>Durata Chiamata</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/CallEndTime__c.field-meta.xml
<CustomField>
    <fullName>CallEndTime__c</fullName>
    <description>Data e ora fine chiamata</description>
    <label>Fine Chiamata</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/CallStartTime__c.field-meta.xml
<CustomField>
    <fullName>CallStartTime__c</fullName>
    <description>Data e ora inizio chiamata</description>
    <label>Inizio Chiamata</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ClientNumber__c.field-meta.xml
<CustomField>
    <fullName>ClientNumber__c</fullName>
    <description>Numero cliente coinvolto nell&apos;interazione</description>
    <label>Numero Cliente</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ConnectionID__c.field-meta.xml
<CustomField>
    <fullName>ConnectionID__c</fullName>
    <description>ID chiamata univoco Genesys</description>
    <label>ConnectionID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Cliente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/CrmChange__c.field-meta.xml
<CustomField>
    <fullName>CrmChange__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True se l&apos;attività è stata conclusa a seguito di un cambio CRM</description>
    <label>Cambio CRM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/OperatorChange__c.field-meta.xml
<CustomField>
    <fullName>OperatorChange__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True se l&apos;attività è stata conclusa a seguito di un cambio operatore</description>
    <label>Cambio Operatore</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ParentActivity__c.field-meta.xml
<CustomField>
    <fullName>ParentActivity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Correlata</label>
    <referenceTo>wrts_prcgvr__Activity__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo attività</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Anticipo Appuntamento</fullName>
            </value>
            <value>
                <fullName>Approvazione Bonus Commerciale</fullName>
            </value>
            <value>
                <fullName>Approvazione Offerte</fullName>
            </value>
            <value>
                <fullName>Assistenza Contact Center</fullName>
            </value>
            <value>
                <fullName>Attesa Preventivo DL</fullName>
            </value>
            <value>
                <fullName>Attivazioni</fullName>
            </value>
            <value>
                <fullName>Back Office - Catalogo Prodotti</fullName>
            </value>
            <value>
                <fullName>Back Office - Contratti</fullName>
            </value>
            <value>
                <fullName>Back Office - Fatturazione</fullName>
            </value>
            <value>
                <fullName>Back Office - Morosità</fullName>
            </value>
            <value>
                <fullName>Back Office - Pagamenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Preventivi</fullName>
            </value>
            <value>
                <fullName>Back Office - Supporto/Comunicazioni Urgenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Tari/TCP</fullName>
            </value>
            <value>
                <fullName>Back Office - Vas e HVAC</fullName>
            </value>
            <value>
                <fullName>Busta Docusign non consegnata</fullName>
            </value>
            <value>
                <fullName>Caricamenti contratti</fullName>
            </value>
            <value>
                <fullName>Caricamento Manuale Siebel</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Chiamata Callback</fullName>
            </value>
            <value>
                <fullName>Chiamata inbound</fullName>
            </value>
            <value>
                <fullName>Chiamata outbound</fullName>
            </value>
            <value>
                <fullName>Comfort Call</fullName>
            </value>
            <value>
                <fullName>Comunicazione da DL</fullName>
            </value>
            <value>
                <fullName>Comunicazioni con DL</fullName>
            </value>
            <value>
                <fullName>Conferma Preventivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/WaitingTime__c.field-meta.xml
<CustomField>
    <fullName>WaitingTime__c</fullName>
    <description>Tempo trascorso in attesa dal cliente</description>
    <label>Tempo di Attesa</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/wrts_prcgvr__Status__c.field-meta.xml
<CustomField>
    <fullName>wrts_prcgvr__Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aperta</fullName>
                <default>true</default>
                <label>Aperta</label>
            </value>
            <value>
                <fullName>Sospesa</fullName>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
            <value>
                <fullName>Creata</fullName>
            </value>
            <value>
                <fullName>Presa appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Appuntamento confermato</fullName>
            </value>
            <value>
                <fullName>Appuntamento non eseguito</fullName>
            </value>
            <value>
                <fullName>Appuntamento eseguito</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
            <value>
                <fullName>Invio app.to SELF cliente</fullName>
            </value>
            <value>
                <fullName>Appuntamento di competenza Distributore</fullName>
            </value>
            <value>
                <fullName>Scartata</fullName>
            </value>
            <value>
                <fullName>Modifica confermata</fullName>
            </value>
            <value>
                <fullName>Modifica appuntamento in corso</fullName>
            </value>
            <value>
                <fullName>Esitata</fullName>
            </value>
            <value>
                <fullName>Non Esitata</fullName>
            </value>
            <value>
                <fullName>Comunicazione inviata</fullName>
            </value>
            <value>
                <fullName>Comunicazione inviata</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>KO Forzato</fullName>
            </value>
            <value>
                <fullName>KO Risolto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConnectorEntityController.cls
global with sharing class ConnectorEntityController {
	public ConnectorEntityController() {}

	private class AttachData {
		String target_crm;
		String sf_activity_id;
		String sb_activity_id;
	}

	@RemoteAction
	global static String createActivity(String jsonMessage) {
		Map<String,Object> message = (Map<String,Object>) JSON.deserializeUntyped(jsonMessage);
		AttachData attachdata = (AttachData) JSON.deserialize((String) message.get('attachdata'), attachdata.class);

		if(message.get('ErrorCode') != '0') {
			return 'Error: ' + message.get('ErrorMessage');
		}

		RecordType recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'HDT_RT_Chiamata'];
		wrts_prcgvr__Activity__c activity = new wrts_prcgvr__Activity__c(
			RecordTypeId = recordType.Id,
			Type__c = 'Chiamata',
			wrts_prcgvr__Status__c = 'In Progress',
			ActivityStartTime__c = DateTime.now(),
			CallStartTime__c = DateTime.now(),
			ConnectionID__c = (String) message.get('ConnectionID'),
			Subtype__c = (String) message.get('CallType')
		);

		switch on (String) message.get('CallType') {
			when 'Outbound' {
				activity.CallCenterNumber__c = (String) message.get('ANI');
				activity.ClientNumber__c = (String) message.get('DNIS');
			}
			when 'Inbound' {
				activity.CallCenterNumber__c = (String) message.get('DNIS');
				activity.ClientNumber__c = (String) message.get('ANI');
			}
		}

		for(wrts_prcgvr__Activity__c a : [SELECT Id FROM wrts_prcgvr__Activity__c WHERE ConnectionID__c =: activity.ConnectionID__c ORDER BY CreatedDate DESC LIMIT 1]) {
			activity.ParentActivity__c = a.Id;
		}

		Map<String,String> result = new Map<String,String>();
		List<Contact> contacts = [SELECT Id, AccountId FROM Contact WHERE Phone =: activity.ClientNumber__c OR MobilePhone =: activity.ClientNumber__c];
		if(contacts.size() == 1) {
			Contact contact = contact[0];
			activity.Contact__c = contact.Id;
			result.put('contactId', contact.Id);
			List<AccountContactRelation> relations = [SELECT Id FROM AccountContactRelation WHERE ContactId =: contact.Id];
			if(relations.size() == 1) {
				activity.Account__c = contact.AccountId;
				result.put('accountId', contact.AccountId);
			}
		}

		insert activity;
		result.put('activityId', activity.Id);
		
		return JSON.serialize(result);
	}

	@RemoteAction
	global static String closeActivity(String jsonMessage, Boolean crmChange, Boolean operatorChange) {
		Map<String,Object> message = (Map<String,Object>) JSON.deserializeUntyped(jsonMessage);
		AttachData attachdata = (AttachData) JSON.deserialize((String) message.get('attachdata'), attachdata.class);

		wrts_prcgvr__Activity__c activity = new wrts_prcgvr__Activity__c(
			Id = attachdata.sf_activity_id,
			wrts_prcgvr__Status__c = 'Completed',
			ActivityEndTime__c = Datetime.now(),
			CallEndTime__c = Datetime.now(),
			ActivityDuration__c = (Decimal) message.get('Duration'),
			CallDuration__c = (Decimal) message.get('Duration'),
			WaitingTime__c = 0, // WIP
			CrmChange__c = crmChange,
			OperatorChange__c = operatorChange,
			BPCode__c = ''
		);

		try {
			update activity;
		} catch (Exception e) {
			return 'ERROR: ' + e.getMessage() + ' ' + e.getCause();
		}

		return '0';
	}
	
	@RemoteAction
	global static Task createTask(Task task,String field, String value) {
		
		try{        
			List<Contact> contacts = Database.query('Select id,AccountId,Birthdate,Email,FirstName,LastName,Phone from Contact where ' + field + ' = \'' + value + '\'');
			System.debug('contacts found : ' + contacts);
			if ( contacts.size() == 1 ){
				task.WhoId = contacts.get(0).Id;
			} 
			} catch(Exception e){
			System.debug('Error in finding contact ' + e);     
		}

		try{           
			Database.SaveResult sr =  Database.insert(task);
				System.debug('save result : ' + sr);   
				return task;
			} catch(Exception e){
			System.debug('Error in insert ' + e);
		
		}
		return null;
	}

	@RemoteAction
	global static Case createCase(Case obj,String field, String value) {
		
		try{        
			List<Contact> contacts = Database.query('Select id,AccountId,Birthdate,Email,FirstName,LastName,Phone from Contact where ' + field + ' = \'' + value + '\'');
			System.debug('contacts found : ' + contacts);
			if ( contacts.size() == 1 ){
				obj.ContactId = contacts.get(0).Id;
			} 
			} catch(Exception e){
			System.debug('Error in finding contact ' + e);     
		}

		try{           
			Database.SaveResult sr =  Database.insert(obj);
				System.debug('save result : ' + sr);   
				return obj;
			} catch(Exception e){
			System.debug('Error in insert ' + e);
		
		}
		return null;
	}

	@RemoteAction
	global static String ERCOmniUtilsPath {
		get {
		return GetResourceURL('softphoneerc','omniUtils');
		}
	}

	@RemoteAction
	global static String ERCiwsscriptomniPath {
		get {
		return GetResourceURL(null,'iwsscript_omni');
		}
	}

	@RemoteAction
	global static String ERCsyncUtilsPath {
		get {
		return GetResourceURL(null,'syncUtils');
		}
	}


	public static String GetResourceURL(String namespace,String resourceName){
	List<StaticResource> resourceList= namespace != null ? 
	[SELECT Name, NamespacePrefix, SystemModStamp FROM StaticResource WHERE Name = :resourceName AND NamespacePrefix = :namespace] : 
	[SELECT Name, NamespacePrefix, SystemModStamp FROM StaticResource WHERE Name = :resourceName] ;
		if(resourceList.size() == 1){
			String nm = resourceList[0].NamespacePrefix;
		return '/resource/' + resourceList[0].SystemModStamp.getTime() + '/' + (nm != null && nm != '' ? nm + '__' : '') + resourceName; 
		}
		return '';
	}
}