force-app/main/default/objects/Order/fields/DateSentToSII__c.field-meta.xml
<CustomField>
    <fullName>DateSentToSII__c</fullName>
    <label>Data Invio al SII</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku</fullName>
            </value>
            <value>
                <fullName>In attesa tempi di ripensamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_BA_SendOrderToSii.cls
/*Author: Edoardo Zanatta
* Date: 18/01/2022
 */
@SuppressWarnings('PMD.AvoidDebugStatements')
public with sharing class HDT_BA_SendOrderToSii implements Database.Batchable<sObject>, Database.AllowsCallouts {

    public Iterable<sObject> start(Database.BatchableContext bc) {

        Date tday = System.today();
        List <Order> orderList = new List <Order>();

        orderList = [SELECT id, Phase__c, DateSentToSII__c FROM Order WHERE Phase__c = 'In attesa tempi di ripensamento' AND DateSentToSII__c <= :tday];
        return orderList;
    }

    public void execute(Database.BatchableContext bc, List<Order> scope){
        List<Order> orderToUpdate = new List<Order>();
        for(Order ord : scope){
            ord.Phase__c = 'Comunicazione verso Heroku';
            orderToUpdate.add(ord);
        }
        HDT_UTL_DatabaseService.updateSObject(scope);
    }
    
    public void finish(Database.BatchableContext bc){
        System.debug(LoggingLevel.DEBUG, 'Batch SendOrderToSii Completed');
    }    
}