force-app/main/default/objects/Order/fields/DiscardReason__c.field-meta.xml
<CustomField>
    <fullName>DiscardReason__c</fullName>
    <label>Causale Ultimo Scarto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__CalloutTemplate__c/wrts_prcgvr__CalloutTemplate__c.object-meta.xml
<CustomObject>
    <description>Available selective callout templates</description>
    <label>Callout Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callout Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__CalloutTemplate__c/fields/wrts_prcgvr__Structure__c.field-meta.xml
<CustomField>
    <fullName>wrts_prcgvr__Structure__c</fullName>
    <label>Structure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hierarchy</fullName>
            </value>
            <value>
                <fullName>Flat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_WS_SalesApexCalloutAction.cls
/**​
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)​
* @date 13/04/2021
* @description HDT_WS_SalesApexCalloutAction – Callout action for custom behavior of Sales Phase Manager
* @history Inserire Nome Cognome – Data Modifica – Descrizione della modifica​
*/
global class HDT_WS_SalesApexCalloutAction implements wrts_prcgvr.Interfaces_1_0.IApexCalloutAction {
    global Object execute(Object args) {
        Map<String,Object> argsMap = (Map<String,Object>) args;
        SObject transition = (SObject) argsMap.get('transition'); //phase transition
        String idTemplate = (String)transition.get('wrts_prcgvr__CalloutTemplate__c');
        wrts_prcgvr__CalloutTemplate__c tm = [select id, wrts_prcgvr__Code__c, wrts_prcgvr__ConfigurationFile__c, wrts_prcgvr__IncludeNullFields__c,wrts_prcgvr__ObjectType__c, wrts_prcgvr__Structure__c from wrts_prcgvr__CalloutTemplate__c where wrts_prcgvr__Code__c = :idTemplate][0];
        SObject action = (SObject) argsMap.get('action'); //phase transition detail
        String method = (String) argsMap.get('method');
        Sobject obj = (sObject) argsMap.get('sender');
        wrts_prcgvr.MRR_1_0.field headerAddValue = new  wrts_prcgvr.MRR_1_0.field();
        headerAddValue.fieldType = 'STRING';
        headerAddValue.name = 'PROCESS_CATEGORY';
        headerAddValue.value = 'sales';
        list<wrts_prcgvr.MRR_1_0.field> headerAttributetoAdd = new list<wrts_prcgvr.MRR_1_0.field>{headerAddValue};
        Object templateMap = argsMap.get('templateMap');
        Map<String,String> parameters = (Map<String,String>)argsMap.get('parameters');

        //custom logic ...
       
        System.debug('********INPUTFIELD:' + argsMap);
        
        System.debug('********tem:' + idTemplate);
        
        System.debug('********sender:' + obj);
        // Aggiungere if basato su Method e parte static nell header struttura ad oggetto
        
        if('SwitchInEECreaRich'.equalsIgnoreCase(method) || 'SwitchInGasCreaRich'.equalsIgnoreCase(method)) {
            //////////// Recupero endpoint in base a contesto di oggetto
            wrts_prcgvr.Interfaces_1_0.IEndpointRulesIntegration endpointUtils = ( wrts_prcgvr.Interfaces_1_0.IEndpointRulesIntegration)  wrts_prcgvr.VersionManager.newClassInstance('EndpointRulesIntegration');
            String endpoint = endpointUtils.getEndpoint(obj);
            System.debug('********endpoint:' + endpoint);
        
            //////////// genero MRR per il payload del servizio
            Map<String,Object> inputTemplateFunction = new Map<String,Object>();
            inputTemplateFunction.put('sender',obj);
            inputTemplateFunction.put('template',tm);
            inputTemplateFunction.put('parameters',parameters);
        
            wrts_prcgvr.Interfaces_1_0.ICalloutTemplateMng templateEngine = (wrts_prcgvr.Interfaces_1_0.ICalloutTemplateMng) wrts_prcgvr.VersionManager.newClassInstance('CalloutTemplateMng');
            Object objTemp = templateEngine.getTemplate(inputTemplateFunction);
            //inputTemplateFunction.put('templateObject',objTemp);
            Map<String,Object> templateReturn = (Map<String,Object>)templateEngine.applyTemplate(objTemp);
            wrts_prcgvr.MRR_1_0.MultiRequest multirequestObj = (wrts_prcgvr.MRR_1_0.MultiRequest)templateReturn.get('multirequest');
            multirequestObj.requests[0].header.fields = headerAttributetoAdd;
        
            System.debug('********MRRequest:' + multirequestObj);
        
            ///////////// instanzio e effettuo la chiamata con la request
            Map<String,Object> inputClientFunction = new Map<String,Object>();
            inputClientFunction.put('endpoint',endpoint);
            inputClientFunction.put('timeout',120);
            inputClientFunction.put('payload',multirequestObj);
            inputClientFunction.put('clientType','REST');
            inputClientFunction.put('contentType','application/json');
            wrts_prcgvr.Interfaces_1_0.ICalloutClient client = (wrts_prcgvr.Interfaces_1_0.ICalloutClient) wrts_prcgvr.VersionManager.newClassInstance ('CalloutClient');
        
            try{

                map<String,String> fieldValueResponse = new map<String,String>();
                wrts_prcgvr.MRR_1_0.MultiResponse responseService = (wrts_prcgvr.MRR_1_0.MultiResponse)client.send(inputClientFunction);

                System.debug('********MRRequest:' + responseService);
                wrts_prcgvr.MRR_1_0.WObject objResponse = responseService.responses[0].objects[0];
                for(wrts_prcgvr.MRR_1_0.field field : objResponse.fields){
                    fieldValueResponse.put(field.name,field.value);
                }
                if(fieldValueResponse.get('result') != null){
                    Order ord = new Order();
                    ord.id = (id)obj.get('Id');
                    if('OK'.equalsIgnoreCase(fieldValueResponse.get('result'))){
                        System.debug('********INSIDE RESULT OK');
                        if(fieldValueResponse.get('FASE') != null){
                            System.debug('********INSIDE FASE NOT NULL');
                            ord.Phase__c = fieldValueResponse.get('FASE');
                            System.debug('********AFTER UPDATE');
                        }
                    }
                    else{
                        ord.DiscardReason__c = fieldValueResponse.get('errorMessage');
                        ord.Phase__c = 'Comunicazione verso Heroku KO';
                    }
                    HDT_SRV_Order ordSrv = new HDT_SRV_Order();
                    ordSrv.updateRecord(ord);
                }

            } catch(Exception e ) {
                System.debug('ERRORE RESPONSE 500');
            }
        }
        
       wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse response = new wrts_prcgvr.ApexActionIntegration_1_0.CalloutResponse();
        response.success = true;
        response.message = 'OK';
        return response;
  		//return responseService;
    }

}