force-app/main/default/objects/Order/fields/HerokuPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>HerokuPracticeCode__c</fullName>
    <label>Codice Pratica Heroku</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <label>Tipo Fornitura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se l&apos;offerta è Billabile</description>
    <label>Billabile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <label>Tipo Fornitura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestico</fullName>
            </value>
            <value>
                <fullName>Non Domestico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service26Config__c/Service26Config__c.object-meta.xml
<CustomObject>
    <description>Oggetto per memorizzare la tabella per il service 26</description>
    <label>Servizio26 Config</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Servizio26 Config</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servizio26 Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service26Config__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Etichetta campo da inviare nella response, può contenere una stringa o un campo del product2 da valutare a runtime</description>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service26Config__c/fields/Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Occurrence__c</fullName>
    <description>Numero di occorrenza, una colonna della tabella 26 utile ad identificare i dati corretti da inviare</description>
    <label>Occorrenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service26Config__c/fields/Operando__c.field-meta.xml
<CustomField>
    <fullName>Operando__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Gerarchica che associa un operando alle corrispettive posizioni</description>
    <label>Operando</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Posizione</value>
        </filterItems>
        <filterItems>
            <field>Service26Config__c.Type__c</field>
            <operation>equals</operation>
            <value>Operando</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service26Config__c</referenceTo>
    <relationshipLabel>Servizio26 Configs</relationshipLabel>
    <relationshipName>Servizio26_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service26Config__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <description>Famiglia di prodotti</description>
    <label>Famiglia Prodotti</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sconto Eur/Giorno</fullName>
            </value>
            <value>
                <fullName>Bonus Eur/Mese</fullName>
            </value>
            <value>
                <fullName>Bonus Eur/Giorno</fullName>
            </value>
            <value>
                <fullName>Sconto Esenzione</fullName>
            </value>
            <value>
                <fullName>Contributo Eur/kWh</fullName>
            </value>
            <value>
                <fullName>Bonus Eur/Kwh</fullName>
            </value>
            <value>
                <fullName>Bonus Percentuale</fullName>
            </value>
            <value>
                <fullName>Sconto Percentuale</fullName>
            </value>
            <value>
                <fullName>Contributo Eur/kW</fullName>
            </value>
            <value>
                <fullName>Contributo Eur/Giorno</fullName>
            </value>
            <value>
                <fullName>Contributo Eur/Mese</fullName>
            </value>
            <value>
                <fullName>VAS Fatturabili</fullName>
            </value>
            <value>
                <fullName>Bonus Eur/SMC</fullName>
            </value>
            <value>
                <fullName>Contributo Eur/SMC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service26Config__c/fields/SapCode__c.field-meta.xml
<CustomField>
    <fullName>SapCode__c</fullName>
    <description>Contiene codice sap da inviare nel DTO</description>
    <label>Codice Sap</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service26Config__c/fields/Servizio__c.field-meta.xml
<CustomField>
    <fullName>Servizio__c</fullName>
    <description>Tipo di servizio (Elettrico o Gas)</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Energia Elettrica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service26Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Distingue il tipo di informazione contenuta, se è un operando o una posizione collegata</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operando</fullName>
            </value>
            <value>
                <fullName>Posizione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <label>Tipo Fornitura</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CommoditySector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SupplyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Non Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>A-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>B-Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>C-Aziende di pubblica utilita</fullName>
    </customValue>
    <customValue>
        <fullName>D-Altri usi</fullName>
    </customValue>
    <customValue>
        <fullName>Uso domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso diverso da domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Usi industriali che scaricano in pubblica fognatura</fullName>
    </customValue>
    <customValue>
        <fullName>Altri usi</fullName>
    </customValue>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <masterLabel>Tipo Fornitura</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_ServiceTwentySixTst.cls
/**
 * Header of the class "HDT_UTL_ServiceTwentySixTst"
 * @author Cesare Bagnolini, cesare.bagnolini@webresults.it
 * @version 1.0
 * @description: Apex Test Class of the relative Apex Class "HDT_UTL_ServiceTwentySix"
 * @history
 * @Created 02/11/2021
 * Modified By:
 **/
@isTest
public class HDT_UTL_ServiceTwentySixTst {
    
    private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
    
    @TestSetup static void makedata(){
        
        HDT_UTL_DataFactoryTst.pClickInstance();
		HDT_UTL_DataFactoryTst.pClickOrderPhase();
        
        List<Account> accs = HDT_UTL_DataFactoryTst.createAccountBusiness(1,true,'HERA COMM','Azienda','Aziende SME');
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<Sale__c> sales = HDT_UTL_DataFactoryTst.createSale(1, true, accs[0].id, 'Bozza');
        
        List<ServicePoint__c> points = HDT_UTL_DataFactoryTst.createServicePoint(1, false);
        points[0].CommoditySector__c = 'GAS';
        insert points;
        
        List<Order> orders = HDT_UTL_DataFactoryTst.createOrderWithPricebook(1, false, accs[0].id, sales, pricebookId);
        orders[0].ServicePointCode__c = 'servicepointcode';
        orders[0].HerokuPracticeCode__c = 'herokucode';
        orders[0].SupplyType__c = 'Domestico';
        orders[0].ServicePoint__c = points[0].id;
        insert orders;
        
        List<Product2> prods = HDT_UTL_DataFactoryTst.createProduct2(1, false);
        prods[0].Family = 'VAS Fatturabili';
        insert prods;
        
        List<PricebookEntry> entries = HDT_UTL_DataFactoryTst.createPricebookEntry(prods, true, pricebookId);
        
        HDT_UTL_DataFactoryTst.createOrderItem(1, true, orders[0].id, points[0].id, prods[0].id, entries[0].id);
        
        List<Service26Config__c> configs = HDT_UTL_DataFactoryTst.createService26Config(2, false);
        configs[0].Type__c = 'Posizione';
        configs[0].ProductFamily__c = 'VAS Fatturabili';
        configs[0].Servizio__c = 'GAS';
        configs[0].Occurrence__c = 1;
        configs[0].Field__c = 'billable__c';
        configs[1].Field__c = 'billable__c';
        configs[1].SapCode__c = 'sapcode1';
        configs[1].Type__c = 'Operando';
        configs[1].ProductFamily__c = 'VAS Fatturabili';
        configs[1].Servizio__c = 'GAS';
        configs[1].Occurrence__c = 1;
        insert configs;
        
        configs[0].Operando__c = configs[1].id;
        update configs;
    }
    
    @isTest static void testStartProcess(){
        
        HDT_UTL_ServiceTwentySix.HDT_WRP_DtoServiceTwentySix res = new HDT_UTL_ServiceTwentySix.HDT_WRP_DtoServiceTwentySix();
        
        Id orderId = [Select id FROM Order][0].id;
        
        HDT_UTL_ServiceTwentySix service = new HDT_UTL_ServiceTwentySix();
        
        res = service.startProcess(orderId);
        
        System.assertEquals('herokucode', res.documentKey, 'HDT_UTL_ServiceTwentySix did not work correctly');
        System.assertNotEquals(null, res, 'HDT_UTL_ServiceTwentySix did not work correctly');
        
    }
    
    @isTest static void testGetFieldValueBlank(){
        
        HDT_UTL_ServiceTwentySix service = new HDT_UTL_ServiceTwentySix();
        
        String res = service.getFieldValue('', null, null);
        
        System.assertEquals('', res, 'getFieldValue did not work correctly');
        System.assertNotEquals(null, res, 'getFieldValue did not work correctly');                
    }    		
}