force-app/main/default/objects/Order/fields/MethodSignedAccepted__c.field-meta.xml
<CustomField>
    <fullName>MethodSignedAccepted__c</fullName>
    <label>Conferma contratto cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IWR</fullName>
            </value>
            <value>
                <fullName>Comfort call</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Attiva</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VocalOrderPublicConfirm__c/VocalOrderPublicConfirm__c.object-meta.xml
<CustomObject>
    <label>Validazione Pagina Pubblica</label>
    <nameField>
        <displayFormat>Valid-{00000000}</displayFormat>
        <label>Validazione Pagina Pubblica Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Validazione Pagina Pubblica</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VocalOrderPublicConfirm__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Validazione Pagina Pubblica</relationshipLabel>
    <relationshipName>Validazione_Pagina_Pubblica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VocalOrderPublicConfirm__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuova</fullName>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_BA_PublicValidationTst.cls
/**
 * @author Sabina Levonja (sabina.levonja@dunegroup.it)
 * @date 12/10/2021
 * @description HDT_BA_PublicValidation Test Class
 * @history Sabina Levonja – 12/10/2021 – Created Class
 */

@isTest
public with sharing class HDT_BA_PublicValidationTst {

    @TestSetup
    static void setup(){
        
		HDT_UTL_DataFactoryTst.pClickOrderPhase();
        List<Account> accList=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
		List<Contact> conList = HDT_UTL_DataFactoryTst.createContact(1,true,accList[0].Id);
		List<Sale__c> sales=HDT_UTL_DataFactoryTst.createSale(1, true, accList[0].Id, 'Attiva');
		List<Order> orders=HDT_UTL_DataFactoryTst.createOrder(1, true, accList[0].Id, 'Bozza');
		HDT_UTL_DataFactoryTst.createChildOrder(1, true, accList[0].Id, sales, orders[0].Id, conList[0].Id);
        HDT_UTL_DataFactoryTst.createVocalOrderPublicConfirm(1,true,'Nuova',orders[0].Id);
	}
    @isTest
    public static void testBatch() {
        Test.startTest();

        HDT_BA_PublicValidation publicVal = new HDT_BA_PublicValidation();
        Database.executeBatch(publicVal);
                
        Test.stopTest();
        
        Order ord = [SELECT Id, MethodSignedAccepted__c from Order limit 1];
        VocalOrderPublicConfirm__c vcOrd= [SELECT Id,Order__c,Status__c,Createddate FROM VocalOrderPublicConfirm__c limit 1];

        System.assertEquals('web assistito', ord.MethodSignedAccepted__c ,'The MethodSignedAccepted__c field has not been updated');
        System.assertNotEquals('Nuova', vcOrd.Status__c ,'The Status__c of VocalOrderPublicConfirm__c has not been updated');

    }
    
}