force-app/main/default/objects/HDT_Generic_Record_Selection__mdt/HDT_Generic_Record_Selection__mdt.object-meta.xml
<CustomObject>
    <label>HDT Generic Record Selection</label>
    <pluralLabel>HDT Generic Records Selection</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_Generic_Record_Selection__mdt/fields/Columns__c.field-meta.xml
<CustomField>
    <fullName>Columns__c</fullName>
    <label>Columns</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HDT_Generic_Record_Selection__mdt/fields/Default_Search_Key__c.field-meta.xml
<CustomField>
    <fullName>Default_Search_Key__c</fullName>
    <label>Default Search Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_Generic_Record_Selection__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>Id is quered by default, don&apos;t include here.</description>
    <inlineHelpText>Id is quered by default, don&apos;t include here.</inlineHelpText>
    <label>Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_Generic_Record_Selection__mdt/fields/Max_Rows__c.field-meta.xml
<CustomField>
    <fullName>Max_Rows__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Max Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HDT_Generic_Record_Selection__mdt/fields/Row_Limit__c.field-meta.xml
<CustomField>
    <fullName>Row_Limit__c</fullName>
    <label>Row Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_Generic_Record_Selection__mdt/fields/Where_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Where_Conditions__c</fullName>
    <label>Where Conditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_BillingProfileSelection.cls
public with sharing class HDT_QR_BillingProfileSelection {
    public List<HDT_Generic_Record_Selection__mdt>  getConfigurationByName(String searchKey) {
        try{
            List<HDT_Generic_Record_Selection__mdt> config = [SELECT Id, Columns__c,Default_Search_Key__c,Fields__c,Max_Rows__c,Row_Limit__c,sObject__c,Where_Conditions__c 
            FROM HDT_Generic_Record_Selection__mdt WHERE DeveloperName =:searchKey WITH SECURITY_ENFORCED];
            return config;
        }catch(Exception ex){
            throw ex;
        }
    }
}