force-app/main/default/objects/Range__c/Range__c.object-meta.xml
<CustomObject>
    <description>Oggetto per la gestione delle fasce di consumo</description>
    <label>Fascia</label>
    <nameField>
        <displayFormat>RNG-{00000000}</displayFormat>
        <label>Fascia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fasce</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SlaAdministration__c/SlaAdministration__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione, dove sono definiti gli SLA ed il relativo contesto di applicazione</description>
    <label>Amministrazione SLA</label>
    <nameField>
        <label>Nome SLA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amministrazione SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SlaAdministration__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <label>Intervallo SLA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/RangeType__c.field-meta.xml
<CustomField>
    <fullName>RangeType__c</fullName>
    <label>Tipo intervallo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Giorni Solari</fullName>
                <default>true</default>
                <label>Giorni Solari</label>
            </value>
            <value>
                <fullName>Giorni Lavorativi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaTracking__c/SlaTracking__c.object-meta.xml
<CustomObject>
    <label>Tracciamento SLA</label>
    <nameField>
        <displayFormat>SLA-{0000}</displayFormat>
        <label>Tracciamento SLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracciamento SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SlaTracking__c/fields/EndDateSolarDays__c.field-meta.xml
<CustomField>
    <fullName>EndDateSolarDays__c</fullName>
    <inlineHelpText>Previsione della data di fine lavorazione calcolata in giorni solari</inlineHelpText>
    <label>Data fine [gg solari]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <inlineHelpText>Data effettiva di fine lavorazione</inlineHelpText>
    <label>Data fine intervallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/EndDateWorkingDays__c.field-meta.xml
<CustomField>
    <fullName>EndDateWorkingDays__c</fullName>
    <inlineHelpText>Previsione della data di fine lavorazione calcolata in giorni lavorativi</inlineHelpText>
    <label>Data fine [gg lavorativi]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <formula>SlaAdministration__r.Range__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Intervallo SLA indicato nella regola</inlineHelpText>
    <label>Intervallo SLA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/RangeType__c.field-meta.xml
<CustomField>
    <fullName>RangeType__c</fullName>
    <formula>IF(ISPICKVAL(SlaAdministration__r.RangeType__c, &apos;Giorni Solari&apos;),&apos;Giorni Solari&apos;,&apos;Giorni Lavorativi&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo intervallo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/SlaAdministration__c.field-meta.xml
<CustomField>
    <fullName>SlaAdministration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Amministrazione SLA</label>
    <referenceTo>SlaAdministration__c</referenceTo>
    <relationshipLabel>Tracciamento SLA</relationshipLabel>
    <relationshipName>SlaTrackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/SlaValue__c.field-meta.xml
<CustomField>
    <fullName>SlaValue__c</fullName>
    <inlineHelpText>Indica il tempo di lavorazione in giorni alla chiusura del tracking</inlineHelpText>
    <label>Tempo gestione [gg]</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Data inizio intervallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aperto</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalHolidaysCalendar__c/TechnicalHolidaysCalendar__c.object-meta.xml
<CustomObject>
    <label>Calendario Festività Tecnico</label>
    <nameField>
        <displayFormat>CFT-{00000}</displayFormat>
        <label>Calendario Festività Tecnico Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendari Festività Tecnico</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalHolidaysCalendar__c/fields/HolidayDate__c.field-meta.xml
<CustomField>
    <fullName>HolidayDate__c</fullName>
    <label>Data Fesitività</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/HDT_UTL_SlaTracking.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public inherited sharing class HDT_UTL_SlaTracking {

    public static void calculateSlaRealValue(List<SlaTracking__c> slaTrackingFromTrigger){

        List<Id> adminRuleIds = new List<Id>();
        List<SlaTracking__c> slaTrackingToElaborate = new List<SlaTracking__c>();
        Map<Id, SlaAdministration__c> adminRuleMap;

        try{
            for(SlaTracking__c track : slaTrackingFromTrigger){

                //if(track.Status__c.equalsIgnoreCase('Chiuso')){
                //    continue;
                //}

                if(track.StartDateTime__c != null && track.EndDateTime__c != null){
                    adminRuleIds.add(track.SlaAdministration__c);
                    slaTrackingToElaborate.add(track);
                }
            }

            if(slaTrackingToElaborate.size()==0){
                return;
            }

            List<SlaAdministration__c> slaAdminList = HDT_QR_SlaTracking.getSlaAdminList(adminRuleIds);
            List<TechnicalHolidaysCalendar__c> holidayList = HDT_QR_SlaTracking.getHolidaysList();

            if(slaAdminList.size() > 0){
                adminRuleMap = new Map<Id, SlaAdministration__c>(slaAdminList);
            }

            String rangeType;
            Date startDate;
            Date endDate;
            for(SlaTracking__c track : slaTrackingToElaborate){

                //startDate = convertDateTime(track.StartDateTime__c);
                //endDate = convertDateTime(track.EndDateTime__c);
                //track.SlaValue__c = startDate.daysBetween(endDate);//+1;
                track.SlaValue__c = calculateSlaValue(track.StartDateTime__c, track.EndDateTime__c);

                if(adminRuleMap.containsKey(track.SlaAdministration__c)){
                    rangeType = adminRuleMap.get(track.SlaAdministration__c).RangeType__c;
                    if(String.isNotEmpty(rangeType) && rangeType.equalsIgnoreCase('Giorni Lavorativi')){
                        track.SlaValue__c = calculateWorkingDaysInteger(startDate, Integer.valueOf(track.SlaValue__c), holidayList);
                    }
                }

            }
        } catch(Exception e){
            System.debug('>>> ERROR calculate SlaValue__c -> ' + e.getMessage());
        }
    }
    
    public static void calculateSlaForecastValue(List<SlaTracking__c> slaTrackingFromTrigger){

        List<Id> adminRuleIds = new List<Id>();
        List<SlaTracking__c> slaTrackingToElaborate = new List<SlaTracking__c>();
        Map<Id, SlaAdministration__c> adminRuleMap;

        for(SlaTracking__c track : slaTrackingFromTrigger){
            if(track.StartDateTime__c != null){
                adminRuleIds.add(track.SlaAdministration__c);
                slaTrackingToElaborate.add(track);
            }
        }

        List<SlaAdministration__c> slaAdminList = HDT_QR_SlaTracking.getSlaAdminList(adminRuleIds);
        List<TechnicalHolidaysCalendar__c> holidayList = HDT_QR_SlaTracking.getHolidaysList();

        if(slaAdminList.size() > 0){
            adminRuleMap = new Map<Id, SlaAdministration__c>(slaAdminList);
        }

        Integer slaRange;
        Date startDate;
        Date endDate;
        for(SlaTracking__c track : slaTrackingToElaborate){
            startDate = convertDateTime(track.StartDateTime__c);
            slaRange = Integer.valueOf(adminRuleMap.get(track.SlaAdministration__c).Range__c);
            track.EndDateSolarDays__c = startDate.addDays(slaRange);
            //slaRange = calculateWorkingDays(track.StartDateTime__c, slaRange, holidayList);
            track.EndDateWorkingDays__c = calculateWorkingDays(startDate, slaRange, holidayList);
        }

    }

    public static Date calculateWorkingDays(Date startDate, Integer slaRange, List<TechnicalHolidaysCalendar__c> holidayList){
        Set<Date> holidays = new Set<Date>();
        for(TechnicalHolidaysCalendar__c holiday : holidayList){
            if(holiday.HolidayDate__c >= startDate){
                holidays.add(holiday.HolidayDate__c);
            }
        }    
    
        Date finalDate = startDate;
        Integer direction = slaRange < 0 ? -1 : 1;
        while(slaRange != 0){
            finalDate = finalDate.addDays(direction);
            if(!isWeekend(finalDate) && !holidays.contains(finalDate)){
                slaRange -= direction;
            }
        }
        return finalDate;
    }

    private static Boolean isWeekend(Date myDate){
        String myDateString = Datetime.newInstance(myDate.year(), myDate.month(),myDate.day()).format('EEE');
        return 'Sat'.equals(myDateString) || 'Sun'.equals(myDateString);
    }

    public static Date convertDateTime(DateTime dt){
        return Date.newinstance(dt.year(), dt.month(), dt.day());
    }

    public static Integer calculateWorkingDaysInteger(Date startDate, Integer diff, List<TechnicalHolidaysCalendar__c> holidayList){

        Set<String> dayToAvoid = new Set<String>{'Saturday', 'Sunday', 'Sabato', 'Domenica'};
        Set<Date> holidays = new Set<Date>();
        for(TechnicalHolidaysCalendar__c holiday : holidayList){
            if(holiday.HolidayDate__c >= startDate){
                holidays.add(holiday.HolidayDate__c);
            }
        }  

        String dayOfWeek;
        Integer slaValue = 0;
        DateTime dt;
        Boolean isWeekEnd;
        Boolean isHoliday;
        for(Integer day=0; day<diff; day++){
            dt = startDate.addDays(day);
            dayOfWeek = dt.format('EEEE');

            isWeekEnd = dayToAvoid.contains(dayOfWeek);
            isHoliday = holidays.contains(convertDateTime(dt));
            

            if(!isWeekEnd && !isHoliday){
                //System.debug('>>> count');
                slaValue++;
            }
            //System.debug('>>> date ' + Date.valueOf(dt) + ' - ' + dayOfWeek + ' - slaValue ' + slaValue);
        }
        return slaValue;
    }

    //DateTime startDt = DateTime.newInstance(2023, 04, 06, 12, 00 , 00);
    //DateTime endDt = DateTime.newInstance(2023, 04, 07, 12, 00 , 01);
    //System.debug('>>>>>>>>> SLA ' + calculateSlaValue(startDt, endDt));
    public static Integer calculateSlaValue(DateTime startDatetime, DateTime endDatetime){
        Decimal timeStart = startDatetime.getTime();
        Decimal timeEnd = endDatetime.getTime();
        Decimal hours = (timeEnd - timeStart) / 3600000;
        Decimal days = hours / 24;
        System.debug('>>>>>>>>> days ' + days + ' - hours ' + hours);
        return (days < 1) ? 0 : (Integer)days.round(System.RoundingMode.UP);
    }

}