force-app/main/default/objects/LandRegistry__c/LandRegistry__c.object-meta.xml
<CustomObject>
    <description>Autonumber</description>
    <label>Dati Catastali</label>
    <nameField>
        <displayFormat>LR-{00000000}</displayFormat>
        <label>Documental Envelope Attachment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dati Catastali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LandRegistry__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Dati Catastali</relationshipLabel>
    <relationshipName>Dati_Catastali</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/CodeMissingRegistryData__c.field-meta.xml
<CustomField>
    <fullName>CodeMissingRegistryData__c</fullName>
    <description>Codice assenza dati catastali</description>
    <label>Codice assenza dati catastali</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>da RD</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Immobile non accatastato</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Immobile non accatastabile</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Dati non forniti dal titolare</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Forniture temporanee</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Condominio</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Non presenti in SIEBEL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/DestinationUsage__c.field-meta.xml
<CustomField>
    <fullName>DestinationUsage__c</fullName>
    <description>Destinazione Uso</description>
    <label>Destinazione Uso</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>da RD</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Uso abitativo</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Immobile tenuto a disposizione</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Uso commerciale</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Locali adibiti a box</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Altri usi</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/LegalCity__c.field-meta.xml
<CustomField>
    <fullName>LegalCity__c</fullName>
    <description>Comune amministrativo</description>
    <label>Comune amministrativo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup all&apos;Order</description>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Dati Catastali</relationshipLabel>
    <relationshipName>Dati_Catastali</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/ParticleSheet__c.field-meta.xml
<CustomField>
    <fullName>ParticleSheet__c</fullName>
    <description>Particella</description>
    <label>Particella</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Provincia ubicazione</description>
    <label>Provincia ubicazione</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/RegistryCategory__c.field-meta.xml
<CustomField>
    <fullName>RegistryCategory__c</fullName>
    <description>Categoria Catastale</description>
    <label>Categoria Catastale</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/RegistryCity__c.field-meta.xml
<CustomField>
    <fullName>RegistryCity__c</fullName>
    <description>Comune catastale</description>
    <label>Comune catastale</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/RegistryCityCode__c.field-meta.xml
<CustomField>
    <fullName>RegistryCityCode__c</fullName>
    <description>Codice comune catastale</description>
    <label>Codice comune catastale</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/RegistrySurface__c.field-meta.xml
<CustomField>
    <fullName>RegistrySurface__c</fullName>
    <description>Superficie Catastale</description>
    <label>Superficie Catastale</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup al Service Point</description>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Dati Catastali</relationshipLabel>
    <relationshipName>Dati_Catastali</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/Sheet__c.field-meta.xml
<CustomField>
    <fullName>Sheet__c</fullName>
    <description>Foglio</description>
    <label>Foglio</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/Subaltern__c.field-meta.xml
<CustomField>
    <fullName>Subaltern__c</fullName>
    <description>Subalterno</description>
    <label>Subalterno</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Qualifica Titolare</description>
    <label>Qualifica Titolare</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Proprietario</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Usufruttuario</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Locatario</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Titolare di altri diritto su immobile</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <description>Tipo unita</description>
    <label>Tipo unita</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Fabbricato</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Terreno</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LandRegistry__c/fields/UrbanSection__c.field-meta.xml
<CustomField>
    <fullName>UrbanSection__c</fullName>
    <description>Sezione urbana</description>
    <label>Sezione urbana</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LandRegistry__c/recordTypes/HDT_RT_DatiCatastali_PraticaTARI.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_DatiCatastali_PraticaTARI</fullName>
    <active>true</active>
    <label>DatiCatastali - Pratica Ambiente</label>
</RecordType>

force-app/main/default/objects/LandRegistry__c/recordTypes/HDT_RT_DatiCatastali_TARI.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_DatiCatastali_TARI</fullName>
    <active>true</active>
    <label>HDT_RT_DatiCatastali_TARI</label>
</RecordType>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_LandRegistry.cls
/*
    @Author:  Carmine Scalise (carmine.scalise@webresults.it)
    @CreatedDate:  10/05/2022
*/

public inherited sharing class HDT_QR_LandRegistry {

    public list<LandRegistry__c> getPraticaTARILandRegistryByOrderIds(list<Id> listId) {
        Id rtIdTARI = Schema.SObjectType.LandRegistry__c.getRecordTypeInfosByName().get('HDT_RT_DatiCatastali_PraticaTARI').getRecordTypeId();
	    list<LandRegistry__c> ldRegistry = [
            SELECT Id, Name, CodeMissingRegistryData__c, DestinationUsage__c, RegistryCity__c, RegistryCityCode__c, 
            LegalCity__c, Province__c, UnitType__c, UrbanSection__c, Sheet__c, ParticleSheet__c, Subaltern__c, 
            RegistryCategory__c, RegistrySurface__c, Title__c, ServicePoint__r.ServicePointCode__c
	        FROM LandRegistry__c 
	        WHERE Order__c IN :listId
	        AND RecordTypeId = :rtIdTARI
            WITH SECURITY_ENFORCED];
        return ldRegistry;
    }
    public list<LandRegistry__c> getPraticaTARILandRegistryByCaseIds(list<Id> listId) {
        Id rtIdTARI = Schema.SObjectType.LandRegistry__c.getRecordTypeInfosByName().get('HDT_RT_DatiCatastali_PraticaTARI').getRecordTypeId();
	    list<LandRegistry__c> ldRegistry = [
            SELECT Id, Name, CodeMissingRegistryData__c, DestinationUsage__c, RegistryCity__c, RegistryCityCode__c, 
            LegalCity__c, Province__c, UnitType__c, UrbanSection__c, Sheet__c, ParticleSheet__c, Subaltern__c, 
            RegistryCategory__c, RegistrySurface__c, Title__c, ServicePoint__r.ServicePointCode__c
	        FROM LandRegistry__c 
	        WHERE Case__c IN :listId
	        AND RecordTypeId = :rtIdTARI
            WITH SECURITY_ENFORCED];
        return ldRegistry;
    }
    public list<LandRegistry__c> getTARILandRegistryByServicePointIds(list<Id> listId) {
        Id rtIdTARI = Schema.SObjectType.LandRegistry__c.getRecordTypeInfosByName().get('HDT_RT_DatiCatastali_TARI').getRecordTypeId();
	    list<LandRegistry__c> ldRegistry = [
            SELECT Id, Name, CodeMissingRegistryData__c, DestinationUsage__c, RegistryCity__c, RegistryCityCode__c, 
            LegalCity__c, Province__c, UnitType__c, UrbanSection__c, Sheet__c, ParticleSheet__c, Subaltern__c, 
            RegistryCategory__c, RegistrySurface__c, Title__c, ServicePoint__r.ServicePointCode__c
	        FROM LandRegistry__c 
	        WHERE ServicePoint__c IN :listId
	        AND RecordTypeId = :rtIdTARI
            WITH SECURITY_ENFORCED];
        return ldRegistry;
    }
}