force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/HDT_FiltriProcessiSelFornitura__mdt.object-meta.xml
<CustomObject>
    <label>FiltriProcessiSelFornitura</label>
    
    <pluralLabel>FiltriProcessiSelFornitura</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/fields/ContrattiCliente__c.field-meta.xml
<CustomField>
    <fullName>ContrattiCliente__c</fullName>
    <label>Contratti Cliente</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/fields/Disalimentabile__c.field-meta.xml
<CustomField>
    <fullName>Disalimentabile__c</fullName>
    <label>Disalimentabile</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/fields/FornitureCliente__c.field-meta.xml
<CustomField>
    <fullName>FornitureCliente__c</fullName>
    <label>Forniture Cliente</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/fields/StatoContratto__c.field-meta.xml
<CustomField>
    <fullName>StatoContratto__c</fullName>
    <label>Stato Contratto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/fields/StatoFornitura__c.field-meta.xml
<CustomField>
    <fullName>StatoFornitura__c</fullName>
    <label>Stato Fornitura</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/fields/TipoProcesso__c.field-meta.xml
<CustomField>
    <fullName>TipoProcesso__c</fullName>
    <label>Tipo Processo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FiltriProcessiSelFornitura__mdt/fields/TipoServizio__c.field-meta.xml
<CustomField>
    <fullName>TipoServizio__c</fullName>
    <label>Tipo Servizio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_FiltriProcessi.cls
public with sharing class HDT_QR_FiltriProcessi {
    private static HDT_SRV_Contract contractSrv = new HDT_SRV_Contract();
    
    public HDT_QR_FiltriProcessi() {

    }

    @AuraEnabled
    public static HDT_FiltriProcessiSelFornitura__mdt getCustomMetadata(String processType){
        contractSrv.checkReadAccess('Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, ContrattiCliente__c, Disalimentabile__c, StatoContratto__c, StatoFornitura__c, TipoProcesso__c, TipoServizio__c, FornitureCliente__c');
        HDT_FiltriProcessiSelFornitura__mdt processi = new HDT_FiltriProcessiSelFornitura__mdt();
        system.debug('processType : '+processType);
        processi = [SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, ContrattiCliente__c, Disalimentabile__c, StatoContratto__c, StatoFornitura__c, TipoProcesso__c, TipoServizio__c, FornitureCliente__c FROM HDT_FiltriProcessiSelFornitura__mdt WHERE TipoProcesso__c=: processType ];
         return processi;
    }


    
}