force-app/main/default/objects/HDT_SegnalazioniAmbientali__mdt/HDT_SegnalazioniAmbientali__mdt.object-meta.xml
<CustomObject>
    <label>HDT_SegnalazioniAmbientali</label>
    <pluralLabel>HDT_SegnalazioniAmbientali</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_SegnalazioniAmbientali__mdt/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Materiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ABITI USATI</fullName>
                <label>Abiti usati</label>
            </value>
            <value>
                <fullName>AMIANTO</fullName>
                <label>Amianto</label>
            </value>
            <value>
                <fullName>AMIANTO/ETHERNIT</fullName>
                <label>Amianto/Ethernit</label>
            </value>
            <value>
                <fullName>ANIMALI D&apos;AFFEZIONE</fullName>
                <label>Animali d&apos;affezione</label>
            </value>
            <value>
                <fullName>BUCHE SU STRADA</fullName>
                <label>Buche su strada</label>
            </value>
            <value>
                <fullName>CADUTA CALCINACCI</fullName>
                <label>Caduta calcinacci</label>
            </value>
            <value>
                <fullName>CARCASSE ANIMALI</fullName>
                <label>Carcasse animali</label>
            </value>
            <value>
                <fullName>CARTA</fullName>
                <label>Carta</label>
            </value>
            <value>
                <fullName>CARTA/CARTONE</fullName>
                <label>Carta/Cartone</label>
            </value>
            <value>
                <fullName>CARTONE_SOLOAZIENDE</fullName>
                <label>Cartone_soloAziende</label>
            </value>
            <value>
                <fullName>CESTINI</fullName>
                <label>cestini</label>
            </value>
            <value>
                <fullName>CON RIMOZIONE</fullName>
                <label>Con rimozione</label>
            </value>
            <value>
                <fullName>DISTANZACASSONDADOMICILIOUT</fullName>
                <label>DistanzaCassonDaDomicilioUT</label>
            </value>
            <value>
                <fullName>ECOSELF (CARTA E PLASTICA)</fullName>
                <label>ECOSELF (carta e plastica)</label>
            </value>
            <value>
                <fullName>FANGOSI NON PERICOLOSI</fullName>
                <label>Fangosi non pericolosi</label>
            </value>
            <value>
                <fullName>FANGOSI PERICOLOSI</fullName>
                <label>Fangosi pericolosi</label>
            </value>
            <value>
                <fullName>FARMACI</fullName>
                <label>Farmaci</label>
            </value>
            <value>
                <fullName>FITOFARMACI</fullName>
            </value>
            <value>
                <fullName>INGOMBRANTI</fullName>
                <label>Ingombranti</label>
            </value>
            <value>
                <fullName>INGOMBRANTI+RAEE</fullName>
                <label>Ingombranti+Raee</label>
            </value>
            <value>
                <fullName>LATTINE</fullName>
                <label>Lattine</label>
            </value>
            <value>
                <fullName>LAVAGGIO/PULIZIA SEDE STRADALE</fullName>
                <label>Lavaggio/pulizia sede stradale</label>
            </value>
            <value>
                <fullName>LEGNO</fullName>
            </value>
            <value>
                <fullName>LEGNO_SOLOAZIENDE</fullName>
                <label>Legno_soloAziende</label>
            </value>
            <value>
                <fullName>LIQUIDI NON PERICOLOSI</fullName>
                <label>Liquidi non pericolosi</label>
            </value>
            <value>
                <fullName>LIQUIDI PERICOLOSI</fullName>
                <label>Liquidi pericolosi</label>
            </value>
            <value>
                <fullName>MACERIE</fullName>
                <label>Macerie</label>
            </value>
            <value>
                <fullName>MARCIAPIEDE</fullName>
                <label>Marciapiede</label>
            </value>
            <value>
                <fullName>MULTIMATERIALE</fullName>
                <label>Multimateriale</label>
            </value>
            <value>
                <fullName>NESSUN MATERIALE</fullName>
                <label>Nessun materiale</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_SegnalazioniAmbientali__mdt/fields/OperationGroup__c.field-meta.xml
<CustomField>
    <fullName>OperationGroup__c</fullName>
    <label>Gruppo Intervento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value><fullName>ALTRI SERVIZI-IUAS0001</fullName><default>true</default><label>ALTRI SERVIZI-IUAS0001</label></value>
            <value><fullName>ALTRI SERVIZI-IUAS0002</fullName><default>false</default><label>ALTRI SERVIZI-IUAS0002</label></value>
            <value><fullName>CIMITERIALI-IUIN0023</fullName><default>false</default><label>CIMITERIALI-IUIN0023</label></value>
            <value><fullName>DLGS_116/2020-IUAS0003</fullName><default>false</default><label>DLGS_116/2020-IUAS0003</label></value>
            <value><fullName>MOVIM.CONTENITORI TARIP-TARIG</fullName><default>false</default><label>MOVIM.CONTENITORI TARIP-TARIG</label></value>
            <value><fullName>MOVIMENTAZIONE CONTENITORI TCP</fullName><default>false</default><label>MOVIMENTAZIONE CONTENITORI TCP</label></value>
            <value><fullName>PULIZIA AREE PUBBLIC-IUPS0000</fullName><default>false</default><label>PULIZIA AREE PUBBLIC-IUPS0000</label></value>
            <value><fullName>PULIZIA AREE PUBBLIC-IUPS0002</fullName><default>false</default><label>PULIZIA AREE PUBBLIC-IUPS0002</label></value>
            <value><fullName>PULIZIA AREE PUBBLIC-IUPS0007</fullName><default>false</default><label>PULIZIA AREE PUBBLIC-IUPS0007</label></value>
            <value><fullName>RACCOLTA DIFFERENZIAT-IURD0023</fullName><default>false</default><label>RACCOLTA DIFFERENZIAT-IURD0023</label></value>
            <value><fullName>RACCOLTA INDIFFERENZ-IUIN0021</fullName><default>false</default><label>RACCOLTA INDIFFERENZ-IUIN0021</label></value>
            <value><fullName>SCARICHI ABUSIVI-IUPS0000</fullName><default>false</default><label>SCARICHI ABUSIVI-IUPS0000</label></value>
            <value><fullName>SERVIZI A PAG.CARCASS-IUAS0001</fullName><default>false</default><label>SERVIZI A PAG.CARCASS-IUAS0001</label></value>
            <value><fullName>SERVIZI A PAGAMENTO-IUAS0002</fullName><default>false</default><label>SERVIZI A PAGAMENTO-IUAS0002</label></value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_SegnalazioniAmbientali__mdt/fields/TypeOperation__c.field-meta.xml
<CustomField>
    <fullName>TypeOperation__c</fullName>
    <label>Tipo Intervento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value><fullName>CONSEGNA KIT PANNOLINI ECO</fullName><default>true</default><label>CONSEGNA KIT PANNOLINI ECO</label></value>
            <value><fullName>DISMISSIONE COMPOSTIERA</fullName><default>false</default><label>DISMISSIONE COMPOSTIERA</label></value>
            <value><fullName>LAMENTELE COMPORTAM OPERATORE</fullName><default>false</default><label>LAMENTELE COMPORTAM OPERATORE</label></value>
            <value><fullName>ODORI MEZZI/DOTAZIONE/IMPIANTI</fullName><default>false</default><label>ODORI MEZZI/DOTAZIONE/IMPIANTI</label></value>
            <value><fullName>RUMORI DI MEZZI/IMPIANTI</fullName><default>false</default><label>RUMORI DI MEZZI/IMPIANTI</label></value>
            <value><fullName>CONSEGNA PANNOLINI</fullName><default>false</default><label>CONSEGNA PANNOLINI</label></value>
            <value><fullName>RICH. VERIFICA SCONTI RACC.DIF</fullName><default>false</default><label>RICH. VERIFICA SCONTI RACC.DIF</label></value>
            <value><fullName>RICHIESTA INFORMAZIONI</fullName><default>false</default><label>RICHIESTA INFORMAZIONI</label></value>
            <value><fullName>RICHIESTA INFORMAZIONI PAP</fullName><default>false</default><label>RICHIESTA INFORMAZIONI PAP</label></value>
            <value><fullName>SEGNALAZ COMPORTAMEN CITTADINI</fullName><default>false</default><label>SEGNALAZ COMPORTAMEN CITTADINI</label></value>
            <value><fullName>SOLLEC RITIROGRATUITO CONAPP</fullName><default>false</default><label>SOLLEC RITIROGRATUITO CONAPP</label></value>
            <value><fullName>SOLLEC RITIROGRATUITO SENZAAPP</fullName><default>false</default><label>SOLLEC RITIROGRATUITO SENZAAPP</label></value>
            <value><fullName>VERIFICA TARIFFA</fullName><default>false</default><label>VERIFICA TARIFFA</label></value>
            <value><fullName>CIMITERIALI</fullName><default>false</default><label>CIMITERIALI</label></value>
            <value><fullName>CONSEGNA/RITIRO TUTTI I CONTEN</fullName><default>false</default><label>CONSEGNA/RITIRO TUTTI I CONTEN</label></value>
            <value><fullName>RICHIESTA CONTENITORE</fullName><default>false</default><label>RICHIESTA CONTENITORE</label></value>
            <value><fullName>RIMOZIONE CONTENITORE</fullName><default>false</default><label>RIMOZIONE CONTENITORE</label></value>
            <value><fullName>SOSTITUZIONE CONTENITORE</fullName><default>false</default><label>SOSTITUZIONE CONTENITORE</label></value>
            <value><fullName>CANCELLAZIONE SCRITTE MURARIE</fullName><default>false</default><label>CANCELLAZIONE SCRITTE MURARIE</label></value>
            <value><fullName>LAVAGGIO PORTICI</fullName><default>false</default><label>LAVAGGIO PORTICI</label></value>
            <value><fullName>PRELIEVO CARCASSE ANIMALI</fullName><default>false</default><label>PRELIEVO CARCASSE ANIMALI</label></value>
            <value><fullName>PRONTO INTERVENTO</fullName><default>false</default><label>PRONTO INTERVENTO</label></value>
            <value><fullName>PULIZIA ARENILE</fullName><default>false</default><label>PULIZIA ARENILE</label></value>
            <value><fullName>PULIZIA CADITOIE</fullName><default>false</default><label>PULIZIA CADITOIE</label></value>
            <value><fullName>PULIZIA GIARDINI</fullName><default>false</default><label>PULIZIA GIARDINI</label></value>
            <value><fullName>PULIZIA SUOLO PUBBLICO</fullName><default>false</default><label>PULIZIA SUOLO PUBBLICO</label></value>
            <value><fullName>RACCOLTA SIRINGHE</fullName><default>false</default><label>RACCOLTA SIRINGHE</label></value>
            <value><fullName>SERVIZI A FESTE E MANIFESTAZ</fullName><default>false</default><label>SERVIZI A FESTE E MANIFESTAZ</label></value>
            <value><fullName>SERVIZI DEIEZIONI CANINE</fullName><default>false</default><label>SERVIZI DEIEZIONI CANINE</label></value>
            <value><fullName>SERVIZIO BORA</fullName><default>false</default><label>SERVIZIO BORA</label></value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/OperationGroup__c.field-meta.xml
<CustomField>
    <fullName>OperationGroup__c</fullName>
    <label>Gruppo Intervento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OperationGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PhaseStory__c.field-meta.xml
<CustomField>
    <fullName>PhaseStory__c</fullName>
    <label>PhaseStory</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/TypeOperation__c.field-meta.xml
<CustomField>
    <fullName>TypeOperation__c</fullName>
    <label>Tipo Intervento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OperationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_OperationGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONSULTA IL RIFIUTOLOGO</fullName>
    </customValue>
    <customValue>
        <fullName>ALTRI SERVIZI-IUAS0001</fullName>
        <label>Altri servizi-IUAS0001</label>
    </customValue>
    <customValue>
        <fullName>ALTRI SERVIZI-IUAS0002</fullName>
        <label>Altri servizi-IUAS0002</label>
    </customValue>
    <customValue>
        <fullName>CIMITERIALI-IUIN0023</fullName>
        <label>Cimiteriali-IUIN0023</label>
    </customValue>
    <customValue>
        <fullName>DLGS_116/2020-IUAS0003</fullName>
    </customValue>
    <customValue>
        <fullName>MOVIM.CONTENITORI TARIP-TARIG</fullName>
    </customValue>
    <customValue>
        <fullName>MOVIMENTAZIONE CONTENITORI TCP</fullName>
    </customValue>
    <customValue>
        <fullName>PULIZIA AREE PUBBLIC-IUPS0000</fullName>
        <label>Pulizia aree pubblic-IUPS0000</label>
    </customValue>
    <customValue>
        <fullName>PULIZIA AREE PUBBLIC-IUPS0002</fullName>
        <label>Pulizia aree pubblic-IUPS0002</label>
    </customValue>
    <customValue>
        <fullName>PULIZIA AREE PUBBLIC-IUPS0007</fullName>
        <label>Pulizia aree pubblic-IUPS0007</label>
    </customValue>
    <customValue>
        <fullName>RACCOLTA DIFFERENZIAT-IURD0023</fullName>
        <label>Raccolta differenziat-IURD0023</label>
    </customValue>
    <customValue>
        <fullName>RACCOLTA INDIFFERENZ-IUIN0021</fullName>
        <label>Raccolta indifferenz-IUIN0021</label>
    </customValue>
    <customValue>
        <fullName>SCARICHI ABUSIVI-IUPS0000</fullName>
        <label>Scarichi abusivi-IUPS0000</label>
    </customValue>
    <customValue>
        <fullName>SERVIZI A PAG.CARCASS-IUAS0001</fullName>
        <label>Servizi a pag.carcass-IUAS0001</label>
    </customValue>
    <customValue>
        <fullName>SERVIZI A PAGAMENTO-IUAS0002</fullName>
        <label>Servizi a pagamento-IUAS0002</label>
    </customValue>
    <customValue>
        <fullName>SOLLEC_Amianto/Etern-IURD0026</fullName>
        <isActive>false</isActive>
        <label>SOLLEC_Amianto/Etern-IURD0026</label>
    </customValue>
    <customValue>
        <fullName>SOLLEC_Verde-IURD0043</fullName>
        <isActive>false</isActive>
        <label>SOLLEC_Verde-IURD0043</label>
    </customValue>
    <masterLabel>Gruppo Intervento</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OperationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Amianto/Eternit_NOApp-IURD0026</fullName>
    </customValue>
    <customValue>
        <fullName>Amianto/Eternit-IURD0026</fullName>
    </customValue>
    <customValue>
        <fullName>Calotta_manutenzione</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellazione scritte murarie</fullName>
    </customValue>
    <customValue>
        <fullName>Cessazione_RestituzContenitore</fullName>
    </customValue>
    <customValue>
        <fullName>Chiavetta elettronica_consegna</fullName>
    </customValue>
    <customValue>
        <fullName>Chiavetta elettronica_manutenz</fullName>
    </customValue>
    <customValue>
        <fullName>Cimiteriali</fullName>
    </customValue>
    <customValue>
        <fullName>Consegna/Ritiro cassone</fullName>
    </customValue>
    <customValue>
        <fullName>Consegna KIT Porta a Porta</fullName>
    </customValue>
    <customValue>
        <fullName>Consegna pannolini</fullName>
    </customValue>
    <customValue>
        <fullName>Contenitore danneggiato</fullName>
    </customValue>
    <customValue>
        <fullName>Diserbo</fullName>
    </customValue>
    <customValue>
        <fullName>Dismissione compostiera</fullName>
    </customValue>
    <customValue>
        <fullName>FE - MO - Spazzamento meccaniz</fullName>
    </customValue>
    <customValue>
        <fullName>Ingombr+RAEE_NOAPP-IURD0033</fullName>
    </customValue>
    <customValue>
        <fullName>Ingombr+RAEE-IURD0033</fullName>
    </customValue>
    <customValue>
        <fullName>Ingombr-IURD0033</fullName>
    </customValue>
    <customValue>
        <fullName>Lavaggio contenitore</fullName>
    </customValue>
    <customValue>
        <fullName>Lavaggio Portici</fullName>
    </customValue>
    <customValue>
        <fullName>Lavaggio strade</fullName>
    </customValue>
    <customValue>
        <fullName>Muschio_Erba murella</fullName>
    </customValue>
    <customValue>
        <fullName>Noleggio cassoni</fullName>
    </customValue>
    <customValue>
        <fullName>Pile-IURD0041</fullName>
    </customValue>
    <customValue>
        <fullName>Prelievo carcasse animali</fullName>
    </customValue>
    <customValue>
        <fullName>Pronto Intervento</fullName>
    </customValue>
    <customValue>
        <fullName>Pulizia arenile</fullName>
    </customValue>
    <customValue>
        <fullName>Pulizia Caditoie</fullName>
    </customValue>
    <customValue>
        <fullName>Pulizia suolo pubblico</fullName>
    </customValue>
    <customValue>
        <fullName>raccolta porta a porta</fullName>
    </customValue>
    <masterLabel>Tipo Operazione</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_SegnalazioniCriteria.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global inherited sharing class HDT_UTL_SegnalazioniCriteria implements wrts_prcgvr.Interfaces_1_2.IApexCriteria {

    global HDT_UTL_SegnalazioniCriteria(){
        return;
    }

    global Boolean evaluate(Object args){//
        Map<String, Object> argsMap = (Map<String, Object>) args;
        //system.debug(json.serialize(args));
        //SObject transition = (SObject) argsMap.get('transition');
        //SObject action = (SObject) argsMap.get('action');
        String method = (String) argsMap.get('method');
        SObject record = (SObject) argsMap.get('record');
        String oldTransitions = (String) record.get('PhaseStory__c');
        Boolean result = false;
        for(String transition : oldTransitions.split('\\|\\|')){
            result = transition?.containsIgnoreCase('In Attesa Appuntamento');
            if(result){
                break;
            }
        }
        if(method?.equalsIgnoreCase('not')){
            result=!result;
        }
        return result;
    }

    @AuraEnabled(cacheable=true)
    public static list<HDT_SegnalazioniAmbientali__mdt> getMaterialOptions(String operationGroup, String operationType) {        
	    if(STRING.isBlank(operationGroup) || STRING.isBlank(operationType)){    return null;   }

        list<HDT_SegnalazioniAmbientali__mdt> pickoptions = [   
                SELECT Material__c
                FROM HDT_SegnalazioniAmbientali__mdt 
                WHERE 
                OperationGroup__c =:operationGroup
                AND TypeOperation__c =:operationType 
                WITH SECURITY_ENFORCED 
                Order By Material__c
        ];

        return pickoptions;
    }
}