force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziareun contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (CPQ) (Contratto di riferimento)</relationshipLabel>
    <relationshipName>QuotesCPQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/IsBillableVas__c.field-meta.xml
<CustomField>
    <fullName>IsBillableVas__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsBillableVas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/IsVAS__c.field-meta.xml
<CustomField>
    <fullName>IsVAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Quotes (CPQ)</relationshipLabel>
    <relationshipName>QuotesCPQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <description>Approved</description>
    <label>Approvazione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_ConfigurePaymentMethods.cls
public inherited sharing class HDT_LC_ConfigurePaymentMethods {

    private static HDT_QR_Activity activityQr = new HDT_QR_Activity();


    public HDT_LC_ConfigurePaymentMethods() {
        system.debug('Costruttore HDT_LC_ConfigurePaymentMethods');
    }

    @AuraEnabled
    public static Boolean disableBotton(String idAcc, SObject o){

    if (o != null) {
    
        wrts_prcgvr__Activity__c activity = activityQr.getLastActivity(idAcc,o);
        if(activity.Approved__c != null){
            if(activity.Approved__c != 'Si'){
                return false;
            }
        }
    }
    
    return true;

    }

    @AuraEnabled
    public static Boolean disableMyButtons(SObject mySale){
        boolean toBeDisabled;
        List<SBQQ__Quote__c> myQuoteList = [select id, IsVAS__c, IsBillableVas__c, OrderReference__c, ContractReference__c from SBQQ__Quote__c where Sale__c = :mySale.Id with security_enforced];
        for(SBQQ__Quote__c myQuote : myQuoteList){
            if(myQuote.IsVAS__c && !myQuote.IsBillableVas__c && (myQuote.OrderReference__c != null || myQuote.ContractReference__c != null)){
                toBeDisabled = true;
            }
            else{
                toBeDisabled = false;
            }
        }
        return toBeDisabled;
    }

    
}