force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Details con l&apos;oggetto account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendite</relationshipLabel>
    <relationshipName>Vendite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account del titolare del punto di fornitura</description>
    <label>Account Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points (Account)</relationshipLabel>
    <relationshipName>Service_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyTypeTemp__c.field-meta.xml
<CustomField>
    <fullName>SupplyTypeTemp__c</fullName>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <label>Tipo Fornitura Temp</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CommoditySector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/recordTypes/HDT_RT_Ele.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Ele</fullName>
    <active>true</active>
    <description>Punto di fornitura Energia Elettrica</description>
    <label>Punto Elettrico</label>
</RecordType>

force-app/main/default/globalValueSets/HDT_SupplyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Non Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>A-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>B-Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>C-Aziende di pubblica utilita</fullName>
    </customValue>
    <customValue>
        <fullName>D-Altri usi</fullName>
    </customValue>
    <customValue>
        <fullName>Uso domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso diverso da domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Usi industriali che scaricano in pubblica fognatura</fullName>
    </customValue>
    <customValue>
        <fullName>Altri usi</fullName>
    </customValue>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <masterLabel>Tipo Fornitura</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_SaleServiceContainer.cls
/**
* @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
* @date 26/11/2020
* @description HDT_LC_SaleServiceContainer – Apex controller for hdtSaleServiceContainer.js component
* @history Keltin Mesonjesi – 23/11/2020 – Created class
*/
public inherited sharing class HDT_LC_SaleServiceContainer {
    private static HDT_QR_Contract contractQr = new HDT_QR_Contract();
    
    private static HDT_QR_SaleServiceItem saleServiceItemQr = new HDT_QR_SaleServiceItem();
    private static HDT_SRV_SaleServiceItem saleServiceItemSrv = new HDT_SRV_SaleServiceItem();
    private static HDT_SRV_Sale saleSrv = new HDT_SRV_Sale();

    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Check if service point for current sale account is linked to quotes that have a contract
     * @param String accountId
     * @param ServicePoint__c newServicePoint
     */
    private static Boolean isServicePointLinkedToContract(ServicePoint__c newServicePoint, String accountId) {
        
        saleServiceItemSrv.checkReadAccess('Id, Status,AccountId,ServicePoint__c ');
        List<Contract> linkedContracts = contractQr.getRecordsWithContractsByServicePointAndAccountId(newServicePoint.Id, accountId);

        return !linkedContracts.isEmpty();
    }

    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Check if field "Uso Energia" has been changed on confirmation for service point
     * @param String accountId
     * @param ServicePoint__c newServicePoint
     * @param ServicePoint__c oldServicePoint
     */
    private static Boolean hasUsoEnergiaChangedForEle(String accountId, ServicePoint__c newServicePoint, ServicePoint__c oldServicePoint) {

        return isServicePointLinkedToContract(newServicePoint, accountId) && newServicePoint.RecordType.DeveloperName == 'HDT_RT_Ele' && newServicePoint.SupplyTypeTemp__c !=null && oldServicePoint.SupplyTypeTemp__c != newServicePoint.SupplyTypeTemp__c;

    }

    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Create tile
     * @param ServicePoint__c servicePoint
     * @param Sale__c sale
     */
    @AuraEnabled
    public static Map<String,Boolean> createSaleServiceItemTile(ServicePoint__c servicePoint, Sale__c sale, ServicePoint__c oldServicePoint){
        
        Map<String,String> extraParams = new Map<String,String>();

        if (hasUsoEnergiaChangedForEle(sale.Account__c, servicePoint, oldServicePoint)) {
            List<Contract> linkedContracts = contractQr.getRecordsWithContractsByServicePointAndAccountId(servicePoint.Id, sale.Account__c);
            String contractReference = linkedContracts[0].id;
            extraParams.put('AllowChangeUse__c', 'true');
            extraParams.put('contractReference', contractReference);
        }

        saleServiceItemSrv.createRecord(servicePoint, sale, extraParams);
        boolean isTransition =HDT_UTL_Sales.isTransition(ServicePoint,sale);
        Map<String,Boolean> result = new Map<String,Boolean>{
            'isTransition'=>isTransition
        };
        return result;

    }
    
    /**
     * @author Keltin Mesonjesi (keltin.mesonjesi@dunegroup.it)
     * @description Update Sale
     * @param Sale__c sale
     */
    @AuraEnabled
    public static void updateSale(Sale__c sale){
        saleSrv.updateRecord(sale);
    }
}