force-app/main/default/objects/Asset/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>La company owner legata al dato record di asset</description>
    <label>Company Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PushTracking__c/PushTracking__c.object-meta.xml
<CustomObject>
    <description>Tracciamento di tutti gli esiti su canale Push inviate da Marketing Cloud</description>
    <label>Push Tracking</label>
    <nameField>
        <displayFormat>PTK-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_TRH_PushTrackingTst.cls
/**
* @author Lucas da Silva Fernandes (lucas.dasilva@engdb.com.br)
* @date 10/08/2021
* @description Test Class for HDT_TRH_PushTracking
* @history Lucas da Silva Fernandes – 10/08/2021 – Created class
*/
@isTest
public with sharing class HDT_TRH_PushTrackingTst {
    
    @isTest
    public static void testPushTrackingBeforeInsert() {

        Test.startTest();

        List<PushTracking__c> pushTrackingList = new List<PushTracking__c>();

        PushTracking__c pt = new PushTracking__c(
            CompanyOwner__c = 'HERA COMM'
        );

        pushTrackingList.add(pt);

        insert pushTrackingList;

        PushTracking__c ptTest = [SELECT Id FROM PushTracking__c WHERE CompanyOwner__c = 'HERA COMM' LIMIT 1];

        System.assertEquals(ptTest.Id, pushTrackingList[0].Id, 'Asset ID match.');

        System.assertNotEquals(pushTrackingList[0].Id, '', 'Asset ID does not match.');

        Test.stopTest();
    }
}