force-app/main/default/objects/Asset/fields/VasPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>VasPracticeCode__c</fullName>
    <label>Codice Pratica</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderODV__c.field-meta.xml
<CustomField>
    <fullName>OrderODV__c</fullName>
    <label>Ordine ODV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>TerminationDate__c</fullName>
    <label>Data Cessazione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>VasPolicyNumber__c</fullName>
    <label>Numero Polizza Vas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>VasPracticeCode__c</fullName>
    <label>Codice Pratica VAS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio VAS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasStatus__c.field-meta.xml
<CustomField>
    <fullName>VasStatus__c</fullName>
    <label>Stato VAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VasEngineStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VasStatusDescription__c.field-meta.xml
<CustomField>
    <fullName>VasStatusDescription__c</fullName>
    <label>Descrizione Stato Motore VAS</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/HDT_StatoMotoreVas__mdt.object-meta.xml
<CustomObject>
    <label>Stato Motore Vas</label>
    <pluralLabel>Stati Motore Vas</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/fields/VasStatus__c.field-meta.xml
<CustomField>
    <fullName>VasStatus__c</fullName>
    <label>Stato Motore Vas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderODV__c.field-meta.xml
<CustomField>
    <fullName>OrderODV__c</fullName>
    <label>Ordine ODV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Ordine di riferimento)</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>TerminationDate__c</fullName>
    <label>Data Cessazione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>VasPolicyNumber__c</fullName>
    <label>Numero Polizza Vas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>VasPracticeCode__c</fullName>
    <label>Codice Pratica VAS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio VAS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasStatus__c.field-meta.xml
<CustomField>
    <fullName>VasStatus__c</fullName>
    <label>Stato Motore VAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VasEngineStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/VasStatusDescription__c.field-meta.xml
<CustomField>
    <fullName>VasStatusDescription__c</fullName>
    <label>Descrizione Stato Motore VAS</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/VasPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>VasPolicyNumber__c</fullName>
    <label>Numero Polizza VAS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_VasEngineStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANNUL PER CESSAZIONE</fullName>
    </customValue>
    <customValue>
        <fullName>ANNUL PER RECESSO</fullName>
    </customValue>
    <customValue>
        <fullName>ANNUL PER RIPENS</fullName>
    </customValue>
    <customValue>
        <fullName>ANNULLATO</fullName>
    </customValue>
    <customValue>
        <fullName>CESS</fullName>
    </customValue>
    <customValue>
        <fullName>CHIUSO</fullName>
    </customValue>
    <customValue>
        <fullName>COFF</fullName>
    </customValue>
    <customValue>
        <fullName>DIS</fullName>
    </customValue>
    <customValue>
        <fullName>FAT SD</fullName>
    </customValue>
    <customValue>
        <fullName>FATT</fullName>
    </customValue>
    <customValue>
        <fullName>FATTURA SD</fullName>
    </customValue>
    <customValue>
        <fullName>KO</fullName>
    </customValue>
    <customValue>
        <fullName>KO BONUS</fullName>
    </customValue>
    <customValue>
        <fullName>KO DIS</fullName>
    </customValue>
    <customValue>
        <fullName>KO ODV</fullName>
    </customValue>
    <customValue>
        <fullName>KO PAREG</fullName>
    </customValue>
    <customValue>
        <fullName>KO RTZ</fullName>
    </customValue>
    <customValue>
        <fullName>KO STORN</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>OK ODV</fullName>
    </customValue>
    <customValue>
        <fullName>OK PAREG</fullName>
    </customValue>
    <customValue>
        <fullName>PAG</fullName>
    </customValue>
    <customValue>
        <fullName>RECESSO DA FORNITORE</fullName>
    </customValue>
    <customValue>
        <fullName>RECL</fullName>
    </customValue>
    <customValue>
        <fullName>RIPENS</fullName>
    </customValue>
    <customValue>
        <fullName>RTZ</fullName>
    </customValue>
    <customValue>
        <fullName>SOL_TAG</fullName>
    </customValue>
    <customValue>
        <fullName>SOLL</fullName>
    </customValue>
    <customValue>
        <fullName>STORN</fullName>
    </customValue>
    <customValue>
        <fullName>VO</fullName>
    </customValue>
    <description>Elenco stati ricevuti da motore vas.</description>
    <masterLabel>Stato Motore Vas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_NotifVas.cls
/**
 * @description       : 
 * @author            : gabriele.rota@webresults.it
 * @group             : WR
 * @last modified on  : 2021-07-27
 * @last modified by  : gabriele.rota@webresults.it
**/
public class HDT_UTL_NotifVas {

    private static HDT_QR_Order orderQr = new HDT_QR_Order();
    private static HDT_QR_Case caseQr = new HDT_QR_Case();
    private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();
    private static HDT_SRV_Case caseSrv = new HDT_SRV_Case();

    public static void handleVasNotify(HDT_WRP_MrrRequest.HDT_WRP_Request request, HDT_WRP_MrrResponse.HDT_WRP_Response mrrResponseItem) {

        Map<String, String> requestMap = new Map<String, String>();
        for(HDT_WRP_MrrRequest.HDT_WRP_Field field : request.objects.get(0).fields){
            requestMap.put(field.name, field.value);
        }

        Exception processExc;
        Savepoint sp = Database.setSavepoint();
        try {
            switch on requestMap.get('TIPO_OPERAZIONE') {
                when 'ATT' {
                    handleVasActivation(request, requestMap);
                }
                when 'DIS' {
                    handleVasDeactivation(request, requestMap);
                }
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
            processExc = e;
            Database.rollback(sp);
        }

        setResponse(mrrResponseItem, processExc);
    }
    
    private static void handleVasActivation(HDT_WRP_MrrRequest.HDT_WRP_Request request, Map<String, String> requestMap) {
        Map<String,SObject> sObjMap = getRequestSObjects(requestMap, Order.sObjectType);
        HDT_StatoMotoreVas__mdt statusMapping = getStatusMapping(requestMap);

        Order currentOrder = (Order)sObjMap.get('Order');
        currentOrder.Phase__c = statusMapping.Phase__c;
        populateFieldsFromRequest(requestMap, currentOrder);
        orderSrv.updateRecord(currentOrder);
    }

    private static void handleVasDeactivation(HDT_WRP_MrrRequest.HDT_WRP_Request request, Map<String, String> requestMap) {
        Map<String,SObject> sObjMap = getRequestSObjects(requestMap, Case.sObjectType);
        HDT_StatoMotoreVas__mdt statusMapping = getStatusMapping(requestMap);

        Case currentCase = (Case)sObjMap.get('Case');
        currentCase.Phase__c = statusMapping.Phase__c;
        populateFieldsFromRequest(requestMap, currentCase);
        caseSrv.updateRecord(currentCase);

        if (sObjMap.containsKey('Order')) {
            Order currentOrder = (Order)sObjMap.get('Order');
            currentOrder.Phase__c = statusMapping.Phase__c;
            populateFieldsFromRequest(requestMap, sObjMap.get('Order'));
            orderSrv.updateRecord(currentOrder);
        }

        if (sObjMap.containsKey('Asset')) {
            Asset currentAsset = (Asset)sObjMap.get('Asset');
            currentAsset.Status = statusMapping.Phase__c;
            update currentAsset;
        }

        if (sObjMap.containsKey('SBQQ__Subscription__c')) {
            SBQQ__Subscription__c subs = (SBQQ__Subscription__c)sObjMap.get('SBQQ__Subscription__c');
            //subs.Phase__c = statusMapping.Phase__c;
            update subs;
        }
    }

    private static void setResponse(HDT_WRP_MrrResponse.HDT_WRP_Response mrrResponseItem, Exception processExc) {

        Boolean isSuccess = (processExc==null);
        String outcome = isSuccess?'OK':'KO';
        Integer httpCode = isSuccess?200:500;

        List<HDT_WRP_MrrResponse.HDT_WRP_Field> respFields = new List<HDT_WRP_MrrResponse.HDT_WRP_Field>();
        
        HDT_WRP_MrrResponse.HDT_WRP_Field responseField = new HDT_WRP_MrrResponse.HDT_WRP_Field();
        responseField.fieldType = 'TEXT';
        responseField.name = 'ESITO';
        responseField.value = outcome;
        respFields.add(responseField);
        
        if (!isSuccess) {
            HDT_WRP_MrrResponse.HDT_WRP_Field responseFieldError = new HDT_WRP_MrrResponse.HDT_WRP_Field();
            responseFieldError.fieldType = 'TEXT';
            responseFieldError.name = 'ERROR_MESSAGE';
            responseFieldError.value = processExc.getMessage();
            respFields.add(responseFieldError);
        }
        
        HDT_WRP_MrrResponse.HDT_WRP_Object responseObject = new HDT_WRP_MrrResponse.HDT_WRP_Object();
        responseObject.fields = respFields;
        mrrResponseItem.objects.add(responseObject);

        RestContext.response.statusCode = httpCode;
    }


    private static Map<String,SObject> getRequestSObjects(Map<String, String> requestMap, SObjectType sObjType) {
        String sObjectKey = requestMap.get('KEY_SERVIZIO');

        Map<String,SObject> sObjMap = new Map<String,SObject>();
        switch on String.valueof(sObjType)  {
            when 'Order' {
                List<Order> orders = orderQr.getRecordByOrderNumber(sObjectKey);
                if (!orders.isEmpty()) {
                    sObjMap.put('Order', orders.get(0));
                }
            }
            when 'Case' {
                List<Case> cases = [SELECT Order__r.Id,Asset.Id,Subscription__r.Id FROM Case
                    WHERE CaseNumber = :sObjectKey WITH SECURITY_ENFORCED LIMIT 1];
                if (!cases.isEmpty()) {
                    sObjMap.put('Case', cases.get(0));
                }
                if (cases.get(0).Order__r!=null) {
                    sObjMap.put('Order', cases.get(0).Order__r);
                }
                if (cases.get(0).Asset!=null) {
                    sObjMap.put('Asset', cases.get(0).Asset);
                }
                if (cases.get(0).Subscription__r!=null) {
                    sObjMap.put('SBQQ__Subscription__c', cases.get(0).Subscription__r);
                }
            }
        }

        if (sObjMap.isEmpty()) {
            throw new HDT_UTL_HeraException('KEY_SERVIZIO: No records found');
        }

        return sObjMap;
    }

    private static HDT_StatoMotoreVas__mdt getStatusMapping(Map<String, String> requestMap) {
        String statoPratica = requestMap.get('STATO_PRATICA').replace(' ','_');
        HDT_StatoMotoreVas__mdt statusMapping = HDT_StatoMotoreVas__mdt.getAll().get(statoPratica);

        if (statusMapping==null) {
            throw new HDT_UTL_HeraException('STATO_PRATICA: No status mapping found');
        }

        return statusMapping;
    }

    private static void populateFieldsFromRequest(Map<String, String> requestMap, SObject targetRecord) {
        targetRecord.put('VasPracticeCode__c', requestMap.get('ID_PRATICA_MOTORE_VAS') );
        targetRecord.put('VasStatus__c', requestMap.get('STATO_PRATICA') );
        targetRecord.put('VasStatusDescription__c', requestMap.get('ESITO') );
        targetRecord.put('VasPolicyNumber__c', requestMap.get('NUMERO_POLIZZA') );
        targetRecord.put('OrderODV__c', requestMap.get('ODV') );

        if (String.isNotBlank(requestMap.get('DATA_DECORRENZA'))) {
            targetRecord.put('VasServiceActivationDate__c', Date.valueOf(requestMap.get('DATA_DECORRENZA')) );
        }

        if (String.isNotBlank(requestMap.get('DATA_CESSAZIONE'))) {
            targetRecord.put('TerminationDate__c', Date.valueOf(requestMap.get('DATA_CESSAZIONE')) );
        }

        if (String.isNotBlank(requestMap.get('DISATTIVAZIONE_COMPLETATA'))) {
            targetRecord.put('CompletedDeactivation__c', Boolean.valueOf(requestMap.get('DISATTIVAZIONE_COMPLETATA')) );
        }
    }
}