force-app/main/default/objects/Asset/fields/VasPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>VasPracticeCode__c</fullName>
    <label>Codice Pratica</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderODV__c.field-meta.xml
<CustomField>
    <fullName>OrderODV__c</fullName>
    <label>Ordine ODV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore VAS</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura Tecnica</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allegati ricevuti</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Extra Sistema</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Approvata</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>TerminationDate__c</fullName>
    <label>Data Cessazione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>VasPolicyNumber__c</fullName>
    <label>Numero Polizza Vas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>VasPracticeCode__c</fullName>
    <label>Codice Pratica VAS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio VAS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/VasStatus__c.field-meta.xml
<CustomField>
    <fullName>VasStatus__c</fullName>
    <label>Stato VAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VasEngineStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VasStatusDescription__c.field-meta.xml
<CustomField>
    <fullName>VasStatusDescription__c</fullName>
    <label>Descrizione Stato Motore VAS</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/HDT_StatoMotoreVas__mdt.object-meta.xml
<CustomObject>
    <label>Stato Motore Vas</label>
    <pluralLabel>Stati Motore Vas</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/fields/AssetStatus__c.field-meta.xml
<CustomField>
    <fullName>AssetStatus__c</fullName>
    <label>Stato Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/fields/CasePhase__c.field-meta.xml
<CustomField>
    <fullName>CasePhase__c</fullName>
    <label>Fase Caso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/fields/CaseStatus__c.field-meta.xml
<CustomField>
    <fullName>CaseStatus__c</fullName>
    <label>Stato Caso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/fields/OrderPhase__c.field-meta.xml
<CustomField>
    <fullName>OrderPhase__c</fullName>
    <label>Fase Ordine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <label>Stato Ordine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_StatoMotoreVas__mdt/fields/VasStatus__c.field-meta.xml
<CustomField>
    <fullName>VasStatus__c</fullName>
    <label>Stato Motore Vas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderODV__c.field-meta.xml
<CustomField>
    <fullName>OrderODV__c</fullName>
    <label>Ordine ODV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>TerminationDate__c</fullName>
    <label>Data Cessazione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>VasPolicyNumber__c</fullName>
    <label>Numero Polizza Vas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>VasPracticeCode__c</fullName>
    <label>Codice Pratica VAS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio VAS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/VasStatus__c.field-meta.xml
<CustomField>
    <fullName>VasStatus__c</fullName>
    <label>Stato Motore VAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VasEngineStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/VasStatusDescription__c.field-meta.xml
<CustomField>
    <fullName>VasStatusDescription__c</fullName>
    <label>Descrizione Stato Motore VAS</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/VasPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>VasPolicyNumber__c</fullName>
    <label>Numero Polizza VAS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/VasServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>VasServiceActivationDate__c</fullName>
    <label>Data attivazione servizio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_VasEngineStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANNUL PER CESSAZIONE</fullName>
    </customValue>
    <customValue>
        <fullName>ANNUL PER RECESSO</fullName>
    </customValue>
    <customValue>
        <fullName>ANNUL PER RIPENS</fullName>
    </customValue>
    <customValue>
        <fullName>ANNULLATO</fullName>
    </customValue>
    <customValue>
        <fullName>CESS</fullName>
    </customValue>
    <customValue>
        <fullName>CHIUSO</fullName>
    </customValue>
    <customValue>
        <fullName>COFF</fullName>
    </customValue>
    <customValue>
        <fullName>DIS</fullName>
    </customValue>
    <customValue>
        <fullName>FAT SD</fullName>
    </customValue>
    <customValue>
        <fullName>FATT</fullName>
    </customValue>
    <customValue>
        <fullName>FATTURA SD</fullName>
    </customValue>
    <customValue>
        <fullName>KO</fullName>
    </customValue>
    <customValue>
        <fullName>KO BONUS</fullName>
    </customValue>
    <customValue>
        <fullName>KO DIS</fullName>
    </customValue>
    <customValue>
        <fullName>KO ODV</fullName>
    </customValue>
    <customValue>
        <fullName>KO PAREG</fullName>
    </customValue>
    <customValue>
        <fullName>KO RTZ</fullName>
    </customValue>
    <customValue>
        <fullName>KO STORN</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>OK ODV</fullName>
    </customValue>
    <customValue>
        <fullName>OK PAREG</fullName>
    </customValue>
    <customValue>
        <fullName>PAG</fullName>
    </customValue>
    <customValue>
        <fullName>RECESSO DA FORNITORE</fullName>
    </customValue>
    <customValue>
        <fullName>RECL</fullName>
    </customValue>
    <customValue>
        <fullName>RIPENS</fullName>
    </customValue>
    <customValue>
        <fullName>RTZ</fullName>
    </customValue>
    <customValue>
        <fullName>SOL_TAG</fullName>
    </customValue>
    <customValue>
        <fullName>SOLL</fullName>
    </customValue>
    <customValue>
        <fullName>STORN</fullName>
    </customValue>
    <customValue>
        <fullName>VO</fullName>
    </customValue>
    <description>Elenco stati ricevuti da motore vas.</description>
    <masterLabel>Stato Motore Vas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_NotifVasHelper.cls
/**
 * @description       : Helper for handling Vas notify requests
 * @author            : gabriele.rota@webresults.it
 * @group             : WR
 * @last modified on  : 2021-11-09
 * @last modified by  : gabriele.rota@webresults.it
 * Modifications Log 
 * Ver   Date         Author                        Modification
 * 1.0   2021-10-26   gabriele.rota@webresults.it   Initial Version
**/
@SuppressWarnings('PMD.AvoidDebugStatements')
public inherited sharing class HDT_UTL_NotifVasHelper {

    private static HDT_QR_Order orderQr = new HDT_QR_Order();
    private static HDT_QR_Case caseQr = new HDT_QR_Case();
    private static HDT_SRV_Order orderSrv = new HDT_SRV_Order();
    private static HDT_SRV_Case caseSrv = new HDT_SRV_Case();
    
    /**
    * @description Getting SObject related to request (Order/Case/Asset/Subscription)
    * @author gabriele.rota@webresults.it | 2021-07-28 
    * @param requestMap 
    * @param sObjType 
    * @return Map<String, SObject> 
    **/
    public static Map<String,SObject> getRequestSObjects(Map<String, String> requestMap, SObjectType sObjType) {
        String sObjectKey = requestMap.get('KEY_SERVIZIO');

        Map<String,SObject> sObjMap = new Map<String,SObject>();
        switch on String.valueof(sObjType)  {
            when 'Order' {
                List<Order> orders = orderQr.getRecordByOrderNumber(sObjectKey);
                if (!orders.isEmpty()) {
                    sObjMap.put('Order', orders.get(0));
                }
            }
            when 'Case' {
                List<Order> orders = orderQr.getRecordByOrderNumber(sObjectKey);
                if (!orders.isEmpty()) {
                    sObjMap.put('Order', orders.get(0));

                    Id orderId = orders.get(0).Id;

                    List<Case> cases = [SELECT Asset.Id, Subscription__r.Id FROM Case
                        WHERE RecordType.DeveloperName='HDT_RT_PostSalesVAS' AND Type='Disattivazione VAS'
                        AND (Asset.SBQQ__OrderProduct__r.OrderId=:orderId OR Subscription__r.SBQQ__Contract__r.SBQQ__Order__c=:orderId) AND Status NOT IN ('Closed', 'Bozza')
                        WITH SECURITY_ENFORCED LIMIT 1];

                    if (!cases.isEmpty()) {
                        sObjMap.put('Case', cases.get(0));

                        if (cases.get(0).getSobject('Asset')!=null) {
                            sObjMap.put('Asset', cases.get(0).Asset);
                        }
                        if (cases.get(0).getSobject('Subscription__r')!=null) {
                            sObjMap.put('SBQQ__Subscription__c', cases.get(0).Subscription__r);
                        }
                    }
                }
            }
        }

        if (sObjMap.isEmpty()) {
            throw new HDT_UTL_HeraException('KEY_SERVIZIO: No records found');
        }

        return sObjMap;
    }

    /**
    * @description Getting status mapping from Custom Metadata
    * @author gabriele.rota@webresults.it | 2021-07-28 
    * @param requestMap 
    * @return HDT_StatoMotoreVas__mdt 
    **/
    public static HDT_StatoMotoreVas__mdt getStatusMapping(Map<String, String> requestMap) {
        String statoPratica = requestMap.get('STATO_PRATICA').replace(' ','_');
        HDT_StatoMotoreVas__mdt statusMapping = HDT_StatoMotoreVas__mdt.getAll().get(statoPratica);

        if (statusMapping==null) {
            throw new HDT_UTL_HeraException('STATO_PRATICA: No status mapping found');
        }

        return statusMapping;
    }

    /**
    * @description Mapping phase/status from Custom Metadata to SObjects
    * @author gabriele.rota@webresults.it | 2021-07-28 
    * @param statusMapping 
    * @param sObjMap 
    **/
    public static void mapPhaseAndStatus(HDT_StatoMotoreVas__mdt statusMapping, Map<String,SObject> sObjMap) {
        try {
            mapOrderPhaseAndStatus(statusMapping, sObjMap);
            mapCasePhaseAndStatus(statusMapping, sObjMap);
            mapAssetStatus(statusMapping, sObjMap);
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new HDT_UTL_HeraException('Error while mapping Phase/Status to Objects');
        }
    }

    /**
    * @description Saving SObjects
    * @author gabriele.rota@webresults.it | 2021-07-28 
    * @param sObjMap 
    **/
    public static void updateRecords(Map<String,SObject> sObjMap) {

        Order orderToUpdate;
        Case caseToUpdate;
        List<SObject> recordsToUpdate = new List<SObject>();

        for (String sObjectName:sObjMap.keySet()) {
            switch on sObjectName {
                when 'Order' {
                    orderToUpdate = (Order)sObjMap.get(sObjectName);
                }
                when 'Case' {
                    caseToUpdate = (Case)sObjMap.get(sObjectName);
                }
                when else {
                    SObject record = sObjMap.get(sObjectName);
                    recordsToUpdate.add(record);
                }
            }
        }

        Savepoint sp = Database.setSavepoint();
        try {
            if (orderToUpdate!=null) {
                System.debug(LoggingLevel.DEBUG, 'Order updated');
                orderSrv.updateRecord(orderToUpdate);
            }

            if (caseToUpdate!=null) {
                System.debug(LoggingLevel.DEBUG, 'Case updated');
                caseSrv.updateRecord(caseToUpdate);
            }

            if (!recordsToUpdate.isEmpty()) {
                System.debug(LoggingLevel.DEBUG, 'Asset/Subscription updated');
                HDT_UTL_DatabaseService.updateSObject(recordsToUpdate);
            }
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new HDT_UTL_HeraException('Error while saving records ('+e.getMessage()+')');
        }
    }

    /**
    * @description Mapping request fields to Order/Case record
    * @author gabriele.rota@webresults.it | 2021-07-28 
    * @param requestMap 
    * @param targetRecord 
    **/
    public static void populateFieldsFromRequest(Map<String, String> requestMap, SObject targetRecord) {
        targetRecord.put('VasPracticeCode__c', requestMap.get('ID_PRATICA_VAS') );
        targetRecord.put('VasStatus__c', requestMap.get('STATO_PRATICA') );
        targetRecord.put('VasStatusDescription__c', requestMap.get('ESITO') );
        targetRecord.put('VasPolicyNumber__c', requestMap.get('NUMERO_POLIZZA') );
        targetRecord.put('OrderODV__c', requestMap.get('ODV') );

        if (String.isNotBlank(requestMap.get('DATA_DECORRENZA'))) {
            targetRecord.put('VasServiceActivationDate__c', Date.valueOf(requestMap.get('DATA_DECORRENZA')) );
        }

        if (String.isNotBlank(requestMap.get('DATA_CESSAZIONE'))) {
            targetRecord.put('TerminationDate__c', Date.valueOf(requestMap.get('DATA_CESSAZIONE')) );
        }
    }

    /**
    * @description Mapping phase/status from Custom Metadata to Order
    * @author gabriele.rota@webresults.it | 2021-10-26 
    * @param statusMapping 
    * @param sObjMap 
    **/
    private static void mapOrderPhaseAndStatus(HDT_StatoMotoreVas__mdt statusMapping, Map<String,SObject> sObjMap) {
        if (sObjMap.containsKey('Order') && !sObjMap.containsKey('Case')) {
            Order currentOrder = (Order)sObjMap.get('Order');
            if (String.isNotBlank(statusMapping.OrderPhase__c)) {
                currentOrder.Phase__c = statusMapping.OrderPhase__c;
            }

            if (String.isNotBlank(statusMapping.OrderStatus__c)) {
                currentOrder.Status = statusMapping.OrderStatus__c;
            }
        }
    }

    /**
    * @description Mapping phase/status from Custom Metadata to Case
    * @author gabriele.rota@webresults.it | 2021-10-26 
    * @param statusMapping 
    * @param sObjMap 
    **/
    private static void mapCasePhaseAndStatus(HDT_StatoMotoreVas__mdt statusMapping, Map<String,SObject> sObjMap) {
        if (sObjMap.containsKey('Case')) {
            Case currentCase = (Case)sObjMap.get('Case');
            if (String.isNotBlank(statusMapping.CasePhase__c)) {
                currentCase.Phase__c = statusMapping.CasePhase__c;
            }

            if (String.isNotBlank(statusMapping.CaseStatus__c)) {
                currentCase.Status = statusMapping.CaseStatus__c;
            }
        }
    }

    /**
    * @description Mapping phase/status from Custom Metadata to Asset
    * @author gabriele.rota@webresults.it | 2021-10-26 
    * @param statusMapping 
    * @param sObjMap 
    **/
    private static void mapAssetStatus(HDT_StatoMotoreVas__mdt statusMapping, Map<String,SObject> sObjMap) {
        if (sObjMap.containsKey('Asset')) {
            Asset currentAsset = (Asset)sObjMap.get('Asset');
            Case currentCase = (Case)sObjMap.get('Case');
            /* Get Assets in bundle */
            List<Asset> bundle = [SELECT DigitalAssetStatus,UsageEndDate FROM Asset WHERE SBQQ__RootAsset__c = :currentAsset.Id WITH SECURITY_ENFORCED];
            bundle.add(currentAsset);
            for(Asset singleAsset : bundle)
            {
                if (String.isNotBlank(statusMapping.AssetStatus__c)) {
                    singleAsset.DigitalAssetStatus = statusMapping.AssetStatus__c;
                    /**@frpanico 16/02/2022
                     * Aggiunto UsageEndDate
                     */
                    if(currentCase.TerminationDate__c != null)
                    {
                        singleAsset.UsageEndDate = currentCase.TerminationDate__c;
                    }
                }
            }
            HDT_UTL_DatabaseService.updateSObject(bundle);
        }
    }
}