force-app/main/default/objects/HDT_GestioneScartiSap__mdt/HDT_GestioneScartiSap__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type per la gestione della Scarti SAP</description>
    <label>Gestione Scarti Sap</label>
    <pluralLabel>Gestione Scarti Sap</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_GestioneScartiSap__mdt/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <description>ATTIVITA inviata da heroku</description>
    <label>Attività</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_GestioneScartiSap__mdt/fields/ActivityInitialStatus__c.field-meta.xml
<CustomField>
    <fullName>ActivityInitialStatus__c</fullName>
    <description>Aperta | Chiusa (stato iniziale dell’activity da creare)</description>
    <label>Stato Iniziale Attività</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aperta</fullName>
                <default>true</default>
                <label>Aperta</label>
            </value>
            <value>
                <fullName>Chiusa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_GestioneScartiSap__mdt/fields/ActivityToClose__c.field-meta.xml
<CustomField>
    <fullName>ActivityToClose__c</fullName>
    <description>Se valorizzato, l’activity configurata in questo campo deve essere chiusa contestualmente alla creazione della nuova activity.</description>
    <label>Attività da Chiudere</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_GestioneScartiSap__mdt/fields/CreateActivity__c.field-meta.xml
<CustomField>
    <fullName>CreateActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se true, creare activity pclick configurata nel campo Activity__c</description>
    <label>Crea Attività</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HDT_GestioneScartiSap__mdt/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>FASE inviata da heroku</description>
    <label>Fase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_GestioneScartiSap__mdt/fields/SkipPhaseManager__c.field-meta.xml
<CustomField>
    <fullName>SkipPhaseManager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se true, effettuare cambio fase skippando il phase manager</description>
    <label>Salta Phase Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HDT_UTL_GestioneScartiSap.cls
public inherited sharing class HDT_UTL_GestioneScartiSap {

    public static Boolean skipPhaseManager(String phase){
        Boolean response = false;
        if (String.isNotBlank(phase)){
            List<HDT_GestioneScartiSap__mdt> rules = [SELECT id FROM HDT_GestioneScartiSap__mdt WHERE Phase__c =:phase AND SkipPhaseManager__c = true WITH SECURITY_ENFORCED];
            response = !rules.isEmpty();
        }
        return response;
    }

    public static List<HDT_GestioneScartiSap__mdt> getRuleFromActivity(Map<String,String> mapFieldValue){ 
        List<HDT_GestioneScartiSap__mdt> response = new List<HDT_GestioneScartiSap__mdt>();
        if (mapFieldValue != null && !mapFieldValue.isEmpty()){
            List<String> partialCondition = new List<String>();
            for (String field : mapFieldValue.keySet()){
                String value = String.escapeSingleQuotes(mapFieldValue.get(field));
                partialCondition.add(field +' = \''+value+'\'');
            }
            String query = 'SELECT Activity__c, CreateActivity__c, ActivityInitialStatus__c,ActivityToClose__c FROM HDT_GestioneScartiSap__mdt WHERE '+String.join(partialCondition, ' AND ')+' WITH SECURITY_ENFORCED';
            response = Database.query(query);
        }
        return response;
    }

}