force-app/main/default/objects/MassiveLoaderRequest__c/MassiveLoaderRequest__c.object-meta.xml
<CustomObject>
    <label>Esito Caricamento</label>
    <nameField>
        <displayFormat>MLR-{00000000}</displayFormat>
        <label>Id Pratica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Esito Caricamenti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>File non processato</fullName>
            </value>
            <value>
                <fullName>File in elaborazione</fullName>
            </value>
            <value>
                <fullName>File processato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priorità</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Processo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SwitchIn</fullName>
                <label>Switch In</label>
            </value>
            <value>
                <fullName>Subentro</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Morosita</fullName>
                <label>Morosità</label>
            </value>
            <value>
                <fullName>VolturaTecnica</fullName>
                <label>Voltura Tecnica</label>
            </value>
            <value>
                <fullName>ModificheAnagrafiche</fullName>
                <label>Modifiche Anagrafiche</label>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
            <value>
                <fullName>Subentro su Gdm Chiuso</fullName>
            </value>
            <value>
                <fullName>Prima Attivazione</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Nuovi Bonus e VAS</fullName>
            </value>
            <value>
                <fullName>Cambio uso</fullName>
                <label>CambioUso</label>
            </value>
            <value>
                <fullName>Cambio offerta</fullName>
            </value>
            <value>
                <fullName>Tariffe e Sconti</fullName>
            </value>
            <value>
                <fullName>CaricamentoCGC</fullName>
                <label>Caricamento CGC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/RequestKO__c.field-meta.xml
<CustomField>
    <fullName>RequestKO__c</fullName>
    <label>Numero Pratiche Con Esito Negativo</label>
    <summaryFilterItems>
        <field>MassiveLoaderRequestRequestItem__c.Status__c</field>
        <operation>equals</operation>
        <value>Errore</value>
    </summaryFilterItems>
    <summaryForeignKey>MassiveLoaderRequestRequestItem__c.MassiveLoaderRequest__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/RequestOK__c.field-meta.xml
<CustomField>
    <fullName>RequestOK__c</fullName>
    <label>Numero Pratiche Con Esito Positivo</label>
    <summaryFilterItems>
        <field>MassiveLoaderRequestRequestItem__c.Status__c</field>
        <operation>equals</operation>
        <value>Chiuso</value>
    </summaryFilterItems>
    <summaryForeignKey>MassiveLoaderRequestRequestItem__c.MassiveLoaderRequest__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>In attesa di lavorazione</fullName>
            </value>
            <value>
                <fullName>Pronto A Partire</fullName>
                <isActive>false</isActive>
                <label>Pronto A Partire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/TotalRequest__c.field-meta.xml
<CustomField>
    <fullName>TotalRequest__c</fullName>
    <label>Numero Pratiche</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priorità</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Media</label>
            </value>
            <value>
                <fullName>3</fullName>
                <default>true</default>
                <label>Bassa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_QR_MassiveLoaderRequest.cls
/**
 * @author Andrei Necsulescu (andrei.necsulescu@webresults.it)
 * @date 23/03/2021
 * @description HDT_QR_MassiveLoaderRequest - Class that holds queries for MassiveLoaderRequest__c
 * @history Inserire Nome Cognome – Data Modifica – Descrizione della modifica
 */

public with sharing class HDT_QR_MassiveLoaderRequest {

    HDT_UTL_Constants constantsUtl = new HDT_UTL_Constants();
    
    /**​
    * @author Andrei Necsulescu (andrei.necsulescu@webresults.it)​
    * @date 31/03/2021
    * @description HDT_QR_MassiveLoaderRequest.getRecordForImport() – Get record of MassiveLoaderRequest ordering by priority
    * @return List of extracted Massive Loader Requests
    */

    public List<MassiveLoaderRequest__c> getRecordForImport() {

        return [SELECT Id, ProcessType__c, Status__c, TotalRequest__c, RequestOK__c, RequestKO__c, Phase__c, Priority__c,
                       (SELECT Id, LinkedEntityId, ContentDocumentId, IsDeleted, SystemModstamp, ShareType, Visibility FROM contentdocumentlinks ORDER BY SystemModstamp DESC LIMIT 1) 
                FROM MassiveLoaderRequest__c 
                WHERE Status__c =: constantsUtl.MASSIVLOADER_STATUS_INATTESAlAVORAZIONE 
                AND Phase__c =: constantsUtl.MASSIVLOADER_PHASE_FILENONPROCESSATO
                ORDER BY Priority__c LIMIT 1];
    }
}