force-app/main/default/objects/PercentageRulesForAssigningVisits__c/PercentageRulesForAssigningVisits__c.object-meta.xml
<CustomObject>
    <label>Regola Percentuale Assegnazione Visite</label>
    <nameField>
        <label>Regole Percentuali Assegnazione Visite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regole Percentuali Assegnazione Visite</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PercentageRulesForAssigningVisits__c/fields/VisitAssignmentRules__c.field-meta.xml
<CustomField>
    <fullName>VisitAssignmentRules__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regole Assegnazione Visite</label>
    <referenceTo>VisitAssignmentRules__c</referenceTo>
    <relationshipLabel>Regole Percentuali Assegnazione Visite</relationshipLabel>
    <relationshipName>Regole_Percentuali_Assegnazione_Visite</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitAssignmentRules__c/VisitAssignmentRules__c.object-meta.xml
<CustomObject>
    <label>Regole Assegnazione Visite</label>
    <nameField>
        <label>Regole Assegnazione Visite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regole Assegnazione Visite</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_QR_PercentagRuleForAssignVisitsTst.cls
/**
 * @author Valere (valere@noeli-it.net)
 * @date 15/09/2021
 * @description HDT_QR_PercentageRulesForAssigningVisits Test Class
 * @history valere - 15/09/2021– Created Class
 */
@isTest
public class HDT_QR_PercentagRuleForAssignVisitsTst {
@testSetup
    static void setup(){
        VisitAssignmentRules__c va = HDT_UTL_DataFactoryTst.createVisitAssignmentRules (1, true,'Default')[0];
        HDT_UTL_DataFactoryTst.createPercentageRulesForAssigningVisits(1, true,'pfTest',va.id);
    }
    @isTest
    static void getRecordByIdTest(){
        string id = [SELECT id,name FROM PercentageRulesForAssigningVisits__c limit 1].id;
        PercentageRulesForAssigningVisits__c pf = HDT_QR_PercentageRulesForAssigningVisits.getRecordById(id);
        system.assertEquals('pfTest',pf.name);
        system.assertNotEquals(null,pf.name,'because the name value of this record has been provided');
    }
    @isTest
    static void getRecordsByVisitAssignmentRulesTest(){
         string id = [SELECT id,name FROM VisitAssignmentRules__c limit 1].id;
       PercentageRulesForAssigningVisits__c[] pfList = HDT_QR_PercentageRulesForAssigningVisits.getRecordsByVisitAssignmentRules(id);
        system.assertEquals(1,pfList.size());
        system.assertNotEquals(0,pfList.size(),'because we have inserted a PercentageRulesForAssigningVisits__c record linked to the assignment rule whose we are passing the id');
    }
     @isTest
    static void getDefaultValueTest(){
       PercentageRulesForAssigningVisits__c[] pfList = HDT_QR_PercentageRulesForAssigningVisits.getDefaultValue();
        system.assertEquals(1,pfList.size());
        system.assertNotEquals(0,pfList.size(),'we have 1 record with the default value');
    }
}