force-app/main/default/objects/HDT_SystemCapacityConfiguration__mdt/HDT_SystemCapacityConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>Configurazione Portata Impianto</label>
    <pluralLabel>Configurazioni Portata Impianto</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_SystemCapacityConfiguration__mdt/fields/CaliberRequested__c.field-meta.xml
<CustomField>
    <fullName>CaliberRequested__c</fullName>
    <label>Classe Contatore Richiesta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G1,6</fullName>
                <default>true</default>
                <label>G1,6</label>
            </value>
            <value>
                <fullName>G2</fullName>
            </value>
            <value>
                <fullName>G2,5</fullName>
            </value>
            <value>
                <fullName>G4</fullName>
            </value>
            <value>
                <fullName>G6</fullName>
            </value>
            <value>
                <fullName>G10</fullName>
            </value>
            <value>
                <fullName>G16</fullName>
            </value>
            <value>
                <fullName>G25</fullName>
            </value>
            <value>
                <fullName>G40</fullName>
            </value>
            <value>
                <fullName>G65</fullName>
            </value>
            <value>
                <fullName>G100</fullName>
            </value>
            <value>
                <fullName>G160</fullName>
            </value>
            <value>
                <fullName>G250</fullName>
            </value>
            <value>
                <fullName>G400</fullName>
            </value>
            <value>
                <fullName>G650</fullName>
            </value>
            <value>
                <fullName>G1000</fullName>
            </value>
            <value>
                <fullName>G1600</fullName>
            </value>
            <value>
                <fullName>G4000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_SystemCapacityConfiguration__mdt/fields/SystemCapacity__c.field-meta.xml
<CustomField>
    <fullName>SystemCapacity__c</fullName>
    <label>Portata Impianto (KWh)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_SystemCapacityConversion.cls
public with sharing class HDT_QR_SystemCapacityConversion {

    public static String querySystemCapacity(String field, String value){

        String query;

        String fieldToQuery = field == 'CaliberClass' ? 'SystemCapacity__c' : 'CaliberRequested__c';

        String fieldToFilter = field == 'CaliberClass' ? 'CaliberRequested__c' : 'SystemCapacity__c';

        String result;

        if(Schema.SObjectType.HDT_SystemCapacityConfiguration__mdt.isAccessible() &&
        Schema.SObjectType.HDT_SystemCapacityConfiguration__mdt.fields.CaliberRequested__c.isAccessible() &&
        Schema.SObjectType.HDT_SystemCapacityConfiguration__mdt.fields.SystemCapacity__c.isAccessible()){

            if(fieldToFilter == 'SystemCapacity__c'){

                value = value.replace('.', ',');

            }
            
            query = 'SELECT ' + fieldToQuery + ' FROM HDT_SystemCapacityConfiguration__mdt WHERE ' + fieldToFilter + ' = \'' + value + '\'';            


            List<HDT_SystemCapacityConfiguration__mdt> listResult = Database.query(query);
            
            result = field == 'CaliberClass' ? listResult[0].SystemCapacity__c : listResult[0].CaliberRequested__c;

        } else {

            return 'Impossibile accedere al Metadato';

        }

        return result;

    }

}