force-app/main/default/objects/HDT_UserInputFlow__mdt/HDT_UserInputFlow__mdt.object-meta.xml
<CustomObject>
    <label>HDT_UserInputFlow</label>
    <pluralLabel>HDT_UserInputFlow</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_UserInputFlow__mdt/fields/FieldsJSON__c.field-meta.xml
<CustomField>
    <fullName>FieldsJSON__c</fullName>
    <label>Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HDT_UserInputFlow__mdt/fields/ReadOnlyFields__c.field-meta.xml
<CustomField>
    <fullName>ReadOnlyFields__c</fullName>
    <label>ReadOnlyFields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HDT_UserInputFlow__mdt/fields/ValidateClass__c.field-meta.xml
<CustomField>
    <fullName>ValidateClass__c</fullName>
    <label>Validate Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_RecordEditFormFlowController.cls
public inherited sharing class HDT_QR_RecordEditFormFlowController {

    public static List<HDT_UserInputFlow__mdt> queryInput(String processType){
        
         List<HDT_UserInputFlow__mdt> userInputFlowList = [
            SELECT FieldsJSON__c, ValidateClass__c,ReadOnlyFields__c
            FROM HDT_UserInputFlow__mdt
            WHERE ProcessType__c =: processType
            LIMIT 1
        ];
        
        return userInputFlowList;
        
    }
    
    
    public static List<ContentDocumentLink> queryCdLink(Id arecordId){
        
        List<ContentDocumentLink> cdLs = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :arecordId];
        
        return cdLs;
        
    }
    
    public static List<ContentDocument> queryCd(List <Id> cdIdList){
        
        List<ContentDocument> entries = [SELECT Id, Title, FileType,CreatedDate FROM ContentDocument WHERE ContentDocument.Id IN :cdIdList];
        
        return entries;
        
    }
    
    
}