force-app/main/default/objects/Product2/fields/CategoryFamily__c.field-meta.xml
<CustomField>
    <fullName>CategoryFamily__c</fullName>
    <description>&quot;La categorie/famiglie offerte la cui  selezione è a carico del CM
    contenente la categorie/famiglie offerte la selezione è a carico del CM
&quot;</description>
    <label>Categoria Famiglia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A.R.E.R.A</fullName>
            </value>
            <value>
                <fullName>Arera Ranton</fullName>
            </value>
            <value>
                <fullName>Delibera 153/12</fullName>
            </value>
            <value>
                <fullName>Energia Serena</fullName>
            </value>
            <value>
                <fullName>Giorno Hera</fullName>
            </value>
            <value>
                <fullName>Giorno Hera Hcp Lucca</fullName>
            </value>
            <value>
                <fullName>Hello Hera</fullName>
            </value>
            <value>
                <fullName>Hello Ranton</fullName>
            </value>
            <value>
                <fullName>Hera Bebè</fullName>
            </value>
            <value>
                <fullName>Hera Etapiu</fullName>
            </value>
            <value>
                <fullName>Hera Impronta Zero</fullName>
            </value>
            <value>
                <fullName>Hera Welfare</fullName>
            </value>
            <value>
                <fullName>Indicizzato Ranton</fullName>
            </value>
            <value>
                <fullName>Mercato Libero Cmv</fullName>
            </value>
            <value>
                <fullName>Nuova Idea</fullName>
            </value>
            <value>
                <fullName>Nuova Idea Ranton</fullName>
            </value>
            <value>
                <fullName>Nuova Idea Tlr</fullName>
            </value>
            <value>
                <fullName>Offerta Gas Ranton</fullName>
            </value>
            <value>
                <fullName>Placet</fullName>
            </value>
            <value>
                <fullName>Prezzo Fisso</fullName>
            </value>
            <value>
                <fullName>Prezzo Fisso Leggero</fullName>
            </value>
            <value>
                <fullName>Prezzo Fisso Ranton</fullName>
            </value>
            <value>
                <fullName>Prezzo Fisso Tlr</fullName>
            </value>
            <value>
                <fullName>Prezzo Indicizzato Ranton</fullName>
            </value>
            <value>
                <fullName>Prezzo Netto</fullName>
            </value>
            <value>
                <fullName>Prezzo Netto Amga</fullName>
            </value>
            <value>
                <fullName>Prezzo Netto Comunita Solare</fullName>
            </value>
            <value>
                <fullName>Prezzo Netto Ranton</fullName>
            </value>
            <value>
                <fullName>Prezzo Netto Tlr</fullName>
            </value>
            <value>
                <fullName>Prezzo Sicurezza</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DescriptionSAP__c.field-meta.xml
<CustomField>
    <fullName>DescriptionSAP__c</fullName>
    <description>Descrizione del prodotto come su DB SAP</description>
    <label>Descrizione SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>il servizio del dato record di Prodotto nella funzionalità di Configurazione Offerta Tecnica</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>la versione del dato record di Prodotto nella funzionalità di Configurazione Offerta Tecnica</description>
    <label>Versione</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/SBQQ__ProductOption__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/CategoryFamily__c.field-meta.xml
<CustomField>
    <fullName>CategoryFamily__c</fullName>
    <label>Categoria Famiglia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <formula>TEXT(SBQQ__ConfiguredSKU__r.Service__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>Versione del Product</description>
    <formula>SBQQ__OptionalSKU__r.Version__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Versione</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_QR_ProductAssociation.cls
public inherited sharing class HDT_QR_ProductAssociation {
    
    public static Integer getCountOfNonConfiguredProduct2(String queryString){
    
        SObjectType objtype = Schema.getGlobalDescribe().get('Product2');
        Schema.DescribeSObjectResult objRes = objtype.getDescribe();
        String selectQuery = '';

        if(objRes.isAccessible()){
            selectQuery = 'SELECT count() ' + queryString;
        }

        return Database.countQuery(selectQuery);
    }

    public static List<Product2> getIdsNonConfiguredProduct2(List<Product2> prodList, String queryString){
        prodList = new List<Product2>();

        SObjectType objtype = Schema.getGlobalDescribe().get('Product2');
        Schema.DescribeSObjectResult objRes = objtype.getDescribe();
        String selectQuery = '';

        if(objRes.isAccessible()){
            selectQuery = 'SELECT Id, DescriptionSAP__c, ProductCode, Version__c, Name, Family, CategoryFamily__c, Service__c ' + queryString;
            System.debug('>>> queryString: ' + selectQuery);

            prodList = Database.query(selectQuery);
        }

        return prodList;
    }

    public static List<SBQQ__ProductOption__c> getProductOptionByOptionalSkuAndConfiguredSku(List<SBQQ__ProductOption__c> productOptionList, String optionalSku, List<String> configuredSkuList){

        SObjectType objtype = Schema.getGlobalDescribe().get('SBQQ__ProductOption__c');
        Schema.DescribeSObjectResult objRes = objtype.getDescribe();
        productOptionList = new List<SBQQ__ProductOption__c>();

        if(objRes.isAccessible()){
            productOptionList = [
                SELECT Id
                FROM SBQQ__ProductOption__c
                WHERE SBQQ__OptionalSKU__c = :optionalSku
                AND SBQQ__ConfiguredSKU__c IN :configuredSkuList
            ];
        }

        return productOptionList;

    }

    public static Id getCustomNotificationTypeId(){
        return [SELECT Id FROM CUstomNotificationType LIMIT 1].Id;
    }

    //public static void getJobStatus(){
    //    AsyncApexJob job = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors FROM AsyncApexJob WHERE ID = '' ];
    //}

    //public static SBQQ__ProductOption__c getProductOptionRecordById(Id productOptionId){
    //    
    //    SObjectType objtype = Schema.getGlobalDescribe().get('SBQQ__ProductOption__c');
    //    Schema.DescribeSObjectResult objRes = objtype.getDescribe();
    //    String selectQuery = '';

    //    if(objRes.isAccessible()){

    //        return [
    //            SELECT Id, SBQQ__Number__c,SBQQ__OptionalSKU__c
    //            FROM SBQQ__ProductOption__c
    //            WHERE Id = :productOptionId
    //        ];
    //    } else {
    //        return null;
    //    }
    //}

}