force-app/main/default/objects/Account/fields/ActiveServices__c.field-meta.xml
<CustomField>
    <fullName>ActiveServices__c</fullName>
    <description>KPI Servizi attivi</description>
    <formula>IF(ActiveServicesEle__c &gt; 0, IMAGE(IF($User.UITheme=&apos;Theme3&apos;, &apos;/sfsites/c&apos;, &apos;&apos;) &amp; $CustomMetadata.HDT_ImageURL__mdt.Service1.URL__c, $CustomMetadata.HDT_ImageURL__mdt.Service1.AlternateText__c, 30, 30), &apos;&apos;)
&amp;
IF(ActiveServicesGas__c &gt; 0, IMAGE(IF($User.UITheme=&apos;Theme3&apos;, &apos;/sfsites/c&apos;, &apos;&apos;) &amp; $CustomMetadata.HDT_ImageURL__mdt.Service2.URL__c, $CustomMetadata.HDT_ImageURL__mdt.Service2.AlternateText__c, 30, 30), &apos;&apos;)
&amp;
IF(ActiveServicesWater__c &gt; 0, IMAGE(IF($User.UITheme=&apos;Theme3&apos;, &apos;/sfsites/c&apos;, &apos;&apos;) &amp; $CustomMetadata.HDT_ImageURL__mdt.Service3.URL__c, $CustomMetadata.HDT_ImageURL__mdt.Service3.AlternateText__c, 30, 30), &apos;&apos;)
&amp;
IF(ActiveServicesWaste__c &gt; 0, IMAGE(IF($User.UITheme=&apos;Theme3&apos;, &apos;/sfsites/c&apos;, &apos;&apos;) &amp; $CustomMetadata.HDT_ImageURL__mdt.Service4.URL__c, $CustomMetadata.HDT_ImageURL__mdt.Service4.AlternateText__c, 30, 30), &apos;&apos;)
&amp;
IF(ActiveServicesTLR__c &gt; 0, IMAGE(IF($User.UITheme=&apos;Theme3&apos;, &apos;/sfsites/c&apos;, &apos;&apos;) &amp; $CustomMetadata.HDT_ImageURL__mdt.Service5.URL__c, $CustomMetadata.HDT_ImageURL__mdt.Service5.AlternateText__c, 30, 30), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizi attivi</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ActiveServicesEle__c.field-meta.xml
<CustomField>
    <fullName>ActiveServicesEle__c</fullName>
    <description>Campo tecnico nascosto. Necessario per calcolo KPI Servizi attivi.</description>
    <label>Numero forniture attive Energia Elettric</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ActiveServicesGas__c.field-meta.xml
<CustomField>
    <fullName>ActiveServicesGas__c</fullName>
    <description>Campo tecnico nascosto. Necessario per calcolo KPI Servizi attivi.</description>
    <label>Numero forniture attive Gas</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ActiveServicesTLR__c.field-meta.xml
<CustomField>
    <fullName>ActiveServicesTLR__c</fullName>
    <description>Campo tecnico nascosto. Necessario per calcolo KPI Servizi attivi.</description>
    <label>Numero forniture attive TLR</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ActiveServicesWaste__c.field-meta.xml
<CustomField>
    <fullName>ActiveServicesWaste__c</fullName>
    <description>Campo tecnico nascosto. Necessario per calcolo KPI Servizi attivi.</description>
    <label>Numero forniture attive Ambiente</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ActiveServicesWater__c.field-meta.xml
<CustomField>
    <fullName>ActiveServicesWater__c</fullName>
    <description>Campo tecnico nascosto. Necessario per calcolo KPI Servizi attivi.</description>
    <label>Numero forniture attive Acqua</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_ActiveServicesKpi.cls
public with sharing class HDT_UTL_ActiveServicesKpi {
    public static void run(Map<Id,SObject> newMap, Map<Id,SObject> oldMap) {
        Set<Id> contractIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();

        for(Contract c : (List<Contract>) newMap.values()) {
            contractIds.add(c.Id);
            accountIds.add(c.AccountId);
        }

        Map<Id,Contract> contractMap = new Map<Id,Contract>([SELECT Id,ServicePoint__r.CommoditySector__c FROM Contract WHERE Id IN :contractIds]);
        Map<Id,Account> accountMap = new Map<Id,Account>([SELECT Id, ActiveServicesEle__c, ActiveServicesGas__c, ActiveServicesTLR__c, ActiveServicesWater__c, ActiveServicesWaste__c FROM Account WHERE Id IN :accountIds]);

        Account account;
        String service;
        Contract oldContract;
        for(Contract c : (List<Contract>) newMap.values()) {
            account = accountMap.get(c.AccountId);
            service = contractMap.get(c.Id).ServicePoint__r.CommoditySector__c;
            oldContract = oldMap != null ? (Contract) oldMap.get(c.Id) : null;

            if(oldContract == null || (c.Status == 'Attivo' && oldContract.Status != 'Attivo')) {
                updateServicesCount(account, service, 1);
            } else if(c.Status != 'Attivo' && oldContract.Status == 'Attivo') {
                updateServicesCount(account, service, (-1));
            }
        }

        update accountMap.values();
    }

    public static void updateServicesCount(Account account, String service, Integer delta) {
        switch on service {
            when 'Energia Elettrica' {
                if (account.ActiveServicesEle__c == null) {
                    account.ActiveServicesEle__c = 0;
                }
                account.ActiveServicesEle__c += delta;
            }
            when 'Gas' {
                if (account.ActiveServicesGas__c == null) {
                    account.ActiveServicesGas__c = 0;
                }
                account.ActiveServicesGas__c += delta;
            }
            // when 'Multi' {
            //    if (account.ActiveServices__c == null) {
            //           account.ActiveServices__c = 0;
            //    }
            //     account.ActiveServices__c += delta;
            // }
            when 'Teleriscaldamento' {
                if (account.ActiveServicesTLR__c == null) {
                    account.ActiveServicesTLR__c = 0;
                }
                account.ActiveServicesTLR__c += delta;
            }
            when 'Acqua' {
                if (account.ActiveServicesWater__c == null) {
                    account.ActiveServicesWater__c = 0;
                }
                account.ActiveServicesWater__c += delta;
            }
            when 'Ambiente' {
                if (account.ActiveServicesWaste__c == null) {
                    account.ActiveServicesWaste__c = 0;
                }
                account.ActiveServicesWaste__c += delta;
            }
        }
    }
}