force-app/main/default/objects/Account/fields/BillingStreetName__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetName__c</fullName>
    <label>Nome Via [Residenziale/Sede Legale]</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNumber__c</fullName>
    <label>Civico [Residenziale/Sede Legale]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetToponym__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetToponym__c</fullName>
    <description>Contiene il Toponimo dell&apos;indirizzo</description>
    <label>Toponimo [Residenziale/Sede Legale]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BuildingFloor__c.field-meta.xml
<CustomField>
    <fullName>BuildingFloor__c</fullName>
    <label>Piano[Residenziale/Sede Legale]</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>Codice Business Partner (BP) di SAP</description>
    <externalId>true</externalId>
    <label>Codice cliente</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerMarking__c.field-meta.xml
<CustomField>
    <fullName>CustomerMarking__c</fullName>
    <description>Rappresenta una segmentazione del cliente</description>
    <label>Marcatura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerMarking</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Nome del cliente B2C</description>
    <label>Nome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Cognome del cliente B2C</description>
    <label>Cognome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Cellulare</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryEmail__c.field-meta.xml
<CustomField>
    <fullName>PrimaryEmail__c</fullName>
    <description>Valorizzare con l&apos;indirizzo Email primario del contatto primario</description>
    <label>Email primaria</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroup__c.field-meta.xml
<CustomField>
    <fullName>VATGroup__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Partita IVA di Gruppo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroupEndDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupEndDate__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Data Fine Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroupStartDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupStartDate__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Data Inizio Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita Iva</description>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Riferimento all&apos;Account</description>
    <label>Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Profiles</relationshipLabel>
    <relationshipName>BillingProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/ContractAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ContractAccountCode__c</fullName>
    <description>Codice Contract Account Sap</description>
    <externalId>true</externalId>
    <label>Conto Contrattuale</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BillingProfile__c/fields/CustomerMarking__c.field-meta.xml
<CustomField>
    <fullName>CustomerMarking__c</fullName>
    <formula>TEXT(Account__r.CustomerMarking__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marcatura Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CertifiedEmail__c.field-meta.xml
<CustomField>
    <fullName>CertifiedEmail__c</fullName>
    <label>Pec</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account del titolare del punto di fornitura</description>
    <label>Account Titolare</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points (Account)</relationshipLabel>
    <relationshipName>Service_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributore</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Necessario inserire un Account Distributore</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HDT_RT_Distributore</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points</relationshipLabel>
    <relationshipName>ServicePoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterStatus__c.field-meta.xml
<CustomField>
    <fullName>MeterStatus__c</fullName>
    <label>Stato Apparecchiatura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Attivo</fullName>
            </value>
            <value>
                <fullName>Inattivo</fullName>
            </value>
            <value>
                <fullName>Sospeso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CustomerMarking.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAS Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Altro</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D1 - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>D2 - Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>D3 - Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>D4 - Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>D5 - Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D6 - Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>D7 - BP Doppio</fullName>
    </customValue>
    <description>Rappresenta una segmentazione del cliente</description>
    <masterLabel>Marcatura Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_QR_ProcessSales.cls
public inherited sharing class HDT_QR_ProcessSales {

    public static List<Account> getAccountList(Set<String> fiscalCodeSet, Set<String> vatNumberSet, Set<String> marcaturaSet, Set<String> csnSet){
        return [
            SELECT Id, CustomerCode__c, FiscalCode__c, VATNumber__c, CustomerMarking__c
            FROM Account
            WHERE CustomerCode__c IN :csnSet
            OR (
                FiscalCode__c IN :fiscalCodeSet
                AND VATNumber__c IN :vatNumberSet
                AND CustomerMarking__c IN :marcaturaSet
                )
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<BillingProfile__c> getBillingProfileList(Set<String> contoContrattualeSet){
        return [
            SELECT Id, ContractAccountCode__c
            FROM BillingProfile__c
            WHERE ContractAccountCode__c IN: contoContrattualeSet
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<AccountContactRelation> getAccountContactRelationByAccountId(List<AccountContactRelation> acrList, List<Id> accountIdsList){
        acrList = new List<AccountContactRelation>();
        acrList = [
            SELECT Id, Roles
            FROM AccountContactRelation
            WHERE AccountId IN :accountIdsList
            WITH SECURITY_ENFORCED
        ];
        return acrList;
    }

    public static List<ServicePoint__c> getServicePointList(List<ServicePoint__c> servicePointList, List<Id> servPointIdsList){
        servicePointList = new List<ServicePoint__c>();
        servicePointList = [
            SELECT Id, MeterStatus__c, Distributor__c, Account__c, ServicePointCode__c, Name
            FROM ServicePoint__c
            WHERE Id = :servPointIdsList
            WITH SECURITY_ENFORCED
        ];
        return servicePointList;
    }

    public static List<AccountContactRelation> getAccountContactRelationList(List<AccountContactRelation> accContRelList, List<Id> accountIdsList){
        accContRelList = new List<AccountContactRelation>();
        accContRelList = [
            SELECT AccountId, Account.Name, Account.RecordTypeId, Account.LastName__c, Account.FirstName__c, Account.Category__c,
                   Account.Fax, Account.CustomerMarking__c, Account.FiscalCode__c, Account.Vatnumber__c, Account.BillingCity,
                   Account.BillingCountry, Account.BillingStreetToponym__c, Account.BillingStreetNumber__c, Account.BillingPostalCode,
                   Account.BillingState, Account.BillingStreetName__c, Account.CustomerCode__c, Account.MobilePhone__c, Account.BuildingFloor__c,
                   Account.PrimaryEmail__c, Account.VATGroup__c, Account.VATGroupStartDate__c, Account.VATGroupEndDate__c,
                   ContactId, Contact.MobilePhone, Contact.email, Contact.fiscalCode__c, Contact.CertifiedEmail__c
            FROM AccountContactRelation
            WHERE AccountId IN :accountIdsList
            WITH SECURITY_ENFORCED
        ];
        return accContRelList;
    }
}