force-app/main/default/objects/Account/fields/BillingCityCode__c.field-meta.xml
<CustomField>
    <fullName>BillingCityCode__c</fullName>
    <description>Codice Comune SAP</description>
    <label>Codice ISTAT [Residenziale/Sede Legale]</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingIsAddressVerified__c.field-meta.xml
<CustomField>
    <fullName>BillingIsAddressVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indirizzo Verificato [Residenziale/Sede</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingPlace__c.field-meta.xml
<CustomField>
    <fullName>BillingPlace__c</fullName>
    <label>Località [Residenziale/Sede Legale]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetCode__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetCode__c</fullName>
    <description>Codice via stradario SAP</description>
    <label>Codice Via Stradario SAP [Residenziale/S</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetName__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetName__c</fullName>
    <label>Nome Via [Residenziale/Sede Legale]</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNumber__c</fullName>
    <label>Civico [Residenziale/Sede Legale]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetNumberExtension__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNumberExtension__c</fullName>
    <label>Estens.Civico [Residenziale/Sede Legale]</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetToponym__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetToponym__c</fullName>
    <description>Contiene il Toponimo dell&apos;indirizzo</description>
    <label>Toponimo [Residenziale/Sede Legale]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerMarking__c.field-meta.xml
<CustomField>
    <fullName>CustomerMarking__c</fullName>
    <description>Rappresenta una segmentazione del cliente</description>
    <label>Marcatura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerMarking</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Nome del cliente B2C</description>
    <label>Nome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Cognome del cliente B2C</description>
    <label>Cognome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroup__c.field-meta.xml
<CustomField>
    <fullName>VATGroup__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Partita IVA di Gruppo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita Iva</description>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/HDT_RT_Business.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Order/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <label>Comune [Fatturazione]</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingCityCode__c.field-meta.xml
<CustomField>
    <fullName>BillingCityCode__c</fullName>
    <label>Codice ISTAT [Fatturazione]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Stato [Fatturazione]</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingIsAddressVerified__c.field-meta.xml
<CustomField>
    <fullName>BillingIsAddressVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indirizzo Verificato [Fatturazione]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingPlace__c.field-meta.xml
<CustomField>
    <fullName>BillingPlace__c</fullName>
    <label>Località [Fatturazione]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingPostalCode__c</fullName>
    <label>Cap[Fatturazione]</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingProvince__c.field-meta.xml
<CustomField>
    <fullName>BillingProvince__c</fullName>
    <label>Provincia [Fatturazione]</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingStreetName__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetName__c</fullName>
    <label>Nome Via [Fatturazione]</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingStreetNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNumber__c</fullName>
    <label>Civico [Fatturazione]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingStreetNumberExtension__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNumberExtension__c</fullName>
    <label>Estensione Civico [Fatturazione]</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillingStreetToponym__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetToponym__c</fullName>
    <label>Toponimo [Fatturazione]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <formula>TEXT(Account.CompanyOwner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerMarking__c.field-meta.xml
<CustomField>
    <fullName>CustomerMarking__c</fullName>
    <formula>TEXT(Account.CustomerMarking__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marcatura Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SignedDate__c.field-meta.xml
<CustomField>
    <fullName>SignedDate__c</fullName>
    <description>In caso di contratto esiste, la data in cui è stato firmato</description>
    <label>Data Firma</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <customValue>
        <fullName>Famiglie</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CustomerMarking.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAS Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Altro</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D1 - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>D2 - Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>D3 - Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>D4 - Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>D5 - Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D6 - Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>D7 - BP Doppio</fullName>
    </customValue>
    <description>Rappresenta una segmentazione del cliente</description>
    <masterLabel>Marcatura Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_SwtichInProcessTest.cls
@isTest
public class HDT_UTL_SwtichInProcessTest {
    
        @testSetup
        static void setup() {

            Id rtId = [SELECT Id FROM recordType WHERE developerName = 'HDT_RT_Business' and sObjectType = 'Account'].Id;

            Account acc = new Account();

                acc.FirstName__c = 'Mickey';
                acc.LastName__c = 'Mouse';
                acc.Name = 'Mickey Mouse';
                acc.FiscalCode__c = 'PCCLSN78C24B354F';
                acc.RecordTypeId = rtId;            
                acc.VatNumber__c = '99999999999';
                acc.CustomerMarking__c = 'ACEL-Persona fisica';
                acc.Category__c = 'Aziende';
                acc.CompanyOwner__c = 'HERA COMM';
                // acc.BillingCity = currentCase.BillingCity__c;
                // acc.BillingCityCode__c = currentCase.BillingCityCode__c;
                // acc.BillingCountry = currentCase.BillingCountry__c;
                // acc.BillingIsAddressVerified__c = currentCase.BillingIsAddressVerified__c;
                // acc.BillingPlace__c = currentCase.BillingPlace__c;
                // acc.BillingPostalCode = currentCase.BillingPostalCode__c;
                // acc.BillingState = currentCase.BillingProvince__c;
                // acc.BillingStreetCode__c = currentCase.BillingStreetCode__c;
                // acc.BillingStreetName__c = currentCase.BillingStreetName__c;
                // acc.BillingStreetNumber__c = currentCase.BillingStreetNumber__c;
                // acc.BillingStreetNumberExtension__c = currentCase.BillingStreetNumberExtension__c;
                // acc.BillingStreetToponym__c = currentCase.BillingStreetToponym__c;
                // objToUpdate = acc;
            

            //Account accTest = new Account(FirstName__c='Test001',LastName__c='AccountTest',FiscalCode__c='00100010',Category__c='Famiglie', CustomerMarking__c='ACEL-Persona fisica',VATNumber__c='', VATGroup__c='');
            insert acc;

            Date Ed = Date.today();

            Order ordTest = new Order(Status='Draft', EffectiveDate=Ed,SignedDate__c=Ed);
            ordTest.AccountId = acc.Id;
            insert ordTest;

        }   

        @isTest static void getMaxAfterthoughtDateTest() {

            Test.startTest();   
                Order testOrder = [select id, SignedDate__c from Order];

                HDT_UTL_SwtichInProcess.getMaxAfterthoughtDate(testOrder);

                Test.stopTest();

        }

}