force-app/main/default/objects/Account/fields/BillingStreetName__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetName__c</fullName>
    <label>Nome Via [Residenziale/Sede Legale]</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNumber__c</fullName>
    <label>Civico [Residenziale/Sede Legale]</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BuildingFloor__c.field-meta.xml
<CustomField>
    <fullName>BuildingFloor__c</fullName>
    <label>Piano[Residenziale/Sede Legale]</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>Codice Business Partner (BP) di SAP</description>
    <externalId>true</externalId>
    <label>Codice cliente</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerMarking__c.field-meta.xml
<CustomField>
    <fullName>CustomerMarking__c</fullName>
    <description>Rappresenta una segmentazione del cliente</description>
    <label>Marcatura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerMarking</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Nome del cliente B2C</description>
    <label>Nome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Cognome del cliente B2C</description>
    <label>Cognome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Cellulare</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryEmail__c.field-meta.xml
<CustomField>
    <fullName>PrimaryEmail__c</fullName>
    <description>Valorizzare con l&apos;indirizzo Email primario del contatto primario</description>
    <label>Email primaria</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroup__c.field-meta.xml
<CustomField>
    <fullName>VATGroup__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Partita IVA di Gruppo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroupEndDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupEndDate__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Data Fine Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroupStartDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupStartDate__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Data Inizio Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita Iva</description>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CertifiedEmail__c.field-meta.xml
<CustomField>
    <fullName>CertifiedEmail__c</fullName>
    <label>Pec</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/NextStepData__c.field-meta.xml
<CustomField>
    <fullName>NextStepData__c</fullName>
    <label>Next Step Data</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In attesa di lavorazione</fullName>
                <default>true</default>
                <label>In attesa di lavorazione</label>
            </value>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Errore</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
                <isActive>false</isActive>
                <label>Done</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Ready To Run</fullName>
                <isActive>false</isActive>
                <label>Ready To Run</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/StatusDescription__c.field-meta.xml
<CustomField>
    <fullName>StatusDescription__c</fullName>
    <description>Used for error status</description>
    <label>Status Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Impianto compl. in funzione</fullName>
            </value>
            <value>
                <fullName>Interruzione avviata</fullName>
            </value>
            <value>
                <fullName>Impianto parzialmente chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto compl. chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto in attivazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CustomerMarking.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAS Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Altro</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D1 - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>D2 - Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>D3 - Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>D4 - Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>D5 - Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D6 - Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>D7 - BP Doppio</fullName>
    </customValue>
    <description>Rappresenta una segmentazione del cliente</description>
    <masterLabel>Marcatura Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_ProcessSalesOutboundWs.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public inherited sharing class HDT_UTL_ProcessSalesOutboundWs {

    private List<Id> accountIdsList;
    private List<Id> billProfIdsList;
    private List<Id> servPointIdsList;
    private List<ServicePoint__c> servicePointList;
    private Map<Id, HDT_UTL_ProcessSales.HDT_WRP_NextDataObj> idsMap;
    Map<Id, ServicePoint__c> servicePointMap;
    List<MassiveLoaderRequestItem__c> requestItemList;
    List<ServicePoint__c> servicePointToUpdate;
    List<AccountContactRelation> accContRelList;
    Map<Id, AccountContactRelation> accRelMap;
    List<MassiveLoaderRequestItem__c> requestItemForUpsert = new List<MassiveLoaderRequestItem__c>();
    private Set<String> servicePointFields;
    private String process;

    public HDT_UTL_ProcessSalesOutboundWs() {
        System.debug(LoggingLevel.DEBUG, 'HDT_UTL_ProcessSalesOutboundWs');
    }

    public void setRequestItemList(List<MassiveLoaderRequestItem__c> requestItemList, String process){
        this.requestItemList = requestItemList;
        this.process = process;
        setServicePointFields('ServicePoint__c', 'CarMassEnrichmentFields');
    }

    public void generateWrapperMap(){

        System.debug(LoggingLevel.DEBUG, '# setRequestItemList #');

        accountIdsList = new List<Id>();
        billProfIdsList = new List<Id>();
        servPointIdsList = new List<Id>();
        Set<Id> servPointIdSet = new Set<Id>();
        accRelMap = new Map<Id, AccountContactRelation>();

        HDT_UTL_ProcessSales.HDT_WRP_NextDataObj obj;
        idsMap = new Map<Id, HDT_UTL_ProcessSales.HDT_WRP_NextDataObj>();

        for(MassiveLoaderRequestItem__c singleItem : requestItemList){

            if(!String.isEmpty(singleItem.NextStepData__c)){
                obj = (HDT_UTL_ProcessSales.HDT_WRP_NextDataObj)JSON.deserialize(singleItem.NextStepData__c, HDT_UTL_ProcessSales.HDT_WRP_NextDataObj.class);
                System.debug('>>>> current item data ' + obj);
    
                idsMap.put(singleItem.Id, obj);
    
                if(String.isNotEmpty(obj.accountId)){
                    accountIdsList.add(obj.accountId);
                }

                if(String.isNotEmpty(obj.billProfId)){
                    billProfIdsList.add(obj.billProfId);
                }

                if(String.isNotEmpty(obj.servPointId)){
                    //servPointIdsList.add(obj.servPointId);
                    servPointIdSet.add(obj.servPointId);
                }

            }

        }

        if(servPointIdSet.size()>0){
            servPointIdsList.addAll(servPointIdSet);
        }

    }

    public void getRecords(){
        System.debug(LoggingLevel.DEBUG, '# getRecords #');

        servicePointList = HDT_QR_ProcessSales.getServicePointList(servicePointList, servPointIdsList);
        servicePointMap = new Map<Id, ServicePoint__c>(servicePointList);

        System.debug(LoggingLevel.DEBUG, '>>> servicePointList size ' + servicePointList.size());

        accContRelList = HDT_QR_ProcessSales.getAccountContactRelationList(accContRelList, accountIdsList);

        for(AccountContactRelation rel : accContRelList){
           accRelMap.put(rel.AccountId, rel);
        }

    }

    public void executeWebService(){

        System.debug(LoggingLevel.DEBUG, '# executeWebService #');
        HDT_WS_ArrichmentDataEntityResponse serResp;
        servicePointToUpdate = new List<ServicePoint__c>();
        List<Account> accountToUpdate = new List<Account>();
        ServicePoint__c servPointFromWs;
        ServicePoint__c oldServPoint;
        Id servicePointId;
        Id accountId;
        Account account;
        Contact contact;
        
        for(MassiveLoaderRequestItem__c singleItem : requestItemList){
            try {
                servicePointId = idsMap.get(singleItem.Id).servPointId;

                if(String.isNotEmpty(servicePointId)){

                    servPointFromWs = servicePointMap.get(servicePointId);

                    if(process.equalsIgnoreCase('CambioUso')){
                        oldServPoint = setOldServicePoint(servPointFromWs, oldServPoint);
                    }

                    serResp = HDT_WS_ArrichmentDataEntityInvoker.callService('', servPointFromWs.Name);
                    System.debug(serResp);

                    if(serResp.statusCode == 200){
                        servPointFromWs = HDT_UTL_ServicePoint.extractDataFromArriccDataServiceWithExistingSp(servPointFromWs, serResp)[0];
                        System.debug(LoggingLevel.DEBUG, '>>> update sp ' + servPointFromWs);

                        if(process.equalsIgnoreCase('CambioUso')){
                            servPointFromWs = setServicePointAfterWebService(servPointFromWs, oldServPoint);
                        }

                        servicePointToUpdate.add(servPointFromWs);
                        requestItemForUpsert.add(singleItem);
                    } else {
                        System.debug(LoggingLevel.DEBUG, '>>> [ServicePoint__c] errore arrichimento dati');
                    }
                }
            } catch (Exception e){
                System.debug(LoggingLevel.DEBUG, 'Exception > HDT_UTL_ProcessSalesOutboundWs: ' + e.getMessage());
                singleItem.Status__c = 'Errore';
                singleItem.StatusDescription__c = e.getMessage().abbreviate(250);
            }
        }
    }

    public void updateItems(){

        if(servicePointToUpdate.size() > 0){
            update servicePointToUpdate;
        }

        update requestItemList;
        //HDT_UTL_ProcessExecution.getLimitDetails('finalUpdate');
    }

    public static Account setAccountRecord(AccountContactRelation rel, Account a){
        a.Id = rel.AccountId;
        a.Name = rel.Account.Name;
        a.RecordTypeId = rel.Account.RecordTypeId;
        a.LastName__c = rel.Account.LastName__c;
        a.FirstName__c = rel.Account.FirstName__c;
        a.Category__c = rel.Account.Category__c;
        a.Fax = rel.Account.Fax;
        a.CustomerMarking__c = rel.Account.CustomerMarking__c;
        a.FiscalCode__c = rel.Account.FiscalCode__c;
        a.Vatnumber__c = rel.Account.Vatnumber__c;
        a.BillingCity = rel.Account.BillingCity;
        a.BillingCountry = rel.Account.BillingCountry;
        a.BillingStreetNumber__c = rel.Account.BillingStreetNumber__c;
        a.BillingPostalCode = rel.Account.BillingPostalCode;
        a.BillingState = rel.Account.BillingState;
        a.BillingStreetName__c = rel.Account.BillingStreetName__c;
        a.CustomerCode__c = rel.Account.CustomerCode__c;
        a.MobilePhone__c = rel.Account.MobilePhone__c;
        a.BuildingFloor__c = rel.Account.BuildingFloor__c;
        a.PrimaryEmail__c = rel.Account.PrimaryEmail__c;
        a.VATGroup__c = rel.Account.VATGroup__c;
        a.VATGroupStartDate__c = rel.Account.VATGroupStartDate__c;
        a.VATGroupEndDate__c = rel.Account.VATGroupEndDate__c;
        return a;
    }

    public static Contact setContactRecord(AccountContactRelation rel, Contact c){
        c.Id = rel.ContactId;
        c.MobilePhone = rel.Contact.MobilePhone;
        c.email = rel.Contact.email;
        c.fiscalCode__c = rel.Contact.fiscalCode__c;
        c.CertifiedEmail__c = rel.Contact.CertifiedEmail__c;
        return c;
    }

    private ServicePoint__c setOldServicePoint(ServicePoint__c servPointFromWs, ServicePoint__c oldServPoint){
        oldServPoint = new ServicePoint__c();
 
        Map<String, Object> fieldsToValue;
        fieldsToValue = servPointFromWs.getPopulatedFieldsAsMap();

        Object field;
        for(String fieldToSet : servicePointFields){
            field = fieldsToValue.get(fieldToSet);
            oldServPoint.put(fieldToSet, field);
        }

        return oldServPoint;
    }

    private ServicePoint__c setServicePointAfterWebService(ServicePoint__c servPointFromWs, ServicePoint__c oldServPoint){

        Map<String, Object> fieldsToValue;
        fieldsToValue = oldServPoint.getPopulatedFieldsAsMap();

        Object field;
        for(String fieldToSet : servicePointFields){
            field = fieldsToValue.get(fieldToSet);
            servPointFromWs.put(fieldToSet, field);
        }

        return servPointFromWs;
    }

    public void setServicePointFields(String sObjectName, String fieldSetName){
        List<Schema.FieldSetMember> fieldSetMembers;
        servicePointFields = new Set<String>();  
        fieldSetMembers = ((SObject)Type.forName(sObjectName).newInstance()).getSObjectType().getDescribe().FieldSets.getMap().get(fieldSetName).getFields();
        for(Schema.FieldSetMember s : fieldSetMembers) {
            servicePointFields.add(String.valueOf(s.getFieldPath()));
        }
    }

}