force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campagna CRM</fullName>
            </value>
            <value>
                <fullName>Campagna Outbound</fullName>
            </value>
            <value>
                <fullName>Campagna Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Campagna Contenitore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Canale verso il quale verrà erogata la campagna</description>
    <label>Canale</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefonico Inbound</fullName>
            </value>
            <value>
                <fullName>Sportello</fullName>
            </value>
            <value>
                <fullName>SOL</fullName>
            </value>
            <value>
                <fullName>Telefonico Outbound</fullName>
            </value>
            <value>
                <fullName>Door to Door</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Push</fullName>
            </value>
            <value>
                <fullName>Cartaceo</fullName>
            </value>
            <value>
                <fullName>Bolletta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SalesChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>HC Point</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie SME</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Punti Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
        <isActive>false</isActive>
        <label>Consip</label>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <isActive>false</isActive>
        <label>Reseller</label>
    </customValue>
    <description>Canale vendita associato all&apos;utente</description>
    <masterLabel>Canale Vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_TRH_CampaignMemberTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 15/09/2021
 * @description HDT_TRH_CampaignMember Test Classes
 * @history Fabricio Petkevicius Nunes – 15/09/2021 – Created class
 */
@isTest
public with sharing class HDT_TRH_CampaignMemberTst{
	private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
	@isTest
	public static void testTriggerSubscriptionBeforeAfterInsert(){

		Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME);
		User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);
		internalUser.UserPermissionsMarketingUser=true;
		insert internalUser;

		System.runAs(internalUser){

			test.startTest();

			List<Account> accounts=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
			List<Contact> contacts=HDT_UTL_DataFactoryTst.createContact(1, true, accounts[0].Id);
			List<Lead> leads=HDT_UTL_DataFactoryTst.createLead(1, true);
			List<Campaign> campaigns=HDT_UTL_DataFactoryTst.createCampaign(1, false);
			campaigns[0].Category__c='Campagna Outbound';
			campaigns[0].Channel__c='Bolletta';
			insert campaigns;

			List<CampaignMember> campMembers=HDT_UTL_DataFactoryTst.createCampaignMember(1, true, campaigns[0].Id, leads[0].Id, contacts[0].Id);

			test.stopTest();

			List<CampaignMember> tCampMembs=[SELECT Id
			                                 FROM CampaignMember
			                                 WHERE Id=:campMembers[0].Id];

			System.assertEquals(true, tCampMembs[0].Id!=null, 'Campaign Member not Inserted');
			System.assertNotEquals(false, tCampMembs[0].Id!=null, 'Campaign Member not Inserted');
		}
	}
}