force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campagna CRM</fullName>
            </value>
            <value>
                <fullName>Campagna Outbound</fullName>
            </value>
            <value>
                <fullName>Campagna Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Campagna Contenitore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Canale verso il quale verrà erogata la campagna</description>
    <label>Canale</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefonico Inbound</fullName>
            </value>
            <value>
                <fullName>Sportello</fullName>
            </value>
            <value>
                <fullName>SOL</fullName>
            </value>
            <value>
                <fullName>Telefonico Outbound</fullName>
            </value>
            <value>
                <fullName>Door to Door</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Push</fullName>
            </value>
            <value>
                <fullName>Cartaceo</fullName>
            </value>
            <value>
                <fullName>Bolletta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/CodeGenerationRule__c.field-meta.xml
<CustomField>
    <fullName>CodeGenerationRule__c</fullName>
    <label>Regola generazione codice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CodeManagementModel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manuale</fullName>
            </value>
            <value>
                <fullName>PrefissoProgressivo</fullName>
                <label>Prefisso + Progressivo</label>
            </value>
            <value>
                <fullName>Prefisso + Nome + Cognome + Progressivo</fullName>
            </value>
            <value>
                <fullName>CognomeProgressivo</fullName>
                <isActive>false</isActive>
                <label>Cognome + Progressivo</label>
            </value>
            <value>
                <fullName>PrefissoNome</fullName>
                <isActive>false</isActive>
                <label>Prefisso + Nome</label>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/CodeManagementModel__c.field-meta.xml
<CustomField>
    <fullName>CodeManagementModel__c</fullName>
    <description>Generico, Per singolo Campaign Member, Porta un amico: selezionabile solo con Campagne MC e Campagne Outbound con canale Bolletta. Pubblico e Convenzione sono compatibili solo con Campagne CRM</description>
    <label>Modello Gestione Codici</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nessuno</fullName>
            </value>
            <value>
                <fullName>Generico</fullName>
            </value>
            <value>
                <fullName>Per singolo Campaign Member</fullName>
            </value>
            <value>
                <fullName>Porta un amico</fullName>
            </value>
            <value>
                <fullName>Pubblico</fullName>
            </value>
            <value>
                <fullName>Convenzione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/PrefixCode__c.field-meta.xml
<CustomField>
    <fullName>PrefixCode__c</fullName>
    <label>Codice Completo / Prefisso</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/PromoCommercialCode__c.field-meta.xml
<CustomField>
    <fullName>PromoCommercialCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l’oggetto che definisce i codici commerciali. Il campo è gestito in automatico dal sistema e non è editabile dall’utente</description>
    <label>Codice Commerciale</label>
    <referenceTo>CommercialCode__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommercialCode__c/CommercialCode__c.object-meta.xml
<CustomObject>
    <label>Codice Commerciale</label>
    <nameField>
        <label>Codice Commerciale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codici Commerciali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Società Silos</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Società Silos</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HC</fullName>
    </customValue>
    <customValue>
        <fullName>HCM</fullName>
    </customValue>
    <customValue>
        <fullName>EENE</fullName>
        <label>NEWCO</label>
    </customValue>
    <customValue>
        <fullName>HSPA</fullName>
    </customValue>
    <customValue>
        <fullName>EB</fullName>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HC+HCM+EENE</fullName>
    </customValue>
    <description>Identifica la società di appartenenza</description>
    <masterLabel>Company</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SalesChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>HC Point</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie SME</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Punti Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
        <isActive>false</isActive>
        <label>Consip</label>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <isActive>false</isActive>
        <label>Reseller</label>
    </customValue>
    <description>Canale vendita associato all&apos;utente</description>
    <masterLabel>Canale Vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_BA_CommercialCodeTst.cls
/**
 * Header of the class "HDT_BA_CommercialCodeTst"
 * @author Cesare Bagnolini, cesare.bagnolini@webresults.it
 * @version 1.0
 * @description: Apex Test Class of the relative Apex Class "HDT_BA_CommercialCode"
 * @history
 * @Created 20/09/2021
 * Modified By:
 **/
@isTest
public class HDT_BA_CommercialCodeTst {
	private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
    
    @TestSetup
    static void makedata(){
        
        Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME);
		User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);
		internalUser.UserPermissionsMarketingUser=true;

		insert internalUser;

        System.runAs(internalUser){
        	
            
            List<Campaign> camps = HDT_UTL_DataFactoryTst.createCampaign(1, false);
            for(Campaign c : camps){
                c.CodeManagementModel__c ='Porta un amico';
                c.Channel__c = 'Bolletta';
                c.Category__c= 'Campagna Outbound';
                c.CodeGenerationRule__c = 'PrefissoProgressivo';
                c.PrefixCode__c = 'TST';
            }
            insert camps;
            
            
            List<Lead> leads = HDT_UTL_DataFactoryTst.createLead(1,true); 
            
            
            List<Account> accs = HDT_UTL_DataFactoryTst.createAccountBusiness(1,true,'MMS','MMS Azienda','Aziende SME');
            Id accId = accs[0].id;
            
            
            List<Contact> contacts = HDT_UTL_DataFactoryTst.createContact(50,false,accId);
            integer i=0;
            for(Contact c : contacts){
                c.Email='email@'+i+'.it';
                c.Company__c='MMS';
                i++;
            }
            insert contacts;
            
            
            List<CampaignMember> campMembers = HDT_UTL_DataFactoryTst.createCampaignMember(50,false,camps[0].id,leads[0].id,contacts[0].id);
            i=0;
            for(CampaignMember c : campMembers){
                c.contactId = contacts[i].id;
                i++;
            }
            insert campMembers;
        }
    }
    
    @isTest
    static void test1(){
        
        String campaignId = [SELECT id from Campaign].id;
        
        List<String> campaignMembers = new List<String>();
        List <CampaignMember> cm = [SELECT id from CampaignMember];
        for(CampaignMember m : cm)
        	campaignMembers.add(m.id);
                
        CampaignMember  cm1 = [SELECT id,PromoCommercialCode__c from CampaignMember limit 1];
        Map<String,List<String>> allMembers = new Map<String,List<String>>();
        allMembers.put(campaignId, campaignMembers);            
        
        Test.startTest();
		HDT_BA_CommercialCode cc = new HDT_BA_CommercialCode(allMembers);     
        Id batchId = Database.executeBatch(cc,200);
        Test.stopTest();
        
        CampaignMember  cm2 = [SELECT id,PromoCommercialCode__c from CampaignMember limit 1];
        System.assertNotEquals(cm1.PromoCommercialCode__c,cm2.PromoCommercialCode__c,'CampaignMember field PromoCommercialCode__c not updated by the batch'); 
        
        List<CommercialCode__c> commercialCodes = [select id from CommercialCode__c];
    	System.assertEquals(100, commercialCodes.size(), 'The number of CommercialCodes in the system does not double the number of CampaignMembers');
    }
}