force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerMarking__c.field-meta.xml
<CustomField>
    <fullName>CustomerMarking__c</fullName>
    <description>Rappresenta una segmentazione del cliente</description>
    <label>Marcatura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerMarking</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <customValue>
        <fullName>Famiglie</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CustomerMarking.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAS Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Altro</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D1 - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>D2 - Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>D3 - Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>D4 - Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>D5 - Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D6 - Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>D7 - BP Doppio</fullName>
    </customValue>
    <customValue>
        <fullName>Persona fisica</fullName>
    </customValue>
    <description>Rappresenta una segmentazione del cliente</description>
    <masterLabel>Marcatura Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_HelperMethodsTst.cls
/**
 * @author Valere (valere@noeli-it.net)
 * @date 23/09/2021
 * @description HDT_UTL_HelperMethods Test Class
 * @history valere - 23/09/2021– Created Class
 */
@isTest
private class HDT_UTL_HelperMethodsTst {
    private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
    @testSetup 
    static void setup() {
        User admin = HDT_UTL_DataFactoryTst.createInternalUser( HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME), false);
        admin.UserRoleId = HDT_UTL_DataFactoryTst.getUserRoleId(constants.USERROLE_DEVELOPERNAME_BACKOFFICE);
        insert admin;
        List<PermissionSetAssignment> permissionSetAssignments=new List<PermissionSetAssignment>{HDT_UTL_DataFactoryTst.assignPermissionSet(admin, constants.PERMISSIONSET_HDT_SUPER_USER_CPQ, false)};
		insert permissionSetAssignments;

        System.runAs(admin) {
            List<Account> accountList= HDT_UTL_DataFactoryTst.createAccountResidenziale(1,true,'HERA COMM','Persona fisica','Famiglie');
            List<Contact> contacts = HDT_UTL_DataFactoryTst.createContact(1, true, accountList[0].Id);
            HDT_UTL_DataFactoryTst.createCommunityUser(contacts[0], HDT_UTL_DataFactoryTst.getProfileId(constants.HERA_DOOR2DOOR_PARTNER_NAME), true);
        }

    }
    
    @isTest
     static void testGetObjAttrList() {

        List<Account> accountList=[SELECT id,CompanyOwner__c,CustomerMarking__c,Category__C
                                   FROM Account];
        HDT_UTL_HelperMethods help= new HDT_UTL_HelperMethods();
        List<String> fields = help.getObjAttrList(accountList[0]);

        System.assertEquals(3, fields.size(),'returns 3 because the account only has 3 fields different from id and attributes');

        System.assertNotEquals(1, fields.size(),' because the account has more than one field different from id and attributes');

    }

    @isTest
    static void testCheckCommunityLogin() {

     User user=[SELECT id FROM User Limit 1];

     system.runAs(user){
        HDT_UTL_HelperMethods help= new HDT_UTL_HelperMethods();
        Boolean check = help.checkCommunityLogin();

        System.assertEquals(true, check,'returns true because the current user is community');

        System.assertNotEquals(false, check,' because the current user is not crm');
     }     
   }


   @isTest
    static void testIsSuperUser() {

        List<User> userTest = [SELECT Id, Email, IsActive FROM User WHERE email = 'commuser@test.com'];

        System.runAs(userTest[0]) {
            HDT_UTL_HelperMethods help= new HDT_UTL_HelperMethods();
            Boolean check = help.isSuperUser();
            System.assertEquals(false, check,'because there is no PermissionSetAssignment that has this user id and HDT_SuperUserCPQ permissions');
            System.assertNotEquals(true, check,'because the returned PermissionSetAssignment list is empty ');
        }
   }



}