force-app/main/default/objects/Account/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <description>Corrisponde al BPKind SAP</description>
    <label>Codice Categoria Cliente</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ContractSalesCompany__c.field-meta.xml
<CustomField>
    <fullName>ContractSalesCompany__c</fullName>
    <description>Società di lettura del contratto</description>
    <label>Società Di Vendita Del Contratto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CommercialId__c.field-meta.xml
<CustomField>
    <fullName>CommercialId__c</fullName>
    <description>Id Commerciale</description>
    <label>Venduto Da</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Ordine di riferimento)</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesCompany__c.field-meta.xml
<CustomField>
    <fullName>SalesCompany__c</fullName>
    <label>Società di vendita</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hera Comm Marche</fullName>
            </value>
            <value>
                <fullName>Acegas Aps Service</fullName>
            </value>
            <value>
                <fullName>Hera Comm NordEst</fullName>
            </value>
            <value>
                <fullName>Hera Comm S.p.A.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/CommercialId__c.field-meta.xml
<CustomField>
    <fullName>CommercialId__c</fullName>
    <label>Venduto Da</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/fields/SalesCompany__c.field-meta.xml
<CustomField>
    <fullName>SalesCompany__c</fullName>
    <description>Società di vendita</description>
    <label>Società di vendita</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_SalesCompany.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hera Comm Marche</fullName>
    </customValue>
    <customValue>
        <fullName>Acegas Aps Service</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Comm NordEst</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Comm S.p.A.</fullName>
    </customValue>
    <customValue>
        <fullName>EstEnergy S.p.A.</fullName>
    </customValue>
    <customValue>
        <fullName>Marche Multiservizi S.p.A.</fullName>
    </customValue>
    <masterLabel>Societa di vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_SIE14Tst.cls
@isTest
public with sharing class HDT_UTL_SIE14Tst {
    
    static void createOrder(Contract c){
        Order o = HDT_UTL_DataFactoryTst.createOrder(1, false, c.AccountId, 'Bozza')[0];
        o.SalesCompany__c=c.contractSalesCompany__c;
        insert o;
        c.SBQQ__Order__c=o.Id;
        insert c;
    }

    static void createOrderAndSale(Contract c){
            Order o = HDT_UTL_DataFactoryTst.createOrder(1, false, c.AccountId, 'Bozza')[0];
            o.SalesCompany__c=c.contractSalesCompany__c;
            Sale__c s =HDT_UTL_DataFactoryTst.createSale(1, false, c.AccountId, 'Bozza')[0];
            s.CommercialId__c='AGSMECON1234';
            insert s;
            o.Sale__c=s.Id;
            insert o;
            c.SBQQ__Order__c=o.Id;
            insert c;
    }

    @TestSetup
    static void makeData(){
        List<Account> accounts= HDT_UTL_DataFactoryTst.createAccountResidenziale(3, true, 'HERA COMM', 'D1 - Persona fisica', 'Enti');

        Account acc1 = accounts.get(0);
        createOrder(new Contract(AccountId=acc1.Id, ContractSalesCompany__c='Hera Comm Marche'));
        createOrder(new Contract(AccountId=acc1.Id, ContractSalesCompany__c='Hera Comm Marche'));
        createOrder(new Contract(AccountId=acc1.Id, ContractSalesCompany__c='Hera Comm S.p.A.'));

        Account acc2 = accounts.get(1);
        acc2.CategoryCode__c = 'Z006';
        update acc2;

        createOrderAndSale(new Contract(AccountId=acc2.Id, ContractSalesCompany__c='Hera Comm S.p.A.'));
        createOrderAndSale(new Contract(AccountId=acc2.Id, ContractSalesCompany__c='Hera Comm S.p.A.'));
        createOrderAndSale(new Contract(AccountId=acc2.Id, ContractSalesCompany__c='EstEnergy S.p.A.'));
        
        Account acc3 = accounts.get(2);
        createOrder(new Contract(AccountId=acc3.Id, ContractSalesCompany__c='Acegas Aps Service'));
        createOrder(new Contract(AccountId=acc3.Id, ContractSalesCompany__c='Acegas Aps Service'));
        createOrder(new Contract(AccountId=acc3.Id, ContractSalesCompany__c='Hera Comm Marche'));
    }

    @isTest
    static void testSie14WithSale() {
        
        List<Contract> contracts =  [SELECT Id, AccountId, SBQQ__Order__c, SBQQ__Order__r.CommercialId__c FROM Contract where ContractSalesCompany__c='EstEnergy S.p.A.'];
        update new Account(Id=contracts[0].AccountId, CategoryCode__c='');
        Test.startTest();
        HDT_SRV_SIE14 testSie14 = new HDT_SRV_SIE14();
        testSie14.initSIE(new Map<Id,Contract>(contracts).keySet());
        Test.stopTest();
    }


    @isTest
    static void testSie14() {
        
        List<Contract> contracts =  [SELECT Id, AccountId FROM Contract];
        
        system.debug('allContracts -> ' + contracts);

        Test.startTest();
        HDT_SRV_SIE14 testSie14 = new HDT_SRV_SIE14();
        testSie14.initSIE(new Map<Id,Contract>(contracts).keySet());
        Test.stopTest();
    }
    /*
    private static boolean doLogicAndSimplifyExpr(String expression, String operator, SObject obj){
        List<String> indexes = new List<String>();
        for(String s : expression.split(operator)){
            indexes.add(s.trim());
        }
        switch on operator {
            when  'AND' {
                checkLogicAndGate(indexes, obj);
            }
            when 'OR' {
                
            }
        }
    }*/
    
    /*private static boolean checkLogicAndGate(SObject obj, List<String> indexes){//Logica AND
        //l'oggetto contiene una lista di condizioni. Se la lista è vuota O se tutte sono vere, torna true.
        if(indexes?.size() > 0){
            if(!this.conditions?.size()>0)   return false;
            for(String booleanIndex : indexes){
                if(booleanIndex=='true') return true;
                if(booleanIndex=='false') return false;
                Integer index = Integer.valueOf(booleanIndex);
                if(!this.conditions?.size()>booleanIndex) return false;
                HDT_WRP_SIECondition condition = this.conditions.get(booleanIndex);
                String actualValue=utlSbj.dinamicFieldValue(condition.fieldName, obj);
                if(!condition.checkCondition(actualValue))   return false;//Alla prima espressione falsa, il processo si blocca negativamente.
            }
        }
        return true;//Se è tutto vero o la lista è vuota, torna true.
    }*/
/*
    private static boolean checkLogicAndGate(SObject obj, List<String> indexes){//Logica AND
        //l'oggetto contiene una lista di condizioni. Se la lista è vuota O se tutte sono vere, torna true.
        if(indexes?.size() > 0){
            if(!this.conditions?.size()>0)   return false;
            for(String booleanIndex : indexes){
                if(booleanIndex=='true') return true;
                if(booleanIndex=='false') return false;
                Integer index = Integer.valueOf(booleanIndex);
                if(!this.conditions?.size()>booleanIndex) return false;
                HDT_WRP_SIECondition condition = this.conditions.get(booleanIndex);
                String actualValue=utlSbj.dinamicFieldValue(condition.fieldName, obj);
                if(!condition.checkCondition(actualValue))   return false;//Alla prima espressione falsa, il processo si blocca negativamente.
            }
        }
        return true;//Se è tutto vero o la lista è vuota, torna true.
    }*/
    
}