force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ContactReason__c.field-meta.xml
<CustomField>
    <fullName>ContactReason__c</fullName>
    <label>Motivo di Contatto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_ContactReason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InterestArea__c.field-meta.xml
<CustomField>
    <fullName>InterestArea__c</fullName>
    <label>Area di Interesse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_InterestArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <label>Prodotto di interesse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_InterestProduct</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campagna CRM</fullName>
            </value>
            <value>
                <fullName>Campagna Outbound</fullName>
            </value>
            <value>
                <fullName>Campagna Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Campagna Contenitore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Canale verso il quale verrà erogata la campagna</description>
    <label>Canale</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefonico Inbound</fullName>
            </value>
            <value>
                <fullName>Sportello</fullName>
            </value>
            <value>
                <fullName>SOL</fullName>
            </value>
            <value>
                <fullName>Telefonico Outbound</fullName>
            </value>
            <value>
                <fullName>Door to Door</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Push</fullName>
            </value>
            <value>
                <fullName>Cartaceo</fullName>
            </value>
            <value>
                <fullName>Bolletta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agenzia Teleseller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMemberLeadAssigment__c/CampaignMemberLeadAssigment__c.object-meta.xml
<CustomObject>
    <label>Assegnazione Campaign Member (Lead)</label>
    <nameField>
        <label>Assegnazione Campaign Member su base Lea</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assegnazioni Campaign Member (Lead)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignMemberLeadAssigment__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l’oggetto Account</description>
    <label>Agenzia</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assegnazioni_Campaign_Member_su_base_Lea</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMemberLeadAssigment__c/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <label>Prodotto di interesse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hera Bebè Dual</fullName>
            </value>
            <value>
                <fullName>Hera Bebè Gas</fullName>
            </value>
            <value>
                <fullName>Hera Bebè Luce</fullName>
            </value>
            <value>
                <fullName>Hera Caldaia</fullName>
            </value>
            <value>
                <fullName>Hera Caldaia Business</fullName>
            </value>
            <value>
                <fullName>Hera Caldaia Sicura</fullName>
            </value>
            <value>
                <fullName>Hera Caldaia Sicura Business</fullName>
            </value>
            <value>
                <fullName>Hera Clima</fullName>
            </value>
            <value>
                <fullName>Hera Clima Business</fullName>
            </value>
            <value>
                <fullName>Hera Contawatt</fullName>
            </value>
            <value>
                <fullName>Hera Contawatt Lavoro</fullName>
            </value>
            <value>
                <fullName>Hera EtàPiù Dual</fullName>
            </value>
            <value>
                <fullName>Hera EtàPiù Gas	Hera</fullName>
            </value>
            <value>
                <fullName>Hera EtàPiù Luce</fullName>
            </value>
            <value>
                <fullName>Hera Fotovoltaico</fullName>
            </value>
            <value>
                <fullName>Hera Fotovoltaico Business</fullName>
            </value>
            <value>
                <fullName>Hera Impronta Zero Dual</fullName>
            </value>
            <value>
                <fullName>Hera Impronta Zero Gas</fullName>
            </value>
            <value>
                <fullName>Hera Impronta Zero Luce</fullName>
            </value>
            <value>
                <fullName>Hera Impronta Zero Lavoro Dual</fullName>
            </value>
            <value>
                <fullName>Hera Impronta Zero Lavoro Gas</fullName>
            </value>
            <value>
                <fullName>Hera Impronta Zero Lavoro Luce</fullName>
            </value>
            <value>
                <fullName>Hera Led</fullName>
            </value>
            <value>
                <fullName>Hera Led Business</fullName>
            </value>
            <value>
                <fullName>Hera No Problem</fullName>
            </value>
            <value>
                <fullName>Hera No Problem Lavoro</fullName>
            </value>
            <value>
                <fullName>Hera Placet Fissa Gas</fullName>
            </value>
            <value>
                <fullName>Hera Placet Fissa Luce</fullName>
            </value>
            <value>
                <fullName>Hera Placet Fissa Lavoro Gas</fullName>
            </value>
            <value>
                <fullName>Hera Placet Fissa Lavoro Luce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMemberLeadAssigment__c/fields/SourceAgency__c.field-meta.xml
<CustomField>
    <fullName>SourceAgency__c</fullName>
    <label>Agenzia Fonte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Covisian</fullName>
            </value>
            <value>
                <fullName>Koinè Bologna Srl</fullName>
            </value>
            <value>
                <fullName>Koinè Srl</fullName>
            </value>
            <value>
                <fullName>Linetech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Società Silos</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <label>Prodotto di interesse</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ContactReason__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_InterestProduct</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SourceAgency__c.field-meta.xml
<CustomField>
    <fullName>SourceAgency__c</fullName>
    <label>Agenzia Fonte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Covisian</fullName>
            </value>
            <value>
                <fullName>Koinè Bologna Srl</fullName>
            </value>
            <value>
                <fullName>Koinè Srl</fullName>
            </value>
            <value>
                <fullName>Linetech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CampaignSource__c.field-meta.xml
<CustomField>
    <fullName>CampaignSource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo tecnico popolato dall’integrazione con Biz in cui viene inserito l’ID della Campagna Mkt cloud che ha portato il Lead ha compilare il form-web</description>
    <label>Campaign Source</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Società Silos</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ContactReason__c.field-meta.xml
<CustomField>
    <fullName>ContactReason__c</fullName>
    <label>Motivo Di Contatto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/InterestArea__c.field-meta.xml
<CustomField>
    <fullName>InterestArea__c</fullName>
    <description>Gli interessi manifestati dal Lead</description>
    <label>Interessi Aggiuntivi</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>InterestProduct__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_InterestArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <label>Prodotto di interesse</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ContactReason__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_InterestProduct</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SourceAgency__c.field-meta.xml
<CustomField>
    <fullName>SourceAgency__c</fullName>
    <label>Agenzia Fonte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Covisian</fullName>
            </value>
            <value>
                <fullName>Koinè Bologna Srl</fullName>
            </value>
            <value>
                <fullName>Koinè Srl</fullName>
            </value>
            <value>
                <fullName>Linetech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HC</fullName>
    </customValue>
    <customValue>
        <fullName>HCM</fullName>
    </customValue>
    <customValue>
        <fullName>EENE</fullName>
        <label>NEWCO</label>
    </customValue>
    <customValue>
        <fullName>HSPA</fullName>
    </customValue>
    <customValue>
        <fullName>EB</fullName>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HC+HCM+EENE</fullName>
    </customValue>
    <description>Identifica la società di appartenenza</description>
    <masterLabel>Company</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_ContactReason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Gestione contratti</fullName>
    </customValue>
    <customValue>
        <fullName>Info commerciali</fullName>
        <default>true</default>
        <label>Info commerciali</label>
    </customValue>
    <customValue>
        <fullName>Bolletta e pagamenti</fullName>
    </customValue>
    <customValue>
        <fullName>Segnalazioni ambientali</fullName>
    </customValue>
    <customValue>
        <fullName>Altro</fullName>
    </customValue>
    <masterLabel>Motivo di Contatto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_InterestArea.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Digitale</fullName>
    </customValue>
    <customValue>
        <fullName>HVAC</fullName>
    </customValue>
    <customValue>
        <fullName>Assicurazioni</fullName>
    </customValue>
    <customValue>
        <fullName>E-mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Offerta EE</fullName>
    </customValue>
    <customValue>
        <fullName>Offerta GAS</fullName>
    </customValue>
    <customValue>
        <fullName>Offerta Dual</fullName>
    </customValue>
    <masterLabel>Aree Interessi</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_InterestProduct.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hera Bebè Dual</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Bebè Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Bebè Luce</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Caldaia</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Caldaia Business</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Caldaia Sicura</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Caldaia Sicura Business</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Clima</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Clima Business</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Contawatt</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Contawatt Lavoro</fullName>
    </customValue>
    <customValue>
        <fullName>Hera E-Bike Business</fullName>
    </customValue>
    <customValue>
        <fullName>Hera EtàPiù Dual</fullName>
    </customValue>
    <customValue>
        <fullName>Hera EtàPiù Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Hera EtàPiù Luce</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Fotovoltaico</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Fotovoltaico Business</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Fotovoltaico Kit fai da te</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Impronta Zero Dual</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Impronta Zero Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Impronta Zero Luce</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Impronta Zero Lavoro Dual</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Impronta Zero Lavoro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Impronta Zero Lavoro Luce</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Led</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Led Business</fullName>
    </customValue>
    <customValue>
        <fullName>Hera No Problem</fullName>
    </customValue>
    <customValue>
        <fullName>Hera No Problem Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Hera No Problem Lavoro</fullName>
    </customValue>
    <customValue>
        <fullName>Hera Placet Fissa Gas</fullName>
    </customValue>
    <masterLabel>Prodotti di Interesse</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SalesChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>HC Point</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie SME</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Punti Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
        <isActive>false</isActive>
        <label>Consip</label>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <isActive>false</isActive>
        <label>Reseller</label>
    </customValue>
    <description>Canale vendita associato all&apos;utente</description>
    <masterLabel>Canale Vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_RecallMeCreateFormTst.cls
/*
 * @author Laureta Demishaj (laureta.demishaj@dunegroup.it)
 * @date 29/09/2021
 * @description HDT_LC_RecallMeCreateForm for Test Classes
 * @history Laureta Demishaj – 29/09/2021 – Created class
*/
@isTest
public with sharing class HDT_LC_RecallMeCreateFormTst {

 private static HDT_UTL_Constants constants = new HDT_UTL_Constants();

    @TestSetup
    static void myData(){
        List<Account> accList       = HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].id);
        List<Campaign> campaignList = HDT_UTL_DataFactoryTst.createCampaign(1, false);
        campaignList[0].Category__c = 'Campagna Outbound';
        campaignList[0].Channel__c  = 'Bolletta'; 
        insert campaignList;
        List<Lead> leadList = HDT_UTL_DataFactoryTst.createLead(1, false);
        leadList[0].CampaignSource__c  = campaignList[0].Id;
        leadList[0].SourceAgency__c    = 'Linetech';
        leadList[0].InterestProduct__c = 'Hera Bebè Gas';
        leadList[0].InterestArea__c    = 'Green';
        leadList[0].ContactReason__c   = 'Info commerciali';
        leadList[0].MobilePhone        = '0123456789';
        insert leadList;

        HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].Id);
    }
    @isTest
    public static void createCampaignMemberFromLeadNegativeTst(){
        List<Lead> ld      = [SELECT Id, SourceAgency__c, InterestProduct__c, MobilePhone FROM Lead];
        List<Campaign> cmp = [SELECT Id FROM Campaign];
        List<Account> acc  = [SELECT Id FROM Account];
        List<Contact> con = [SELECT Id FROM Contact];
        HDT_UTL_DataFactoryTst.createCampaignMember(true, cmp[0].Id, ld, con);
        try{ 
        List<CampaignMemberLeadAssigment__c> camMemLeadAss = new List<CampaignMemberLeadAssigment__c>();
        CampaignMemberLeadAssigment__c cmlA = new CampaignMemberLeadAssigment__c();
        cmlA.Name               = 'prova';
        cmlA.Agency__c          = acc[0].Id;
        cmlA.InterestProduct__c = ld[0].InterestProduct__c;
        cmlA.SourceAgency__c    = ld[0].SourceAgency__c;
        insert cmlA;
        camMemLeadAss.add(cmlA);
        Test.startTest();
        HDT_LC_RecallMeCreateForm.createCampaignMemberFromLead(ld[0].Id, ld[0].SourceAgency__c, ld[0].InterestProduct__c, cmp[0].Id, ld[0].MobilePhone);
        Test.stopTest();
        } catch(Exception e) {
            System.assertEquals('Script-thrown exception', e.getMessage(), 'The exception throws an error message in case the given lead has a campaign member');
            System.assertNotEquals('', e.getMessage(), 'An exception is expected');
        }

    }
    @isTest
    public static void createCampaignMemberFromLeadNullTst(){
        List<Lead> ld = [SELECT Id, SourceAgency__c, InterestProduct__c, MobilePhone FROM Lead];
        List<Campaign> cmp = [SELECT Id FROM Campaign];
        List<Contact> con = [SELECT Id FROM Contact];
        HDT_UTL_DataFactoryTst.createCampaignMember(true, cmp[0].Id, ld, con);
        try{ 
        
        Test.startTest();
        Id response = HDT_LC_RecallMeCreateForm.createCampaignMemberFromLead(ld[0].Id, ld[0].SourceAgency__c, ld[0].InterestProduct__c, cmp[0].Id, ld[0].MobilePhone);
        System.assertEquals(null, response, 'When the list of CampaignMemberLeadAssigment__c is empty the method returns null');
        Test.stopTest();
        } catch(Exception e) {
            System.assertEquals('Script-thrown exception', e.getMessage(), 'The exception throws an error message in case the given lead has a campaign member');
            System.assertNotEquals('', e.getMessage(), 'An exception is expected');
        }
    }
    @isTest
    public static void createCampaignMemberFromLeadPositivetiveTst() {
        List<Lead> ld      = [SELECT Id, SourceAgency__c, InterestProduct__c, MobilePhone FROM Lead];
        List<Campaign> cmp = [SELECT Id FROM Campaign];
        List<Account> acc  = [SELECT Id FROM Account];
        try{ 
        List<CampaignMemberLeadAssigment__c> camMemLeadAss = new List<CampaignMemberLeadAssigment__c>();
        CampaignMemberLeadAssigment__c cmlA = new CampaignMemberLeadAssigment__c();
        cmlA.Name               = 'prova';
        cmlA .Agency__c         = acc[0].Id;
        cmlA.InterestProduct__c = ld[0].InterestProduct__c;
        cmlA.SourceAgency__c    = ld[0].SourceAgency__c;
        insert cmlA;
        camMemLeadAss.add(cmlA);
        Test.startTest();
        Id response = HDT_LC_RecallMeCreateForm.createCampaignMemberFromLead(ld[0].Id, ld[0].SourceAgency__c, ld[0].InterestProduct__c, cmp[0].Id, ld[0].MobilePhone);
        List<CampaignMember> campaignMemmberResult = [SELECT Id FROM CampaignMember WHERE LeadId = :ld[0].Id LIMIT 1];       
        System.assertEquals(campaignMemmberResult[0].Id, response, 'The method creates a campaign member from a Lead');
        System.assertNotEquals(null, response, 'The method is expected to create a campaign member from a Lead');
        Test.stopTest();
        } catch(Exception e) {
            System.assertEquals('Script-thrown exception', e.getMessage(), 'The exception throws an error message');
            System.assertNotEquals('', e.getMessage(), 'An exception is expected');
        }
    }
    //** [START MOD 21/10/2021] @Author:Cesare Bagnolini WR (cesare.bagnolini@webresults.it) @Description: Added Test Methods
    @isTest static void testCreateCampaignMemberFromContact(){
        String acc = [Select id FROM Account][0].id;
        String con = [Select id FROM Contact][0].id;
        String cam = [Select id FROM Campaign][0].id;
        
        new List<CampaignMemberLeadAssigment__c>();
        CampaignMemberLeadAssigment__c cmlA = new CampaignMemberLeadAssigment__c();
        cmlA.Name               = 'prova';
        cmlA .Agency__c         =  acc;
        cmlA.InterestProduct__c = 'Hera Bebè Gas';
        cmlA.SourceAgency__c    = 'Linetech';
        insert cmlA;
        
        Test.startTest();
        
        String result = HDT_LC_RecallMeCreateForm.createCampaignMemberFromContact(con, 'Linetech', 'Hera Bebè Gas', cam, '3333453344');
        
        Test.stopTest();
        
        String member = [Select id FROM CampaignMember][0].id;
        
        System.assertEquals(member, result, 'CreateCampaignMemberFromContact did not work correctly');
        System.assertNotEquals(null, result, 'CreateCampaignMemberFromContact did not work correctly');        
    }

    @isTest static void testGetActivePicklistValues(){

        Test.startTest();
        
        List<String> result = HDT_LC_RecallMeCreateForm.getActivePicklistValues('Contact','Company__c');
        
        Test.stopTest();
        
        System.assertEquals(10, result.size(), 'GetActivePicklistValues did not work correctly');
        System.assertNotEquals(null, result, 'GetActivePicklistValues did not work correctly');        
    }
    //** [END MOD 21/10/2021] @Author:Cesare Bagnolini WR (cesare.bagnolini@webresults.it) @Description: Added Test Methods
}