force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>categoria del cliente</description>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerMarking__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita Iva</description>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_TRH_ContactTst.cls
/**
* @author Lucas da Silva Fernandes (lucas.dasilva@engdb.com.br)
* @date 17/09/2021
* @description HDT_TRH_Contact Test Class
* @history Lucas da Silva Fernandes – 17/09/2021 – Created Class
*/
@isTest
public with sharing class HDT_TRH_ContactTst {
    
    private static HDT_UTL_Constants constants = new HDT_UTL_Constants();
    
    @TestSetup
    static void setup(){
        
        Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME);
        
        User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);
        
        internalUser.UserPermissionsMarketingUser=true;
        
        insert internalUser;
        
        System.runAs(internalUser) {
            
            List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(1, false, 'HERA COMM', 'Azienda', 'Aziende SME');
            accList[0].VATNumber__c='13288870150';
            accList[0].FiscalCode__c='KNMKST92D20Z100D';
            insert accList;
            List<Contact> contList=HDT_UTL_DataFactoryTst.createContact(1, false, accList[0].Id);
            contList[0].VATNumber__c='13288870150';
            contList[0].FiscalCode__c='KNMKST92D20Z100D';
            insert contList;
        }
    }
    
    @isTest
    public static void testInsert() {
        
        User u=[SELECT Id FROM User WHERE Alias='crmuser' LIMIT 1];
        
        System.runAs(u){
            
            Test.startTest();
            
            Account acc = [SELECT Id FROM Account WHERE Category__c = 'Aziende SME'];
            List<Contact> ct = HDT_UTL_DataFactoryTst.createContact(1, false, acc.Id);
            ct[0].FirstName='Princess';
            ct[0].LastName='Toadstool';
            insert ct;
            
            List<Contact> ctList = [SELECT Id FROM Contact WHERE FirstName = 'Princess'];
            
            Test.stopTest();
            
            System.assertEquals(false, ctList.isEmpty(), 'Contact created.');
            System.assertNotEquals(true, ctList.isEmpty(), 'Contact creation failed.');
        }
    }
    
    @isTest
    public static void testUpdate() {
        
        User u=[SELECT Id FROM User WHERE Alias='crmuser' LIMIT 1];
        
        System.runAs(u){
            
            Test.startTest();
            
            List<Contact> ctList = [SELECT Id, FirstName, LastName FROM Contact WHERE CompanyOwner__c = 'HERA COMM'];
            ctList[0].FirstName = 'Joe';
            ctList[0].LastName = 'Frazier';
            update ctList;
            
            List<Contact> contacts = [SELECT Id FROM Contact WHERE FirstName = 'Joe'];
            
            Test.stopTest();
            
            System.assertEquals(false, contacts.isEmpty(), 'Contact created.');
            System.assertNotEquals(true, contacts.isEmpty(), 'Contact creation failed.');
        }
    }
}