force-app/main/default/objects/Account/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <formula>IF(CONTAINS(Code__c, &apos;13D&apos;)&amp;&amp; (RecordType.DeveloperName==&apos;HDT_RT_Distributore&apos;),
							&apos;Ele&apos;, 
							        IF(CONTAINS(Code__c, &apos;10D&apos;)&amp;&amp; (RecordType.DeveloperName==&apos;HDT_RT_Distributore&apos;),
							        &apos;Gas&apos;,
											         &apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizi</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/HDT_RT_Residenziale.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Residenziale</fullName>
    <active>true</active>
    <label>Residenziale</label>
</RecordType>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/HDT_AfterthoughtDays__mdt.object-meta.xml
<CustomObject>
    <description>Mdt che contiene la matrice per il calcolo dei giorni di ripensamento</description>
    <label>Gironi Di Ripensamento</label>
    <pluralLabel>HDT_AfterthoughtDays</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Account Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/AfterthoughtDays__c.field-meta.xml
<CustomField>
    <fullName>AfterthoughtDays__c</fullName>
    <label>Afterthought Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/DocumentSendingMode__c.field-meta.xml
<CustomField>
    <fullName>DocumentSendingMode__c</fullName>
    <label>Document Sending Mode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/SignatureMode__c.field-meta.xml
<CustomField>
    <fullName>SignatureMode__c</fullName>
    <label>Signature Mode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/HDT_FulfillmentDateMatrix__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contiene la matrice per il calcolo della data di Decorrenza</description>
    <label>Matrice Data Adempimento</label>
</CustomObject>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/ActivationDate__c.field-meta.xml
<CustomField>
    <fullName>ActivationDate__c</fullName>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/FulfillmentDateFrom__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentDateFrom__c</fullName>
    <label>Fulfillment Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/FulfillmentDateTo__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentDateTo__c</fullName>
    <label>Fulfillment Date To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/OriginMarket__c.field-meta.xml
<CustomField>
    <fullName>OriginMarket__c</fullName>
    <label>Origin Market</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Process Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <label>Supply Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_FulfillmentDateMatrix__c/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <label>Voltage Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale di Vendita</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <description>campo utilizzato per salvare il servizio presente in siebel per le RDS migrate</description>
    <label>Servizio</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerCategory__c.field-meta.xml
<CustomField>
    <fullName>CustomerCategory__c</fullName>
    <label>Categoria Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DocSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>DocSendingMethod__c</fullName>
    <label>Modalita Invio Doc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Posta</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Stampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Mercato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Libero</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>FUI</fullName>
            </value>
            <value>
                <fullName>Regolamentato</fullName>
            </value>
            <value>
                <fullName>Salvaguardia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MarketOrigin__c.field-meta.xml
<CustomField>
    <fullName>MarketOrigin__c</fullName>
    <label>Mercato Provenienza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MaxAfterthoughtDate__c.field-meta.xml
<CustomField>
    <fullName>MaxAfterthoughtDate__c</fullName>
    <label>Data Massima Ripensamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/RecessNotice__c.field-meta.xml
<CustomField>
    <fullName>RecessNotice__c</fullName>
    <label>Mesi Preavviso recesso</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SignatureMethod__c.field-meta.xml
<CustomField>
    <fullName>SignatureMethod__c</fullName>
    <label>Metodo Firma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vocal Order</fullName>
            </value>
            <value>
                <fullName>OTP Remoto</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
            </value>
            <value>
                <fullName>OTP Coopresenza</fullName>
            </value>
            <value>
                <fullName>Contratto già firmato</fullName>
            </value>
            <value>
                <fullName>Accettato Digitalmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SignedDate__c.field-meta.xml
<CustomField>
    <fullName>SignedDate__c</fullName>
    <description>In caso di contratto esiste, la data in cui è stato firmato</description>
    <label>Data Firma</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <label>Tipo Fornitura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <label>Tensione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VoltageLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/WaiverRightAfterthought__c.field-meta.xml
<CustomField>
    <fullName>WaiverRightAfterthought__c</fullName>
    <label>Attivazione Anticipata</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/WizardCompletedDate__c.field-meta.xml
<CustomField>
    <fullName>WizardCompletedDate__c</fullName>
    <label>Data completamento wizard</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_Default.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Default</fullName>
    <active>true</active>
    <description>Record Tyope di defulat ordini Figli, utilizzato prima della selezione del processo</description>
    <label>Default</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_OrderDossier.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_OrderDossier</fullName>
    <active>true</active>
    <description>Record Type Ordine Padre</description>
    <label>Order Dossier</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_ScontiBonus.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_ScontiBonus</fullName>
    <active>true</active>
    <label>Aggiunta Sconti o Bonus VAS</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_Subentro.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Subentro</fullName>
    <active>true</active>
    <description>Record type per gli ordini di Subentro</description>
    <label>Subentro</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_SwitchIn.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_SwitchIn</fullName>
    <active>true</active>
    <description>Record type per gli ordini di SwitchIn</description>
    <label>SwitchIn</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VAS.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VAS</fullName>
    <active>true</active>
    <label>VAS</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_Voltura.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Voltura</fullName>
    <active>true</active>
    <description>Record Type per processo di Voltura</description>
    <label>Voltura</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MarketOrigin__c.field-meta.xml
<CustomField>
    <fullName>MarketOrigin__c</fullName>
    <label>Mercato di provenienza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <label>Tipo Fornitura</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CommoditySector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <description>Livello di tensione</description>
    <label>Tensione di Consegna</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VoltageLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Libero</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>FUI</fullName>
    </customValue>
    <customValue>
        <fullName>Regolamentato</fullName>
    </customValue>
    <customValue>
        <fullName>Salvaguardia</fullName>
    </customValue>
    <customValue>
        <fullName>STGM</fullName>
    </customValue>
    <masterLabel>Mercato</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SupplyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Non Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>A-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>B-Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>C-Aziende di pubblica utilita</fullName>
    </customValue>
    <customValue>
        <fullName>D-Altri usi</fullName>
    </customValue>
    <customValue>
        <fullName>Uso domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso diverso da domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Usi industriali che scaricano in pubblica fognatura</fullName>
    </customValue>
    <customValue>
        <fullName>Altri usi</fullName>
    </customValue>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <masterLabel>Tipo Fornitura</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_VoltageLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AAT</fullName>
    </customValue>
    <description>Livello Tensione</description>
    <masterLabel>Livello Tensione</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_SwtichInProcess.cls
/**
 * @author alessandro.picchiri@eng.it
 * @date 24/05/2021
 * @description  Classe per la gestione delle date nel processo switch in 
*/
public with sharing class HDT_UTL_SwtichInProcess {

    // Calcolo Data Max Ripensamento(MaxAfterthoughtDate__c)  // Solo per clienti residenziali
    public static Date getMaxAfterthoughtDate(Order order) {

        system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate - Channel__c: ' + order.Channel__c );
        system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate - Market__c: ' + order.Market__c  );
        system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate - AccountType__c: ' + order.CustomerCategory__c );
        system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate - SignatureMode__c: ' + order.SignatureMethod__c );
        system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate - DocumentSendingMode__c: ' + order.DocSendingMethod__c );
        system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate - SignedDate: ' + order.SignedDate__c );

        Date SignedDate = order.SignedDate__c;   
        Date MaxAfterthoughtDate = null;  
        List<HDT_AfterthoughtDays__mdt> AfterthoughtDays3 = [ // Giorni di ripensamento
                                                                SELECT AfterthoughtDays__c 
                                                                FROM HDT_AfterthoughtDays__mdt 
                                                                WHERE Channel__c =: order.Channel__c 
                                                                        AND Market__c =: order.Market__c
                                                                        AND AccountType__c =: order.CustomerCategory__c  
                                                                        AND SignatureMode__c =: order.SignatureMethod__c 
                                                                        AND DocumentSendingMode__c =: order.DocSendingMethod__c 
                                                            ];            
        if(SignedDate != null){
            system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate - AfterthoughtDays__c: ' + (Integer)AfterthoughtDays3[0].AfterthoughtDays__c );
            MaxAfterthoughtDate = SignedDate.addDays((Integer)AfterthoughtDays3[0].AfterthoughtDays__c);                      
        }   

    
        system.debug('HDT_UTL_SwtichInProcess - getMaxAfterthoughtDate: ' + MaxAfterthoughtDate);
        return MaxAfterthoughtDate;

    }


    public static Date getDateSentToSII(Order order) {

        Date SignedDate = order.SignedDate__c;   
        Date DateSentToSII = null;

        if(order.Account.RecordType.DeveloperName == 'HDT_RT_Residenziale'){

        

            if(SignedDate != null){ 
                if(order.WizardCompletedDate__c > getMaxAfterthoughtDate(order)){
                    DateSentToSII = order.WizardCompletedDate__c;
                }else{
                    DateSentToSII = getMaxAfterthoughtDate(order).addDays(1);
                }
            }else{ 
                DateSentToSII = order.WizardCompletedDate__c;            
            }

            if(DateSentToSII.day() < 10){
                DateSentToSII = DateSentToSII.addMonths(1).toStartofMonth();  
            }else{
                DateSentToSII = DateSentToSII.addMonths(2).toStartofMonth();  
            }
            
            // if (order.WaiverRightAfterthought__c == 'Si') { 
            //     DateSentToSII = order.WizardCompletedDate__c;
            // }
        
        }else{
            DateSentToSII = order.WizardCompletedDate__c;    
            /*
            La data invio richiesta al SII deve essere ricalcolata nel caso in cui il sistema riceva degli esiti di rilavorazione.  
            Alla rilavorazione, la data di invio richiesta deve assumere la data di rilavorazione della richiesta (la data di ultimo aggiornamento fase).  
            Tale ricalcolo potrà essere possibile fino all’esito di ammissibilità ok.  
            Da quel momento in poi il sistema non dovrà più ricalcolare la data invio richiesta al SII. 
            */          
        }

        system.debug('HDT_UTL_SwtichInProcess - getDateSentToSII: ' + DateSentToSII);
        return DateSentToSII;

    }

    // public static Date getActivatedDate(Order order) {
        
    //     Date DateSentToSII_tmp = getDateSentToSII(order);
    //     Date ActivatedDate_tmp = null;
    //     if(order.Account.RecordType.DeveloperName == 'HDT_RT_Residenziale'){
    //         if(DateSentToSII_tmp.day() <= 10){
    //             ActivatedDate_tmp = DateSentToSII_tmp.addMonths(1).toStartofMonth();  
    //         }else{
    //             ActivatedDate_tmp = DateSentToSII_tmp.addMonths(2).toStartofMonth();  
    //         }
    //     }
    //     else{
    //         if(DateSentToSII_tmp.day() <= 10 && order.RecessNotice__c  != null){
    //             ActivatedDate_tmp = DateSentToSII_tmp.addMonths(1).toStartofMonth();  // Aggiunto in HDT_QR_Order.getRecordById
    //         }
    //         if(DateSentToSII_tmp.day() > 10 && order.RecessNotice__c  != null){
    //             ActivatedDate_tmp = DateSentToSII_tmp.addMonths(2).toStartofMonth();  // Aggiunto in HDT_QR_Order.getRecordById
    //         }  
    //     }
    //     system.debug('HDT_UTL_SwtichInProcess - getActivatedDate: ' + ActivatedDate_tmp);
    //     return ActivatedDate_tmp; 
    // }


    public static Date getEffectiveDate(Order order) {
        
        Date EffectiveDate_tmp = null;
        Date DateDecorrenzaTmp = null;
        String processType = PROCESSTYPEBYRRECORDTYPEMAP.get(order.RecordType.DeveloperName);

        // Inizio Questa parte è da definire con Ravicini per il campo isReseller
        // Verificare con luca
        // if(order.isReseller == true && processType == 'Switch In'){
        //     processType = processTypeMap.get('isReseller');
        // }
        // Fine Questa parte è da definire con Ravicini per il campo isReseller

        system.debug('HDT_UTL_SwtichInProcess - getEffectiveDate - OriginMarket__c: ' + order.MarketOrigin__c );
        system.debug('HDT_UTL_SwtichInProcess - getEffectiveDate - Commodity__c: ' + order.ServicePoint__r.CommoditySector__c  );
        system.debug('HDT_UTL_SwtichInProcess - getEffectiveDate - VoltageLevel__c: ' + order.VoltageLevel__c);
        system.debug('HDT_UTL_SwtichInProcess - getEffectiveDate - SupplyType__c: ' + order.SupplyType__c );
        system.debug('HDT_UTL_SwtichInProcess - getEffectiveDate - DateSentToSII: ' + getDateSentToSII(order));

        if(order.Account.RecordType.DeveloperName == 'HDT_RT_Residenziale'){
            
            List<HDT_FulfillmentDateMatrix__c> AfterthoughtDays = [
                                                                    SELECT ActivationDate__c 
                                                                    FROM HDT_FulfillmentDateMatrix__c 
                                                                    WHERE OriginMarket__c =: order.MarketOrigin__c   
                                                                            AND Commodity__c =: order.ServicePoint__r.CommoditySector__c   
                                                                            AND VoltageLevel__c =: order.VoltageLevel__c 
                                                                            AND ProcessType__c = :processType
                                                                            AND SupplyType__c =: order.SupplyType__c 
                                                                            AND (FulfillmentDateFrom__c <=: getDateSentToSII(order) AND FulfillmentDateTo__c >=: getDateSentToSII(order))
                ];
            EffectiveDate_tmp = AfterthoughtDays[0].ActivationDate__c;
        }
        else{
            if(order.RecessNotice__c != null){
                List<HDT_FulfillmentDateMatrix__c> AfterthoughtDays2 = [
                SELECT ActivationDate__c 
                FROM HDT_FulfillmentDateMatrix__c 
                WHERE OriginMarket__c =: order.MarketOrigin__c 
                        AND Commodity__c =: order.ServicePoint__r.CommoditySector__c   
                        AND VoltageLevel__c =: order.VoltageLevel__c 
                        AND ProcessType__c = :processType 
                        AND SupplyType__c =: order.SupplyType__c 
                        AND (FulfillmentDateFrom__c <= :getDateSentToSII(order) AND FulfillmentDateTo__c >= :getDateSentToSII(order))
                ];

                EffectiveDate_tmp = AfterthoughtDays2[0].ActivationDate__c;
            }else{
                DateDecorrenzaTmp = getDateSentToSII(order).addMonths((Integer)order.RecessNotice__c);
                EffectiveDate_tmp = DateDecorrenzaTmp.addMonths(1).toStartofMonth();
            }
        }    

        

        system.debug('HDT_UTL_SwtichInProcess - getEffectiveDate: ' + EffectiveDate_tmp);
        return EffectiveDate_tmp;
    }


    // verifica con luca cambio offerta
    public static final Map<String,String> PROCESSTYPEBYRRECORDTYPEMAP = new Map<String,String>{  
        'HDT_RT_OrderDossier' => '',
        'HDT_RT_Subentro' => '',
        'HDT_RT_Default' => '',
        'HDT_RT_Voltura' => '',
        'HDT_RT_SwitchIn' => 'Switch In',
        'isReseller' => 'Switch In Reseller',
        'HDT_RT_ScontiBonus' => '',
        'HDT_RT_VAS' => ''
    };
    
}