force-app/main/default/objects/Account/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <formula>IF(CONTAINS(Code__c, &apos;13D&apos;)&amp;&amp; (RecordType.DeveloperName==&apos;HDT_RT_Distributore&apos;),
							&apos;Ele&apos;, 
							        IF(CONTAINS(Code__c, &apos;10D&apos;)&amp;&amp; (RecordType.DeveloperName==&apos;HDT_RT_Distributore&apos;),
							        &apos;Gas&apos;,
											         &apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizi</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributorPointCode__c/DistributorPointCode__c.object-meta.xml
<CustomObject>
    <description>L&apos;oggetto ha la funzione di memorizzare i codice o porzioni di codici dei punti assegnati a specifici distributori.</description>
    <label>Codice Punto Distributore</label>
    <nameField>
        <displayFormat>DPC-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Codici Punto Distributore</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributorPointCode__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <description>Indica la commodity per la quale il codice si applica</description>
    <label>Commodity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributorPointCode__c/fields/PointCode__c.field-meta.xml
<CustomField>
    <fullName>PointCode__c</fullName>
    <description>Indica il codice del punto o porzione di esso</description>
    <label>Codice punto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_DistributorPointCodeTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 15/09/2021
 * @description HDT_QR_DistributorPointCode Test Classes
 * @history Fabricio Petkevicius Nunes – 15/09/2021 – Created class
 */
@isTest
public with sharing class HDT_QR_DistributorPointCodeTst{
	private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
	private static HDT_QR_DistributorPointCode distPointCodeQr=new HDT_QR_DistributorPointCode();
	@TestSetup
	static void makeData(){
		Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME);
		User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);
		insert internalUser;

		System.runAs(internalUser){

			List<Account> accList=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
			List<DistributorPointCode__c> distPointCodes=HDT_UTL_DataFactoryTst.createDistributorPointCode(1, false, accList[0].Id);
			distPointCodes[0].PointCode__c='testPointCode';
			distPointCodes[0].Commodity__c='testCommodity';

			insert distPointCodes;
		}
	}

	@isTest
	public static void testGetDistributorPointCode(){

		User tUser=[SELECT Id
		            FROM User
		            WHERE Alias='crmuser'
		            LIMIT 1];

		System.runAs(tUser){

			test.startTest();

			List<DistributorPointCode__c> getDistPointCode=distPointCodeQr.getDistributorPointCode('testPointCode', 'testCommodity');

			test.stopTest();

			System.assertEquals(true, getDistPointCode[0].Id!=null, 'Distributor Code not found');
			System.assertNotEquals(false, getDistPointCode[0].Id!=null, 'value of parameter is not matching');
		}
	}
}