force-app/main/default/objects/Account/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <formula>IF(CONTAINS(Code__c, &apos;13D&apos;)&amp;&amp; (RecordType.DeveloperName==&apos;HDT_RT_Distributore&apos;),
							&apos;Ele&apos;, 
							        IF(CONTAINS(Code__c, &apos;10D&apos;)&amp;&amp; (RecordType.DeveloperName==&apos;HDT_RT_Distributore&apos;),
							        &apos;Gas&apos;,
											         &apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizi</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/HDT_RT_Residenziale.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_Residenziale</fullName>
    <active>true</active>
    <label>Residenziale</label>
</RecordType>

force-app/main/default/objects/FulfillmentDateMatrix__c/FulfillmentDateMatrix__c.object-meta.xml
<CustomObject>
    <description>Contiene la matrice per il calcolo della data di decorrenza</description>
    <label>Matrice Data Adempimento</label>
    <nameField>
        <label>Matrice Data Adempimento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrici Data Adempimento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FulfillmentDateMatrix__c/fields/ActivationDate__c.field-meta.xml
<CustomField>
    <fullName>ActivationDate__c</fullName>
    <label>Data Attivazione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FulfillmentDateMatrix__c/fields/FulfillmentDateFrom__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentDateFrom__c</fullName>
    <label>Data Adempimento da</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FulfillmentDateMatrix__c/fields/FulfillmentDateTo__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentDateTo__c</fullName>
    <label>Data Adempimento a</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FulfillmentDateMatrix__c/fields/OriginMarket__c.field-meta.xml
<CustomField>
    <fullName>OriginMarket__c</fullName>
    <label>Mercato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OriginMarket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FulfillmentDateMatrix__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Processo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cambio offerta</fullName>
            </value>
            <value>
                <fullName>Switch In</fullName>
            </value>
            <value>
                <fullName>Switch In Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FulfillmentDateMatrix__c/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <label>Tipo Fornitura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FulfillmentDateMatrix__c/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <label>Tensione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Voltage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/HDT_AfterthoughtDays__mdt.object-meta.xml
<CustomObject>
    <description>Mdt che contiene la matrice per il calcolo dei giorni di ripensamento</description>
    <label>Gironi Di Ripensamento</label>
    <pluralLabel>HDT_AfterthoughtDays</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Account Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/AfterthoughtDays__c.field-meta.xml
<CustomField>
    <fullName>AfterthoughtDays__c</fullName>
    <label>Afterthought Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/DocumentSendingMode__c.field-meta.xml
<CustomField>
    <fullName>DocumentSendingMode__c</fullName>
    <label>Document Sending Mode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_AfterthoughtDays__mdt/fields/SignatureMode__c.field-meta.xml
<CustomField>
    <fullName>SignatureMode__c</fullName>
    <label>Signature Mode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/AttributesCatalogDesc__c.field-meta.xml
<CustomField>
    <fullName>AttributesCatalogDesc__c</fullName>
    <label>Descrizione Catalogo Attributi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale di Vendita</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ClientCategoryFormula__c.field-meta.xml
<CustomField>
    <fullName>ClientCategoryFormula__c</fullName>
    <formula>TEXT(Account.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <description>campo utilizzato per salvare il servizio presente in siebel per le RDS migrate</description>
    <label>Servizio</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CommodityFormula__c.field-meta.xml
<CustomField>
    <fullName>CommodityFormula__c</fullName>
    <formula>TEXT(ServicePoint__r.CommoditySector__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerCategory__c.field-meta.xml
<CustomField>
    <fullName>CustomerCategory__c</fullName>
    <label>Categoria Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CategoryTypeClient</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DateSentToSII__c.field-meta.xml
<CustomField>
    <fullName>DateSentToSII__c</fullName>
    <label>Data Invio al SII</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>DocSendingMethod__c</fullName>
    <label>Modalita Invio Doc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Posta</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Stampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentalProcessType__c.field-meta.xml
<CustomField>
    <fullName>DocumentalProcessType__c</fullName>
    <formula>IF(ISPICKVAL(ProcessType__c,&apos;Subentro Gas&apos;),&apos;Subentro&apos;,
IF(ISPICKVAL(ProcessType__c,&apos; Subentro Ele&apos;),&apos;Subentro&apos;,TEXT(ProcessType__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo Processo Documentale</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Data decorrenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsActivationDeferred__c.field-meta.xml
<CustomField>
    <fullName>IsActivationDeferred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attivazione Posticipata</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsEarlyActivation__c.field-meta.xml
<CustomField>
    <fullName>IsEarlyActivation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attivazione Anticipata</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Mercato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Libero</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>FUI</fullName>
            </value>
            <value>
                <fullName>Regolamentato</fullName>
            </value>
            <value>
                <fullName>Salvaguardia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MarketOrigin__c.field-meta.xml
<CustomField>
    <fullName>MarketOrigin__c</fullName>
    <label>Mercato Provenienza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MaxAfterthoughtDate__c.field-meta.xml
<CustomField>
    <fullName>MaxAfterthoughtDate__c</fullName>
    <label>Data Massima Ripensamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/RecessNotice__c.field-meta.xml
<CustomField>
    <fullName>RecessNotice__c</fullName>
    <label>Mesi Preavviso recesso</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/SignatureMethod__c.field-meta.xml
<CustomField>
    <fullName>SignatureMethod__c</fullName>
    <label>Metodo Firma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vocal Order</fullName>
            </value>
            <value>
                <fullName>OTP Remoto</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
            </value>
            <value>
                <fullName>OTP Coopresenza</fullName>
            </value>
            <value>
                <fullName>Contratto già firmato</fullName>
            </value>
            <value>
                <fullName>Accettato Digitalmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SignedDate__c.field-meta.xml
<CustomField>
    <fullName>SignedDate__c</fullName>
    <description>In caso di contratto esiste, la data in cui è stato firmato</description>
    <label>Data Firma</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyType__c.field-meta.xml
<CustomField>
    <fullName>SupplyType__c</fullName>
    <label>Tipo Fornitura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SupplyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <label>Tensione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VoltageLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/WaiverRightAfterthought__c.field-meta.xml
<CustomField>
    <fullName>WaiverRightAfterthought__c</fullName>
    <label>Attivazione Anticipata</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/WizardCompletedDate__c.field-meta.xml
<CustomField>
    <fullName>WizardCompletedDate__c</fullName>
    <label>Data completamento wizard</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CategoryTypeClient.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accedi</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzia di confisca</fullName>
    </customValue>
    <customValue>
        <fullName>Applicazione della legge</fullName>
    </customValue>
    <customValue>
        <fullName>Assicuratore</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza a lungo termine</fullName>
    </customValue>
    <customValue>
        <fullName>Assistenza gestita</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>Attività bancaria</fullName>
    </customValue>
    <customValue>
        <fullName>Auto/Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda/Di passaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda wireline</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende SME</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende Soho</fullName>
    </customValue>
    <customValue>
        <fullName>Aziende TOP</fullName>
    </customValue>
    <customValue>
        <fullName>Banca centrale</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>BSU ESP</fullName>
    </customValue>
    <customValue>
        <fullName>Casalinghi</fullName>
    </customValue>
    <customValue>
        <fullName>Casa progettazione</fullName>
    </customValue>
    <customValue>
        <fullName>Centro convegni</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di assistenza</fullName>
    </customValue>
    <customValue>
        <fullName>Centro di formazione aziendale</fullName>
    </customValue>
    <customValue>
        <fullName>Centro formaz altri produttori</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Chain Food</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente azienda</fullName>
    </customValue>
    <customValue>
        <fullName>Clinica</fullName>
    </customValue>
    <customValue>
        <fullName>Famiglie</fullName>
    </customValue>
    <masterLabel>Categoria Tipo Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Libero</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>FUI</fullName>
    </customValue>
    <customValue>
        <fullName>Regolamentato</fullName>
    </customValue>
    <customValue>
        <fullName>Salvaguardia</fullName>
    </customValue>
    <customValue>
        <fullName>STGM</fullName>
    </customValue>
    <masterLabel>Mercato</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OriginMarket.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Libero</fullName>
    </customValue>
    <customValue>
        <fullName>Regolamentato</fullName>
    </customValue>
    <customValue>
        <fullName>Salvaguardia</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>FUI</fullName>
    </customValue>
    <customValue>
        <fullName>STGM</fullName>
    </customValue>
    <description>Libero
Regolamentato</description>
    <masterLabel>Mercato Provenienza</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SupplyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Non Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>A-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>B-Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>C-Aziende di pubblica utilita</fullName>
    </customValue>
    <customValue>
        <fullName>D-Altri usi</fullName>
    </customValue>
    <customValue>
        <fullName>Uso domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso diverso da domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Uso civile non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>Usi industriali che scaricano in pubblica fognatura</fullName>
    </customValue>
    <customValue>
        <fullName>Altri usi</fullName>
    </customValue>
    <description>Domestico
Non Domestico
A-Domestico
B-Condominio
C-Aziende di pubblica utilita
D-Altri usi</description>
    <masterLabel>Tipo Fornitura</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Voltage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
        <label>AT</label>
    </customValue>
    <description>Tensione</description>
    <masterLabel>Voltage</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_VoltageLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AAT</fullName>
    </customValue>
    <description>Livello Tensione</description>
    <masterLabel>Livello Tensione</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_ProcessDateManager.cls
public with sharing class HDT_UTL_ProcessDateManager {

	@AuraEnabled
	public static Boolean isAfterthoughtDaysZero(Order order){
		try {
			
			List<HDT_AfterthoughtDays__mdt> afterthoughtDays = [SELECT AfterthoughtDays__c FROM HDT_AfterthoughtDays__mdt WHERE 
			Channel__c =: order.Channel__c AND 
			Market__c =: order.Market__c AND 
			AccountType__c =: order.CustomerCategory__c AND 
			SignatureMode__c =: order.SignatureMethod__c AND 
			DocumentSendingMode__c =: order.DocSendingMethod__c
			WITH SECURITY_ENFORCED];

			return ( afterthoughtDays[0].AfterthoughtDays__c == 0 );

		} catch (Exception e) {
			return false;
		}
	}

    public static void calculateOrderProcessDate(List<Order> orderList){
		List<Order> nonDomOrderList = new List<Order>();
		List<Order> domOrderList = new List<Order>();
		for(Order order : orderList){
			if(order.Account.RecordType.DeveloperName == 'HDT_RT_Residenziale' || (order.RecessNotice__c == null || (order.RecessNotice__c != null && order.RecessNotice__c == 0))){
				domOrderList.add(order);
			}else {
				nonDomOrderList.add(order);
			}
		}
		if(!domOrderList.isEmpty()){
			setMaxAfterthoughtDate(orderList);
			setDateSentToSii(orderList);
			setEffectiveDate(orderList);
		}
        if(!nonDomOrderList.isEmpty()){
			handleBusinessDate(orderList);
		}
    }
    public static void setMaxAfterthoughtDate(List<Order> orderList) {
		if(!orderList.isEmpty()){
			Order order = orderList[0];
			Date signedDate = order.SignedDate__c;   
			Date maxAfterthoughtDate = null;
			Set<String> processToCalculate = new Set<String>{'SWITCH IN', 'CAMBIO OFFERTA'};
			
			// Giorni di ripensamento
			List<HDT_AfterthoughtDays__mdt> afterthoughtDays = [SELECT AfterthoughtDays__c FROM HDT_AfterthoughtDays__mdt WHERE 
				Channel__c =: order.Channel__c AND 
				Market__c =: order.Market__c AND 
				AccountType__c =: order.CustomerCategory__c AND 
				SignatureMode__c =: order.SignatureMethod__c AND 
				DocumentSendingMode__c =: order.DocSendingMethod__c
			WITH SECURITY_ENFORCED];

			if(afterthoughtDays.isEmpty() && signedDate != null){
				maxAfterthoughtDate = signedDate;                      
			}
			else if(signedDate != null){
				maxAfterthoughtDate = signedDate.addDays((Integer)afterthoughtDays[0].AfterthoughtDays__c);                              
			}
			if(maxAfterthoughtDate != null){
				for(Order singleOrder : orderList){
					if(processToCalculate.contains(singleOrder.DocumentalProcessType__c?.toUpperCase()))
					singleOrder.MaxAfterthoughtDate__c = maxAfterthoughtDate;
				}
			}
		}
    }

    public static void setDateSentToSii(List<Order> orderList) {
        if(!orderList.isEmpty()){
            for(Order order : orderList){
                Date signedDate = order.SignedDate__c;
                if (order.WizardCompletedDate__c==null) {
                    order.WizardCompletedDate__c = Date.today();
                }
    
                Date dateSentToSii= null;
                if(signedDate != null  && order.ProcessType__c != null &&  order.ProcessType__c.containsIgnoreCase('Switch In')){
                    //if(order.Account.RecordType.DeveloperName == 'HDT_RT_Residenziale'){
                        // DIRITTO DI RINUNCIA DI RIPENSAMENTO
                        if (order.WaiverRightAfterthought__c == 'Si') { 
                            dateSentToSii = Date.today();
                        }
                        else if(order.IsEarlyActivation__c) {
                            dateSentToSii = order.WizardCompletedDate__c;
                        }
                        else{
                            Date dataRipensamento = order.MaxAfterthoughtDate__c;
                            if(dataRipensamento != null && order.Account.RecordType.DeveloperName == 'HDT_RT_Residenziale' ){
								if(dataRipensamento > Date.Today()){
									dateSentToSii = dataRipensamento.addDays(1);
								}else if(dataRipensamento < Date.Today()){
									dateSentToSii = Date.today();
								}
								else {
									dateSentToSii = dataRipensamento;
								}
                            }else {
								dateSentToSii = Date.today();
							}
                        }            
                    //}
                }else {
                    continue;
                }
				if(dateSentToSii != null){
					order.DateSentToSII__c = dateSentToSii;
				}
            }
        }
    }
	public static void setEffectiveDateBusiness(List<Order> orderList){
		for(Order order : orderList){
			Date signDate = order.SignedDate__c;
			if(!order.IsActivationDeferred__c){
				if(order.DocumentalProcessType__c.equalsIgnoreCase('Switch In') && order.ClientCategoryFormula__c != 'Famiglie'){
					if (order.RecessNotice__c == null) {
						order.RecessNotice__c = 0;
					}
					Date dateDecorrenzaTmp = signDate.addMonths((Integer)order.RecessNotice__c);
					Date effectiveDateTmp = dateDecorrenzaTmp.addMonths(1).toStartofMonth();
					order.EffectiveDate__c = effectiveDateTmp;
				}
			}
		}
	}
	public static void setDateSentToSiiBusiness(List<Order> orderList){
		List<FulfillmentDateMatrix__c> dateMatrix = getFulfillmentDate(orderList);
		Date dateToFrom;
		for(Order order : orderList){
			//CAMBIO OFFERTA DATA FIRMA - SWITCH IN DATA INVIO SII
			if(order.DocumentalProcessType__c.equalsIgnoreCase('Switch In')){
				dateToFrom = order.EffectiveDate__c;
			}else if(order.EffectiveDate__c == null){
				continue;
			}else {
				continue;
			}
			if(!order.IsActivationDeferred__c){
				order.DateSentToSII__c = order.WizardCompletedDate__c != null? order.WizardCompletedDate__c:Date.today();
			}else if(dateToFrom != null){
				Boolean founded = false;
				for(FulfillmentDateMatrix__c singleRecord : dateMatrix){
						founded = false;
						if(order.CommodityFormula__c != null && 'Gas'.equalsIgnoreCase(order.CommodityFormula__c)){
							if(
								singleRecord.OriginMarket__c.equalsIgnoreCase(order.MarketOrigin__c) &&
								singleRecord.Commodity__c.equalsIgnoreCase(order.CommodityFormula__c) &&	
								singleRecord.ProcessType__c.equalsIgnoreCase(order.DocumentalProcessType__c) &&	
								singleRecord.SupplyType__c.equalsIgnoreCase(order.SupplyType__c) &&	
								singleRecord.ActivationDate__c == dateToFrom
							){
								founded = true;
							}else {
								founded = false; 
							}
						}
						else if(order.CommodityFormula__c != null && 'Energia Elettrica'.equalsIgnoreCase(order.CommodityFormula__c)){
							if(
								singleRecord.OriginMarket__c.equalsIgnoreCase(order.MarketOrigin__c) &&
								singleRecord.Commodity__c.equalsIgnoreCase(order.CommodityFormula__c) &&	
								singleRecord.ProcessType__c.equalsIgnoreCase(order.DocumentalProcessType__c) &&	
								singleRecord.SupplyType__c.equalsIgnoreCase(order.SupplyType__c) &&
								singleRecord.VoltageLevel__c != null && singleRecord.VoltageLevel__c.equalsIgnoreCase(order.VoltageLevel__c) &&	
								singleRecord.ActivationDate__c == dateToFrom
							){
								founded = true;
							}else {
								founded = false; 
							}
						}
						if(founded){
							Date targetDate = singleRecord.FulfillmentDateFrom__c;
							Integer preavviso = order.RecessNotice__c != null? (Integer)order.RecessNotice__c:0;
							Integer month = 1 - preavviso;
							Date siiDate = targetDate.addMonths(month).toStartofMonth();
							order.DateSentToSII__c = siiDate;
							break;
						}
					}
				}
		}
	}
	public static void handleBusinessDate(List<Order> orderList){
		if(!orderList.isEmpty()){
			setMaxAfterthoughtDate(orderList);
			setEffectiveDateBusiness(orderList);
			setDateSentToSiiBusiness(orderList);
		}
	}

	private static List<FulfillmentDateMatrix__c> getFulfillmentDate(List<Order> orderList){
		Set<String> marketSet = new Set<String>();
		Set<String> commoditySet = new Set<String>();
		Set<String> voltageSet = new Set<String>();
		Set<String> processTypeSet = new Set<String>();
		Set<String> supplySet = new Set<String>();
		Date nowDate = Date.today();
		Date dateFrom = Date.newInstance(nowDate.year(),01,01);
		for(Order order : orderList){
			marketSet.add(order.MarketOrigin__c);
			commoditySet.add(order.CommodityFormula__c);
			voltageSet.add(order.VoltageLevel__c);
			processTypeSet.add(order.DocumentalProcessType__c);
			supplySet.add(order.SupplyType__c);
		}
		List<FulfillmentDateMatrix__c> matrixDate = [SELECT ActivationDate__c,OriginMarket__c,Commodity__c,VoltageLevel__c,ProcessType__c,SupplyType__c,FulfillmentDateFrom__c,FulfillmentDateTo__c FROM FulfillmentDateMatrix__c WHERE
			OriginMarket__c IN:marketSet AND 
			Commodity__c IN:commoditySet AND 
			(VoltageLevel__c IN:voltageSet OR  VoltageLevel__c = '') AND
			ProcessType__c IN:processTypeSet AND 
			SupplyType__c IN:supplySet AND 
			FulfillmentDateTo__c >=: dateFrom 
		WITH SECURITY_ENFORCED];
		
		return matrixDate;
	}
    public static void setEffectiveDate(List<Order> orderList) {
		if(!orderList.isEmpty()){
			Date dateToFrom = null;
			List<FulfillmentDateMatrix__c> dateMatrix = getFulfillmentDate(orderList);
			
			for(Order order : orderList){
				//CAMBIO OFFERTA DATA FIRMA - SWITCH IN DATA INVIO SII
				if(order.DocumentalProcessType__c != null && order.DocumentalProcessType__c.equalsIgnoreCase('Cambio offerta')){
					dateToFrom = order.SignedDate__c;
				}else if(order.DocumentalProcessType__c != null && order.DocumentalProcessType__c.equalsIgnoreCase('Switch In')){
					dateToFrom = order.DateSentToSII__c;
				}else if(order.EffectiveDate__c == null){
					order.EffectiveDate__c = order.SignedDate__c;
					continue;
				}

				if (order.IsActivationDeferred__c==true) {
					continue;
				}
				
				if( order.SignedDate__c != null && ( order.DocumentalProcessType__c.equalsIgnoreCase('Voltura') || order.DocumentalProcessType__c.equalsIgnoreCase('Voltura con autolettura') ) ){
					order.EffectiveDate__c = order.SignedDate__c.addDays(3);
				}

				if(dateToFrom != null){
                    Boolean founded = false;
					for(FulfillmentDateMatrix__c singleRecord : dateMatrix){
                            founded = false;
							if(order.CommodityFormula__c != null && 'Gas'.equalsIgnoreCase(order.CommodityFormula__c)){
								if(
									singleRecord.OriginMarket__c.equalsIgnoreCase(order.MarketOrigin__c) &&
									singleRecord.Commodity__c.equalsIgnoreCase(order.CommodityFormula__c) &&	
									singleRecord.ProcessType__c.equalsIgnoreCase(order.DocumentalProcessType__c) &&	
									singleRecord.SupplyType__c.equalsIgnoreCase(order.SupplyType__c) &&	
									singleRecord.FulfillmentDateFrom__c <= 	dateToFrom &&
									singleRecord.FulfillmentDateTo__c >= dateToFrom
								){
									order.EffectiveDate__c = singleRecord.ActivationDate__c;
									order.AttributesCatalogDesc__c = 'Calcolata Data Order Gas il ' + Date.today() + 'con il seguente valore: ' + singleRecord.ActivationDate__c + ' Record utilizzato ' + singleRecord.Id;
                                    founded = true;
								}else {
                                    founded = false; 
                                }
							}
							else if(order.CommodityFormula__c != null && 'Energia Elettrica'.equalsIgnoreCase(order.CommodityFormula__c)){
								if(
									singleRecord.OriginMarket__c.equalsIgnoreCase(order.MarketOrigin__c) &&
									singleRecord.Commodity__c.equalsIgnoreCase(order.CommodityFormula__c) &&	
									singleRecord.ProcessType__c.equalsIgnoreCase(order.DocumentalProcessType__c) &&	
									singleRecord.SupplyType__c.equalsIgnoreCase(order.SupplyType__c) &&
									singleRecord.VoltageLevel__c != null && singleRecord.VoltageLevel__c.equalsIgnoreCase(order.VoltageLevel__c) &&	
									singleRecord.FulfillmentDateFrom__c <= 	dateToFrom &&
									singleRecord.FulfillmentDateTo__c >= 	dateToFrom
								){
									order.EffectiveDate__c = singleRecord.ActivationDate__c;
									order.AttributesCatalogDesc__c = 'Calcolata Data Order Ele il ' + Date.today() + ' con il seguente valore: ' + singleRecord.ActivationDate__c + ' Record utilizzato ' + singleRecord.Id;
                                    founded = true;
								}else {
                                    founded = false; 
                                }
							}
                            if(founded){
                                System.debug(order.EffectiveDate__c + ' ' + singleRecord);
                                break;
                            }
						}
					}
				}
		}
    }
}