force-app/main/default/objects/Account/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Interaction__c.field-meta.xml
<CustomField>
    <fullName>Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interazione</label>
    <referenceTo>Interaction__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead oggetto di richiesta informativa</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>Descrizione funzionale dell&apos;oggetto</description>
    <label>Interazione</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Interazione Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo di ricerca per l’Account da collegare all’interazione o creazione nuovo Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interazioni</relationshipLabel>
    <relationshipName>Interazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <label>Company Owner</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interazioni</relationshipLabel>
    <relationshipName>Interazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Silos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <formula>TEXT(Account.CompanyOwner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Interaction__c.field-meta.xml
<CustomField>
    <fullName>Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interazione</label>
    <referenceTo>Interaction__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_EscalationControllerTst.cls
@isTest
public with sharing class HDT_LC_EscalationControllerTst {
    @TestSetup
    static void makeData(){
        Account account = HDT_UTL_DataFactoryTst.createAccountPartner(1, false, 'Mario Rossi')[0];
        account.CompanyOwner__c = 'MMS';
        insert account;
        HDT_UTL_DataFactoryTst.createLead(1, true);
        HDT_UTL_DataFactoryTst.createOpportunity(1, true);
        Order order = HDT_UTL_DataFactoryTst.createOrder(1, true, account.Id, '')[0];
        HDT_UTL_DataFactoryTst.createCase(1, true, account.Id, null, null, null, order.Id);

        insert new Interaction__c(

        );
    }

    @IsTest
    static void methodName(){
        String result;
        Test.startTest();

        Account account = [SELECT Id FROM Account];
        result = HDT_LC_EscalationController.getRecordData(account.Id);
        System.assert(result.contains('Account__c'));
        
        Lead lead = [SELECT Id FROM Lead];
        result = HDT_LC_EscalationController.getRecordData(lead.Id);
        System.assert(result.contains('Lead__c'));
        
        Opportunity opportunity = [SELECT Id FROM Opportunity];
        result = HDT_LC_EscalationController.getRecordData(opportunity.Id);
        System.assert(result.contains('Opportunity__c'));
        
        Order order = [SELECT Id FROM Order];
        result = HDT_LC_EscalationController.getRecordData(order.Id);
        System.assert(result.contains('Order__c'));
        
        Case caseRecord = [SELECT Id FROM Case];
        result = HDT_LC_EscalationController.getRecordData(caseRecord.Id);
        System.assert(result.contains('Case__c'));
        
        Interaction__c interaction = [SELECT Id FROM Interaction__c];
        result = HDT_LC_EscalationController.getRecordData(interaction.Id);
        System.assert(result.contains('Interaction__c'));

        result = HDT_LC_EscalationController.getRecordData(null);
        System.assert(!result.contains('parentEntityField'));

        Test.stopTest();
    }
}