force-app/main/default/objects/Account/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/et4ae5__IndividualEmailResult__c.object-meta.xml
<CustomObject>
    <label>Individual Email Result</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Email Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup all&apos;Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individual Email Results</relationshipLabel>
    <relationshipName>Individual_Email_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/fields/CaseID__c.field-meta.xml
<CustomField>
    <fullName>CaseID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Individual Email Results</relationshipLabel>
    <relationshipName>Individual_Email_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Individual Email Results</relationshipLabel>
    <relationshipName>Individual_Email_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Silos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <formula>TEXT(Account.CompanyOwner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_TRH_IndividualEmailResult.cls
 /**
* @author Sabina Levonja (sabina.levonja@dunegroup.it)
* @date 04/06/21
* @description HDT_TRH_IndividualEmailResult
* @history Sabina Levonja – 04/06/21 – created class
*/
public inherited sharing class HDT_TRH_IndividualEmailResult extends HDT_TRH_TriggerHandler{

    public override void beforeInsert(){
        HDT_UTL_CompanyOwner.feedCompanyOwner(trigger.new);
    }
    public override void beforeUpdate(){
        setAccount(trigger.new);
    }
    public override void afterUpdate(){
        HDT_UTL_Scarti.createScartoForMarketingCloud(trigger.new,trigger.oldMap);
    }

    public static void setAccount(List<SObject> objs){

        HDT_QR_Account accountQr = new HDT_QR_Account();
        HDT_QR_Case caseQr = new HDT_QR_Case();
        HDT_QR_Order orderQr = new HDT_QR_Order();
        HDT_QR_Lead leadQr = new HDT_QR_Lead();
        HDT_QR_Contact contactQr = new HDT_QR_Contact();
        String objectApiName='';

        List<String> accountIds= new List<String>();
        List<String> caseIds= new List<String>();
        List<String> orderIds= new List<String>();
        List<String> leadIds= new List<String>();
        Set<Id> contactIds= new Set<Id>();
        List<Account> accounts= new List<Account>();
        List<Case> cases= new List<Case>();
        List<Order> orders= new List<Order>();
        List<Lead> leads= new List<Lead>();
        List<Contact> contacts= new List<Contact>();
        Map<String,Account> accountsMap=new Map<String,Account>();
        Map<String,Case> casesMap=new Map<String,Case>();
        Map<String,Order> ordersMap=new Map<String,Order>();
        Map<String,Lead> leadsMap=new Map<String,Lead>();
        Map<String,Contact> contactsMap=new Map<String,Contact>();

        for(SObject s: objs){
            objectApiName=String.valueOf(s.getSObjectType());
            if(objectApiName=='et4ae5__IndividualEmailResult__c'){
                leadIds.add(String.valueOf(s.get('et4ae5__Lead__c')));
                contactIds.add(String.valueOf(s.get('et4ae5__Contact__c')));
                caseIds.add(String.valueOf(s.get('CaseID__c')));
                orderIds.add(String.valueOf(s.get('OrderID__c')));
            }
        }
        if(accountIds.size()>0){
            accounts=accountQr.getRecordsById(accountIds, 'Id,CompanyOwner__c');
        }
        if(caseIds.size()>0){
            cases=caseQr.getRecordsById(caseIds, 'Id,CompanyOwner__c,AccountId');
        }
        if(orderIds.size()>0){
            orders=orderQr.getRecordsByIdWithFields(orderIds, 'Id,CompanyOwner__c,AccountId');
        }
        if(leadIds.size()>0){
            leads=leadQr.getRecordsById(leadIds);
        }
        if(contactIds.size()>0){
            contacts=contactQr.getRecordsByIds(contactIds);
        }

        for(Account a:accounts){
            accountsMap.put(a.Id,a);
        }
        for(Case c:cases){
            casesMap.put(c.Id,c);
        }
        for(Order o:orders){
            ordersMap.put(o.Id,o);
        }
        for(Lead l:leads){
            leadsMap.put(l.Id,l);
        }
        for(Contact con:contacts){
            contactsMap.put(con.Id,con);
        }
        for(SObject s: objs){
            if(objectApiName=='et4ae5__IndividualEmailResult__c'){
                // EVERIS: per i soli oggetti di Marketing Cloud, valorizziamo anche l'Id dell'Account recuperato dal Case/Order correlato alla comunicazione.
                if (casesMap.containsKey(String.valueOf(s.get('CaseID__c')))){
                    Case caseObj = casesMap.get(String.valueOf(s.get('CaseID__c')));
                    if (caseObj != null){
                        s.put('Account__c', caseObj.AccountId);
                    }
                }else if(ordersMap.containsKey(String.valueOf(s.get('OrderID__c')))) { // Added check making sure the ordersMap contains the id from the IndividualEmailResult
                    Order orderObj = ordersMap.get(String.valueOf(s.get('OrderID__c')));
                    if (orderObj != null){
                        s.put('Account__c', orderObj.AccountId);
                    }
                }
                // EVERIS END
            }
        }
    }
}