force-app/main/default/objects/Account/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agenzia Teleseller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/ExcludeFub__c.field-meta.xml
<CustomField>
    <fullName>ExcludeFub__c</fullName>
     <description>Determina se la numerazione indicata in “Numero telefonico”  deve essere oggetto o meno di verifica FUB. Da processo standard viene valorizzato dall’utente Marketing Cloud</description>
    <label>Escludi Fub</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/OutcomeDateFub__c.field-meta.xml
<CustomField>
    <fullName>OutcomeDateFub__c</fullName>
    <description>Campo gestito in automatico dal sistema;</description>
    <label>Data Esito FUB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/OutcomeFub__c.field-meta.xml
<CustomField>
    <fullName>OutcomeFub__c</fullName>
    <description>Campo gestito in automatico dal sistema;</description>
    <label>Esito FUB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OkKo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Contiene il numero telefonico da chiamare durante l’erogazione delle Campagne Outbound con canale Telefonico. Da processo standard viene valorizzato dall’utente Marketing Cloud</description>
    <label>Numero telefonico</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPointPhone/fields/LastOutcomeFUB__c.field-meta.xml
<CustomField>
    <fullName>LastOutcomeFUB__c</fullName>
    <label>Ultimo Esito FUB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OkKo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPointPhone/fields/LastResultDateFUB__c.field-meta.xml
<CustomField>
    <fullName>LastResultDateFUB__c</fullName>
    <description>Data di ultima esitazione FUB</description>
    <label>Data Ultimo Esito FUB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContactPointPhone/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Riporta lo stato in seguito al double opt-in</description>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificato</fullName>
            </value>
            <value>
                <fullName>Non Verificato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FUBProcessing__c/FUBProcessing__c.object-meta.xml
<CustomObject>
    <label>Lavorazione FUB</label>
    <nameField>
        <label>Lavorazione FUB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lavorazioni FUB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FUBProcessing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Archivio FUB da importare</fullName>
            </value>
            <value>
                <fullName>Archivio FUB importato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agenzia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Silos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OkKo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>KO</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <masterLabel>OK KO</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_BA_ImportFubFileTst.cls
@isTest
public with sharing class HDT_BA_ImportFubFileTst {
    
    @testSetup 
    static void setup(){
        
        List<Account> testAcc =  HDT_UTL_DataFactoryTst.createAccountPartner(1, false , 'testact');
        testAcc[0].CompanyOwner__c  = 'HERA COMM';
        insert testAcc;

        id acctId =testAcc[0].id;

        List<Individual>  testInd = HDT_UTL_DataFactoryTst.createIndividual(1,true);
        id indId = testInd[0].id;

        List<Contact> testCont =  HDT_UTL_DataFactoryTst.createContact(2, true, acctId);
        testCont[0].IndividualId = indId;
        update testCont;
        

        List<Lead> testLead =  HDT_UTL_DataFactoryTst.createLead(2,true);
        

        List<Campaign> camp = HDT_UTL_DataFactoryTst.createCampaign(1,true);
        id campId = camp[0].id;

        List<FUBProcessing__c> testFubPro = HDT_UTL_DataFactoryTst.createfubProcessing (1, true, 'Archivio FUB da importare');
        id fpId = testFubPro[0].id;


        HDT_UTL_DataFactoryTst.createFubProcessingItem(1,true,campId,fpId);

        List<CampaignMember> listCamps = HDT_UTL_DataFactoryTst.createCampaignMember(true,campId,testLead,testCont);
        listCamps[0].ExcludeFub__c = 'No';
        listCamps[0].Agency__c = acctId;
        listCamps[0].PhoneNumber__c = '1234';
        //listCamps[0].OutcomeFub__c = '';
        //listCamps[0].OutcomeDateFub__c = system.Date.today();
        listCamps[1].PhoneNumber__c = '';
        listCamps[1].ExcludeFub__c = 'No';
        listCamps[1].Agency__c = acctId;
        update listCamps;

        List<ContactPointPhone> testContPointPhone = HDT_UTL_DataFactoryTst.createContactPointPhone(1,true,indId);
        testContPointPhone[0].TelephoneNumber = '1234';
        testContPointPhone[0].ParentId = testInd[0].id;
        testContPointPhone[0].LastOutcomeFUB__c = 'OK';
        testContPointPhone[0].LastResultDateFUB__c = system.Date.today();
        update testContPointPhone;

    }

    @isTest
    public static void testImportFubFiles() {
        
        String csv = '1234';
        id fubId = [SELECT id FROM FUBProcessing__c WHERE  Status__c = 'Archivio FUB da importare'].id;

        Test.startTest();
        HDT_BA_ImportFubFile imp = new HDT_BA_ImportFubFile(fubId,csv);
        Database.executeBatch(imp);
        Test.stopTest();

        FUBProcessing__c fubp = [SELECT id,Status__c FROM FUBProcessing__c WHERE id = :fubId];

        system.assertEquals(true, fubp.Status__c == 'Archivio FUB importato' , 'the status of FUBProcessing__c is not assigned');
        system.assertNotEquals('', fubp.Status__c, 'the status of FUBProcessing__c is null');
    
    } 
}