force-app/main/default/objects/Account/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsVATGroupJoined__c.field-meta.xml
<CustomField>
    <fullName>IsVATGroupJoined__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Gestione Gruppo IVA</description>
    <label>Adesione Gruppo IVA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroup__c.field-meta.xml
<CustomField>
    <fullName>VATGroup__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Partita IVA di Gruppo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroupEndDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupEndDate__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Data Fine Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATGroupStartDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupStartDate__c</fullName>
    <description>Gestione Gruppo IVA</description>
    <label>Data Inizio Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Importo</description>
    <label>Importo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Nome del Cluster a cui appartiene un processo.</description>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentalProcessType__c.field-meta.xml
<CustomField>
    <fullName>DocumentalProcessType__c</fullName>
    <description>Rappresenta il tipo di processo gestito dal provider Documentale</description>
    <formula>IF(AND(ISPICKVAL(Type,&apos;Variazione Potenza&apos;), PowerRequested__c &gt; PowerCommitted__c),&apos;Aumento Potenza&apos;,
    IF(AND(ISPICKVAL(Type,&apos;Variazione Potenza&apos;), PowerRequested__c &lt; PowerCommitted__c),&apos;Diminuzione Potenza&apos;,
        IF(AND(ISPICKVAL(Type,&apos;Verifica Tensione - Pressione&apos;), CommodityFormula__c=&apos;Gas&apos;),&apos;Verifica Pressione&apos;,
            IF(AND(ISPICKVAL(Type,&apos;Verifica Tensione - Pressione&apos;), CommodityFormula__c=&apos;Energia Elettrica&apos;),&apos;Verifica Tensione&apos;,
				IF(ISPICKVAL(Type,&apos;Verifica GDM&apos;),&apos;Verifica GdM&apos;,
					IF(ISPICKVAL(Type,&apos;Richiesta lettura cliente&apos;),&apos;Richiesta lettura c/cliente&apos;,
						IF(ISPICKVAL(Type,&apos;Sost. contatore cliente&apos;),&apos;Sost. contatore c/cliente&apos;,TEXT(Type))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo Processo Documentale</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FixedAmount__c.field-meta.xml
<CustomField>
    <fullName>FixedAmount__c</fullName>
    <description>Diritti fissi che compongono il prezzo del preventivo</description>
    <label>Componente Fissa Importo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsVATGroupJoined__c.field-meta.xml
<CustomField>
    <fullName>IsVATGroupJoined__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Nuova Flag Adesione Gruppo IVA per sotto-processo Variazione Gruppo IVA</description>
    <label>Flag Adesione Gruppo IVA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/QuotationType__c.field-meta.xml
<CustomField>
    <fullName>QuotationType__c</fullName>
    <label>Tipo Preventivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalesCompany__c.field-meta.xml
<CustomField>
    <fullName>SalesCompany__c</fullName>
    <description>Società di Vendita</description>
    <label>Sales Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VariableAmount__c.field-meta.xml
<CustomField>
    <fullName>VariableAmount__c</fullName>
    <description>Componente variabile che compone il prezzo del preventivo</description>
    <label>Componente Variabile Importo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/VATGroup__c.field-meta.xml
<CustomField>
    <fullName>VATGroup__c</fullName>
    <description>Nuova Partita IVA di Gruppo per sotto-processo Variazione Gruppo IVA</description>
    <label>Partita IVA di Gruppo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VATGroupEndDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupEndDate__c</fullName>
    <description>Nuova Data Fine Piva di Gruppo per sotto-processo Variazione Gruppo IVA</description>
    <label>Data Fine Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/VATGroupStartDate__c.field-meta.xml
<CustomField>
    <fullName>VATGroupStartDate__c</fullName>
    <description>Nuova Data Inizio Piva di Gruppo per sotto-processo Variazione Gruppo IVA</description>
    <label>Data Inizio Piva di Gruppo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/VATPercentage__c.field-meta.xml
<CustomField>
    <fullName>VATPercentage__c</fullName>
    <description>Indica la percentuale iva applicata in base alla tipologia di cliente</description>
    <label>Percentuale IVA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VATPercentage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_HcmCityException__mdt/HDT_HcmCityException__mdt.object-meta.xml
<CustomObject>
    <label>HDT_HcmCityException</label>
    <pluralLabel>HDT_HcmCityExceptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_HeraCompany__mdt/HDT_HeraCompany__mdt.object-meta.xml
<CustomObject>
    <label>Società</label>
    <pluralLabel>Società</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_HeraCompany__mdt/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>CompanyCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_HeraCompany__mdt/fields/SalesCompany__c.field-meta.xml
<CustomField>
    <fullName>SalesCompany__c</fullName>
    <label>Società di vendita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attivazioni</fullName>
                <default>true</default>
                <label>Attivazioni</label>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <formula>TEXT(Account.CompanyOwner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocumentalProcessType__c.field-meta.xml
<CustomField>
    <fullName>DocumentalProcessType__c</fullName>
    <formula>IF(ISPICKVAL(ProcessType__c,&apos;Subentro Gas&apos;),&apos;Subentro&apos;,
IF(ISPICKVAL(ProcessType__c,&apos; Subentro Ele&apos;),&apos;Subentro&apos;,TEXT(ProcessType__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo Processo Documentale</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ImplantType__c.field-meta.xml
<CustomField>
    <fullName>ImplantType__c</fullName>
    <label>Tipo impianto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_ImplantType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/QuotationType__c.field-meta.xml
<CustomField>
    <fullName>QuotationType__c</fullName>
    <label>Tipo Preventivo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesCompany__c.field-meta.xml
<CustomField>
    <fullName>SalesCompany__c</fullName>
    <label>Società di vendita</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hera Comm Marche</fullName>
            </value>
            <value>
                <fullName>Acegas Aps Service</fullName>
            </value>
            <value>
                <fullName>Hera Comm NordEst</fullName>
            </value>
            <value>
                <fullName>Hera Comm S.p.A.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VariableAmount__c.field-meta.xml
<CustomField>
    <fullName>VariableAmount__c</fullName>
    <label>Componente Variabile Importo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_ImplantType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1001-Cottura cibi</fullName>
    </customValue>
    <customValue>
        <fullName>1002-Cottura/Produz acq calda</fullName>
    </customValue>
    <customValue>
        <fullName>1003-Riscaldamento esclusivo</fullName>
    </customValue>
    <customValue>
        <fullName>1004-Riscaldamento promiscuo</fullName>
    </customValue>
    <customValue>
        <fullName>1005-Risc. centraliz esclusivo</fullName>
    </customValue>
    <customValue>
        <fullName>1006-Risc. centraliz promiscuo</fullName>
    </customValue>
    <customValue>
        <fullName>1007-Attivita produttive</fullName>
    </customValue>
    <customValue>
        <fullName>1008-Promiscuo (prod+ risc)</fullName>
    </customValue>
    <customValue>
        <fullName>1009-Reti (cabine primo salto)</fullName>
    </customValue>
    <customValue>
        <fullName>1010-Usi interni</fullName>
    </customValue>
    <customValue>
        <fullName>13A0-Usi di Abitazione BT</fullName>
    </customValue>
    <customValue>
        <fullName>13BB-Illuminazione pubblica BT</fullName>
    </customValue>
    <customValue>
        <fullName>13CB-Non domestici in BT</fullName>
    </customValue>
    <customValue>
        <fullName>13CT-Forn temporanee &lt; 21 gg</fullName>
    </customValue>
    <customValue>
        <fullName>13DM-Illuminazione pubblica MT</fullName>
    </customValue>
    <customValue>
        <fullName>13EM-Non domestici MT</fullName>
    </customValue>
    <customValue>
        <fullName>13FM-Non domestici AT</fullName>
    </customValue>
    <customValue>
        <fullName>13X0-Usi interni BT</fullName>
    </customValue>
    <customValue>
        <fullName>13Y0-Usi interni MT</fullName>
    </customValue>
    <customValue>
        <fullName>13Z0-Grossisti</fullName>
    </customValue>
    <customValue>
        <fullName>1101-Domestico</fullName>
    </customValue>
    <customValue>
        <fullName>1102-Non domestico</fullName>
    </customValue>
    <customValue>
        <fullName>1103-Attivita</fullName>
    </customValue>
    <customValue>
        <fullName>1104-Scar. poz priv. civ. cont</fullName>
    </customValue>
    <customValue>
        <fullName>1105-Antincendio</fullName>
    </customValue>
    <customValue>
        <fullName>1106-Cantiere</fullName>
    </customValue>
    <customValue>
        <fullName>1107-Colonnetta</fullName>
    </customValue>
    <customValue>
        <fullName>1108-Irriguo</fullName>
    </customValue>
    <customValue>
        <fullName>1109-Comunale</fullName>
    </customValue>
    <customValue>
        <fullName>1110-Ente pubblico</fullName>
    </customValue>
    <description>1001-Cottura cibi
1002-Cottura/Produz acq calda
1003-Riscaldamento esclusivo
1100-ACQUA --- Non definito --- 
1119-Scar. ind.le  cont. Div</description>
    <masterLabel>Tipologia Impianto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_VATPercentage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GENERICI 10%-01</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICI 22%-02</fullName>
    </customValue>
    <customValue>
        <fullName>SOC. CONTROLLATE 10%-03</fullName>
    </customValue>
    <customValue>
        <fullName>SOC.CONTROLLATE 22%-04</fullName>
    </customValue>
    <customValue>
        <fullName>SOC. COLLEGATE 10%-05</fullName>
    </customValue>
    <customValue>
        <fullName>SOC. COLLEGATE 22%-06</fullName>
    </customValue>
    <customValue>
        <fullName>SOC. CONTROLLANTI 10%-07</fullName>
    </customValue>
    <customValue>
        <fullName>SOC. CONTROLLANTI 22%-08</fullName>
    </customValue>
    <customValue>
        <fullName>SOCIETA&apos; DEL GRUPPO 10%-09</fullName>
    </customValue>
    <customValue>
        <fullName>SOCIETA&apos; DEL GRUPPO 22%-10</fullName>
    </customValue>
    <customValue>
        <fullName>NON IMP. ART. 72-12</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOFATT. F.CAMPO IVA ART.2-13</fullName>
    </customValue>
    <customValue>
        <fullName>SOC. PARTECIPATE 10%-14</fullName>
    </customValue>
    <customValue>
        <fullName>SOC. PARTECIPATE 22%-16</fullName>
    </customValue>
    <customValue>
        <fullName>LIVIGNO/CAMPIONE FUOR CAMPO-19</fullName>
    </customValue>
    <customValue>
        <fullName>NON IMP. ART. 8 S. MARINO-17</fullName>
    </customValue>
    <customValue>
        <fullName>Reverse Charge-25</fullName>
    </customValue>
    <customValue>
        <fullName>Split payment clienti 10%-S1</fullName>
    </customValue>
    <customValue>
        <fullName>Split payment clienti 22%-S2</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller IVA ES-26</fullName>
    </customValue>
    <customValue>
        <fullName>Split payment soc gruppo10%-S3</fullName>
    </customValue>
    <customValue>
        <fullName>Split payment soc gruppo10%-S4</fullName>
    </customValue>
    <customValue>
        <fullName>Consociate IVA ridotta-27</fullName>
    </customValue>
    <customValue>
        <fullName>Consociate IVA ordinaria-28</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICI 20%-02</fullName>
    </customValue>
    <masterLabel>Percentuale IVA</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_PayloadManagement.cls
public with sharing class HDT_UTL_PayloadManagement implements HDT_UTL_DocumentalManagementInterface{
    public HDT_QR_PayloadManagement queryClass = new HDT_QR_PayloadManagement();
    public String execute(String method,Map<String,List<sObject>> inputs, Map<String,Object> formParams){
        String result = '';
        try {
            switch on method {
                when 'calculateCompanyCode' {
                    return calculateCompanyCode(inputs,formParams);
                }when 'checkQuotationType'{
                    return checkQuotationType(inputs,formParams);
                }when 'calculateQuotationAmount'{
                    return calculateQuotationAmount(inputs,formParams);
                }when 'checkGruppoIva'{
                    return checkGruppoIva(inputs,formParams);
                }when 'checkCommercialOffer'{
                    return checkCommercialOffer(inputs,formParams);
                }
                when else {
                    return '';
                }
            }
        } catch (Exception ex) {
            System.debug('Si è verificato un errore nel richiamo del metodo ' + method + ': ' + ex.getMessage() + ' alla riga ' + ex.getLineNumber());
        }
        return result;
    }

    private String calculateCompanyCode(Map<String,List<sObject>> inputs, Map<String,Object> formParams){
        //TODO: Gestione Account e Estratto Conto
        String context = (String) formParams.get('Contesto');
        String companyDesc = '';
        String city = '';
        switch on context {
            when 'Order' {
                companyDesc = 'Hera Comm S.p.A.';
                companyDesc = HDT_UTL_DocumentalManagement.getValue('Order', 'SalesCompany__c', 0, inputs, formParams);
                city = HDT_UTL_DocumentalManagement.getValue('Order', 'SupplyCity__c', 0, inputs, formParams);
                List<HDT_HcmCityException__mdt> cityExceptionList = queryClass.getHcmCityExceptionByName(city);
                if (cityExceptionList != null && cityExceptionList.size()>0) {
                    companyDesc = 'Hera Comm S.p.A.';
                }
            }
            when 'Case'{
                companyDesc = HDT_UTL_DocumentalManagement.getValue('Case', 'SalesCompany__c', 0, inputs, formParams);
            }
            when 'Account'{
                //gestire in base al compani owner
                companyDesc = HDT_UTL_DocumentalManagement.getValue('Account', 'CompanyOwner__c', 0, inputs, formParams);
                if(companyDesc.equalsIgnoreCase('HERA COMM')){
                    companyDesc = 'Hera Comm S.p.A.';
                }
            }
            when else {
                companyDesc = '';
            }
        }
        return getCompanyCode(companyDesc);
    }

    private String getCompanyCode(String companyDesc){
        if(companyDesc==null || String.isBlank(companyDesc)) return '';
        String queryString = 'SELECT id,Label, CompanyCode__c from HDT_HeraCompany__mdt WHERE Label=\''+companyDesc+'\'';
        String objectName = 'HDT_HeraCompany__mdt';
        List<SObject> recordList = HDT_QR_GenericQuery.getGenericRecords(queryString, objectName);
        if(recordList != null && recordList.size()>0){
            return (String) recordList[0].get('CompanyCode__c');
        }else {
            return '';
        }
    }

    private String checkQuotationType(Map<String,List<sObject>> inputs, Map<String,Object> formParams){
        String context = (String) formParams.get('Contesto');
        String quotationType='';
        String processType = '';
        String cluster='';
        switch on context {
            when 'Case' {
                quotationType = HDT_UTL_DocumentalManagement.getValue('Case', 'QuotationType__c', 0, inputs, formParams);
                processType = HDT_UTL_DocumentalManagement.getValue('Case', 'DocumentalProcessType__c', 0, inputs, formParams);
                cluster = HDT_UTL_DocumentalManagement.getValue('Case', 'Cluster__c', 0, inputs, formParams);
            }
            when else {
                quotationType = ''; //da ordine manca il campo
                processType =  HDT_UTL_DocumentalManagement.getValue('Order', 'ProcessType__c', 0, inputs, formParams);
                cluster = HDT_UTL_DocumentalManagement.getValue('Order', 'Cluster__c', 0, inputs, formParams);
            }
        }
        //aggiungere cluster attivazioni
        if(cluster.equalsIgnoreCase('Preventivi') || cluster.equalsIgnoreCase('Verifiche')){
            if(quotationType.equalsIgnoreCase('Predeterminabile')){
                return 'SIP';
            }else if(quotationType.equalsIgnoreCase('Rapido') && processType.equalsIgnoreCase('Aumento Potenza')){
                return 'NOP';
            }else if(quotationType.equalsIgnoreCase('Rapido') && processType.equalsIgnoreCase('Diminuzione Potenza')){
                return 'POT';
            }else if(quotationType.equalsIgnoreCase('Predeterminabile')) {
                return 'SIP';
            }else {
                return '';
            }
        }else {
            return '';
        }
    }
    private String calculateQuotationAmount(Map<String,List<sObject>> inputs, Map<String,Object> formParams){
        //imponibile = importo preventivo
        //aliquota iva
        //prestazione=(imponibile-contributo);
        //totale=(imponibile+valIva);
        //valIva=((imponibile/100)*aliquota);
        String context = (String) formParams.get('Contesto');
        String amount='';
        Double amountDouble;
        Integer ivaInteger = 0;
        String iva = '';
        Double ivaAmount=0;
        String fixedAmount = '';
        String variableAmount = '';
        Double totalAmount;
        String result='';
        switch on context {
            when 'Case' {
                amount = HDT_UTL_DocumentalManagement.getValue('Case', 'Amount__c', 0, inputs, formParams);
                fixedAmount = HDT_UTL_DocumentalManagement.getValue('Case', 'FixedAmount__c', 0, inputs, formParams);
                variableAmount = HDT_UTL_DocumentalManagement.getValue('Case', 'VariableAmount__c', 0, inputs, formParams);
                iva = HDT_UTL_DocumentalManagement.getValue('Case', 'VATPercentage__c', 0, inputs, formParams);
            }
            when else {
                //quotationType = ''; //da ordine manca il campo
                //processType =  HDT_UTL_DocumentalManagement.getValue('Order', 'ProcessType__c', 0, inputs, formParams);
            }
        }
        if(String.isNotBlank(amount)){
            amountDouble = Double.valueOf(amount);
            if(String.isNotBlank(iva)){
                if(iva.indexOf('10') > -1){
                    ivaInteger = 10;
                }else if(iva.indexOf('22') > -1){
                    ivaInteger = 22;
                }
                if(ivaInteger > 0)
                    ivaAmount = ((amountDouble/100)*ivaInteger);
            }
            totalAmount = amountDouble + ivaAmount;
            result = variableAmount + '|' + fixedAmount + '|' + amount + '|' + ivaInteger + '|' + ivaAmount + '|' + totalAmount;
        }else {
            result = '|||||';
        }
        
        return result;
    }

    private String checkGruppoIva(Map<String,List<sObject>> inputs, Map<String,Object> formParams){
        String gPiva = HDT_UTL_DocumentalManagement.getValue('Account', 'VATGroup__c', 0, inputs, formParams);//VATGroup__c
        String startPiva = HDT_UTL_DocumentalManagement.getValue('Account', 'VATGroupStartDate__c', 0, inputs, formParams);//VATGroupStartDate__c
        String flagPiva = HDT_UTL_DocumentalManagement.getValue('Account', 'IsVATGroupJoined__c', 0, inputs, formParams);//IsVATGroupJoined__c
        String endPiva = HDT_UTL_DocumentalManagement.getValue('Account', 'VATGroupEndDate__c', 0, inputs, formParams);//VATGroupEndDate__c
        Date maxDate = date.newInstance(4000, 12, 31);
        if(String.isBlank(flagPiva) || flagPiva.equalsIgnoreCase('false')){
            return '';
        }else if(String.isNotBlank(endPiva) && Date.valueOf(endPiva) == maxDate){
            if(Date.today()> Date.valueOf(startPiva)){
                return gPiva + '|' + HDT_UTL_DocumentalManagement.transformDate(Date.valueOf(startPiva));
            }else {
                return '';
            }
        }else{
            if(Date.today() > Date.valueOf(startPiva) && Date.today() < Date.valueOf(endPiva)){
                return gPiva + '|' + HDT_UTL_DocumentalManagement.transformDate(Date.valueOf(startPiva));
            }else {
                return '';
            }
        }
    }

    private String checkCommercialOffer(Map<String,List<sObject>> inputs, Map<String,Object> formParams){
        String offerName = HDT_UTL_DocumentalManagement.getValue('Order', 'ProductName__c', 0, inputs, formParams);//ProductName__c
        String implantType = HDT_UTL_DocumentalManagement.getValue('Order', 'ImplantType__c', 0, inputs, formParams);//ImplantType__c
        String result = '';
        if(String.isNotBlank(offerName)){
            if(offerName.indexOf('Sole Lune') > -1){
                result = 'X|';
            }else {
                result = '|';
            }
            if(offerName.indexOf('24') > -1){
                result += 'X|';
            }else {
                result += '|';
            }
            if(offerName.indexOf('caso A') > -1){
                result += 'X|';
            }else {
                result += '|';
            }
            if(offerName.indexOf('caso B') > -1){
                result += 'X|';
            }else {
                result += '|';
            }
        }else {
            result = '||||';
        }
        if(String.isNotBlank(implantType)){
            if (implantType.indexOf('Cottura cibi') > -1) {
                result+='CO|';
            }else if (implantType.indexOf('acq calda') > -1) {
                result+='AC|';
            }else if (implantType.indexOf('Riscaldamento') > -1) {
                result+='RA|';
            }else if (implantType.indexOf('Risc. centraliz') > -1) {
                result+='RC|';
            }else {
                 result +='|';
            }
        }else {
            result += '|';
        }

        if(String.isNotBlank(offerName)){
            if(offerName.indexOf('Bonus') > -1){
                result = 'X|';
            }else {
                result = '|';
            }
            if(offerName.indexOf('Opzione Natura') > -1){
                result = 'X';
            }
        }else {
            result += '|';
        }
        return result;
    }
}