force-app/main/default/objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>Codice Business Partner (BP) di SAP</description>
    <externalId>true</externalId>
    <label>Codice cliente</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerMarking__c.field-meta.xml
<CustomField>
    <fullName>CustomerMarking__c</fullName>
    <description>Rappresenta una segmentazione del cliente</description>
    <label>Marcatura Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerMarking</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita Iva</description>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_CustomerMarking.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAS Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>AAS Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ACEL-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>Amga-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>ANTENORE ENERGY-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BENACO-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BE POWER-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Altro</fullName>
    </customValue>
    <customValue>
        <fullName>BLU RANTON-Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Altro</fullName>
    </customValue>
    <customValue>
        <fullName>CMV E e I - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D1 - Persona fisica</fullName>
    </customValue>
    <customValue>
        <fullName>D2 - Ditta individuale</fullName>
    </customValue>
    <customValue>
        <fullName>D3 - Azienda</fullName>
    </customValue>
    <customValue>
        <fullName>D4 - Parti comuni</fullName>
    </customValue>
    <customValue>
        <fullName>D5 - Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>D6 - Associazione</fullName>
    </customValue>
    <customValue>
        <fullName>D7 - BP Doppio</fullName>
    </customValue>
    <description>Rappresenta una segmentazione del cliente</description>
    <masterLabel>Marcatura Cliente</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_StoricizzazioneClienteTst.cls
/**
 * Header of the class "HDT_LC_StoricizzazioneClienteTst"
 * @author Cesare Bagnolini, cesare.bagnolini@webresults.it
 * @version 1.0
 * @description: Apex Test Class of the relative Apex Class ""HDT_LC_StoricizzazioneCliente"
 * @history
 * @Created 17/09/2021
 * Modified By:
 **/

@isTest
public class HDT_LC_StoricizzazioneClienteTst {    
    
    private static HDT_UTL_Constants constants=new HDT_UTL_Constants();
    @TestSetup
    static void makedata(){
        
        
        Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME);
		User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);
		internalUser.UserPermissionsMarketingUser=true;

		insert internalUser;

        System.runAs(internalUser){
            List<Account> accs = HDT_UTL_DataFactoryTst.createAccountBusiness(1,true,'HERA COMM','Azienda','Aziende SME');
            for(Account a : accs){
                a.FiscalCode__c='testFC';
                a.VATNumber__c='testVN';
                a.CustomerCode__c='testCC';
            }
            
            update accs;
            
		}
    }
    
    @isTest
    static void test1(){
        
        Id profileId = HDT_UTL_DataFactoryTst.getProfileId('Hera System Integrator');
        Id UserRoleId = HDT_UTL_DataFactoryTst.getUserRoleId('HDT_FrontOffice_HERA_COMM');
        User u = HDT_UTL_DataFactoryTst.createInternalUser(profileId,false);
        u.UserRoleId = UserRoleid;
        insert u;
        
        system.runAs(u){
            Test.startTest();        
            
            HDT_LC_StoricizzazioneCliente.HDT_LC_Link link = new HDT_LC_StoricizzazioneCliente.HDT_LC_Link('testname','testvalue');
            
            List<HDT_LC_StoricizzazioneCliente.HDT_LC_Customer> listaCustomer1 = HDT_LC_StoricizzazioneCliente.getExternalCustomer('testFC', 'id', 'ASC', 'Codice Fiscale');
            List<HDT_LC_StoricizzazioneCliente.HDT_LC_Customer> listaCustomer2 = HDT_LC_StoricizzazioneCliente.getExternalCustomer('testVN', 'id', 'ASC', 'Partita Iva');
            List<HDT_LC_StoricizzazioneCliente.HDT_LC_Customer> listaCustomer3 = HDT_LC_StoricizzazioneCliente.getExternalCustomer('testCC', 'id', 'DESC', 'Codice Cliente');
            
            System.assertNotEquals(null, listaCustomer1, 'A list of account is not returned');
            
            List <Account> accounts = [select id from Account where CustomerMarking__c = 'Azienda'];
            List <Id> accountsId = new List<Id>();
            for (Account a : accounts){
                accountsId.add(a.id);
            }
            
            List<Id> customerId = new List<Id>();
            for(HDT_LC_StoricizzazioneCliente.HDT_LC_Customer a : listaCustomer1){
                customerId.add(a.id);
            }
            
            System.assertEquals(accountsId, customerId, 'The account with CustomerMarking__c = Azienda is not returned');

            Test.stopTest();
        }        
    }
}