force-app/main/default/objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>Codice Business Partner (BP) di SAP</description>
    <externalId>true</externalId>
    <label>Codice cliente</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountDataEnrichment__mdt/AccountDataEnrichment__mdt.object-meta.xml
<CustomObject>
    <label>Account data enrichment</label>
    <pluralLabel>Account data enrichment</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountDataEnrichment__mdt/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_AccountDataEnrichment.cls
public  inherited sharing  class HDT_QR_AccountDataEnrichment {

    public static List<AccountDataEnrichment__mdt> getAccountDataEnrichment(List<AccountDataEnrichment__mdt> enrichmentbMetadataList, String tabCode){
        enrichmentbMetadataList = new List<AccountDataEnrichment__mdt>();
        enrichmentbMetadataList = [
            SELECT Label, DeveloperName, Authorization__c, ColumnData__c, Credential__c, UseMock__c
            FROM AccountDataEnrichment__mdt
            WHERE DeveloperName = :tabCode
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        return enrichmentbMetadataList;       
    }

    public static List<Account> getAccountRecords(List<Account> accList, String recordId){
        accList = new List<Account>();
        accList = [
            SELECT Id, CustomerCode__c
            FROM Account
            WHERE Id = :recordId
            WITH SECURITY_ENFORCED
            LIMIT 1            
        ];
        return accList;
    }

}