force-app/main/default/objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>Codice Business Partner (BP) di SAP</description>
    <externalId>true</externalId>
    <label>Codice cliente</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/ContractAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ContractAccountCode__c</fullName>
    <description>Codice Contract Account Sap</description>
    <externalId>true</externalId>
    <label>Conto Contrattuale</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Profile</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Casi</relationshipLabel>
    <relationshipName>Casi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ContractAccountCode__c</fullName>
    <description>Conto Contrattuale</description>
    <label>Conto Contrattuale</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentSelected__c/DocumentSelected__c.object-meta.xml
<CustomObject>
    <label>Documento selezionato</label>
    <nameField>
        <label>Nome Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documenti selezionati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/BillingProfile__c.field-meta.xml
<CustomField>
    <fullName>BillingProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profilo di fatturazione</label>
    <referenceTo>BillingProfile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ContractAccountCode__c</fullName>
    <label>Codice CA SAP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <label>Codice Cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_LC_AddDocumentSelectedTst.cls
@isTest
public class HDT_LC_AddDocumentSelectedTst {
    
    @TestSetup
    static void setup(){
        
        List<Account> accList = HDT_UTL_DataFactoryTst.createAccountBusiness(2, true, 'HERA COMM', 'Azienda', 'Aziende SME');
        List<Order> ordList = HDT_UTL_DataFactoryTst.createOrder(1, true, accList[0].id, 'Bozza');
        List<ServicePoint__c> servPointList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        List<Contact> contactList = HDT_UTL_DataFactoryTst.createContact(1, true, accList[0].Id);
        List<BillingProfile__c> billingProfileList = HDT_UTL_DataFactoryTst.createBillingProfile(1,true, accList[0].Id);
        List<Contract> contractList = HDT_UTL_DataFactoryTst.createContract(1, true, accList[0].id);
        List<Contract> contractListTwo = HDT_UTL_DataFactoryTst.createContract(1, true, accList[1].id);
        List<Case> caseList = HDT_UTL_DataFactoryTst.createCaseDocumentale(1, true, accList[0].id, contactList[0].Id, servPointList[0].id, contractList[0].id, ordList[0].id);

        HDT_UTL_DataFactoryTst.pClickCasePhase();

        HDT_UTL_Constants constantsUtl = new HDT_UTL_Constants();
        String rtName = constantsUtl.CASE_RECORDTYPE_DEVELOPERNAME_DOCUMENTALECOPIACONTRATTO;
        String rtId = constantsUtl.CASE_RECORDTYPEID_DOCUMENTALECOPIACONTRATTO;
        HDT_UTL_DataFactoryTst.createPhaseTransition(true, 'In attesa Documentazione', 'Bozza', rtId, rtName,'A','','','');

        List<DocumentSelected__c> documents = HDT_UTL_DataFactoryTst.createDocumentSelected(1, true, false, (String) caseList[0].Id,billingProfileList[0].ContractAccountCode__c);
    }

    @isTest
    static void testInsertDocuments(){

        List<String> documents = new List<String>();
        documents.add('0000411709364963'); //000041170936496 + 3

        Account account = [
            SELECT Id, CustomerCode__c
            FROM Account
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        Case cas = [SELECT Id FROM Case WHERE AccountId =: account.Id WITH SECURITY_ENFORCED LIMIT 1];

        Test.startTest();

        HDT_LC_AddDocumentSelected.insertDocuments(documents, cas.Id);

        DocumentSelected__c document = [SELECT Id FROM DocumentSelected__c WHERE Name = '0000411709364963' WITH SECURITY_ENFORCED LIMIT 1];

        System.assert(document != null, 'Si è verificato un errore in fase di inserimento del documento');

        Test.stopTest();

    }

    @isTest
    static void testCheckExistingDocuments(){

        List<String> documents = new List<String>();

        Account account = [
            SELECT Id, CustomerCode__c
            FROM Account
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];

        Case cas = [SELECT Id FROM Case WHERE AccountId =: account.Id WITH SECURITY_ENFORCED LIMIT 1];

        Test.startTest();

        List<string> documentsRetrieved = HDT_LC_AddDocumentSelected.checkExistingDocuments(documents, cas.Id);

        System.assert(documentsRetrieved.size() != 0, 'Si è verificato un errore in fase di retrieve dei documenti esistenti');

        Test.stopTest();

    }

}