force-app/main/default/objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>Codice Business Partner (BP) di SAP</description>
    <externalId>true</externalId>
    <label>Codice cliente</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Cliente Finale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita Iva</description>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l&apos;oggetto Vendita</description>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale di Vendita</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare un contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <label>Codice Cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Tipo Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IsWinback__c.field-meta.xml
<CustomField>
    <fullName>IsWinback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flag WinBack</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketOrigin__c.field-meta.xml
<CustomField>
    <fullName>MarketOrigin__c</fullName>
    <label>Mercato Provenienza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PowerCommitted__c.field-meta.xml
<CustomField>
    <fullName>PowerCommitted__c</fullName>
    <description>Indica la potenza impegnata dell&apos;impianto</description>
    <label>Potenza Impegnata</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/PowerRequested__c.field-meta.xml
<CustomField>
    <fullName>PowerRequested__c</fullName>
    <label>Potenza Richiesta</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SAPImplantCode__c.field-meta.xml
<CustomField>
    <fullName>SAPImplantCode__c</fullName>
    <label>Impianto SAP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <label>Tensione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VoltageLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SaleServiceItem__c/SaleServiceItem__c.object-meta.xml
<CustomObject>
    <description>Oggetto giunzione tra opportunity/quote e Service point</description>
    <label>Sale Service Item</label>
    <nameField>
        <label>SaleServiceItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Service Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SaleServiceItem__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Sale Service Items</relationshipLabel>
    <relationshipName>SaleServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/AnnualConsumptionStandardM3__c.field-meta.xml
<CustomField>
    <fullName>AnnualConsumptionStandardM3__c</fullName>
    <description>Consumo annuo stimato correttore (solo GAS)</description>
    <label>Consumo Annuo</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MarketOrigin__c.field-meta.xml
<CustomField>
    <fullName>MarketOrigin__c</fullName>
    <label>Mercato di provenienza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/MeterStatus__c.field-meta.xml
<CustomField>
    <fullName>MeterStatus__c</fullName>
    <label>Stato Apparecchiatura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Attivo</fullName>
            </value>
            <value>
                <fullName>Inattivo</fullName>
            </value>
            <value>
                <fullName>Sospeso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/PowerRequested__c.field-meta.xml
<CustomField>
    <fullName>PowerRequested__c</fullName>
    <description>Specifica per l&apos;ele nei casi di attivazione con modifica.</description>
    <label>Potenza Richiesta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SAPImplantCode__c.field-meta.xml
<CustomField>
    <fullName>SAPImplantCode__c</fullName>
    <description>SAPImplantCode__c</description>
    <externalId>true</externalId>
    <label>Impianto SAP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/VoltageLevel__c.field-meta.xml
<CustomField>
    <fullName>VoltageLevel__c</fullName>
    <description>Livello di tensione</description>
    <label>Tensione di Consegna</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_VoltageLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Viene restituito il canale di vendita dell&apos;ordine padre correlato, oppure dell&apos;ordine padre dell&apos;ordine correlato all&apos;attività</description>
    <formula>IF(Order__r.ParentOrder__c = null, Order__r.Channel__c , Order__r.ParentOrder__r.Channel__c)</formula>
    <label>Canale di vendita</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente inviato da Sigma al CRM.</description>
    <label>Codice Fiscale AU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OrderID</description>
    <label>Order Correlato</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>POD/PDR</description>
    <label>POD/PDR</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita IVA del cliente inviata da Sigma al CRM.</description>
    <label>Partita IVA</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CustomerType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Persona Fisica</fullName>
    </customValue>
    <customValue>
        <fullName>Organizzazione</fullName>
    </customValue>
    <customValue>
        <fullName>Gruppo</fullName>
    </customValue>
    <masterLabel>Tipo Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Libero</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>FUI</fullName>
    </customValue>
    <customValue>
        <fullName>Regolamentato</fullName>
    </customValue>
    <customValue>
        <fullName>Salvaguardia</fullName>
    </customValue>
    <customValue>
        <fullName>STGM</fullName>
    </customValue>
    <masterLabel>Mercato</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SalesChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telefono</fullName>
    </customValue>
    <customValue>
        <fullName>Back office</fullName>
    </customValue>
    <customValue>
        <fullName>Sportello</fullName>
    </customValue>
    <customValue>
        <fullName>HC Point</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita Condomini</fullName>
    </customValue>
    <customValue>
        <fullName>Vendita TopBusiness</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie SME</fullName>
    </customValue>
    <customValue>
        <fullName>Agenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Punti Hera</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Teleselling Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Associazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Consip</fullName>
        <isActive>false</isActive>
        <label>Consip</label>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <isActive>false</isActive>
        <label>Reseller</label>
    </customValue>
    <description>Canale vendita associato all&apos;utente</description>
    <masterLabel>Canale Vendita</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_VoltageLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AAT</fullName>
    </customValue>
    <description>Livello Tensione</description>
    <masterLabel>Livello Tensione</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_SRV_SaleServiceItemTst.cls
/**
* Header of the class "HDT_SRV_SaleServiceItemTst"
* @author: Luca Belometti WR (luca.belometti@webresults.it)
* @version 1.0
* @description: Apex Test Class of the relative ApexClass "HDT_SRV_SaleServiceItem"
* @history
* Created: 2021-09-15
* Modified By:
* Luca Belometti WR (luca.belometti@webresults.it) - Updated the class with the new methods - 25/10/2021
**/

@IsTest
public with sharing class HDT_SRV_SaleServiceItemTst {
private static HDT_UTL_Constants constants = new HDT_UTL_Constants();
@TestSetup
static void makeData(){
    HDT_UTL_DataFactoryTst.pClickInstance();
    HDT_UTL_DataFactoryTst.pClickOrderPhase();
    Id adminUserProfileId=HDT_UTL_DataFactoryTst.getProfileId(constants.SYSTEM_ADMINISTRATOR_NAME);
    User internalUser=HDT_UTL_DataFactoryTst.createInternalUser(adminUserProfileId, false);
    internalUser.UserPermissionsMarketingUser=true;
    insert internalUser;

    List<Account> accList=HDT_UTL_DataFactoryTst.createAccountResidenziale(1, false, 'HERA COMM', 'D1 - Persona fisica', 'Enti');
    accList[0].FiscalCode__c = 'RSSMRA80A01F839W';
    accList[0].VATNumber__c = 'RSSMRA80A01F839W';
    accList[0].CustomerCode__c = 'uniqueTest';
    accList[0].CustomerType__c = 'Persona Fisica'; 
    insert accList;
    HDT_UTL_DataFactoryTst.createContact(1,true,accList[0].Id);
    HDT_UTL_DataFactoryTst.createBillingProfile(1, true, accList[0].Id);
    List<Sale__c> saleList = HDT_UTL_DataFactoryTst.createSale(1, true, accList[0].Id, 'Bozza');
    Test.setCreatedDate(saleList[0].Id,System.now().addDays(-30));
    List<Opportunity> oppList = HDT_UTL_DataFactoryTst.createOpportunity(1, false);
    oppList[0].Sale__c= saleList[0].Id;
    insert oppList;
    List<ServicePoint__c> spList = HDT_UTL_DataFactoryTst.createServicePoint(1, false);
    spList[0].MeterStatus__c = 'Bozza';
    spList[0].AnnualConsumptionStandardM3__c = 10;
    spList[0].CommoditySector__c = 'Energia Elettrica';
    insert spList;
    List<Order> orders =  HDT_UTL_DataFactoryTst.createOrder(1, false, accList[0].id, 'Bozza');
    orders[0].ServicePoint__c = spList[0].id;
    orders[0].VoltageLevel__c ='MT';
    orders[0].MarketOrigin__c ='Libero';
    orders[0].PowerRequested__c = 50;
    orders[0].PowerCommitted__c = 45;
    orders[0].IsWinback__c = false;
    orders[0].Channel__c = 'test';
    //orders[0].ContractReference__c = contracts[0].id;
    orders[0].SAPImplantCode__c = '';
    insert orders;
    HDT_UTL_DataFactoryTst.createLead(1, true);
    



    List<wrts_prcgvr__Activity__c> actCust = HDT_UTL_DataFactoryTst.createActivityCustom(1, false, accList[0].Id);
    actCust[0].Order__c = orders[0].id;
    actCust[0].wrts_prcgvr__Status__c = 'Creata';
    actCust[0].NewEmail__c = 'yes@no.it';
    actCust[0].NewMobile__c = '3334441122';
    actCust[0].DiscardCategory__c = 'Anonima';
    //actCust[0].Case__c = cases[0].id;
    insert actCust;        

    HDT_WebServiceConfiguration__c wsConf=new HDT_WebServiceConfiguration__c();
    wsConf.name='CampagenDmDmpData';
    wsConf.Endpoint__c='https://integration-ts.gruppohera.it/dev/salesforce-api-exp/api/data-management/files';
    wsConf.Method__c='POST';
    wsConf.User__c='MulesoftSalesforceUser';
    insert wsConf;

    HDT_UTL_DataFactoryTst.createWebServiceCredential('testUser', '12345', 'usernameTest');
    }


    @isTest
    public static void testCheckAccessInit() {

        boolean finito = false;

        Test.startTest();

        User tUser=[SELECT Id, FirstName
                    FROM USER
                    WHERE UserPermissionsMarketingUser=true AND IsActive=true AND CreatedDate = TODAY
                    LIMIT 1];

        System.runAs(tUser){
            HDT_SRV_SaleServiceItem testClass = new HDT_SRV_SaleServiceItem();


            testClass.checkAccessInit('Opportunity__c', 'create');

        }
        
        Test.stopTest();
        finito = true;
        System.assertEquals(true, finito, 'Test not finished');
        System.assertNotEquals(false, finito, 'Test not finished');
    }


    @isTest
    public static void testCheckReadAccess() {

        boolean finito = false;

        Test.startTest();

        User tUser=[SELECT Id, FirstName
                    FROM USER
                    WHERE UserPermissionsMarketingUser=true AND IsActive=true AND CreatedDate = TODAY
                    LIMIT 1];

        System.runAs(tUser){
            HDT_SRV_SaleServiceItem testClass = new HDT_SRV_SaleServiceItem();


            testClass.checkReadAccess('Opportunity__c');

        }
        
        Test.stopTest();
        finito = true;
        System.assertEquals(true, finito, 'Test not finished');
        System.assertNotEquals(false, finito, 'Test not finished');
    }


    @isTest
    public static void testCheckCreateAccess() {

        boolean finito = false;

        Test.startTest();

        User tUser=[SELECT Id, FirstName
                    FROM USER
                    WHERE UserPermissionsMarketingUser=true AND IsActive=true AND CreatedDate = TODAY
                    LIMIT 1];

        System.runAs(tUser){
            HDT_SRV_SaleServiceItem testClass = new HDT_SRV_SaleServiceItem();


            testClass.checkCreateAccess('Opportunity__c');

        }
        
        Test.stopTest();
        finito = true;
        System.assertEquals(true, finito, 'Test not finished');
        System.assertNotEquals(false, finito, 'Test not finished');
    }


    @IsTest
    static void testCreateRecord(){

        User tUser=[SELECT Id, FirstName
        FROM USER
        WHERE UserPermissionsMarketingUser=true AND IsActive=true AND CreatedDate = TODAY
        LIMIT 1];
        
        Test.startTest();
        System.runAs(tUser){
            List<ServicePoint__c> spRetrieved = [SELECT id FROM ServicePoint__c LIMIT 1];
            List<Sale__c> saleRetrieved = [SELECT id FROM Sale__c LIMIT 1];
            Map<String,String> mapStrings = New Map<String,String>();
            //mapStrings.put('Test', 'Test');
            HDT_SRV_SaleServiceItem testClass = new HDT_SRV_SaleServiceItem();
            testClass.createRecord(spRetrieved[0],saleRetrieved[0],mapStrings);
            
        }
        Test.stopTest();
        List<SaleServiceItem__c> testSize = [SELECT Id FROM SaleServiceItem__c];

        System.assertNotEquals(testSize.size() == 0, true, 'The method correctly created a record of SaleServiceItem__c');
        System.assertEquals(testSize.size() > 0, true, 'The method correctly created a record of SaleServiceItem__c');
    }

    @IsTest
    static void testDeleteRecords(){
        User tUser=[SELECT Id, FirstName
        FROM USER
        WHERE UserPermissionsMarketingUser=true AND IsActive=true AND CreatedDate = TODAY
        LIMIT 1];
        
        Test.startTest();
        System.runAs(tUser){
            List<SaleServiceItem__c> ssiRetrieved = [SELECT Id FROM SaleServiceItem__c LIMIT 1];
            HDT_SRV_SaleServiceItem testClass = new HDT_SRV_SaleServiceItem();
            testClass.deleteRecords(ssiRetrieved);

        }
        Test.stopTest();

        List<SaleServiceItem__c> testSize = [SELECT Id FROM SaleServiceItem__c];

        System.assertEquals(testSize.size() == 0, true, 'The method correctly deleted a record of SaleServiceItem__c');
        System.assertNotEquals(testSize.size() > 0, true, 'The method correctly deleted a record of SaleServiceItem__c');
        
    }


    
    @IsTest
    static void testGroupRecordsByOpportunityNull(){
        User tUser=[SELECT Id, FirstName
        FROM USER
        WHERE UserPermissionsMarketingUser=true AND IsActive=true AND CreatedDate = TODAY
        LIMIT 1];
        List<List<SaleServiceItem__c>> returnedList = new List<List<SaleServiceItem__c>>();

        
        Test.startTest();
        System.runAs(tUser){
            List<Opportunity> oppRetrieved = [SELECT Id FROM Opportunity LIMIT 1];
            List<ServicePoint__c> spRetrieved = [SELECT id FROM ServicePoint__c LIMIT 1];
            List<Sale__c> saleRetrieved = [SELECT id FROM Sale__c LIMIT 1];
            Map<String,String> mapStrings = New Map<String,String>();
            HDT_SRV_SaleServiceItem testClass = new HDT_SRV_SaleServiceItem();

            testClass.createRecord(spRetrieved[0],saleRetrieved[0],mapStrings);

            List<SaleServiceItem__c> ssiRetrieved = [SELECT Id,Opportunity__c FROM SaleServiceItem__c LIMIT 1];
             returnedList = testClass.groupRecordsByOpportunity(oppRetrieved, ssiRetrieved);

        }
        

        System.assertEquals(true,returnedList.size() == 0, 'The method correctly returned a list of SaleServiceItem__c null');
        System.assertNotEquals(true,returnedList.size() > 0, 'The method correctly a list of SaleServiceItem__c null');
        Test.stopTest();
        
    }
}