force-app/main/default/objects/Account/fields/CustomerLifeCycleWaste__c.field-meta.xml
<CustomField>
    <fullName>CustomerLifeCycleWaste__c</fullName>
    <description>KPI Customer Life Cycle</description>
    <label>Customer Life Cycle Ambiente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CustomerLifeCycle</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Punto di fornitura</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CustomerLifeCycle.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ENGAGEMENT</fullName>
    </customValue>
    <customValue>
        <fullName>GROWTH</fullName>
    </customValue>
    <customValue>
        <fullName>LEAVING</fullName>
    </customValue>
    <customValue>
        <fullName>LOST</fullName>
    </customValue>
    <customValue>
        <fullName>ONBOARDING</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECT</fullName>
    </customValue>
    <customValue>
        <fullName>USAGE</fullName>
    </customValue>
    <customValue>
        <fullName>WELCOME</fullName>
    </customValue>
    <masterLabel>Customer Life Cycle</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_BA_CustomerLifeCycleTst.cls
@isTest
public with sharing class HDT_BA_CustomerLifeCycleTst {
    @TestSetup
    static void makeData(){
        List<Account> accounts = HDT_UTL_DataFactoryTst.createAccountResidenziale(2, false, 'HERA COMM', 'Persona Fisica', 'Famiglie');
        accounts[1].CustomerLifeCycleWaste__c = 'ONBOARDING';
        insert accounts;

        List<ServicePoint__c> points = HDT_UTL_DataFactoryTst.createServicePoint(3, false);
        points[0].CommoditySector__c = 'Gas';
        points[1].CommoditySector__c = 'Ambiente';
        points[2].CommoditySector__c = 'Acqua';
        insert points;

        List<Contract> contracts = HDT_UTL_DataFactoryTst.createContract(3, false, accounts[0].Id);
        contracts[0].ServicePoint__c = points[0].Id;
        contracts[0].CustomerSignedDate = Date.today().addDays(-1);
        contracts[0].StartDate = Date.today().addDays(-1);
        contracts[0].EndDate = Date.today().addDays(1);
        contracts[1].ServicePoint__c = points[1].Id;
        contracts[1].CustomerSignedDate = Date.today().addDays(-2);
        contracts[1].StartDate = Date.today().addDays(2);
        contracts[1].EndDate = Date.today().addDays(4);
        contracts[1].AccountId = accounts[1].Id;
        contracts[2].ServicePoint__c = points[2].Id;
        contracts[2].CustomerSignedDate = Date.today().addDays(-2);
        contracts[2].StartDate = Date.today().addDays(2);
        contracts[2].EndDate = Date.today().addDays(4);
        insert contracts;

        Case caso = HDT_UTL_DataFactoryTst.createCase(1, false, accounts[0].Id, null, null, contracts[0].Id, null)[0];
        insert caso;
    }

    @isTest
    private static void executeBatch() {
        Test.startTest();
        Database.executeBatch(new HDT_BA_CustomerLifeCycle());
        Test.stopTest();
    }
}