force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <description>Codice Fiscale del cliente</description>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Partita Iva</description>
    <label>Partita Iva</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingProfile__c/BillingProfile__c.object-meta.xml
<CustomObject>
    <label>Billing Profile</label>
    <nameField>
        <displayFormat>BP-{00000000}</displayFormat>
        <label>Billing Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status; Ereditato da SAP</description>
    <label>Status del Profilo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CancellationHerokuPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>CancellationHerokuPracticeCode__c</fullName>
    <label>Annullamento/Ripensamento - Prat. Heroku</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CancellationNote__c.field-meta.xml
<CustomField>
    <fullName>CancellationNote__c</fullName>
    <description>Note Anullamento</description>
    <label>Note Annullamento/Ripensamento</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/CausalCode__c.field-meta.xml
<CustomField>
    <fullName>CausalCode__c</fullName>
    <label>Codice Causale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare un contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DiscardReason__c.field-meta.xml
<CustomField>
    <fullName>DiscardReason__c</fullName>
    <label>Causale Ultimo Scarto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DistributorPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>DistributorPracticeCode__c</fullName>
    <label>Codice Pratica Distributore</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Data decorrenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/EstimateAmount__c.field-meta.xml
<CustomField>
    <fullName>EstimateAmount__c</fullName>
    <label>Importo Preventivo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalUserCompany__c.field-meta.xml
<CustomField>
    <fullName>ExternalUserCompany__c</fullName>
    <label>Società utente esterno</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/HerokuPracticeCode__c.field-meta.xml
<CustomField>
    <fullName>HerokuPracticeCode__c</fullName>
    <label>Codice Pratica Heroku</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsTechnicalTransfer__c.field-meta.xml
<CustomField>
    <fullName>IsTechnicalTransfer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo per identificare se si tratta di un Switch In Con Voltura Tecnica</description>
    <label>Voltura Tecnica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>Dati discordanti</fullName>
            </value>
            <value>
                <fullName>Dati Tecnici Ricevuti</fullName>
            </value>
            <value>
                <fullName>Errore invio a DL/SII</fullName>
            </value>
            <value>
                <fullName>Errore lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Errore tecnico invio a SAP</fullName>
            </value>
            <value>
                <fullName>Esito KO da DL</fullName>
            </value>
            <value>
                <fullName>Esito KO da SII</fullName>
            </value>
            <value>
                <fullName>Esito OK da DL</fullName>
            </value>
            <value>
                <fullName>Esito OK da SII</fullName>
            </value>
            <value>
                <fullName>Flusso bloccato in assenza del precedente</fullName>
            </value>
            <value>
                <fullName>Inviare preventivo</fullName>
            </value>
            <value>
                <fullName>Ripensamento - Esito KO da SII</fullName>
            </value>
            <value>
                <fullName>Ripensamento - Esito OK da SII</fullName>
            </value>
            <value>
                <fullName>Ripensamento - Inviato al SII</fullName>
            </value>
            <value>
                <fullName>Ripensato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PrecheckReasonSII__c.field-meta.xml
<CustomField>
    <fullName>PrecheckReasonSII__c</fullName>
    <label>Causale Precheck al SII</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PrecheckResultSII__c.field-meta.xml
<CustomField>
    <fullName>PrecheckResultSII__c</fullName>
    <label>Esito Precheck al SII</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/QuotationType__c.field-meta.xml
<CustomField>
    <fullName>QuotationType__c</fullName>
    <label>Tipo Preventivo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/RemiCode__c.field-meta.xml
<CustomField>
    <fullName>RemiCode__c</fullName>
    <label>Codice REMI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SapContractActivationDate__c.field-meta.xml
<CustomField>
    <fullName>SapContractActivationDate__c</fullName>
    <label>Data Attivazione Contratto SAP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Codice Service Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TecnicalPhase__c.field-meta.xml
<CustomField>
    <fullName>TecnicalPhase__c</fullName>
    <description>Campo Tecnico di appoggio per la gestione del doppio cambio di fase.</description>
    <label>Fase Tecnica</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TrackingDiscardPhase__c.field-meta.xml
<CustomField>
    <fullName>TrackingDiscardPhase__c</fullName>
    <description>&quot;Conterrà la fase di tracciamento di Heroku che sarà filtrata nelle dashboard scarti&quot;</description>
    <label>Fase tracciamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ValidityDateEstimate__c.field-meta.xml
<CustomField>
    <fullName>ValidityDateEstimate__c</fullName>
    <label>Data Validita Preventivo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/VATNumberUdb__c.field-meta.xml
<CustomField>
    <fullName>VATNumberUdb__c</fullName>
    <label>Paretita iva Udb</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/WorkExecutionTime__c.field-meta.xml
<CustomField>
    <fullName>WorkExecutionTime__c</fullName>
    <label>Tempo Esecuzione Lavori</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/HDT_RT_CambioOfferta.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_CambioOfferta</fullName>
    <active>true</active>
    <label>Cambio Offerta</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_ConnessioneConAttivazione.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_ConnessioneConAttivazione</fullName>
    <active>true</active>
    <label>Connessione con Attivazione</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_SwitchIn.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_SwitchIn</fullName>
    <active>true</active>
    <description>Record type per gli ordini di SwitchIn</description>
    <label>SwitchIn</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_TemporaneaNuovaAtt.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_TemporaneaNuovaAtt</fullName>
    <active>true</active>
    <description>Record type per gli ordini di Temporanea Nuova Attivazione</description>
    <label>Temporanea Nuova Attivazione</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Order/recordTypes/HDT_RT_VolturaConSwitch.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_VolturaConSwitch</fullName>
    <active>true</active>
    <label>Voltura Con Switch</label>
    </picklistValues>
</RecordType>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributore</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Necessario inserire un Account Distributore</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HDT_RT_Distributore</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Points</relationshipLabel>
    <relationshipName>ServicePoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/RemiCode__c.field-meta.xml
<CustomField>
    <fullName>RemiCode__c</fullName>
    <description>Cabina di REgolazione e MIsura (REMI) è il punto fisico di congiunzione tra le reti.</description>
    <label>Codice REMI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/ServicePointCode__c.field-meta.xml
<CustomField>
    <fullName>ServicePointCode__c</fullName>
    <label>Service Point Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Impianto compl. in funzione</fullName>
            </value>
            <value>
                <fullName>Interruzione avviata</fullName>
            </value>
            <value>
                <fullName>Impianto parzialmente chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto compl. chiuso</fullName>
            </value>
            <value>
                <fullName>Impianto in attivazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_SRV_SalesHandler.cls
/**
* @author Andrei Necsulescu (andrei.necsulescu@webresults.it)
* @date 13/04/2021
* @description HDT_SRV_SalesHandler - Class that holds business logic for MrrRequest Webservice
* @history Inserire Nome Cognome – Data Modifica – Descrizione della modifica
*/

public with sharing class HDT_SRV_SalesHandler {

    /**​
    * @author Andrei Necsulescu (andrei.necsulescu@webresults.it)​
    * @date 13/04/2021
    * @description HDT_SRV_SalesHandler.manageSalesProcessCategory() – manage the requests of process category "sales"
    * @param request The request to be processed
    * @param mrrResponseItem the already initialized response item that needs to be returned at the end of the execution
    * @return the response item containing the result of the executed operations
    */

    /**@frpanico 25/10/2021
     * Added class instance
     */
    private static HDT_SRV_VoltureChangeManager voltureChangeSrv = new HDT_SRV_VoltureChangeManager();
    private static Set<String> moveOutProcesses = new Set<String>{'Cambio Uso','Voltura','Cambio Offerta'};

    public  HDT_WRP_MrrResponse.HDT_WRP_Response manageSalesProcessCategory(HDT_WRP_MrrRequest.HDT_WRP_Request request, HDT_WRP_MrrResponse.HDT_WRP_Response mrrResponseItem) {
        
        HDT_WRP_MrrResponse.HDT_WRP_Object responseObject = new HDT_WRP_MrrResponse.HDT_WRP_Object();

        HDT_WRP_MrrResponse.HDT_WRP_Field responseField = new HDT_WRP_MrrResponse.HDT_WRP_Field();
        HDT_WRP_MrrResponse.HDT_WRP_Field responseFieldError = new HDT_WRP_MrrResponse.HDT_WRP_Field();

        HDT_QR_Order orderQr = new HDT_QR_Order();
        HDT_SRV_Order orderSrv = new HDT_SRV_Order();
        HDT_WRP_MrrRequest.HDT_WRP_Header header = request.header;
		Map<String,String> mapRequestFields = new Map<String,String>();

        switch on header.requestType {
            when 'NOTIF_ES'{
                String activityName;
                if (request.objects.get(0).fields.get(0) != null) {
				
                    For(HDT_WRP_MrrRequest.HDT_WRP_Field field : request.objects.get(0).fields){
                        if(mapRequestFields.get(field.name) == null){
                            mapRequestFields.put(field.name,field.value);
                        }
                        
                    }

                    if (mapRequestFields.get('ATTIVITA') != null) {
                        activityName = mapRequestFields.get('ATTIVITA');
                        switch on activityName{
                            when 'Gestione Switch in Ripristinatorio'{
                                HDT_UTL_ActivityCustom.createActivityWithParams(new Map<String,String>{
                                    'RecordTypeDeveloperName' => 'HDT_RT_AttivitaGestionali',
                                    'Type__c'                 => 'Gestione Switch in Ripristinatorio',
                                    'Status__c'               => 'Creata',
                                    'ServicePointCode__c'     => mapRequestFields.get('COD_PDR'),
                                    'FiscalCode__c'           => mapRequestFields.get('CODICE_FISCALE'),
                                    'VATNumber__c'            => mapRequestFields.get('PIVA'),
                                    'EffectiveDate__c'        => mapRequestFields.get('DATA_DECORRENZA'),
                                    'HerokuPracticeCode__c'   => mapRequestFields.get('COD_PRAT_UTENTE')
                                });
                            }
                        }
                    }
                    if (mapRequestFields.get('METHOD')!= null && mapRequestFields.get('METHOD').equalsIgnoreCase('AggiornaAppuntamento')){
                        HDT_SRV_AppointmentAgenda agendaService = new HDT_SRV_AppointmentAgenda();
                        Map<String,String> clonedMapRequestFields = mapRequestFields.clone();
                        try{
                            clonedMapRequestFields.put('PROCESS_CATEGORY','');
                            for (HDT_WRP_MrrRequest.HDT_WRP_Field field : header.fields){
                                if (field.name.equals('PROCESS_CATEGORY')){
                                    clonedMapRequestFields.put(field.name,field.value);
                                }
                            }
                        }catch (Exception e){
                            throw new HDT_WS_MrrRequest.CustomMessageException(e.getMessage());
                        }
                        String responseMethod = agendaService.handleAppointmentUpdate(clonedMapRequestFields);
                        if (String.isNotEmpty(responseMethod)){
                            throw new HDT_WS_MrrRequest.CustomMessageException(responseMethod);
                        }
                        responseField.fieldType = 'TEXT';
                    	responseField.name = 'ESITO';
                    	responseField.value = 'OK';
                    }else if(mapRequestFields.get('RECORD_ID')!= null && mapRequestFields.get('FASE')!= null){
                        //EVERIS: START ANNULLAMENTO/RIPENSAMENTO
                        String recordId = mapRequestFields.get('RECORD_ID');
                        Order ordRetrieved;
                        if(recordId instanceOf Id){
                            ordRetrieved = orderQr.getRecordByOrderId(recordId)[0];
                        }
                        else {
                            ordRetrieved = orderQr.getRecordByOrderNumber(mapRequestFields.get('RECORD_ID'))[0];
                        }

                        String previousPhase = ordRetrieved.Phase__c;
                        String nextPhase = mapRequestFields.get('FASE');
                        String finalCancellationPhase = '';
                        //EVERIS: EMD ANNULLAMENTO/RIPENSAMENTO
                        //EVERIS: Gestione Scarti SAP
                        HDT_UTL_Scarti.handleHerokuResponse(ordRetrieved.Id, activityName, nextPhase);
                        Order ord = new Order();
                        ord.Id = ordRetrieved.Id;
                        ord.Phase__c = mapRequestFields.get('FASE');
                        //START>> 26/07/2021 costanzo.lomele@webresults.it - nuovi sviluppi cb scarti, attività anonime
                        ord.ExternalUserCompany__c = mapRequestFields.get('CMP');
                        //END>> 26/07/2021 costanzo.lomele@webresults.it - nuovi sviluppi cb scarti, attività anonime

                        switch on mapRequestFields.get('FASE') {
                            when 'Ammissibilità KO' {
                                ord.DiscardReason__c = mapRequestFields.get('DES_ERR_AEEG');
                                ord.CausalCode__c = mapRequestFields.get('CODERR');
                                ord.CausalCode__c = mapRequestFields.get('CODERR_AEEG');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.Description = mapRequestFields.get('ANNOTAZIONI');

                                 if((ord.CausalCode__c == '032' || ord.CausalCode__c == '033')
                                     && (ordRetrieved.ProcessType__c == 'Subentro Gas' 
                                         || ordRetrieved.ProcessType__c == 'Prima Attivazione In delibera'
                                         || ordRetrieved.ProcessType__c == 'Prima Attivazione Fuori delibera'
                                 )){
                                     ord.TecnicalPhase__c = 'Annullato';
                                     ord.Status = 'Annullato';
                                 }
                            }
                            when 'Ammissibilità OK' {

                                /**@frpanico 26/10/2021
                                 * Cambio Voltura - RN008 "Voltura con Switch"
                                 */
                                if(ordRetrieved.ProcessType__c.equalsIgnoreCase('Voltura con Switch'))
                                {
                                    voltureChangeSrv.handleAmmissibilityCheck(mapRequestFields, ordRetrieved);
                                }

                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.CausalCode__c = mapRequestFields.get('COD_FLUSSO');


                                if( mapRequestFields.get('DES_ERR_AEEG') != null) {
                                    ord.DiscardReason__c = mapRequestFields.get('DES_ERR_AEEG');
                                    ord.CausalCode__c = mapRequestFields.get('CODERR_AEEG');
                                } else {
                                    ord.CausalCode__c = mapRequestFields.get('COD_FLUSSO');
                                }
                                //String workExecutionTime =mapRequestFields.get('TEMP_ES_PREV');
                                if(String.isNotBlank(mapRequestFields.get('TEMP_ES_PREV')) && mapRequestFields.get('TEMP_ES_PREV').isNumeric()){
                                    ord.WorkExecutionTime__c = Decimal.valueOf(mapRequestFields.get('TEMP_ES_PREV'));
                                }

                                if (String.isNotBlank(mapRequestFields.get('IMP_PREV_DIST'))) {
                                    ord.EstimateAmount__c = Decimal.valueOf(mapRequestFields.get('IMP_PREV_DIST'));
                                    Boolean isDispatcherInMtd= HDT_UTL_QuoteManagement.checkLocalDispatcher(ord.ServicePoint__r.Distributor__r.Name);
                                    Integer validityDateDelay=isDispatcherInMtd ? 90 : 30; //ExtraRete? 30 : InRete? 90 : AAA? 180 : null; Manca caso AAA
                                    ord.QuotationType__c='Predeterminabile';
                                    switch on mapRequestFields.get('TIPO_INTERVENTO') {
                                        when 'Attivazione', 'Lavoro Semplice' {
                                            ord.ValidityDateEstimate__c=Date.today().addDays(validityDateDelay);
                                        }
                                    }
                                    
                                }else{
                                    switch on mapRequestFields.get('TIPO_INTERVENTO') {
                                        when 'Lavoro Semplice' {
                                            ord.QuotationType__c='Rapido';
                                        }
                                        when 'A Preventivo', 'Lavoro Complesso'{
                                            ord.QuotationType__c='Analitico';
                                        }
                                    }
                                }

                                 if(ord.CausalCode__c == '034' 
                                     && (ordRetrieved.ProcessType__c == 'Subentro Gas' 
                                         || ordRetrieved.ProcessType__c == 'Prima Attivazione In delibera'
                                         || ordRetrieved.ProcessType__c == 'Prima Attivazione Fuori delibera'
                                 )){
                                     ord.TecnicalPhase__c = 'Annullato';
                                     ord.Status = 'Annullato';
                                     ord.Phase__c = 'Annullato'; //HRAWRM-460
                                 }
                            }
                            when 'Dati Tecnici Ricevuti'{
                                HDT_UTL_HandleTechnicalData utlTechData = new HDT_UTL_HandleTechnicalData();
                                utlTechData.sp = new ServicePoint__c(Id=ordRetrieved.ServicePoint__c);
                                switch on mapRequestFields.get('COD_FLUSSO'){
                                    when 'E154'{
                                        utlTechData.handleE154Flow(mapRequestFields, ord);
                                    }
                                    when 'E150F'{
                                        utlTechData.handleE150Flow(mapRequestFields, ord);
                                    }
                                    when '0351' {
                                        utlTechData.handle351Flow(mapRequestFields, ord);
                                    }
                                    when '0300' {
                                        utlTechData.handle300Flow(mapRequestFields, ord);
                                    }
                                }
                            }
                            when 'Errore tecnico invio a SAP', 'Flusso bloccato in assenza del precedente', 'Errore invio a DL/SII' {
                                system.debug('previousPhase '+previousPhase);
                                String finalPhase = ord.phase__c;
                                if('Errore tecnico invio a SAP'.equalsIgnoreCase(finalPhase)){
                                     finalPhase = 'Errore comunicazione SAP';
                                }
                            	ord.TrackingDiscardPhase__c = finalPhase;
                                ord.phase__c=previousPhase; //perchè queste 3 non sono ammesse nel campo phase__c
                                system.debug('phase__c '+ord.phase__c);
                                system.debug('TrackingDiscardPhase__c '+ord.TrackingDiscardPhase__c);
                            }
                            when 'Esito KO da DL' {
                                ord.DiscardReason__c = mapRequestFields.get('TESTO_ERRR');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.CausalCode__c = mapRequestFields.get('COD_FLUSSO');
                                ord.DiscardReason__c = mapRequestFields.get('DES_ERR_AEEG');
                                ord.Description = mapRequestFields.get('ANNOTAZIONI');
                            }
                            when 'Esito OK da DL' {
                                HDT_UTL_HandleTechnicalData utlTechData = new HDT_UTL_HandleTechnicalData();
                                utlTechData.sp = new ServicePoint__c(Id=ordRetrieved.ServicePoint__c);
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.SapContractActivationDate__c = mapRequestFields.get('DT_INIZIO_VERT') != null ? Date.valueOf(mapRequestFields.get('DT_INIZIO_VERT')) : null;
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                                ord.CausalCode__c = mapRequestFields.get('COD_FLUSSO');
                                
                                //Start HRAWRM-657 21/09/2021
                                List<Id> listRecType = new List<Id>();
                                Id rtTemporaryNewActivation        = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_TemporaneaNuovaAtt').getRecordTypeId();
                                Id rtConnectionwithActivation      = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_ConnessioneConAttivazione').getRecordTypeId();
                                listRecType.add(rtTemporaryNewActivation);
                                listRecType.add(rtConnectionwithActivation);
                                if (listRecType.contains(ord.recordtypeId )   ) {
                                    ord.ServicePointCode__c = mapRequestFields.get('POD');
                                    ord.ServicePoint__r.Name= mapRequestFields.get('POD');
                                    ord.ServicePoint__r.ServicePointCode__c = mapRequestFields.get('POD');
                                }
                                //End HRAWRM-657 21/09/2021
                                
                                
                                switch on mapRequestFields.get('COD_FLUSSO'){
                                    when 'E150F'{
                                        utlTechData.handleE150Flow(mapRequestFields, ord);
                                    }
                                    when '0300' {
                                        utlTechData.handle300Flow(mapRequestFields, ord);
                                    }
                                }
                            }
                            when 'Amm. Precheck KO SII' {
                                ord.PrecheckReasonSII__c = mapRequestFields.get('DES_ERR_ES');
                                ord.CausalCode__c = mapRequestFields.get('CODERR_ES');
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');

                                if(mapRequestFields.get('CODERR_ES') == '003' || mapRequestFields.get('CODERR_ES') == '103'){
                                    ord.IsTechnicalTransfer__c = true;
                                }
                            }
                            when 'Amm. Precheck OK SII' {
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                                ord.RemiCode__c = mapRequestFields.get('EXT_CABINA_REMI');
                                ord.VATNumberUdb__c = mapRequestFields.get('EXT_PIVA_DISTR');
                                if (ordRetrieved.PrecheckResultSII__c == null || ordRetrieved.PrecheckResultSII__c == '') {
                                    ord.PrecheckResultSII__c = 'OK';
                                }
                            }
                            when 'Esito KO da SII' {
                                ord.PrecheckReasonSII__c = mapRequestFields.get('TESTO_ERRR');
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
			                    ord.CausalCode__c = mapRequestFields.get('COD_FLUSSO');
                            }
                            when 'Esito OK da SII' {
                                ord.DistributorPracticeCode__c = mapRequestFields.get('COD_PRAT_DISTR');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
			                    ord.CausalCode__c = mapRequestFields.get('COD_FLUSSO');
                            }
                            when 'Annullamento - Inviato al DL/SII'{
                                //EVERIS: START ANNULLAMENTO/RIPENSAMENTO
                                if(previousPhase.indexOf('Ripensamento') >-1){
                                    nextPhase = 'Ripensamento - Inviato al SII';
                                }
                                ord.Phase__c = nextPhase;
                                //EVERIS: END ANNULLAMENTO/RIPENSAMENTO
                            }
                            when 'Annullamento - Ammissibilità OK', 'Annullamento - Ammissibilità KO' {
                                //EVERIS: START ANNULLAMENTO/RIPENSAMENTO
                                ord.CancellationHerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                                Datetime nowDate = Datetime.now();
                                String nowDateFormat = nowDate.format('dd/MM/yyyy h:mm a');
                                String cancellationNote = ordRetrieved.CancellationNote__c != null ? ordRetrieved.CancellationNote__c : '';
                                if(mapRequestFields.get('ANNOTAZIONI_ANN') != null && mapRequestFields.get('ANNOTAZIONI_ANN') != '')
                                {
                                    ord.CancellationNote__c = nowDateFormat + ': ' + mapRequestFields.get('ANNOTAZIONI_ANN') + '\n' + cancellationNote;
                                }
                                if(previousPhase.indexOf('Ripensamento') >-1){
                                    nextPhase = nextPhase.replace('Annullamento', 'Ripensamento');
                                }
                                ord.Phase__c = nextPhase;
                                //EVERIS: END ANNULLAMENTO/RIPENSAMENTO
                            }
                            when 'Esito OK da DL/SII'{
                                //EVERIS: START ANNULLAMENTO/RIPENSAMENTO
                                if(previousPhase.indexOf('Annullamento') > -1) {
                                    ord.Phase__c = 'Annullamento - ' + nextPhase;
                                    finalCancellationPhase = 'Annullato';
                                    Datetime nowDate = Datetime.now();
                                    String nowDateFormat = nowDate.format('dd/MM/yyyy h:mm a');
                                    String cancellationNote = ordRetrieved.CancellationNote__c != null ? ordRetrieved.CancellationNote__c : '';
                                    if(mapRequestFields.get('NOTE_ANN') != null && mapRequestFields.get('NOTE_ANN') != '')
                                    {
                                        ord.CancellationNote__c = nowDateFormat + ': ' + mapRequestFields.get('NOTE_ANN') + '\n' + cancellationNote;
                                    }
                                }else if(previousPhase.indexOf('Ripensamento') > -1) {
                                   	ord.Phase__c = 'Ripensamento - Esito OK da SII';
                                    finalCancellationPhase = 'Ripensato';
                                }
                                //EVERIS: END ANNULLAMENTO/RIPENSAMENTO
                            }
                            when 'Esito KO da DL/SII' {
                                //EVERIS: START ANNULLAMENTO/RIPENSAMENTO
                                if(previousPhase.indexOf('Annullamento') > -1) {
                                    ord.Phase__c = 'Annullamento - ' + nextPhase;
                                    Datetime nowDate = Datetime.now();
                                    String nowDateFormat = nowDate.format('dd/MM/yyyy h:mm a');
                                    String cancellationNote = ordRetrieved.CancellationNote__c != null ? ordRetrieved.CancellationNote__c : '';
                                    if(mapRequestFields.get('NOTE_ANN') != null && mapRequestFields.get('NOTE_ANN') != '')
                                    {
                                        ord.CancellationNote__c = nowDateFormat + ': ' + mapRequestFields.get('NOTE_ANN') + '\n' + cancellationNote;
                                    }
                                }else if(previousPhase.indexOf('Ripensamento') > -1) {
                                    ord.Phase__c = 'Ripensamento - Esito KO da SII';
                                }
                                //EVERIS: END ANNULLAMENTO/RIPENSAMENTO
                            }
                            when 'Errore lavorazione SAP' {
                                ord.DiscardReason__c = mapRequestFields.get('NOTE_ERR');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                            }
                            when 'Dati discordanti'{
                                ord.phase__c = mapRequestFields.get('FASE');
                                ord.DiscardReason__c = mapRequestFields.get('TESTO_ERR');
                                ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                            }
                            when 'Completata' {

                                Boolean redirectPreventivo = false;
                                switch on ordRetrieved.ProcessType__c{
                                    when 'Connessione con Attivazione', 'Temporanea - Nuova Attivazione', 'Attivazione con Modifica'{
                                        redirectPreventivo=true;
                                    }
                                }                            
                                //Start HRAWRM-657 21/09/2021
                                List<Id> listRecordType = new List<Id>();
                                Id rtSwitchIn           = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_SwitchIn').getRecordTypeId();
                                Id rtChangeOffer        = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_CambioOfferta').getRecordTypeId();
                                Id rtVultureWithSwitch  = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('HDT_RT_VolturaConSwitch').getRecordTypeId();
                                listRecordType.add(rtSwitchIn);
                                listRecordType.add(rtChangeOffer);
                                listRecordType.add(rtVultureWithSwitch);

                                if (!listRecordType.contains(ord.recordtypeId ) && String.isNotBlank(mapRequestFields.get('DT_CREA'))  ) {
                                    ord.EffectiveDate__c = date.valueOf( mapRequestFields.get('DT_CREA')); //? per tutti i processi tranne RecordType.Name in ('SwitchIn','Cambio Offerta','Voltura Con Switch')
                                }
                                //End HRAWRM-657 21/09/2021

                                if(ordRetrieved.Phase__c.equalsIgnoreCase('Dati Tecnici Ricevuti') && redirectPreventivo){
                                    ord.Phase__c = 'Inviare preventivo';
                                }else{
                                    /**@frpanico 04/01/2022
                                     * Aggiunto MoveOut
                                    */
                                    if(moveOutProcesses.contains(ordRetrieved.ProcessType__c))
                                    {
                                        HDT_UTL_ContractProcess.moveOut(ordRetrieved.Id, 'ContractReference__c');
                                    }
                                    ord.Description = mapRequestFields.get('NOTA_HK');
                                    ord.SAPImplantCode__c = mapRequestFields.get('ANLAGE');
                                    ord.OrderODV__c = mapRequestFields.get('VBELN');
                                    ord.SapContractCode__c = mapRequestFields.get('VERTRAG');
                                    ord.HerokuPracticeCode__c = mapRequestFields.get('COD_PRAT_UTENTE');
                                    ord.Status='Activated';
                                    
                                    if(mapRequestFields.get('VKONT') != null) {
                                        ord.ContractAccountCode__c = mapRequestFields.get('VKONT');

                                        BillingProfile__c billingProfile = new BillingProfile__c();
                                        billingProfile.Id = ordRetrieved.BillingProfile__c;
                                        billingProfile.ContractAccountCode__c = mapRequestFields.get('VKONT');
                                        
                                        HDT_SRV_BillingProfile billingProfileSrv = new HDT_SRV_BillingProfile();
                                        try{
                                            billingProfileSrv.updateRecord(billingProfile);
                                        }catch(Exception e){
                                            system.debug('Exception Update Billing Profile');
                                            throw new HDT_WS_MrrRequest.CustomMessageException('Error on Updating Billing Profile, VKONT Already not Unique - '+e.getMessage());
                                        }
                                    }
                                    HDT_UTL_HandleTechnicalData utlTechData = new HDT_UTL_HandleTechnicalData();
                                    utlTechData.sp = new ServicePoint__c(Id=ordRetrieved.ServicePoint__c);
                                    utlTechData.handleCompletata(mapRequestFields);
                                }
                            }
                            when 'Annullamento SII - Ricezione'{
                                /*@frpanico 16/12/2021
                                * Aggiunta CancellationRequestDate__c
                                * Utilizzato per la determinazione della 
                                * Funzionalita Clona
                                */
                                ord.CancellationRequestDate__c = System.today();
                                ord.CancellationReasonCode__c = mapRequestFields.get('COD_CAUSALE');
                                ord.CancellationNote__c = mapRequestFields.get('ANNOTAZIONI_ANN');
                                String annotazioni = ord.CancellationNote__c != null? ord.CancellationNote__c:'';
                                ord.CancellationNote__c = mapRequestFields.get('NOTE_ANN') +'\n' + annotazioni;
                                HDT_UTL_HerokuPostSalesManager utlClass = new HDT_UTL_HerokuPostSalesManager();
                                Order cancellationOrder = new Order();
                                cancellationOrder.Id = ord.Id;
                                utlClass.handlePassiveCancellation(cancellationOrder, 'Order', mapRequestFields.get('STORNO'), mapRequestFields.get('ATTIVITA'));
                            }
                        }

                        system.debug('cost2 '+ord.phase__c);
                        orderSrv.updateRecord(ord);
                    	responseField.fieldType = 'TEXT';
                    	responseField.name = 'ESITO';
                    	responseField.value = 'OK';

                        //EVERIS: START ANNULLAMENTO/RIPENSAMENTO
                        if (String.isNotBlank(finalCancellationPhase)) {
                            ord.Phase__c = finalCancellationPhase;
                            ord.Status = 'Completed';
                            updateFuture(JSON.serialize(ord));
                        }
                        //EVERIS: END ANNULLAMENTO/RIPENSAMENTO  
                    }else{
                        responseField.fieldType = 'TEXT';
                    	responseField.name = 'ESITO';
                    	responseField.value = 'OK';
                    }

                    responseObject.fields = new List<HDT_WRP_MrrResponse.HDT_WRP_Field>{responseField};
                    mrrResponseItem.objects.add(responseObject);
                    
                    RestContext.response.statusCode = 200;
                    
                } else {

                    responseField.fieldType = 'TEXT';
                    responseField.name = 'ESITO';
                    responseField.value = 'KO';

                    responseFieldError.fieldType = 'TEXT';
                    responseFieldError.name = 'ERROR_MESSAGE';
                    responseFieldError.value = 'There was an issue with your request message';

                    responseObject.fields = new List<HDT_WRP_MrrResponse.HDT_WRP_Field>{responseField, responseFieldError};
                    mrrResponseItem.objects.add(responseObject);

                    RestContext.response.statusCode = 400;

                }                        

            }

            when 'NOTIF_VAS'{
                HDT_UTL_NotifVas.handleVasNotify(request, mrrResponseItem);
            }
            when 'RICH_PASS' {

                if (request.objects.get(0).fields.get(0) != null){

                    responseField.fieldType = 'TEXT';
                    responseField.name = 'ESITO';
                    responseField.value = 'OK';
                    responseField.rds = '';
                    responseField.rdo = '';

                    responseObject.fields = new List<HDT_WRP_MrrResponse.HDT_WRP_Field>{responseField};
                    mrrResponseItem.objects.add(responseObject);
                    
                    RestContext.response.statusCode = 200;
                    
                } else {

                    responseField.fieldType = 'TEXT';
                    responseField.name = 'ESITO';
                    responseField.value = 'KO';

                    responseFieldError.fieldType = 'TEXT';
                    responseFieldError.name = 'ERROR_MESSAGE';
                    responseFieldError.value = 'There was an issue with your request message';

                    responseObject.fields = new List<HDT_WRP_MrrResponse.HDT_WRP_Field>{responseField, responseFieldError};
                    mrrResponseItem.objects.add(responseObject);

                    RestContext.response.statusCode = 400;

                }

            }
            when 'WSLead_Callback'{
                try {
                    List<String> listFieldsReq =new List<String>{'NOMEMACROACTIVITYEASYCIM'};
                    requiredFields(listFieldsReq, request);
                    RestContext.response.statusCode = 200; 
                    HDT_UTL_LeadProcess.formCallback(request, mrrResponseItem, responseObject);
                   
                  
                } 
                catch (Exception e) {
                    mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                }
                
            }
            when 'WSLead_Winback'{
                try {
                    List<String> listFieldsReq =new List<String>{'NOMEMACROACTIVITYEASYCIM'};
                    requiredFields(listFieldsReq, request);
                    RestContext.response.statusCode = 200;
                    HDT_UTL_LeadProcess.formWinback(request, mrrResponseItem, responseObject);
                  

                } 
                catch (Exception e) {
                    mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                }
            }
            when 'WSLead_CariBoll'{
                try {
                    List<String> listFieldsReq =new List<String>{'NOMEMACROACTIVITYEASYCIM'};
                    requiredFields(listFieldsReq, request);
                    RestContext.response.statusCode = 200;
                    HDT_UTL_LeadProcess.formCaricBoll(request, mrrResponseItem, responseObject);
                    
                } 
                catch (Exception e) {
                    mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                }
              
            }
            when 'WSLead_HVAC'{
                try {
                    List<String> listFieldsReq =new List<String>{'NOMEMACROACTIVITYEASYCIM'};
                    requiredFields(listFieldsReq, request);
                    RestContext.response.statusCode = 200; 
                    HDT_UTL_LeadProcess.formHvac(request, mrrResponseItem, responseObject);
                     
                } 
                catch (Exception e) {
                    mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                }

            }
            when 'WSLead_SOL'{
                try {
                    List<String> listFieldsReq =new List<String>{'NOMEMACROACTIVITYEASYCIM'};
                    requiredFields(listFieldsReq, request);
                    RestContext.response.statusCode = 200;
                    HDT_UTL_LeadProcess.formSol(request, mrrResponseItem, responseObject);
                  
                } 
                catch (Exception e) {
                    mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                }

            }
            when 'CMPDMP_PRV'{
               
                if (request.objects.get(0).fields.get(0) != null) {
                    List<String> listFieldsReq =new List<String>{'runId'};
                    try {
                        Map<String,String> localMapRequestFields =requiredFields(listFieldsReq, request);
                        HDT_BA_ConsentLead ba = new HDT_BA_ConsentLead(localMapRequestFields.get('runId')); 
                        Database.executeBatch(ba,1000);
                        RestContext.response.statusCode = 200;
                    }
                    catch (Exception e){
                        mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                      //  mapError('runId cannot be empty',responseField,responseFieldError,responseObject,mrrResponseItem);

                    }  
                }
            }

            when 'CMPDMP_ATTR'{
                if (request.objects.get(0).fields.get(0) != null ) {
                    List<String> listFieldsReq =new List<String>{'runId'};
                    Map<String,String> localMapRequestFields =requiredFields(listFieldsReq, request);
                    try {
                        HDT_BA_AttributesLead ba = new HDT_BA_AttributesLead(localMapRequestFields.get('runId')); 
                        Database.executeBatch(ba,1000);
                        RestContext.response.statusCode = 200;
                    }
                     catch (Exception e) {
                        mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                    }
                }
            }

            when 'SIE34_7'{
                if (request.objects.get(0).fields.get(0) != null ) {
                    List<String> listFieldsReq =new List<String>{'runId','updatedFrom'};
                    try {
                        Map<String,String> localMapRequestFields =requiredFields(listFieldsReq, request);
                        System.enqueueJob(new HDT_QBL_SIE34_7(localMapRequestFields.get('runId'),localMapRequestFields.get('updatedFrom'), 'SIE34_7'));
                        RestContext.response.statusCode = 200;
                    } catch (Exception e) {
                        mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                    }
                   
                }
            }
            when 'SIE34_6'{
                if (request.objects.get(0).fields.get(0) != null ) {
                    List<String> listFieldsReq =new List<String>{'runId','updatedFrom'};
                    try {
                        Map<String,String> localMapRequestFields =requiredFields(listFieldsReq, request);
                        System.enqueueJob(new HDT_QBL_SIE34_6(localMapRequestFields.get('runId'),localMapRequestFields.get('updatedFrom'), 'SIE34_6'));
                        RestContext.response.statusCode = 200;
                    } 
                    catch (Exception e) {
                        mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);

                    }       
                }
            }
            when 'SIE34_3'{
                //System.debug('SIE34');
                if (request.objects.get(0).fields.get(0) != null ) {
                    List<String> listFieldsReq =new List<String>{'runId','updatedFrom'};
                    try {
                        Map<String,String> localMapRequestFields =requiredFields(listFieldsReq, request);
                        System.enqueueJob(new HDT_QBL_SIE34_3(localMapRequestFields.get('runId'),localMapRequestFields.get('updatedFrom'), 'SIE34_3'));
                        RestContext.response.statusCode = 200;
                    } catch (Exception e) {
                        mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                    }
                   
                }
            }
            when 'SIE34_2'{
               
                if (request.objects.get(0).fields.get(0) != null ) {
                    List<String> listFieldsReq =new List<String>{'runId','updatedFrom'};
                    try {
                        Map<String,String> localMapRequestFields =requiredFields(listFieldsReq, request);
                        System.enqueueJob(new HDT_QBL_SIE34_2SME(localMapRequestFields.get('runId'),localMapRequestFields.get('updatedFrom'), 'SIE34_2'));
                        RestContext.response.statusCode = 200;
                    } 
                    catch (Exception e) {
                        mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);
                    }
                }
            }

            when 'SIE34_1'{
              
                if (request.objects.get(0).fields.get(0) != null ) {
                    List<String> listFieldsReq =new List<String>{'runId','updatedFrom'};
                    try {
                        Map<String,String> localMapRequestFields =requiredFields(listFieldsReq, request);
                        System.enqueueJob(new HDT_QBL_SIE34_1Gas(localMapRequestFields.get('runId'),localMapRequestFields.get('updatedFrom'), 'SIE34_1'));
                        RestContext.response.statusCode = 200;
                    } 
                    catch (Exception e) {
                        mapError(e.getMessage(),responseField,responseFieldError,responseObject,mrrResponseItem);

                    } 
                }
            }
            when else {

                responseField.fieldType = 'TEXT';
                responseField.name = 'ESITO';
                responseField.value = 'KO';

                responseFieldError.fieldType = 'TEXT';
                responseFieldError.name = 'ERROR_MESSAGE';
                responseFieldError.value = 'Unsupported requestType';

                responseObject.fields = new List<HDT_WRP_MrrResponse.HDT_WRP_Field>{responseField, responseFieldError};
                mrrResponseItem.objects.add(responseObject);

                RestContext.response.statusCode = 400;

            }
        }
        return mrrResponseItem;
    }
    
    //EVERIS: START ANNULLAMENTO/RIPENSAMENTO
    @Future
    private static void updateFuture(String inputString){
        Order recordOrder = (Order) JSON.deserialize(inputString, Order.class);
        HDT_UTL_DatabaseService.updateSObject(recordOrder);
    }
    //EVERIS: END ANNULLAMENTO/RIPENSAMENTO
    private static void mapError(String msg, HDT_WRP_MrrResponse.HDT_WRP_Field responseField,HDT_WRP_MrrResponse.HDT_WRP_Field responseFieldError,HDT_WRP_MrrResponse.HDT_WRP_Object responseObject,HDT_WRP_MrrResponse.HDT_WRP_Response mrrResponseItem){
        responseField.fieldType = 'TEXT';
        responseField.name = 'ESITO';
        responseField.value = 'KO';

        responseFieldError.fieldType = 'TEXT';
        responseFieldError.name = 'ERROR_MESSAGE';
        responseFieldError.value = msg;
        responseObject.fields = new List<HDT_WRP_MrrResponse.HDT_WRP_Field>{responseField, responseFieldError};
        mrrResponseItem.objects.add(responseObject);
        RestContext.response.statusCode = 400;

    }

    @TestVisible
    private static void updateServicePoint(ServicePoint__c sp){
        try{
            new HDT_SRV_ServicePoint().updateRecord(sp);
        }catch(Exception e){
           // system.debug('Exception Update ServicePoint');
            throw new HDT_WS_MrrRequest.CustomMessageException('Error on Updating ServicePoint - '+e.getMessage());
        }
    }
    @TestVisible
    private static Map<String,String> requiredFields(List<String> listFieldsReq,HDT_WRP_MrrRequest.HDT_WRP_Request request){
        Map<String,String> localMapRequestFields = new Map<String,String>();

        for(HDT_WRP_MrrRequest.HDT_WRP_Field field : request.objects.get(0).fields){ 
                localMapRequestFields.put(field.name,field.value);
        }
        for (String tempString : listFieldsReq) {
            if (localMapRequestFields.get(tempString)==null || String.isBlank(localMapRequestFields.get(tempString))) { 
                throw new HDT_WS_MrrRequest.CustomMessageException('Missing Required Field '+tempString);
            }
        }
        
        return localMapRequestFields;
    }

}