force-app/main/default/objects/Account/fields/IsDigitalMarking__c.field-meta.xml
<CustomField>
    <fullName>IsDigitalMarking__c</fullName>
    <description>Indica se il cliente ha una tra le nuove marcature previste per la Digital.</description>
    <formula>IF(
CASE(TEXT(CustomerMarking__c), 
&apos;D1 - Persona fisica&apos;, 1,
&apos;D2 - Ditta individuale&apos;, 1,
&apos;D3 - Azienda&apos;, 1,
&apos;D4 - Parti comuni&apos;, 1,
&apos;D5 - Condominio&apos;, 1,
&apos;D6 - Associazione&apos;, 1,
&apos;D7 - BP Doppio&apos;, 1,
&apos;D8 - Marcatura nulla&apos;, 1, 
0) = 1,
TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marcatura Digitale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsWrongFiscalData__c.field-meta.xml
<CustomField>
    <fullName>IsWrongFiscalData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Valorizzato a true inibisce qualsiasi azione sul cliente</description>
    <label>Dati fiscali errati</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HDT_UTL_ServiceCatalogFieldFilterTst.cls
/*
    @Author:        Davide Viola
    CreatedDate:    16/11/2021
*/

@isTest
public class HDT_UTL_ServiceCatalogFieldFilterTst {

    @TestSetup
    static void setup(){

        HDT_UTL_DataFactoryTst.createAccountBusiness(2, true, 'HERA COMM', 'Azienda', 'Aziende SME');
    }

    @isTest public static void testEvaluate(){

        Map<String, Object> argsMap = new Map<String, Object>();

        Account acc = [SELECT Id, IsDigitalMarking__c, IsWrongFiscalData__c FROM Account LIMIT 1];
        argsMap.put('record', acc);

        Test.startTest();

        HDT_UTL_ServiceCatalogFieldFilter servCatalFilter = new HDT_UTL_ServiceCatalogFieldFilter();
        Boolean res = servCatalFilter.evaluate(argsMap);
        
        Test.stopTest();

        System.assertEquals(res, False, 'Condizione verificata');
    }
}