force-app/main/default/objects/DocumentSelected__c/DocumentSelected__c.object-meta.xml
<CustomObject>
    <label>Documento selezionato</label>
    <nameField>
        <label>Nome Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documenti selezionati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentSelected__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <description>Data Emissione</description>
    <label>Data Emissione</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/HDT_SRV_Reimbursement.cls
public inherited sharing class HDT_SRV_Reimbursement {

    HDT_QR_Reimbursement reimbursementQr = new HDT_QR_Reimbursement();
    HDT_WS_Reimbursement reimbursementWs = new HDT_WS_Reimbursement();
    
    public Boolean checkDocumentDate(String recordId){

        List<DocumentSelected__c> documents = new List<DocumentSelected__c>();

        Boolean flag = false;

        documents = reimbursementQr.getDocumentSelectedByCaseId(recordId);

        for(DocumentSelected__c document : documents){

            if(document.IssueDate__c.addDays(20) < System.today()){

                flag = true;

            }


        }

        return flag;

    }


    public Boolean checkAccountBalance(String customerCode){

        JSONGenerator gen = JSON.createGenerator(true);
        String pretty;
        String result;
        Boolean flag = false;

        gen.writeStartObject();
        gen.writeStringField('codiceCliente', customerCode);
        gen.writeStringField('tipoEstrattoConto', 'ORDINARIO');
        gen.writeEndObject();

        pretty = gen.getAsString();

        System.debug('SRV_Reimbursement bodyRequest--> '+pretty);

        result = reimbursementWs.calloutAccountBalance(pretty);

        if(result == 'N'){

            flag = true;

        }

        return flag;


    }


}