force-app/main/default/objects/OperandTemplate__c/OperandTemplate__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione per la determinazione degli operandi di tempate nella funzionalità di configurazione offerta tecnica</description>
    <label>Template Operando</label>
    <nameField>
        <displayFormat>OTP-{00000000}</displayFormat>
        <label>Template Operando Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Operandi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OperandTemplate__c/fields/ContractTemplate__c.field-meta.xml
<CustomField>
    <fullName>ContractTemplate__c</fullName>
    <description>Campo di configurazione usato per l&apos;individuazione del Contract Template da usare per l&apos;ndividuazione dei correlati valori dei campi &quot;Operandi&quot;Tipologia&quot; ed &quot;Unita Prezzo&quot;durante la funzionalità di Configurazione Offerta Tecnica</description>
    <label>Template Contratto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperandTemplate__c/fields/Definition__c.field-meta.xml
<CustomField>
    <fullName>Definition__c</fullName>
    <description>Campo di configurazione usato per gestire i valori di Unità prezzo al Contract Template da usare durante la funzionalità di Configurazione Offerta Tecnica</description>
    <label>Definizione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperandTemplate__c/fields/Operands__c.field-meta.xml
<CustomField>
    <fullName>Operands__c</fullName>
    <description>Campo di configurazione usato per gestire i valori di Operandi legati al Contract Template da usare durante la funzionalità di Configurazione Offerta Tecnica</description>
    <label>Operandi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperandTemplate__c/fields/Typology__c.field-meta.xml
<CustomField>
    <fullName>Typology__c</fullName>
    <description>Campo di configurazione usato per gestire i valori di Tipologia al Contract Template da usare durante la funzionalità di Configurazione Offerta Tecnica</description>
    <label>Tipologia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DescriptionSAP__c.field-meta.xml
<CustomField>
    <fullName>DescriptionSAP__c</fullName>
    <description>Descrizione del prodotto come su DB SAP</description>
    <label>Descrizione SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RateCategory__c.field-meta.xml
<CustomField>
    <fullName>RateCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RateCategory</description>
    <label>Rate Template</label>
    <referenceTo>RateTemplate__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Stato</description>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullata</fullName>
            </value>
            <value>
                <fullName>Confermata</fullName>
            </value>
            <value>
                <fullName>In Sviluppo</fullName>
            </value>
            <value>
                <fullName>Vendibile</fullName>
            </value>
            <value>
                <fullName>Scaduta</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>la versione del dato record di Prodotto nella funzionalità di Configurazione Offerta Tecnica</description>
    <label>Versione</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateTemplate__c/RateTemplate__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione per la determinazione di Rete Category e Contract Template nella funzionalità di configurazione offerta tecnica</description>
    <label>Rate Template</label>
    <nameField>
        <label>Rate Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateTemplate__c/fields/ContractTemplate__c.field-meta.xml
<CustomField>
    <fullName>ContractTemplate__c</fullName>
    <description>Campo di configurazione usato per contenere i possibili Contract Template da usare durante la funzionalità di Configurazione Offerta Tecnica</description>
    <label>Template Contratto </label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateTemplate__c/fields/RateCategory__c.field-meta.xml
<CustomField>
    <fullName>RateCategory__c</fullName>
    <description>Campo di configurazione usato per l&apos;individuazione del Contract Template da usare durante la funzionalità di Configurazione Offerta Tecnica</description>
    <label>Rate Category </label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateTemplate__c/fields/ServiceProduct__c.field-meta.xml
<CustomField>
    <fullName>ServiceProduct__c</fullName>
    <label>Prodotto di servizio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateTemplate__c/fields/Visibile__c.field-meta.xml
<CustomField>
    <fullName>Visibile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visibile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TechnicalOffer__c/TechnicalOffer__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione per lafunzionalità di configurazione offerta tecnica</description>
    <label>Offerta Tecnica</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Offer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalOffer__c/fields/NameExternalId__c.field-meta.xml
<CustomField>
    <fullName>NameExternalId__c</fullName>
    <description>Campo di configurazione che indica il nome dell&apos;offerta tecnica come external id.</description>
    <externalId>true</externalId>
    <label>Offer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOffer__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo di configurazione usato per indicare il prodotto del rdato ecord di tale oggetto legato alla funzionalità dei Criteri di Eleggiblità</description>
    <label>Prodotto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.CategoryFamily__c</field>
            <operation>equals</operation>
            <value>Offerta Commerciale</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Technical Offer</relationshipLabel>
    <relationshipName>Technical_Offer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalOffer__c/fields/RateCategory__c.field-meta.xml
<CustomField>
    <fullName>RateCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Category</label>
    <referenceTo>RateTemplate__c</referenceTo>
    <relationshipLabel>Technical Offers</relationshipLabel>
    <relationshipName>TechnicalOffers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalOffer__c/fields/SapCode__c.field-meta.xml
<CustomField>
    <fullName>SapCode__c</fullName>
    <description>Campo di configurazione che indica il codice sap.</description>
    <label>Codice SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOffer__c/fields/ServiceProduct__c.field-meta.xml
<CustomField>
    <fullName>ServiceProduct__c</fullName>
    <label>Prodotto di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GAS_SB_A_SCONTI</fullName>
            </value>
            <value>
                <fullName>ELE_PREZZO</fullName>
            </value>
            <value>
                <fullName>GAS_BUSINESS</fullName>
            </value>
            <value>
                <fullName>ELE_DOMES</fullName>
            </value>
            <value>
                <fullName>ELE_ND_30KW</fullName>
            </value>
            <value>
                <fullName>ELE_ND_POTMASS</fullName>
            </value>
            <value>
                <fullName>GAS_DIFFUSI</fullName>
            </value>
            <value>
                <fullName>GAS_MULTISITO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalOffer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo di configurazione che indica lo stato dell&apos;offerta tecnica.</description>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Status OK</fullName>
            </value>
            <value>
                <fullName>Status KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalOffer__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <formula>Product__r.Version__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Versione</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/TechnicalOfferItem__c.object-meta.xml
<CustomObject>
    <label>Technical Offer Item</label>
    <nameField>
        <label>TechnicalOfferItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Offer Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalOfferItem__c/fields/Definition__c.field-meta.xml
<CustomField>
    <fullName>Definition__c</fullName>
    <description>Definizione dell&apos;Item Offerta tecnica</description>
    <label>Definizione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/FareType__c.field-meta.xml
<CustomField>
    <fullName>FareType__c</fullName>
    <description>la tipologia di tariffa</description>
    <label>Tipo Tariffa</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/FareTypeValue__c.field-meta.xml
<CustomField>
    <fullName>FareTypeValue__c</fullName>
    <description>Valore del Tipo Tariffa associato all&apos;item dell&apos;offerta tecnica</description>
    <label>Tipo Tariffa Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/G__c.field-meta.xml
<CustomField>
    <fullName>G__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo di configurazione che indica se l&apos;offerta è gestibile.</description>
    <label>G</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/InfoGroup__c.field-meta.xml
<CustomField>
    <fullName>InfoGroup__c</fullName>
    <description>Il gruppo</description>
    <label>Gruppo Info</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/InfoGroupValue__c.field-meta.xml
<CustomField>
    <fullName>InfoGroupValue__c</fullName>
    <description>Valore del Gruppo Info associato all&apos;item dell&apos;offerta tecnica</description>
    <label>Gruppo info Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/M__c.field-meta.xml
<CustomField>
    <fullName>M__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo tecnico di sviluppo</description>
    <label>M</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/NameExternalId__c.field-meta.xml
<CustomField>
    <fullName>NameExternalId__c</fullName>
    <description>Chiave esterna</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/Operand__c.field-meta.xml
<CustomField>
    <fullName>Operand__c</fullName>
    <description>Operando</description>
    <label>Operando</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/S__c.field-meta.xml
<CustomField>
    <fullName>S__c</fullName>
    <description>Campo di configurazione che indica lo Stato operando.</description>
    <label>S</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/TechnicalOffer__c.field-meta.xml
<CustomField>
    <fullName>TechnicalOffer__c</fullName>
    <description>Offerta Tecnica</description>
    <label>Offerta Tecnica</label>
    <referenceTo>TechnicalOffer__c</referenceTo>
    <relationshipLabel>Technical Offer Items</relationshipLabel>
    <relationshipName>RigheOffertaTecnica</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipologia</description>
    <label>Tipologia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalOfferItem__c/fields/V__c.field-meta.xml
<CustomField>
    <fullName>V__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo tecnico di sviluppo</description>
    <label>V</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HDT_TRH_ProductStObjTst.cls
@isTest
public class HDT_TRH_ProductStObjTst {

    @testSetup
    static void setup() {
        List<OperandTemplate__c> operandTemplateList = new List<OperandTemplate__c>();
        OperandTemplate__c op1 = new OperandTemplate__c(Operands__c = 'ES_ADG_GO', ContractTemplate__c = 'ZELE_PREZZO', Typology__c = 'PDISCNT', Definition__c = 'DESCR ES_ADG_GO');
        operandTemplateList.add(op1);
        insert operandTemplateList;

        List<RateTemplate__c> rateList = new List<RateTemplate__c>();
        RateTemplate__c rateTemplate = new RateTemplate__c(Name = 'EVVUD', ContractTemplate__c = 'ZELE_DOMES', ServiceProduct__c = 'ELE_DOMES', Visibile__c = true);
        rateList.add(rateTemplate);
        insert rateList;
    }

    @isTest
    static void beforeInsert(){

        Boolean finished = false;

        Test.startTest();

        Product2 p = new Product2();
        p.ProductCode = 'pCode01';
        p.Version__c = '01V1';
        p.Name = 'ExampleProduct';
        p.Family = Label.HDT_ProductFamilyTrigger;

        insert p;

        finished = true;

        Test.stopTest();

        System.assertEquals(true, finished, 'Test Not Ended');

    }

    @isTest
    static void beforeUpdate(){

        Boolean finished = false;

        Product2 p = new Product2();
        p.ProductCode = 'pCode01';
        p.Version__c = '01V1';
        p.Name = 'ExampleProduct';
        p.Family = Label.HDT_ProductFamilyTrigger;
        p.DescriptionSAP__c = 'descr';

        insert p;


        RateTemplate__c rate = [
            SELECT Id
            FROM RateTemplate__c
            WITH SECURITY_ENFORCED
            LIMIT 1    
        ];

        TechnicalOffer__c technicalOffer = new TechnicalOffer__c();
        technicalOffer.Name = p.ProductCode + ' [' + p.Version__c + '] [EVVUD]';
        technicalOffer.NameExternalId__c = technicalOffer.Name;
        technicalOffer.Product__c = p.Id;
        technicalOffer.RateCategory__c = rate.Id;
        technicalOffer.SapCode__c = '1010';
        technicalOffer.Status__c = 'Status OK';
        insert technicalOffer;

        List<TechnicalOfferItem__c> techOffeItems = new List<TechnicalOfferItem__c>();
        TechnicalOfferItem__c tecOffItem = new TechnicalOfferItem__c();
        tecOffItem.TechnicalOffer__c = technicalOffer.Id;
        tecOffItem.Type__c = 'PDISCNT';
        tecOffItem.Definition__c = 'DESCR ES_ADG_GO';
        tecOffItem.G__c = false;
        tecOffItem.V__c = false;
        tecOffItem.M__c = false;
        tecOffItem.S__c = null;
        tecOffItem.Operand__c = 'ES_ADG_GO';
        tecOffItem.FareType__c = 'TEST';
        tecOffItem.FareTypeValue__c = 'TEST';
        tecOffItem.InfoGroup__c = 'TEST';
        tecOffItem.InfoGroupValue__c = 'TEST';
        tecOffItem.NumericValue__c = '0.00001';
        tecOffItem.Flag__c = false;
        tecOffItem.PriceCode__c = 'TEST';
        tecOffItem.PriceCodeValue__c = 'TEST';
        tecOffItem.DiscountCode__c = 'TEST';
        tecOffItem.DiscountCodeValue__c = 'TEST';
        tecOffItem.StringValue__c = 'TEST';
        techOffeItems.add(tecOffItem);
        insert techOffeItems;

        Test.startTest();

        p.StartDate__c = Date.today().addDays(2);
        p.EndDate__c = Date.today().addDays(6);
        p.Status__c = 'Confermata';
        update p;

        finished = true;

        Test.stopTest();

        System.assertEquals(true, finished, 'Test Not Ended');

    }

    @isTest
    static void changeStatusHandlerNull(){

        Boolean finished = false;

        Product2 pOld = new Product2();
        pOld.Status__c = null;

        Product2 pNew = new Product2();
        pNew.Status__c = null;

        HDT_WRP_ProductStObjProcess.HDT_WRP_StatusResponse statusResponse;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        finished = true;

        System.assertEquals(true, finished, 'Test Not Ended');

    }

    @isTest
    static void changeStatusHandlerInDevelopment(){

        Boolean finished = false;

        Product2 pOld = new Product2();
        pOld.Status__c = Label.HDT_InDevelopment;

        Product2 pNew = new Product2();
        pNew.Status__c = Label.HDT_InDevelopment;

        HDT_WRP_ProductStObjProcess.HDT_WRP_StatusResponse statusResponse;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Confirmed;
        pOld.Family = Label.HDT_ProductFamilyTrigger;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Sold;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Canceled;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Expired;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        finished = true;

        System.assertEquals(true, finished, 'Test Not Ended');

    }

    @isTest
    static void changeStatusHandlerConfirmed(){

        Boolean finished = false;

        Product2 pOld = new Product2();
        pOld.Status__c = Label.HDT_Confirmed;

        Product2 pNew = new Product2();
        pNew.Status__c = Label.HDT_InDevelopment;

        HDT_WRP_ProductStObjProcess.HDT_WRP_StatusResponse statusResponse;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Confirmed;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Sold;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Canceled;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Expired;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        finished = true;

        System.assertEquals(true, finished, 'Test Not Ended');

    }

    @isTest
    static void changeStatusHandlerSold(){

        Boolean finished = false;

        Product2 pOld = new Product2();
        pOld.Status__c = Label.HDT_Sold;

        Product2 pNew = new Product2();
        pNew.Status__c = Label.HDT_InDevelopment;

        HDT_WRP_ProductStObjProcess.HDT_WRP_StatusResponse statusResponse;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Confirmed;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Sold;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Canceled;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Expired;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        finished = true;

        System.assertEquals(true, finished, 'Test Not Ended');

    }

    @isTest
    static void changeStatusHandlerCanceled(){

        Boolean finished = false;

        Product2 pOld = new Product2();
        pOld.Status__c = Label.HDT_Canceled;

        Product2 pNew = new Product2();
        pNew.Status__c = Label.HDT_InDevelopment;

        HDT_WRP_ProductStObjProcess.HDT_WRP_StatusResponse statusResponse;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Confirmed;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Sold;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Canceled;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Expired;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        finished = true;

        System.assertEquals(true, finished, 'Test Not Ended');

    }

    @isTest
    static void changeStatusHandlerExpired(){

        Boolean finished = false;

        Product2 pOld = new Product2();
        pOld.Status__c = Label.HDT_Expired;

        Product2 pNew = new Product2();
        pNew.Status__c = Label.HDT_InDevelopment;

        HDT_WRP_ProductStObjProcess.HDT_WRP_StatusResponse statusResponse;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Confirmed;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Sold;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Canceled;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        pNew.Status__c = Label.HDT_Expired;
        statusResponse = HDT_UTL_ProductStObjProcess.changeStatusHandler(statusResponse, null, pOld, pNew, 0, 0);

        finished = true;

        System.assertEquals(true, finished, 'Test Not Ended');

    }

}