force-app/main/default/objects/QuoteManagement__c/QuoteManagement__c.object-meta.xml
<CustomObject>
    <description>Oggetto standard utilizzato per tutti i processi di post Sales.</description>
    <label>Quote Management</label>
    <nameField>
        <label>Quote Management Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteManagement__c/fields/CausalCode__c.field-meta.xml
<CustomField>
    <fullName>CausalCode__c</fullName>
    <description>Codice causale</description>
    <label>Codice Causale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteManagement__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <description>Servizio</description>
    <label>Commodity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteManagement__c/fields/Operation_type__c.field-meta.xml
<CustomField>
    <fullName>Operation_type__c</fullName>
    <description>Tipo operazione</description>
    <label>Operation Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteManagement__c/fields/OperationCode__c.field-meta.xml
<CustomField>
    <fullName>OperationCode__c</fullName>
    <label>Codice Prestazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteManagement__c/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <description>Tipo preventivo</description>
    <label>Quote type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteManagement__c/fields/Subprocess__c.field-meta.xml
<CustomField>
    <fullName>Subprocess__c</fullName>
    <description>Sottoprocesso</description>
    <label>Sottoprocesso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_QuoteManagement.cls
public inherited sharing class HDT_QR_QuoteManagement {

    public static QuoteManagement__c queryAddInformation(String commodity, String operationType,String subprocess){

        return [SELECT CausalCode__c, OperationCode__c, QuoteType__c 
        
                FROM QuoteManagement__c 
        
                WHERE 
                
                Commodity__c = :commodity 
                
                AND 
                
                Operation_type__c = :operationType

                AND

                (Subprocess__c =: subprocess OR Subprocess__c = null)

                WITH SECURITY_ENFORCED

                LIMIT 1

                ];

    }
	
    /*
        *@frpanico 05/10/2021
        *Refactoring due to PMD
        *Metodo deprecato poiche' il DataBase.Query viene invocato nel metodo principale. 
    */

	/*public static QuoteManagement__c queryString(String fields, String conditions){
        QuoteManagement__c quoteConfig = new QuoteManagement__c();
		String query = 'SELECT ' + fields + ' FROM QuoteManagement__c WHERE ' + conditions + ' WITH SECURITY_ENFORCED LIMIT 1';
        System.debug(LoggingLevel.DEBUG,'Query--> '+query);
        try{
            quoteConfig = Database.query(query);
        } catch(Exception e){
            quoteConfig = null;
            //System.debug('Config Not Found -> ' + e.getMessage());
        }
		return quoteConfig;
		 
	}*/
}