force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <label>Coda</label>
    <nameField>
        <label>Coda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Queue__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Agenzia assegnata alla coda</description>
    <label>@deprecated</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Gruppo di Lavoro old</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/QueueId__c.field-meta.xml
<CustomField>
    <fullName>QueueId__c</fullName>
    <description>ID della coda</description>
    <label>ID Coda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/WorkGroup__c.field-meta.xml
<CustomField>
    <fullName>WorkGroup__c</fullName>
    <label>Gruppo di Lavoro</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CDO_PPT_DISCO</fullName>
            </value>
            <value>
                <fullName>HC_CDO_OM</fullName>
            </value>
            <value>
                <fullName>HC_CDO_OM_Attivazioni_HC</fullName>
            </value>
            <value>
                <fullName>HC_CDO_OM_Attivazioni_Service A</fullName>
            </value>
            <value>
                <fullName>HC_CDO_OM_Attivazioni_Service B</fullName>
            </value>
            <value>
                <fullName>HC_CDO_OM_OUT</fullName>
            </value>
            <value>
                <fullName>HC_CRM_CC_CMD</fullName>
            </value>
            <value>
                <fullName>HC_CRM_CC_CV_qualità</fullName>
            </value>
            <value>
                <fullName>HC_CRM_CC_CV_TL</fullName>
            </value>
            <value>
                <fullName>HC_CRM_CC_KNVK_TL</fullName>
            </value>
            <value>
                <fullName>HC_CRM_CC_LT_TL</fullName>
            </value>
            <value>
                <fullName>HC_CRM_Escalation_CC_CV_qualità</fullName>
            </value>
            <value>
                <fullName>HC_CRM_Escalation_CC_CV_TL</fullName>
            </value>
            <value>
                <fullName>HC_CRM_Escalation_CC_KNVK_TL</fullName>
            </value>
            <value>
                <fullName>HC_CRM_Escalation_CC_LT_TL</fullName>
            </value>
            <value>
                <fullName>HC_CRM_Escalation_HD</fullName>
            </value>
            <value>
                <fullName>HC_CRM_Quality_CC</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_CSREG_Bonus Sociale Energy</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_CSREG_Bonus Sociale Energy_Target</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_CSREG_Canone Rai</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MICO_Miglioramento Continuo</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Accise_Conservice</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Accise_HC</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Appuntamenti_Koinè</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Bonif Anagr da DAFC_HC</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Bonif Anagr da DAFC_Target</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Com Pag_Koinè</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Contratti_Preventivi_HC</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Contratti_Preventivi_Koinè</fullName>
            </value>
            <value>
                <fullName>HC_CVMBO_MMSME_CFBS_Disattivazioni_HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/UserCompany__c.field-meta.xml
<CustomField>
    <fullName>UserCompany__c</fullName>
    <description>Campo chiesto dal BSN, verrà valorizzato da OIG in fase di Provisioninig</description>
    <label>Società Utenza</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACEGASAPSAMGA SPA</fullName>
            </value>
            <value>
                <fullName>HERA TRADING SRL</fullName>
            </value>
            <value>
                <fullName>ASCOPIAVE ENERGIE SPA</fullName>
            </value>
            <value>
                <fullName>ARESGAS</fullName>
            </value>
            <value>
                <fullName>ALIPLAST IBERIA</fullName>
            </value>
            <value>
                <fullName>HERA COMM SPA</fullName>
            </value>
            <value>
                <fullName>ALIPLAST FRANCE</fullName>
            </value>
            <value>
                <fullName>BLUE META</fullName>
            </value>
            <value>
                <fullName>HERAMBIENTE SPA</fullName>
            </value>
            <value>
                <fullName>HERAMBIENTE SERVIZI INDUSTRIALI SRL</fullName>
            </value>
            <value>
                <fullName>HESTAMBIENTE SRL</fullName>
            </value>
            <value>
                <fullName>HERA COMM SRL</fullName>
            </value>
            <value>
                <fullName>ALIPLAST SPA</fullName>
            </value>
            <value>
                <fullName>BLUE META SPA</fullName>
            </value>
            <value>
                <fullName>FRULLO ENERGIA AMBIENTE SRL</fullName>
            </value>
            <value>
                <fullName>HERA COMM MARCHE SRL</fullName>
            </value>
            <value>
                <fullName>ASA SPA</fullName>
            </value>
            <value>
                <fullName>ETRA ENERGIA SRL</fullName>
            </value>
            <value>
                <fullName>INRETE</fullName>
            </value>
            <value>
                <fullName>HERA SPA</fullName>
            </value>
            <value>
                <fullName>INRETE DISTRIBUZIONE ENERGIA SPA</fullName>
            </value>
            <value>
                <fullName>HERATECH SRL</fullName>
            </value>
            <value>
                <fullName>ASCOTRADE SPA</fullName>
            </value>
            <value>
                <fullName>ALIMPET SRL</fullName>
            </value>
            <value>
                <fullName>ORACLE ITALIA SRL</fullName>
            </value>
            <value>
                <fullName>ACANTHO SPA</fullName>
            </value>
            <value>
                <fullName>HERA LUCE SRL</fullName>
            </value>
            <value>
                <fullName>ALIPLST POLSKA</fullName>
            </value>
            <value>
                <fullName>BLU RANTON</fullName>
            </value>
            <value>
                <fullName>SINERGIE SPA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coda</label>
    <referenceTo>Queue__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/UserCompany__c.field-meta.xml
<CustomField>
    <fullName>UserCompany__c</fullName>
    <label>Società Utenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/WorkGroup__c.field-meta.xml
<CustomField>
    <fullName>WorkGroup__c</fullName>
    <label>Gruppo di Lavoro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_LC_ActivityReassignmentTool.cls
public with sharing class HDT_LC_ActivityReassignmentTool {    
    @AuraEnabled
    public static List<Map<String,String>> getAssignees(String queryString) {
        List<Map<String,String>> results = new List<Map<String,String>>();
        queryString = '%' + queryString + '%';
        if(String.isNotBlank(UserInfo.getUserRoleId())) {
            User currentUser = [SELECT Id, UserRole.Name, UserCompany__c FROM User WHERE Id = :UserInfo.getUserId()];
            if(currentUser.UserRole.Name.contains('Supervisore')) {
                // WIP WHERE CLAUSE
                List<User> users = [SELECT Id, Name FROM User WHERE UserCompany__c = :currentUser.UserCompany__c AND Name LIKE :queryString WITH SECURITY_ENFORCED];
                for(User user : users) {
                    results.add(new Map<String,String>{
                        'id' => user.Id,
                        'name' => user.Name,
                        'icon' => 'standard:user'
                    });
                }
            }
        }
        List<Queue__c> queues = [SELECT Id, Name, QueueId__c, Group__c, Agency__c FROM Queue__c WHERE Name LIKE :queryString WITH SECURITY_ENFORCED];
        for(Queue__c queue : queues) {
            results.add(new Map<String,String>{
                'id' => queue.QueueId__c,
                'wrapperId' => queue.Id,
                'name' => queue.Name,
                'workGroup' => queue.Group__c,
                'agency' => queue.Agency__c,
                'icon' => 'standard:queue'
            });
        }

        return results;
    }

    @AuraEnabled
    public static String reassignActivity(String recordId, String assigneeId, String wrapperId, String workGroup, String agency) {
        try {
            wrts_prcgvr__Activity__c activity = new wrts_prcgvr__Activity__c(
                Id = recordId,
                OwnerId = assigneeId
            );

            if(String.isNotBlank(wrapperId)) {
                activity.WorkGroup__c = workGroup;
                activity.Agency__c = agency;
                activity.Queue__c = wrapperId;
            }

            HDT_UTL_DatabaseService.updateSObject(activity);
            return null;
        } catch (Exception e) {
            return e.getMessage();
        }
    }

    @AuraEnabled
    public static String assignToMe(String recordId) {
        return reassignActivity(recordId, UserInfo.getUserId(), null, null, null);
    }
}