force-app/main/default/objects/ScriptConfig__c/ScriptConfig__c.object-meta.xml
<CustomObject>
    <description>oggetto per configurare la capability &quot;Gestione Script&quot;.  Ogni record rappresenta un processo di script ai quali vengono agganciati con una lookup Hierarchy (ad uno o più livelli) e contengono meta-informazioni (come il testo, la formattazione, l&apos;oggetto in input, etc) che le logiche implementate utilizzeranno per costruire dinamicamente il flusso dello script</description>
    <label>Configurazione Script</label>
    <nameField>
        <label>Configurazione Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurazione Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptConfig__c/fields/ContextObject__c.field-meta.xml
<CustomField>
    <fullName>ContextObject__c</fullName>
    <description>Picklist selezione oggetto di riferimento, contiene una lista di oggetti preconcordata, nelle sezioni lista serve ad identificare il nome della relazione</description>
    <label>Oggetto di Riferimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CampaignMember</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/ScriptType__c.field-meta.xml
<CustomField>
    <fullName>ScriptType__c</fullName>
    <label>Tipologia Script</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processo</fullName>
            </value>
            <value>
                <fullName>Sezione decisionale</fullName>
            </value>
            <value>
                <fullName>Sezione lista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_LC_ScriptTesterController.cls
/**
 * @description       : Script test tab controller
 * @author            : gabriele.rota@webresults.it
 * @group             : WR
 * @last modified on  : 2021-09-20
 * @last modified by  : gabriele.rota@webresults.it
 * Modifications Log 
 * Ver   Date         Author                        Modification
 * 1.0   2021-09-20   gabriele.rota@webresults.it   Initial Version
**/
public with sharing class HDT_LC_ScriptTesterController {
    
    /**
    * @description Get parent scripts
    * @author gabriele.rota@webresults.it | 2021-09-20 
    * @return List<ScriptConfig__c> 
    **/
    @AuraEnabled
    public static List<ScriptConfig__c> getScripts(){
        try {
            return [SELECT Name, ContextObject__c, CreatedBy.Name FROM ScriptConfig__c
                WHERE ScriptType__c='Processo' WITH SECURITY_ENFORCED ORDER BY Name];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}