force-app/main/default/objects/HDT_MassiveLoaderProcess__mdt/HDT_MassiveLoaderProcess__mdt.object-meta.xml
<CustomObject>
    <label>Processo Caricatore Massivo</label>
    <pluralLabel>Processi Caricatore Massivo</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_MassiveLoaderProcess__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Classe Apex</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/MassiveLoaderRequest__c.object-meta.xml
<CustomObject>
    <label>Esito Caricamento</label>
    <nameField>
        <displayFormat>MLR-{00000000}</displayFormat>
        <label>Id Pratica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Esito Caricamenti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Processo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SwitchIn</fullName>
                <label>Switch In</label>
            </value>
            <value>
                <fullName>Subentro</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Morosita</fullName>
                <label>Morosità</label>
            </value>
            <value>
                <fullName>VolturaTecnica</fullName>
                <label>Voltura Tecnica</label>
            </value>
            <value>
                <fullName>ModificheAnagrafiche</fullName>
                <label>Modifiche Anagrafiche</label>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
            <value>
                <fullName>Subentro su Gdm Chiuso</fullName>
            </value>
            <value>
                <fullName>Prima Attivazione</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Nuovi Bonus e VAS</fullName>
            </value>
            <value>
                <fullName>Cambio uso</fullName>
                <label>CambioUso</label>
            </value>
            <value>
                <fullName>Cambio offerta</fullName>
            </value>
            <value>
                <fullName>Tariffe e Sconti</fullName>
            </value>
            <value>
                <fullName>CaricamentoCGC</fullName>
                <label>Caricamento CGC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>In attesa di lavorazione</fullName>
            </value>
            <value>
                <fullName>Pronto A Partire</fullName>
                <isActive>false</isActive>
                <label>Pronto A Partire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/MassiveLoaderRequest__c.field-meta.xml
<CustomField>
    <fullName>MassiveLoaderRequest__c</fullName>
    <label>Richiesta di Caricamento</label>
    <referenceTo>MassiveLoaderRequest__c</referenceTo>
    <relationshipLabel>Massive Loader Request Request Item</relationshipLabel>
    <relationshipName>MassiveLoaderRequest_Request_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In attesa di lavorazione</fullName>
                <default>true</default>
                <label>In attesa di lavorazione</label>
            </value>
            <value>
                <fullName>In Lavorazione</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Errore</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
                <isActive>false</isActive>
                <label>Done</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Ready To Run</fullName>
                <isActive>false</isActive>
                <label>Ready To Run</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassiveLoaderRequestItem__c/fields/StatusDescription__c.field-meta.xml
<CustomField>
    <fullName>StatusDescription__c</fullName>
    <description>Used for error status</description>
    <label>Status Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_BA_ProcessRequestItem.cls
public with sharing class HDT_BA_ProcessRequestItem implements Database.Batchable<SObject>, Database.Stateful,Database.AllowsCallouts {
    private id idLoaderRequest;
    private Integer batchSize;
    private String process;

    private static HDT_UTL_Constants constantsUtl = new HDT_UTL_Constants();

    private static HDT_QR_MassiveLoaderProcess massiveLoaderProcessQr = new HDT_QR_MassiveLoaderProcess();
    public HDT_BA_ProcessRequestItem(Id varIdLoaderRequest, Integer batchSize, String process) {
        //System.debug('HDT_BA_ProcessRequestItem : '+varIdLoaderRequest);
        this.idLoaderRequest=varIdLoaderRequest;
        this.batchSize = batchSize;
        this.process = process;
    }
   	public Database.QueryLocator start(Database.BatchableContext bc) {
            HDT_QR_Helper qrObj=new HDT_QR_Helper();
            qrObj.setObj('MassiveLoaderRequestItem__c');
            qrObj.setNestedFields(new list<String>{'MassiveLoaderRequest__r.ProcessType__c'});
            qrObj.setFilter('MassiveLoaderRequest__c =\''+this.idLoaderRequest+'\' Order by CreatedDate DESC');
			String query =  qrObj.getQeryString();
            //System.debug('query:  '+query);
			return Database.getQueryLocator(query);
	}
    public void execute(Database.BatchableContext bc, List<MassiveLoaderRequestItem__c> scope) {

        HDT_UTL_ProcessExecution cls;

        if(batchSize > 1){
            // System.debug('HDT_BA_ProcessRequestItem execute ' );
            HDT_MassiveLoaderProcess__mdt selectedProcess = massiveLoaderProcessQr.getRecordByName(process);
            // System.debug('Apex Class : '+selectedProcess.ApexClass__c);
            Type t = Type.forName(selectedProcess.ApexClass__c);
            cls = (HDT_UTL_ProcessExecution)t.newInstance();
            // --------- montors fix for bulk develop  ---------
            cls.setMassiveLoaderRequestItemList(scope);
        } else if(batchSize == 1){
            // System.debug('HDT_BA_ProcessRequestItem execute ' );
            MassiveLoaderRequestItem__c massiveItem=scope.get(0);
            // System.debug('massiveItem:  '+massiveItem);
            // System.debug('ProcessType: '+massiveItem.MassiveLoaderRequest__r.ProcessType__c);
            HDT_MassiveLoaderProcess__mdt selectedProcess = massiveLoaderProcessQr.getRecordByName(massiveItem.MassiveLoaderRequest__r.ProcessType__c);
            // System.debug('Apex Class : '+selectedProcess.ApexClass__c);
            Type t = Type.forName(selectedProcess.ApexClass__c);
            cls = (HDT_UTL_ProcessExecution)t.newInstance();
            cls.setMassiveLoaderRequestItem(massiveItem);
        }
        
        try {
            cls.execute();
        } catch (HDT_UTL_ProcessExecution.HDT_WRP_ProcessEntitiesException e) {
            System.debug('HDT_UTL_ProcessExecution.HDT_WRP_ProcessEntitiesException');
            System.debug(e.Message);
            //update massiveItem;
        } catch (Exception e) {
            System.debug('Standard Exception');
            System.debug(e.getMessage());
            //massiveItem.Status__c               = 'Errore'          ;
            //massiveItem.StatusDescription__c    = e.getMessage()    ;
            //update massiveItem;
            cls.manageCatchException(batchSize, scope, e.getMessage());
        }
    }
    public void finish(Database.BatchableContext bc){
        //System.debug('HDT_BA_ProcessRequestItem finish ');
        MassiveLoaderRequest__c oldReq=new MassiveLoaderRequest__c(id=idLoaderRequest,Status__c=constantsUtl.MASSIVLOADER_STATUS_CHIUSO);
        update oldReq;
        // Creazione file RequestItem in Errore 
        List<MassiveLoaderRequestItem__c> listErrorReq =[SELECT Id,Name,Data__c, Status__c,StatusDescription__c  from MassiveLoaderRequestItem__c WHERE Status__c ='Errore' AND MassiveLoaderRequest__c =:idLoaderRequest ];
        if (listErrorReq!=null && listErrorReq.size()>0) {
            HDT_BA_ErrorRequestItem batch = new HDT_BA_ErrorRequestItem(idLoaderRequest);
            Database.executebatch(batch,1000);
        }
      




        // List<MassiveLoaderRequest__c> listmsr = [SELECT Id FROM MassiveLoaderRequest__c WHERE Status__c=:constantsUtl.MASSIVLOADER_STATUS_INATTESAlAVORAZIONE ORDER BY CreatedDate DESC LIMIT 10];
        // if (listmsr!=null && listmsr.size()>0 ) {
        //     HDT_BA_ProcessRequestItem processReq = new HDT_BA_ProcessRequestItem(listmsr.get(0).id); 
        //     Id batchprocessid = Database.executeBatch(processReq,1);
        // }

        


    }
}