force-app/main/default/objects/BatchExecutionKpi__c/BatchExecutionKpi__c.object-meta.xml
<CustomObject>
    <description>ogetto per tracciare i risultati di Batch execution</description>
    <label>BatchExecutionKpi</label>
    <nameField>
        <label>Nome BatchExecutionKpi</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BatchExecutionKpi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchExecutionKpiConfiguration__mdt/BatchExecutionKpiConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>BatchExecutionKpiConfiguration</label>
    <pluralLabel>BatchExecutionKpiConfiguration</pluralLabel>
</CustomObject>

force-app/main/default/objects/BatchExecutionKpiConfiguration__mdt/fields/DesiredEmail__c.field-meta.xml
<CustomField>
    <fullName>DesiredEmail__c</fullName>
    <label>Desired email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BatchExecutionKpiConfiguration__mdt/fields/EnableEmailSend__c.field-meta.xml
<CustomField>
    <fullName>EnableEmailSend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable email send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BatchExecutionKpiConfiguration__mdt/fields/EnableTracking__c.field-meta.xml
<CustomField>
    <fullName>EnableTracking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable tracking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailSetting__mdt/EmailSetting__mdt.object-meta.xml
<CustomObject>
    <label>EmailSetting</label>
    <pluralLabel>EmailSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order/fields/CommodityFormula__c.field-meta.xml
<CustomField>
    <fullName>CommodityFormula__c</fullName>
    <formula>TEXT(ServicePoint__r.CommoditySector__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servizio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DocSendingMethod__c.field-meta.xml
<CustomField>
    <fullName>DocSendingMethod__c</fullName>
    <label>Modalita Invio Doc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Posta</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Stampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ParentOrder__c.field-meta.xml
<CustomField>
    <fullName>ParentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione verso l&apos;order dossier</description>
    <label>Order Padre</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingAddressFormula__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressFormula__c</fullName>
    <formula>ShippingStreetName__c&amp;&apos; &apos;&amp;ShippingStreetNumber__c
&amp;IF(!ISBLANK(ShippingStreetNumberExtension__c),&apos;/&apos;&amp; ShippingStreetNumberExtension__c,&apos;&apos;)
&amp;IF(!ISBLANK(ShippingPlace__c),&apos;, &apos;&amp; ShippingPlace__c,&apos;&apos;)
&amp;&apos;, &apos;&amp;ShippingCity__c&amp;&apos; &apos;&amp;ShippingProvince__c
&amp;&apos;, &apos;&amp;ShippingPostalCode__c&amp;&apos; &apos;&amp;ShippingCountry__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Indirizzo di Spedizione</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SignatureMethod__c.field-meta.xml
<CustomField>
    <fullName>SignatureMethod__c</fullName>
    <label>Metodo Firma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vocal Order</fullName>
            </value>
            <value>
                <fullName>OTP Remoto</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
            </value>
            <value>
                <fullName>OTP Coopresenza</fullName>
            </value>
            <value>
                <fullName>Contratto già firmato</fullName>
            </value>
            <value>
                <fullName>Accettato Digitalmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDT_BA_OrderDocumentalManagement.cls
public with sharing class HDT_BA_OrderDocumentalManagement implements Database.Batchable<sObject>, Database.Stateful {
    public Set<String> orderScartatiSet = new Set<String>();
    public Integer counterKo = 0;
    public Integer counterOk = 0;
    Datetime start = null;
    private static HDT_SRV_BatchExecutionKpi srvBatchEx = new HDT_SRV_BatchExecutionKpi();
    BatchExecutionKpiConfiguration__mdt kpiMeta = BatchExecutionKpiConfiguration__mdt.getInstance('HDT_BA_OrderDocumentalManagement');
    BatchExecutionKpi__c kpiTrack=new BatchExecutionKpi__c();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        if(kpiMeta!=null && kpiMeta.EnableTracking__c){
            kpiTrack = srvBatchEx.createRecord(Datetime.now(),'HDT_BA_OrderDocumentalManagement');
        }
        String query = 'select ParentOrder__c from Order where Phase__c = \'In attesa validazione\' and CommodityFormula__c = \'Ambiente\'';
        List<Order> ordList = Database.query(query);
        Set<Id> orderIdSet = new Set<Id>();
        for(Order ord: ordList){
            orderIdSet.add(ord.ParentOrder__c);
        }
        String queryOrder = 'SELECT Id,DocSendingMethod__c,SignatureMethod__c,ShippingAddressFormula__c FROM Order WHERE Id IN:orderIdSet';
        return Database.getQueryLocator(queryOrder);
    }
    public void execute(Database.BatchableContext bc, List<Order> scope){
        Order singleOrder = (Order) scope[0];
        if(String.isBlank(singleOrder.ShippingAddressFormula__c)){
            orderScartatiSet.add(singleOrder.Id);
            counterKo++;
            return;
        }
        Map<String,String> params = new Map<String,String>();
        String modInvio = singleOrder.DocSendingMethod__c == 'Stampa Cartacea'? 'Sportello':singleOrder.DocSendingMethod__c;
        params.put('signMode', singleOrder.SignatureMethod__c);
        params.put('sendMode', 'Posta Cartacea');
        params.put('Contesto', 'Order');
        params.put('mode', 'Print');
        params.put('Archiviato', 'Y');
        params.put('TipoPlico', 'Sollecito');
        HDT_SRV_DocumentalManagementFacade.sendDocumentAsync(singleOrder.Id, 'Order',JSON.serialize(params));
        counterOk++;
}
    public void finish(Database.BatchableContext bc){
        if(kpiMeta!=null && kpiMeta.EnableEmailSend__c){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            list <EmailSetting__mdt> email=[SELECT DeveloperName, Email__c FROM EmailSetting__mdt WHERE DeveloperName='Elaborazione_Archivio_FUB' limit 1];
            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress LIMIT 1];
            mail.setOrgWideEmailAddressId(owea[0].Id);
            mail.setToAddresses(new String[]{kpiMeta.DesiredEmail__c});
            mail.setSubject('Batch HDT_BA_OrderDocumentalManagement execution KPI');
            String body='number of records: ' + (counterKo+counterOk) + '\nsuccessful send to e1: ' + counterOk + '\nunsuccessful deletions ' + counterKo ;
            mail.setPlainTextBody (body);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }

        if(kpiMeta!=null && kpiMeta.EnableTracking__c){
            srvBatchEx.updateRecord(kpiTrack.Id,counterOk, counterKo, counterKo + counterOk);
        }
    }
}