force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>Lista di citta con corrispettivo codice belfiore per il calcolo del codice fiscale</description>
    <label>Città</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Città</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/IsNotTransition__c.field-meta.xml
<CustomField>
    <fullName>IsNotTransition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nuovo Modello</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/City__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Provincia</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/fields/SDV__c.field-meta.xml
<CustomField>
    <fullName>SDV__c</fullName>
    <label>SDV</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/fields/CommoditySector__c.field-meta.xml
<CustomField>
    <fullName>CommoditySector__c</fullName>
    <description>Commodity del punto</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/isReseller__c.field-meta.xml
<CustomField>
    <fullName>isReseller__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReseller</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServicePoint__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_CalculateTransitionTst.cls
@IsTest
public with sharing class HDT_UTL_CalculateTransitionTst {

    @TestSetup
    static void setup()
    {
        List<Account> accList=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'D1 - Persona fisica', 'Enti');
		List<Sale__c> saleList=HDT_UTL_DataFactoryTst.createSale(1, true, accList[0].Id, 'Attiva');
        List<ServicePoint__c> spList = HDT_UTL_DataFactoryTst.createServicePoint(1, true);
        spList[0].SupplyCity__c = 'Pesaro';
        spList[0].CommoditySector__c = 'Gas';
        spList[0].IsReseller__c = true;
        update spList;
        List<City__c> cities = new List<City__c>();
        City__c c = new City__c(SDV__C = 'HCM', Province__c = 'PU', Name = spList[0].SupplyCity__c, IsNotTransition__c = true);
        City__c city = new City__c(SDV__C = 'HCM', Province__c = 'RM', Name = 'Acerra', IsNotTransition__c = false);
        cities.add(c);
        cities.add(city);
        insert cities;
    }

    @istest
    static void calculateTransitionTest1(){

        String city = 'Pesaro';
        String commodity = 'Gas';
        Boolean result = false;
        HDT_UTL_CalculateTransition calculateTransition = new HDT_UTL_CalculateTransition(city, commodity); 
        result = calculateTransition.calculateTransition();
        
        System.assertEquals(true, result,'Transizione non calcolata');
    }

    @istest
    static void calculateTransitionTest2(){

        List<ServicePoint__c> servicePoints = [SELECT Id, SupplyCity__c, CommoditySector__c, IsReseller__c 
                                               FROM ServicePoint__c 
                                               WHERE SupplyCity__c = 'Pesaro'
                                               AND CommoditySector__c = 'Gas'
                                               AND IsReseller__c = true WITH SECURITY_ENFORCED];
        
        List<Sale__c> sales = [SELECT Id FROM Sale__c];
        Boolean result = false;
        if(!servicePoints.isEmpty() && !sales.isEmpty()){
            HDT_UTL_CalculateTransition calculateTransition = new HDT_UTL_CalculateTransition(servicePoints[0], sales[0]); 
            result = calculateTransition.calculateTransition();
            
            System.assertEquals(true, result,'Transizione non calcolata');
        }

    }

    @istest
    static void calculateTransitionTest3(){

        String city = 'Pesaro';
        List<Sale__c> sales = [SELECT Id FROM Sale__c];
        Boolean result = false;
        HDT_UTL_CalculateTransition calculateTransition = new HDT_UTL_CalculateTransition(city, sales[0]); 
        result = calculateTransition.calculateTransition();
        
        System.assertEquals(true, result,'Transizione non calcolata');

    }

    @istest
    static void calculateTransitionTest4(){

        String city = 'Acerra';
        String commodity = 'Gas';
        String distributorCode = 'ALTRO';
        Boolean result = false;
        HDT_UTL_CalculateTransition calculateTransition = new HDT_UTL_CalculateTransition(city, commodity, distributorCode); 
        result = calculateTransition.calculateTransition();
        
        System.assertEquals(true, result,'Transizione non calcolata');
    }
    @IsTest
    static void calculateCompanyInfosTst()
    {
        String city = 'Pesaro';
        String commodity = 'Gas';
        String distributorCode = 'ALTRO';
        HDT_UTL_CalculateTransition calculateTransition = new HDT_UTL_CalculateTransition(city, commodity, distributorCode);
        Test.startTest();
            Map<String,Object> result = calculateTransition.calculateCompanyInfos();
        Test.stopTest();
        System.assertEquals(true, !result.isEmpty(), 'Compnay Info Calcolati');
    }
}