force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>Lista di citta con corrispettivo codice belfiore per il calcolo del codice fiscale</description>
    <label>Città</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Città</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HDT_DistributorExceptionHC__mdt/HDT_DistributorExceptionHC__mdt.object-meta.xml
<CustomObject>
    <description>Elenco distributori che fanno eccezione su territorio HCM e richiedono il logo di HC.</description>
    <label>Distributor Exception HC</label>
    <pluralLabel>Distributor Exception HC</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_DistributorExceptionHC__mdt/fields/DistributorName__c.field-meta.xml
<CustomField>
    <fullName>DistributorName__c</fullName>
    <label>Distributor Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIRETTO SNAM-10R0000020</fullName>
                <default>true</default>
                <label>DIRETTO SNAM-10R0000020</label>
            </value>
            <value>
                <fullName>DIRETTO SGM-10R0000230</fullName>
            </value>
            <value>
                <fullName>DIRETTO EDISON-10R0000051</fullName>
            </value>
            <value>
                <fullName>A.S.SE.M SPA-10R0000068</fullName>
            </value>
            <value>
                <fullName>ITALGAS RETI SPA -10R0000013</fullName>
            </value>
            <value>
                <fullName>EDMA RETI GAS-10R0000015</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_HcmCityException__mdt/HDT_HcmCityException__mdt.object-meta.xml
<CustomObject>
    <label>HDT_HcmCityException</label>
    <pluralLabel>HDT_HcmCityExceptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_HcmCityException__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Comune</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_HcmCityException__mdt/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Servizio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_PayloadManagement.cls
public with sharing class HDT_QR_PayloadManagement {
    public HDT_QR_PayloadManagement() {

    }
    public List<HDT_HcmCityException__mdt> getHcmCityExceptionByName(String city){
        if(String.isBlank(city)) return null;
        city = String.escapeSingleQuotes(city);
        city = city.toUpperCase();
        return [SELECT City__c, Commodity__c FROM HDT_HcmCityException__mdt WHERE City__c=:city WITH SECURITY_ENFORCED];
    }

    public List<HDT_DistributorExceptionHC__mdt> getHcDistributorExceptionByName(String distributorName){
        if(String.isBlank(distributorName)) return null;
        distributorName = String.escapeSingleQuotes(distributorName);
        distributorName = distributorName.toUpperCase();
        return [SELECT DistributorName__c FROM HDT_DistributorExceptionHC__mdt WHERE DistributorName__c=:distributorName WITH SECURITY_ENFORCED];
    }
}