force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>Lista di citta con corrispettivo codice belfiore per il calcolo del codice fiscale</description>
    <label>Città</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Città</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>il servizio del dato record di Prodotto nella funzionalità di Configurazione Offerta Tecnica</description>
    <label>Servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteAdministrationTaxBreaks__c/WasteAdministrationTaxBreaks__c.object-meta.xml
<CustomObject>
    <label>Amministrazione Testo Agevolazione</label>
    <nameField>
        <displayFormat>TB-{000000}</displayFormat>
        <label>TaxBreaks</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amministrazione Testo Agevolazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WasteAdministrationTaxBreaks__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProdottoOpzione</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Il prodotto opzione non esiste.</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Opzioni Tari</value>
        </filterItems>
        <filterItems>
            <field>Product2.Service__c</field>
            <operation>equals</operation>
            <value>Ambiente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Amministrazione Testo Agevolazioni</relationshipLabel>
    <relationshipName>Amministrazione_Testo_Agevolazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WasteAdministrationTaxBreaks__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Codice Prodotto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WasteAdministrationTaxBreaks__c/fields/TextRemove__c.field-meta.xml
<CustomField>
    <fullName>TextRemove__c</fullName>
    <label>Testo Rimozione</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WasteAdministrationTaxBreaks__c/fields/TextRequest__c.field-meta.xml
<CustomField>
    <fullName>TextRequest__c</fullName>
    <label>Testo Richiesta</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/HDT_Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acqua</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Energia Elettrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Multi</fullName>
    </customValue>
    <customValue>
        <fullName>Teleriscaldamento</fullName>
    </customValue>
    <description>Elenco Servizi gestiti da Hera</description>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_AdministrationTaxBreaksTst.cls
@isTest
public with sharing class HDT_UTL_AdministrationTaxBreaksTst {
	@TestSetup
	static void makeData(){
		Product2 testerProduct = new Product2(Name = 'NomeTest', ProductCode = 'TestProductCode', Family = 'Opzioni Tari', Service__c = 'Ambiente');
		insert testerProduct;
		WasteAdministrationTaxBreaks__c tester = new WasteAdministrationTaxBreaks__c(TextRemove__c = 'TextRmT1', TextRequest__c = 'TextRqT1', city__c = 'Roma');
		insert tester;
        tester.Product__c = testerProduct.Id;
        update tester;
	}
    @isTest
    private static void validategetTexTaxBreaks(){
		//DEBUG
		
        System.debug('Test classe HDT_UTL_AdministrationTaxBreaksTst metodo validategetTexTaxBreaks');
	
		//SETUP
		
		Boolean isEmptyVar = false;
		String citytest = 'Roma';
		String productCodetest = 'TestProductCode';
		List <WasteAdministrationTaxBreaks__c> risultati = new list <WasteAdministrationTaxBreaks__c>();
		
		//TESTING
		
		Test.startTest();
          
		String fields1 = 'Id, TextRemove__c, TextRequest__c,city__c,productCode__c';
		String obj1 = 'WasteAdministrationTaxBreaks__c';

        List <WasteAdministrationTaxBreaks__c> records=new list <WasteAdministrationTaxBreaks__c>();
		records = HDT_QR_GenericQuery.getGenericRecords(fields1,obj1,'');

        
		risultati = HDT_UTL_AdministrationTaxBreaks.getTexTaxBreaks(citytest,productCodetest);
		isEmptyVar = risultati.isEmpty();
		
		Test.stopTest();
		
		//ASSERTS
		
		System.assertEquals(false, isEmptyVar,'');
    }
}