force-app/main/default/objects/AccountStatementFilter__c/AccountStatementFilter__c.object-meta.xml
<CustomObject>
    <description>Oggetto tecnico per innesco processi da Estratto Conto</description>
    <label>Filtro Estratto Conto</label>
    <nameField>
        <displayFormat>ASF-{0000}</displayFormat>
        <label>Filtro Estratto Conto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filtri Estratto Conto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Nome del Cluster a cui appartiene un processo.</description>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServicePoint__c.field-meta.xml
<CustomField>
    <fullName>ServicePoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>ServicePoint__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HDT_ServiceCatalogProfileFilter__mdt/HDT_ServiceCatalogProfileFilter__mdt.object-meta.xml
<CustomObject>
    <label>ServiceCatalogProfileFilter</label>
    <pluralLabel>ServiceCatalogProfileFilters</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServicePoint__c/ServicePoint__c.object-meta.xml
<CustomObject>
    <description>Oggetto Custom per tracciare i dati del POD/PDR</description>
    <label>Service Point</label>
    <nameField>
        <label>Service Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDT_UTL_ServiceCatalogOrFilter.cls
global inherited sharing class HDT_UTL_ServiceCatalogOrFilter implements wrts_prcgvr.Interfaces_1_2.IApexCriteria {
    HDT_QR_PermissionSet permQr = new HDT_QR_PermissionSet();
    // Classe Utilizzata per i filtri in OR del Processo da catalogo servizi.
  //  'Cluster__c:valore,valore2,valore3?Type:valore1 ,valore2, valore3'
    global boolean evaluate(Object args) {
        Map<String,Object> argsMap = (Map<String,Object>) args;
        System.debug('************VALUEOF:' + argsMap);
        sObject sb = (sObject) argsMap.get('record');
        System.debug('************VALUE:'+ sb.Id.getSObjectType().getDescribe().getName());
        String objectType = sb.Id.getSObjectType().getDescribe().getName();
        //Map<String,HDT_ServiceCatalogProfileFilter__mdt> listMet = HDT_ServiceCatalogProfileFilter__mdt.getAll();
        //SObject action = (SObject) argsMap.get('action'); //phase transition detail
        String method = (String) argsMap.get('method');
        boolean res = true;
        if ('ServicePoint__c'.equalsIgnoreCase(objectType)){
            res = HDT_UTL_ServiceCatalogOrFilterProcess.servicePointFilter(sb, method);
        }else if(objectType == 'Case'){
            res = HDT_UTL_ServiceCatalogOrFilterProcess.caseFilter(sb, method);
        } else if (objectType == 'AccountStatementFilter__c'){
            res = HDT_UTL_ServiceCatalogOrFilterProcess.accountStatementFilter(sb, method);
        }
        return res;
    }
    /*global object getLinkItems(Object args){
        Map<String,Object> argsMap = (Map<String,Object>) args;
 
        SObject action = (SObject) argsMap.get('action'); //phase transition detail
        String method = (String) argsMap.get('method');
        if(method == 'Prova1'){
            return true;
        }
        else{
            return false;
        }
        
    }
    global object getLinks(Object args){
        Map<String,Object> argsMap = (Map<String,Object>) args;
 
        SObject action = (SObject) argsMap.get('action'); //phase transition detail
        String method = (String) argsMap.get('method');
        if(method == 'Prova1'){
            return true;
        }
        else{
            return false;
        }
        
    }*/
}