force-app/main/default/objects/Opportunity/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relazione con l&apos;oggetto Vendita</description>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare un contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsVAS__c.field-meta.xml
<CustomField>
    <fullName>IsVAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Ordine di riferimento)</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettato Motore Vas</fullName>
            </value>
            <value>
                <fullName>Accettazione pagamento a DL</fullName>
            </value>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck OK SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità conformità OK</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Annullamento - Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Annullamento - Da inviare</fullName>
            </value>
            <value>
                <fullName>Annullamento dal SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito KO da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Esito OK da DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento - Inviato al DL/SII</fullName>
            </value>
            <value>
                <fullName>Annullamento per Switch-out</fullName>
            </value>
            <value>
                <fullName>Annullamento - Revocato</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Annullamento SII - Ricezione</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Annullato per Dati Discordanti</fullName>
            </value>
            <value>
                <fullName>Annullato SII</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Credit Check</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
                <isActive>false</isActive>
                <label>BL010</label>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Bozza Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune [Fornitura]</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <description>Oggetto per gestione Vendite</description>
    <label>Vendita</label>
    <nameField>
        <label>Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Attiva</fullName>
            </value>
            <value>
                <fullName>Annullata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ContractReference__c.field-meta.xml
<CustomField>
    <fullName>ContractReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziareun contratto attivo durante la vendita singola di un VAS</description>
    <label>Contratto di riferimento</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (CPQ) (Contratto di riferimento)</relationshipLabel>
    <relationshipName>QuotesCPQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/IsVAS__c.field-meta.xml
<CustomField>
    <fullName>IsVAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo utilizzato per referenziare l&apos;ordine in corso durante la vendita singola di un VAS</description>
    <label>Ordine di riferimento</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Quotes (CPQ)</relationshipLabel>
    <relationshipName>QuotesCPQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendita</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SupplyCity__c.field-meta.xml
<CustomField>
    <fullName>SupplyCity__c</fullName>
    <label>Comune Fornitura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_QR_OpportunityTst.cls
/**
 * @author Fabricio Petkevicius Nunes (fabricio.nunes@engdb.com.br)
 * @date 03/08/2021
 * @description Test Class for HDT_QR_Opportunity.cls
 * @history Fabricio Petkevicius Nunes – 03/08/2021 – Created class
 */
@isTest
public class HDT_QR_OpportunityTst{
	@TestSetup
	static void setup(){

		HDT_UTL_DataFactoryTst.pClickInstance();
		HDT_UTL_DataFactoryTst.pClickOrderPhase();

		List<Account> tAccount=HDT_UTL_DataFactoryTst.createAccountBusiness(1, true, 'HERA COMM', 'Azienda', 'Aziende SME');
		List<Sale__c> tSale=HDT_UTL_DataFactoryTst.createSale(1, true, tAccount[0].Id, 'Attiva');
		List<Opportunity> tOpp=HDT_UTL_DataFactoryTst.createOpportunity(1, false);
		tOpp[0].Sale__c=tsale[0].Id;

		insert tOpp;


		List<Contract> tContract=HDT_UTL_DataFactoryTst.createContract(1, true, tAccount[0].Id);

		List<Order> tOrder=HDT_UTL_DataFactoryTst.createOrder(1, false, tAccount[0].Id, tSale[0].Id);
		tOrder[0].Phase__c='Bozza';

		insert tOrder;

		List<SBQQ__Quote__c> tQuote=HDT_UTL_DataFactoryTst.createQuote(1, false, tOrder[0].Id, topp[0].Id, tSale[0].Id, 'Amendment');

		tQuote[0].IsVAS__c=true;
		tquote[0].OrderReference__c=tOrder[0].Id;
		tquote[0].ContractReference__c=tContract[0].Id;
		tQuote[0].SupplyCity__c='Roma';

		insert tQuote;

		// List<SBQQ__Quote__c> quoteLst = [SELECT IsVas__c, SupplyCity__c FROM SBQQ__Quote__c WHERE Id=:tquote[0].Id];
		// System.debug('quoteLst = '+quoteLst);

		topp[0].SBQQ__PrimaryQuote__c=tQuote[0].Id;

		update tOpp;
		//    List<Opportunity> oppLst = [SELECT StageName, SBQQ__PrimaryQuote__r.IsVAS__c FROM Opportunity WHERE Sale__c =: tSale[0].Id];
		//     System.debug('oppLst = '+oppLst);
	}

	@isTest
	static void testcountRecordsBySale(){

		Test.startTest();

		Sale__c saleTst=[SELECT Id, Status__c
		                 FROM Sale__c
		                 WHERE Status__c='Attiva'
		                 LIMIT 1];

		HDT_QR_Opportunity oppQr=new HDT_QR_Opportunity();


		integer methodRet=oppQr.countRecordsBySale(saleTst.Id);

		System.debug('methodRet = '+methodRet);


		System.assertEquals(1, methodRet, 'Return is wrong');

		System.assertNotEquals(0, methodRet, 'Value of parameter is not matching');

		Test.stopTest();
	}

	@isTest
	static void testgetRecordsBySaleFilterStageName(){

		Test.startTest();

		Sale__c saleTst=[SELECT Id, Status__c
		                 FROM Sale__c
		                 WHERE Status__c='Attiva'
		                 LIMIT 1];

		HDT_QR_Opportunity oppQr=new HDT_QR_Opportunity();

		string stageName='Negotiation';
		string fields='StageName';


		List<Opportunity> methodRet=oppQr.getRecordsBySaleFilterStageName(saleTst.Id, fields, stageName);

		System.debug('methodRet = '+methodRet);


		System.assertEquals('Negotiation', methodRet[0].StageName, 'Return is wrong');

		System.assertNotEquals('', methodRet[0].StageName, 'Value of parameter is not matching');

		Test.stopTest();
	}

	@isTest
	static void testgetRecordsBySaleFilterStageNameNotVas(){

		Test.startTest();

		Sale__c saleTst=[SELECT Id, Status__c
		                 FROM Sale__c
		                 WHERE Status__c='Attiva'
		                 LIMIT 1];
		
		Order ordTst=[SELECT Id
		FROM Order
		LIMIT 1];

		Opportunity oppTst=[SELECT Id, SBQQ__PrimaryQuote__c
		FROM Opportunity
		LIMIT 1];
		
		List<SBQQ__Quote__c> tQuote= HDT_UTL_DataFactoryTst.createQuote(1, true, ordTst.Id, oppTst.Id, saleTst.Id, 'Quote');
		oppTst.SBQQ__PrimaryQuote__c = tQuote[0].Id;
		update oppTst;


		HDT_QR_Opportunity oppQr=new HDT_QR_Opportunity();

		string stageName='NotNegotiation';
		string fields='StageName';

		List<Opportunity> methodRet=oppQr.getRecordsBySaleFilterStageNameNotVas(saleTst.Id, fields, stageName);

		// Cannot insert IsVas= null, return is always empty

		System.assertEquals(1, methodRet.size(), 'Return is wrong');

		System.assertNotEquals(0, methodRet.size(), 'Value of parameter is not matching');

		Test.stopTest();
	}

	@isTest
	static void testgetRecordById(){

		Test.startTest();

		Opportunity oppTst=[SELECT Id, StageName, SBQQ__PrimaryQuote__c
		                    FROM Opportunity
		                    WHERE StageName='Negotiation'
		                    LIMIT 1];


		HDT_QR_Opportunity oppQr=new HDT_QR_Opportunity();

		Opportunity methodRet=oppQr.getRecordById(oppTst.Id);

		System.debug('methodRet = '+methodRet);


		System.assertEquals('Negotiation', methodRet.StageName, 'Return is wrong');

		System.assertNotEquals('', methodRet.StageName, 'Value of parameter is not matching');

		Test.stopTest();
	}

	@isTest
	static void testgetRecordByIdFilterStatus(){

		Test.startTest();

		Opportunity oppTst=[SELECT Id, StageName, SBQQ__PrimaryQuote__c
		                    FROM Opportunity
		                    WHERE StageName='Negotiation'
		                    LIMIT 1];


		HDT_QR_Opportunity oppQr=new HDT_QR_Opportunity();

		Opportunity methodRet=oppQr.getRecordByIdFilterStatus(oppTst.Id, 'Proposal');

		System.debug('methodRet = '+methodRet);


		System.assertEquals('Negotiation', methodRet.StageName, 'Return is wrong');

		System.assertNotEquals('', methodRet.StageName, 'Value of parameter is not matching');

		Test.stopTest();
	}

	@isTest
	static void testgetRecordsBySaleFilteredVas(){

		Test.startTest();

		Sale__c saleTst=[SELECT Id, Status__c
		                 FROM Sale__c
		                 WHERE Status__c='Attiva'
		                 LIMIT 1];

		HDT_QR_Opportunity oppQr=new HDT_QR_Opportunity();


		List<Opportunity> methodRet=oppQr.getRecordsBySaleFilteredVas(saleTst.Id);

		System.debug('methodRet = '+methodRet);


		System.assertEquals('Roma', methodRet[0].SBQQ__PrimaryQuote__r.SupplyCity__c, 'Return is wrong');

		System.assertNotEquals('0', methodRet[0].SBQQ__PrimaryQuote__r.SupplyCity__c, 'Value of parameter is not matching');

		Test.stopTest();
	}

	@isTest
	static void testgetRecordByQuote(){

		Test.startTest();

		SBQQ__Quote__c quoteTst=[SELECT Id, SBQQ__Type__c
		                         FROM SBQQ__Quote__c
		                         WHERE SBQQ__Type__c='Amendment'
		                         LIMIT 1];

		HDT_QR_Opportunity oppQr=new HDT_QR_Opportunity();


		List<Opportunity> methodRet=oppQr.getRecordByQuote(quoteTst.Id);

		System.debug('methodRet = '+methodRet);


		System.assertEquals(1, methodRet.size(), 'Return is wrong');

		System.assertNotEquals(0, methodRet.size(), 'Value of parameter is not matching');

		Test.stopTest();
	}
}