force-app/main/default/objects/Contact/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/MarketingPrivacy__c.field-meta.xml
<CustomField>
    <fullName>MarketingPrivacy__c</fullName>
    <description>Indica la scelta del cliente riguardo l&apos;essere contattato per scopi di marketing</description>
    <label>Consenso Marketing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>Non espresso</fullName>
                <default>true</default>
                <label>Non espresso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/ProfilingPrivacy__c.field-meta.xml
<CustomField>
    <fullName>ProfilingPrivacy__c</fullName>
    <description>Indica la scelta del cliente riguardo la profilazione dei suoi dati personali</description>
    <label>Consenso Alla Profilazione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>Non espresso</fullName>
                <default>true</default>
                <label>Non espresso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <formula>TEXT(Account.CompanyOwner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contatto Primario</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders (Contatto Primario)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketingPrivacy__c.field-meta.xml
<CustomField>
    <fullName>MarketingPrivacy__c</fullName>
    <label>Consenso Marketing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProfilingPrivacy__c.field-meta.xml
<CustomField>
    <fullName>ProfilingPrivacy__c</fullName>
    <label>Consenso Alla Profilazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SignatureMethod__c.field-meta.xml
<CustomField>
    <fullName>SignatureMethod__c</fullName>
    <label>Metodo Firma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vocal Order</fullName>
            </value>
            <value>
                <fullName>OTP Remoto</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
            </value>
            <value>
                <fullName>OTP Coopresenza</fullName>
            </value>
            <value>
                <fullName>Contratto già firmato</fullName>
            </value>
            <value>
                <fullName>Accettato Digitalmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_LC_AlertPrivacy.cls
public with sharing class HDT_LC_AlertPrivacy {
    public HDT_LC_AlertPrivacy() {

    }
    @AuraEnabled(cacheable=false)
    public static Boolean handleShowAlert(String orderId){
        Boolean result = false;
        Boolean blankMarket = true;
        Boolean blankProfile = true;
        String signatureMethod = '';
        try {
            if(String.IsBlank(orderId))return false;
            List<Order> ordList = [SELECT id,Contact__r.Individual.MarketingPrivacy__c, Contact__r.Individual.ProfilingPrivacy__c,SignatureMethod__c FROM Order WHERE Id =:orderId AND CompanyOwner__c != 'MMS' WITH SECURITY_ENFORCED];
            if(!ordList.isEmpty()){
                if(ordList[0].Contact__r!=null){
                    blankMarket = ordList[0].Contact__r.Individual.MarketingPrivacy__c == 'Non espresso'?true:false;
                    blankProfile = ordList[0].Contact__r.Individual.ProfilingPrivacy__c == 'Non espresso'?true:false;
                    signatureMethod = ordList[0].SignatureMethod__c;
                }
                if(blankMarket && blankProfile && !signatureMethod.contains('OTP')){
                    result = true;
                }
            }
        } catch (Exception e) {
            return false;
        }
        return result;
    }
}