force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Società Silos</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompanyOwner__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>HDT_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMSTracking__c/SMSTracking__c.object-meta.xml
<CustomObject>
    <description>Tracciamento di tutti gli esiti su canale SMS  inviate da Marketing Cloud</description>
    <label>SMS Tracking</label>
    <nameField>
        <displayFormat>STK-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/HDT_Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HC</fullName>
    </customValue>
    <customValue>
        <fullName>HCM</fullName>
    </customValue>
    <customValue>
        <fullName>EENE</fullName>
        <label>NEWCO</label>
    </customValue>
    <customValue>
        <fullName>HSPA</fullName>
    </customValue>
    <customValue>
        <fullName>EB</fullName>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HC+HCM+EENE</fullName>
    </customValue>
    <description>Identifica la società di appartenenza</description>
    <masterLabel>Company</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_SmsTrackingTst.cls
/**
 * Header of the class "HDT_SmsTrackingTs"
 * @author Cesare Bagnolini, cesare.bagnolini@webresults.it
 * @version 1.0
 * @description: Apex Test Class of the relative trigger "HDT_SmsTracking"
 * @history
 * @Created 12/10/2021
 * Modified By:
 **/

@isTest
public class HDT_SmsTrackingTst {
    
    @isTest static void test(){
        
        Test.startTest();
        
        List<Account> accs = HDT_UTL_DataFactoryTst.createAccountBusiness(1,true,'MMS','MMS Azienda','Aziende SME');
        List<Contact> contacts = HDT_UTL_DataFactoryTst.createContact(1,false,accs[0].id);
        contacts[0].Company__c='MMS';
        insert contacts;

        HDT_UTL_DataFactoryTst.createSmsTracking(1, true, contacts[0].id);
        
        List<SMSTracking__c> query = [Select id from SMSTracking__c];

        System.assertEquals(1, query.size(), 'SMSTracking not inserted correctly');

        System.assertNotEquals(null, query, 'SMSTracking not inserted correctly');

        Test.stopTest();
        
    }

}