force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/NewsNotificationCenter__c/NewsNotificationCenter__c.object-meta.xml
<CustomObject>
    <description>Oggetto per la gestione dell&apos;invio delle notifiche alla pubblicazione di una news verso specifici ruoli in base alle DataCategories associate all&apos;articolo di News</description>
    <label>Regola Notifiche News</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regole Notifiche News</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewsNotificationCenter__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Data Category Group Cluster</description>
    <label>Cluster</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Cluster</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NewsNotificationCenter__c/fields/EntryChannel__c.field-meta.xml
<CustomField>
    <fullName>EntryChannel__c</fullName>
    <description>Data Category Group Canale</description>
    <label>Canale</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sportello</fullName>
            </value>
            <value>
                <fullName>Call Center Inbound</fullName>
            </value>
            <value>
                <fullName>SOL e App</fullName>
            </value>
            <value>
                <fullName>Teleselling Outbound</fullName>
            </value>
            <value>
                <fullName>Agenti D2D</fullName>
            </value>
            <value>
                <fullName>Protocollo</fullName>
            </value>
            <value>
                <fullName>Back-office</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Sportello Amministratori Condominio</fullName>
            </value>
            <value>
                <fullName>Tutti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NewsNotificationCenter__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Ruoli a cui inviare notifica</description>
    <label>Ruolo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back Office</fullName>
            </value>
            <value>
                <fullName>Front Office AAA-EBT</fullName>
            </value>
            <value>
                <fullName>Front Office HERA COMM</fullName>
            </value>
            <value>
                <fullName>Front Office MMS</fullName>
            </value>
            <value>
                <fullName>Front Office Reseller</fullName>
            </value>
            <value>
                <fullName>ADDETTO SPORTELLI</fullName>
                <isActive>false</isActive>
                <label>ADDETTO SPORTELLI</label>
            </value>
            <value>
                <fullName>ADDETTO VENDITA CRM</fullName>
                <isActive>false</isActive>
                <label>ADDETTO VENDITA CRM</label>
            </value>
            <value>
                <fullName>Addetto Back Office</fullName>
                <isActive>false</isActive>
                <label>Addetto Back Office</label>
            </value>
            <value>
                <fullName>Addetto Contact Center</fullName>
                <isActive>false</isActive>
                <label>Addetto Contact Center</label>
            </value>
            <value>
                <fullName>Addetto Esercizio Sistemi Clienti</fullName>
                <isActive>false</isActive>
                <label>Addetto Esercizio Sistemi Clienti</label>
            </value>
            <value>
                <fullName>Addetto Gestione del Credito</fullName>
                <isActive>false</isActive>
                <label>Addetto Gestione del Credito</label>
            </value>
            <value>
                <fullName>Addetto Order Management</fullName>
                <isActive>false</isActive>
                <label>Addetto Order Management</label>
            </value>
            <value>
                <fullName>Addetto Processi Transazionali</fullName>
                <isActive>false</isActive>
                <label>Addetto Processi Transazionali</label>
            </value>
            <value>
                <fullName>Addetto Programmazione Operativa e Monitoraggio</fullName>
                <isActive>false</isActive>
                <label>Addetto Programmazione Operativa e Monitoraggio</label>
            </value>
            <value>
                <fullName>Addetto Quality Assurance</fullName>
                <isActive>false</isActive>
                <label>Addetto Quality Assurance</label>
            </value>
            <value>
                <fullName>Addetto Supporto Tecnico Amministrativo</fullName>
                <isActive>false</isActive>
                <label>Addetto Supporto Tecnico Amministrativo</label>
            </value>
            <value>
                <fullName>Addetto Supporto Vendita</fullName>
                <isActive>false</isActive>
                <label>Addetto Supporto Vendita</label>
            </value>
            <value>
                <fullName>COORDINATORE SPORTELLI</fullName>
                <isActive>false</isActive>
                <label>COORDINATORE SPORTELLI</label>
            </value>
            <value>
                <fullName>Coordinatore Contact Center</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Contact Center</label>
            </value>
            <value>
                <fullName>Coordinatore Customer Value Management e Back Office</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Customer Value Management e Back Office</label>
            </value>
            <value>
                <fullName>Coordinatore Esercizio Sistemi Clienti</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Esercizio Sistemi Clienti</label>
            </value>
            <value>
                <fullName>Coordinatore Order Management</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Order Management</label>
            </value>
            <value>
                <fullName>Coordinatore Processi Transazionali</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Processi Transazionali</label>
            </value>
            <value>
                <fullName>Coordinatore Programmazione Operativa e Monitoraggio</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Programmazione Operativa e Monitoraggio</label>
            </value>
            <value>
                <fullName>Coordinatore Quality Assurance</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Quality Assurance</label>
            </value>
            <value>
                <fullName>Coordinatore Reporting</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Reporting</label>
            </value>
            <value>
                <fullName>Coordinatore Supporto Vendita</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Supporto Vendita</label>
            </value>
            <value>
                <fullName>Coordinatore Vendita</fullName>
                <isActive>false</isActive>
                <label>Coordinatore Vendita</label>
            </value>
            <value>
                <fullName>Responsabile Contact Center</fullName>
                <isActive>false</isActive>
                <label>Responsabile Contact Center</label>
            </value>
            <value>
                <fullName>Responsabile Customer Data Operations</fullName>
                <isActive>false</isActive>
                <label>Responsabile Customer Data Operations</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_Cluster.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento</fullName>
    </customValue>
    <customValue>
        <fullName>Attivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Autolettura</fullName>
    </customValue>
    <customValue>
        <fullName>Canone Rai</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Fatturazione</fullName>
    </customValue>
    <customValue>
        <fullName>Indennizzi</fullName>
    </customValue>
    <customValue>
        <fullName>Informative</fullName>
    </customValue>
    <customValue>
        <fullName>Modifiche Anagrafiche</fullName>
    </customValue>
    <customValue>
        <fullName>Morosità</fullName>
    </customValue>
    <customValue>
        <fullName>Notifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Pagamenti</fullName>
    </customValue>
    <customValue>
        <fullName>PostSales VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Preventivi</fullName>
    </customValue>
    <customValue>
        <fullName>Reclami</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>Variazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Verifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
        <isActive>false</isActive>
        <label>Ambiente</label>
    </customValue>
    <customValue>
        <fullName>Generiche Attivazioni</fullName>
        <isActive>false</isActive>
        <label>Generiche Attivazioni</label>
    </customValue>
    <customValue>
        <fullName>Generiche VAS</fullName>
        <isActive>false</isActive>
        <label>Generiche VAS</label>
    </customValue>
    <customValue>
        <fullName>HERA</fullName>
        <isActive>false</isActive>
        <label>HERA</label>
    </customValue>
    <masterLabel>Cluster</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_NewsNotificationCenter.cls
public inherited sharing class HDT_UTL_NewsNotificationCenter {

    private static HDT_QR_Knowledge qrKb = new HDT_QR_Knowledge();

    /*
    * @Author: Salvatore A. Sarà 19/10/2021
    * Risoluzione "Debug Should Use Logging Level"
    * Risoluzione "Avoid debug statements since they impact on performance"
    * Risoluzione "Local variable is declared and-or assigned but not used"
    */
    @SuppressWarnings('PMD.AvoidDebugStatements')
    public static String sendNotification(Knowledge__kav article){

        List<String> rolesToNotificate = new List<String>();
        List<String> userToNotificate = new List<String>();
        List<Knowledge__DataCategorySelection> dataCategories = new List<Knowledge__DataCategorySelection>();
        List<NewsNotificationCenter__c> newsList = new List<NewsNotificationCenter__c>();

        Set<String> userSet = new Set<String>();
        Set<String> clusterSet = new Set<String>();
        Set<String> channelSet = new Set<String>();

        String title;
        /*
			@Author: Davide Viola - 20/10/2021
			Description: PMD -> Commentata variabile non utilizzata.
		*/
		//String body;
        String result;
        String rolesString = '';


        try{
            
            dataCategories = qrKb.getDataCategories(article.Id);
		
        } catch(Exception e){

            System.debug(LoggingLevel.DEBUG, e.getMessage());

        }

        if(dataCategories.size() > 0){
        
        
            for(Knowledge__DataCategorySelection dataCategory : dataCategories){
    
                if(dataCategory.DataCategoryGroupName == 'Cluster'){
    
                    clusterSet.add(dataCategory.DataCategoryName);
    
                }else if(dataCategory.DataCategoryGroupName == 'Canale'){
    
                    channelSet.add(dataCategory.DataCategoryName);
    
                }
    
            }

    
            newsList= qrKb.getRolesToNotificate();

            //Populate roleList
            //First checks Cluster form data cateogries and from query
            //Than checks EntryChannel from data categories and from query
            //If all check are succesfully roles are added to list 'rolesToNotificate'
            if(newsList.size() > 0){
                Set<String> tmpCluster = new Set<String>();
                Set<String> tmpChannel = new Set<String>();
                Boolean retainAllResult;
                for(NewsNotificationCenter__c news : newsList){ 
                    tmpCluster = clusterSet;
                    tmpChannel = channelSet;
                    Set<String> returnedCluster = new Set<String>(news.Cluster__c.split(';'));
                    Set<String> returnedChannel = new Set<String>(news.EntryChannel__c.split(';'));
                    retainAllResult = tmpCluster.retainAll(returnedCluster);
                    if((retainAllResult && tmpCluster.size() > 0) || (!retainAllResult)){
                        retainAllResult = tmpChannel.retainAll(returnedChannel);
                        if((retainAllResult && tmpChannel.size() > 0) || (!retainAllResult) || news.EntryChannel__c.containsIgnoreCase('Tutti')){
                            rolesString += news.Role__c;
                        }else{
                            System.debug(LoggingLevel.DEBUG, 'Rule Not Found');
                        }
                    }else{
                        System.debug(LoggingLevel.DEBUG, 'Rule Not Found');
                    }
                    
                }
            
                rolesToNotificate = rolesString.split(';');
        
                userToNotificate = qrKb.getUserIdToNotificate(rolesToNotificate);
        
                userSet.addAll(userToNotificate);
                
                if(!Test.isRunningTest())
                {
                    Id jobId = Database.executeBatch(new HDT_BA_Knowledge(userSet, article.Id, article.Title), 200);
                }
            }
        }
        

        return null;


        }


    public static String fireNotification(String title, String body, String recordId, Set<String> userToNotificate){

        CustomNotificationType notificationType = qrKb.getCustomNotificationType();

        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        
        notification.setTitle(title);
        notification.setBody(body);
        notification.setNotificationTypeId(notificationType.Id);
        notification.setTargetId(recordId);
        notification.send(userToNotificate);

        return null;

    }

    @InvocableMethod(Label = 'Batch Notifiche News')
    public static List<HDT_UTL_FlowOutputs> sendNotificationFromFlow(List<HDT_UTL_FlowInputs> inputs)
    {
        List<HDT_UTL_FlowOutputs> outputs = new List<HDT_UTL_FlowOutputs>();

        Knowledge__kav article = inputs[0].article;
        sendNotification(article);

        return outputs;
    }
    
    public class HDT_UTL_FlowInputs
    {
        @InvocableVariable
        public Knowledge__kav article;
    }
    public class HDT_UTL_FlowOutputs
    {
        @InvocableVariable
        public String output;    
    }


}