force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributore</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities (Custom) (Distributore)</relationshipLabel>
    <relationshipName>Activities_Custom1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/isUserActivity__c.field-meta.xml
<CustomField>
    <fullName>isUserActivity__c</fullName>
    <formula>IF( $User.Id ==  OwnerId , true,false )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attività Utente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HDT_LC_AppointmentExtraSist.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public with sharing class HDT_LC_AppointmentExtraSist {
    @AuraEnabled(cacheable = true)
    public static String getLink(String recordId){
        List <wrts_prcgvr__Activity__c> listAct=new list <wrts_prcgvr__Activity__c>();
        listAct=HDT_QR_GenericQuery.getGenericRecords('Distributor__r.Name', 'wrts_prcgvr__Activity__c', 'Id = \''+String.escapeSingleQuotes(recordId)+'\'');
        system.debug(LoggingLevel.DEBUG,'@@@lista  ' + listAct[0].Distributor__r.Name);
        Map<String,String> response = new Map<String,String>();
        if(listAct!=null && listAct.size()!=0 && string.isNotBlank(listAct[0].Distributor__r.Name)){
            response=HDT_UTL_AppointmentSetting.getQuickLink(listAct[0].Distributor__r.Name);
            if(response.containsKey('link')){
                System.debug(LoggingLevel.DEBUG,'@@@Link '+response.get('link'));
            }
            else if(response.containsKey('errorMessage')) {
                System.debug(LoggingLevel.DEBUG,'@@@Error '+response.get('errorMessage'));
            }
            return JSON.serialize(response);
        }
        else {
            return null;
        }
    }

    @AuraEnabled(cacheable = true)
    public static String getActivity(String activityId,List<String> fields){
        if (String.isNotBlank(activityId)){
            Map<String,Object> response = new Map<String,Object>();
            String fieldsToString = String.join(fields,',');
            if (!fieldsToString.containsIgnoreCase('isUserActivity__c')){
                fieldsToString += ',isUserActivity__c';
            }
            try{
                wrts_prcgvr__Activity__c activity = HDT_UTL_AppointmentAgenda.getActivity(activityId, fieldsToString);
                response.put('activity',activity);
                response.put('isNotOwner',activity.isUserActivity__c); 
            }catch (Exception e){
                throw new AuraException(e.getMessage());
            }
            return JSON.serialize(response);
        }
        return null;
    }
    @AuraEnabled
    public static Boolean getActivityOwner(String activityId){
        try{
            String fieldsToString = 'Id,isUserActivity__c';
            wrts_prcgvr__Activity__c activity = HDT_UTL_AppointmentAgenda.getActivity(activityId, fieldsToString);
            
            return !activity.isUserActivity__c;
        }
        catch(Exception e){
            throw new AuraException(e.getMessage());
        }
    }
}