force-app/main/default/objects/DocumentalPayloadAdministration__c/DocumentalPayloadAdministration__c.object-meta.xml
<CustomObject>
    <label>Amministrazione Payload Documentale</label>
    <nameField>
        <displayFormat>APLD-{0000}</displayFormat>
        <label>Amministrazione Payload</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amministrazione Payload Documentale</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Classe Apex</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Context1__c.field-meta.xml
<CustomField>
    <fullName>Context1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Context2__c.field-meta.xml
<CustomField>
    <fullName>Context2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Context3__c.field-meta.xml
<CustomField>
    <fullName>Context3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Context4__c.field-meta.xml
<CustomField>
    <fullName>Context4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estratto Conto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/DefaultValue__c.field-meta.xml
<CustomField>
    <fullName>DefaultValue__c</fullName>
    <label>Default</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Expression__c.field-meta.xml
<CustomField>
    <fullName>Expression__c</fullName>
    <label>Espressione Regolare</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>Field 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Field2__c.field-meta.xml
<CustomField>
    <fullName>Field2__c</fullName>
    <label>Field 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Field3__c.field-meta.xml
<CustomField>
    <fullName>Field3__c</fullName>
    <label>Field 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Field4__c.field-meta.xml
<CustomField>
    <fullName>Field4__c</fullName>
    <label>Field 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/IsData__c.field-meta.xml
<CustomField>
    <fullName>IsData__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Iterative__c.field-meta.xml
<CustomField>
    <fullName>Iterative__c</fullName>
    <label>Iterative</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/ManageAmount__c.field-meta.xml
<CustomField>
    <fullName>ManageAmount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bonifica Importi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Metodo Apex</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Object1__c.field-meta.xml
<CustomField>
    <fullName>Object1__c</fullName>
    <label>sObject 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Object2__c.field-meta.xml
<CustomField>
    <fullName>Object2__c</fullName>
    <label>sObject 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Object3__c.field-meta.xml
<CustomField>
    <fullName>Object3__c</fullName>
    <label>sObject 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Object4__c.field-meta.xml
<CustomField>
    <fullName>Object4__c</fullName>
    <label>sObject 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/OrderPayloadField__c.field-meta.xml
<CustomField>
    <fullName>OrderPayloadField__c</fullName>
    <label>Ordinamento Campi Payload</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/OrderSection__c.field-meta.xml
<CustomField>
    <fullName>OrderSection__c</fullName>
    <label>Ordinamento Sezione</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/PayloadField__c.field-meta.xml
<CustomField>
    <fullName>PayloadField__c</fullName>
    <label>Field Tracciato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Separetor__c.field-meta.xml
<CustomField>
    <fullName>Separetor__c</fullName>
    <label>Separatore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentalPayloadAdministration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo Record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HDT_SignModeSettings__mdt/HDT_SignModeSettings__mdt.object-meta.xml
<CustomObject>
    <label>HDT_SignModeSettings</label>
    <pluralLabel>HDT_SignModeSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_SignModeSettings__mdt/fields/SendMode1__c.field-meta.xml
<CustomField>
    <fullName>SendMode1__c</fullName>
    <label>SendMode1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Mail</fullName>
                <default>true</default>
                <label>E-Mail</label>
            </value>
            <value>
                <fullName>Posta Cartacea</fullName>
            </value>
            <value>
                <fullName>Stampa Cartacea</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_SignModeSettings__mdt/fields/SendMode2__c.field-meta.xml
<CustomField>
    <fullName>SendMode2__c</fullName>
    <label>SendMode2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Mail</fullName>
                <default>true</default>
                <label>E-Mail</label>
            </value>
            <value>
                <fullName>Posta Cartacea</fullName>
            </value>
            <value>
                <fullName>Stampa Cartacea</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_SignModeSettings__mdt/fields/SendMode3__c.field-meta.xml
<CustomField>
    <fullName>SendMode3__c</fullName>
    <label>SendMode3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Mail</fullName>
                <default>true</default>
                <label>E-Mail</label>
            </value>
            <value>
                <fullName>Posta Cartacea</fullName>
            </value>
            <value>
                <fullName>Stampa Cartacea</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_SignModeSettings__mdt/fields/SignMode__c.field-meta.xml
<CustomField>
    <fullName>SignMode__c</fullName>
    <label>SignMode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTP Coopresenza</fullName>
                <default>true</default>
                <label>OTP Coopresenza</label>
            </value>
            <value>
                <fullName>OTP Remoto</fullName>
            </value>
            <value>
                <fullName>Vocal Order</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
            </value>
            <value>
                <fullName>Contratto già firmato</fullName>
            </value>
            <value>
                <fullName>Accettato Digitalmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Sottoprocesso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_OrderProcess</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SignMode__c.field-meta.xml
<CustomField>
    <fullName>SignMode__c</fullName>
    <description>Indica la modalità di firma documentale</description>
    <label>Modalità di firma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_SignMode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_OrderProcess.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To define</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione In delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione Fuori delibera</fullName>
    </customValue>
    <customValue>
        <fullName>Prima Attivazione con modifica</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso</fullName>
    </customValue>
    <customValue>
        <fullName>Connessione con Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Riattivazione non morose</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in con voltura tecnica</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura con Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ripristinatorio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Fittizio</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Winback</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Switch in Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Aggiunta Sconti o Bonus VAS Gas</fullName>
    </customValue>
    <customValue>
        <fullName>VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Temporanea - Nuova Attivazione</fullName>
    </customValue>
    <customValue>
        <fullName>Proroga Temporanea</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Uso Tecnico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Ele</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio Offerta Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Subentro Acqua</fullName>
    </customValue>
    <description>Lista Processi Ordine</description>
    <masterLabel>Processo Ordine</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_SignMode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartacea</fullName>
    </customValue>
    <customValue>
        <fullName>OTP Coopresenza</fullName>
    </customValue>
    <customValue>
        <fullName>OTP Remoto</fullName>
    </customValue>
    <customValue>
        <fullName>Vocal Order</fullName>
    </customValue>
    <customValue>
        <fullName>Contratto già firmato</fullName>
    </customValue>
    <masterLabel>Sign Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_QR_DocumentalConfiguration.cls
public inherited sharing class HDT_QR_DocumentalConfiguration {

    public static List<Document> getDocument(){
        Id folderId = [SELECT Id FROM Folder WHERE DeveloperName  =: 'DocumentalPayloadAdministration' LIMIT 1].Id;
        List<Document> docList = new List<Document>();
        docList = [
            SELECT Id, Name, CreatedDate, LastModifiedDate
            FROM Document
            WHERE FolderId = :folderId
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
        return docList;
    }
    public static List<Document> getDocumentByContext(String context){
        List<Document> docList = [
            SELECT Id, Name, Body
            FROM Document
            WHERE Name =:context
            WITH SECURITY_ENFORCED
        ];
        return docList;
    }

    public static List<DocumentalPayloadAdministration__c> getDocumentalPayloadAdministration(List<DocumentalPayloadAdministration__c> docPayloadAdminList){
        docPayloadAdminList = new List<DocumentalPayloadAdministration__c>();
        docPayloadAdminList = [
            SELECT Class__c, Context1__c, Context2__c, Context3__c, Context4__c, DefaultValue__c, Expression__c,
                   Field1__c, Field2__c, Field3__c, Field4__c, IsData__c, Iterative__c, ManageAmount__c, Method__c,
                   Object1__c, Object2__c, Object3__c, Object4__c, OrderPayloadField__c, OrderSection__c, PayloadField__c,
                   Separetor__c, Type__c
            FROM DocumentalPayloadAdministration__c
            WHERE Type__C != 'TDRV'
            WITH SECURITY_ENFORCED
            ORDER BY OrderSection__c, OrderPayloadField__c
        ];
        return docPayloadAdminList;
    }

    public static List<HDT_SignModeSettings__mdt> getSignModeSettings(String processType,String source){
        return [SELECT Id, ProcessType__c,Source__c,SignMode__c,SendMode1__c,SendMode2__c,SendMode3__c FROM HDT_SignModeSettings__mdt WHERE Source__c =:source AND ProcessType__c=:processType  WITH SECURITY_ENFORCED];
    }

}