force-app/main/default/objects/Activity/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Valorizzato con il SILOS dell&apos;Account.</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_ProtocolSpecificEmail__mdt/HDT_ProtocolSpecificEmail__mdt.object-meta.xml
<CustomObject>
    <label>HDT_ProtocolSpecificEmail</label>
    <pluralLabel>HDT_ProtocolSpecificEmails</pluralLabel>
</CustomObject>

force-app/main/default/objects/HDT_ProtocolSpecificEmail__mdt/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AAA-EBT</fullName>
                <default>true</default>
                <label>AAA-EBT</label>
            </value>
            <value>
                <fullName>HERA COMM</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HDT_ProtocolSpecificEmail__mdt/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HDT_ProtocolSpecificEmail__mdt/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Protocollo - Da tipizzare</fullName>
                <default>true</default>
                <label>Protocollo - Da tipizzare</label>
            </value>
            <value>
                <fullName>Protocollo - Attivazioni</fullName>
            </value>
            <value>
                <fullName>Protocollo - Voltura</fullName>
            </value>
            <value>
                <fullName>Protocollo - VAS</fullName>
            </value>
            <value>
                <fullName>Protocollo - Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Protocollo - Preventivi</fullName>
            </value>
            <value>
                <fullName>Protocollo - Verifiche</fullName>
            </value>
            <value>
                <fullName>Protocollo - Reclami</fullName>
            </value>
            <value>
                <fullName>Protocollo - Pagamenti</fullName>
            </value>
            <value>
                <fullName>Protocollo - Morosità</fullName>
            </value>
            <value>
                <fullName>Protocollo - Canone Rai</fullName>
            </value>
            <value>
                <fullName>Protocollo - Fatturazione</fullName>
            </value>
            <value>
                <fullName>Protocollo - Autolettura</fullName>
            </value>
            <value>
                <fullName>Protocollo - Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Protocollo - Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>Descrizione funzionale dell&apos;oggetto</description>
    <label>Interazione</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Interazione Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo di ricerca per l’Account da collegare all’interazione o creazione nuovo Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interazioni</relationshipLabel>
    <relationshipName>Interazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/BodyEmail__c.field-meta.xml
<CustomField>
    <fullName>BodyEmail__c</fullName>
    <label>Corpo Email</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <label>Company Owner</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo di ricerca per il Contact da collegare all’interazione o creazione nuovo Contact</description>
    <label>Referente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interazioni</relationshipLabel>
    <relationshipName>Interazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/ReceptionDate__c.field-meta.xml
<CustomField>
    <fullName>ReceptionDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Data di ricezione</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/SenderEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>SenderEmailAddress__c</fullName>
    <label>Indirizzo Email Mittente</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/SubjectEmail__c.field-meta.xml
<CustomField>
    <fullName>SubjectEmail__c</fullName>
    <label>Oggetto Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Cartacea</fullName>
                <default>true</default>
                <label>Cartacea</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/wrts_prcgvr__Activity__c.object-meta.xml
<CustomObject>
    <description>Activities are process related events, tasks or calls that have been made or sent</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza.</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Cliente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Dato di contatto cliente canale Email</description>
    <label>Email Self</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Interaction__c.field-meta.xml
<CustomField>
    <fullName>Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interazione</label>
    <referenceTo>Interaction__c</referenceTo>
    <relationshipLabel>Activities (Custom)</relationshipLabel>
    <relationshipName>Activities_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo attività</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accettazione Voltura</fullName>
            </value>
            <value>
                <fullName>Amm. Precheck KO SII</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Anticipo Appuntamento</fullName>
            </value>
            <value>
                <fullName>Approvazione Bonus Commerciale</fullName>
            </value>
            <value>
                <fullName>Approvazione Offerte</fullName>
            </value>
            <value>
                <fullName>Assistenza Contact Center</fullName>
            </value>
            <value>
                <fullName>Attesa Preventivo DL</fullName>
            </value>
            <value>
                <fullName>Attivazioni</fullName>
            </value>
            <value>
                <fullName>Back Office - Catalogo Prodotti</fullName>
            </value>
            <value>
                <fullName>Back Office - Contratti</fullName>
            </value>
            <value>
                <fullName>Back Office - Fatturazione</fullName>
            </value>
            <value>
                <fullName>Back Office - Morosità</fullName>
            </value>
            <value>
                <fullName>Back Office - Pagamenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Preventivi</fullName>
            </value>
            <value>
                <fullName>Back Office - Supporto/Comunicazioni Urgenti</fullName>
            </value>
            <value>
                <fullName>Back Office - Tari/TCP</fullName>
            </value>
            <value>
                <fullName>Back Office - Vas e HVAC</fullName>
            </value>
            <value>
                <fullName>Busta Docusign non consegnata</fullName>
            </value>
            <value>
                <fullName>Caricamenti contratti</fullName>
            </value>
            <value>
                <fullName>Caricamento Manuale Siebel</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Chiamata Callback</fullName>
            </value>
            <value>
                <fullName>Chiamata inbound</fullName>
            </value>
            <value>
                <fullName>Chiamata outbound</fullName>
            </value>
            <value>
                <fullName>Comfort Call</fullName>
            </value>
            <value>
                <fullName>Comunicazione da DL</fullName>
            </value>
            <value>
                <fullName>Comunicazioni con DL</fullName>
            </value>
            <value>
                <fullName>Conferma Preventivo</fullName>
            </value>
            <value>
                <fullName>Protocollo - Da tipizzare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/wrts_prcgvr__Activity__c/recordTypes/HDT_RT_RegisterActivity.recordType-meta.xml
<RecordType>
    <fullName>HDT_RT_RegisterActivity</fullName>
    <active>true</active>
    <description>Activity per tracciare le richieste ricevute da protocollo</description>
    <label>Protocollo</label>
</RecordType>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_EmailProtocolReceiver.cls
public class HDT_UTL_EmailProtocolReceiver implements Messaging.InboundEmailHandler {

    public Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        try {
            HDT_SRV_ContentDocumentLink contentdocumentLink = new HDT_SRV_ContentDocumentLink();
            HDT_SRV_ContentVersion contentSrv = new HDT_SRV_ContentVersion();
            String emailBody;
            Boolean bodyTruncated = false;

            if(email.plainTextBody != null && email.plainTextBody.length() > 31999) {
                emailBody = email.plainTextBody.left(31999);
                bodyTruncated = true;
            } else {
                emailBody = email.plainTextBody;
            }

            Map<String,HDT_ProtocolSpecificEmail__mdt> mapEmailObj = new Map<String,HDT_ProtocolSpecificEmail__mdt>();
            for(HDT_ProtocolSpecificEmail__mdt specificEmail : HDT_ProtocolSpecificEmail__mdt.getAll().values()) {
                mapEmailObj.put(specificEmail.Email__c.toUpperCase(), specificEmail);
            }
            HDT_ProtocolSpecificEmail__mdt specificEmail = mapEmailObj.get(toAddress.toUpperCase());

            Interaction__c interaction = new Interaction__c(
                Type__c = 'Digital',
                ReceptionDate__c = Date.today(),
                BodyEmail__c = emailBody,
                SubjectEmail__c = email.subject,
                SenderEmailAddress__c = email.fromAddress,
                CompanyOwner__c =  specificEmail.CompanyOwner__c
            );

            List<ContentVersion> listContent = new List<ContentVersion>();
            List<Contact> contacts = new HDT_QR_Contact().getContactByEmailAddress(email.fromAddress);
            if(contacts.size() == 1) {
                interaction.Contact__c = contacts[0].Id;
                interaction.Account__c = contacts[0].AccountId;
            }
            interaction = new HDT_SRV_Interaction().createRecord(interaction);

            if(bodyTruncated) {
                HDT_UTL_Note.createNoteAndAssign(interaction.id, 'Testo Troncato per Superamento Limite Caratteri', '');
            }

            if(email.textAttachments != null) {
                for (Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
                    ContentVersion content = contentSrv.createRecordNoInsert(tAttachment.fileName,tAttachment.fileName,tAttachment.body);
                    //content.ParentId = interaction.Id;
                    listContent.add(content);
                }
            }
            if(email.binaryAttachments != null) {
                for (Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
                    ContentVersion content = contentSrv.createRecordNoInsert(bAttachment.fileName,bAttachment.fileName,bAttachment.body);
                    //content.ParentId = interaction.Id;
                    listContent.add(content);
                }
            }
            if(!listContent.isEmpty()) {
                listContent = contentSrv.insertRecords(listContent);
            }
            List<ContentDocumentLink> contentDocumentList = new List<ContentDocumentLink>();
            List<String> idContentVersion = new List<String>();
            for(ContentVersion cv : listContent) {
                idContentVersion.add(cv.id);
            }
            if(!listContent.isEmpty()) {
                List<ContentVersion> contentWithDocument = new HDT_QR_ContentVersion().getRecordByIds(idContentVersion);
                for(ContentVersion cv : contentWithDocument) {
                    contentDocumentList.add(contentdocumentLink.createRecordNoInsert(interaction.Id, cv.ContentDocumentId, 'I'));
                }
                contentdocumentLink.insertRecords(contentDocumentList);
            }

            String toAddress = email.toAddresses == null || email.toAddresses.isEmpty() ? null : email.toAddresses[0];
            EmailMessage newEmail = new EmailMessage(
                FromAddress = email.fromAddress,
                FromName = email.fromName,
                ToAddress = toAddress,
                Subject = email.subject,
                TextBody = emailBody,
                //HtmlBody = email.htmlBody,
                relatedToId = interaction.Id ,
                status = '0'
            );
            HDT_SRV_EmailMessage.insertEmailMessage(newEmail);

            wrts_prcgvr__Activity__c activity = new wrts_prcgvr__Activity__c(
                Interaction__c = interaction.Id,
                RecordTypeId = new HDT_QR_RecordType().getRecordTypeIdByName('HDT_RT_RegisterActivity'),
                Account__c = interaction.Account__c,
                Contact__c = interaction.Contact__c,
                Type__c = specificEmail.Type__c,
                CompanyOwner__c = specificEmail.CompanyOwner__c
            );

            if(activity.Account__c == null) {
                activity.Type__c = 'Protocollo - Da tipizzare';
            }

            new HDT_SRV_ActivityCustom().createRecord(activity);
        } catch (Exception e) {
            e.setMessage(e.getMessage() + ' at line ' + e.getLineNumber());
            throw e;
        }
        return null;
    }
}