force-app/main/default/objects/Activity/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Valorizzato con il SILOS dell&apos;Account.</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo di tracciamento per identificare l&apos;Activity responsabile della creazione del record.</description>
    <label>Attività</label>
    <referenceTo>wrts_prcgvr__Activity__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Nome del Cluster a cui appartiene un processo.</description>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annullamento</fullName>
            </value>
            <value>
                <fullName>Canone Rai</fullName>
            </value>
            <value>
                <fullName>Disattivazioni</fullName>
            </value>
            <value>
                <fullName>Fatturazione</fullName>
            </value>
            <value>
                <fullName>Modifiche Anagrafiche</fullName>
            </value>
            <value>
                <fullName>Notifiche</fullName>
            </value>
            <value>
                <fullName>Pagamenti</fullName>
            </value>
            <value>
                <fullName>Preventivi</fullName>
            </value>
            <value>
                <fullName>Verifiche</fullName>
            </value>
            <value>
                <fullName>Voltura</fullName>
            </value>
            <value>
                <fullName>Reclami</fullName>
            </value>
            <value>
                <fullName>Autolettura</fullName>
            </value>
            <value>
                <fullName>Informative</fullName>
            </value>
            <value>
                <fullName>Morosità</fullName>
            </value>
            <value>
                <fullName>Variazioni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <description>Identifica la company di appartenenza</description>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data Fine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordine</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Inizio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/SlaAdministration__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione, dove sono definiti gli SLA ed il relativo contesto di applicazione</description>
    <label>Amministrazione SLA</label>
    <nameField>
        <label>Nome SLA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amministrazione SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SlaAdministration__c/fields/CaseField__c.field-meta.xml
<CustomField>
    <fullName>CaseField__c</fullName>
    <label>Campo case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Inserimento Richiesta</fullName>
            </value>
            <value>
                <fullName>Data Ricezione Richiesta</fullName>
            </value>
            <value>
                <fullName>Data Pagamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_Cluster</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/CompanyOwner__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwner__c</fullName>
    <label>Company Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HDT_CompanyOwner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrizione SLA</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/EndCasePhase__c.field-meta.xml
<CustomField>
    <fullName>EndCasePhase__c</fullName>
    <label>Fase Case fine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acconto Paperless Non Pagato</fullName>
            </value>
            <value>
                <fullName>Acconto Paperless Pagato</fullName>
            </value>
            <value>
                <fullName>Allineamento RCU Concluso</fullName>
            </value>
            <value>
                <fullName>Ammissibilità KO</fullName>
            </value>
            <value>
                <fullName>Ammissibilità OK</fullName>
            </value>
            <value>
                <fullName>Annullato</fullName>
            </value>
            <value>
                <fullName>Approvazione KO</fullName>
            </value>
            <value>
                <fullName>Approvazione OK</fullName>
            </value>
            <value>
                <fullName>Attesa check preliminari</fullName>
            </value>
            <value>
                <fullName>Attesa conferma preventivo cliente</fullName>
            </value>
            <value>
                <fullName>Attesa Info da Banca</fullName>
            </value>
            <value>
                <fullName>Avvenuta Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>BL010</fullName>
            </value>
            <value>
                <fullName>Bozza</fullName>
            </value>
            <value>
                <fullName>Check preliminari KO</fullName>
            </value>
            <value>
                <fullName>Check preliminari OK</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
            <value>
                <fullName>Completata</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku KO</fullName>
            </value>
            <value>
                <fullName>Comunicazione verso Heroku OK</fullName>
            </value>
            <value>
                <fullName>Da Inviare</fullName>
            </value>
            <value>
                <fullName>Da inviare a SAP</fullName>
            </value>
            <value>
                <fullName>Data Esecuzione Prevista</fullName>
            </value>
            <value>
                <fullName>Elaborazione Manuale</fullName>
            </value>
            <value>
                <fullName>E-Mail Inviata</fullName>
            </value>
            <value>
                <fullName>E-Mail Non Inviata</fullName>
            </value>
            <value>
                <fullName>Errore Lavorazione SAP</fullName>
            </value>
            <value>
                <fullName>Esito KO Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>Esito OK Riduzione Potenza</fullName>
            </value>
            <value>
                <fullName>Esito KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data fine validità</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/OrderField__c.field-meta.xml
<CustomField>
    <fullName>OrderField__c</fullName>
    <label>Campo Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data consenso E-mail PEC Invio Bolletta</fullName>
            </value>
            <value>
                <fullName>Data inizio Validità Codice Destinatario</fullName>
            </value>
            <value>
                <fullName>Data invio richiesta</fullName>
            </value>
            <value>
                <fullName>Data decorrenza</fullName>
            </value>
            <value>
                <fullName>Data differita</fullName>
            </value>
            <value>
                <fullName>Data lettura Attuale</fullName>
            </value>
            <value>
                <fullName>Data lettura retroattiva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlaAdministration__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data inizio validità</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/SlaTracking__c.object-meta.xml
<CustomObject>
    <label>Tracciamento SLA</label>
    <nameField>
        <displayFormat>SLA-{0000}</displayFormat>
        <label>Tracciamento SLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracciamento SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SlaTracking__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>wrts_prcgvr__Activity__c</referenceTo>
    <relationshipLabel>Tracciamento SLA</relationshipLabel>
    <relationshipName>SlaTrackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Tracciamento SLA</relationshipLabel>
    <relationshipName>SlaTrackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>SlaAdministration__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descrizione</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <inlineHelpText>Data effettiva di fine lavorazione</inlineHelpText>
    <label>Data fine intervallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Tracciamento SLA</relationshipLabel>
    <relationshipName>SlaTrackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/SlaAdministration__c.field-meta.xml
<CustomField>
    <fullName>SlaAdministration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Amministrazione SLA</label>
    <referenceTo>SlaAdministration__c</referenceTo>
    <relationshipLabel>Tracciamento SLA</relationshipLabel>
    <relationshipName>SlaTrackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/SlaName__c.field-meta.xml
<CustomField>
    <fullName>SlaName__c</fullName>
    <formula>SlaAdministration__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome SLA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Data inizio intervallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SlaTracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aperto</fullName>
            </value>
            <value>
                <fullName>Chiuso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/HDT_Cluster.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annullamento</fullName>
    </customValue>
    <customValue>
        <fullName>Attivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Autolettura</fullName>
    </customValue>
    <customValue>
        <fullName>Canone Rai</fullName>
    </customValue>
    <customValue>
        <fullName>Disattivazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Fatturazione</fullName>
    </customValue>
    <customValue>
        <fullName>Indennizzi</fullName>
    </customValue>
    <customValue>
        <fullName>Informative</fullName>
    </customValue>
    <customValue>
        <fullName>Modifiche Anagrafiche</fullName>
    </customValue>
    <customValue>
        <fullName>Morosità</fullName>
    </customValue>
    <customValue>
        <fullName>Notifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Pagamenti</fullName>
    </customValue>
    <customValue>
        <fullName>PostSales VAS</fullName>
    </customValue>
    <customValue>
        <fullName>Preventivi</fullName>
    </customValue>
    <customValue>
        <fullName>Reclami</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>Variazioni</fullName>
    </customValue>
    <customValue>
        <fullName>Verifiche</fullName>
    </customValue>
    <customValue>
        <fullName>Voltura</fullName>
    </customValue>
    <customValue>
        <fullName>Ambiente</fullName>
        <isActive>false</isActive>
        <label>Ambiente</label>
    </customValue>
    <customValue>
        <fullName>Generiche Attivazioni</fullName>
        <isActive>false</isActive>
        <label>Generiche Attivazioni</label>
    </customValue>
    <customValue>
        <fullName>Generiche VAS</fullName>
        <isActive>false</isActive>
        <label>Generiche VAS</label>
    </customValue>
    <customValue>
        <fullName>HERA</fullName>
        <isActive>false</isActive>
        <label>HERA</label>
    </customValue>
    <masterLabel>Cluster</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HDT_CompanyOwner.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA-EBT</fullName>
    </customValue>
    <customValue>
        <fullName>HERA COMM</fullName>
        <label>Gruppo Hera</label>
    </customValue>
    <customValue>
        <fullName>MMS</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <description>Identifica la company di appartenenza</description>
    <masterLabel>Company Owner</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HDT_UTL_SlaManagement.cls
@SuppressWarnings('PMD.AvoidDebugStatements, PMD.ClassNamingConventions, PMD.ExcessiveParameterList, PMD.IfElseStmtsMustUseBraces, PMD.IfStmtsMustUseBraces, PMD.LocalVariableNamingConventions')
public inherited sharing class HDT_UTL_SlaManagement {
    
    private Set<Id> recordIdList;
    private List<HDT_WRP_SlaManagement.HDT_WRP_sObject> wrpCaseList;
    private List<SlaTracking__c> trackingRecordsList;
    private Map<Id, HDT_WRP_SlaManagement.HDT_WRP_sObject> wrpEventObjMap;

    public HDT_UTL_SlaManagement() {
        System.debug('>>> HDT_UTL_SlaManagement...');
    }

    public void setChangedObjList(Map<Id, HDT_WRP_SlaManagement.HDT_WRP_sObject> wrpEventObjMap){
        this.wrpCaseList = wrpEventObjMap.values();
        recordIdList = wrpEventObjMap.keySet();
    }
    
    public void execute(){

        try{

            List<SlaTracking__c> trackToUpsert = new List<SlaTracking__c>();
            Map<Id, List<SlaTracking__c>> trackingMap = new Map<Id, List<SlaTracking__c>>();
            Map<Id, HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin> wrpAdminMap = new Map<Id, HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin>();

            trackingRecordsList = new List<SlaTracking__c>();
            getTrackingRecords();

            if(trackingRecordsList.size() > 0){
                for(SlaTracking__c track : trackingRecordsList){
                    if(trackingMap.containsKey(track.Case__c)){
                        trackingMap.get(track.Case__c).add(track);
                    } else {
                        trackingMap.put(track.Case__c, new List<SlaTracking__c>{track});
                    }
                    
                }
            }

            List<HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin> wrpAdminList = buildSlaRules('HDT_RT_CaseSLA');

            for(HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin wrpAdmin : wrpAdminList){
                wrpAdminMap.put(wrpAdmin.slaAdminId, wrpAdmin);
            }

            HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin wrpAdmin;
            String startField;
            String endField;

            SlaTracking__c currentTrack;
            for(HDT_WRP_SlaManagement.HDT_WRP_sObject eventObj : wrpCaseList){
                
                if(trackingMap.containsKey(eventObj.recordId)){

                    List<SlaTracking__c> trackingList = trackingMap.get(eventObj.recordId);
                    Set<Id> adminIds = new Set<Id>();

                    for(SlaTracking__c track : trackingMap.get(eventObj.recordId)){
                        System.debug('>>> checking trckSla: ' + track.Id);
                        adminIds.add(track.SlaAdministration__c);

                        if(wrpAdminMap.containsKey(track.SlaAdministration__c) && track.Status__c.equalsIgnoreCase('Aperto')){

                            System.debug('>>> update existing sla....');
                            track = updateTrackingRecord(track, wrpAdminMap.get(track.SlaAdministration__c), eventObj);
                            if(track != null){
                                System.debug('>>> add new track...');
                                trackToUpsert.add(track);
                            }

                        }
                    }

                    // check for new tracking record to insert
                    System.debug('>>> check for new tracking record to insert...');
                    for(Id adminRuleId : wrpAdminMap.keySet()){
                        if(!adminIds.contains(adminRuleId)){
                            /// check if this rule have to create new tracking record
                            System.debug('>>> check if this rule have to create new tracking record...');
                            currentTrack = createNewTrackingRecord(currentTrack, wrpAdminMap.get(adminRuleId), eventObj);
                            if(currentTrack != null){
                                System.debug('>>> add new track...');
                                trackToUpsert.add(currentTrack);
                            }
                        }
                    }

                } else {
                    System.debug('>>> no record...');
                }

            }

            if(trackToUpsert.size() > 0){
                System.debug('>>> ' + String.valueOf(trackToUpsert));
                upsert trackToUpsert;
            }
            
            sendCustomNotification('ok');

        } catch(Exception e){
            System.debug('>>> Exception ' + e.getMessage() + ' at line ' + String.valueOf(e.getLineNumber()));
            sendCustomNotification(e.getMessage());
        }
    }

    public void getTrackingRecords(){
        trackingRecordsList = [
            SELECT Id, Activity__c, SlaAdministration__c, Case__c, EndDateTime__c, StartDateTime__c, Description__c,
                   SlaName__c, Order__c, Status__c, Name
            FROM SlaTracking__c
            WHERE Case__c IN :recordIdList
        ];
    }

    public static List<HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin> buildSlaRules(String slaRuleType){
        
        List<HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin> slaAdminRules = new List<HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin>();

        List<SlaAdministration__c> slaAdminList = [ 
            SELECT Id, CaseField__c, OrderField__c, Cluster__c, CompanyOwner__c, CreatedById, EndDate__c, StartDate__c,
                   Description__c, EndCasePhase__c, StartCasePhase__c, Range__c, LastModifiedById, Name, OwnerId, Process__c,
                   RecordTypeId, Commodity__c, SalesCompany__c, CustomerType__c, RangeType__c, Type__c
            FROM SlaAdministration__c
            WHERE RecordType.DeveloperName = :slaRuleType
            AND IsActive__c = true
        ];

        if(slaAdminList.size() == 0){
            return slaAdminRules;
        }

        HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin slaMgmt;
        for(SlaAdministration__c slaAdmin : slaAdminList){
            slaMgmt = new HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin();
            slaMgmt = buildSingleRule(slaMgmt, slaAdmin);
            slaAdminRules.add(slaMgmt);
        }

        return slaAdminRules;

    }

    public static HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin buildSingleRule(HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin slaMgmt, SlaAdministration__c slaAdmin){

        slaMgmt.slaAdminId = slaAdmin.Id;

        switch on slaAdmin.Type__c {
            when '01' {
                // Transizione Fasi Case
                slaMgmt.startRule.isDate = false;
                slaMgmt.startRule.obj = 'Case';
                //slaMgmt.startRule.field = 'Phase__c';
                slaMgmt.startRule.field = 'Status';
                slaMgmt.startRule.value = slaAdmin.StartCasePhase__c;

                slaMgmt.endRule.isDate = false;
                slaMgmt.endRule.obj = 'Case';
                //slaMgmt.endRule.field = 'Phase__c';
                slaMgmt.endRule.field = 'Status';
                slaMgmt.endRule.value = slaAdmin.EndCasePhase__c;
            }	
            when '02' {
                // Data presente sul Case –> Apertura Activity
                slaMgmt.startRule.isDate = true;
                slaMgmt.startRule.obj = 'Case';
                slaMgmt.startRule.field = slaAdmin.CaseField__c;
                slaMgmt.startRule.value = '';

                slaMgmt.endRule.isDate = true;
                slaMgmt.endRule.obj = 'Activity';
                slaMgmt.endRule.field = '';
                slaMgmt.endRule.value = '';
            }
            when '03' {
                // Data presente sul Case –> Chiusura Activity
            }	
            when '04' {
                // Data presente sul Case –> Fase Case
            }
        }

        return slaMgmt;
    }

    public static SlaTracking__c updateTrackingRecord(SlaTracking__c currentTrack, HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin singleRule, HDT_WRP_SlaManagement.HDT_WRP_sObject eventObj){

        if(singleRule.endRule.obj.equalsIgnoreCase('Case')){
            String endField = String.valueOf(eventObj.fieldMap.get(singleRule.endRule.field));

            if(endField.equalsIgnoreCase(singleRule.endRule.value)){
                System.debug('>>> update...');
                Object objField = eventObj.fieldMap.get('LastModifiedDate');
                currentTrack.EndDateTime__c = Datetime.valueOf(objField);
                currentTrack.Status__c = 'Chiuso';
            } else {
                return null;
            }

        } else {
            return null;
        }
        return currentTrack;
    }

    public static SlaTracking__c createNewTrackingRecord(SlaTracking__c currentTrack, HDT_WRP_SlaManagement.HDT_WRP_SlaAdmin singleRule, HDT_WRP_SlaManagement.HDT_WRP_sObject eventObj){

        System.debug('>>> check this rule ' + singleRule.slaAdminId);

        if(eventObj.fieldMap.containsKey(singleRule.startRule.field)){

            System.debug('>>> startRule.field: ' +singleRule.startRule.field);
            currentTrack = new SlaTracking__c();
            currentTrack.Status__c = 'Aperto';
            currentTrack.Case__c = eventObj.recordId;
            currentTrack.SlaAdministration__c = singleRule.slaAdminId;

            Object dt;
            if(singleRule.startRule.isDate){
                System.debug('>>> isDate -> ' + singleRule.startRule.field);
                if(!eventObj.fieldMap.containsKey(singleRule.startRule.field)){
                    return null;  
                }
                dt = eventObj.fieldMap.get(singleRule.startRule.field);
            } else {
                System.debug('>>> isNotDate -> ' + singleRule.startRule.field);
                String startField = String.valueOf(eventObj.fieldMap.get(singleRule.startRule.field));
                if(startField.equalsIgnoreCase(singleRule.startRule.value)){
                    dt = eventObj.fieldMap.get('LastModifiedDate');
                } else {
                    return null;
                }
            }

            currentTrack.StartDateTime__c = Datetime.valueOf(dt);
            
        }
        return currentTrack;

    }

    public static void sendCustomNotification(String message){

        try{
            Id typeId = [SELECT Id FROM CUstomNotificationType LIMIT 1].Id;
            Id userId = '0051X0000055rbNQAQ';
            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            notification.setTitle('Event notification');
            notification.setBody(message);
            notification.setSenderId(userId);
            notification.setNotificationTypeId(typeId);
            notification.setTargetId(userId);
            notification.send(new Set<String> {userId});
        } catch(Exception ex){
            System.debug(logginglevel.DEBUG, '>>> somethig goes wrong with comunication: ' + ex.getMessage() + ' [' + String.valueOf(ex.getLineNumber()) + ']');
        }

    }

}