force-app/main/default/objects/DiscardAnnullmentRule__c/DiscardAnnullmentRule__c.object-meta.xml
<CustomObject>
    <description>Tabella di configurazione per l&apos;annullamento automatico degli scarti</description>
    <label>Regola Annullamento Scarto</label>
    <nameField>
        <displayFormat>DAR-{0000}</displayFormat>
        <label>Regola Annullamento Scarto Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regola Annullamento Scarto</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DiscardAnnullmentRule__c/fields/ControllingValue__c.field-meta.xml
<CustomField>
    <fullName>ControllingValue__c</fullName>
    <description>Valore da utilizzare per il controllo sulla causale di annullamento</description>
    <label>Valore controllante</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_TRH_DiscardAnnullmentRule.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public with sharing class HDT_TRH_DiscardAnnullmentRule extends HDT_TRH_TriggerHandler {
    
    protected override void beforeInsert() {
        validateDiscardText();
    }

    protected override void beforeUpdate() {
        validateDiscardText();
    }

    /**
     * Validazione e normalizzazione del testo inserito come nota dello scarto.
     */
    private void validateDiscardText() {

        for (DiscardAnnullmentRule__c rule : (List<DiscardAnnullmentRule__c>) Trigger.new) {
            if (String.isNotBlank(rule.ControllingValue__c)) {

                if (!rule.ControllingValue__c.contains(' ')) {
                    rule.addError('La nota dello scarto deve contenere almeno due parole.');
                } else {
                    rule.ControllingValue__c = HDT_UTL_Accents.removeDiacritics(rule.ControllingValue__c);
                }
            }
        }

    }

}